import type { StaticSougouPageSeed } from "./sougou-static-common";

export const STATIC_SOUGOU_PAGES_1_3: Record<number, StaticSougouPageSeed> = {
  1: {
    // frontmatter không gắn vào một mục chương cụ thể
    sectionCode: "frontmatter",
    content_blocks: [
      {
        type: "heading",
        level: 1,
        jp: "巻頭ガイド　科学的管理法",
        vi: "Hướng dẫn đầu sách — Phương pháp quản lý khoa học",
        explanation_vi: "Đây là tờ sơ đồ tổng quan đặt trước trang 1 của sách. Giữ riêng như phần hướng dẫn đầu sách, không trộn vào các câu hỏi.",
      },
      {
        type: "image_placeholder",
        caption_jp: "科学的管理法の全体図（原本 IMG_6400）",
        caption_vi: "Sơ đồ tổng quan về phương pháp quản lý khoa học",
        explanation_vi: "Giữ đúng vị trí của sơ đồ gốc; sẽ chèn ảnh gốc sau. Nội dung chính liên kết các khái niệm quản lý, giám sát, quản lý thi công, quy trình quản lý, an toàn lao động và các tiêu chuẩn/pháp quy liên quan.",
      },
      {
        type: "heading",
        level: 2,
        jp: "令和8年度電気工事施工管理技術者検定試験要綱",
        vi: "Đề cương kỳ thi Kỹ thuật quản lý thi công điện năm Reiwa 8 (2026)",
        explanation_vi: null,
      },
      {
        type: "heading",
        level: 3,
        jp: "2級　電気工事施工管理技術検定試験日程",
        vi: "Lịch thi 2級 Điện công trình",
        explanation_vi: null,
      },
      {
        type: "table",
        headers_jp: ["項目", "日程"],
        rows_jp: [
          ["願書受付日", "令和8年7月13日（月）～7月27日（月）"],
          ["試験日", "令和8年11月8日（日）"],
          ["合格発表", "一次：令和8年12月21日（月）／二次：令和9年2月5日（金）"],
          ["合格証明書受付・交付", "合格通知書にて確認"],
        ],
        headers_vi: ["Mục", "Thời gian"],
        rows_vi: [
          ["Nhận hồ sơ dự thi", "13/07/2026 (Thứ Hai) – 27/07/2026 (Thứ Hai)"],
          ["Ngày thi", "08/11/2026 (Chủ Nhật)"],
          ["Công bố kết quả", "Lần 1: 21/12/2026 / Lần 2: 05/02/2027"],
          ["Tiếp nhận/cấp giấy chứng nhận đỗ", "Xác nhận theo thông báo trúng tuyển"],
        ],
        explanation_vi: null,
      },
      {
        type: "heading",
        level: 3,
        jp: "2級電気工事施工管理技術検定試験出題数と解答数（令和7年度後期の例）",
        vi: "Số câu ra và số câu phải trả lời của kỳ thi 2級 (ví dụ đợt cuối năm Reiwa 7)",
        explanation_vi: null,
      },
      {
        type: "table",
        headers_jp: ["分類", "細目", "出題数", "解答数"],
        rows_jp: [
          ["電気工学等", "電気諸計算", "4", "4"],
          ["電気工学等", "電気機器・電力系統・電気応用", "6", "4"],
          ["電気設備", "発電・一般設備／変電設備／送配電設備／構内電気設備／電気通信関係／電車線／その他の設備", "19", "10"],
          ["関連分野", "機械設備関係／土木関係／建築関係", "6", "3"],
          ["施工管理法・応用問題", "設計・契約関係", "1", "1"],
          ["施工管理法・応用問題", "工事施工／施工計画／工程管理", "4", "4"],
          ["施工管理法・知識問題", "工程管理／品質管理／安全管理", "10", "6"],
          ["法規", "建設業法／電気事業法／建築基準法／消防法／労働安全衛生法／その他関連法規", "12", "8"],
          ["合計", "", "62", "40"],
        ],
        headers_vi: ["Phân loại", "Nội dung", "Số câu ra", "Số câu trả lời"],
        rows_vi: [
          ["Điện công học...", "Các phép tính điện", "4", "4"],
          ["Điện công học...", "Máy điện / hệ thống điện lực / ứng dụng điện", "6", "4"],
          ["Thiết bị điện", "Phát điện & thiết bị chung / trạm biến áp / truyền phân phối / điện trong công trình / thông tin liên lạc / đường dây tàu điện / thiết bị khác", "19", "10"],
          ["Lĩnh vực liên quan", "Thiết bị cơ khí / công trình dân dụng / kiến trúc", "6", "3"],
          ["Quản lý thi công – câu ứng dụng", "Thiết kế / quan hệ hợp đồng", "1", "1"],
          ["Quản lý thi công – câu ứng dụng", "Thi công / kế hoạch thi công / quản lý tiến độ", "4", "4"],
          ["Quản lý thi công – câu kiến thức", "Tiến độ / chất lượng / an toàn", "10", "6"],
          ["Pháp quy", "Luật xây dựng / Luật điện lực / Luật tiêu chuẩn xây dựng / Luật PCCC / Luật an toàn vệ sinh lao động / pháp luật liên quan khác", "12", "8"],
          ["Tổng cộng", "", "62", "40"],
        ],
        explanation_vi: null,
      },
      {
        type: "table",
        headers_jp: ["第二次検定", "解答数"],
        rows_jp: [
          ["電気工学等に関する知識", "1問必須"],
          ["施工管理法", "2問必須"],
          ["法規", "1問必須"],
          ["施工経験記述", "1問必須"],
        ],
        headers_vi: ["Kỳ thi lần 2", "Số câu phải làm"],
        rows_vi: [
          ["Kiến thức về điện công học...", "Bắt buộc 1 câu"],
          ["Phương pháp quản lý thi công", "Bắt buộc 2 câu"],
          ["Pháp quy", "Bắt buộc 1 câu"],
          ["Bài viết kinh nghiệm thi công", "Bắt buộc 1 câu"],
        ],
        explanation_vi: null,
      },
      {
        type: "note",
        jp: "合格の基準：第一次検定の合格基準は全体の60％以上の得点（試験の実施状況を踏まえて変更の可能性がある）と発表されている。",
        vi: "Tiêu chuẩn đỗ: kỳ thi lần 1 được công bố lấy mốc từ 60% tổng điểm trở lên; mức này có thể thay đổi tùy tình hình tổ chức kỳ thi.",
        explanation_vi: "Thông tin này là phần hướng dẫn của sách, nên hiển thị ở trang đầu để tra cứu nhanh trước khi học câu hỏi.",
      },
    ],
  },

  2: {
    sectionCode: "frontmatter",
    content_blocks: [
      {
        type: "heading",
        level: 1,
        jp: "目次",
        vi: "Mục lục",
        explanation_vi: "Giữ mục lục như một trang điều hướng trước khi vào nội dung bài tập.",
      },
      {
        type: "table",
        headers_jp: ["項目", "頁"],
        rows_jp: [
          ["第1章　練習問題", "p.3"],
          ["1. 練習問題①（4回目講習）", "p.4"],
          ["2. 練習問題②（5回目講習）", "p.10"],
          ["第2章　基本問題", "p.15"],
          ["1. 施工管理法", "p.16"],
          ["2. 法規", "p.28"],
          ["3. 電気理論", "p.39"],
          ["4. 電気機器", "p.46"],
          ["5. 電気応用", "p.48"],
          ["6. 電気設備", "p.50"],
          ["7. 関連分野", "p.72"],
          ["8. 工事施工", "p.79"],
          ["第3章　第二次検定基本問題", "p.81"],
          ["1. 安全管理", "p.82"],
          ["2. 品質管理", "p.84"],
          ["3. 高圧受電設備の単線結線図", "p.86"],
          ["4. 電気用語", "p.88"],
          ["5. 法規", "p.90"],
        ],
        headers_vi: ["Mục", "Trang"],
        rows_vi: [
          ["Chương 1 — Bài luyện tập", "p.3"],
          ["1. Bài luyện tập ① (buổi học lần 4)", "p.4"],
          ["2. Bài luyện tập ② (buổi học lần 5)", "p.10"],
          ["Chương 2 — Câu hỏi cơ bản", "p.15"],
          ["1. Phương pháp quản lý thi công", "p.16"],
          ["2. Pháp quy", "p.28"],
          ["3. Lý thuyết điện", "p.39"],
          ["4. Máy điện", "p.46"],
          ["5. Ứng dụng điện", "p.48"],
          ["6. Thiết bị điện", "p.50"],
          ["7. Lĩnh vực liên quan", "p.72"],
          ["8. Thi công công trình", "p.79"],
          ["Chương 3 — Câu hỏi cơ bản kỳ thi lần 2", "p.81"],
          ["1. Quản lý an toàn", "p.82"],
          ["2. Quản lý chất lượng", "p.84"],
          ["3. Sơ đồ một sợi thiết bị nhận điện cao áp", "p.86"],
          ["4. Thuật ngữ điện", "p.88"],
          ["5. Pháp quy", "p.90"],
        ],
        explanation_vi: "Các số trang giữ nguyên theo sách để đối chiếu nhanh.",
      },
    ],
  },

  3: {
    sectionCode: "ch1",
    content_blocks: [
      {
        type: "heading",
        level: 1,
        jp: "第1章　練習問題",
        vi: "Chương 1 — Bài luyện tập",
        explanation_vi: "Trang mở đầu chương. Từ trang 4 bắt đầu 練習問題①.",
      },
    ],
  },
};
