-- ============================================================
-- jp-go — Từ vựng N5, 課25 (BÀI CUỐI CÙNG của phần 語彙 N5 — cơ
-- hội/du học/điều kiện giả định もし～たら, いくら～ても). Nguồn:
-- PDF "Tổng hợp kiến thức N5" (Dũng Mori), PART 2 - 語彙, trang in
-- 31 (trang cuối, ngay sau đó PDF chuyển sang PART 3 - 文法).
-- word_jp/reading/meaning/usage_note nguyên văn PDF (source_type='pdf').
-- Ví dụ/câu hỏi Claude tự soạn (source_type='generated'). Additive,
-- idempotent. Sau migration này, toàn bộ 25/25 課 của N5 (~1000+ từ,
-- 課1-25) đã được nạp đầy đủ vào jp_vocab.
-- ============================================================

-- ---------- jp_vocab: 課25 (13 mục, bài cuối N5) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('f8c5d1e9-6ff3-497f-ab76-d7807719631f', 'N5', 25, 'word', '体', 'からだ', 'cơ thể', NULL, NULL, 31, '体', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('0b656b37-98ac-4cac-81bd-18325d761a30', 'N5', 25, 'word', '調子', 'ちょうし', 'tình trạng', 'sức khỏe, máy móc', NULL, 31, '調子', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('c042ea3c-ae90-493b-9982-423ab9d30ce9', 'N5', 25, 'word', 'グループ', 'グループ', 'nhóm, đoàn', NULL, NULL, 31, 'グループ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('3b3c5587-07b0-42c7-a988-143444374678', 'N5', 25, 'word', 'チャンス', 'チャンス', 'cơ hội', NULL, NULL, 31, 'チャンス', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('523026bd-a5ae-4c8e-95cf-8812f027c811', 'N5', 25, 'word', '日本製', 'にほんせい', 'hàng Nhật', 'có xuất xứ từ Nhật', NULL, 31, '日本製', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('23a9b759-9c7a-4edd-808a-59cc39003cda', 'N5', 25, 'word', '[駅に～]着く', 'つく', 'đến', 'ga', NULL, 31, '[駅に～]着く', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('2277d277-6ce2-43f0-ba34-092ee5757ca6', 'N5', 25, 'word', '考える', 'かんがえる', 'nghĩ, suy nghĩ', NULL, NULL, 31, '考える', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('941d9e4d-5ad9-485e-a424-bcd7c7f872d7', 'N5', 25, 'phrase', 'もし［～たら］', 'もし', 'nếu (- thì)', NULL, NULL, 31, 'もし［～たら］', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('bd099a99-87c9-4ce3-a78d-53a796cccf0f', 'N5', 25, 'phrase', 'いくら［～ても］', 'いくら', 'cho dù, thế nào (- đi nữa)', NULL, NULL, 31, 'いくら［～ても］', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('d1b51178-3a1e-4c4c-a93c-005427b4291c', 'N5', 25, 'word', '給料', 'きゅうりょう', 'lương', NULL, NULL, 31, '給料', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('eace8fb8-1d5b-46a6-863e-c07ab537b5f2', 'N5', 25, 'word', '目が覚める', 'めがさめる', 'tỉnh giấc', NULL, NULL, 31, '目が覚める', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('ea039429-55a7-4e95-aacf-8bc8bf5d5e42', 'N5', 25, 'word', '留学する', 'りゅうがくする', 'du học', NULL, NULL, 31, '留学する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, source_page, source_text, source_type, review_status) values ('05604754-fb7f-4771-b73f-231b56bdf142', 'N5', 25, 'word', '体にいい', 'からだにいい', 'tốt cho sức khỏe', NULL, NULL, 31, '体にいい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '体が大切です。', 'Cơ thể là quan trọng nhất.', '_____が大切です。', '体', 'generated' from jp_vocab where id = 'f8c5d1e9-6ff3-497f-ab76-d7807719631f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '体の調子はどうですか。', 'Tình trạng sức khỏe của bạn thế nào?', '体の_____はどうですか。', '調子', 'generated' from jp_vocab where id = '0b656b37-98ac-4cac-81bd-18325d761a30';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'グループで勉強します。', 'Tôi học theo nhóm.', '_____で勉強します。', 'グループ', 'generated' from jp_vocab where id = 'c042ea3c-ae90-493b-9982-423ab9d30ce9';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'いいチャンスです。', 'Đây là cơ hội tốt.', 'いい_____です。', 'チャンス', 'generated' from jp_vocab where id = '3b3c5587-07b0-42c7-a988-143444374678';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'これは日本製です。', 'Đây là hàng Nhật.', 'これは_____です。', '日本製', 'generated' from jp_vocab where id = '523026bd-a5ae-4c8e-95cf-8812f027c811';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '駅に着きました。', 'Tôi đã đến ga.', '駅に_____ました。', '着き', 'generated' from jp_vocab where id = '23a9b759-9c7a-4edd-808a-59cc39003cda';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '将来について考えます。', 'Tôi suy nghĩ về tương lai.', '将来について_____ます。', '考え', 'generated' from jp_vocab where id = '2277d277-6ce2-43f0-ba34-092ee5757ca6';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'もし時間があったら、来てください。', 'Nếu có thời gian thì xin hãy đến.', '_____時間があったら、来てください。', 'もし', 'generated' from jp_vocab where id = '941d9e4d-5ad9-485e-a424-bcd7c7f872d7';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'いくら考えても分かりません。', 'Dù có nghĩ thế nào đi nữa tôi cũng không hiểu.', '_____考えても分かりません。', 'いくら', 'generated' from jp_vocab where id = 'bd099a99-87c9-4ce3-a78d-53a796cccf0f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '給料をもらいました。', 'Tôi đã nhận lương.', '_____をもらいました。', '給料', 'generated' from jp_vocab where id = 'd1b51178-3a1e-4c4c-a93c-005427b4291c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '朝早く目が覚めました。', 'Sáng sớm tôi đã tỉnh giấc.', '朝早く_____ました。', '目が覚め', 'generated' from jp_vocab where id = 'eace8fb8-1d5b-46a6-863e-c07ab537b5f2';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '日本に留学します。', 'Tôi du học ở Nhật.', '日本に_____ます。', '留学し', 'generated' from jp_vocab where id = 'ea039429-55a7-4e95-aacf-8bc8bf5d5e42';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '野菜は体にいいです。', 'Rau củ tốt cho sức khỏe.', '野菜は_____です。', '体にいい', 'generated' from jp_vocab where id = '05604754-fb7f-4771-b73f-231b56bdf142';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"体" có nghĩa là gì?', 'nhóm, đoàn', 'hàng Nhật', 'cơ thể', 'tỉnh giấc', 'cơ thể', 'generated' from jp_vocab where id = 'f8c5d1e9-6ff3-497f-ab76-d7807719631f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cơ thể"?', '体', 'もし［～たら］', '考える', '調子', '体', 'generated' from jp_vocab where id = 'f8c5d1e9-6ff3-497f-ab76-d7807719631f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"体" đọc là gì?', 'からだ', 'にほんせい', 'めがさめる', 'つく', 'からだ', 'generated' from jp_vocab where id = 'f8c5d1e9-6ff3-497f-ab76-d7807719631f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が大切です。', NULL, NULL, NULL, NULL, '体', 'generated' from jp_vocab where id = 'f8c5d1e9-6ff3-497f-ab76-d7807719631f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"調子" có nghĩa là gì?', 'cho dù, thế nào (- đi nữa)', 'nếu (- thì)', 'cơ hội', 'tình trạng', 'tình trạng', 'generated' from jp_vocab where id = '0b656b37-98ac-4cac-81bd-18325d761a30';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tình trạng"?', 'グループ', '体にいい', '調子', '[駅に～]着く', '調子', 'generated' from jp_vocab where id = '0b656b37-98ac-4cac-81bd-18325d761a30';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"調子" đọc là gì?', 'ちょうし', 'りゅうがくする', 'にほんせい', 'からだにいい', 'ちょうし', 'generated' from jp_vocab where id = '0b656b37-98ac-4cac-81bd-18325d761a30';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 体の_____はどうですか。', NULL, NULL, NULL, NULL, '調子', 'generated' from jp_vocab where id = '0b656b37-98ac-4cac-81bd-18325d761a30';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"グループ" có nghĩa là gì?', 'du học', 'nghĩ, suy nghĩ', 'cho dù, thế nào (- đi nữa)', 'nhóm, đoàn', 'nhóm, đoàn', 'generated' from jp_vocab where id = 'c042ea3c-ae90-493b-9982-423ab9d30ce9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhóm, đoàn"?', 'グループ', '[駅に～]着く', 'チャンス', '給料', 'グループ', 'generated' from jp_vocab where id = 'c042ea3c-ae90-493b-9982-423ab9d30ce9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で勉強します。', NULL, NULL, NULL, NULL, 'グループ', 'generated' from jp_vocab where id = 'c042ea3c-ae90-493b-9982-423ab9d30ce9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"チャンス" có nghĩa là gì?', 'cơ thể', 'nhóm, đoàn', 'cơ hội', 'nghĩ, suy nghĩ', 'cơ hội', 'generated' from jp_vocab where id = '3b3c5587-07b0-42c7-a988-143444374678';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cơ hội"?', '留学する', '目が覚める', 'チャンス', '体', 'チャンス', 'generated' from jp_vocab where id = '3b3c5587-07b0-42c7-a988-143444374678';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: いい_____です。', NULL, NULL, NULL, NULL, 'チャンス', 'generated' from jp_vocab where id = '3b3c5587-07b0-42c7-a988-143444374678';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"日本製" có nghĩa là gì?', 'lương', 'nhóm, đoàn', 'tốt cho sức khỏe', 'hàng Nhật', 'hàng Nhật', 'generated' from jp_vocab where id = '523026bd-a5ae-4c8e-95cf-8812f027c811';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "hàng Nhật"?', '[駅に～]着く', '日本製', '目が覚める', '体にいい', '日本製', 'generated' from jp_vocab where id = '523026bd-a5ae-4c8e-95cf-8812f027c811';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"日本製" đọc là gì?', 'にほんせい', 'めがさめる', 'からだ', 'かんがえる', 'にほんせい', 'generated' from jp_vocab where id = '523026bd-a5ae-4c8e-95cf-8812f027c811';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: これは_____です。', NULL, NULL, NULL, NULL, '日本製', 'generated' from jp_vocab where id = '523026bd-a5ae-4c8e-95cf-8812f027c811';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"[駅に～]着く" có nghĩa là gì?', 'tốt cho sức khỏe', 'du học', 'đến', 'tỉnh giấc', 'đến', 'generated' from jp_vocab where id = '23a9b759-9c7a-4edd-808a-59cc39003cda';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đến"?', 'もし［～たら］', '留学する', '調子', '[駅に～]着く', '[駅に～]着く', 'generated' from jp_vocab where id = '23a9b759-9c7a-4edd-808a-59cc39003cda';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"[駅に～]着く" đọc là gì?', 'つく', 'からだ', 'からだにいい', 'にほんせい', 'つく', 'generated' from jp_vocab where id = '23a9b759-9c7a-4edd-808a-59cc39003cda';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 駅に_____ました。', NULL, NULL, NULL, NULL, '着き', 'generated' from jp_vocab where id = '23a9b759-9c7a-4edd-808a-59cc39003cda';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"考える" có nghĩa là gì?', 'nghĩ, suy nghĩ', 'cơ thể', 'lương', 'tình trạng', 'nghĩ, suy nghĩ', 'generated' from jp_vocab where id = '2277d277-6ce2-43f0-ba34-092ee5757ca6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nghĩ, suy nghĩ"?', '考える', 'チャンス', '体にいい', '給料', '考える', 'generated' from jp_vocab where id = '2277d277-6ce2-43f0-ba34-092ee5757ca6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"考える" đọc là gì?', 'つく', 'きゅうりょう', 'からだ', 'かんがえる', 'かんがえる', 'generated' from jp_vocab where id = '2277d277-6ce2-43f0-ba34-092ee5757ca6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 将来について_____ます。', NULL, NULL, NULL, NULL, '考え', 'generated' from jp_vocab where id = '2277d277-6ce2-43f0-ba34-092ee5757ca6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"もし［～たら］" có nghĩa là gì?', 'nếu (- thì)', 'cho dù, thế nào (- đi nữa)', 'nhóm, đoàn', 'lương', 'nếu (- thì)', 'generated' from jp_vocab where id = '941d9e4d-5ad9-485e-a424-bcd7c7f872d7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nếu (- thì)"?', '留学する', '体にいい', '給料', 'もし［～たら］', 'もし［～たら］', 'generated' from jp_vocab where id = '941d9e4d-5ad9-485e-a424-bcd7c7f872d7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____時間があったら、来てください。', NULL, NULL, NULL, NULL, 'もし', 'generated' from jp_vocab where id = '941d9e4d-5ad9-485e-a424-bcd7c7f872d7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"いくら［～ても］" có nghĩa là gì?', 'nhóm, đoàn', 'cơ hội', 'lương', 'cho dù, thế nào (- đi nữa)', 'cho dù, thế nào (- đi nữa)', 'generated' from jp_vocab where id = 'bd099a99-87c9-4ce3-a78d-53a796cccf0f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cho dù, thế nào (- đi nữa)"?', '考える', 'いくら［～ても］', 'もし［～たら］', '目が覚める', 'いくら［～ても］', 'generated' from jp_vocab where id = 'bd099a99-87c9-4ce3-a78d-53a796cccf0f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____考えても分かりません。', NULL, NULL, NULL, NULL, 'いくら', 'generated' from jp_vocab where id = 'bd099a99-87c9-4ce3-a78d-53a796cccf0f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"給料" có nghĩa là gì?', 'tốt cho sức khỏe', 'đến', 'cho dù, thế nào (- đi nữa)', 'lương', 'lương', 'generated' from jp_vocab where id = 'd1b51178-3a1e-4c4c-a93c-005427b4291c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "lương"?', '給料', 'グループ', '体', '体にいい', '給料', 'generated' from jp_vocab where id = 'd1b51178-3a1e-4c4c-a93c-005427b4291c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"給料" đọc là gì?', 'にほんせい', 'きゅうりょう', 'つく', 'からだ', 'きゅうりょう', 'generated' from jp_vocab where id = 'd1b51178-3a1e-4c4c-a93c-005427b4291c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____をもらいました。', NULL, NULL, NULL, NULL, '給料', 'generated' from jp_vocab where id = 'd1b51178-3a1e-4c4c-a93c-005427b4291c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"目が覚める" có nghĩa là gì?', 'cho dù, thế nào (- đi nữa)', 'hàng Nhật', 'cơ thể', 'tỉnh giấc', 'tỉnh giấc', 'generated' from jp_vocab where id = 'eace8fb8-1d5b-46a6-863e-c07ab537b5f2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tỉnh giấc"?', '体にいい', 'チャンス', '目が覚める', '日本製', '目が覚める', 'generated' from jp_vocab where id = 'eace8fb8-1d5b-46a6-863e-c07ab537b5f2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"目が覚める" đọc là gì?', 'きゅうりょう', 'めがさめる', 'ちょうし', 'からだ', 'めがさめる', 'generated' from jp_vocab where id = 'eace8fb8-1d5b-46a6-863e-c07ab537b5f2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 朝早く_____ました。', NULL, NULL, NULL, NULL, '目が覚め', 'generated' from jp_vocab where id = 'eace8fb8-1d5b-46a6-863e-c07ab537b5f2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"留学する" có nghĩa là gì?', 'nghĩ, suy nghĩ', 'tốt cho sức khỏe', 'du học', 'nhóm, đoàn', 'du học', 'generated' from jp_vocab where id = 'ea039429-55a7-4e95-aacf-8bc8bf5d5e42';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "du học"?', '目が覚める', '留学する', 'いくら［～ても］', '給料', '留学する', 'generated' from jp_vocab where id = 'ea039429-55a7-4e95-aacf-8bc8bf5d5e42';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"留学する" đọc là gì?', 'にほんせい', 'りゅうがくする', 'めがさめる', 'からだ', 'りゅうがくする', 'generated' from jp_vocab where id = 'ea039429-55a7-4e95-aacf-8bc8bf5d5e42';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 日本に_____ます。', NULL, NULL, NULL, NULL, '留学し', 'generated' from jp_vocab where id = 'ea039429-55a7-4e95-aacf-8bc8bf5d5e42';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"体にいい" có nghĩa là gì?', 'tốt cho sức khỏe', 'cho dù, thế nào (- đi nữa)', 'nếu (- thì)', 'đến', 'tốt cho sức khỏe', 'generated' from jp_vocab where id = '05604754-fb7f-4771-b73f-231b56bdf142';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tốt cho sức khỏe"?', 'チャンス', 'いくら［～ても］', '考える', '体にいい', '体にいい', 'generated' from jp_vocab where id = '05604754-fb7f-4771-b73f-231b56bdf142';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"体にいい" đọc là gì?', 'にほんせい', 'からだ', 'めがさめる', 'からだにいい', 'からだにいい', 'generated' from jp_vocab where id = '05604754-fb7f-4771-b73f-231b56bdf142';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 野菜は_____です。', NULL, NULL, NULL, NULL, '体にいい', 'generated' from jp_vocab where id = '05604754-fb7f-4771-b73f-231b56bdf142';

-- Tổng 48 câu hỏi generated cho 13 từ.
