-- ============================================================
-- jp-go — Ngữ pháp N5, round 5 (10 mẫu). Nguồn: PDF "Tổng hợp
-- kiến thức N5" (Dũng Mori), PART 3 - 文法, trang in 39-40. Chủ đề:
-- đếm số lượng trong câu, hỏi thời lượng (どのぐらい), tần suất
-- (回), giới hạn (だけ), quá khứ tính từ (2 usage な/い), so sánh
-- hơn (より) và so sánh nhất (一番), mong muốn (ほしい/たい).
--
-- LƯU Ý: 1 ví dụ PDF (trang 39) có mâu thuẫn số đếm — 三回 (3 lần)
-- nhưng bản dịch ghi "2 lần" — giữ nguyên source_text, đánh dấu
-- review_status='needs_review' kèm corrected_text/correction_note.
-- ============================================================

-- ---------- jp_grammar: 10 mẫu round 5 ----------
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('ac7ee7d3-375d-415e-a3be-94ee361382d5', 'N5', 'N + Trợ từ + Số đếm + Động từ', 'Hỏi/nói số lượng đồ vật trong 1 câu (số đếm chen giữa trợ từ và động từ)', 'Số đếm KHÔNG có trợ từ đi kèm, đứng ngay trước động từ', 'N + が／を + Số đếm(+助数詞) + Động từ', 'Nói số lượng của 1 vật ngay trong câu có động từ, không cần trợ từ riêng cho số đếm', NULL, NULL, 'Số đếm không được gắn thêm は/が/を — nó đứng tự do ngay trước động từ.', '{}', NULL, 39, 'N + Trợ từ + Số đếm + Động từ', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('e4602c21-be56-41f3-964f-9129534f75c9', 'N5', 'どのぐらい／どのくらい Vますか', 'Làm việc gì trong bao lâu／khoảng bao nhiêu', 'Trả lời bằng N(khoảng thời gian/số lượng) + ぐらい／くらい', 'どのぐらい／どのくらい + Vますか → N(khoảng thời gian) + ぐらい／くらい + Vます', 'Hỏi/trả lời độ dài thời gian hoặc mức độ/số lượng % của 1 việc', NULL, 'Nếu sau どのぐらい／どのくらい là động từ できます: có で thì đang hỏi về "thời gian"; không có で thì đang hỏi về "số lượng, mức độ %".', NULL, '{}', NULL, 39, 'どのぐらい／どのくらい Vますか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('3503654e-1283-4554-b9a7-ce64c39a870c', 'N5', 'Lượng từ（ngày, tiếng, đồng hồ...）に～回 + V', 'Trong khoảng thời gian ~ làm việc gì bao nhiêu lần', 'に đứng giữa lượng từ chỉ thời gian và số lần (回)', 'Lượng từ(khoảng thời gian) + に + Số đếm + 回 + V', 'Nói tần suất lặp lại của 1 hành động trong 1 khoảng thời gian', NULL, NULL, NULL, '{}', NULL, 39, 'Lượng từ（ngày, tiếng, đồng hồ...）に～回 + V', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('c8275bcf-b739-440a-8253-335894d6cfc1', 'N5', 'Lượng từ だけ／N だけ', 'Chỉ (lượng từ)／Chỉ (danh từ)', 'だけ = chỉ, chỉ mỗi', 'Lượng từ／N + だけ', 'Giới hạn phạm vi chỉ trong 1 lượng/1 đối tượng duy nhất, không hơn', NULL, NULL, NULL, '{}', NULL, 39, 'Lượng từ だけ／N だけ', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', 'N5', 'Dạng quá khứ của tính từ (A)', 'Thể quá khứ (đã~/đã không~) của tính từ đuôi な và đuôi い', 'Aな: bỏ な, thêm でした/じゃありませんでした; Aい: bỏ い, thêm かったです/くなかったです', NULL, NULL, NULL, NULL, NULL, '{}', NULL, 40, 'Dạng quá khứ của tính từ (A)', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('40276bdc-1505-4c00-80f7-e6c16e09b510', 'N5', 'A は B より／よりずっと Adj です', 'A thì Adj hơn B／A thì Adj hơn hẳn B', 'より = hơn; よりずっと = hơn HẲN (mức chênh lệch lớn)', 'A + は + B + より(ずっと) + Adj + です', 'So sánh hơn giữa 2 đối tượng A và B', NULL, NULL, NULL, '{"A と B と どちらが Adj ですか"}', NULL, 40, 'A は B より／よりずっと Adj です', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('fa7782fd-b253-44e3-94a1-53922a824855', 'N5', 'A と B とどちらが Adj ですか', 'A và B thì cái nào Adj hơn?', 'Trả lời: Aのほうが～ (A thì hơn) hoặc どちらも～ (cái nào cũng)', 'A + と + B + と + どちらが + Adj + ですか → Aのほうが～です／どちらも～です', 'Hỏi so sánh giữa đúng 2 đối tượng, chọn ra bên hơn (hoặc cả 2 như nhau)', NULL, NULL, NULL, '{"A は B より／よりずっと Adj です"}', NULL, 40, 'A と B とどちらが Adj ですか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('06c4b1ef-ce77-4546-859d-a36783f89501', 'N5', 'N の中で A が一番 Adj です', 'Trong số N thì A là ~ nhất', '一番 = nhất (mức độ cao nhất trong 1 nhóm từ 3 trở lên)', 'N(nhóm) + の中で + A(đối tượng) + が + 一番 + Adj + です', 'So sánh nhất giữa nhiều đối tượng trong 1 nhóm/phạm vi', NULL, NULL, NULL, '{}', NULL, 40, 'N の中で A が一番 Adj です', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('c95c564c-1c6f-4900-868e-6ac1b5554a50', 'N5', '何がほしいですか', 'Muốn cái gì／Không muốn cái gì (mong muốn sở hữu 1 vật)', 'ほしい chỉ dùng cho ngôi thứ 1 (tôi); người thứ 3 dùng を欲しがっています', '何 + が + ほしいですか → （私は）N + が + ほしい／ほしくないです', 'Diễn tả mong muốn sở hữu 1 đồ vật', NULL, 'Nếu chủ ngữ là người thứ 3 thì dùng Nを欲しがっています (không dùng ほしいです trực tiếp).', NULL, '{"Vたいですか"}', NULL, 40, '何がほしいですか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('4f32f44d-f84a-4231-b479-7d0162632af7', 'N5', 'V たいですか／何を（が）V たいですか', 'Muốn làm gì／Không muốn làm gì', 'たい chỉ dùng cho ngôi thứ 1; người thứ 3 dùng V連用形+たがっています', '（私は）N + を（が） + V(bỏ ます) + たいです', 'Diễn tả mong muốn thực hiện 1 hành động', NULL, 'Nếu chủ ngữ là người thứ 3 thì dùng V(thể ます bỏ ます)+たがっています.', NULL, '{"何がほしいですか"}', NULL, 40, 'V たいですか／何を（が）V たいですか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;

-- ---------- jp_grammar_usages ----------
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('a7671f10-06cd-41a6-ab9d-e669d744b747', '0d8ab0e0-f906-48c0-9e86-af7c33639115', 1, 'Tính từ đuôi な và danh từ: quá khứ khẳng định でした／phủ định じゃありませんでした', 'N／A(な) + でした (đã~) ／ N／A(な) + じゃありませんでした・ではありませんでした (đã không~)', 'Diễn tả tính chất/trạng thái ở thì quá khứ cho tính từ đuôi な hoặc danh từ', NULL, 40, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('437d9482-9246-4e4a-bd50-07fab8e8078e', '0d8ab0e0-f906-48c0-9e86-af7c33639115', 2, 'Tính từ đuôi い: quá khứ khẳng định かったです／phủ định くなかったです (いい→よかったです)', 'Aい → Aかったです (đã~) ／ Aい → Aくなかったです (đã không~) ； いい → よかったです／よくなかったです (bất quy tắc)', 'Diễn tả tính chất/trạng thái ở thì quá khứ cho tính từ đuôi い', NULL, 40, 'pdf');

-- ---------- jp_grammar_examples: mỗi usage đủ 3 ví dụ ----------
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ac7ee7d3-375d-415e-a3be-94ee361382d5', NULL, 1, 'standard', '机の上に本が何冊ありますか。', 'Trên bàn có mấy quyển sách?', '机の上に本が＿＿＿ありますか。', '何冊', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ac7ee7d3-375d-415e-a3be-94ee361382d5', NULL, 2, 'standard', '机の上に本が八冊あります。', 'Trên bàn có 8 quyển sách.', '机の上に本が＿＿＿あります。', '八冊', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ac7ee7d3-375d-415e-a3be-94ee361382d5', NULL, 3, 'daily', 'かばんの中にペンが三本あります。', 'Trong cặp có 3 cây bút.', 'かばんの中にペンが＿＿＿あります。', '三本', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e4602c21-be56-41f3-964f-9129534f75c9', NULL, 1, 'standard', 'ハノイからダナンまでバスでどのぐらい時間がかかりますか。', 'Đi từ Hà Nội đến Đà Nẵng bằng xe bus hết bao nhiêu thời gian?', 'ハノイからダナンまでバスで＿＿＿時間がかかりますか。', 'どのぐらい', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e4602c21-be56-41f3-964f-9129534f75c9', NULL, 2, 'standard', '八時間ぐらいかかります。', 'Hết khoảng 8 giờ đồng hồ.', '八時間＿＿＿かかります。', 'ぐらい', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e4602c21-be56-41f3-964f-9129534f75c9', NULL, 3, 'standard', '料理はどのくらいでできますか。', 'Nấu cơm khoảng giờ thì xong?', '料理は＿＿＿でできますか。', 'どのくらい', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type, review_status, corrected_text, correction_note) values ('3503654e-1283-4554-b9a7-ce64c39a870c', NULL, 1, 'standard', '一日に三回この薬を飲みます。', 'Tôi một ngày uống thuốc 2 lần.', '一日に＿＿＿この薬を飲みます。', '三回', 'pdf', 'needs_review', '一日に二回この薬を飲みます。(hoặc bản dịch phải là "3 lần" nếu giữ nguyên 三回)', 'PDF gốc dùng 三回 (3 lần) nhưng bản dịch tiếng Việt ghi "2 lần" — số đếm trong câu tiếng Nhật và bản dịch mâu thuẫn nhau, khả năng là lỗi đánh máy trong tài liệu gốc.');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('3503654e-1283-4554-b9a7-ce64c39a870c', NULL, 2, 'daily', '一週間に二回にほんごを勉強します。', 'Một tuần tôi học tiếng Nhật 2 lần.', '一週間に＿＿＿にほんごを勉強します。', '二回', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('3503654e-1283-4554-b9a7-ce64c39a870c', NULL, 3, 'daily', '一か月に一回びょういんへ行きます。', 'Một tháng tôi đi bệnh viện 1 lần.', '一か月に＿＿＿びょういんへ行きます。', '一回', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c8275bcf-b739-440a-8253-335894d6cfc1', NULL, 1, 'standard', 'このスーパーはやさいだけ安いです。', 'Siêu thị này chỉ có rau là rẻ.', 'このスーパーはやさい＿＿＿安いです。', 'だけ', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c8275bcf-b739-440a-8253-335894d6cfc1', NULL, 2, 'standard', '財布の中に100円だけあります。', 'Trong túi chỉ có 100 yên.', '財布の中に100円＿＿＿あります。', 'だけ', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c8275bcf-b739-440a-8253-335894d6cfc1', NULL, 3, 'daily', '肉だけ食べます。', 'Tôi chỉ ăn thịt (thôi).', '肉＿＿＿食べます。', 'だけ', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', 'a7671f10-06cd-41a6-ab9d-e669d744b747', 1, 'standard', '昨日の天気は雨でした。', 'Thời tiết hôm qua mưa.', '昨日の天気は雨＿＿＿。', 'でした', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', 'a7671f10-06cd-41a6-ab9d-e669d744b747', 2, 'daily', 'きのう、ひまでした。', 'Hôm qua tôi rảnh.', 'きのう、ひま＿＿＿。', 'でした', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', 'a7671f10-06cd-41a6-ab9d-e669d744b747', 3, 'daily', 'テストはかんたんじゃありませんでした。', 'Bài kiểm tra đã không đơn giản.', 'テストはかんたん＿＿＿。', 'じゃありませんでした', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', '437d9482-9246-4e4a-bd50-07fab8e8078e', 1, 'standard', '昨日、涼しかったです。', 'Hôm qua đã mát mẻ.', '昨日、＿＿＿です。', '涼しかった', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', '437d9482-9246-4e4a-bd50-07fab8e8078e', 2, 'daily', 'テストはよかったです。', 'Bài kiểm tra đã tốt.', 'テストは＿＿＿です。', 'よかった', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', '437d9482-9246-4e4a-bd50-07fab8e8078e', 3, 'daily', 'きのうのりょうりはおいしくなかったです。', 'Món ăn hôm qua đã không ngon.', 'きのうのりょうりは＿＿＿です。', 'おいしくなかった', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('40276bdc-1505-4c00-80f7-e6c16e09b510', NULL, 1, 'standard', '飛行機はバイクよりずっと速いです。', 'Máy bay thì nhanh hơn hẳn xe máy.', '飛行機はバイク＿＿＿速いです。', 'よりずっと', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('40276bdc-1505-4c00-80f7-e6c16e09b510', NULL, 2, 'daily', '今日は昨日より寒いです。', 'Hôm nay lạnh hơn hôm qua.', '今日は昨日＿＿＿寒いです。', 'より', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('40276bdc-1505-4c00-80f7-e6c16e09b510', NULL, 3, 'daily', '電車はタクシーより安いです。', 'Tàu điện thì rẻ hơn taxi.', '電車はタクシー＿＿＿安いです。', 'より', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fa7782fd-b253-44e3-94a1-53922a824855', NULL, 1, 'standard', '日本語と英語とどちらが難しいですか。', 'Tiếng Nhật và Tiếng Anh thì tiếng nào khó hơn?', '日本語と英語と＿＿＿が難しいですか。', 'どちら', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fa7782fd-b253-44e3-94a1-53922a824855', NULL, 2, 'standard', 'どちらも難しいです。', 'Tiếng nào cũng khó.', '＿＿＿も難しいです。', 'どちら', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fa7782fd-b253-44e3-94a1-53922a824855', NULL, 3, 'daily', 'コーヒーと紅茶とどちらが好きですか。', 'Cà phê và trà thì bạn thích cái nào hơn?', 'コーヒーと紅茶と＿＿＿が好きですか。', 'どちら', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('06c4b1ef-ce77-4546-859d-a36783f89501', NULL, 1, 'standard', '教室の中で誰が一番可愛いですか。', 'Trong lớp thì ai là người dễ thương nhất?', '教室の中で誰が＿＿＿可愛いですか。', '一番', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('06c4b1ef-ce77-4546-859d-a36783f89501', NULL, 2, 'standard', 'Hanhさんが一番可愛いです。', 'Bạn Hạnh là dễ thương nhất.', 'Hanhさんが＿＿＿可愛いです。', '一番', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('06c4b1ef-ce77-4546-859d-a36783f89501', NULL, 3, 'daily', '家族の中で父が一番背が高いです。', 'Trong gia đình thì bố là người cao nhất.', '家族の中で父が＿＿＿背が高いです。', '一番', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c95c564c-1c6f-4900-868e-6ac1b5554a50', NULL, 1, 'standard', '何がほしいですか。', 'Bạn muốn cái gì?', '＿＿＿がほしいですか。', '何', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c95c564c-1c6f-4900-868e-6ac1b5554a50', NULL, 2, 'standard', '今、私はお金が一番欲しいです。', 'Bây giờ tôi muốn tiền nhất.', '今、私はお金が＿＿＿欲しいです。', '一番', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c95c564c-1c6f-4900-868e-6ac1b5554a50', NULL, 3, 'daily', '新しいかばんがほしいです。', 'Tôi muốn 1 cái cặp mới.', '新しいかばん＿＿＿ほしいです。', 'が', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4f32f44d-f84a-4231-b479-7d0162632af7', NULL, 1, 'standard', '今、寝たいです。', 'Bây giờ tôi muốn ngủ.', '今、＿＿＿です。', '寝たい', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4f32f44d-f84a-4231-b479-7d0162632af7', NULL, 2, 'standard', 'すしが食べたいです。', 'Tôi muốn ăn sushi.', 'すし＿＿＿食べたいです。', 'が', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4f32f44d-f84a-4231-b479-7d0162632af7', NULL, 3, 'daily', '日本へ行きたいです。', 'Tôi muốn đi Nhật Bản.', '日本へ＿＿＿です。', '行きたい', 'generated');

-- ---------- jp_grammar_questions: PDF không có 問題, toàn bộ generated ----------
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ac7ee7d3-375d-415e-a3be-94ee361382d5', NULL, 'fill_blank', 'Điền vào chỗ trống: 机の上に本が＿＿＿ありますか。', NULL, NULL, NULL, NULL, '何冊', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ac7ee7d3-375d-415e-a3be-94ee361382d5', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Hỏi/nói số lượng đồ vật trong 1 câu (số đếm chen giữa trợ từ và động từ)"?', 'N + Trợ từ + Số đếm + Động từ', 'A は B より／よりずっと Adj です', 'Lượng từ（ngày, tiếng, đồng hồ...）に～回 + V', 'A と B とどちらが Adj ですか', 'N + Trợ từ + Số đếm + Động từ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ac7ee7d3-375d-415e-a3be-94ee361382d5', NULL, 'choose_connection', 'Cách nối đúng của mẫu "N + Trợ từ + Số đếm + Động từ" (Hỏi/nói số lượng đồ vật trong 1 câu (số đếm chen giữa trợ từ và động từ)) là gì?', 'N + が／を + Số đếm(+助数詞) + Động từ', 'A + と + B + と + どちらが + Adj + ですか → Aのほうが～です／どちらも～です', 'A + は + B + より(ずっと) + Adj + です', 'どのぐらい／どのくらい + Vますか → N(khoảng thời gian) + ぐらい／くらい + Vます', 'N + が／を + Số đếm(+助数詞) + Động từ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e4602c21-be56-41f3-964f-9129534f75c9', NULL, 'fill_blank', 'Điền vào chỗ trống: ハノイからダナンまでバスで＿＿＿時間がかかりますか。', NULL, NULL, NULL, NULL, 'どのぐらい', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e4602c21-be56-41f3-964f-9129534f75c9', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Làm việc gì trong bao lâu／khoảng bao nhiêu"?', 'N + Trợ từ + Số đếm + Động từ', 'A と B とどちらが Adj ですか', 'どのぐらい／どのくらい Vますか', 'Dạng quá khứ của tính từ (A)', 'どのぐらい／どのくらい Vますか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e4602c21-be56-41f3-964f-9129534f75c9', NULL, 'choose_connection', 'Cách nối đúng của mẫu "どのぐらい／どのくらい Vますか" (Làm việc gì trong bao lâu／khoảng bao nhiêu) là gì?', 'N + が／を + Số đếm(+助数詞) + Động từ', 'どのぐらい／どのくらい + Vますか → N(khoảng thời gian) + ぐらい／くらい + Vます', 'N(nhóm) + の中で + A(đối tượng) + が + 一番 + Adj + です', 'A + は + B + より(ずっと) + Adj + です', 'どのぐらい／どのくらい + Vますか → N(khoảng thời gian) + ぐらい／くらい + Vます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('3503654e-1283-4554-b9a7-ce64c39a870c', NULL, 'fill_blank', 'Điền vào chỗ trống: 一日に＿＿＿この薬を飲みます。', NULL, NULL, NULL, NULL, '三回', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('3503654e-1283-4554-b9a7-ce64c39a870c', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Trong khoảng thời gian ~ làm việc gì bao nhiêu lần"?', 'どのぐらい／どのくらい Vますか', 'Lượng từ（ngày, tiếng, đồng hồ...）に～回 + V', 'Dạng quá khứ của tính từ (A)', 'A は B より／よりずっと Adj です', 'Lượng từ（ngày, tiếng, đồng hồ...）に～回 + V', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('3503654e-1283-4554-b9a7-ce64c39a870c', NULL, 'choose_connection', 'Cách nối đúng của mẫu "Lượng từ（ngày, tiếng, đồng hồ...）に～回 + V" (Trong khoảng thời gian ~ làm việc gì bao nhiêu lần) là gì?', 'N／A(な) + でした (đã~) ／ N／A(な) + じゃありませんでした・ではありませんでした (đã không~)', 'Lượng từ(khoảng thời gian) + に + Số đếm + 回 + V', '何 + が + ほしいですか → （私は）N + が + ほしい／ほしくないです', 'N + が／を + Số đếm(+助数詞) + Động từ', 'Lượng từ(khoảng thời gian) + に + Số đếm + 回 + V', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c8275bcf-b739-440a-8253-335894d6cfc1', NULL, 'fill_blank', 'Điền vào chỗ trống: このスーパーはやさい＿＿＿安いです。', NULL, NULL, NULL, NULL, 'だけ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c8275bcf-b739-440a-8253-335894d6cfc1', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Chỉ (lượng từ)／Chỉ (danh từ)"?', 'Lượng từ だけ／N だけ', 'A は B より／よりずっと Adj です', 'Dạng quá khứ của tính từ (A)', 'Lượng từ（ngày, tiếng, đồng hồ...）に～回 + V', 'Lượng từ だけ／N だけ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c8275bcf-b739-440a-8253-335894d6cfc1', NULL, 'choose_connection', 'Cách nối đúng của mẫu "Lượng từ だけ／N だけ" (Chỉ (lượng từ)／Chỉ (danh từ)) là gì?', 'どのぐらい／どのくらい + Vますか → N(khoảng thời gian) + ぐらい／くらい + Vます', 'A + は + B + より(ずっと) + Adj + です', 'Lượng từ／N + だけ', 'N／A(な) + でした (đã~) ／ N／A(な) + じゃありませんでした・ではありませんでした (đã không~)', 'Lượng từ／N + だけ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', 'a7671f10-06cd-41a6-ab9d-e669d744b747', 'fill_blank', 'Điền vào chỗ trống: 昨日の天気は雨＿＿＿。', NULL, NULL, NULL, NULL, 'でした', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', 'a7671f10-06cd-41a6-ab9d-e669d744b747', 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Tính từ đuôi な và danh từ: quá khứ khẳng định でした／phủ định じゃありませんでした"?', 'V たいですか／何を（が）V たいですか', 'A と B とどちらが Adj ですか', 'Dạng quá khứ của tính từ (A)', 'N の中で A が一番 Adj です', 'Dạng quá khứ của tính từ (A)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', 'a7671f10-06cd-41a6-ab9d-e669d744b747', 'choose_connection', 'Cách nối đúng của mẫu "Dạng quá khứ của tính từ (A)" (Tính từ đuôi な và danh từ: quá khứ khẳng định でした／phủ định じゃありませんでした) là gì?', 'Lượng từ(khoảng thời gian) + に + Số đếm + 回 + V', 'N + が／を + Số đếm(+助数詞) + Động từ', 'N／A(な) + でした (đã~) ／ N／A(な) + じゃありませんでした・ではありませんでした (đã không~)', 'どのぐらい／どのくらい + Vますか → N(khoảng thời gian) + ぐらい／くらい + Vます', 'N／A(な) + でした (đã~) ／ N／A(な) + じゃありませんでした・ではありませんでした (đã không~)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', '437d9482-9246-4e4a-bd50-07fab8e8078e', 'fill_blank', 'Điền vào chỗ trống: 昨日、＿＿＿です。', NULL, NULL, NULL, NULL, '涼しかった', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', '437d9482-9246-4e4a-bd50-07fab8e8078e', 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Tính từ đuôi い: quá khứ khẳng định かったです／phủ định くなかったです (いい→よかったです)"?', 'V たいですか／何を（が）V たいですか', 'Lượng từ だけ／N だけ', 'Dạng quá khứ của tính từ (A)', 'A は B より／よりずっと Adj です', 'Dạng quá khứ của tính từ (A)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0d8ab0e0-f906-48c0-9e86-af7c33639115', '437d9482-9246-4e4a-bd50-07fab8e8078e', 'choose_connection', 'Cách nối đúng của mẫu "Dạng quá khứ của tính từ (A)" (Tính từ đuôi い: quá khứ khẳng định かったです／phủ định くなかったです (いい→よかったです)) là gì?', '何 + が + ほしいですか → （私は）N + が + ほしい／ほしくないです', 'N(nhóm) + の中で + A(đối tượng) + が + 一番 + Adj + です', 'N／A(な) + でした (đã~) ／ N／A(な) + じゃありませんでした・ではありませんでした (đã không~)', 'Aい → Aかったです (đã~) ／ Aい → Aくなかったです (đã không~) ； いい → よかったです／よくなかったです (bất quy tắc)', 'Aい → Aかったです (đã~) ／ Aい → Aくなかったです (đã không~) ； いい → よかったです／よくなかったです (bất quy tắc)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('40276bdc-1505-4c00-80f7-e6c16e09b510', NULL, 'fill_blank', 'Điền vào chỗ trống: 飛行機はバイク＿＿＿速いです。', NULL, NULL, NULL, NULL, 'よりずっと', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('40276bdc-1505-4c00-80f7-e6c16e09b510', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "A thì Adj hơn B／A thì Adj hơn hẳn B"?', '何がほしいですか', 'N の中で A が一番 Adj です', 'N + Trợ từ + Số đếm + Động từ', 'A は B より／よりずっと Adj です', 'A は B より／よりずっと Adj です', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('40276bdc-1505-4c00-80f7-e6c16e09b510', NULL, 'choose_connection', 'Cách nối đúng của mẫu "A は B より／よりずっと Adj です" (A thì Adj hơn B／A thì Adj hơn hẳn B) là gì?', '（私は）N + を（が） + V(bỏ ます) + たいです', '何 + が + ほしいですか → （私は）N + が + ほしい／ほしくないです', 'A + は + B + より(ずっと) + Adj + です', 'A + と + B + と + どちらが + Adj + ですか → Aのほうが～です／どちらも～です', 'A + は + B + より(ずっと) + Adj + です', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fa7782fd-b253-44e3-94a1-53922a824855', NULL, 'fill_blank', 'Điền vào chỗ trống: 日本語と英語と＿＿＿が難しいですか。', NULL, NULL, NULL, NULL, 'どちら', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fa7782fd-b253-44e3-94a1-53922a824855', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "A và B thì cái nào Adj hơn?"?', 'A と B とどちらが Adj ですか', 'N の中で A が一番 Adj です', 'N + Trợ từ + Số đếm + Động từ', 'Lượng từ（ngày, tiếng, đồng hồ...）に～回 + V', 'A と B とどちらが Adj ですか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fa7782fd-b253-44e3-94a1-53922a824855', NULL, 'choose_connection', 'Cách nối đúng của mẫu "A と B とどちらが Adj ですか" (A và B thì cái nào Adj hơn?) là gì?', 'N／A(な) + でした (đã~) ／ N／A(な) + じゃありませんでした・ではありませんでした (đã không~)', 'N + が／を + Số đếm(+助数詞) + Động từ', 'A + と + B + と + どちらが + Adj + ですか → Aのほうが～です／どちらも～です', 'どのぐらい／どのくらい + Vますか → N(khoảng thời gian) + ぐらい／くらい + Vます', 'A + と + B + と + どちらが + Adj + ですか → Aのほうが～です／どちらも～です', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('06c4b1ef-ce77-4546-859d-a36783f89501', NULL, 'fill_blank', 'Điền vào chỗ trống: 教室の中で誰が＿＿＿可愛いですか。', NULL, NULL, NULL, NULL, '一番', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('06c4b1ef-ce77-4546-859d-a36783f89501', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Trong số N thì A là ~ nhất"?', 'N の中で A が一番 Adj です', 'どのぐらい／どのくらい Vますか', 'V たいですか／何を（が）V たいですか', 'A は B より／よりずっと Adj です', 'N の中で A が一番 Adj です', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('06c4b1ef-ce77-4546-859d-a36783f89501', NULL, 'choose_connection', 'Cách nối đúng của mẫu "N の中で A が一番 Adj です" (Trong số N thì A là ~ nhất) là gì?', 'A + は + B + より(ずっと) + Adj + です', 'N(nhóm) + の中で + A(đối tượng) + が + 一番 + Adj + です', 'N／A(な) + でした (đã~) ／ N／A(な) + じゃありませんでした・ではありませんでした (đã không~)', 'どのぐらい／どのくらい + Vますか → N(khoảng thời gian) + ぐらい／くらい + Vます', 'N(nhóm) + の中で + A(đối tượng) + が + 一番 + Adj + です', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c95c564c-1c6f-4900-868e-6ac1b5554a50', NULL, 'fill_blank', 'Điền vào chỗ trống: ＿＿＿がほしいですか。', NULL, NULL, NULL, NULL, '何', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c95c564c-1c6f-4900-868e-6ac1b5554a50', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Muốn cái gì／Không muốn cái gì (mong muốn sở hữu 1 vật)"?', '何がほしいですか', 'Lượng từ（ngày, tiếng, đồng hồ...）に～回 + V', 'Dạng quá khứ của tính từ (A)', 'N + Trợ từ + Số đếm + Động từ', '何がほしいですか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c95c564c-1c6f-4900-868e-6ac1b5554a50', NULL, 'choose_connection', 'Cách nối đúng của mẫu "何がほしいですか" (Muốn cái gì／Không muốn cái gì (mong muốn sở hữu 1 vật)) là gì?', '何 + が + ほしいですか → （私は）N + が + ほしい／ほしくないです', 'Lượng từ(khoảng thời gian) + に + Số đếm + 回 + V', 'Lượng từ／N + だけ', 'どのぐらい／どのくらい + Vますか → N(khoảng thời gian) + ぐらい／くらい + Vます', '何 + が + ほしいですか → （私は）N + が + ほしい／ほしくないです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4f32f44d-f84a-4231-b479-7d0162632af7', NULL, 'fill_blank', 'Điền vào chỗ trống: 今、＿＿＿です。', NULL, NULL, NULL, NULL, '寝たい', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4f32f44d-f84a-4231-b479-7d0162632af7', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Muốn làm gì／Không muốn làm gì"?', 'N + Trợ từ + Số đếm + Động từ', 'どのぐらい／どのくらい Vますか', 'V たいですか／何を（が）V たいですか', '何がほしいですか', 'V たいですか／何を（が）V たいですか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4f32f44d-f84a-4231-b479-7d0162632af7', NULL, 'choose_connection', 'Cách nối đúng của mẫu "V たいですか／何を（が）V たいですか" (Muốn làm gì／Không muốn làm gì) là gì?', 'Lượng từ(khoảng thời gian) + に + Số đếm + 回 + V', 'Aい → Aかったです (đã~) ／ Aい → Aくなかったです (đã không~) ； いい → よかったです／よくなかったです (bất quy tắc)', 'N(nhóm) + の中で + A(đối tượng) + が + 一番 + Adj + です', '（私は）N + を（が） + V(bỏ ます) + たいです', '（私は）N + を（が） + V(bỏ ます) + たいです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4f32f44d-f84a-4231-b479-7d0162632af7', NULL, 'reorder_sentence', 'Sắp xếp thành câu đúng: すし ／ が ／ 食べたい ／ です (Tôi muốn ăn sushi.)', NULL, NULL, NULL, NULL, 'すしが食べたいです', 'generated');

-- Tổng 34 câu hỏi generated cho 10 mẫu ngữ pháp.
