-- ============================================================
-- jp-go — Ngữ pháp N5, round 6 (8 mẫu). Nguồn: PDF "Tổng hợp kiến
-- thức N5" (Dũng Mori), PART 3 - 文法, trang in 40-41. Chủ đề: mục
-- đích di chuyển (Vますに+行きます), phiếm chỉ (どこか/なにか), thể て
-- của động từ, các cấu trúc cơ bản dùng thể て (てください/ています
-- gộp 3 usage/ましょうか/てもいいですか/てはいけません).
-- ============================================================

-- ---------- jp_grammar: 8 mẫu round 6 ----------
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('b7ee2b77-4b11-450e-9f15-27faafa5449c', 'N5', 'N1（Địa điểm）へ（に）+ V(masu gốc)に + 行きます／来ます／帰ります', 'Đi／Đến／Về (địa điểm) để làm gì (mục đích di chuyển)', 'V bỏ ます + に đứng trước động từ di chuyển để chỉ mục đích', 'N1(địa điểm) + へ／に + V(bỏ ます) + に + 行きます／来ます／帰ります', 'Chỉ mục đích của việc di chuyển tới 1 địa điểm', NULL, NULL, NULL, '{"(Địa điểm) へ(に) + 行きます／来ます／帰ります"}', NULL, 40, 'N1（Địa điểm）へ（に）+ V(masu gốc)に + 行きます／来ます／帰ります', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('df790a09-2ee6-4f99-b917-92a51c53dfe0', 'N5', 'どこか・なにか', 'Nơi nào đó – Cái gì đó (phiếm chỉ, không xác định)', 'か sau どこ/なに = một nơi/1 thứ nào đó không xác định cụ thể', 'どこか + へ／を + V ； なにか + を + V', 'Chỉ 1 nơi hoặc 1 vật không xác định, không cần nói rõ là gì/ở đâu', NULL, NULL, 'Khác どこも (không...đâu cả, luôn đi với phủ định) — どこか mang nghĩa khẳng định phiếm chỉ.', '{"どこ(へ)もいきません"}', NULL, 40, 'どこか・なにか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('9d1806ce-c469-476d-8ede-07aed065cef0', 'N5', 'Thể て của động từ', 'Thể て (dùng để nối câu, làm nền cho nhiều mẫu ngữ pháp khác)', 'Nhóm I: う/つ/る→って; む/ぶ/ぬ→んで; す→して; く→いて; ぐ→いで; Nhóm II: eる/iる→て; Nhóm III: する→して, くる→きて', 'Nhóm I: う,つ,る→って｜む,ぶ,ぬ→んで｜す→して｜く→いて｜ぐ→いで ； Nhóm II: bỏ る thêm て ； Nhóm III: する→して, くる→きて', 'Dạng nối của động từ, không tự đứng thành câu hoàn chỉnh mà làm nền cho các cấu trúc như てください/ています/てもいいです...', NULL, NULL, NULL, '{}', NULL, 41, 'Thể て của động từ', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('c34b715e-cb50-45ed-aeb9-5869eb04a4ea', 'N5', 'V てください', 'Hãy làm ...đi!', 'てください = mệnh lệnh lịch sự, yêu cầu ai đó làm gì', 'V(thể て) + ください', 'Yêu cầu/nhờ vả ai đó làm 1 việc một cách lịch sự', 'lịch sự', NULL, NULL, '{"V てはいけません"}', NULL, 41, 'V てください', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'N5', 'V ています', 'Đang làm ~／Trạng thái tiếp diễn của kết quả hành động／Thói quen, tập quán lặp lại', '1 dạng ています, 3 cách hiểu tùy động từ và ngữ cảnh', 'V(thể て) + います', NULL, NULL, NULL, NULL, '{}', NULL, 41, 'V ています', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('fcbd287e-4bd2-4411-96e6-0467fb9f7888', 'N5', 'V（thể ます）ましょうか', 'Để tôi làm giúp nhé?', 'ましょうか = đề nghị giúp đỡ, khác Vましょう (rủ cùng làm)', 'V(thể ます, bỏ ます) + ましょうか', 'Đề nghị chủ động làm giúp người nghe 1 việc gì đó', 'lịch sự', NULL, 'ましょうか (đề nghị giúp) khác ませんか (rủ rê cùng làm) — chú ý ngữ cảnh.', '{"V ましょう"}', NULL, 41, 'V（thể ます）ましょうか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('7e3fd288-270e-4b19-8bb2-5a00c782df70', 'N5', 'V てもいいですか', 'Làm việc này được không?', 'てもいいですか hỏi xin phép; trả lời いいですよ (được) / いけません (không được)', 'V(thể て) + も + いいですか', 'Xin phép làm 1 việc gì đó', 'Thể lịch sự hơn: てもよろしいですか. てもいいです = てもかまいません.', 'Từ chối lịch sự: いいえ、いけません。～から。／すみません、ちょっと～から。', NULL, '{"V てはいけません"}', NULL, 41, 'V てもいいですか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('e901190c-84fa-4059-a54d-742c2b070494', 'N5', 'V てはいけません', 'Cấm làm gì／Không được làm gì', 'てはいけません = cấm tuyệt đối, sắc thái mạnh hơn ないでください', 'V(thể て) + は + いけません', 'Cấm đoán, không cho phép thực hiện 1 hành động', NULL, NULL, NULL, '{"V てもいいですか"}', NULL, 41, 'V てはいけません', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;

-- ---------- jp_grammar_usages ----------
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('bed644cd-4dab-4a9d-ba6a-d60af4ed2c40', '2c067970-1247-46ee-a2b5-073084d6564e', 1, 'Đang làm ~ (hành động đang diễn ra tại thời điểm nói)', 'V(thể て) + います', 'Diễn tả hành động đang xảy ra ngay lúc nói', NULL, 41, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('8716f245-6d83-46d6-9798-790002e19d06', '2c067970-1247-46ee-a2b5-073084d6564e', 2, 'Kết quả của 1 hành động đã diễn ra trong quá khứ vẫn còn hiệu lực ở hiện tại', 'V(thể て) + います', 'Hành động xảy ra 1 lần trong quá khứ nhưng kết quả/trạng thái của nó vẫn còn tiếp diễn', NULL, 41, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('e26ef015-cc03-4416-ab5e-5fa1058e3945', '2c067970-1247-46ee-a2b5-073084d6564e', 3, 'Tập quán, thói quen, hành động lặp đi lặp lại trong thời gian dài', 'V(thể て) + います', 'Diễn tả công việc/thói quen thường xuyên, kéo dài, không chỉ tại thời điểm nói', NULL, 41, 'pdf');

-- ---------- jp_grammar_examples: mỗi usage đủ 3 ví dụ ----------
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b7ee2b77-4b11-450e-9f15-27faafa5449c', NULL, 1, 'standard', 'ハノイへ日本語を勉強しに行きます。', 'Tôi đi Hà Nội để học tiếng Nhật.', 'ハノイへ日本語を勉強し＿＿＿行きます。', 'に', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b7ee2b77-4b11-450e-9f15-27faafa5449c', NULL, 2, 'daily', 'スーパーへ買い物に行きます。', 'Tôi đi siêu thị để mua đồ.', 'スーパーへ買い物＿＿＿行きます。', 'に', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b7ee2b77-4b11-450e-9f15-27faafa5449c', NULL, 3, 'daily', 'レストランへ食べに行きます。', 'Tôi đi nhà hàng để ăn.', 'レストランへ食べ＿＿＿行きます。', 'に', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('df790a09-2ee6-4f99-b917-92a51c53dfe0', NULL, 1, 'standard', '明日、どこかへ行きますか。', 'Ngày mai bạn đi đâu đó không?', '明日、＿＿＿へ行きますか。', 'どこか', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('df790a09-2ee6-4f99-b917-92a51c53dfe0', NULL, 2, 'standard', '図書館へ行きます。', 'Tôi sẽ đi thư viện.', '図書館＿＿＿行きます。', 'へ', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('df790a09-2ee6-4f99-b917-92a51c53dfe0', NULL, 3, 'standard', 'なにか食べますか。', 'Bạn ăn cái gì đó không?', '＿＿＿食べますか。', 'なにか', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('9d1806ce-c469-476d-8ede-07aed065cef0', NULL, 1, 'standard', 'エアコンをつけてください。', 'Hãy bật điều hòa lên.', 'エアコンをつけ＿＿＿ください。', 'て', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('9d1806ce-c469-476d-8ede-07aed065cef0', NULL, 2, 'daily', '本を読んでください。', 'Hãy đọc sách.', '本を読＿＿＿ください。', 'んで', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('9d1806ce-c469-476d-8ede-07aed065cef0', NULL, 3, 'daily', '写真を撮って、見せてください。', 'Hãy chụp ảnh rồi cho tôi xem.', '写真を撮＿＿＿、見せてください。', 'って', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c34b715e-cb50-45ed-aeb9-5869eb04a4ea', NULL, 1, 'standard', 'すみませんが、エアコンをつけてください。', 'Xin lỗi nhưng hãy bật điều hòa lên.', 'すみませんが、エアコンをつけ＿＿＿。', 'てください', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c34b715e-cb50-45ed-aeb9-5869eb04a4ea', NULL, 2, 'daily', 'ちょっと待ってください。', 'Hãy đợi một chút.', 'ちょっと待＿＿＿。', 'ってください', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c34b715e-cb50-45ed-aeb9-5869eb04a4ea', NULL, 3, 'daily', 'ここに名前を書いてください。', 'Hãy viết tên vào đây.', 'ここに名前を書＿＿＿。', 'いてください', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'bed644cd-4dab-4a9d-ba6a-d60af4ed2c40', 1, 'standard', '娘はなにをしていますか。', 'Con gái đang làm gì vậy?', '娘はなにを＿＿＿か。', 'していますか', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'bed644cd-4dab-4a9d-ba6a-d60af4ed2c40', 2, 'standard', '今、寝ています。', 'Bây giờ thì đang ngủ.', '今、＿＿＿。', '寝ています', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'bed644cd-4dab-4a9d-ba6a-d60af4ed2c40', 3, 'daily', 'テレビを見ています。', 'Tôi đang xem tivi.', 'テレビを＿＿＿。', '見ています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', '8716f245-6d83-46d6-9798-790002e19d06', 1, 'standard', '私はハノイに住んでいます。', 'Tôi đang sống tại Hà Nội.', '私はハノイに＿＿＿。', '住んでいます', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', '8716f245-6d83-46d6-9798-790002e19d06', 2, 'daily', '結婚しています。', 'Tôi đã kết hôn (và vẫn đang trong tình trạng đó).', '＿＿＿。', '結婚しています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', '8716f245-6d83-46d6-9798-790002e19d06', 3, 'daily', '窓が開いています。', 'Cửa sổ đang mở (đã mở và vẫn còn mở).', '窓が＿＿＿。', '開いています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'e26ef015-cc03-4416-ab5e-5fa1058e3945', 1, 'standard', 'Linhさんは ABC 会社で働いています。', 'Chị Linh đang làm việc tại Công ty ABC.', 'Linhさんは ABC 会社で＿＿＿。', '働いています', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'e26ef015-cc03-4416-ab5e-5fa1058e3945', 2, 'daily', '毎朝、走っています。', 'Mỗi sáng tôi đều chạy bộ.', '毎朝、＿＿＿。', '走っています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'e26ef015-cc03-4416-ab5e-5fa1058e3945', 3, 'daily', '銀行で働いています。', 'Tôi làm việc ở ngân hàng.', '銀行で＿＿＿。', '働いています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fcbd287e-4bd2-4411-96e6-0467fb9f7888', NULL, 1, 'standard', '窓をあけましょうか。', 'Để tôi mở cửa sổ nhé?', '窓をあけ＿＿＿。', 'ましょうか', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fcbd287e-4bd2-4411-96e6-0467fb9f7888', NULL, 2, 'standard', 'すみません、お願いします。', 'Xin lỗi nhưng phiền bạn.', 'すみません、＿＿＿。', 'お願いします', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fcbd287e-4bd2-4411-96e6-0467fb9f7888', NULL, 3, 'daily', '荷物を持ちましょうか。', 'Để tôi xách đồ giúp nhé?', '荷物を持ち＿＿＿。', 'ましょうか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('7e3fd288-270e-4b19-8bb2-5a00c782df70', NULL, 1, 'standard', 'すみませんが、先に帰ってもいいですか。', 'Xin lỗi, tôi có thể về trước được không?', 'すみませんが、先に帰＿＿＿か。', 'ってもいいです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('7e3fd288-270e-4b19-8bb2-5a00c782df70', NULL, 2, 'standard', 'ええ、いいですよ。', 'Vâng, được nhé.', 'ええ、＿＿＿よ。', 'いいです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('7e3fd288-270e-4b19-8bb2-5a00c782df70', NULL, 3, 'standard', 'このスープに砂糖を入れてもいいです。', 'Bỏ đường vào trong món súp này được.', 'このスープに砂糖を入れ＿＿＿。', 'てもいいです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e901190c-84fa-4059-a54d-742c2b070494', NULL, 1, 'standard', '教室でタバコを吸ってはいけません。', 'Cấm không được hút thuốc lá trong lớp học.', '教室でタバコを吸＿＿＿。', 'ってはいけません', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e901190c-84fa-4059-a54d-742c2b070494', NULL, 2, 'standard', 'まだ子供ですから、お酒を飲んではいけませんよ。', 'Vì vẫn là trẻ con nên cấm không được uống rượu nhé!', 'まだ子供ですから、お酒を飲＿＿＿よ。', 'んではいけません', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e901190c-84fa-4059-a54d-742c2b070494', NULL, 3, 'daily', 'ここで写真を撮ってはいけません。', 'Cấm chụp ảnh ở đây.', 'ここで写真を撮＿＿＿。', 'ってはいけません', 'generated');

-- ---------- jp_grammar_questions: PDF không có 問題, toàn bộ generated ----------
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b7ee2b77-4b11-450e-9f15-27faafa5449c', NULL, 'fill_blank', 'Điền vào chỗ trống: ハノイへ日本語を勉強し＿＿＿行きます。', NULL, NULL, NULL, NULL, 'に', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b7ee2b77-4b11-450e-9f15-27faafa5449c', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Đi／Đến／Về (địa điểm) để làm gì (mục đích di chuyển)"?', 'V ています', 'V てはいけません', 'N1（Địa điểm）へ（に）+ V(masu gốc)に + 行きます／来ます／帰ります', 'V てください', 'N1（Địa điểm）へ（に）+ V(masu gốc)に + 行きます／来ます／帰ります', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b7ee2b77-4b11-450e-9f15-27faafa5449c', NULL, 'choose_connection', 'Cách nối đúng của mẫu "N1（Địa điểm）へ（に）+ V(masu gốc)に + 行きます／来ます／帰ります" (Đi／Đến／Về (địa điểm) để làm gì (mục đích di chuyển)) là gì?', 'V(thể て) + います', 'V(thể て) + います', 'N1(địa điểm) + へ／に + V(bỏ ます) + に + 行きます／来ます／帰ります', 'どこか + へ／を + V ； なにか + を + V', 'N1(địa điểm) + へ／に + V(bỏ ます) + に + 行きます／来ます／帰ります', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('df790a09-2ee6-4f99-b917-92a51c53dfe0', NULL, 'fill_blank', 'Điền vào chỗ trống: 明日、＿＿＿へ行きますか。', NULL, NULL, NULL, NULL, 'どこか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('df790a09-2ee6-4f99-b917-92a51c53dfe0', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Nơi nào đó – Cái gì đó (phiếm chỉ, không xác định)"?', 'N1（Địa điểm）へ（に）+ V(masu gốc)に + 行きます／来ます／帰ります', 'V てもいいですか', 'どこか・なにか', 'Thể て của động từ', 'どこか・なにか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('df790a09-2ee6-4f99-b917-92a51c53dfe0', NULL, 'choose_connection', 'Cách nối đúng của mẫu "どこか・なにか" (Nơi nào đó – Cái gì đó (phiếm chỉ, không xác định)) là gì?', 'どこか + へ／を + V ； なにか + を + V', 'V(thể て) + ください', 'V(thể て) + います', 'V(thể て) + は + いけません', 'どこか + へ／を + V ； なにか + を + V', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('9d1806ce-c469-476d-8ede-07aed065cef0', NULL, 'fill_blank', 'Điền vào chỗ trống: エアコンをつけ＿＿＿ください。', NULL, NULL, NULL, NULL, 'て', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('9d1806ce-c469-476d-8ede-07aed065cef0', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Thể て (dùng để nối câu, làm nền cho nhiều mẫu ngữ pháp khác)"?', 'Thể て của động từ', 'V ています', 'V てください', 'N1（Địa điểm）へ（に）+ V(masu gốc)に + 行きます／来ます／帰ります', 'Thể て của động từ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('9d1806ce-c469-476d-8ede-07aed065cef0', NULL, 'choose_connection', 'Cách nối đúng của mẫu "Thể て của động từ" (Thể て (dùng để nối câu, làm nền cho nhiều mẫu ngữ pháp khác)) là gì?', 'Nhóm I: う,つ,る→って｜む,ぶ,ぬ→んで｜す→して｜く→いて｜ぐ→いで ； Nhóm II: bỏ る thêm て ； Nhóm III: する→して, くる→きて', 'V(thể て) + も + いいですか', 'V(thể て) + は + いけません', 'V(thể て) + ください', 'Nhóm I: う,つ,る→って｜む,ぶ,ぬ→んで｜す→して｜く→いて｜ぐ→いで ； Nhóm II: bỏ る thêm て ； Nhóm III: する→して, くる→きて', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c34b715e-cb50-45ed-aeb9-5869eb04a4ea', NULL, 'fill_blank', 'Điền vào chỗ trống: すみませんが、エアコンをつけ＿＿＿。', NULL, NULL, NULL, NULL, 'てください', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c34b715e-cb50-45ed-aeb9-5869eb04a4ea', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Hãy làm ...đi!"?', 'V てもいいですか', 'N1（Địa điểm）へ（に）+ V(masu gốc)に + 行きます／来ます／帰ります', 'V てはいけません', 'V てください', 'V てください', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c34b715e-cb50-45ed-aeb9-5869eb04a4ea', NULL, 'choose_connection', 'Cách nối đúng của mẫu "V てください" (Hãy làm ...đi!) là gì?', 'V(thể て) + ください', 'V(thể ます, bỏ ます) + ましょうか', 'V(thể て) + います', 'V(thể て) + は + いけません', 'V(thể て) + ください', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'bed644cd-4dab-4a9d-ba6a-d60af4ed2c40', 'fill_blank', 'Điền vào chỗ trống: 娘はなにを＿＿＿か。', NULL, NULL, NULL, NULL, 'していますか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'bed644cd-4dab-4a9d-ba6a-d60af4ed2c40', 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Đang làm ~ (hành động đang diễn ra tại thời điểm nói)"?', 'どこか・なにか', 'V てもいいですか', 'V ています', 'V てください', 'V ています', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'bed644cd-4dab-4a9d-ba6a-d60af4ed2c40', 'choose_connection', 'Cách nối đúng của mẫu "V ています" (Đang làm ~ (hành động đang diễn ra tại thời điểm nói)) là gì?', 'V(thể ます, bỏ ます) + ましょうか', 'V(thể て) + います', 'どこか + へ／を + V ； なにか + を + V', 'V(thể て) + も + いいですか', 'V(thể て) + います', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', '8716f245-6d83-46d6-9798-790002e19d06', 'fill_blank', 'Điền vào chỗ trống: 私はハノイに＿＿＿。', NULL, NULL, NULL, NULL, '住んでいます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', '8716f245-6d83-46d6-9798-790002e19d06', 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Kết quả của 1 hành động đã diễn ra trong quá khứ vẫn còn hiệu lực ở hiện tại"?', 'V ています', 'どこか・なにか', 'V てください', 'V てもいいですか', 'V ています', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', '8716f245-6d83-46d6-9798-790002e19d06', 'choose_connection', 'Cách nối đúng của mẫu "V ています" (Kết quả của 1 hành động đã diễn ra trong quá khứ vẫn còn hiệu lực ở hiện tại) là gì?', 'V(thể て) + います', 'Nhóm I: う,つ,る→って｜む,ぶ,ぬ→んで｜す→して｜く→いて｜ぐ→いで ； Nhóm II: bỏ る thêm て ； Nhóm III: する→して, くる→きて', 'N1(địa điểm) + へ／に + V(bỏ ます) + に + 行きます／来ます／帰ります', 'どこか + へ／を + V ； なにか + を + V', 'V(thể て) + います', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'e26ef015-cc03-4416-ab5e-5fa1058e3945', 'fill_blank', 'Điền vào chỗ trống: Linhさんは ABC 会社で＿＿＿。', NULL, NULL, NULL, NULL, '働いています', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'e26ef015-cc03-4416-ab5e-5fa1058e3945', 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Tập quán, thói quen, hành động lặp đi lặp lại trong thời gian dài"?', 'どこか・なにか', 'V てもいいですか', 'V てください', 'V ています', 'V ています', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'e26ef015-cc03-4416-ab5e-5fa1058e3945', 'choose_connection', 'Cách nối đúng của mẫu "V ています" (Tập quán, thói quen, hành động lặp đi lặp lại trong thời gian dài) là gì?', 'V(thể ます, bỏ ます) + ましょうか', 'V(thể て) + ください', 'どこか + へ／を + V ； なにか + を + V', 'V(thể て) + います', 'V(thể て) + います', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2c067970-1247-46ee-a2b5-073084d6564e', 'bed644cd-4dab-4a9d-ba6a-d60af4ed2c40', 'reorder_sentence', 'Sắp xếp thành câu đúng: 私 ／ は ／ ハノイ ／ に ／ 住んでいます (Tôi đang sống tại Hà Nội.)', NULL, NULL, NULL, NULL, '私はハノイに住んでいます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fcbd287e-4bd2-4411-96e6-0467fb9f7888', NULL, 'fill_blank', 'Điền vào chỗ trống: 窓をあけ＿＿＿。', NULL, NULL, NULL, NULL, 'ましょうか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fcbd287e-4bd2-4411-96e6-0467fb9f7888', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Để tôi làm giúp nhé?"?', 'N1（Địa điểm）へ（に）+ V(masu gốc)に + 行きます／来ます／帰ります', 'V（thể ます）ましょうか', 'どこか・なにか', 'Thể て của động từ', 'V（thể ます）ましょうか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fcbd287e-4bd2-4411-96e6-0467fb9f7888', NULL, 'choose_connection', 'Cách nối đúng của mẫu "V（thể ます）ましょうか" (Để tôi làm giúp nhé?) là gì?', 'V(thể て) + は + いけません', 'V(thể ます, bỏ ます) + ましょうか', 'V(thể て) + ください', 'V(thể て) + います', 'V(thể ます, bỏ ます) + ましょうか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('7e3fd288-270e-4b19-8bb2-5a00c782df70', NULL, 'fill_blank', 'Điền vào chỗ trống: すみませんが、先に帰＿＿＿か。', NULL, NULL, NULL, NULL, 'ってもいいです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('7e3fd288-270e-4b19-8bb2-5a00c782df70', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Làm việc này được không?"?', 'V てください', 'V てもいいですか', 'V（thể ます）ましょうか', 'Thể て của động từ', 'V てもいいですか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('7e3fd288-270e-4b19-8bb2-5a00c782df70', NULL, 'choose_connection', 'Cách nối đúng của mẫu "V てもいいですか" (Làm việc này được không?) là gì?', 'V(thể て) + います', 'V(thể て) + います', 'V(thể て) + も + いいですか', 'どこか + へ／を + V ； なにか + を + V', 'V(thể て) + も + いいですか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e901190c-84fa-4059-a54d-742c2b070494', NULL, 'fill_blank', 'Điền vào chỗ trống: 教室でタバコを吸＿＿＿。', NULL, NULL, NULL, NULL, 'ってはいけません', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e901190c-84fa-4059-a54d-742c2b070494', NULL, 'choose_meaning', 'Mẫu ngữ pháp nào có nghĩa: "Cấm làm gì／Không được làm gì"?', 'V てはいけません', 'V てもいいですか', 'V ています', 'N1（Địa điểm）へ（に）+ V(masu gốc)に + 行きます／来ます／帰ります', 'V てはいけません', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e901190c-84fa-4059-a54d-742c2b070494', NULL, 'choose_connection', 'Cách nối đúng của mẫu "V てはいけません" (Cấm làm gì／Không được làm gì) là gì?', 'V(thể て) + は + いけません', 'N1(địa điểm) + へ／に + V(bỏ ます) + に + 行きます／来ます／帰ります', 'どこか + へ／を + V ； なにか + を + V', 'V(thể て) + います', 'V(thể て) + は + いけません', 'generated');

-- Tổng 31 câu hỏi generated cho 8 mẫu ngữ pháp.
