-- ============================================================
-- jp-go — Kanji N2, round 2 (12 kanji). Nguồn: PDF "Tổng hợp kiến
-- thức N2" (Dũng Mori), PART 1 - 漢字, trang in 2 (5 kanji còn lại
-- của trang thí điểm: 丼/囲/逸/令/罠) và trang in 3 (7 kanji: 祭/
-- 察/際/垂/郵/睡/票). Cùng cơ chế round trước: tự tách furigana ứng
-- đúng kanji đang xét, tự phân loại on/kun, không bịa âm không có.
-- ============================================================

-- ---------- 丼 (TỊNH) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('0329fffa-1996-4ae1-9b0b-395dbb7bb55b', 'N2', '丼', 'TỊNH', 'cái tô lớn, cơm tô (kiểu donburi)', NULL, NULL, '丼 tượng hình cái bát to đựng cơm — món cơm tô kiểu Nhật gọi chung là donburi.', '丼 và 井 cùng Hán Việt "TỊNH" nhưng khác kanji hẳn — 丼 có thêm dấu chấm ở giữa.', '{"井"}', 2, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'dbc346ec-ec80-42b5-8d86-6da79fceecb7', id, 'kun', 'どんぶり', true, 2, 'ok', NULL from jp_kanji where id = '0329fffa-1996-4ae1-9b0b-395dbb7bb55b' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('0329fffa-1996-4ae1-9b0b-395dbb7bb55b', 'dbc346ec-ec80-42b5-8d86-6da79fceecb7', '丼', 'どんぶり', 'cái tô, bát loa', false, 2, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('0329fffa-1996-4ae1-9b0b-395dbb7bb55b', 'dbc346ec-ec80-42b5-8d86-6da79fceecb7', '天丼', 'てんどん', 'cơm tempura', false, 2, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('0329fffa-1996-4ae1-9b0b-395dbb7bb55b', 'dbc346ec-ec80-42b5-8d86-6da79fceecb7', 'カツ丼', 'かつどん', 'cơm thịt tấm bột chiên', false, 2, 'pdf', 'ok', NULL);

-- ---------- 囲 (VI) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('aa42fae9-54b9-4b20-9b52-e75f7145a352', 'N2', '囲', 'VI', 'bao quanh, phạm vi', NULL, NULL, '囲 = 囗(bao quanh) + 井 — vây quanh giống hình cái giếng có thành bao.', NULL, '{}', 2, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'ce45cf58-c136-4e1c-8709-58e23bdf5d27', id, 'kun', 'かこ', true, 2, 'ok', NULL from jp_kanji where id = 'aa42fae9-54b9-4b20-9b52-e75f7145a352' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '1433f8a7-e5a1-46f4-be2f-54d3abe7178f', id, 'on', 'い', true, 2, 'ok', NULL from jp_kanji where id = 'aa42fae9-54b9-4b20-9b52-e75f7145a352' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('aa42fae9-54b9-4b20-9b52-e75f7145a352', 'ce45cf58-c136-4e1c-8709-58e23bdf5d27', '囲む', 'かこむ', 'quây quần', false, 2, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('aa42fae9-54b9-4b20-9b52-e75f7145a352', 'ce45cf58-c136-4e1c-8709-58e23bdf5d27', '囲う', 'かこう', 'quây lại', false, 2, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('aa42fae9-54b9-4b20-9b52-e75f7145a352', '1433f8a7-e5a1-46f4-be2f-54d3abe7178f', '範囲', 'はんい', 'phạm vi', false, 2, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('aa42fae9-54b9-4b20-9b52-e75f7145a352', '1433f8a7-e5a1-46f4-be2f-54d3abe7178f', '包囲', 'ほうい', 'bao vây', false, 2, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('aa42fae9-54b9-4b20-9b52-e75f7145a352', '1433f8a7-e5a1-46f4-be2f-54d3abe7178f', '周囲', 'しゅうい', 'chu vi', false, 2, 'pdf', 'ok', NULL);

-- ---------- 逸 (DẬT) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('a7159500-4e1f-48c9-8dee-2bb9a37c23d9', 'N2', '逸', 'DẬT', 'xuất sắc; lệch, trốn tránh', NULL, NULL, '逸 = 辶(đi) + 兎(thỏ) — thỏ chạy vụt đi, ý chỉ vượt trội hoặc lạc hướng.', NULL, '{}', 2, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '3671130a-8ef0-490d-86aa-8b6d0e10df22', id, 'on', 'いつ', true, 2, 'ok', NULL from jp_kanji where id = 'a7159500-4e1f-48c9-8dee-2bb9a37c23d9' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'f75fbf2f-b767-4276-81eb-10bf42335fd1', id, 'kun', 'そ', true, 2, 'ok', NULL from jp_kanji where id = 'a7159500-4e1f-48c9-8dee-2bb9a37c23d9' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a7159500-4e1f-48c9-8dee-2bb9a37c23d9', '3671130a-8ef0-490d-86aa-8b6d0e10df22', '逸材', 'いつざい', 'tài năng xuất sắc', false, 2, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a7159500-4e1f-48c9-8dee-2bb9a37c23d9', '3671130a-8ef0-490d-86aa-8b6d0e10df22', '逸脱する', 'いつだつする', 'bị sai lệch', false, 2, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a7159500-4e1f-48c9-8dee-2bb9a37c23d9', 'f75fbf2f-b767-4276-81eb-10bf42335fd1', '逸れる', 'それる', 'đánh trống lảng', false, 2, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a7159500-4e1f-48c9-8dee-2bb9a37c23d9', 'f75fbf2f-b767-4276-81eb-10bf42335fd1', '逸らす', 'そらす', 'lờ đi', false, 2, 'pdf', 'ok', NULL);

-- ---------- 令 (LỆNH) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('14ba2115-059b-4746-8793-0096d92266e4', 'N2', '令', 'LỆNH', 'mệnh lệnh', NULL, NULL, '令 hay đi sau các động từ chỉ hành động ra lệnh, chỉ thị.', NULL, '{}', 2, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'cbc39e21-1a3b-4996-8c06-20b9d38a1186', id, 'on', 'れい', true, 2, 'ok', NULL from jp_kanji where id = '14ba2115-059b-4746-8793-0096d92266e4' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('14ba2115-059b-4746-8793-0096d92266e4', 'cbc39e21-1a3b-4996-8c06-20b9d38a1186', '命令', 'めいれい', 'mệnh lệnh', false, 2, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('14ba2115-059b-4746-8793-0096d92266e4', 'cbc39e21-1a3b-4996-8c06-20b9d38a1186', '号令', 'ごうれい', 'hiệu lệnh', false, 2, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('14ba2115-059b-4746-8793-0096d92266e4', 'cbc39e21-1a3b-4996-8c06-20b9d38a1186', '指令', 'しれい', 'yêu cầu, mệnh lệnh', false, 2, 'pdf', 'ok', NULL);

-- ---------- 罠 (MÃN) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('2d25f439-c6c1-40e3-b9ac-3c0577753eb5', 'N2', '罠', 'MÃN', 'cái bẫy', NULL, NULL, '罠 = 罒(lưới) + 民 — lưới giăng bẫy người/thú.', NULL, '{}', 2, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'a0572ee6-d814-4f02-8797-48b6106c7ac1', id, 'kun', 'わな', true, 2, 'ok', NULL from jp_kanji where id = '2d25f439-c6c1-40e3-b9ac-3c0577753eb5' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('2d25f439-c6c1-40e3-b9ac-3c0577753eb5', 'a0572ee6-d814-4f02-8797-48b6106c7ac1', '罠', 'わな', 'cái bẫy', false, 2, 'pdf', 'ok', NULL);

-- ---------- 祭 (TẾ) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('319e8e13-06c9-415e-8968-0032fc19c2f3', 'N2', '祭', 'TẾ', 'lễ hội, cúng tế', NULL, NULL, '祭 = 示(bàn thờ) + tay cầm thịt — hình ảnh dâng lễ vật cúng tế.', NULL, '{}', 3, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '46d9bb4f-0a19-4687-bcb5-0290c899c26d', id, 'kun', 'まつ', true, 3, 'ok', NULL from jp_kanji where id = '319e8e13-06c9-415e-8968-0032fc19c2f3' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'cd3485ab-3422-4e26-8e5a-83b1df37f56c', id, 'on', 'さい', true, 3, 'ok', NULL from jp_kanji where id = '319e8e13-06c9-415e-8968-0032fc19c2f3' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('319e8e13-06c9-415e-8968-0032fc19c2f3', '46d9bb4f-0a19-4687-bcb5-0290c899c26d', '祭る', 'まつる', 'thờ cúng', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('319e8e13-06c9-415e-8968-0032fc19c2f3', 'cd3485ab-3422-4e26-8e5a-83b1df37f56c', '祭日', 'さいじつ', 'ngày lễ', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('319e8e13-06c9-415e-8968-0032fc19c2f3', 'cd3485ab-3422-4e26-8e5a-83b1df37f56c', '文化祭', 'ぶんかさい', 'lễ hội văn hóa', false, 3, 'pdf', 'ok', NULL);

-- ---------- 察 (SÁT) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('48932cf1-c49e-49d3-9b61-3bc71ad6a86c', 'N2', '察', 'SÁT', 'xem xét, quan sát', NULL, NULL, '察 = 宀(mái nhà) + 祭 — xem xét kỹ lưỡng như đang tế lễ, cẩn trọng từng chi tiết.', NULL, '{"祭"}', 3, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'c395ca40-dd7c-42c4-a0b8-b75439628d25', id, 'on', 'さつ', true, 3, 'ok', NULL from jp_kanji where id = '48932cf1-c49e-49d3-9b61-3bc71ad6a86c' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('48932cf1-c49e-49d3-9b61-3bc71ad6a86c', 'c395ca40-dd7c-42c4-a0b8-b75439628d25', '警察署', 'けいさつしょ', 'sở Cảnh sát', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('48932cf1-c49e-49d3-9b61-3bc71ad6a86c', 'c395ca40-dd7c-42c4-a0b8-b75439628d25', '考察する', 'こうさつする', 'tìm hiểu cặn kẽ', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('48932cf1-c49e-49d3-9b61-3bc71ad6a86c', 'c395ca40-dd7c-42c4-a0b8-b75439628d25', '診察', 'しんさつ', 'khám', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('48932cf1-c49e-49d3-9b61-3bc71ad6a86c', 'c395ca40-dd7c-42c4-a0b8-b75439628d25', '察する', 'さっする', 'hiểu được', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('48932cf1-c49e-49d3-9b61-3bc71ad6a86c', 'c395ca40-dd7c-42c4-a0b8-b75439628d25', '観察する', 'かんさつする', 'quan sát', false, 3, 'pdf', 'ok', NULL);

-- ---------- 際 (TẾ) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('81e0ffb4-732f-460b-b17e-90f260e8364e', 'N2', '際', 'TẾ', 'lúc, khi; giao tiếp quốc tế', NULL, NULL, '際 = 阝(gò đất) + 祭 — ranh giới, thời điểm giao nhau giữa 2 việc/2 bên.', '際 và 祭 cùng Hán Việt "TẾ" nhưng nghĩa khác hẳn (際 = lúc/giao tiếp, 祭 = cúng tế/lễ hội).', '{"祭"}', 3, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'eacfd62f-db56-4293-a9fb-f7c0570c9f9c', id, 'kun', 'きわ', true, 3, 'ok', NULL from jp_kanji where id = '81e0ffb4-732f-460b-b17e-90f260e8364e' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'f7385e94-40a7-4edd-8a9e-83955c2c1e38', id, 'on', 'さい', true, 3, 'ok', NULL from jp_kanji where id = '81e0ffb4-732f-460b-b17e-90f260e8364e' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('81e0ffb4-732f-460b-b17e-90f260e8364e', 'eacfd62f-db56-4293-a9fb-f7c0570c9f9c', '際どい', 'きわどい', 'tế nhị', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('81e0ffb4-732f-460b-b17e-90f260e8364e', 'eacfd62f-db56-4293-a9fb-f7c0570c9f9c', '窓際', 'まどぎわ', 'bên khung cửa sổ', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('81e0ffb4-732f-460b-b17e-90f260e8364e', 'f7385e94-40a7-4edd-8a9e-83955c2c1e38', '際', 'さい', 'khi, lúc', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('81e0ffb4-732f-460b-b17e-90f260e8364e', 'f7385e94-40a7-4edd-8a9e-83955c2c1e38', '交際する', 'こうさいする', 'hẹn hò', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('81e0ffb4-732f-460b-b17e-90f260e8364e', 'f7385e94-40a7-4edd-8a9e-83955c2c1e38', '国際結婚', 'こくさいけっこん', 'kết hôn với người nước ngoài', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('81e0ffb4-732f-460b-b17e-90f260e8364e', 'f7385e94-40a7-4edd-8a9e-83955c2c1e38', '国際的', 'こくさいてき', 'tầm cỡ quốc tế', false, 3, 'pdf', 'ok', NULL);

-- ---------- 垂 (THÙY) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('ad98d3fd-47a5-462c-bc33-a3b0bff285ba', 'N2', '垂', 'THÙY', 'rủ xuống, treo', NULL, NULL, '垂 tượng hình cành lá rủ xuống — chảy xuống, treo thẳng đứng.', NULL, '{}', 3, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '5554a700-9696-41cb-a584-de81e6b87ada', id, 'kun', 'た', true, 3, 'ok', NULL from jp_kanji where id = 'ad98d3fd-47a5-462c-bc33-a3b0bff285ba' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '275d5be8-7b4d-4969-ace1-c6df4b2b763b', id, 'on', 'すい', true, 3, 'ok', NULL from jp_kanji where id = 'ad98d3fd-47a5-462c-bc33-a3b0bff285ba' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('ad98d3fd-47a5-462c-bc33-a3b0bff285ba', '5554a700-9696-41cb-a584-de81e6b87ada', '垂れる', 'たれる', 'chảy xuống', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('ad98d3fd-47a5-462c-bc33-a3b0bff285ba', '5554a700-9696-41cb-a584-de81e6b87ada', '垂らす', 'たらす', 'thả xuống', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('ad98d3fd-47a5-462c-bc33-a3b0bff285ba', '275d5be8-7b4d-4969-ace1-c6df4b2b763b', '懸垂', 'けんすい', 'treo thẳng đứng, hít xà đơn', false, 3, 'pdf', 'ok', NULL);

-- ---------- 郵 (BƯU) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('86619b6d-dc01-441a-9166-9f7a260006df', 'N2', '郵', 'BƯU', 'bưu điện, gửi thư', NULL, NULL, '郵 hay đi kèm 便/送 để chỉ việc gửi thư/hàng qua bưu điện.', NULL, '{}', 3, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'dc1b4b1d-3f67-4fe6-8436-7f96c736bf4e', id, 'on', 'ゆう', true, 3, 'ok', NULL from jp_kanji where id = '86619b6d-dc01-441a-9166-9f7a260006df' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('86619b6d-dc01-441a-9166-9f7a260006df', 'dc1b4b1d-3f67-4fe6-8436-7f96c736bf4e', '郵便', 'ゆうびん', 'bưu điện', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('86619b6d-dc01-441a-9166-9f7a260006df', 'dc1b4b1d-3f67-4fe6-8436-7f96c736bf4e', '郵便局', 'ゆうびんきょく', 'bưu điện', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('86619b6d-dc01-441a-9166-9f7a260006df', 'dc1b4b1d-3f67-4fe6-8436-7f96c736bf4e', '郵送する', 'ゆうそうする', 'gửi qua bưu điện', false, 3, 'pdf', 'ok', NULL);

-- ---------- 睡 (THỤY) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('9d8fadee-644a-44ea-aea5-a556b6833133', 'N2', '睡', 'THỤY', 'ngủ', NULL, NULL, '睡 = 目(mắt) + 垂(rủ xuống) — mí mắt rủ xuống là buồn ngủ.', NULL, '{"垂","眠"}', 3, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '51d943d6-f06d-4e67-8f6b-083f2450e453', id, 'on', 'すい', true, 3, 'ok', NULL from jp_kanji where id = '9d8fadee-644a-44ea-aea5-a556b6833133' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9d8fadee-644a-44ea-aea5-a556b6833133', '51d943d6-f06d-4e67-8f6b-083f2450e453', '爆睡する', 'ばくすいする', 'ngủ say', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9d8fadee-644a-44ea-aea5-a556b6833133', '51d943d6-f06d-4e67-8f6b-083f2450e453', '一睡', 'いっすい', 'chợp mắt', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9d8fadee-644a-44ea-aea5-a556b6833133', '51d943d6-f06d-4e67-8f6b-083f2450e453', '睡眠', 'すいみん', 'giấc ngủ', false, 3, 'pdf', 'ok', NULL);

-- ---------- 票 (PHIẾU) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('ffd57750-a907-415f-ae5c-14432df89cc0', 'N2', '票', 'PHIẾU', 'lá phiếu', NULL, NULL, '票 hay đi với 投/伝 để chỉ giấy tờ dùng để bầu chọn hoặc ghi chép.', NULL, '{}', 3, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'e99cffda-62a4-4557-b359-361dcbea087b', id, 'on', 'ひょう', true, 3, 'ok', NULL from jp_kanji where id = 'ffd57750-a907-415f-ae5c-14432df89cc0' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('ffd57750-a907-415f-ae5c-14432df89cc0', 'e99cffda-62a4-4557-b359-361dcbea087b', '一票', 'いっぴょう', 'một lá phiếu', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('ffd57750-a907-415f-ae5c-14432df89cc0', 'e99cffda-62a4-4557-b359-361dcbea087b', '票', 'ひょう', 'lá phiếu', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('ffd57750-a907-415f-ae5c-14432df89cc0', 'e99cffda-62a4-4557-b359-361dcbea087b', '伝票', 'でんぴょう', 'phiếu thu', false, 3, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('ffd57750-a907-415f-ae5c-14432df89cc0', 'e99cffda-62a4-4557-b359-361dcbea087b', '投票する', 'とうひょうする', 'bỏ phiếu', false, 3, 'pdf', 'ok', NULL);

-- ---------- jp_kanji_questions: PDF không có 問題 cho phần Kanji, toàn bộ generated ----------
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"丼" đọc là gì (trong từ "丼")?', 'どんぶり', 'まつ', 'い', 'さい', 'どんぶり', 'generated' from jp_kanji where id = '0329fffa-1996-4ae1-9b0b-395dbb7bb55b';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "cái tô lớn, cơm tô (kiểu donburi)"?', '票', '垂', '丼', '睡', '丼', 'generated' from jp_kanji where id = '0329fffa-1996-4ae1-9b0b-395dbb7bb55b';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"丼" (どんぶり) nghĩa là gì?', 'tầm cỡ quốc tế', 'cái tô, bát loa', 'ngủ say', 'treo thẳng đứng, hít xà đơn', 'cái tô, bát loa', 'generated' from jp_kanji where id = '0329fffa-1996-4ae1-9b0b-395dbb7bb55b';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 天丼 (cơm tempura)', 'てんどん', 'generated' from jp_kanji where id = '0329fffa-1996-4ae1-9b0b-395dbb7bb55b';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"囲" đọc là gì (trong từ "囲む")?', 'た', 'すい', 'さい', 'かこ', 'かこ', 'generated' from jp_kanji where id = 'aa42fae9-54b9-4b20-9b52-e75f7145a352';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "bao quanh, phạm vi"?', '逸', '垂', '郵', '囲', '囲', 'generated' from jp_kanji where id = 'aa42fae9-54b9-4b20-9b52-e75f7145a352';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"囲む" (かこむ) nghĩa là gì?', 'bị sai lệch', 'chợp mắt', 'quây quần', 'cái bẫy', 'quây quần', 'generated' from jp_kanji where id = 'aa42fae9-54b9-4b20-9b52-e75f7145a352';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 囲う (quây lại)', 'かこう', 'generated' from jp_kanji where id = 'aa42fae9-54b9-4b20-9b52-e75f7145a352';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"逸" đọc là gì (trong từ "逸材")?', 'い', 'さい', 'いつ', 'た', 'いつ', 'generated' from jp_kanji where id = 'a7159500-4e1f-48c9-8dee-2bb9a37c23d9';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "xuất sắc; lệch, trốn tránh"?', '罠', '令', '囲', '逸', '逸', 'generated' from jp_kanji where id = 'a7159500-4e1f-48c9-8dee-2bb9a37c23d9';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"逸材" (いつざい) nghĩa là gì?', 'quây quần', 'khám', 'tài năng xuất sắc', 'cơm thịt tấm bột chiên', 'tài năng xuất sắc', 'generated' from jp_kanji where id = 'a7159500-4e1f-48c9-8dee-2bb9a37c23d9';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 逸脱する (bị sai lệch)', 'いつだつする', 'generated' from jp_kanji where id = 'a7159500-4e1f-48c9-8dee-2bb9a37c23d9';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"令" đọc là gì (trong từ "命令")?', 'れい', 'かこ', 'ゆう', 'さい', 'れい', 'generated' from jp_kanji where id = '14ba2115-059b-4746-8793-0096d92266e4';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "mệnh lệnh"?', '罠', '睡', '囲', '令', '令', 'generated' from jp_kanji where id = '14ba2115-059b-4746-8793-0096d92266e4';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"命令" (めいれい) nghĩa là gì?', 'mệnh lệnh', 'tế nhị', 'phạm vi', 'hiệu lệnh', 'mệnh lệnh', 'generated' from jp_kanji where id = '14ba2115-059b-4746-8793-0096d92266e4';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 号令 (hiệu lệnh)', 'ごうれい', 'generated' from jp_kanji where id = '14ba2115-059b-4746-8793-0096d92266e4';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"罠" đọc là gì (trong từ "罠")?', 'さつ', 'わな', 'どんぶり', 'ゆう', 'わな', 'generated' from jp_kanji where id = '2d25f439-c6c1-40e3-b9ac-3c0577753eb5';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "cái bẫy"?', '祭', '郵', '罠', '睡', '罠', 'generated' from jp_kanji where id = '2d25f439-c6c1-40e3-b9ac-3c0577753eb5';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"罠" (わな) nghĩa là gì?', 'bỏ phiếu', 'tế nhị', 'cái bẫy', 'đánh trống lảng', 'cái bẫy', 'generated' from jp_kanji where id = '2d25f439-c6c1-40e3-b9ac-3c0577753eb5';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 罠 (cái bẫy)', 'わな', 'generated' from jp_kanji where id = '2d25f439-c6c1-40e3-b9ac-3c0577753eb5';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"祭" đọc là gì (trong từ "祭る")?', 'すい', 'どんぶり', 'そ', 'まつ', 'まつ', 'generated' from jp_kanji where id = '319e8e13-06c9-415e-8968-0032fc19c2f3';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "lễ hội, cúng tế"?', '察', '囲', '逸', '祭', '祭', 'generated' from jp_kanji where id = '319e8e13-06c9-415e-8968-0032fc19c2f3';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"祭る" (まつる) nghĩa là gì?', 'thờ cúng', 'chợp mắt', 'tầm cỡ quốc tế', 'treo thẳng đứng, hít xà đơn', 'thờ cúng', 'generated' from jp_kanji where id = '319e8e13-06c9-415e-8968-0032fc19c2f3';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 祭日 (ngày lễ)', 'さいじつ', 'generated' from jp_kanji where id = '319e8e13-06c9-415e-8968-0032fc19c2f3';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"察" đọc là gì (trong từ "警察署")?', 'すい', 'さつ', 'さい', 'ゆう', 'さつ', 'generated' from jp_kanji where id = '48932cf1-c49e-49d3-9b61-3bc71ad6a86c';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "xem xét, quan sát"?', '垂', '票', '察', '罠', '察', 'generated' from jp_kanji where id = '48932cf1-c49e-49d3-9b61-3bc71ad6a86c';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"警察署" (けいさつしょ) nghĩa là gì?', 'sở Cảnh sát', 'quây quần', 'mệnh lệnh', 'bỏ phiếu', 'sở Cảnh sát', 'generated' from jp_kanji where id = '48932cf1-c49e-49d3-9b61-3bc71ad6a86c';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 考察する (tìm hiểu cặn kẽ)', 'こうさつする', 'generated' from jp_kanji where id = '48932cf1-c49e-49d3-9b61-3bc71ad6a86c';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"際" đọc là gì (trong từ "際どい")?', 'きわ', 'さつ', 'い', 'いつ', 'きわ', 'generated' from jp_kanji where id = '81e0ffb4-732f-460b-b17e-90f260e8364e';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "lúc, khi; giao tiếp quốc tế"?', '睡', '際', '郵', '丼', '際', 'generated' from jp_kanji where id = '81e0ffb4-732f-460b-b17e-90f260e8364e';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"際どい" (きわどい) nghĩa là gì?', 'tế nhị', 'phạm vi', 'lễ hội văn hóa', 'yêu cầu, mệnh lệnh', 'tế nhị', 'generated' from jp_kanji where id = '81e0ffb4-732f-460b-b17e-90f260e8364e';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 窓際 (bên khung cửa sổ)', 'まどぎわ', 'generated' from jp_kanji where id = '81e0ffb4-732f-460b-b17e-90f260e8364e';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"垂" đọc là gì (trong từ "垂れる")?', 'た', 'さつ', 'まつ', 'きわ', 'た', 'generated' from jp_kanji where id = 'ad98d3fd-47a5-462c-bc33-a3b0bff285ba';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "rủ xuống, treo"?', '垂', '逸', '罠', '察', '垂', 'generated' from jp_kanji where id = 'ad98d3fd-47a5-462c-bc33-a3b0bff285ba';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"垂れる" (たれる) nghĩa là gì?', 'chảy xuống', 'mệnh lệnh', 'khi, lúc', 'giấc ngủ', 'chảy xuống', 'generated' from jp_kanji where id = 'ad98d3fd-47a5-462c-bc33-a3b0bff285ba';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 垂らす (thả xuống)', 'たらす', 'generated' from jp_kanji where id = 'ad98d3fd-47a5-462c-bc33-a3b0bff285ba';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"郵" đọc là gì (trong từ "郵便")?', 'い', 'た', 'さい', 'ゆう', 'ゆう', 'generated' from jp_kanji where id = '86619b6d-dc01-441a-9166-9f7a260006df';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "bưu điện, gửi thư"?', '令', '垂', '祭', '郵', '郵', 'generated' from jp_kanji where id = '86619b6d-dc01-441a-9166-9f7a260006df';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"郵便" (ゆうびん) nghĩa là gì?', 'ngày lễ', 'bưu điện', 'tìm hiểu cặn kẽ', 'lờ đi', 'bưu điện', 'generated' from jp_kanji where id = '86619b6d-dc01-441a-9166-9f7a260006df';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 郵便局 (bưu điện)', 'ゆうびんきょく', 'generated' from jp_kanji where id = '86619b6d-dc01-441a-9166-9f7a260006df';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"睡" đọc là gì (trong từ "爆睡する")?', 'すい', 'い', 'わな', 'かこ', 'すい', 'generated' from jp_kanji where id = '9d8fadee-644a-44ea-aea5-a556b6833133';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "ngủ"?', '睡', '察', '令', '際', '睡', 'generated' from jp_kanji where id = '9d8fadee-644a-44ea-aea5-a556b6833133';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"爆睡する" (ばくすいする) nghĩa là gì?', 'ngủ say', 'tìm hiểu cặn kẽ', 'cơm tempura', 'hẹn hò', 'ngủ say', 'generated' from jp_kanji where id = '9d8fadee-644a-44ea-aea5-a556b6833133';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 一睡 (chợp mắt)', 'いっすい', 'generated' from jp_kanji where id = '9d8fadee-644a-44ea-aea5-a556b6833133';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"票" đọc là gì (trong từ "一票")?', 'い', 'た', 'わな', 'ひょう', 'ひょう', 'generated' from jp_kanji where id = 'ffd57750-a907-415f-ae5c-14432df89cc0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "lá phiếu"?', '票', '郵', '罠', '睡', '票', 'generated' from jp_kanji where id = 'ffd57750-a907-415f-ae5c-14432df89cc0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"一票" (いっぴょう) nghĩa là gì?', 'ngày lễ', 'phiếu thu', 'bên khung cửa sổ', 'một lá phiếu', 'một lá phiếu', 'generated' from jp_kanji where id = 'ffd57750-a907-415f-ae5c-14432df89cc0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 票 (lá phiếu)', 'ひょう', 'generated' from jp_kanji where id = 'ffd57750-a907-415f-ae5c-14432df89cc0';

-- Tổng 48 câu hỏi generated cho 12 kanji.
