-- ============================================================
-- jp-go — Kanji N2, round 3 (15 kanji). Nguồn: PDF "Tổng hợp kiến
-- thức N2" (Dũng Mori), PART 1 - 漢字, trang in 4 (標/漂/周/彫/調/
-- 兼/嫌/謙) và trang in 5 (更/便/硬/充/銃/統/害). Cùng cơ chế các
-- round trước: tự tách furigana ứng đúng kanji, tự phân loại on/kun,
-- không bịa âm không có trong PDF.
--
-- Nhóm dễ nhầm mặt chữ 兼/嫌/謙 (kiêm/hiềm/khiêm) — đánh dấu
-- common_mistake/similar_kanji chéo nhau cả 3.
-- ============================================================

-- ---------- 標 (TIÊU) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('3a2c518e-1110-4eef-88b0-7c91febe09bd', 'N2', '標', 'TIÊU', 'tiêu chuẩn, mục tiêu, biển báo', NULL, NULL, '標 = 木(cây) + 票(phiếu) — cột mốc/biển hiệu dựng lên để đánh dấu.', NULL, '{"票"}', 4, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '052d3904-f7d5-44e2-ac01-5cc502032012', id, 'on', 'ひょう', true, 4, 'ok', NULL from jp_kanji where id = '3a2c518e-1110-4eef-88b0-7c91febe09bd' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('3a2c518e-1110-4eef-88b0-7c91febe09bd', '052d3904-f7d5-44e2-ac01-5cc502032012', '標準語', 'ひょうじゅんご', 'ngôn ngữ phổ thông', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('3a2c518e-1110-4eef-88b0-7c91febe09bd', '052d3904-f7d5-44e2-ac01-5cc502032012', '標識', 'ひょうしき', 'biển báo', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('3a2c518e-1110-4eef-88b0-7c91febe09bd', '052d3904-f7d5-44e2-ac01-5cc502032012', '標本', 'ひょうほん', 'tiêu bản', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('3a2c518e-1110-4eef-88b0-7c91febe09bd', '052d3904-f7d5-44e2-ac01-5cc502032012', '目標', 'もくひょう', 'mục tiêu', false, 4, 'pdf', 'ok', NULL);

-- ---------- 漂 (PHIÊU) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('12b5a33a-853b-4354-a56e-283cd82bb23b', 'N2', '漂', 'PHIÊU', 'trôi nổi, tẩy trắng', NULL, NULL, '漂 = 氵(nước) + 票 — trôi bồng bềnh trên mặt nước.', NULL, '{"標"}', 4, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'd13eb89f-93c4-486a-8212-d5a2c7d0af17', id, 'kun', 'ただよ', true, 4, 'ok', NULL from jp_kanji where id = '12b5a33a-853b-4354-a56e-283cd82bb23b' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '16d73080-021a-4cd6-94de-0866d3fc81bf', id, 'on', 'ひょう', true, 4, 'ok', NULL from jp_kanji where id = '12b5a33a-853b-4354-a56e-283cd82bb23b' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('12b5a33a-853b-4354-a56e-283cd82bb23b', 'd13eb89f-93c4-486a-8212-d5a2c7d0af17', '漂う', 'ただよう', 'trôi nổi', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('12b5a33a-853b-4354-a56e-283cd82bb23b', '16d73080-021a-4cd6-94de-0866d3fc81bf', '漂白剤', 'ひょうはくざい', 'chất tẩy trắng', false, 4, 'pdf', 'ok', NULL);

-- ---------- 周 (CHU) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('6bfa4fbe-28f2-4ff1-8ae0-da13974096e0', 'N2', '周', 'CHU', 'xung quanh, vòng quanh', NULL, NULL, '周 tượng hình ruộng đất được bao quanh khép kín — chu vi, vòng quanh.', NULL, '{}', 4, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '3e717653-aac0-4b9f-9cc8-c770375c7314', id, 'on', 'しゅう', true, 4, 'ok', NULL from jp_kanji where id = '6bfa4fbe-28f2-4ff1-8ae0-da13974096e0' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '00d16ff6-8ac0-469a-8cf3-6eea0d296193', id, 'kun', 'まわ', true, 4, 'ok', NULL from jp_kanji where id = '6bfa4fbe-28f2-4ff1-8ae0-da13974096e0' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('6bfa4fbe-28f2-4ff1-8ae0-da13974096e0', '3e717653-aac0-4b9f-9cc8-c770375c7314', '周辺', 'しゅうへん', 'quanh khu vực', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('6bfa4fbe-28f2-4ff1-8ae0-da13974096e0', '00d16ff6-8ac0-469a-8cf3-6eea0d296193', '周り', 'まわり', 'xung quanh', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('6bfa4fbe-28f2-4ff1-8ae0-da13974096e0', '3e717653-aac0-4b9f-9cc8-c770375c7314', '一周', 'いっしゅう', 'một vòng', false, 4, 'pdf', 'ok', NULL);

-- ---------- 彫 (ĐIÊU) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('660c892a-b3d1-4b2a-a4a3-d375e81bf321', 'N2', '彫', 'ĐIÊU', 'khắc, chạm trổ', NULL, NULL, '彫 = 周 + 彡(nét vẽ) — khắc từng đường nét quanh bề mặt.', NULL, '{"周"}', 4, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'a57741b6-aa1a-4234-bfcb-47b60ad70ed8', id, 'kun', 'ほ', true, 4, 'ok', NULL from jp_kanji where id = '660c892a-b3d1-4b2a-a4a3-d375e81bf321' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '1ca3433f-f4d5-4e6a-b21a-a2437cfccd1d', id, 'on', 'ちょう', true, 4, 'ok', NULL from jp_kanji where id = '660c892a-b3d1-4b2a-a4a3-d375e81bf321' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('660c892a-b3d1-4b2a-a4a3-d375e81bf321', 'a57741b6-aa1a-4234-bfcb-47b60ad70ed8', '彫る', 'ほる', 'khắc', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('660c892a-b3d1-4b2a-a4a3-d375e81bf321', '1ca3433f-f4d5-4e6a-b21a-a2437cfccd1d', '彫刻', 'ちょうこく', 'điêu khắc', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('660c892a-b3d1-4b2a-a4a3-d375e81bf321', '1ca3433f-f4d5-4e6a-b21a-a2437cfccd1d', '彫刻刀', 'ちょうこくとう', 'dao khắc', false, 4, 'pdf', 'ok', NULL);

-- ---------- 調 (ĐIỀU) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('f0dd1c6f-c448-4e2a-bfa6-1063145dcc4d', 'N2', '調', 'ĐIỀU', 'điều chỉnh, nêm nếm, trạng thái', NULL, NULL, '調 = 言(lời nói) + 周 — nói/chỉnh sửa cho vừa vặn, đúng điệu.', NULL, '{}', 4, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '0792dbba-2099-41c6-87ef-93eee8a86758', id, 'kun', 'ととの', true, 4, 'ok', NULL from jp_kanji where id = 'f0dd1c6f-c448-4e2a-bfa6-1063145dcc4d' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '213787ee-2653-4b1d-8809-75764fdaf4b3', id, 'on', 'ちょう', true, 4, 'ok', NULL from jp_kanji where id = 'f0dd1c6f-c448-4e2a-bfa6-1063145dcc4d' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('f0dd1c6f-c448-4e2a-bfa6-1063145dcc4d', '0792dbba-2099-41c6-87ef-93eee8a86758', '調える', 'ととのえる', 'nêm, chuẩn bị', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('f0dd1c6f-c448-4e2a-bfa6-1063145dcc4d', '213787ee-2653-4b1d-8809-75764fdaf4b3', '調子', 'ちょうし', 'trạng thái', false, 4, 'pdf', 'ok', NULL);

-- ---------- 兼 (KIÊM) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('02d7d40d-5b49-4aa2-8aad-890db2e85ab7', 'N2', '兼', 'KIÊM', 'kiêm, kiêm nhiệm', NULL, NULL, '兼 tượng hình 1 tay cầm 2 bó lúa — kiêm nhiệm nhiều việc cùng lúc.', NULL, '{"嫌","謙"}', 4, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '74cfd8b3-52ab-4978-a165-e56e32cc8324', id, 'on', 'けん', true, 4, 'ok', NULL from jp_kanji where id = '02d7d40d-5b49-4aa2-8aad-890db2e85ab7' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('02d7d40d-5b49-4aa2-8aad-890db2e85ab7', '74cfd8b3-52ab-4978-a165-e56e32cc8324', '兼任する', 'けんにんする', 'kiêm nhiệm', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('02d7d40d-5b49-4aa2-8aad-890db2e85ab7', '74cfd8b3-52ab-4978-a165-e56e32cc8324', '兼業', 'けんぎょう', 'nghề phụ', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('02d7d40d-5b49-4aa2-8aad-890db2e85ab7', '74cfd8b3-52ab-4978-a165-e56e32cc8324', '兼用する', 'けんようする', 'dùng chung', false, 4, 'pdf', 'ok', NULL);

-- ---------- 嫌 (HIỀM) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8', 'N2', '嫌', 'HIỀM', 'ghét, khó chịu', NULL, NULL, '嫌 = 女 + 兼 — cảm xúc khó chịu, không ưa.', '嫌 (ghét) rất dễ nhầm mặt chữ với 兼 (kiêm) và 謙 (khiêm tốn) — chú ý bộ 女/言 để phân biệt.', '{"兼","謙"}', 4, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '06a6d007-629a-4511-a20f-16c477b62b06', id, 'kun', 'きら', true, 4, 'ok', NULL from jp_kanji where id = 'a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'cbb60451-ae35-46ad-8380-61296d66a589', id, 'kun', 'いや', true, 4, 'ok', NULL from jp_kanji where id = 'a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '13189dc7-9f95-411e-991d-280b0304c280', id, 'on', 'けん', true, 4, 'ok', NULL from jp_kanji where id = 'a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8', '06a6d007-629a-4511-a20f-16c477b62b06', '嫌い', 'きらい', 'ghét', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8', '13189dc7-9f95-411e-991d-280b0304c280', '機嫌', 'きげん', 'tâm trạng', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8', '13189dc7-9f95-411e-991d-280b0304c280', '自己嫌悪', 'じこけんお', 'trạng thái tự căm ghét bản thân', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8', 'cbb60451-ae35-46ad-8380-61296d66a589', '嫌がる', 'いやがる', 'ghét', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8', '06a6d007-629a-4511-a20f-16c477b62b06', '嫌う', 'きらう', 'ghét', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8', 'cbb60451-ae35-46ad-8380-61296d66a589', '嫌な', 'いやな', 'không ưa', false, 4, 'pdf', 'ok', NULL);

-- ---------- 謙 (KHIÊM) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('471acd28-1476-4878-ba69-37f595f5cab8', 'N2', '謙', 'KHIÊM', 'khiêm tốn', NULL, NULL, '謙 = 言(lời nói) + 兼 — lời nói khiêm nhường, không phô trương.', '謙 (khiêm tốn) dễ nhầm mặt chữ với 嫌 (ghét) và 兼 (kiêm) — chú ý bộ 言 riêng của 謙.', '{"兼","嫌"}', 4, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'ac7287c1-b2df-43fc-bffa-47c71c95fdae', id, 'on', 'けん', true, 4, 'ok', NULL from jp_kanji where id = '471acd28-1476-4878-ba69-37f595f5cab8' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('471acd28-1476-4878-ba69-37f595f5cab8', 'ac7287c1-b2df-43fc-bffa-47c71c95fdae', '謙譲語', 'けんじょうご', 'khiêm nhường ngữ', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('471acd28-1476-4878-ba69-37f595f5cab8', 'ac7287c1-b2df-43fc-bffa-47c71c95fdae', '謙虚', 'けんきょ', 'khiêm tốn (đức tính)', false, 4, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('471acd28-1476-4878-ba69-37f595f5cab8', 'ac7287c1-b2df-43fc-bffa-47c71c95fdae', '謙遜', 'けんそん', 'khiêm tốn (cách ứng xử)', false, 4, 'pdf', 'ok', NULL);

-- ---------- 更 (CANH) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('da08ea2a-5860-4d05-8f14-c2f01aa8533f', 'N2', '更', 'CANH', 'thay đổi, canh (giờ khuya)', NULL, NULL, '更 hay đi với 変/新 để chỉ việc thay đổi, cập nhật; kun ふ- chỉ đêm khuya dần trôi qua.', NULL, '{}', 5, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '1989be9b-8479-4bfe-8380-abc81268afe4', id, 'on', 'こう', true, 5, 'ok', NULL from jp_kanji where id = 'da08ea2a-5860-4d05-8f14-c2f01aa8533f' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'df95fb20-d908-43b5-a627-2192f6ab3f2e', id, 'kun', 'ふ', true, 5, 'ok', NULL from jp_kanji where id = 'da08ea2a-5860-4d05-8f14-c2f01aa8533f' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('da08ea2a-5860-4d05-8f14-c2f01aa8533f', '1989be9b-8479-4bfe-8380-abc81268afe4', '更新する', 'こうしんする', 'gia hạn', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('da08ea2a-5860-4d05-8f14-c2f01aa8533f', '1989be9b-8479-4bfe-8380-abc81268afe4', '変更する', 'へんこうする', 'thay đổi', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('da08ea2a-5860-4d05-8f14-c2f01aa8533f', 'df95fb20-d908-43b5-a627-2192f6ab3f2e', '夜が更ける', 'よがふける', 'đêm khuya', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('da08ea2a-5860-4d05-8f14-c2f01aa8533f', 'df95fb20-d908-43b5-a627-2192f6ab3f2e', '夜更かし', 'よふかし', 'thức đêm', false, 5, 'pdf', 'ok', NULL);

-- ---------- 便 (TIỆN) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('6f4fccae-2288-4120-9515-4a16eed76855', 'N2', '便', 'TIỆN', 'tiện lợi, thư từ', NULL, NULL, '便 = 亻(người) + 更 — người thay đổi cách làm để cho tiện hơn.', NULL, '{}', 5, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '992da276-fd34-42db-aa49-297133a0adaa', id, 'on', 'べん', true, 5, 'ok', NULL from jp_kanji where id = '6f4fccae-2288-4120-9515-4a16eed76855' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('6f4fccae-2288-4120-9515-4a16eed76855', '992da276-fd34-42db-aa49-297133a0adaa', '便利', 'べんり', 'tiện lợi', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('6f4fccae-2288-4120-9515-4a16eed76855', '992da276-fd34-42db-aa49-297133a0adaa', '郵便局', 'ゆうびんきょく', 'bưu điện', false, 5, 'pdf', 'ok', NULL);

-- ---------- 硬 (NGẠCH) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('3b5015c5-9a08-4551-ac13-cc768079071b', 'N2', '硬', 'NGẠCH', 'cứng, cứng rắn', NULL, NULL, '硬 = 石(đá) + 更 — cứng như đá.', NULL, '{}', 5, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '8bf1eec2-2e69-48cd-8ef5-ef80d9c8b835', id, 'on', 'こう', true, 5, 'ok', NULL from jp_kanji where id = '3b5015c5-9a08-4551-ac13-cc768079071b' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '9aea64f8-25a2-40e4-b24b-8e81773ac99d', id, 'kun', 'かた', true, 5, 'ok', NULL from jp_kanji where id = '3b5015c5-9a08-4551-ac13-cc768079071b' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('3b5015c5-9a08-4551-ac13-cc768079071b', '8bf1eec2-2e69-48cd-8ef5-ef80d9c8b835', '強硬な', 'きょうこうな', 'cứng rắn', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('3b5015c5-9a08-4551-ac13-cc768079071b', '8bf1eec2-2e69-48cd-8ef5-ef80d9c8b835', '硬貨', 'こうか', 'đồng xu', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('3b5015c5-9a08-4551-ac13-cc768079071b', '9aea64f8-25a2-40e4-b24b-8e81773ac99d', '硬い', 'かたい', 'cứng nhắc', false, 5, 'pdf', 'ok', NULL);

-- ---------- 充 (SUNG) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('5ebf3991-6022-4272-abfe-49a51496e133', 'N2', '充', 'SUNG', 'đầy đủ, sạc, lấp đầy', NULL, NULL, '充 hay đi với 分/実/電 để chỉ trạng thái đầy đủ, được nạp/sạc đầy.', NULL, '{}', 5, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'dd594f62-46a9-4537-98ab-b4d2eeee7279', id, 'on', 'じゅう', true, 5, 'ok', NULL from jp_kanji where id = '5ebf3991-6022-4272-abfe-49a51496e133' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '1be9c086-3fd9-41b1-8cc6-8c577deba048', id, 'kun', 'あ', true, 5, 'ok', NULL from jp_kanji where id = '5ebf3991-6022-4272-abfe-49a51496e133' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('5ebf3991-6022-4272-abfe-49a51496e133', 'dd594f62-46a9-4537-98ab-b4d2eeee7279', '充分', 'じゅうぶん', 'đầy đủ', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('5ebf3991-6022-4272-abfe-49a51496e133', 'dd594f62-46a9-4537-98ab-b4d2eeee7279', '充実する', 'じゅうじつする', 'ý nghĩa', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('5ebf3991-6022-4272-abfe-49a51496e133', '1be9c086-3fd9-41b1-8cc6-8c577deba048', '充てる', 'あてる', 'trang trải', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('5ebf3991-6022-4272-abfe-49a51496e133', 'dd594f62-46a9-4537-98ab-b4d2eeee7279', '充電する', 'じゅうでんする', 'sạc điện', false, 5, 'pdf', 'ok', NULL);

-- ---------- 銃 (SÚNG) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('e18168b9-2252-4b3f-8aed-27c8b92871c0', 'N2', '銃', 'SÚNG', 'súng', NULL, NULL, '銃 = 金(kim loại) + 充 — vật kim loại nạp đạn, tức là súng.', NULL, '{"充"}', 5, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '67ba12f3-c5ed-471d-a807-0a183d8f2581', id, 'on', 'じゅう', true, 5, 'ok', NULL from jp_kanji where id = 'e18168b9-2252-4b3f-8aed-27c8b92871c0' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('e18168b9-2252-4b3f-8aed-27c8b92871c0', '67ba12f3-c5ed-471d-a807-0a183d8f2581', '拳銃', 'けんじゅう', 'súng', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('e18168b9-2252-4b3f-8aed-27c8b92871c0', '67ba12f3-c5ed-471d-a807-0a183d8f2581', '銃弾', 'じゅうだん', 'viên đạn', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('e18168b9-2252-4b3f-8aed-27c8b92871c0', '67ba12f3-c5ed-471d-a807-0a183d8f2581', '銃', 'じゅう', 'súng', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('e18168b9-2252-4b3f-8aed-27c8b92871c0', '67ba12f3-c5ed-471d-a807-0a183d8f2581', '銃口', 'じゅうこう', 'họng súng', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('e18168b9-2252-4b3f-8aed-27c8b92871c0', '67ba12f3-c5ed-471d-a807-0a183d8f2581', '銃撃戦', 'じゅうげきせん', 'cuộc đọ súng', false, 5, 'pdf', 'ok', NULL);

-- ---------- 統 (THỐNG) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('9772278b-8f3e-4786-b6fc-780c6a3c3018', 'N2', '統', 'THỐNG', 'thống nhất, hệ thống', NULL, NULL, '統 = 糸(sợi chỉ) + 充 — các sợi chỉ được gom mối lại thành một hệ thống.', NULL, '{}', 5, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '1a4be8fb-b2fc-4e43-9adf-ec4aa6a336c8', id, 'on', 'とう', true, 5, 'ok', NULL from jp_kanji where id = '9772278b-8f3e-4786-b6fc-780c6a3c3018' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9772278b-8f3e-4786-b6fc-780c6a3c3018', '1a4be8fb-b2fc-4e43-9adf-ec4aa6a336c8', '統計', 'とうけい', 'thống kê', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9772278b-8f3e-4786-b6fc-780c6a3c3018', '1a4be8fb-b2fc-4e43-9adf-ec4aa6a336c8', '伝統', 'でんとう', 'truyền thống', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9772278b-8f3e-4786-b6fc-780c6a3c3018', '1a4be8fb-b2fc-4e43-9adf-ec4aa6a336c8', '統一', 'とういつ', 'thống nhất', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9772278b-8f3e-4786-b6fc-780c6a3c3018', '1a4be8fb-b2fc-4e43-9adf-ec4aa6a336c8', '統合する', 'とうごうする', 'tổng hợp', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9772278b-8f3e-4786-b6fc-780c6a3c3018', '1a4be8fb-b2fc-4e43-9adf-ec4aa6a336c8', '統治する', 'とうちする', 'cai trị', false, 5, 'pdf', 'ok', NULL);

-- ---------- 害 (HẠI) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('062fbf1b-a2a4-45b2-9cf9-f82a83dda5b4', 'N2', '害', 'HẠI', 'thiệt hại, nguy hại', NULL, NULL, '害 tượng hình mái nhà đè lên miệng — lời nói/việc làm gây tổn hại.', NULL, '{}', 5, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'a5b8721f-ac97-46db-b16f-57572d0705dd', id, 'on', 'がい', true, 5, 'ok', NULL from jp_kanji where id = '062fbf1b-a2a4-45b2-9cf9-f82a83dda5b4' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('062fbf1b-a2a4-45b2-9cf9-f82a83dda5b4', 'a5b8721f-ac97-46db-b16f-57572d0705dd', '加害者', 'かがいしゃ', 'người gây hại', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('062fbf1b-a2a4-45b2-9cf9-f82a83dda5b4', 'a5b8721f-ac97-46db-b16f-57572d0705dd', '被害者', 'ひがいしゃ', 'người bị hại', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('062fbf1b-a2a4-45b2-9cf9-f82a83dda5b4', 'a5b8721f-ac97-46db-b16f-57572d0705dd', '殺害する', 'さつがいする', 'sát hại', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('062fbf1b-a2a4-45b2-9cf9-f82a83dda5b4', 'a5b8721f-ac97-46db-b16f-57572d0705dd', '損害', 'そんがい', 'thiệt hại', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('062fbf1b-a2a4-45b2-9cf9-f82a83dda5b4', 'a5b8721f-ac97-46db-b16f-57572d0705dd', '災害', 'さいがい', 'thảm họa', false, 5, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('062fbf1b-a2a4-45b2-9cf9-f82a83dda5b4', 'a5b8721f-ac97-46db-b16f-57572d0705dd', '被害', 'ひがい', 'thiệt hại', false, 5, 'pdf', 'ok', NULL);

-- ---------- jp_kanji_questions: PDF không có 問題 cho phần Kanji, toàn bộ generated ----------
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"標" đọc là gì (trong từ "標準語")?', 'ほ', 'ちょう', 'ひょう', 'じゅう', 'ひょう', 'generated' from jp_kanji where id = '3a2c518e-1110-4eef-88b0-7c91febe09bd';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "tiêu chuẩn, mục tiêu, biển báo"?', '標', '謙', '嫌', '漂', '標', 'generated' from jp_kanji where id = '3a2c518e-1110-4eef-88b0-7c91febe09bd';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"標準語" (ひょうじゅんご) nghĩa là gì?', 'ngôn ngữ phổ thông', 'đầy đủ', 'khắc', 'truyền thống', 'ngôn ngữ phổ thông', 'generated' from jp_kanji where id = '3a2c518e-1110-4eef-88b0-7c91febe09bd';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 標識 (biển báo)', 'ひょうしき', 'generated' from jp_kanji where id = '3a2c518e-1110-4eef-88b0-7c91febe09bd';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"漂" đọc là gì (trong từ "漂う")?', 'けん', 'べん', 'ほ', 'ただよ', 'ただよ', 'generated' from jp_kanji where id = '12b5a33a-853b-4354-a56e-283cd82bb23b';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "trôi nổi, tẩy trắng"?', '漂', '兼', '害', '銃', '漂', 'generated' from jp_kanji where id = '12b5a33a-853b-4354-a56e-283cd82bb23b';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"漂う" (ただよう) nghĩa là gì?', 'cứng nhắc', 'kiêm nhiệm', 'khiêm tốn (đức tính)', 'trôi nổi', 'trôi nổi', 'generated' from jp_kanji where id = '12b5a33a-853b-4354-a56e-283cd82bb23b';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 漂白剤 (chất tẩy trắng)', 'ひょうはくざい', 'generated' from jp_kanji where id = '12b5a33a-853b-4354-a56e-283cd82bb23b';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"周" đọc là gì (trong từ "周辺")?', 'きら', 'ふ', 'けん', 'しゅう', 'しゅう', 'generated' from jp_kanji where id = '6bfa4fbe-28f2-4ff1-8ae0-da13974096e0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "xung quanh, vòng quanh"?', '便', '標', '周', '彫', '周', 'generated' from jp_kanji where id = '6bfa4fbe-28f2-4ff1-8ae0-da13974096e0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"周辺" (しゅうへん) nghĩa là gì?', 'cứng rắn', 'thức đêm', 'quanh khu vực', 'người bị hại', 'quanh khu vực', 'generated' from jp_kanji where id = '6bfa4fbe-28f2-4ff1-8ae0-da13974096e0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 周り (xung quanh)', 'まわり', 'generated' from jp_kanji where id = '6bfa4fbe-28f2-4ff1-8ae0-da13974096e0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"彫" đọc là gì (trong từ "彫る")?', 'あ', 'ほ', 'じゅう', 'ちょう', 'ほ', 'generated' from jp_kanji where id = '660c892a-b3d1-4b2a-a4a3-d375e81bf321';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "khắc, chạm trổ"?', '周', '硬', '彫', '兼', '彫', 'generated' from jp_kanji where id = '660c892a-b3d1-4b2a-a4a3-d375e81bf321';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"彫る" (ほる) nghĩa là gì?', 'đồng xu', 'gia hạn', 'khắc', 'mục tiêu', 'khắc', 'generated' from jp_kanji where id = '660c892a-b3d1-4b2a-a4a3-d375e81bf321';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 彫刻 (điêu khắc)', 'ちょうこく', 'generated' from jp_kanji where id = '660c892a-b3d1-4b2a-a4a3-d375e81bf321';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"調" đọc là gì (trong từ "調える")?', 'こう', 'ととの', 'ひょう', 'じゅう', 'ととの', 'generated' from jp_kanji where id = 'f0dd1c6f-c448-4e2a-bfa6-1063145dcc4d';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "điều chỉnh, nêm nếm, trạng thái"?', '調', '統', '充', '漂', '調', 'generated' from jp_kanji where id = 'f0dd1c6f-c448-4e2a-bfa6-1063145dcc4d';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"調える" (ととのえる) nghĩa là gì?', 'thiệt hại', 'viên đạn', 'nêm, chuẩn bị', 'trang trải', 'nêm, chuẩn bị', 'generated' from jp_kanji where id = 'f0dd1c6f-c448-4e2a-bfa6-1063145dcc4d';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 調子 (trạng thái)', 'ちょうし', 'generated' from jp_kanji where id = 'f0dd1c6f-c448-4e2a-bfa6-1063145dcc4d';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"兼" đọc là gì (trong từ "兼任する")?', 'ふ', 'とう', 'ひょう', 'けん', 'けん', 'generated' from jp_kanji where id = '02d7d40d-5b49-4aa2-8aad-890db2e85ab7';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "kiêm, kiêm nhiệm"?', '兼', '充', '更', '標', '兼', 'generated' from jp_kanji where id = '02d7d40d-5b49-4aa2-8aad-890db2e85ab7';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"兼任する" (けんにんする) nghĩa là gì?', 'kiêm nhiệm', 'tâm trạng', 'quanh khu vực', 'ngôn ngữ phổ thông', 'kiêm nhiệm', 'generated' from jp_kanji where id = '02d7d40d-5b49-4aa2-8aad-890db2e85ab7';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 兼業 (nghề phụ)', 'けんぎょう', 'generated' from jp_kanji where id = '02d7d40d-5b49-4aa2-8aad-890db2e85ab7';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"嫌" đọc là gì (trong từ "嫌い")?', 'ととの', 'ほ', 'きら', 'こう', 'きら', 'generated' from jp_kanji where id = 'a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "ghét, khó chịu"?', '統', '硬', '更', '嫌', '嫌', 'generated' from jp_kanji where id = 'a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"嫌い" (きらい) nghĩa là gì?', 'khắc', 'đầy đủ', 'cai trị', 'ghét', 'ghét', 'generated' from jp_kanji where id = 'a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 機嫌 (tâm trạng)', 'きげん', 'generated' from jp_kanji where id = 'a4b41f9b-cf0d-41a1-b5ab-f7572f898fe8';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"謙" đọc là gì (trong từ "謙譲語")?', 'きら', 'あ', 'けん', 'じゅう', 'けん', 'generated' from jp_kanji where id = '471acd28-1476-4878-ba69-37f595f5cab8';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "khiêm tốn"?', '彫', '謙', '漂', '銃', '謙', 'generated' from jp_kanji where id = '471acd28-1476-4878-ba69-37f595f5cab8';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"謙譲語" (けんじょうご) nghĩa là gì?', 'thiệt hại', 'cai trị', 'điêu khắc', 'khiêm nhường ngữ', 'khiêm nhường ngữ', 'generated' from jp_kanji where id = '471acd28-1476-4878-ba69-37f595f5cab8';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 謙虚 (khiêm tốn (đức tính))', 'けんきょ', 'generated' from jp_kanji where id = '471acd28-1476-4878-ba69-37f595f5cab8';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"更" đọc là gì (trong từ "更新する")?', 'こう', 'ほ', 'ちょう', 'あ', 'こう', 'generated' from jp_kanji where id = 'da08ea2a-5860-4d05-8f14-c2f01aa8533f';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "thay đổi, canh (giờ khuya)"?', '更', '充', '嫌', '便', '更', 'generated' from jp_kanji where id = 'da08ea2a-5860-4d05-8f14-c2f01aa8533f';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"更新する" (こうしんする) nghĩa là gì?', 'gia hạn', 'dao khắc', 'cai trị', 'biển báo', 'gia hạn', 'generated' from jp_kanji where id = 'da08ea2a-5860-4d05-8f14-c2f01aa8533f';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 変更する (thay đổi)', 'へんこうする', 'generated' from jp_kanji where id = 'da08ea2a-5860-4d05-8f14-c2f01aa8533f';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"便" đọc là gì (trong từ "便利")?', 'ひょう', 'べん', 'かた', 'けん', 'べん', 'generated' from jp_kanji where id = '6f4fccae-2288-4120-9515-4a16eed76855';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "tiện lợi, thư từ"?', '更', '調', '標', '便', '便', 'generated' from jp_kanji where id = '6f4fccae-2288-4120-9515-4a16eed76855';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"便利" (べんり) nghĩa là gì?', 'truyền thống', 'kiêm nhiệm', 'tiện lợi', 'tâm trạng', 'tiện lợi', 'generated' from jp_kanji where id = '6f4fccae-2288-4120-9515-4a16eed76855';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 郵便局 (bưu điện)', 'ゆうびんきょく', 'generated' from jp_kanji where id = '6f4fccae-2288-4120-9515-4a16eed76855';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"硬" đọc là gì (trong từ "強硬な")?', 'いや', 'こう', 'ちょう', 'ただよ', 'こう', 'generated' from jp_kanji where id = '3b5015c5-9a08-4551-ac13-cc768079071b';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "cứng, cứng rắn"?', '嫌', '銃', '硬', '周', '硬', 'generated' from jp_kanji where id = '3b5015c5-9a08-4551-ac13-cc768079071b';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"強硬な" (きょうこうな) nghĩa là gì?', 'cuộc đọ súng', 'cứng rắn', 'đầy đủ', 'súng', 'cứng rắn', 'generated' from jp_kanji where id = '3b5015c5-9a08-4551-ac13-cc768079071b';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 硬貨 (đồng xu)', 'こうか', 'generated' from jp_kanji where id = '3b5015c5-9a08-4551-ac13-cc768079071b';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"充" đọc là gì (trong từ "充分")?', 'まわ', 'じゅう', 'ひょう', 'かた', 'じゅう', 'generated' from jp_kanji where id = '5ebf3991-6022-4272-abfe-49a51496e133';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "đầy đủ, sạc, lấp đầy"?', '充', '更', '謙', '兼', '充', 'generated' from jp_kanji where id = '5ebf3991-6022-4272-abfe-49a51496e133';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"充分" (じゅうぶん) nghĩa là gì?', 'nêm, chuẩn bị', 'cứng rắn', 'thay đổi', 'đầy đủ', 'đầy đủ', 'generated' from jp_kanji where id = '5ebf3991-6022-4272-abfe-49a51496e133';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 充実する (ý nghĩa)', 'じゅうじつする', 'generated' from jp_kanji where id = '5ebf3991-6022-4272-abfe-49a51496e133';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"銃" đọc là gì (trong từ "拳銃")?', 'まわ', 'ひょう', 'じゅう', 'こう', 'じゅう', 'generated' from jp_kanji where id = 'e18168b9-2252-4b3f-8aed-27c8b92871c0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "súng"?', '硬', '害', '便', '銃', '銃', 'generated' from jp_kanji where id = 'e18168b9-2252-4b3f-8aed-27c8b92871c0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"拳銃" (けんじゅう) nghĩa là gì?', 'cứng nhắc', 'dao khắc', 'viên đạn', 'súng', 'súng', 'generated' from jp_kanji where id = 'e18168b9-2252-4b3f-8aed-27c8b92871c0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 銃弾 (viên đạn)', 'じゅうだん', 'generated' from jp_kanji where id = 'e18168b9-2252-4b3f-8aed-27c8b92871c0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"統" đọc là gì (trong từ "統計")?', 'けん', 'こう', 'とう', 'こう', 'とう', 'generated' from jp_kanji where id = '9772278b-8f3e-4786-b6fc-780c6a3c3018';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "thống nhất, hệ thống"?', '硬', '兼', '統', '謙', '統', 'generated' from jp_kanji where id = '9772278b-8f3e-4786-b6fc-780c6a3c3018';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"統計" (とうけい) nghĩa là gì?', 'quanh khu vực', 'cai trị', 'thống kê', 'người bị hại', 'thống kê', 'generated' from jp_kanji where id = '9772278b-8f3e-4786-b6fc-780c6a3c3018';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 伝統 (truyền thống)', 'でんとう', 'generated' from jp_kanji where id = '9772278b-8f3e-4786-b6fc-780c6a3c3018';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"害" đọc là gì (trong từ "加害者")?', 'ちょう', 'とう', 'がい', 'かた', 'がい', 'generated' from jp_kanji where id = '062fbf1b-a2a4-45b2-9cf9-f82a83dda5b4';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "thiệt hại, nguy hại"?', '兼', '漂', '調', '害', '害', 'generated' from jp_kanji where id = '062fbf1b-a2a4-45b2-9cf9-f82a83dda5b4';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"加害者" (かがいしゃ) nghĩa là gì?', 'bưu điện', 'chất tẩy trắng', 'dùng chung', 'người gây hại', 'người gây hại', 'generated' from jp_kanji where id = '062fbf1b-a2a4-45b2-9cf9-f82a83dda5b4';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 被害者 (người bị hại)', 'ひがいしゃ', 'generated' from jp_kanji where id = '062fbf1b-a2a4-45b2-9cf9-f82a83dda5b4';

-- Tổng 60 câu hỏi generated cho 15 kanji.
