-- ============================================================
-- jp-go — Kanji N2, round 4 (15 kanji). Nguồn: PDF "Tổng hợp kiến
-- thức N2" (Dũng Mori), PART 1 - 漢字, trang in 6.
--
-- 抱 (BÃO, ôm) có 4 âm đọc thật: kun だ (抱く=だく, 抱きしめる), kun
-- いだ (CÙNG chữ 抱く nhưng đọc いだく — cả 2 cách đọc đều có thật,
-- không phải trùng lặp lỗi), kun かか (抱える), on ほう (gộp biến âm
-- ほう/ぼう: 抱負/介抱する/辛抱).
--
-- 酔 và 粋 là 2 KANJI KHÁC NHAU cùng Hán Việt "TÚY" — tách 2 mục
-- riêng, đánh dấu common_mistake/similar_kanji chéo nhau.
-- ============================================================

-- ---------- 婦 (PHỤ) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('428a6fe9-cf0b-4493-a8a7-4fce6ded08e5', 'N2', '婦', 'PHỤ', 'phụ nữ, người vợ', NULL, NULL, '婦 = 女(nữ) + 帚(cái chổi) — hình ảnh người phụ nữ trong gia đình xưa.', NULL, '{}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'db2d798a-4307-4c84-a84c-cf7b29d36689', id, 'on', 'ふ', true, 6, 'ok', NULL from jp_kanji where id = '428a6fe9-cf0b-4493-a8a7-4fce6ded08e5' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('428a6fe9-cf0b-4493-a8a7-4fce6ded08e5', 'db2d798a-4307-4c84-a84c-cf7b29d36689', '夫婦円満', 'ふうふえんまん', 'vợ chồng viên mãn', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('428a6fe9-cf0b-4493-a8a7-4fce6ded08e5', 'db2d798a-4307-4c84-a84c-cf7b29d36689', '新郎新婦', 'しんろうしんぷ', 'cô dâu chú rể', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('428a6fe9-cf0b-4493-a8a7-4fce6ded08e5', 'db2d798a-4307-4c84-a84c-cf7b29d36689', '主婦業', 'しゅふぎょう', 'công việc nội trợ', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('428a6fe9-cf0b-4493-a8a7-4fce6ded08e5', 'db2d798a-4307-4c84-a84c-cf7b29d36689', '産婦人科', 'さんふじんか', 'khoa sản', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('428a6fe9-cf0b-4493-a8a7-4fce6ded08e5', 'db2d798a-4307-4c84-a84c-cf7b29d36689', '妊婦', 'にんぷ', 'mang thai', false, 6, 'pdf', 'ok', NULL);

-- ---------- 掃 (TẢO) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('a9341206-1629-4a15-b5f5-ef5257e421f1', 'N2', '掃', 'TẢO', 'quét dọn', NULL, NULL, '掃 = 扌(tay) + 帚(chổi) — tay cầm chổi quét dọn.', NULL, '{"婦"}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'd26bb19b-5b54-4fd6-808b-09ff0c13d135', id, 'on', 'そう', true, 6, 'ok', NULL from jp_kanji where id = 'a9341206-1629-4a15-b5f5-ef5257e421f1' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '53f515fc-24fe-4860-aff2-a2cd1e17c487', id, 'kun', 'は', true, 6, 'ok', NULL from jp_kanji where id = 'a9341206-1629-4a15-b5f5-ef5257e421f1' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a9341206-1629-4a15-b5f5-ef5257e421f1', 'd26bb19b-5b54-4fd6-808b-09ff0c13d135', '一掃する', 'いっそうする', 'tiêu diệt sạch', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a9341206-1629-4a15-b5f5-ef5257e421f1', 'd26bb19b-5b54-4fd6-808b-09ff0c13d135', '清掃', 'せいそう', 'dọn vệ sinh', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a9341206-1629-4a15-b5f5-ef5257e421f1', '53f515fc-24fe-4860-aff2-a2cd1e17c487', '掃く', 'はく', 'quét', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a9341206-1629-4a15-b5f5-ef5257e421f1', 'd26bb19b-5b54-4fd6-808b-09ff0c13d135', '掃除する', 'そうじする', 'dọn dẹp', false, 6, 'pdf', 'ok', NULL);

-- ---------- 構 (CẤU) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('aceca53a-6981-42f5-affd-163d3b71ed31', 'N2', '構', 'CẤU', 'xây dựng, cấu tạo', NULL, NULL, '構 = 木(gỗ) + 冓(khung chồng) — dựng khung gỗ, xây cất.', '構 (xây dựng) và 購 (mua) cùng Hán Việt "CẤU" nhưng nghĩa khác hẳn.', '{"購"}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'b4de302a-dc66-400f-a6b7-d9032c3518d7', id, 'kun', 'かま', true, 6, 'ok', NULL from jp_kanji where id = 'aceca53a-6981-42f5-affd-163d3b71ed31' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '8c8467f9-7fb6-4594-9a88-f2025902622c', id, 'on', 'こう', true, 6, 'ok', NULL from jp_kanji where id = 'aceca53a-6981-42f5-affd-163d3b71ed31' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('aceca53a-6981-42f5-affd-163d3b71ed31', 'b4de302a-dc66-400f-a6b7-d9032c3518d7', '構える', 'かまえる', 'xây dựng, sở hữu, có thái độ, sẵn sàng tư thế', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('aceca53a-6981-42f5-affd-163d3b71ed31', '8c8467f9-7fb6-4594-9a88-f2025902622c', '構造', 'こうぞう', 'cấu tạo', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('aceca53a-6981-42f5-affd-163d3b71ed31', '8c8467f9-7fb6-4594-9a88-f2025902622c', '構成', 'こうせい', 'cấu trúc', false, 6, 'pdf', 'ok', NULL);

-- ---------- 購 (CẤU) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('a57b7506-a64e-4e11-9ac4-a3046b838a8d', 'N2', '購', 'CẤU', 'mua, đặt mua', NULL, NULL, '購 = 貝(tiền/vỏ sò) + 冓 — dùng tiền để mua.', '構 (xây dựng) và 購 (mua) cùng Hán Việt "CẤU" nhưng nghĩa khác hẳn.', '{"構"}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '0da61fab-7faa-4ade-83c6-850de8e484a9', id, 'on', 'こう', true, 6, 'ok', NULL from jp_kanji where id = 'a57b7506-a64e-4e11-9ac4-a3046b838a8d' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a57b7506-a64e-4e11-9ac4-a3046b838a8d', '0da61fab-7faa-4ade-83c6-850de8e484a9', '購買', 'こうばい', 'mua hàng', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a57b7506-a64e-4e11-9ac4-a3046b838a8d', '0da61fab-7faa-4ade-83c6-850de8e484a9', '購入する', 'こうにゅうする', 'mua', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('a57b7506-a64e-4e11-9ac4-a3046b838a8d', '0da61fab-7faa-4ade-83c6-850de8e484a9', '定期購読', 'ていきこうどく', 'đặt mua báo, tạp chí định kỳ', false, 6, 'pdf', 'ok', NULL);

-- ---------- 講 (GIẢNG) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('72b0b298-629b-40f8-b7b4-7066afbd1d6a', 'N2', '講', 'GIẢNG', 'giảng dạy, giảng giải', NULL, NULL, '講 = 言(lời nói) + 冓 — lời nói được sắp xếp thành bài giảng.', NULL, '{"構","購"}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '3681104e-927d-4f66-9d26-b15b1a155fa6', id, 'on', 'こう', true, 6, 'ok', NULL from jp_kanji where id = '72b0b298-629b-40f8-b7b4-7066afbd1d6a' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('72b0b298-629b-40f8-b7b4-7066afbd1d6a', '3681104e-927d-4f66-9d26-b15b1a155fa6', '講義', 'こうぎ', 'giờ giảng', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('72b0b298-629b-40f8-b7b4-7066afbd1d6a', '3681104e-927d-4f66-9d26-b15b1a155fa6', '講演', 'こうえん', 'bài diễn thuyết', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('72b0b298-629b-40f8-b7b4-7066afbd1d6a', '3681104e-927d-4f66-9d26-b15b1a155fa6', '講師', 'こうし', 'giảng viên', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('72b0b298-629b-40f8-b7b4-7066afbd1d6a', '3681104e-927d-4f66-9d26-b15b1a155fa6', '講じる', 'こうじる', 'đề ra', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('72b0b298-629b-40f8-b7b4-7066afbd1d6a', '3681104e-927d-4f66-9d26-b15b1a155fa6', '講座', 'こうざ', 'toạ giảng', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('72b0b298-629b-40f8-b7b4-7066afbd1d6a', '3681104e-927d-4f66-9d26-b15b1a155fa6', '受講', 'じゅこう', 'tham gia', false, 6, 'pdf', 'ok', NULL);

-- ---------- 抱 (BÃO) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85', 'N2', '抱', 'BÃO', 'ôm, ấp ủ (hoài bão)', NULL, NULL, '抱 = 扌(tay) + 包(bao bọc) — tay ôm ấp, bao bọc lấy.', '抱く có 2 cách đọc đều đúng: だく (thân mật, thường dùng cho vật) và いだく (trang trọng hơn, dùng cho ý niệm trừu tượng như hoài bão).', '{}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '7550600d-67d0-4cb5-8a42-ecb40eaf93cd', id, 'kun', 'だ', true, 6, 'ok', NULL from jp_kanji where id = '9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'f93ec6f3-b2bf-4c64-b4e7-c78be334f3a5', id, 'kun', 'いだ', true, 6, 'ok', NULL from jp_kanji where id = '9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'c808956e-5cb9-41d3-b31b-c5bb99dc1bd2', id, 'kun', 'かか', true, 6, 'ok', NULL from jp_kanji where id = '9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '1c5709da-b663-475d-b136-9f453d741ebc', id, 'on', 'ほう', true, 6, 'ok', NULL from jp_kanji where id = '9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85', '7550600d-67d0-4cb5-8a42-ecb40eaf93cd', '抱く', 'だく', 'ôm, ấp ủ (hoài bão, ước mơ)', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85', '7550600d-67d0-4cb5-8a42-ecb40eaf93cd', '抱きしめる', 'だきしめる', 'ôm chặt', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85', 'f93ec6f3-b2bf-4c64-b4e7-c78be334f3a5', '抱く', 'いだく', 'ôm (vật hữu hình/ý niệm trừu tượng)', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85', 'c808956e-5cb9-41d3-b31b-c5bb99dc1bd2', '抱える', 'かかえる', 'mang, vướng phải, mắc', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85', '1c5709da-b663-475d-b136-9f453d741ebc', '辛抱', 'しんぼう', 'sức chịu đựng', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85', '1c5709da-b663-475d-b136-9f453d741ebc', '抱負', 'ほうふ', 'hoài bão', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85', '1c5709da-b663-475d-b136-9f453d741ebc', '介抱する', 'かいほうする', 'chăm sóc', false, 6, 'pdf', 'ok', NULL);

-- ---------- 泡 (PHAO) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('020b153a-e741-482b-83df-24623577e5f8', 'N2', '泡', 'PHAO', 'bọt, bong bóng', NULL, NULL, '泡 = 氵(nước) + 包 — nước bao lấy không khí thành bọt.', NULL, '{"砲"}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'f61c9156-9442-4557-8ef4-fe5c7400c2df', id, 'kun', 'あわ', true, 6, 'ok', NULL from jp_kanji where id = '020b153a-e741-482b-83df-24623577e5f8' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '32e55739-eef0-493d-a1df-2435f5853799', id, 'on', 'ほう', true, 6, 'ok', NULL from jp_kanji where id = '020b153a-e741-482b-83df-24623577e5f8' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('020b153a-e741-482b-83df-24623577e5f8', 'f61c9156-9442-4557-8ef4-fe5c7400c2df', '泡', 'あわ', 'bọt', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('020b153a-e741-482b-83df-24623577e5f8', '32e55739-eef0-493d-a1df-2435f5853799', '気泡', 'きほう', 'bọt khí', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('020b153a-e741-482b-83df-24623577e5f8', 'f61c9156-9442-4557-8ef4-fe5c7400c2df', '泡風呂', 'あわぶろ', 'bồn tắm có bọt bong bóng', false, 6, 'pdf', 'ok', NULL);

-- ---------- 砲 (PHÁO) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('3025ec59-a7b0-4ce0-b5a8-7ca28b101011', 'N2', '砲', 'PHÁO', 'súng, pháo', NULL, NULL, '砲 = 石(đá) + 包 — vũ khí bắn ra đạn đá/kim loại.', '泡 (bọt, bộ 氵) và 砲 (súng, bộ 石) dễ nhầm mặt chữ vì cùng phần 包.', '{"泡"}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '55aec04f-7d41-4718-9aba-53316f732faa', id, 'on', 'ほう', true, 6, 'ok', NULL from jp_kanji where id = '3025ec59-a7b0-4ce0-b5a8-7ca28b101011' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('3025ec59-a7b0-4ce0-b5a8-7ca28b101011', '55aec04f-7d41-4718-9aba-53316f732faa', '鉄砲', 'てっぽう', 'súng', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('3025ec59-a7b0-4ce0-b5a8-7ca28b101011', '55aec04f-7d41-4718-9aba-53316f732faa', '発砲する', 'はっぽうする', 'nã súng', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('3025ec59-a7b0-4ce0-b5a8-7ca28b101011', '55aec04f-7d41-4718-9aba-53316f732faa', '大砲', 'たいほう', 'đại bác', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('3025ec59-a7b0-4ce0-b5a8-7ca28b101011', '55aec04f-7d41-4718-9aba-53316f732faa', '砲撃する', 'ほうげきする', 'pháo kích', false, 6, 'pdf', 'ok', NULL);

-- ---------- 枠 (KHUNG) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('5715d6eb-a07c-4842-ba3c-013ddac5809f', 'N2', '枠', 'KHUNG', 'khung, khuôn khổ', NULL, NULL, '枠 = 木(gỗ) + 卆 — khung gỗ đóng thành khuôn.', NULL, '{}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'c4ef3438-69d8-4715-9d9f-1fb6a38b101a', id, 'kun', 'わく', true, 6, 'ok', NULL from jp_kanji where id = '5715d6eb-a07c-4842-ba3c-013ddac5809f' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('5715d6eb-a07c-4842-ba3c-013ddac5809f', 'c4ef3438-69d8-4715-9d9f-1fb6a38b101a', '枠組み', 'わくぐみ', 'lên khung', false, 6, 'pdf', 'ok', NULL);

-- ---------- 酔 (TÚY) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('94176020-f56d-478b-b523-257e1bf440fd', 'N2', '酔', 'TÚY', 'say (rượu, xe)', NULL, NULL, '酔 = 酉(rượu) + 卆 — uống rượu vào rồi say.', '酔 (say, bộ 酉) và 粋 (tinh túy, bộ 米) là 2 KANJI KHÁC NHAU nhưng cùng Hán Việt "TÚY" — dễ nhầm.', '{"粋"}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '048ad46a-44a8-4e11-ba11-3dc6adeaf787', id, 'kun', 'よ', true, 6, 'ok', NULL from jp_kanji where id = '94176020-f56d-478b-b523-257e1bf440fd' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('94176020-f56d-478b-b523-257e1bf440fd', '048ad46a-44a8-4e11-ba11-3dc6adeaf787', '車に酔う', 'くるまによう', 'say xe', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('94176020-f56d-478b-b523-257e1bf440fd', '048ad46a-44a8-4e11-ba11-3dc6adeaf787', '酔っ払う', 'よっぱらう', 'say rượu', false, 6, 'pdf', 'ok', NULL);

-- ---------- 粋 (TÚY) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('754e61a8-eb1c-4295-b781-9dfaddb04c50', 'N2', '粋', 'TÚY', 'tinh túy, thuần khiết', NULL, NULL, '粋 = 米(gạo) + 卆 — chắt lọc lấy phần tinh túy nhất của hạt gạo.', '粋 (tinh túy, bộ 米) và 酔 (say, bộ 酉) là 2 KANJI KHÁC NHAU nhưng cùng Hán Việt "TÚY" — dễ nhầm.', '{"酔"}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'c912b425-6f72-4092-8be8-ececfa03f3db', id, 'kun', 'いき', true, 6, 'ok', NULL from jp_kanji where id = '754e61a8-eb1c-4295-b781-9dfaddb04c50' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '748f398f-8df1-4a1b-9d79-aa1d1fd324b8', id, 'on', 'すい', true, 6, 'ok', NULL from jp_kanji where id = '754e61a8-eb1c-4295-b781-9dfaddb04c50' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('754e61a8-eb1c-4295-b781-9dfaddb04c50', 'c912b425-6f72-4092-8be8-ececfa03f3db', '粋な', 'いきな', 'tinh tuý', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('754e61a8-eb1c-4295-b781-9dfaddb04c50', '748f398f-8df1-4a1b-9d79-aa1d1fd324b8', '純粋な', 'じゅんすいな', 'trong sáng', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('754e61a8-eb1c-4295-b781-9dfaddb04c50', '748f398f-8df1-4a1b-9d79-aa1d1fd324b8', '抜粋', 'ばっすい', 'trích dẫn', false, 6, 'pdf', 'ok', NULL);

-- ---------- 飯 (PHẠN) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('9ed7d83d-3c32-4d46-9237-6695238f50e0', 'N2', '飯', 'PHẠN', 'cơm', NULL, NULL, '飯 = 食(ăn) + 反 — bữa ăn với cơm.', NULL, '{}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'cf02b97a-b466-486c-8544-966ce5ad40f2', id, 'on', 'はん', true, 6, 'ok', NULL from jp_kanji where id = '9ed7d83d-3c32-4d46-9237-6695238f50e0' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '0d23fa26-3f6f-45d0-8d04-37698e1b392b', id, 'kun', 'めし', true, 6, 'ok', NULL from jp_kanji where id = '9ed7d83d-3c32-4d46-9237-6695238f50e0' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9ed7d83d-3c32-4d46-9237-6695238f50e0', 'cf02b97a-b466-486c-8544-966ce5ad40f2', '御飯', 'ごはん', 'cơm', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9ed7d83d-3c32-4d46-9237-6695238f50e0', '0d23fa26-3f6f-45d0-8d04-37698e1b392b', '飯を食う', 'めしをくう', 'ăn cơm', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('9ed7d83d-3c32-4d46-9237-6695238f50e0', 'cf02b97a-b466-486c-8544-966ce5ad40f2', '晩御飯', 'ばんごはん', 'bữa cơm tối', false, 6, 'pdf', 'ok', NULL);

-- ---------- 販 (PHIẾN) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('8caa2d0c-1ac7-4446-a075-f5f92f83a094', 'N2', '販', 'PHIẾN', 'bán hàng', NULL, NULL, '販 = 貝(tiền) + 反 — trao đổi tiền để bán hàng.', NULL, '{"飯"}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'dcebf0d7-5922-49ac-a3bf-bc9aef432eab', id, 'on', 'はん', true, 6, 'ok', NULL from jp_kanji where id = '8caa2d0c-1ac7-4446-a075-f5f92f83a094' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('8caa2d0c-1ac7-4446-a075-f5f92f83a094', 'dcebf0d7-5922-49ac-a3bf-bc9aef432eab', '市販', 'しはん', 'thị trường', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('8caa2d0c-1ac7-4446-a075-f5f92f83a094', 'dcebf0d7-5922-49ac-a3bf-bc9aef432eab', '販売機', 'はんばいき', 'máy bán hàng', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('8caa2d0c-1ac7-4446-a075-f5f92f83a094', 'dcebf0d7-5922-49ac-a3bf-bc9aef432eab', '販売する', 'はんばいする', 'bán hàng', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('8caa2d0c-1ac7-4446-a075-f5f92f83a094', 'dcebf0d7-5922-49ac-a3bf-bc9aef432eab', '販売部', 'はんばいぶ', 'bộ phận bán hàng', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('8caa2d0c-1ac7-4446-a075-f5f92f83a094', 'dcebf0d7-5922-49ac-a3bf-bc9aef432eab', '通信販売', 'つうしんはんばい', 'mua hàng qua mạng', false, 6, 'pdf', 'ok', NULL);

-- ---------- 仮 (GIẢ) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('74f87aae-cf2a-4567-9a95-0d0d5b054edf', 'N2', '仮', 'GIẢ', 'giả, tạm thời', NULL, NULL, '仮 = 亻(người) + 反 — người đóng vai tạm, giả danh.', NULL, '{}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '806ba26f-0ed0-4e93-a11e-dcfe89147d1c', id, 'on', 'か', true, 6, 'ok', NULL from jp_kanji where id = '74f87aae-cf2a-4567-9a95-0d0d5b054edf' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '9480fb87-fdd1-4e0e-a808-5d14ff078946', id, 'on', 'け', true, 6, 'ok', NULL from jp_kanji where id = '74f87aae-cf2a-4567-9a95-0d0d5b054edf' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select '9a5d5495-674e-43e3-9fd2-63f6cea0720a', id, 'kun', 'かり', true, 6, 'ok', NULL from jp_kanji where id = '74f87aae-cf2a-4567-9a95-0d0d5b054edf' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('74f87aae-cf2a-4567-9a95-0d0d5b054edf', '806ba26f-0ed0-4e93-a11e-dcfe89147d1c', '仮名', 'かめい', 'bí danh', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('74f87aae-cf2a-4567-9a95-0d0d5b054edf', '9480fb87-fdd1-4e0e-a808-5d14ff078946', '仮病', 'けびょう', 'giả ốm', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('74f87aae-cf2a-4567-9a95-0d0d5b054edf', '806ba26f-0ed0-4e93-a11e-dcfe89147d1c', '仮定する', 'かていする', 'giả sử', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('74f87aae-cf2a-4567-9a95-0d0d5b054edf', '806ba26f-0ed0-4e93-a11e-dcfe89147d1c', '仮説', 'かせつ', 'giả thuyết', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('74f87aae-cf2a-4567-9a95-0d0d5b054edf', '9a5d5495-674e-43e3-9fd2-63f6cea0720a', '仮免許', 'かりめんきょ', 'giấy phép tạm thời', false, 6, 'pdf', 'ok', NULL);

-- ---------- 殴 (ẨU) ----------
insert into jp_kanji (id, level, kanji_character, han_viet, meaning_vi_summary, stroke_count, radical, mnemonic_hint_vi, common_mistake, similar_kanji, source_page, source_type, review_status) values ('717b4409-bae4-4291-8c7b-e09edef7ef09', 'N2', '殴', 'ẨU', 'đấm, đánh', NULL, NULL, '殴 = 区(khu vực) + 殳(cây gậy) — dùng gậy đánh vào một chỗ.', NULL, '{}', 6, 'pdf', 'ok')
on conflict (level, kanji_character) do nothing;

insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'b19e2112-58f8-4910-ae6b-f929e10c4fd5', id, 'kun', 'なぐ', true, 6, 'ok', NULL from jp_kanji where id = '717b4409-bae4-4291-8c7b-e09edef7ef09' on conflict (id) do nothing;
insert into jp_kanji_readings (id, kanji_id, reading_type, reading_kana, is_main, source_page, review_status, correction_note) select 'b07bc954-0eca-4dad-81df-1f604e753f5e', id, 'on', 'おう', true, 6, 'ok', NULL from jp_kanji where id = '717b4409-bae4-4291-8c7b-e09edef7ef09' on conflict (id) do nothing;

insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('717b4409-bae4-4291-8c7b-e09edef7ef09', 'b19e2112-58f8-4910-ae6b-f929e10c4fd5', '殴る', 'なぐる', 'đấm', false, 6, 'pdf', 'ok', NULL);
insert into jp_kanji_words (kanji_id, reading_id, word_jp, word_furigana, meaning_vi, is_irregular, source_page, source_type, review_status, correction_note) values ('717b4409-bae4-4291-8c7b-e09edef7ef09', 'b07bc954-0eca-4dad-81df-1f604e753f5e', '殴打される', 'おうだされる', 'bị đánh', false, 6, 'pdf', 'ok', NULL);

-- ---------- jp_kanji_questions: PDF không có 問題 cho phần Kanji, toàn bộ generated ----------
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"婦" đọc là gì (trong từ "夫婦円満")?', 'わく', 'なぐ', 'はん', 'ふ', 'ふ', 'generated' from jp_kanji where id = '428a6fe9-cf0b-4493-a8a7-4fce6ded08e5';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "phụ nữ, người vợ"?', '粋', '販', '婦', '掃', '婦', 'generated' from jp_kanji where id = '428a6fe9-cf0b-4493-a8a7-4fce6ded08e5';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"夫婦円満" (ふうふえんまん) nghĩa là gì?', 'giấy phép tạm thời', 'vợ chồng viên mãn', 'pháo kích', 'bị đánh', 'vợ chồng viên mãn', 'generated' from jp_kanji where id = '428a6fe9-cf0b-4493-a8a7-4fce6ded08e5';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 新郎新婦 (cô dâu chú rể)', 'しんろうしんぷ', 'generated' from jp_kanji where id = '428a6fe9-cf0b-4493-a8a7-4fce6ded08e5';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"掃" đọc là gì (trong từ "一掃する")?', 'なぐ', 'は', 'そう', 'ほう', 'そう', 'generated' from jp_kanji where id = 'a9341206-1629-4a15-b5f5-ef5257e421f1';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "quét dọn"?', '構', '掃', '仮', '殴', '掃', 'generated' from jp_kanji where id = 'a9341206-1629-4a15-b5f5-ef5257e421f1';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"一掃する" (いっそうする) nghĩa là gì?', 'bồn tắm có bọt bong bóng', 'công việc nội trợ', 'tiêu diệt sạch', 'bọt khí', 'tiêu diệt sạch', 'generated' from jp_kanji where id = 'a9341206-1629-4a15-b5f5-ef5257e421f1';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 清掃 (dọn vệ sinh)', 'せいそう', 'generated' from jp_kanji where id = 'a9341206-1629-4a15-b5f5-ef5257e421f1';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"構" đọc là gì (trong từ "構える")?', 'かま', 'いだ', 'ほう', 'はん', 'かま', 'generated' from jp_kanji where id = 'aceca53a-6981-42f5-affd-163d3b71ed31';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "xây dựng, cấu tạo"?', '抱', '砲', '構', '婦', '構', 'generated' from jp_kanji where id = 'aceca53a-6981-42f5-affd-163d3b71ed31';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"構える" (かまえる) nghĩa là gì?', 'xây dựng, sở hữu, có thái độ, sẵn sàng tư thế', 'dọn vệ sinh', 'lên khung', 'giả thuyết', 'xây dựng, sở hữu, có thái độ, sẵn sàng tư thế', 'generated' from jp_kanji where id = 'aceca53a-6981-42f5-affd-163d3b71ed31';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 構造 (cấu tạo)', 'こうぞう', 'generated' from jp_kanji where id = 'aceca53a-6981-42f5-affd-163d3b71ed31';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"購" đọc là gì (trong từ "購買")?', 'こう', 'わく', 'ほう', 'すい', 'こう', 'generated' from jp_kanji where id = 'a57b7506-a64e-4e11-9ac4-a3046b838a8d';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "mua, đặt mua"?', '販', '掃', '購', '酔', '購', 'generated' from jp_kanji where id = 'a57b7506-a64e-4e11-9ac4-a3046b838a8d';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"購買" (こうばい) nghĩa là gì?', 'mua hàng', 'thị trường', 'trích dẫn', 'mang thai', 'mua hàng', 'generated' from jp_kanji where id = 'a57b7506-a64e-4e11-9ac4-a3046b838a8d';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 購入する (mua)', 'こうにゅうする', 'generated' from jp_kanji where id = 'a57b7506-a64e-4e11-9ac4-a3046b838a8d';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"講" đọc là gì (trong từ "講義")?', 'あわ', 'はん', 'こう', 'わく', 'こう', 'generated' from jp_kanji where id = '72b0b298-629b-40f8-b7b4-7066afbd1d6a';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "giảng dạy, giảng giải"?', '構', '講', '泡', '酔', '講', 'generated' from jp_kanji where id = '72b0b298-629b-40f8-b7b4-7066afbd1d6a';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"講義" (こうぎ) nghĩa là gì?', 'giảng viên', 'giờ giảng', 'bọt', 'chăm sóc', 'giờ giảng', 'generated' from jp_kanji where id = '72b0b298-629b-40f8-b7b4-7066afbd1d6a';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 講演 (bài diễn thuyết)', 'こうえん', 'generated' from jp_kanji where id = '72b0b298-629b-40f8-b7b4-7066afbd1d6a';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"抱" đọc là gì (trong từ "抱く")?', 'おう', 'かか', 'いき', 'だ', 'だ', 'generated' from jp_kanji where id = '9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "ôm, ấp ủ (hoài bão)"?', '抱', '枠', '掃', '酔', '抱', 'generated' from jp_kanji where id = '9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"抱く" (だく) nghĩa là gì?', 'ôm, ấp ủ (hoài bão, ước mơ)', 'mua hàng qua mạng', 'mang thai', 'cô dâu chú rể', 'ôm, ấp ủ (hoài bão, ước mơ)', 'generated' from jp_kanji where id = '9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 抱きしめる (ôm chặt)', 'だきしめる', 'generated' from jp_kanji where id = '9aa86e5a-561f-4c41-a5f3-e94b1b1f0c85';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"泡" đọc là gì (trong từ "泡")?', 'かま', 'わく', 'すい', 'あわ', 'あわ', 'generated' from jp_kanji where id = '020b153a-e741-482b-83df-24623577e5f8';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "bọt, bong bóng"?', '購', '殴', '粋', '泡', '泡', 'generated' from jp_kanji where id = '020b153a-e741-482b-83df-24623577e5f8';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"泡" (あわ) nghĩa là gì?', 'bọt', 'dọn dẹp', 'trích dẫn', 'say rượu', 'bọt', 'generated' from jp_kanji where id = '020b153a-e741-482b-83df-24623577e5f8';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 気泡 (bọt khí)', 'きほう', 'generated' from jp_kanji where id = '020b153a-e741-482b-83df-24623577e5f8';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"砲" đọc là gì (trong từ "鉄砲")?', 'よ', 'ほう', 'はん', 'は', 'ほう', 'generated' from jp_kanji where id = '3025ec59-a7b0-4ce0-b5a8-7ca28b101011';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "súng, pháo"?', '酔', '砲', '婦', '構', '砲', 'generated' from jp_kanji where id = '3025ec59-a7b0-4ce0-b5a8-7ca28b101011';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"鉄砲" (てっぽう) nghĩa là gì?', 'súng', 'cấu trúc', 'giờ giảng', 'khoa sản', 'súng', 'generated' from jp_kanji where id = '3025ec59-a7b0-4ce0-b5a8-7ca28b101011';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 発砲する (nã súng)', 'はっぽうする', 'generated' from jp_kanji where id = '3025ec59-a7b0-4ce0-b5a8-7ca28b101011';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"枠" đọc là gì (trong từ "枠組み")?', 'わく', 'そう', 'いだ', 'いき', 'わく', 'generated' from jp_kanji where id = '5715d6eb-a07c-4842-ba3c-013ddac5809f';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "khung, khuôn khổ"?', '販', '酔', '購', '枠', '枠', 'generated' from jp_kanji where id = '5715d6eb-a07c-4842-ba3c-013ddac5809f';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"枠組み" (わくぐみ) nghĩa là gì?', 'tiêu diệt sạch', 'bồn tắm có bọt bong bóng', 'cấu trúc', 'lên khung', 'lên khung', 'generated' from jp_kanji where id = '5715d6eb-a07c-4842-ba3c-013ddac5809f';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 枠組み (lên khung)', 'わくぐみ', 'generated' from jp_kanji where id = '5715d6eb-a07c-4842-ba3c-013ddac5809f';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"酔" đọc là gì (trong từ "車に酔う")?', 'け', 'よ', 'は', 'いだ', 'よ', 'generated' from jp_kanji where id = '94176020-f56d-478b-b523-257e1bf440fd';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "say (rượu, xe)"?', '飯', '掃', '粋', '酔', '酔', 'generated' from jp_kanji where id = '94176020-f56d-478b-b523-257e1bf440fd';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"車に酔う" (くるまによう) nghĩa là gì?', 'tham gia', 'giả thuyết', 'mua', 'say xe', 'say xe', 'generated' from jp_kanji where id = '94176020-f56d-478b-b523-257e1bf440fd';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 酔っ払う (say rượu)', 'よっぱらう', 'generated' from jp_kanji where id = '94176020-f56d-478b-b523-257e1bf440fd';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"粋" đọc là gì (trong từ "粋な")?', 'こう', 'ほう', 'はん', 'いき', 'いき', 'generated' from jp_kanji where id = '754e61a8-eb1c-4295-b781-9dfaddb04c50';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "tinh túy, thuần khiết"?', '泡', '仮', '枠', '粋', '粋', 'generated' from jp_kanji where id = '754e61a8-eb1c-4295-b781-9dfaddb04c50';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"粋な" (いきな) nghĩa là gì?', 'mua hàng', 'xây dựng, sở hữu, có thái độ, sẵn sàng tư thế', 'tinh tuý', 'giả sử', 'tinh tuý', 'generated' from jp_kanji where id = '754e61a8-eb1c-4295-b781-9dfaddb04c50';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 純粋な (trong sáng)', 'じゅんすいな', 'generated' from jp_kanji where id = '754e61a8-eb1c-4295-b781-9dfaddb04c50';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"飯" đọc là gì (trong từ "御飯")?', 'こう', 'そう', 'めし', 'はん', 'はん', 'generated' from jp_kanji where id = '9ed7d83d-3c32-4d46-9237-6695238f50e0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "cơm"?', '殴', '砲', '飯', '講', '飯', 'generated' from jp_kanji where id = '9ed7d83d-3c32-4d46-9237-6695238f50e0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"御飯" (ごはん) nghĩa là gì?', 'tham gia', 'khoa sản', 'bọt khí', 'cơm', 'cơm', 'generated' from jp_kanji where id = '9ed7d83d-3c32-4d46-9237-6695238f50e0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 飯を食う (ăn cơm)', 'めしをくう', 'generated' from jp_kanji where id = '9ed7d83d-3c32-4d46-9237-6695238f50e0';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"販" đọc là gì (trong từ "市販")?', 'こう', 'こう', 'ふ', 'はん', 'はん', 'generated' from jp_kanji where id = '8caa2d0c-1ac7-4446-a075-f5f92f83a094';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "bán hàng"?', '酔', '販', '枠', '購', '販', 'generated' from jp_kanji where id = '8caa2d0c-1ac7-4446-a075-f5f92f83a094';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"市販" (しはん) nghĩa là gì?', 'ôm (vật hữu hình/ý niệm trừu tượng)', 'mua hàng', 'thị trường', 'toạ giảng', 'thị trường', 'generated' from jp_kanji where id = '8caa2d0c-1ac7-4446-a075-f5f92f83a094';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 販売機 (máy bán hàng)', 'はんばいき', 'generated' from jp_kanji where id = '8caa2d0c-1ac7-4446-a075-f5f92f83a094';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"仮" đọc là gì (trong từ "仮名")?', 'おう', 'こう', 'か', 'は', 'か', 'generated' from jp_kanji where id = '74f87aae-cf2a-4567-9a95-0d0d5b054edf';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "giả, tạm thời"?', '婦', '仮', '販', '泡', '仮', 'generated' from jp_kanji where id = '74f87aae-cf2a-4567-9a95-0d0d5b054edf';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"仮名" (かめい) nghĩa là gì?', 'bị đánh', 'súng', 'dọn dẹp', 'bí danh', 'bí danh', 'generated' from jp_kanji where id = '74f87aae-cf2a-4567-9a95-0d0d5b054edf';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 仮病 (giả ốm)', 'けびょう', 'generated' from jp_kanji where id = '74f87aae-cf2a-4567-9a95-0d0d5b054edf';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"殴" đọc là gì (trong từ "殴る")?', 'はん', 'だ', 'かり', 'なぐ', 'なぐ', 'generated' from jp_kanji where id = '717b4409-bae4-4291-8c7b-e09edef7ef09';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_kanji_from_meaning', 'Kanji nào có nghĩa "đấm, đánh"?', '枠', '酔', '抱', '殴', '殴', 'generated' from jp_kanji where id = '717b4409-bae4-4291-8c7b-e09edef7ef09';
insert into jp_kanji_questions (kanji_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_meaning', '"殴る" (なぐる) nghĩa là gì?', 'đấm', 'mua', 'giấy phép tạm thời', 'hoài bão', 'đấm', 'generated' from jp_kanji where id = '717b4409-bae4-4291-8c7b-e09edef7ef09';
insert into jp_kanji_questions (kanji_id, question_type, question_text, correct_answer, source_type) select id, 'write_reading', 'Đọc từ sau: 殴打される (bị đánh)', 'おうだされる', 'generated' from jp_kanji where id = '717b4409-bae4-4291-8c7b-e09edef7ef09';

-- Tổng 60 câu hỏi generated cho 15 kanji.
