-- ============================================================
-- jp-go — Từ vựng N2, round 9 (nhóm 動名詞, trang in 46, 39 từ —
-- TRANG CUỐI nhóm 動名詞). Nguồn: PDF "Tổng hợp kiến thức N2"
-- (Dũng Mori), PART 2 - 語彙.
--
-- Trang này có câu hỏi trắc nghiệm THẬT thứ 2 (đánh dấu ＊) — chưa
-- insert, sẽ gom đủ 16 câu và khớp đáp án ở phần ＊答 sau.
-- ============================================================

-- ---------- 中断 (ちゅうだん) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('aa17caf8-d466-49c7-9490-481778a65747', 'N2', NULL, 'word', '中断', 'ちゅうだん', 'Gián đoạn', NULL, NULL, '動名詞', 46, '中断', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '工事が中断しました。', 'Công trình đã bị gián đoạn.', '工事が_____しました。', '中断', 'generated' from jp_vocab where id = 'aa17caf8-d466-49c7-9490-481778a65747';

-- ---------- 摩擦 (まさつ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('a9cf786d-40ee-45e4-bef6-6d429221ce2d', 'N2', NULL, 'word', '摩擦', 'まさつ', 'Ma sát', NULL, NULL, '動名詞', 46, '摩擦', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '国同士の摩擦が起きました。', 'Đã xảy ra ma sát giữa các nước.', '国同士の_____が起きました。', '摩擦', 'generated' from jp_vocab where id = 'a9cf786d-40ee-45e4-bef6-6d429221ce2d';

-- ---------- 栽培 (さいばい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('f638ce2d-9d52-4e21-abb8-988f7215dc65', 'N2', NULL, 'word', '栽培', 'さいばい', 'Trồng trọt, canh tác', NULL, NULL, '動名詞', 46, '栽培', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '野菜を栽培します。', 'Tôi trồng rau.', '野菜を_____します。', '栽培', 'generated' from jp_vocab where id = 'f638ce2d-9d52-4e21-abb8-988f7215dc65';

-- ---------- 所有 (しょゆう) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('1907619c-090d-43de-90c7-ed8aa58de116', 'N2', NULL, 'word', '所有', 'しょゆう', 'Sở hữu', NULL, NULL, '動名詞', 46, '所有', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '車を所有しています。', 'Tôi sở hữu một chiếc xe.', '車を_____しています。', '所有', 'generated' from jp_vocab where id = '1907619c-090d-43de-90c7-ed8aa58de116';

-- ---------- 発展 (はってん) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('737e9eed-8e85-4385-a499-410e60270910', 'N2', NULL, 'word', '発展', 'はってん', 'Phát triển', NULL, NULL, '動名詞', 46, '発展', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '経済が発展しました。', 'Kinh tế đã phát triển.', '経済が_____しました。', '発展', 'generated' from jp_vocab where id = '737e9eed-8e85-4385-a499-410e60270910';

-- ---------- 考慮 (こうりょ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('3bfa71e2-1f95-4cd8-81cc-bd871d9c095d', 'N2', NULL, 'word', '考慮', 'こうりょ', 'Xem xét, suy tính', NULL, NULL, '動名詞', 46, '考慮', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '状況を考慮します。', 'Tôi xem xét tình huống.', '状況を_____します。', '考慮', 'generated' from jp_vocab where id = '3bfa71e2-1f95-4cd8-81cc-bd871d9c095d';

-- ---------- 処置 (しょち) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('ab5d2879-0c8f-4191-b45f-07f64396548f', 'N2', NULL, 'word', '処置', 'しょち', 'Biện pháp, xử lý, điều trị', NULL, NULL, '動名詞', 46, '処置', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '怪我の処置をします。', 'Tôi xử lý vết thương.', '怪我の_____をします。', '処置', 'generated' from jp_vocab where id = 'ab5d2879-0c8f-4191-b45f-07f64396548f';

-- ---------- 普及 (ふきゅう) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('a52ad3a8-829d-4221-bda9-109a3b30824b', 'N2', NULL, 'word', '普及', 'ふきゅう', 'Lan tràn, phổ biến', NULL, NULL, '動名詞', 46, '普及', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'スマホが普及しました。', 'Điện thoại thông minh đã trở nên phổ biến.', 'スマホが_____しました。', '普及', 'generated' from jp_vocab where id = 'a52ad3a8-829d-4221-bda9-109a3b30824b';

-- ---------- 操作 (そうさ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('201e5d57-18fd-4b2b-af3c-55650559919e', 'N2', NULL, 'word', '操作', 'そうさ', 'Thao tác, vận hành', NULL, NULL, '動名詞', 46, '操作', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '機械を操作します。', 'Tôi vận hành máy móc.', '機械を_____します。', '操作', 'generated' from jp_vocab where id = '201e5d57-18fd-4b2b-af3c-55650559919e';

-- ---------- 抵抗 (ていこう) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('ae2fa114-095f-4cb3-8718-e2c264e4c8eb', 'N2', NULL, 'word', '抵抗', 'ていこう', 'Đề kháng, kháng', NULL, NULL, '動名詞', 46, '抵抗', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '変化に抵抗します。', 'Tôi kháng cự lại sự thay đổi.', '変化に_____します。', '抵抗', 'generated' from jp_vocab where id = 'ae2fa114-095f-4cb3-8718-e2c264e4c8eb';

-- ---------- 管理 (かんり) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('8969add3-a0c9-4dee-a5a7-729bfd0953c4', 'N2', NULL, 'word', '管理', 'かんり', 'Quản lý, điều hành, điều khiển', NULL, NULL, '動名詞', 46, '管理', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お金を管理します。', 'Tôi quản lý tiền bạc.', 'お金を_____します。', '管理', 'generated' from jp_vocab where id = '8969add3-a0c9-4dee-a5a7-729bfd0953c4';

-- ---------- 構成 (こうせい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('84cd6d17-ab11-4d71-a8ef-0ca1d080365c', 'N2', NULL, 'word', '構成', 'こうせい', 'Cấu trúc', NULL, NULL, '動名詞', 46, '構成', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '文章を構成します。', 'Tôi cấu trúc bài văn.', '文章を_____します。', '構成', 'generated' from jp_vocab where id = '84cd6d17-ab11-4d71-a8ef-0ca1d080365c';

-- ---------- 供給 (きょうきゅう) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('57dfb98b-9013-4260-b5df-f6c76255b0c7', 'N2', NULL, 'word', '供給', 'きょうきゅう', 'Cung cấp', NULL, NULL, '動名詞', 46, '供給', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '電力を供給します。', 'Tôi cung cấp điện năng.', '電力を_____します。', '供給', 'generated' from jp_vocab where id = '57dfb98b-9013-4260-b5df-f6c76255b0c7';

-- ---------- 汚染 (おせん) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('760141a8-cd8a-4cfe-888f-ab5d8e3b8cfe', 'N2', NULL, 'word', '汚染', 'おせん', 'Ô nhiễm', NULL, NULL, '動名詞', 46, '汚染', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '海が汚染されました。', 'Biển đã bị ô nhiễm.', '海が_____されました。', '汚染', 'generated' from jp_vocab where id = '760141a8-cd8a-4cfe-888f-ab5d8e3b8cfe';

-- ---------- 分布 (ぶんぷ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('3a6824b3-807f-4641-8092-2f96b3bf0c92', 'N2', NULL, 'word', '分布', 'ぶんぷ', 'Phân phối, phân bố', NULL, NULL, '動名詞', 46, '分布', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '人口の分布を調べます。', 'Tôi khảo sát sự phân bố dân số.', '人口の_____を調べます。', '分布', 'generated' from jp_vocab where id = '3a6824b3-807f-4641-8092-2f96b3bf0c92';

-- ---------- 達成 (たっせい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('f616897d-3ce4-4c55-ae54-619795f95559', 'N2', NULL, 'word', '達成', 'たっせい', 'Thành tựu, đạt được', NULL, NULL, '動名詞', 46, '達成', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '目標を達成しました。', 'Tôi đã đạt được mục tiêu.', '目標を_____しました。', '達成', 'generated' from jp_vocab where id = 'f616897d-3ce4-4c55-ae54-619795f95559';

-- ---------- 刺激 (しげき) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('feee4fd6-55f0-40ce-8b15-20dc08b8ccff', 'N2', NULL, 'word', '刺激', 'しげき', 'Kích thích, khích lệ, khiêu khích', NULL, NULL, '動名詞', 46, '刺激', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '脳を刺激します。', 'Nó kích thích não bộ.', '脳を_____します。', '刺激', 'generated' from jp_vocab where id = 'feee4fd6-55f0-40ce-8b15-20dc08b8ccff';

-- ---------- 消化 (しょうか) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('b05520a1-d566-4885-b38b-b2bed3379188', 'N2', NULL, 'word', '消化', 'しょうか', 'Tiêu hóa, xử lý', NULL, NULL, '動名詞', 46, '消化', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '食べ物を消化します。', 'Tôi tiêu hóa thức ăn.', '食べ物を_____します。', '消化', 'generated' from jp_vocab where id = 'b05520a1-d566-4885-b38b-b2bed3379188';

-- ---------- 吸収 (きゅうしゅう) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('249bca95-f93a-4541-8779-481e244d2216', 'N2', NULL, 'word', '吸収', 'きゅうしゅう', 'Tiếp thu, hấp thụ', NULL, NULL, '動名詞', 46, '吸収', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '知識を吸収します。', 'Tôi hấp thụ kiến thức.', '知識を_____します。', '吸収', 'generated' from jp_vocab where id = '249bca95-f93a-4541-8779-481e244d2216';

-- ---------- 収穫 (しゅうかく) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('8f9d826e-8878-44d8-8857-65e05e13c079', 'N2', NULL, 'word', '収穫', 'しゅうかく', 'Thu hoạch, thu được, có được', NULL, NULL, '動名詞', 46, '収穫', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '米を収穫します。', 'Tôi thu hoạch lúa.', '米を_____します。', '収穫', 'generated' from jp_vocab where id = '8f9d826e-8878-44d8-8857-65e05e13c079';

-- ---------- 収集 (しゅうしゅう) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('b10b86ac-600c-481a-bfe6-73b4cd9c2265', 'N2', NULL, 'word', '収集', 'しゅうしゅう', 'Thu thập, sưu tầm', NULL, NULL, '動名詞', 46, '収集', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '切手を収集します。', 'Tôi sưu tầm tem.', '切手を_____します。', '収集', 'generated' from jp_vocab where id = 'b10b86ac-600c-481a-bfe6-73b4cd9c2265';

-- ---------- 滞在 (たいざい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('4d9b9f4a-2344-4d0c-954a-482ed87cd46f', 'N2', NULL, 'word', '滞在', 'たいざい', 'Ở lại, lưu lại', NULL, NULL, '動名詞', 46, '滞在', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ホテルに滞在します。', 'Tôi lưu trú ở khách sạn.', 'ホテルに_____します。', '滞在', 'generated' from jp_vocab where id = '4d9b9f4a-2344-4d0c-954a-482ed87cd46f';

-- ---------- 歓迎 (かんげい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('a80e39f2-e90c-45f6-a1c5-80822463402c', 'N2', NULL, 'word', '歓迎', 'かんげい', 'Hoan nghênh, tiếp đón', NULL, NULL, '動名詞', 46, '歓迎', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お客様を歓迎します。', 'Chúng tôi hoan nghênh khách hàng.', 'お客様を_____します。', '歓迎', 'generated' from jp_vocab where id = 'a80e39f2-e90c-45f6-a1c5-80822463402c';

-- ---------- 検討 (けんとう) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('058446db-2afd-4eb5-8fa2-c33f3170dd3b', 'N2', NULL, 'word', '検討', 'けんとう', 'Kiểm tra, điều tra, xem xét', NULL, NULL, '動名詞', 46, '検討', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '計画を検討します。', 'Tôi xem xét kế hoạch.', '計画を_____します。', '検討', 'generated' from jp_vocab where id = '058446db-2afd-4eb5-8fa2-c33f3170dd3b';

-- ---------- 選択 (せんたく) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('ca2bd5e8-bc8a-4381-a749-fb31f9d4bd00', 'N2', NULL, 'word', '選択', 'せんたく', 'Lựa chọn', NULL, NULL, '動名詞', 46, '選択', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '道を選択します。', 'Tôi lựa chọn con đường.', '道を_____します。', '選択', 'generated' from jp_vocab where id = 'ca2bd5e8-bc8a-4381-a749-fb31f9d4bd00';

-- ---------- 訂正 (ていせい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('087f40c6-2ac9-493f-b7e9-2ff3bbd8c12f', 'N2', NULL, 'word', '訂正', 'ていせい', 'Đính chính, hiệu đính, sửa lại', NULL, NULL, '動名詞', 46, '訂正', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '間違いを訂正します。', 'Tôi sửa lại lỗi sai.', '間違いを_____します。', '訂正', 'generated' from jp_vocab where id = '087f40c6-2ac9-493f-b7e9-2ff3bbd8c12f';

-- ---------- 修正 (しゅうせい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('bc598850-35a2-46be-90c3-a9c83822145f', 'N2', NULL, 'word', '修正', 'しゅうせい', 'Chỉnh sửa, sửa đổi', NULL, NULL, '動名詞', 46, '修正', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '文章を修正します。', 'Tôi chỉnh sửa bài văn.', '文章を_____します。', '修正', 'generated' from jp_vocab where id = 'bc598850-35a2-46be-90c3-a9c83822145f';

-- ---------- 処理 (しょり) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('010b8122-36f7-446f-9c21-957a308bd8d1', 'N2', NULL, 'word', '処理', 'しょり', 'Xử lý, giải quyết', NULL, NULL, '動名詞', 46, '処理', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'データを処理します。', 'Tôi xử lý dữ liệu.', 'データを_____します。', '処理', 'generated' from jp_vocab where id = '010b8122-36f7-446f-9c21-957a308bd8d1';

-- ---------- 制限 (せいげん) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('a6c3eb9e-d2dd-4f45-aaa5-0f6b1894bb0d', 'N2', NULL, 'word', '制限', 'せいげん', 'Hạn chế', NULL, NULL, '動名詞', 46, '制限', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '速度を制限します。', 'Tôi hạn chế tốc độ.', '速度を_____します。', '制限', 'generated' from jp_vocab where id = 'a6c3eb9e-d2dd-4f45-aaa5-0f6b1894bb0d';

-- ---------- 重視 (じゅうし) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('c6270d00-f850-4da4-a5b3-af310c5c9e5e', 'N2', NULL, 'word', '重視', 'じゅうし', 'Coi trọng', NULL, NULL, '動名詞', 46, '重視', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '健康を重視します。', 'Tôi coi trọng sức khỏe.', '健康を_____します。', '重視', 'generated' from jp_vocab where id = 'c6270d00-f850-4da4-a5b3-af310c5c9e5e';

-- ---------- 反抗 (はんこう) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('aceb4463-8a66-4bb3-9873-998634481152', 'N2', NULL, 'word', '反抗', 'はんこう', 'Phản đối, phản kháng', NULL, NULL, '動名詞', 46, '反抗', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '親に反抗します。', 'Tôi phản kháng lại cha mẹ.', '親に_____します。', '反抗', 'generated' from jp_vocab where id = 'aceb4463-8a66-4bb3-9873-998634481152';

-- ---------- 分析 (ぶんせき) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('157e5ce1-2385-43b2-b7f0-22db92653660', 'N2', NULL, 'word', '分析', 'ぶんせき', 'Phân tích', NULL, NULL, '動名詞', 46, '分析', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'データを分析します。', 'Tôi phân tích dữ liệu.', 'データを_____します。', '分析', 'generated' from jp_vocab where id = '157e5ce1-2385-43b2-b7f0-22db92653660';

-- ---------- 維持 (いじ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('dcd231cb-dd31-4472-b4d4-df6c99214e7c', 'N2', NULL, 'word', '維持', 'いじ', 'Duy trì', NULL, NULL, '動名詞', 46, '維持', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '健康を維持します。', 'Tôi duy trì sức khỏe.', '健康を_____します。', '維持', 'generated' from jp_vocab where id = 'dcd231cb-dd31-4472-b4d4-df6c99214e7c';

-- ---------- 徹底 (てってい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('c27cd896-3a7e-4a23-b6a1-a3b22cf0e8f7', 'N2', NULL, 'word', '徹底', 'てってい', 'Triệt để, kỹ lưỡng', NULL, NULL, '動名詞', 46, '徹底', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '掃除を徹底します。', 'Tôi dọn dẹp triệt để.', '掃除を_____します。', '徹底', 'generated' from jp_vocab where id = 'c27cd896-3a7e-4a23-b6a1-a3b22cf0e8f7';

-- ---------- 組織 (そしき) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('e5e73e7e-e983-4013-bbb3-162d25405b92', 'N2', NULL, 'word', '組織', 'そしき', 'Tổ chức, thành lập', NULL, NULL, '動名詞', 46, '組織', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'チームを組織します。', 'Tôi tổ chức đội nhóm.', 'チームを_____します。', '組織', 'generated' from jp_vocab where id = 'e5e73e7e-e983-4013-bbb3-162d25405b92';

-- ---------- 付属 (ふぞく) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('d7e835ba-55d8-4efe-b351-a1cbb2aa4538', 'N2', NULL, 'word', '付属', 'ふぞく', 'Đi, đính kèm theo', NULL, NULL, '動名詞', 46, '付属', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '説明書が付属しています。', 'Có kèm theo sách hướng dẫn.', '説明書が_____しています。', '付属', 'generated' from jp_vocab where id = 'd7e835ba-55d8-4efe-b351-a1cbb2aa4538';

-- ---------- 関連 (かんれん) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('7dce47c9-efee-4c1a-9783-d2a514488ee0', 'N2', NULL, 'word', '関連', 'かんれん', 'Liên quan, sự kết nối', NULL, NULL, '動名詞', 46, '関連', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '事件に関連しています。', 'Nó có liên quan đến vụ việc.', '事件に_____しています。', '関連', 'generated' from jp_vocab where id = '7dce47c9-efee-4c1a-9783-d2a514488ee0';

-- ---------- 手当 (てあて) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('61dbe6db-6f5d-44a4-bcd9-e5299d3b5165', 'N2', NULL, 'word', '手当', 'てあて', 'Phụ cấp, chuẩn bị, chữa trị', NULL, NULL, '動名詞', 46, '手当', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '傷の手当をします。', 'Tôi chữa trị vết thương.', '傷の_____をします。', '手当', 'generated' from jp_vocab where id = '61dbe6db-6f5d-44a4-bcd9-e5299d3b5165';

-- ---------- 伝染 (でんせん) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('b9390c25-652e-4b7a-ae24-267a1d027b0c', 'N2', NULL, 'word', '伝染', 'でんせん', 'Truyền nhiễm', NULL, NULL, '動名詞', 46, '伝染', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '病気が伝染します。', 'Bệnh lây truyền.', '病気が_____します。', '伝染', 'generated' from jp_vocab where id = 'b9390c25-652e-4b7a-ae24-267a1d027b0c';

-- ---------- でこぼこ (でこぼこ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('0022f7da-008b-4b8c-8fc5-4f36171cd042', 'N2', NULL, 'word', 'でこぼこ', 'でこぼこ', 'Lồi lõm, ổ gà', NULL, NULL, '動名詞', 46, 'でこぼこ', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '道がでこぼこしています。', 'Con đường lồi lõm.', '道が_____しています。', 'でこぼこ', 'generated' from jp_vocab where id = '0022f7da-008b-4b8c-8fc5-4f36171cd042';

-- ---------- jp_vocab_questions: generated, 4 câu/từ ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"中断" có nghĩa là gì?', 'Phát triển', 'Cung cấp', 'Gián đoạn', 'Duy trì', 'Gián đoạn', 'generated' from jp_vocab where id = 'aa17caf8-d466-49c7-9490-481778a65747';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Gián đoạn"?', '供給', '中断', '選択', '制限', '中断', 'generated' from jp_vocab where id = 'aa17caf8-d466-49c7-9490-481778a65747';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"中断" đọc là gì?', 'ぶんぷ', 'せんたく', 'ちゅうだん', 'いじ', 'ちゅうだん', 'generated' from jp_vocab where id = 'aa17caf8-d466-49c7-9490-481778a65747';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 工事が_____しました。', '中断', 'generated' from jp_vocab where id = 'aa17caf8-d466-49c7-9490-481778a65747';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"摩擦" có nghĩa là gì?', 'Hạn chế', 'Lựa chọn', 'Cấu trúc', 'Ma sát', 'Ma sát', 'generated' from jp_vocab where id = 'a9cf786d-40ee-45e4-bef6-6d429221ce2d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Ma sát"?', '摩擦', '汚染', '処置', '供給', '摩擦', 'generated' from jp_vocab where id = 'a9cf786d-40ee-45e4-bef6-6d429221ce2d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"摩擦" đọc là gì?', 'ていこう', 'しゅうしゅう', 'まさつ', 'たいざい', 'まさつ', 'generated' from jp_vocab where id = 'a9cf786d-40ee-45e4-bef6-6d429221ce2d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 国同士の_____が起きました。', '摩擦', 'generated' from jp_vocab where id = 'a9cf786d-40ee-45e4-bef6-6d429221ce2d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"栽培" có nghĩa là gì?', 'Đề kháng, kháng', 'Cung cấp', 'Trồng trọt, canh tác', 'Phản đối, phản kháng', 'Trồng trọt, canh tác', 'generated' from jp_vocab where id = 'f638ce2d-9d52-4e21-abb8-988f7215dc65';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Trồng trọt, canh tác"?', '栽培', '刺激', '管理', '発展', '栽培', 'generated' from jp_vocab where id = 'f638ce2d-9d52-4e21-abb8-988f7215dc65';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"栽培" đọc là gì?', 'しげき', 'さいばい', 'かんれん', 'しゅうしゅう', 'さいばい', 'generated' from jp_vocab where id = 'f638ce2d-9d52-4e21-abb8-988f7215dc65';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 野菜を_____します。', '栽培', 'generated' from jp_vocab where id = 'f638ce2d-9d52-4e21-abb8-988f7215dc65';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"所有" có nghĩa là gì?', 'Duy trì', 'Chỉnh sửa, sửa đổi', 'Ma sát', 'Sở hữu', 'Sở hữu', 'generated' from jp_vocab where id = '1907619c-090d-43de-90c7-ed8aa58de116';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sở hữu"?', '刺激', '中断', '所有', '普及', '所有', 'generated' from jp_vocab where id = '1907619c-090d-43de-90c7-ed8aa58de116';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"所有" đọc là gì?', 'しゅうせい', 'しょゆう', 'そうさ', 'はってん', 'しょゆう', 'generated' from jp_vocab where id = '1907619c-090d-43de-90c7-ed8aa58de116';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 車を_____しています。', '所有', 'generated' from jp_vocab where id = '1907619c-090d-43de-90c7-ed8aa58de116';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"発展" có nghĩa là gì?', 'Thao tác, vận hành', 'Ô nhiễm', 'Phát triển', 'Gián đoạn', 'Phát triển', 'generated' from jp_vocab where id = '737e9eed-8e85-4385-a499-410e60270910';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Phát triển"?', '選択', '処理', 'でこぼこ', '発展', '発展', 'generated' from jp_vocab where id = '737e9eed-8e85-4385-a499-410e60270910';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"発展" đọc là gì?', 'しょうか', 'はってん', 'てってい', 'きゅうしゅう', 'はってん', 'generated' from jp_vocab where id = '737e9eed-8e85-4385-a499-410e60270910';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 経済が_____しました。', '発展', 'generated' from jp_vocab where id = '737e9eed-8e85-4385-a499-410e60270910';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"考慮" có nghĩa là gì?', 'Hoan nghênh, tiếp đón', 'Cấu trúc', 'Xem xét, suy tính', 'Coi trọng', 'Xem xét, suy tính', 'generated' from jp_vocab where id = '3bfa71e2-1f95-4cd8-81cc-bd871d9c095d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Xem xét, suy tính"?', '収穫', '考慮', '選択', '分布', '考慮', 'generated' from jp_vocab where id = '3bfa71e2-1f95-4cd8-81cc-bd871d9c095d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"考慮" đọc là gì?', 'けんとう', 'しょち', 'しげき', 'こうりょ', 'こうりょ', 'generated' from jp_vocab where id = '3bfa71e2-1f95-4cd8-81cc-bd871d9c095d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 状況を_____します。', '考慮', 'generated' from jp_vocab where id = '3bfa71e2-1f95-4cd8-81cc-bd871d9c095d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"処置" có nghĩa là gì?', 'Chỉnh sửa, sửa đổi', 'Duy trì', 'Sở hữu', 'Biện pháp, xử lý, điều trị', 'Biện pháp, xử lý, điều trị', 'generated' from jp_vocab where id = 'ab5d2879-0c8f-4191-b45f-07f64396548f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Biện pháp, xử lý, điều trị"?', '処置', '制限', '汚染', '摩擦', '処置', 'generated' from jp_vocab where id = 'ab5d2879-0c8f-4191-b45f-07f64396548f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"処置" đọc là gì?', 'ていせい', 'てあて', 'しょち', 'そしき', 'しょち', 'generated' from jp_vocab where id = 'ab5d2879-0c8f-4191-b45f-07f64396548f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 怪我の_____をします。', '処置', 'generated' from jp_vocab where id = 'ab5d2879-0c8f-4191-b45f-07f64396548f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"普及" có nghĩa là gì?', 'Liên quan, sự kết nối', 'Kiểm tra, điều tra, xem xét', 'Lan tràn, phổ biến', 'Ở lại, lưu lại', 'Lan tràn, phổ biến', 'generated' from jp_vocab where id = 'a52ad3a8-829d-4221-bda9-109a3b30824b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Lan tràn, phổ biến"?', '普及', '刺激', '達成', '伝染', '普及', 'generated' from jp_vocab where id = 'a52ad3a8-829d-4221-bda9-109a3b30824b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"普及" đọc là gì?', 'たっせい', 'いじ', 'でんせん', 'ふきゅう', 'ふきゅう', 'generated' from jp_vocab where id = 'a52ad3a8-829d-4221-bda9-109a3b30824b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: スマホが_____しました。', '普及', 'generated' from jp_vocab where id = 'a52ad3a8-829d-4221-bda9-109a3b30824b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"操作" có nghĩa là gì?', 'Ma sát', 'Ở lại, lưu lại', 'Liên quan, sự kết nối', 'Thao tác, vận hành', 'Thao tác, vận hành', 'generated' from jp_vocab where id = '201e5d57-18fd-4b2b-af3c-55650559919e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Thao tác, vận hành"?', '分析', '収穫', '処置', '操作', '操作', 'generated' from jp_vocab where id = '201e5d57-18fd-4b2b-af3c-55650559919e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"操作" đọc là gì?', 'ぶんぷ', 'そうさ', 'ていこう', 'さいばい', 'そうさ', 'generated' from jp_vocab where id = '201e5d57-18fd-4b2b-af3c-55650559919e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 機械を_____します。', '操作', 'generated' from jp_vocab where id = '201e5d57-18fd-4b2b-af3c-55650559919e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"抵抗" có nghĩa là gì?', 'Lồi lõm, ổ gà', 'Chỉnh sửa, sửa đổi', 'Đề kháng, kháng', 'Trồng trọt, canh tác', 'Đề kháng, kháng', 'generated' from jp_vocab where id = 'ae2fa114-095f-4cb3-8718-e2c264e4c8eb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Đề kháng, kháng"?', '抵抗', '収穫', '中断', '制限', '抵抗', 'generated' from jp_vocab where id = 'ae2fa114-095f-4cb3-8718-e2c264e4c8eb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"抵抗" đọc là gì?', 'ていこう', 'ぶんせき', 'かんげい', 'しゅうしゅう', 'ていこう', 'generated' from jp_vocab where id = 'ae2fa114-095f-4cb3-8718-e2c264e4c8eb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 変化に_____します。', '抵抗', 'generated' from jp_vocab where id = 'ae2fa114-095f-4cb3-8718-e2c264e4c8eb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"管理" có nghĩa là gì?', 'Quản lý, điều hành, điều khiển', 'Xem xét, suy tính', 'Duy trì', 'Lựa chọn', 'Quản lý, điều hành, điều khiển', 'generated' from jp_vocab where id = '8969add3-a0c9-4dee-a5a7-729bfd0953c4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Quản lý, điều hành, điều khiển"?', 'でこぼこ', '歓迎', '栽培', '管理', '管理', 'generated' from jp_vocab where id = '8969add3-a0c9-4dee-a5a7-729bfd0953c4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"管理" đọc là gì?', 'そうさ', 'かんり', 'ちゅうだん', 'ふきゅう', 'かんり', 'generated' from jp_vocab where id = '8969add3-a0c9-4dee-a5a7-729bfd0953c4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: お金を_____します。', '管理', 'generated' from jp_vocab where id = '8969add3-a0c9-4dee-a5a7-729bfd0953c4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"構成" có nghĩa là gì?', 'Ma sát', 'Xem xét, suy tính', 'Phân phối, phân bố', 'Cấu trúc', 'Cấu trúc', 'generated' from jp_vocab where id = '84cd6d17-ab11-4d71-a8ef-0ca1d080365c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Cấu trúc"?', '組織', '構成', '維持', '供給', '構成', 'generated' from jp_vocab where id = '84cd6d17-ab11-4d71-a8ef-0ca1d080365c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"構成" đọc là gì?', 'じゅうし', 'しょうか', 'ふぞく', 'こうせい', 'こうせい', 'generated' from jp_vocab where id = '84cd6d17-ab11-4d71-a8ef-0ca1d080365c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 文章を_____します。', '構成', 'generated' from jp_vocab where id = '84cd6d17-ab11-4d71-a8ef-0ca1d080365c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"供給" có nghĩa là gì?', 'Ma sát', 'Cung cấp', 'Tiêu hóa, xử lý', 'Phân phối, phân bố', 'Cung cấp', 'generated' from jp_vocab where id = '57dfb98b-9013-4260-b5df-f6c76255b0c7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Cung cấp"?', '供給', '消化', '検討', '徹底', '供給', 'generated' from jp_vocab where id = '57dfb98b-9013-4260-b5df-f6c76255b0c7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"供給" đọc là gì?', 'きょうきゅう', 'かんれん', 'いじ', 'かんり', 'きょうきゅう', 'generated' from jp_vocab where id = '57dfb98b-9013-4260-b5df-f6c76255b0c7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 電力を_____します。', '供給', 'generated' from jp_vocab where id = '57dfb98b-9013-4260-b5df-f6c76255b0c7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"汚染" có nghĩa là gì?', 'Đính chính, hiệu đính, sửa lại', 'Ô nhiễm', 'Thành tựu, đạt được', 'Phụ cấp, chuẩn bị, chữa trị', 'Ô nhiễm', 'generated' from jp_vocab where id = '760141a8-cd8a-4cfe-888f-ab5d8e3b8cfe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Ô nhiễm"?', '訂正', '考慮', '伝染', '汚染', '汚染', 'generated' from jp_vocab where id = '760141a8-cd8a-4cfe-888f-ab5d8e3b8cfe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"汚染" đọc là gì?', 'まさつ', 'しげき', 'おせん', 'ちゅうだん', 'おせん', 'generated' from jp_vocab where id = '760141a8-cd8a-4cfe-888f-ab5d8e3b8cfe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 海が_____されました。', '汚染', 'generated' from jp_vocab where id = '760141a8-cd8a-4cfe-888f-ab5d8e3b8cfe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"分布" có nghĩa là gì?', 'Duy trì', 'Đề kháng, kháng', 'Thao tác, vận hành', 'Phân phối, phân bố', 'Phân phối, phân bố', 'generated' from jp_vocab where id = '3a6824b3-807f-4641-8092-2f96b3bf0c92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Phân phối, phân bố"?', '修正', '手当', '分布', '収集', '分布', 'generated' from jp_vocab where id = '3a6824b3-807f-4641-8092-2f96b3bf0c92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"分布" đọc là gì?', 'たいざい', 'きょうきゅう', 'そうさ', 'ぶんぷ', 'ぶんぷ', 'generated' from jp_vocab where id = '3a6824b3-807f-4641-8092-2f96b3bf0c92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 人口の_____を調べます。', '分布', 'generated' from jp_vocab where id = '3a6824b3-807f-4641-8092-2f96b3bf0c92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"達成" có nghĩa là gì?', 'Lồi lõm, ổ gà', 'Thành tựu, đạt được', 'Gián đoạn', 'Quản lý, điều hành, điều khiển', 'Thành tựu, đạt được', 'generated' from jp_vocab where id = 'f616897d-3ce4-4c55-ae54-619795f95559';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Thành tựu, đạt được"?', '徹底', '達成', '選択', '刺激', '達成', 'generated' from jp_vocab where id = 'f616897d-3ce4-4c55-ae54-619795f95559';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"達成" đọc là gì?', 'せんたく', 'さいばい', 'ていこう', 'たっせい', 'たっせい', 'generated' from jp_vocab where id = 'f616897d-3ce4-4c55-ae54-619795f95559';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 目標を_____しました。', '達成', 'generated' from jp_vocab where id = 'f616897d-3ce4-4c55-ae54-619795f95559';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"刺激" có nghĩa là gì?', 'Ma sát', 'Kích thích, khích lệ, khiêu khích', 'Hạn chế', 'Hoan nghênh, tiếp đón', 'Kích thích, khích lệ, khiêu khích', 'generated' from jp_vocab where id = 'feee4fd6-55f0-40ce-8b15-20dc08b8ccff';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Kích thích, khích lệ, khiêu khích"?', '所有', '検討', '刺激', '操作', '刺激', 'generated' from jp_vocab where id = 'feee4fd6-55f0-40ce-8b15-20dc08b8ccff';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"刺激" đọc là gì?', 'おせん', 'たいざい', 'しげき', 'きょうきゅう', 'しげき', 'generated' from jp_vocab where id = 'feee4fd6-55f0-40ce-8b15-20dc08b8ccff';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 脳を_____します。', '刺激', 'generated' from jp_vocab where id = 'feee4fd6-55f0-40ce-8b15-20dc08b8ccff';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"消化" có nghĩa là gì?', 'Sở hữu', 'Kiểm tra, điều tra, xem xét', 'Tiêu hóa, xử lý', 'Phân tích', 'Tiêu hóa, xử lý', 'generated' from jp_vocab where id = 'b05520a1-d566-4885-b38b-b2bed3379188';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Tiêu hóa, xử lý"?', '消化', '中断', '関連', '操作', '消化', 'generated' from jp_vocab where id = 'b05520a1-d566-4885-b38b-b2bed3379188';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"消化" đọc là gì?', 'まさつ', 'しょうか', 'たいざい', 'ていせい', 'しょうか', 'generated' from jp_vocab where id = 'b05520a1-d566-4885-b38b-b2bed3379188';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 食べ物を_____します。', '消化', 'generated' from jp_vocab where id = 'b05520a1-d566-4885-b38b-b2bed3379188';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"吸収" có nghĩa là gì?', 'Phụ cấp, chuẩn bị, chữa trị', 'Thu thập, sưu tầm', 'Tiếp thu, hấp thụ', 'Phân tích', 'Tiếp thu, hấp thụ', 'generated' from jp_vocab where id = '249bca95-f93a-4541-8779-481e244d2216';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Tiếp thu, hấp thụ"?', '徹底', '操作', '吸収', '付属', '吸収', 'generated' from jp_vocab where id = '249bca95-f93a-4541-8779-481e244d2216';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"吸収" đọc là gì?', 'きゅうしゅう', 'しょゆう', 'しゅうせい', 'こうせい', 'きゅうしゅう', 'generated' from jp_vocab where id = '249bca95-f93a-4541-8779-481e244d2216';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 知識を_____します。', '吸収', 'generated' from jp_vocab where id = '249bca95-f93a-4541-8779-481e244d2216';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"収穫" có nghĩa là gì?', 'Đi, đính kèm theo', 'Thu thập, sưu tầm', 'Coi trọng', 'Thu hoạch, thu được, có được', 'Thu hoạch, thu được, có được', 'generated' from jp_vocab where id = '8f9d826e-8878-44d8-8857-65e05e13c079';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Thu hoạch, thu được, có được"?', '汚染', '収集', '中断', '収穫', '収穫', 'generated' from jp_vocab where id = '8f9d826e-8878-44d8-8857-65e05e13c079';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"収穫" đọc là gì?', 'たいざい', 'しゅうかく', 'おせん', 'けんとう', 'しゅうかく', 'generated' from jp_vocab where id = '8f9d826e-8878-44d8-8857-65e05e13c079';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 米を_____します。', '収穫', 'generated' from jp_vocab where id = '8f9d826e-8878-44d8-8857-65e05e13c079';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"収集" có nghĩa là gì?', 'Lựa chọn', 'Biện pháp, xử lý, điều trị', 'Đi, đính kèm theo', 'Thu thập, sưu tầm', 'Thu thập, sưu tầm', 'generated' from jp_vocab where id = 'b10b86ac-600c-481a-bfe6-73b4cd9c2265';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Thu thập, sưu tầm"?', '修正', '収集', '達成', '徹底', '収集', 'generated' from jp_vocab where id = 'b10b86ac-600c-481a-bfe6-73b4cd9c2265';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"収集" đọc là gì?', 'でこぼこ', 'いじ', 'しゅうしゅう', 'ていせい', 'しゅうしゅう', 'generated' from jp_vocab where id = 'b10b86ac-600c-481a-bfe6-73b4cd9c2265';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 切手を_____します。', '収集', 'generated' from jp_vocab where id = 'b10b86ac-600c-481a-bfe6-73b4cd9c2265';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"滞在" có nghĩa là gì?', 'Ở lại, lưu lại', 'Kích thích, khích lệ, khiêu khích', 'Xem xét, suy tính', 'Hạn chế', 'Ở lại, lưu lại', 'generated' from jp_vocab where id = '4d9b9f4a-2344-4d0c-954a-482ed87cd46f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Ở lại, lưu lại"?', '滞在', '消化', '構成', '処置', '滞在', 'generated' from jp_vocab where id = '4d9b9f4a-2344-4d0c-954a-482ed87cd46f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"滞在" đọc là gì?', 'かんげい', 'たいざい', 'ぶんせき', 'そうさ', 'たいざい', 'generated' from jp_vocab where id = '4d9b9f4a-2344-4d0c-954a-482ed87cd46f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: ホテルに_____します。', '滞在', 'generated' from jp_vocab where id = '4d9b9f4a-2344-4d0c-954a-482ed87cd46f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"歓迎" có nghĩa là gì?', 'Hạn chế', 'Duy trì', 'Hoan nghênh, tiếp đón', 'Tiêu hóa, xử lý', 'Hoan nghênh, tiếp đón', 'generated' from jp_vocab where id = 'a80e39f2-e90c-45f6-a1c5-80822463402c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Hoan nghênh, tiếp đón"?', '重視', '所有', '滞在', '歓迎', '歓迎', 'generated' from jp_vocab where id = 'a80e39f2-e90c-45f6-a1c5-80822463402c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"歓迎" đọc là gì?', 'かんり', 'しゅうせい', 'ふぞく', 'かんげい', 'かんげい', 'generated' from jp_vocab where id = 'a80e39f2-e90c-45f6-a1c5-80822463402c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: お客様を_____します。', '歓迎', 'generated' from jp_vocab where id = 'a80e39f2-e90c-45f6-a1c5-80822463402c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"検討" có nghĩa là gì?', 'Tiêu hóa, xử lý', 'Liên quan, sự kết nối', 'Ô nhiễm', 'Kiểm tra, điều tra, xem xét', 'Kiểm tra, điều tra, xem xét', 'generated' from jp_vocab where id = '058446db-2afd-4eb5-8fa2-c33f3170dd3b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Kiểm tra, điều tra, xem xét"?', '吸収', '達成', '中断', '検討', '検討', 'generated' from jp_vocab where id = '058446db-2afd-4eb5-8fa2-c33f3170dd3b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"検討" đọc là gì?', 'てあて', 'じゅうし', 'おせん', 'けんとう', 'けんとう', 'generated' from jp_vocab where id = '058446db-2afd-4eb5-8fa2-c33f3170dd3b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 計画を_____します。', '検討', 'generated' from jp_vocab where id = '058446db-2afd-4eb5-8fa2-c33f3170dd3b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"選択" có nghĩa là gì?', 'Thao tác, vận hành', 'Coi trọng', 'Lựa chọn', 'Lan tràn, phổ biến', 'Lựa chọn', 'generated' from jp_vocab where id = 'ca2bd5e8-bc8a-4381-a749-fb31f9d4bd00';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Lựa chọn"?', '達成', '吸収', '徹底', '選択', '選択', 'generated' from jp_vocab where id = 'ca2bd5e8-bc8a-4381-a749-fb31f9d4bd00';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"選択" đọc là gì?', 'ぶんせき', 'せんたく', 'こうせい', 'しげき', 'せんたく', 'generated' from jp_vocab where id = 'ca2bd5e8-bc8a-4381-a749-fb31f9d4bd00';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 道を_____します。', '選択', 'generated' from jp_vocab where id = 'ca2bd5e8-bc8a-4381-a749-fb31f9d4bd00';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"訂正" có nghĩa là gì?', 'Ma sát', 'Đề kháng, kháng', 'Đính chính, hiệu đính, sửa lại', 'Duy trì', 'Đính chính, hiệu đính, sửa lại', 'generated' from jp_vocab where id = '087f40c6-2ac9-493f-b7e9-2ff3bbd8c12f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Đính chính, hiệu đính, sửa lại"?', '訂正', '付属', '構成', '所有', '訂正', 'generated' from jp_vocab where id = '087f40c6-2ac9-493f-b7e9-2ff3bbd8c12f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"訂正" đọc là gì?', 'ふきゅう', 'しゅうせい', 'ていせい', 'きょうきゅう', 'ていせい', 'generated' from jp_vocab where id = '087f40c6-2ac9-493f-b7e9-2ff3bbd8c12f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 間違いを_____します。', '訂正', 'generated' from jp_vocab where id = '087f40c6-2ac9-493f-b7e9-2ff3bbd8c12f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"修正" có nghĩa là gì?', 'Tổ chức, thành lập', 'Phản đối, phản kháng', 'Chỉnh sửa, sửa đổi', 'Thu thập, sưu tầm', 'Chỉnh sửa, sửa đổi', 'generated' from jp_vocab where id = 'bc598850-35a2-46be-90c3-a9c83822145f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Chỉnh sửa, sửa đổi"?', '付属', '滞在', 'でこぼこ', '修正', '修正', 'generated' from jp_vocab where id = 'bc598850-35a2-46be-90c3-a9c83822145f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"修正" đọc là gì?', 'きゅうしゅう', 'しゅうせい', 'ていせい', 'ちゅうだん', 'しゅうせい', 'generated' from jp_vocab where id = 'bc598850-35a2-46be-90c3-a9c83822145f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 文章を_____します。', '修正', 'generated' from jp_vocab where id = 'bc598850-35a2-46be-90c3-a9c83822145f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"処理" có nghĩa là gì?', 'Xem xét, suy tính', 'Xử lý, giải quyết', 'Gián đoạn', 'Tiếp thu, hấp thụ', 'Xử lý, giải quyết', 'generated' from jp_vocab where id = '010b8122-36f7-446f-9c21-957a308bd8d1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Xử lý, giải quyết"?', '処理', '検討', 'でこぼこ', '徹底', '処理', 'generated' from jp_vocab where id = '010b8122-36f7-446f-9c21-957a308bd8d1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"処理" đọc là gì?', 'はんこう', 'しょり', 'きょうきゅう', 'ふきゅう', 'しょり', 'generated' from jp_vocab where id = '010b8122-36f7-446f-9c21-957a308bd8d1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: データを_____します。', '処理', 'generated' from jp_vocab where id = '010b8122-36f7-446f-9c21-957a308bd8d1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"制限" có nghĩa là gì?', 'Lan tràn, phổ biến', 'Tiêu hóa, xử lý', 'Duy trì', 'Hạn chế', 'Hạn chế', 'generated' from jp_vocab where id = 'a6c3eb9e-d2dd-4f45-aaa5-0f6b1894bb0d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Hạn chế"?', '発展', '選択', '刺激', '制限', '制限', 'generated' from jp_vocab where id = 'a6c3eb9e-d2dd-4f45-aaa5-0f6b1894bb0d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"制限" đọc là gì?', 'けんとう', 'ちゅうだん', 'しょち', 'せいげん', 'せいげん', 'generated' from jp_vocab where id = 'a6c3eb9e-d2dd-4f45-aaa5-0f6b1894bb0d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 速度を_____します。', '制限', 'generated' from jp_vocab where id = 'a6c3eb9e-d2dd-4f45-aaa5-0f6b1894bb0d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"重視" có nghĩa là gì?', 'Coi trọng', 'Triệt để, kỹ lưỡng', 'Đính chính, hiệu đính, sửa lại', 'Ô nhiễm', 'Coi trọng', 'generated' from jp_vocab where id = 'c6270d00-f850-4da4-a5b3-af310c5c9e5e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Coi trọng"?', '組織', '摩擦', '中断', '重視', '重視', 'generated' from jp_vocab where id = 'c6270d00-f850-4da4-a5b3-af310c5c9e5e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"重視" đọc là gì?', 'ふぞく', 'かんげい', 'てあて', 'じゅうし', 'じゅうし', 'generated' from jp_vocab where id = 'c6270d00-f850-4da4-a5b3-af310c5c9e5e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 健康を_____します。', '重視', 'generated' from jp_vocab where id = 'c6270d00-f850-4da4-a5b3-af310c5c9e5e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"反抗" có nghĩa là gì?', 'Xử lý, giải quyết', 'Sở hữu', 'Hoan nghênh, tiếp đón', 'Phản đối, phản kháng', 'Phản đối, phản kháng', 'generated' from jp_vocab where id = 'aceb4463-8a66-4bb3-9873-998634481152';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Phản đối, phản kháng"?', '滞在', '吸収', '反抗', '発展', '反抗', 'generated' from jp_vocab where id = 'aceb4463-8a66-4bb3-9873-998634481152';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"反抗" đọc là gì?', 'ぶんせき', 'はんこう', 'いじ', 'しょり', 'はんこう', 'generated' from jp_vocab where id = 'aceb4463-8a66-4bb3-9873-998634481152';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 親に_____します。', '反抗', 'generated' from jp_vocab where id = 'aceb4463-8a66-4bb3-9873-998634481152';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"分析" có nghĩa là gì?', 'Kích thích, khích lệ, khiêu khích', 'Truyền nhiễm', 'Đi, đính kèm theo', 'Phân tích', 'Phân tích', 'generated' from jp_vocab where id = '157e5ce1-2385-43b2-b7f0-22db92653660';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Phân tích"?', '考慮', '栽培', '分析', 'でこぼこ', '分析', 'generated' from jp_vocab where id = '157e5ce1-2385-43b2-b7f0-22db92653660';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"分析" đọc là gì?', 'そうさ', 'ぶんせき', 'こうせい', 'せいげん', 'ぶんせき', 'generated' from jp_vocab where id = '157e5ce1-2385-43b2-b7f0-22db92653660';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: データを_____します。', '分析', 'generated' from jp_vocab where id = '157e5ce1-2385-43b2-b7f0-22db92653660';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"維持" có nghĩa là gì?', 'Ma sát', 'Duy trì', 'Phân phối, phân bố', 'Chỉnh sửa, sửa đổi', 'Duy trì', 'generated' from jp_vocab where id = 'dcd231cb-dd31-4472-b4d4-df6c99214e7c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Duy trì"?', '維持', '汚染', '手当', '構成', '維持', 'generated' from jp_vocab where id = 'dcd231cb-dd31-4472-b4d4-df6c99214e7c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"維持" đọc là gì?', 'いじ', 'ちゅうだん', 'てあて', 'でんせん', 'いじ', 'generated' from jp_vocab where id = 'dcd231cb-dd31-4472-b4d4-df6c99214e7c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 健康を_____します。', '維持', 'generated' from jp_vocab where id = 'dcd231cb-dd31-4472-b4d4-df6c99214e7c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"徹底" có nghĩa là gì?', 'Ma sát', 'Triệt để, kỹ lưỡng', 'Lan tràn, phổ biến', 'Thành tựu, đạt được', 'Triệt để, kỹ lưỡng', 'generated' from jp_vocab where id = 'c27cd896-3a7e-4a23-b6a1-a3b22cf0e8f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Triệt để, kỹ lưỡng"?', '組織', '摩擦', '徹底', '達成', '徹底', 'generated' from jp_vocab where id = 'c27cd896-3a7e-4a23-b6a1-a3b22cf0e8f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"徹底" đọc là gì?', 'はんこう', 'まさつ', 'かんれん', 'てってい', 'てってい', 'generated' from jp_vocab where id = 'c27cd896-3a7e-4a23-b6a1-a3b22cf0e8f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 掃除を_____します。', '徹底', 'generated' from jp_vocab where id = 'c27cd896-3a7e-4a23-b6a1-a3b22cf0e8f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"組織" có nghĩa là gì?', 'Phát triển', 'Lựa chọn', 'Tổ chức, thành lập', 'Cấu trúc', 'Tổ chức, thành lập', 'generated' from jp_vocab where id = 'e5e73e7e-e983-4013-bbb3-162d25405b92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Tổ chức, thành lập"?', '考慮', '組織', '抵抗', '滞在', '組織', 'generated' from jp_vocab where id = 'e5e73e7e-e983-4013-bbb3-162d25405b92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"組織" đọc là gì?', 'ていせい', 'しょち', 'しげき', 'そしき', 'そしき', 'generated' from jp_vocab where id = 'e5e73e7e-e983-4013-bbb3-162d25405b92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: チームを_____します。', '組織', 'generated' from jp_vocab where id = 'e5e73e7e-e983-4013-bbb3-162d25405b92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"付属" có nghĩa là gì?', 'Lồi lõm, ổ gà', 'Thu hoạch, thu được, có được', 'Kiểm tra, điều tra, xem xét', 'Đi, đính kèm theo', 'Đi, đính kèm theo', 'generated' from jp_vocab where id = 'd7e835ba-55d8-4efe-b351-a1cbb2aa4538';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Đi, đính kèm theo"?', '中断', '選択', '修正', '付属', '付属', 'generated' from jp_vocab where id = 'd7e835ba-55d8-4efe-b351-a1cbb2aa4538';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"付属" đọc là gì?', 'いじ', 'ふぞく', 'ふきゅう', 'おせん', 'ふぞく', 'generated' from jp_vocab where id = 'd7e835ba-55d8-4efe-b351-a1cbb2aa4538';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 説明書が_____しています。', '付属', 'generated' from jp_vocab where id = 'd7e835ba-55d8-4efe-b351-a1cbb2aa4538';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"関連" có nghĩa là gì?', 'Chỉnh sửa, sửa đổi', 'Liên quan, sự kết nối', 'Phân tích', 'Kiểm tra, điều tra, xem xét', 'Liên quan, sự kết nối', 'generated' from jp_vocab where id = '7dce47c9-efee-4c1a-9783-d2a514488ee0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Liên quan, sự kết nối"?', '検討', '収集', '操作', '関連', '関連', 'generated' from jp_vocab where id = '7dce47c9-efee-4c1a-9783-d2a514488ee0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"関連" đọc là gì?', 'ふぞく', 'しょち', 'かんれん', 'きょうきゅう', 'かんれん', 'generated' from jp_vocab where id = '7dce47c9-efee-4c1a-9783-d2a514488ee0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 事件に_____しています。', '関連', 'generated' from jp_vocab where id = '7dce47c9-efee-4c1a-9783-d2a514488ee0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"手当" có nghĩa là gì?', 'Lựa chọn', 'Phản đối, phản kháng', 'Phụ cấp, chuẩn bị, chữa trị', 'Thu hoạch, thu được, có được', 'Phụ cấp, chuẩn bị, chữa trị', 'generated' from jp_vocab where id = '61dbe6db-6f5d-44a4-bcd9-e5299d3b5165';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Phụ cấp, chuẩn bị, chữa trị"?', '手当', '組織', '収穫', '処置', '手当', 'generated' from jp_vocab where id = '61dbe6db-6f5d-44a4-bcd9-e5299d3b5165';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"手当" đọc là gì?', 'てあて', 'そうさ', 'しゅうせい', 'いじ', 'てあて', 'generated' from jp_vocab where id = '61dbe6db-6f5d-44a4-bcd9-e5299d3b5165';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 傷の_____をします。', '手当', 'generated' from jp_vocab where id = '61dbe6db-6f5d-44a4-bcd9-e5299d3b5165';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"伝染" có nghĩa là gì?', 'Truyền nhiễm', 'Thu thập, sưu tầm', 'Xử lý, giải quyết', 'Liên quan, sự kết nối', 'Truyền nhiễm', 'generated' from jp_vocab where id = 'b9390c25-652e-4b7a-ae24-267a1d027b0c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Truyền nhiễm"?', '汚染', '伝染', '操作', '摩擦', '伝染', 'generated' from jp_vocab where id = 'b9390c25-652e-4b7a-ae24-267a1d027b0c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"伝染" đọc là gì?', 'でんせん', 'しょち', 'せいげん', 'しげき', 'でんせん', 'generated' from jp_vocab where id = 'b9390c25-652e-4b7a-ae24-267a1d027b0c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 病気が_____します。', '伝染', 'generated' from jp_vocab where id = 'b9390c25-652e-4b7a-ae24-267a1d027b0c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"でこぼこ" có nghĩa là gì?', 'Lồi lõm, ổ gà', 'Phản đối, phản kháng', 'Coi trọng', 'Triệt để, kỹ lưỡng', 'Lồi lõm, ổ gà', 'generated' from jp_vocab where id = '0022f7da-008b-4b8c-8fc5-4f36171cd042';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Lồi lõm, ổ gà"?', '維持', '関連', 'でこぼこ', '普及', 'でこぼこ', 'generated' from jp_vocab where id = '0022f7da-008b-4b8c-8fc5-4f36171cd042';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"でこぼこ" đọc là gì?', 'でこぼこ', 'そしき', 'かんげい', 'ていせい', 'でこぼこ', 'generated' from jp_vocab where id = '0022f7da-008b-4b8c-8fc5-4f36171cd042';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 道が_____しています。', 'でこぼこ', 'generated' from jp_vocab where id = '0022f7da-008b-4b8c-8fc5-4f36171cd042';

-- Tổng 160 câu hỏi generated cho 40 từ.
