-- ============================================================
-- jp-go — Từ vựng N2, round 16 (pilot nhóm い形容詞, trang in 53,
-- 37 từ). Nguồn: PDF "Tổng hợp kiến thức N2" (Dũng Mori), PART 2 -
-- 語彙. word_class='い形容詞'.
--
-- Trang này có câu hỏi trắc nghiệm THẬT thứ 4 (đánh dấu ＊) — chưa
-- insert, sẽ gom đủ 16 câu và khớp đáp án sau.
-- ============================================================

-- ---------- 騒々しい (そうぞうしい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('9f011189-a886-4a62-b0fe-795530919035', 'N2', NULL, 'word', '騒々しい', 'そうぞうしい', 'Ồn ào, sôi nổi', NULL, NULL, 'い形容詞', 53, '騒々しい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '騒々しい町です。', 'Đó là thị trấn ồn ào.', '_____町です。', '騒々しい', 'generated' from jp_vocab where id = '9f011189-a886-4a62-b0fe-795530919035';

-- ---------- ばかばかしい (ばかばかしい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('f2b11d53-04d8-4270-af67-644fbeb0ed7f', 'N2', NULL, 'word', 'ばかばかしい', 'ばかばかしい', 'Tào lao, nhảm nhí, vớ vẩn', NULL, NULL, 'い形容詞', 53, 'ばかばかしい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ばかばかしい話です。', 'Đó là câu chuyện nhảm nhí.', '_____話です。', 'ばかばかしい', 'generated' from jp_vocab where id = 'f2b11d53-04d8-4270-af67-644fbeb0ed7f';

-- ---------- 憎い (にくい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('abfbf2db-13c9-46d5-be76-8958150d0257', 'N2', NULL, 'word', '憎い', 'にくい', 'Căm thù, ghét', NULL, NULL, 'い形容詞', 53, '憎い', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '憎い相手です。', 'Đó là đối thủ đáng ghét.', '_____相手です。', '憎い', 'generated' from jp_vocab where id = 'abfbf2db-13c9-46d5-be76-8958150d0257';

-- ---------- 面倒くさい (めんどうくさい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('36a5f2f0-f18c-4d29-bc1e-81ef12381cca', 'N2', NULL, 'word', '面倒くさい', 'めんどうくさい', 'Phiền toái, rắc rối, khó chịu', NULL, NULL, 'い形容詞', 53, '面倒くさい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '面倒くさい仕事です。', 'Đó là công việc phiền phức.', '_____仕事です。', '面倒くさい', 'generated' from jp_vocab where id = '36a5f2f0-f18c-4d29-bc1e-81ef12381cca';

-- ---------- 煙い (けむい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('e3f53439-a0cb-45fa-9544-dfe831cf0fe8', 'N2', NULL, 'word', '煙い', 'けむい', 'Khói mù mịt', NULL, NULL, 'い形容詞', 53, '煙い', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '部屋が煙いです。', 'Căn phòng đầy khói.', '部屋が_____です。', '煙い', 'generated' from jp_vocab where id = 'e3f53439-a0cb-45fa-9544-dfe831cf0fe8';

-- ---------- 鈍い (にぶい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('86cb399e-a9e8-46d7-a98f-a112474afb9c', 'N2', NULL, 'word', '鈍い', 'にぶい', 'Cùn, đần độn, kém', NULL, NULL, 'い形容詞', 53, '鈍い', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '動きが鈍いです。', 'Động tác chậm chạp.', '動きが_____です。', '鈍い', 'generated' from jp_vocab where id = '86cb399e-a9e8-46d7-a98f-a112474afb9c';

-- ---------- 思いがけない (おもいがけない) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('1319201e-4eb6-4b64-b536-def5219015d6', 'N2', NULL, 'word', '思いがけない', 'おもいがけない', 'Không ngờ đến', NULL, NULL, 'い形容詞', 53, '思いがけない', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '思いがけない結果です。', 'Đó là kết quả không ngờ tới.', '_____結果です。', '思いがけない', 'generated' from jp_vocab where id = '1319201e-4eb6-4b64-b536-def5219015d6';

-- ---------- とんでもない (とんでもない) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('9c43be0b-6a90-4d59-bbe9-08bc2e12b52c', 'N2', NULL, 'word', 'とんでもない', 'とんでもない', 'Ngoài sức tưởng tượng/ Lố bịch, vô văn/ Không có gì đâu', NULL, NULL, 'い形容詞', 53, 'とんでもない', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'とんでもない話です。', 'Đó là chuyện ngoài sức tưởng tượng.', '_____話です。', 'とんでもない', 'generated' from jp_vocab where id = '9c43be0b-6a90-4d59-bbe9-08bc2e12b52c';

-- ---------- やむを得ない (やむをえない) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('2261a049-0948-4950-8e94-05a32c4cc412', 'N2', NULL, 'word', 'やむを得ない', 'やむをえない', 'Không tránh khỏi, bất đắc dĩ', NULL, NULL, 'い形容詞', 53, 'やむを得ない', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'やむを得ない事情です。', 'Đó là tình huống bất đắc dĩ.', '_____事情です。', 'やむを得ない', 'generated' from jp_vocab where id = '2261a049-0948-4950-8e94-05a32c4cc412';

-- ---------- 懐かしい (なつかしい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('bae16094-866e-4170-a875-34bbb3e96075', 'N2', NULL, 'word', '懐かしい', 'なつかしい', 'Nhớ, hoài niệm, thân thuộc, thân quen', NULL, NULL, 'い形容詞', 53, '懐かしい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '懐かしい写真です。', 'Đó là bức ảnh gợi nhớ kỷ niệm.', '_____写真です。', '懐かしい', 'generated' from jp_vocab where id = 'bae16094-866e-4170-a875-34bbb3e96075';

-- ---------- 幼い (おさない) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('4afd624d-50e0-4488-b362-f076b0973954', 'N2', NULL, 'word', '幼い', 'おさない', 'Non nớt, bé, ngây thơ', NULL, NULL, 'い形容詞', 53, '幼い', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '幼い子供です。', 'Đó là đứa trẻ còn nhỏ.', '_____子供です。', '幼い', 'generated' from jp_vocab where id = '4afd624d-50e0-4488-b362-f076b0973954';

-- ---------- 怪しい (あやしい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('d26d3403-5951-40c6-961e-304c7fdf6ceb', 'N2', NULL, 'word', '怪しい', 'あやしい', 'Đáng nghi ngờ, ngờ, không chắc chắn', NULL, NULL, 'い形容詞', 53, '怪しい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '怪しい人です。', 'Đó là người đáng nghi.', '_____人です。', '怪しい', 'generated' from jp_vocab where id = 'd26d3403-5951-40c6-961e-304c7fdf6ceb';

-- ---------- 等しい (ひとしい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('ea9dab88-dee9-496e-8bf8-bbf54c949281', 'N2', NULL, 'word', '等しい', 'ひとしい', 'Bằng nhau, giống nhau', NULL, NULL, 'い形容詞', 53, '等しい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '二つの数は等しいです。', 'Hai con số bằng nhau.', '二つの数は_____です。', '等しい', 'generated' from jp_vocab where id = 'ea9dab88-dee9-496e-8bf8-bbf54c949281';

-- ---------- 慌ただしい (あわただしい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('878017f5-b319-4ee1-ac2a-0abb9ee9ce36', 'N2', NULL, 'word', '慌ただしい', 'あわただしい', 'Vội vã, cuống cuồng', NULL, NULL, 'い形容詞', 53, '慌ただしい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '慌ただしい毎日です。', 'Đó là những ngày vội vã.', '_____毎日です。', '慌ただしい', 'generated' from jp_vocab where id = '878017f5-b319-4ee1-ac2a-0abb9ee9ce36';

-- ---------- ずうずうしい (ずうずうしい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('fcf2ac78-7983-4dd8-8461-46921a7e1d3c', 'N2', NULL, 'word', 'ずうずうしい', 'ずうずうしい', 'Mặt dày, vô liêm sỉ, không biết xấu hổ', NULL, NULL, 'い形容詞', 53, 'ずうずうしい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ずうずうしい態度です。', 'Đó là thái độ vô liêm sỉ.', '_____態度です。', 'ずうずうしい', 'generated' from jp_vocab where id = 'fcf2ac78-7983-4dd8-8461-46921a7e1d3c';

-- ---------- ずるい (ずるい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('ee85c24b-7e06-4d69-9096-f1388ac3ff3f', 'N2', NULL, 'word', 'ずるい', 'ずるい', 'Không trung thực, xảo quyệt; Không công bằng', NULL, NULL, 'い形容詞', 53, 'ずるい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ずるいやり方です。', 'Đó là cách làm xảo quyệt.', '_____やり方です。', 'ずるい', 'generated' from jp_vocab where id = 'ee85c24b-7e06-4d69-9096-f1388ac3ff3f';

-- ---------- しつこい (しつこい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('07aeadbc-831c-4073-a00a-2f0b74ea0beb', 'N2', NULL, 'word', 'しつこい', 'しつこい', 'Cố chấp, lằng nhằng; Đậm (vị, màu, mùi)', NULL, NULL, 'い形容詞', 53, 'しつこい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'しつこい味です。', 'Đó là vị đậm.', '_____味です。', 'しつこい', 'generated' from jp_vocab where id = '07aeadbc-831c-4073-a00a-2f0b74ea0beb';

-- ---------- きつい (きつい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('6e3f4c34-fe9c-4515-ac38-0b1d865d9d90', 'N2', NULL, 'word', 'きつい', 'きつい', 'Khó khăn, mệt, vất vả; Nghiêm khắc', NULL, NULL, 'い形容詞', 53, 'きつい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'きつい仕事です。', 'Đó là công việc vất vả.', '_____仕事です。', 'きつい', 'generated' from jp_vocab where id = '6e3f4c34-fe9c-4515-ac38-0b1d865d9d90';

-- ---------- 鋭い (するどい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('749f4b91-0a62-4f6a-bb2d-be63e6ddf607', 'N2', NULL, 'word', '鋭い', 'するどい', 'Nhọn, sắc; Sắc sảo', NULL, NULL, 'い形容詞', 53, '鋭い', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '鋭いナイフです。', 'Đó là con dao sắc bén.', '_____ナイフです。', '鋭い', 'generated' from jp_vocab where id = '749f4b91-0a62-4f6a-bb2d-be63e6ddf607';

-- ---------- 何気ない (なにげない) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('9a0315ee-3584-4813-9688-a6f113584281', 'N2', NULL, 'word', '何気ない', 'なにげない', 'Ngẫu nhiên, tình cờ, không cố ý', NULL, NULL, 'い形容詞', 53, '何気ない', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '何気ない一言です。', 'Đó là một câu nói vô tình.', '_____一言です。', '何気ない', 'generated' from jp_vocab where id = '9a0315ee-3584-4813-9688-a6f113584281';

-- ---------- くだらない (くだらない) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('0c2ad4a1-9b87-477e-b0f0-b8c77322d103', 'N2', NULL, 'word', 'くだらない', 'くだらない', 'Vô giá trị, vô nghĩa', NULL, NULL, 'い形容詞', 53, 'くだらない', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'くだらない冗談です。', 'Đó là câu đùa vô nghĩa.', '_____冗談です。', 'くだらない', 'generated' from jp_vocab where id = '0c2ad4a1-9b87-477e-b0f0-b8c77322d103';

-- ---------- 申し訳ない (もうしわけない) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('88a3bde4-3bbc-48f4-8016-9784300ca8a1', 'N2', NULL, 'word', '申し訳ない', 'もうしわけない', 'Xin lỗi', NULL, NULL, 'い形容詞', 53, '申し訳ない', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '申し訳ない気持ちです。', 'Tôi cảm thấy rất áy náy.', '_____気持ちです。', '申し訳ない', 'generated' from jp_vocab where id = '88a3bde4-3bbc-48f4-8016-9784300ca8a1';

-- ---------- 有難い (ありがたい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('8bfb9dcd-6805-412d-a740-324b47be3bf1', 'N2', NULL, 'word', '有難い', 'ありがたい', 'Cảm ơn', NULL, NULL, 'い形容詞', 53, '有難い', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '有難いお言葉です。', 'Đó là lời nói đáng trân trọng.', '_____お言葉です。', '有難い', 'generated' from jp_vocab where id = '8bfb9dcd-6805-412d-a740-324b47be3bf1';

-- ---------- 心細い (こころぼそい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('51e8ca00-6472-4e71-a7d2-16b42ffc4f0a', 'N2', NULL, 'word', '心細い', 'こころぼそい', 'Bất an', NULL, NULL, 'い形容詞', 53, '心細い', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '一人で心細いです。', 'Một mình khiến tôi bất an.', '一人で_____です。', '心細い', 'generated' from jp_vocab where id = '51e8ca00-6472-4e71-a7d2-16b42ffc4f0a';

-- ---------- 偉い (えらい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('e3e8b1f0-0d0e-4425-8026-1bb2859db3bd', 'N2', NULL, 'word', '偉い', 'えらい', 'Vĩ đại, chức cao', NULL, NULL, 'い形容詞', 53, '偉い', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '偉い人です。', 'Đó là người có chức vị cao.', '_____人です。', '偉い', 'generated' from jp_vocab where id = 'e3e8b1f0-0d0e-4425-8026-1bb2859db3bd';

-- ---------- そそっかしい (そそっかしい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('27c9cb6d-fb6c-4cbf-b4ad-d42e3f5b85c4', 'N2', NULL, 'word', 'そそっかしい', 'そそっかしい', 'Cẩu thả', NULL, NULL, 'い形容詞', 53, 'そそっかしい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'そそっかしい性格です。', 'Đó là tính cách cẩu thả.', '_____性格です。', 'そそっかしい', 'generated' from jp_vocab where id = '27c9cb6d-fb6c-4cbf-b4ad-d42e3f5b85c4';

-- ---------- 憎らしい (にくらしい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('f6662375-4cb1-4f6e-aecd-33b781a28652', 'N2', NULL, 'word', '憎らしい', 'にくらしい', 'Đáng ghét, ganh tị', NULL, NULL, 'い形容詞', 53, '憎らしい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '憎らしい態度です。', 'Đó là thái độ đáng ghét.', '_____態度です。', '憎らしい', 'generated' from jp_vocab where id = 'f6662375-4cb1-4f6e-aecd-33b781a28652';

-- ---------- 険しい (けわしい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('748612d4-7c60-483e-b995-8d2b64637791', 'N2', NULL, 'word', '険しい', 'けわしい', 'Nghiêm khắc, hung dữ; Hiểm trở', NULL, NULL, 'い形容詞', 53, '険しい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '険しい山道です。', 'Đó là con đường núi hiểm trở.', '_____山道です。', '険しい', 'generated' from jp_vocab where id = '748612d4-7c60-483e-b995-8d2b64637791';

-- ---------- くどい (くどい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('c54e5e40-c183-4781-b1d6-40486bff60f7', 'N2', NULL, 'word', 'くどい', 'くどい', 'Dài dòng, lắm lời, lòe loẹt; Đậm (vị, màu, mùi)', NULL, NULL, 'い形容詞', 53, 'くどい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'くどい説明です。', 'Đó là lời giải thích dài dòng.', '_____説明です。', 'くどい', 'generated' from jp_vocab where id = 'c54e5e40-c183-4781-b1d6-40486bff60f7';

-- ---------- 緩い (ゆるい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('df837887-feb8-4951-b613-5b2a8a2449fd', 'N2', NULL, 'word', '緩い', 'ゆるい', 'Lỏng, rộng; Thoai thoải (dốc)', NULL, NULL, 'い形容詞', 53, '緩い', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '緩いズボンです。', 'Đó là chiếc quần rộng.', '_____ズボンです。', '緩い', 'generated' from jp_vocab where id = 'df837887-feb8-4951-b613-5b2a8a2449fd';

-- ---------- 惜しい (おしい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('daff6d5b-ba0c-4a8d-9cc2-1fbdca14714b', 'N2', NULL, 'word', '惜しい', 'おしい', 'Đáng tiếc, yêu quý, quý trọng', NULL, NULL, 'い形容詞', 53, '惜しい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '惜しい結果です。', 'Đó là kết quả đáng tiếc.', '_____結果です。', '惜しい', 'generated' from jp_vocab where id = 'daff6d5b-ba0c-4a8d-9cc2-1fbdca14714b';

-- ---------- だらしない (だらしない) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('a50d4723-f790-4b67-82bb-3ce29985a03f', 'N2', NULL, 'word', 'だらしない', 'だらしない', 'Không gọn gàng, luộm thuộm; Vô kỉ luật', NULL, NULL, 'い形容詞', 53, 'だらしない', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'だらしない格好です。', 'Đó là vẻ ngoài luộm thuộm.', '_____格好です。', 'だらしない', 'generated' from jp_vocab where id = 'a50d4723-f790-4b67-82bb-3ce29985a03f';

-- ---------- 仕方(が)ない (しかたがない) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('c86a57bc-7099-48ec-bbf3-f55d0b0be220', 'N2', NULL, 'word', '仕方(が)ない', 'しかたがない', 'Vô phương, bó tay', NULL, NULL, 'い形容詞', 53, '仕方(が)ない', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '仕方がないですね。', 'Đành chịu vậy thôi.', '_____ですね。', '仕方がない', 'generated' from jp_vocab where id = 'c86a57bc-7099-48ec-bbf3-f55d0b0be220';

-- ---------- 恋しい (こいしい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('17aba917-ff9b-4c6a-861f-64bce2e58c43', 'N2', NULL, 'word', '恋しい', 'こいしい', 'Nhớ', NULL, NULL, 'い形容詞', 53, '恋しい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '故郷が恋しいです。', 'Tôi nhớ quê hương.', '故郷が_____です。', '恋しい', 'generated' from jp_vocab where id = '17aba917-ff9b-4c6a-861f-64bce2e58c43';

-- ---------- めでたい (めでたい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('d8b189ce-ff22-4865-91bb-4211296a7e38', 'N2', NULL, 'word', 'めでたい', 'めでたい', 'Đáng mừng, tốt lành', NULL, NULL, 'い形容詞', 53, 'めでたい', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'めでたい話です。', 'Đó là tin đáng mừng.', '_____話です。', 'めでたい', 'generated' from jp_vocab where id = 'd8b189ce-ff22-4865-91bb-4211296a7e38';

-- ---------- 荒い・粗い (あらい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('4e284c0f-7a1b-470f-ba41-73bbf799a82b', 'N2', NULL, 'word', '荒い・粗い', 'あらい', 'Bạo lực, khốc liệt, hung tợn; Thô, qua loa, sơ sài', NULL, NULL, 'い形容詞', 53, '荒い・粗い', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '荒い言葉です。', 'Đó là lời nói thô bạo.', '_____言葉です。', '荒い', 'generated' from jp_vocab where id = '4e284c0f-7a1b-470f-ba41-73bbf799a82b';

-- ---------- 快い (こころよい) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('8956c8e5-0a18-4208-a7b9-314f138ce473', 'N2', NULL, 'word', '快い', 'こころよい', 'Sẵn lòng, vui vẻ', NULL, NULL, 'い形容詞', 53, '快い', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '快い返事です。', 'Đó là câu trả lời vui vẻ.', '_____返事です。', '快い', 'generated' from jp_vocab where id = '8956c8e5-0a18-4208-a7b9-314f138ce473';

-- ---------- jp_vocab_questions: generated, 4 câu/từ ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"騒々しい" có nghĩa là gì?', 'Đáng ghét, ganh tị', 'Mặt dày, vô liêm sỉ, không biết xấu hổ', 'Ồn ào, sôi nổi', 'Cảm ơn', 'Ồn ào, sôi nổi', 'generated' from jp_vocab where id = '9f011189-a886-4a62-b0fe-795530919035';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Ồn ào, sôi nổi"?', '慌ただしい', '恋しい', '騒々しい', 'ばかばかしい', '騒々しい', 'generated' from jp_vocab where id = '9f011189-a886-4a62-b0fe-795530919035';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"騒々しい" đọc là gì?', 'めでたい', 'くどい', 'そうぞうしい', 'こころよい', 'そうぞうしい', 'generated' from jp_vocab where id = '9f011189-a886-4a62-b0fe-795530919035';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____町です。', '騒々しい', 'generated' from jp_vocab where id = '9f011189-a886-4a62-b0fe-795530919035';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ばかばかしい" có nghĩa là gì?', 'Dài dòng, lắm lời, lòe loẹt; Đậm (vị, màu, mùi)', 'Phiền toái, rắc rối, khó chịu', 'Không trung thực, xảo quyệt; Không công bằng', 'Tào lao, nhảm nhí, vớ vẩn', 'Tào lao, nhảm nhí, vớ vẩn', 'generated' from jp_vocab where id = 'f2b11d53-04d8-4270-af67-644fbeb0ed7f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Tào lao, nhảm nhí, vớ vẩn"?', 'ばかばかしい', '惜しい', '等しい', 'ずうずうしい', 'ばかばかしい', 'generated' from jp_vocab where id = 'f2b11d53-04d8-4270-af67-644fbeb0ed7f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ばかばかしい" đọc là gì?', 'ずうずうしい', 'そうぞうしい', 'にくらしい', 'ばかばかしい', 'ばかばかしい', 'generated' from jp_vocab where id = 'f2b11d53-04d8-4270-af67-644fbeb0ed7f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____話です。', 'ばかばかしい', 'generated' from jp_vocab where id = 'f2b11d53-04d8-4270-af67-644fbeb0ed7f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"憎い" có nghĩa là gì?', 'Cố chấp, lằng nhằng; Đậm (vị, màu, mùi)', 'Vội vã, cuống cuồng', 'Căm thù, ghét', 'Nhớ, hoài niệm, thân thuộc, thân quen', 'Căm thù, ghét', 'generated' from jp_vocab where id = 'abfbf2db-13c9-46d5-be76-8958150d0257';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Căm thù, ghét"?', 'ずうずうしい', '思いがけない', '怪しい', '憎い', '憎い', 'generated' from jp_vocab where id = 'abfbf2db-13c9-46d5-be76-8958150d0257';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"憎い" đọc là gì?', 'そうぞうしい', 'にくい', 'やむをえない', 'けわしい', 'にくい', 'generated' from jp_vocab where id = 'abfbf2db-13c9-46d5-be76-8958150d0257';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____相手です。', '憎い', 'generated' from jp_vocab where id = 'abfbf2db-13c9-46d5-be76-8958150d0257';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"面倒くさい" có nghĩa là gì?', 'Cố chấp, lằng nhằng; Đậm (vị, màu, mùi)', 'Ngẫu nhiên, tình cờ, không cố ý', 'Dài dòng, lắm lời, lòe loẹt; Đậm (vị, màu, mùi)', 'Phiền toái, rắc rối, khó chịu', 'Phiền toái, rắc rối, khó chịu', 'generated' from jp_vocab where id = '36a5f2f0-f18c-4d29-bc1e-81ef12381cca';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Phiền toái, rắc rối, khó chịu"?', '惜しい', '面倒くさい', '快い', 'やむを得ない', '面倒くさい', 'generated' from jp_vocab where id = '36a5f2f0-f18c-4d29-bc1e-81ef12381cca';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"面倒くさい" đọc là gì?', 'めんどうくさい', 'しかたがない', 'めでたい', 'ずるい', 'めんどうくさい', 'generated' from jp_vocab where id = '36a5f2f0-f18c-4d29-bc1e-81ef12381cca';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____仕事です。', '面倒くさい', 'generated' from jp_vocab where id = '36a5f2f0-f18c-4d29-bc1e-81ef12381cca';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"煙い" có nghĩa là gì?', 'Đáng ghét, ganh tị', 'Không trung thực, xảo quyệt; Không công bằng', 'Khói mù mịt', 'Cùn, đần độn, kém', 'Khói mù mịt', 'generated' from jp_vocab where id = 'e3f53439-a0cb-45fa-9544-dfe831cf0fe8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Khói mù mịt"?', '申し訳ない', 'しつこい', '煙い', 'ずうずうしい', '煙い', 'generated' from jp_vocab where id = 'e3f53439-a0cb-45fa-9544-dfe831cf0fe8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"煙い" đọc là gì?', 'くだらない', 'にくらしい', 'そそっかしい', 'けむい', 'けむい', 'generated' from jp_vocab where id = 'e3f53439-a0cb-45fa-9544-dfe831cf0fe8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 部屋が_____です。', '煙い', 'generated' from jp_vocab where id = 'e3f53439-a0cb-45fa-9544-dfe831cf0fe8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"鈍い" có nghĩa là gì?', 'Vô giá trị, vô nghĩa', 'Sẵn lòng, vui vẻ', 'Cùn, đần độn, kém', 'Ồn ào, sôi nổi', 'Cùn, đần độn, kém', 'generated' from jp_vocab where id = '86cb399e-a9e8-46d7-a98f-a112474afb9c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Cùn, đần độn, kém"?', 'そそっかしい', '恋しい', '思いがけない', '鈍い', '鈍い', 'generated' from jp_vocab where id = '86cb399e-a9e8-46d7-a98f-a112474afb9c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"鈍い" đọc là gì?', 'とんでもない', 'にぶい', 'だらしない', 'けわしい', 'にぶい', 'generated' from jp_vocab where id = '86cb399e-a9e8-46d7-a98f-a112474afb9c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 動きが_____です。', '鈍い', 'generated' from jp_vocab where id = '86cb399e-a9e8-46d7-a98f-a112474afb9c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"思いがけない" có nghĩa là gì?', 'Khói mù mịt', 'Bất an', 'Không ngờ đến', 'Phiền toái, rắc rối, khó chịu', 'Không ngờ đến', 'generated' from jp_vocab where id = '1319201e-4eb6-4b64-b536-def5219015d6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Không ngờ đến"?', 'とんでもない', 'ずうずうしい', '憎い', '思いがけない', '思いがけない', 'generated' from jp_vocab where id = '1319201e-4eb6-4b64-b536-def5219015d6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"思いがけない" đọc là gì?', 'こいしい', 'なつかしい', 'おもいがけない', 'にくい', 'おもいがけない', 'generated' from jp_vocab where id = '1319201e-4eb6-4b64-b536-def5219015d6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____結果です。', '思いがけない', 'generated' from jp_vocab where id = '1319201e-4eb6-4b64-b536-def5219015d6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"とんでもない" có nghĩa là gì?', 'Khó khăn, mệt, vất vả; Nghiêm khắc', 'Đáng mừng, tốt lành', 'Cùn, đần độn, kém', 'Ngoài sức tưởng tượng/ Lố bịch, vô văn/ Không có gì đâu', 'Ngoài sức tưởng tượng/ Lố bịch, vô văn/ Không có gì đâu', 'generated' from jp_vocab where id = '9c43be0b-6a90-4d59-bbe9-08bc2e12b52c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Ngoài sức tưởng tượng/ Lố bịch, vô văn/ Không có gì đâu"?', '偉い', '緩い', '思いがけない', 'とんでもない', 'とんでもない', 'generated' from jp_vocab where id = '9c43be0b-6a90-4d59-bbe9-08bc2e12b52c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"とんでもない" đọc là gì?', 'そうぞうしい', 'とんでもない', 'ありがたい', 'あやしい', 'とんでもない', 'generated' from jp_vocab where id = '9c43be0b-6a90-4d59-bbe9-08bc2e12b52c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____話です。', 'とんでもない', 'generated' from jp_vocab where id = '9c43be0b-6a90-4d59-bbe9-08bc2e12b52c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"やむを得ない" có nghĩa là gì?', 'Non nớt, bé, ngây thơ', 'Ngẫu nhiên, tình cờ, không cố ý', 'Phiền toái, rắc rối, khó chịu', 'Không tránh khỏi, bất đắc dĩ', 'Không tránh khỏi, bất đắc dĩ', 'generated' from jp_vocab where id = '2261a049-0948-4950-8e94-05a32c4cc412';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Không tránh khỏi, bất đắc dĩ"?', '思いがけない', '快い', '面倒くさい', 'やむを得ない', 'やむを得ない', 'generated' from jp_vocab where id = '2261a049-0948-4950-8e94-05a32c4cc412';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"やむを得ない" đọc là gì?', 'しつこい', 'ずるい', 'おさない', 'やむをえない', 'やむをえない', 'generated' from jp_vocab where id = '2261a049-0948-4950-8e94-05a32c4cc412';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____事情です。', 'やむを得ない', 'generated' from jp_vocab where id = '2261a049-0948-4950-8e94-05a32c4cc412';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"懐かしい" có nghĩa là gì?', 'Vô phương, bó tay', 'Không trung thực, xảo quyệt; Không công bằng', 'Bất an', 'Nhớ, hoài niệm, thân thuộc, thân quen', 'Nhớ, hoài niệm, thân thuộc, thân quen', 'generated' from jp_vocab where id = 'bae16094-866e-4170-a875-34bbb3e96075';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Nhớ, hoài niệm, thân thuộc, thân quen"?', 'しつこい', '懐かしい', '心細い', '申し訳ない', '懐かしい', 'generated' from jp_vocab where id = 'bae16094-866e-4170-a875-34bbb3e96075';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"懐かしい" đọc là gì?', 'こころぼそい', 'なにげない', 'なつかしい', 'あらい', 'なつかしい', 'generated' from jp_vocab where id = 'bae16094-866e-4170-a875-34bbb3e96075';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____写真です。', '懐かしい', 'generated' from jp_vocab where id = 'bae16094-866e-4170-a875-34bbb3e96075';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"幼い" có nghĩa là gì?', 'Dài dòng, lắm lời, lòe loẹt; Đậm (vị, màu, mùi)', 'Không trung thực, xảo quyệt; Không công bằng', 'Non nớt, bé, ngây thơ', 'Tào lao, nhảm nhí, vớ vẩn', 'Non nớt, bé, ngây thơ', 'generated' from jp_vocab where id = '4afd624d-50e0-4488-b362-f076b0973954';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Non nớt, bé, ngây thơ"?', '幼い', 'ばかばかしい', 'くだらない', '怪しい', '幼い', 'generated' from jp_vocab where id = '4afd624d-50e0-4488-b362-f076b0973954';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"幼い" đọc là gì?', 'ありがたい', 'おさない', 'ゆるい', 'あわただしい', 'おさない', 'generated' from jp_vocab where id = '4afd624d-50e0-4488-b362-f076b0973954';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____子供です。', '幼い', 'generated' from jp_vocab where id = '4afd624d-50e0-4488-b362-f076b0973954';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"怪しい" có nghĩa là gì?', 'Ngẫu nhiên, tình cờ, không cố ý', 'Không trung thực, xảo quyệt; Không công bằng', 'Non nớt, bé, ngây thơ', 'Đáng nghi ngờ, ngờ, không chắc chắn', 'Đáng nghi ngờ, ngờ, không chắc chắn', 'generated' from jp_vocab where id = 'd26d3403-5951-40c6-961e-304c7fdf6ceb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Đáng nghi ngờ, ngờ, không chắc chắn"?', '面倒くさい', 'きつい', '怪しい', '憎い', '怪しい', 'generated' from jp_vocab where id = 'd26d3403-5951-40c6-961e-304c7fdf6ceb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"怪しい" đọc là gì?', 'やむをえない', 'くだらない', 'にくらしい', 'あやしい', 'あやしい', 'generated' from jp_vocab where id = 'd26d3403-5951-40c6-961e-304c7fdf6ceb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____人です。', '怪しい', 'generated' from jp_vocab where id = 'd26d3403-5951-40c6-961e-304c7fdf6ceb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"等しい" có nghĩa là gì?', 'Nhớ, hoài niệm, thân thuộc, thân quen', 'Bất an', 'Bằng nhau, giống nhau', 'Khói mù mịt', 'Bằng nhau, giống nhau', 'generated' from jp_vocab where id = 'ea9dab88-dee9-496e-8bf8-bbf54c949281';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Bằng nhau, giống nhau"?', 'だらしない', '騒々しい', '険しい', '等しい', '等しい', 'generated' from jp_vocab where id = 'ea9dab88-dee9-496e-8bf8-bbf54c949281';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"等しい" đọc là gì?', 'おもいがけない', 'ひとしい', 'ずうずうしい', 'あわただしい', 'ひとしい', 'generated' from jp_vocab where id = 'ea9dab88-dee9-496e-8bf8-bbf54c949281';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 二つの数は_____です。', '等しい', 'generated' from jp_vocab where id = 'ea9dab88-dee9-496e-8bf8-bbf54c949281';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"慌ただしい" có nghĩa là gì?', 'Vội vã, cuống cuồng', 'Đáng ghét, ganh tị', 'Vĩ đại, chức cao', 'Cảm ơn', 'Vội vã, cuống cuồng', 'generated' from jp_vocab where id = '878017f5-b319-4ee1-ac2a-0abb9ee9ce36';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Vội vã, cuống cuồng"?', '慌ただしい', '面倒くさい', '鈍い', '等しい', '慌ただしい', 'generated' from jp_vocab where id = '878017f5-b319-4ee1-ac2a-0abb9ee9ce36';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"慌ただしい" đọc là gì?', 'しかたがない', 'きつい', 'もうしわけない', 'あわただしい', 'あわただしい', 'generated' from jp_vocab where id = '878017f5-b319-4ee1-ac2a-0abb9ee9ce36';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____毎日です。', '慌ただしい', 'generated' from jp_vocab where id = '878017f5-b319-4ee1-ac2a-0abb9ee9ce36';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ずうずうしい" có nghĩa là gì?', 'Không gọn gàng, luộm thuộm; Vô kỉ luật', 'Đáng mừng, tốt lành', 'Mặt dày, vô liêm sỉ, không biết xấu hổ', 'Cẩu thả', 'Mặt dày, vô liêm sỉ, không biết xấu hổ', 'generated' from jp_vocab where id = 'fcf2ac78-7983-4dd8-8461-46921a7e1d3c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Mặt dày, vô liêm sỉ, không biết xấu hổ"?', '鈍い', '鋭い', '面倒くさい', 'ずうずうしい', 'ずうずうしい', 'generated' from jp_vocab where id = 'fcf2ac78-7983-4dd8-8461-46921a7e1d3c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ずうずうしい" đọc là gì?', 'けわしい', 'あらい', 'ずうずうしい', 'するどい', 'ずうずうしい', 'generated' from jp_vocab where id = 'fcf2ac78-7983-4dd8-8461-46921a7e1d3c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____態度です。', 'ずうずうしい', 'generated' from jp_vocab where id = 'fcf2ac78-7983-4dd8-8461-46921a7e1d3c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ずるい" có nghĩa là gì?', 'Vô phương, bó tay', 'Bằng nhau, giống nhau', 'Không trung thực, xảo quyệt; Không công bằng', 'Nghiêm khắc, hung dữ; Hiểm trở', 'Không trung thực, xảo quyệt; Không công bằng', 'generated' from jp_vocab where id = 'ee85c24b-7e06-4d69-9096-f1388ac3ff3f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Không trung thực, xảo quyệt; Không công bằng"?', '恋しい', '思いがけない', 'だらしない', 'ずるい', 'ずるい', 'generated' from jp_vocab where id = 'ee85c24b-7e06-4d69-9096-f1388ac3ff3f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ずるい" đọc là gì?', 'おさない', 'ずるい', 'なにげない', 'めんどうくさい', 'ずるい', 'generated' from jp_vocab where id = 'ee85c24b-7e06-4d69-9096-f1388ac3ff3f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____やり方です。', 'ずるい', 'generated' from jp_vocab where id = 'ee85c24b-7e06-4d69-9096-f1388ac3ff3f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"しつこい" có nghĩa là gì?', 'Nhọn, sắc; Sắc sảo', 'Đáng nghi ngờ, ngờ, không chắc chắn', 'Tào lao, nhảm nhí, vớ vẩn', 'Cố chấp, lằng nhằng; Đậm (vị, màu, mùi)', 'Cố chấp, lằng nhằng; Đậm (vị, màu, mùi)', 'generated' from jp_vocab where id = '07aeadbc-831c-4073-a00a-2f0b74ea0beb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Cố chấp, lằng nhằng; Đậm (vị, màu, mùi)"?', '憎い', 'しつこい', '何気ない', '仕方(が)ない', 'しつこい', 'generated' from jp_vocab where id = '07aeadbc-831c-4073-a00a-2f0b74ea0beb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"しつこい" đọc là gì?', 'あやしい', 'しつこい', 'ばかばかしい', 'にぶい', 'しつこい', 'generated' from jp_vocab where id = '07aeadbc-831c-4073-a00a-2f0b74ea0beb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____味です。', 'しつこい', 'generated' from jp_vocab where id = '07aeadbc-831c-4073-a00a-2f0b74ea0beb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"きつい" có nghĩa là gì?', 'Vội vã, cuống cuồng', 'Phiền toái, rắc rối, khó chịu', 'Vô giá trị, vô nghĩa', 'Khó khăn, mệt, vất vả; Nghiêm khắc', 'Khó khăn, mệt, vất vả; Nghiêm khắc', 'generated' from jp_vocab where id = '6e3f4c34-fe9c-4515-ac38-0b1d865d9d90';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Khó khăn, mệt, vất vả; Nghiêm khắc"?', 'きつい', '怪しい', '憎い', '険しい', 'きつい', 'generated' from jp_vocab where id = '6e3f4c34-fe9c-4515-ac38-0b1d865d9d90';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"きつい" đọc là gì?', 'きつい', 'めんどうくさい', 'そそっかしい', 'こころぼそい', 'きつい', 'generated' from jp_vocab where id = '6e3f4c34-fe9c-4515-ac38-0b1d865d9d90';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____仕事です。', 'きつい', 'generated' from jp_vocab where id = '6e3f4c34-fe9c-4515-ac38-0b1d865d9d90';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"鋭い" có nghĩa là gì?', 'Nhọn, sắc; Sắc sảo', 'Đáng nghi ngờ, ngờ, không chắc chắn', 'Không ngờ đến', 'Cẩu thả', 'Nhọn, sắc; Sắc sảo', 'generated' from jp_vocab where id = '749f4b91-0a62-4f6a-bb2d-be63e6ddf607';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Nhọn, sắc; Sắc sảo"?', '思いがけない', 'とんでもない', '何気ない', '鋭い', '鋭い', 'generated' from jp_vocab where id = '749f4b91-0a62-4f6a-bb2d-be63e6ddf607';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"鋭い" đọc là gì?', 'するどい', 'こころぼそい', 'そそっかしい', 'やむをえない', 'するどい', 'generated' from jp_vocab where id = '749f4b91-0a62-4f6a-bb2d-be63e6ddf607';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____ナイフです。', '鋭い', 'generated' from jp_vocab where id = '749f4b91-0a62-4f6a-bb2d-be63e6ddf607';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"何気ない" có nghĩa là gì?', 'Ngẫu nhiên, tình cờ, không cố ý', 'Cùn, đần độn, kém', 'Đáng nghi ngờ, ngờ, không chắc chắn', 'Vội vã, cuống cuồng', 'Ngẫu nhiên, tình cờ, không cố ý', 'generated' from jp_vocab where id = '9a0315ee-3584-4813-9688-a6f113584281';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Ngẫu nhiên, tình cờ, không cố ý"?', '何気ない', 'ずうずうしい', '鈍い', '険しい', '何気ない', 'generated' from jp_vocab where id = '9a0315ee-3584-4813-9688-a6f113584281';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"何気ない" đọc là gì?', 'しつこい', 'だらしない', 'えらい', 'なにげない', 'なにげない', 'generated' from jp_vocab where id = '9a0315ee-3584-4813-9688-a6f113584281';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____一言です。', '何気ない', 'generated' from jp_vocab where id = '9a0315ee-3584-4813-9688-a6f113584281';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"くだらない" có nghĩa là gì?', 'Cẩu thả', 'Ồn ào, sôi nổi', 'Nhọn, sắc; Sắc sảo', 'Vô giá trị, vô nghĩa', 'Vô giá trị, vô nghĩa', 'generated' from jp_vocab where id = '0c2ad4a1-9b87-477e-b0f0-b8c77322d103';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Vô giá trị, vô nghĩa"?', 'くだらない', 'やむを得ない', '心細い', '快い', 'くだらない', 'generated' from jp_vocab where id = '0c2ad4a1-9b87-477e-b0f0-b8c77322d103';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"くだらない" đọc là gì?', 'おさない', 'くだらない', 'こころよい', 'ゆるい', 'くだらない', 'generated' from jp_vocab where id = '0c2ad4a1-9b87-477e-b0f0-b8c77322d103';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____冗談です。', 'くだらない', 'generated' from jp_vocab where id = '0c2ad4a1-9b87-477e-b0f0-b8c77322d103';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"申し訳ない" có nghĩa là gì?', 'Căm thù, ghét', 'Cùn, đần độn, kém', 'Xin lỗi', 'Non nớt, bé, ngây thơ', 'Xin lỗi', 'generated' from jp_vocab where id = '88a3bde4-3bbc-48f4-8016-9784300ca8a1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Xin lỗi"?', 'ずるい', '快い', '申し訳ない', '荒い・粗い', '申し訳ない', 'generated' from jp_vocab where id = '88a3bde4-3bbc-48f4-8016-9784300ca8a1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"申し訳ない" đọc là gì?', 'けわしい', 'もうしわけない', 'にくい', 'めんどうくさい', 'もうしわけない', 'generated' from jp_vocab where id = '88a3bde4-3bbc-48f4-8016-9784300ca8a1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____気持ちです。', '申し訳ない', 'generated' from jp_vocab where id = '88a3bde4-3bbc-48f4-8016-9784300ca8a1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"有難い" có nghĩa là gì?', 'Cùn, đần độn, kém', 'Cẩu thả', 'Mặt dày, vô liêm sỉ, không biết xấu hổ', 'Cảm ơn', 'Cảm ơn', 'generated' from jp_vocab where id = '8bfb9dcd-6805-412d-a740-324b47be3bf1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Cảm ơn"?', '煙い', 'めでたい', '有難い', '憎い', '有難い', 'generated' from jp_vocab where id = '8bfb9dcd-6805-412d-a740-324b47be3bf1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"有難い" đọc là gì?', 'ありがたい', 'こころぼそい', 'あわただしい', 'そうぞうしい', 'ありがたい', 'generated' from jp_vocab where id = '8bfb9dcd-6805-412d-a740-324b47be3bf1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____お言葉です。', '有難い', 'generated' from jp_vocab where id = '8bfb9dcd-6805-412d-a740-324b47be3bf1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"心細い" có nghĩa là gì?', 'Bất an', 'Vội vã, cuống cuồng', 'Mặt dày, vô liêm sỉ, không biết xấu hổ', 'Bằng nhau, giống nhau', 'Bất an', 'generated' from jp_vocab where id = '51e8ca00-6472-4e71-a7d2-16b42ffc4f0a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Bất an"?', '心細い', 'ばかばかしい', 'めでたい', '何気ない', '心細い', 'generated' from jp_vocab where id = '51e8ca00-6472-4e71-a7d2-16b42ffc4f0a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"心細い" đọc là gì?', 'こころぼそい', 'めでたい', 'こいしい', 'するどい', 'こころぼそい', 'generated' from jp_vocab where id = '51e8ca00-6472-4e71-a7d2-16b42ffc4f0a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 一人で_____です。', '心細い', 'generated' from jp_vocab where id = '51e8ca00-6472-4e71-a7d2-16b42ffc4f0a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"偉い" có nghĩa là gì?', 'Nhọn, sắc; Sắc sảo', 'Vĩ đại, chức cao', 'Lỏng, rộng; Thoai thoải (dốc)', 'Khói mù mịt', 'Vĩ đại, chức cao', 'generated' from jp_vocab where id = 'e3e8b1f0-0d0e-4425-8026-1bb2859db3bd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Vĩ đại, chức cao"?', '心細い', '恋しい', '偉い', '鈍い', '偉い', 'generated' from jp_vocab where id = 'e3e8b1f0-0d0e-4425-8026-1bb2859db3bd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"偉い" đọc là gì?', 'しかたがない', 'えらい', 'にくらしい', 'もうしわけない', 'えらい', 'generated' from jp_vocab where id = 'e3e8b1f0-0d0e-4425-8026-1bb2859db3bd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____人です。', '偉い', 'generated' from jp_vocab where id = 'e3e8b1f0-0d0e-4425-8026-1bb2859db3bd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"そそっかしい" có nghĩa là gì?', 'Đáng ghét, ganh tị', 'Vô giá trị, vô nghĩa', 'Xin lỗi', 'Cẩu thả', 'Cẩu thả', 'generated' from jp_vocab where id = '27c9cb6d-fb6c-4cbf-b4ad-d42e3f5b85c4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Cẩu thả"?', 'そそっかしい', '憎い', 'しつこい', 'ずるい', 'そそっかしい', 'generated' from jp_vocab where id = '27c9cb6d-fb6c-4cbf-b4ad-d42e3f5b85c4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"そそっかしい" đọc là gì?', 'おさない', 'にくい', 'にぶい', 'そそっかしい', 'そそっかしい', 'generated' from jp_vocab where id = '27c9cb6d-fb6c-4cbf-b4ad-d42e3f5b85c4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____性格です。', 'そそっかしい', 'generated' from jp_vocab where id = '27c9cb6d-fb6c-4cbf-b4ad-d42e3f5b85c4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"憎らしい" có nghĩa là gì?', 'Vô phương, bó tay', 'Non nớt, bé, ngây thơ', 'Đáng ghét, ganh tị', 'Lỏng, rộng; Thoai thoải (dốc)', 'Đáng ghét, ganh tị', 'generated' from jp_vocab where id = 'f6662375-4cb1-4f6e-aecd-33b781a28652';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Đáng ghét, ganh tị"?', '幼い', '煙い', '有難い', '憎らしい', '憎らしい', 'generated' from jp_vocab where id = 'f6662375-4cb1-4f6e-aecd-33b781a28652';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"憎らしい" đọc là gì?', 'にくらしい', 'けわしい', 'しかたがない', 'あらい', 'にくらしい', 'generated' from jp_vocab where id = 'f6662375-4cb1-4f6e-aecd-33b781a28652';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____態度です。', '憎らしい', 'generated' from jp_vocab where id = 'f6662375-4cb1-4f6e-aecd-33b781a28652';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"険しい" có nghĩa là gì?', 'Cùn, đần độn, kém', 'Nghiêm khắc, hung dữ; Hiểm trở', 'Khó khăn, mệt, vất vả; Nghiêm khắc', 'Nhọn, sắc; Sắc sảo', 'Nghiêm khắc, hung dữ; Hiểm trở', 'generated' from jp_vocab where id = '748612d4-7c60-483e-b995-8d2b64637791';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Nghiêm khắc, hung dữ; Hiểm trở"?', '険しい', '懐かしい', 'やむを得ない', '等しい', '険しい', 'generated' from jp_vocab where id = '748612d4-7c60-483e-b995-8d2b64637791';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"険しい" đọc là gì?', 'こころよい', 'けわしい', 'ずうずうしい', 'けむい', 'けわしい', 'generated' from jp_vocab where id = '748612d4-7c60-483e-b995-8d2b64637791';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____山道です。', '険しい', 'generated' from jp_vocab where id = '748612d4-7c60-483e-b995-8d2b64637791';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"くどい" có nghĩa là gì?', 'Khó khăn, mệt, vất vả; Nghiêm khắc', 'Vô giá trị, vô nghĩa', 'Dài dòng, lắm lời, lòe loẹt; Đậm (vị, màu, mùi)', 'Khói mù mịt', 'Dài dòng, lắm lời, lòe loẹt; Đậm (vị, màu, mùi)', 'generated' from jp_vocab where id = 'c54e5e40-c183-4781-b1d6-40486bff60f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Dài dòng, lắm lời, lòe loẹt; Đậm (vị, màu, mùi)"?', '心細い', 'ずるい', 'くだらない', 'くどい', 'くどい', 'generated' from jp_vocab where id = 'c54e5e40-c183-4781-b1d6-40486bff60f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"くどい" đọc là gì?', 'おもいがけない', 'あらい', 'にぶい', 'くどい', 'くどい', 'generated' from jp_vocab where id = 'c54e5e40-c183-4781-b1d6-40486bff60f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____説明です。', 'くどい', 'generated' from jp_vocab where id = 'c54e5e40-c183-4781-b1d6-40486bff60f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"緩い" có nghĩa là gì?', 'Không ngờ đến', 'Vội vã, cuống cuồng', 'Lỏng, rộng; Thoai thoải (dốc)', 'Ngẫu nhiên, tình cờ, không cố ý', 'Lỏng, rộng; Thoai thoải (dốc)', 'generated' from jp_vocab where id = 'df837887-feb8-4951-b613-5b2a8a2449fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Lỏng, rộng; Thoai thoải (dốc)"?', '何気ない', 'めでたい', 'ばかばかしい', '緩い', '緩い', 'generated' from jp_vocab where id = 'df837887-feb8-4951-b613-5b2a8a2449fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"緩い" đọc là gì?', 'あわただしい', 'くだらない', 'ゆるい', 'めんどうくさい', 'ゆるい', 'generated' from jp_vocab where id = 'df837887-feb8-4951-b613-5b2a8a2449fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____ズボンです。', '緩い', 'generated' from jp_vocab where id = 'df837887-feb8-4951-b613-5b2a8a2449fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"惜しい" có nghĩa là gì?', 'Không tránh khỏi, bất đắc dĩ', 'Không gọn gàng, luộm thuộm; Vô kỉ luật', 'Đáng tiếc, yêu quý, quý trọng', 'Phiền toái, rắc rối, khó chịu', 'Đáng tiếc, yêu quý, quý trọng', 'generated' from jp_vocab where id = 'daff6d5b-ba0c-4a8d-9cc2-1fbdca14714b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Đáng tiếc, yêu quý, quý trọng"?', 'とんでもない', 'しつこい', '惜しい', '幼い', '惜しい', 'generated' from jp_vocab where id = 'daff6d5b-ba0c-4a8d-9cc2-1fbdca14714b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"惜しい" đọc là gì?', 'けわしい', 'ばかばかしい', 'おしい', 'めでたい', 'おしい', 'generated' from jp_vocab where id = 'daff6d5b-ba0c-4a8d-9cc2-1fbdca14714b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____結果です。', '惜しい', 'generated' from jp_vocab where id = 'daff6d5b-ba0c-4a8d-9cc2-1fbdca14714b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"だらしない" có nghĩa là gì?', 'Không ngờ đến', 'Nhớ, hoài niệm, thân thuộc, thân quen', 'Đáng mừng, tốt lành', 'Không gọn gàng, luộm thuộm; Vô kỉ luật', 'Không gọn gàng, luộm thuộm; Vô kỉ luật', 'generated' from jp_vocab where id = 'a50d4723-f790-4b67-82bb-3ce29985a03f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Không gọn gàng, luộm thuộm; Vô kỉ luật"?', 'だらしない', '思いがけない', '憎い', 'ずうずうしい', 'だらしない', 'generated' from jp_vocab where id = 'a50d4723-f790-4b67-82bb-3ce29985a03f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"だらしない" đọc là gì?', 'そそっかしい', 'だらしない', 'ずるい', 'ありがたい', 'だらしない', 'generated' from jp_vocab where id = 'a50d4723-f790-4b67-82bb-3ce29985a03f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____格好です。', 'だらしない', 'generated' from jp_vocab where id = 'a50d4723-f790-4b67-82bb-3ce29985a03f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"仕方(が)ない" có nghĩa là gì?', 'Ngẫu nhiên, tình cờ, không cố ý', 'Cùn, đần độn, kém', 'Vội vã, cuống cuồng', 'Vô phương, bó tay', 'Vô phương, bó tay', 'generated' from jp_vocab where id = 'c86a57bc-7099-48ec-bbf3-f55d0b0be220';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Vô phương, bó tay"?', 'ずるい', '緩い', '仕方(が)ない', 'とんでもない', '仕方(が)ない', 'generated' from jp_vocab where id = 'c86a57bc-7099-48ec-bbf3-f55d0b0be220';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"仕方(が)ない" đọc là gì?', 'おさない', 'けむい', 'めでたい', 'しかたがない', 'しかたがない', 'generated' from jp_vocab where id = 'c86a57bc-7099-48ec-bbf3-f55d0b0be220';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____ですね。', '仕方がない', 'generated' from jp_vocab where id = 'c86a57bc-7099-48ec-bbf3-f55d0b0be220';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"恋しい" có nghĩa là gì?', 'Nhớ', 'Mặt dày, vô liêm sỉ, không biết xấu hổ', 'Ngẫu nhiên, tình cờ, không cố ý', 'Cẩu thả', 'Nhớ', 'generated' from jp_vocab where id = '17aba917-ff9b-4c6a-861f-64bce2e58c43';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Nhớ"?', 'くだらない', '恋しい', '憎い', 'ばかばかしい', '恋しい', 'generated' from jp_vocab where id = '17aba917-ff9b-4c6a-861f-64bce2e58c43';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"恋しい" đọc là gì?', 'おもいがけない', 'なにげない', 'あわただしい', 'こいしい', 'こいしい', 'generated' from jp_vocab where id = '17aba917-ff9b-4c6a-861f-64bce2e58c43';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 故郷が_____です。', '恋しい', 'generated' from jp_vocab where id = '17aba917-ff9b-4c6a-861f-64bce2e58c43';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"めでたい" có nghĩa là gì?', 'Cùn, đần độn, kém', 'Ngoài sức tưởng tượng/ Lố bịch, vô văn/ Không có gì đâu', 'Đáng mừng, tốt lành', 'Nhớ', 'Đáng mừng, tốt lành', 'generated' from jp_vocab where id = 'd8b189ce-ff22-4865-91bb-4211296a7e38';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Đáng mừng, tốt lành"?', 'しつこい', '快い', 'ずるい', 'めでたい', 'めでたい', 'generated' from jp_vocab where id = 'd8b189ce-ff22-4865-91bb-4211296a7e38';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"めでたい" đọc là gì?', 'めでたい', 'おさない', 'けむい', 'おしい', 'めでたい', 'generated' from jp_vocab where id = 'd8b189ce-ff22-4865-91bb-4211296a7e38';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____話です。', 'めでたい', 'generated' from jp_vocab where id = 'd8b189ce-ff22-4865-91bb-4211296a7e38';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"荒い・粗い" có nghĩa là gì?', 'Bằng nhau, giống nhau', 'Đáng mừng, tốt lành', 'Vĩ đại, chức cao', 'Bạo lực, khốc liệt, hung tợn; Thô, qua loa, sơ sài', 'Bạo lực, khốc liệt, hung tợn; Thô, qua loa, sơ sài', 'generated' from jp_vocab where id = '4e284c0f-7a1b-470f-ba41-73bbf799a82b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Bạo lực, khốc liệt, hung tợn; Thô, qua loa, sơ sài"?', '憎らしい', '懐かしい', '仕方(が)ない', '荒い・粗い', '荒い・粗い', 'generated' from jp_vocab where id = '4e284c0f-7a1b-470f-ba41-73bbf799a82b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"荒い・粗い" đọc là gì?', 'あらい', 'おもいがけない', 'しつこい', 'くだらない', 'あらい', 'generated' from jp_vocab where id = '4e284c0f-7a1b-470f-ba41-73bbf799a82b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____言葉です。', '荒い', 'generated' from jp_vocab where id = '4e284c0f-7a1b-470f-ba41-73bbf799a82b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"快い" có nghĩa là gì?', 'Sẵn lòng, vui vẻ', 'Xin lỗi', 'Không tránh khỏi, bất đắc dĩ', 'Cùn, đần độn, kém', 'Sẵn lòng, vui vẻ', 'generated' from jp_vocab where id = '8956c8e5-0a18-4208-a7b9-314f138ce473';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sẵn lòng, vui vẻ"?', '快い', '懐かしい', '憎らしい', '有難い', '快い', 'generated' from jp_vocab where id = '8956c8e5-0a18-4208-a7b9-314f138ce473';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"快い" đọc là gì?', 'ばかばかしい', 'こころよい', 'おさない', 'ゆるい', 'こころよい', 'generated' from jp_vocab where id = '8956c8e5-0a18-4208-a7b9-314f138ce473';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____返事です。', '快い', 'generated' from jp_vocab where id = '8956c8e5-0a18-4208-a7b9-314f138ce473';

-- Tổng 148 câu hỏi generated cho 37 từ.
