-- ============================================================
-- jp-go — Từ vựng N2, round 21 (pilot nhóm 複合動詞, nhóm ～出す,
-- trang in 57, 12 từ). Nguồn: PDF "Tổng hợp kiến thức N2" (Dũng
-- Mori), PART 2 - 語彙. word_class='複合動詞'.
-- ============================================================

-- ---------- 聞き出す (ききだす) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('f3a10b2d-cc4d-4e9d-a70a-9cfb83272a62', 'N2', NULL, 'word', '聞き出す', 'ききだす', 'Chất vấn, hỏi ra', NULL, NULL, '複合動詞', 57, '聞き出す', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '秘密を聞き出しました。', 'Tôi đã hỏi ra được bí mật.', '秘密を_____ました。', '聞き出し', 'generated' from jp_vocab where id = 'f3a10b2d-cc4d-4e9d-a70a-9cfb83272a62';

-- ---------- 連れ出す (つれだす) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('a123cfbc-18d8-4667-884c-95c06748d903', 'N2', NULL, 'word', '連れ出す', 'つれだす', 'Dẫn ra ngoài', NULL, NULL, '複合動詞', 57, '連れ出す', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '子供を連れ出します。', 'Tôi dẫn con ra ngoài.', '子供を_____ます。', '連れ出し', 'generated' from jp_vocab where id = 'a123cfbc-18d8-4667-884c-95c06748d903';

-- ---------- 投げ出す (なげだす) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('36aec999-96f1-4920-83be-0dbd1939703d', 'N2', NULL, 'word', '投げ出す', 'なげだす', 'Ném đi, từ bỏ, ngồi gác chéo chân', NULL, NULL, '複合動詞', 57, '投げ出す', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '仕事を投げ出しました。', 'Tôi đã bỏ dở công việc.', '仕事を_____ました。', '投げ出し', 'generated' from jp_vocab where id = '36aec999-96f1-4920-83be-0dbd1939703d';

-- ---------- 放り出す (ほうりだす) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('b94d5d2c-5582-48a1-a762-9de7c1d50a54', 'N2', NULL, 'word', '放り出す', 'ほうりだす', 'Buông bỏ, quẳng ra', NULL, NULL, '複合動詞', 57, '放り出す', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '荷物を放り出しました。', 'Tôi đã quẳng hành lý ra.', '荷物を_____ました。', '放り出し', 'generated' from jp_vocab where id = 'b94d5d2c-5582-48a1-a762-9de7c1d50a54';

-- ---------- 持ち出す (もちだす) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('22e20cc1-d261-4070-8b04-a858f0311317', 'N2', NULL, 'word', '持ち出す', 'もちだす', 'Mang ra ngoài; Mang một vấn đề, chủ đề ra nói', NULL, NULL, '複合動詞', 57, '持ち出す', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '問題を持ち出しました。', 'Anh ấy đã nêu ra vấn đề.', '問題を_____ました。', '持ち出し', 'generated' from jp_vocab where id = '22e20cc1-d261-4070-8b04-a858f0311317';

-- ---------- 追い出す (おいだす) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('18392aa7-6cde-40aa-b2f8-b7a92aa664c0', 'N2', NULL, 'word', '追い出す', 'おいだす', 'Đuổi cổ, đuổi đi', NULL, NULL, '複合動詞', 57, '追い出す', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '猫を追い出しました。', 'Tôi đã đuổi con mèo đi.', '猫を_____ました。', '追い出し', 'generated' from jp_vocab where id = '18392aa7-6cde-40aa-b2f8-b7a92aa664c0';

-- ---------- 引っ張り出す (ひっぱりだす) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('49113cda-0485-48c6-b86c-938b0b3f1c92', 'N2', NULL, 'word', '引っ張り出す', 'ひっぱりだす', 'Lôi ra, bới móc ra', NULL, NULL, '複合動詞', 57, '引っ張り出す', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '箱から引っ張り出しました。', 'Tôi đã lôi nó ra từ trong hộp.', '箱から_____ました。', '引っ張り出し', 'generated' from jp_vocab where id = '49113cda-0485-48c6-b86c-938b0b3f1c92';

-- ---------- 見つけ出す (みつけだす) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('bef9834a-fa50-4997-a9e0-cb412ef93d2f', 'N2', NULL, 'word', '見つけ出す', 'みつけだす', 'Tìm ra, tìm thấy', NULL, NULL, '複合動詞', 57, '見つけ出す', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '解決策を見つけ出しました。', 'Tôi đã tìm ra giải pháp.', '解決策を_____ました。', '見つけ出し', 'generated' from jp_vocab where id = 'bef9834a-fa50-4997-a9e0-cb412ef93d2f';

-- ---------- 探し出す (さがしだす) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('d0939d56-1f47-4d3d-a067-747a7adbfbc7', 'N2', NULL, 'word', '探し出す', 'さがしだす', 'Tìm thấy được', NULL, NULL, '複合動詞', 57, '探し出す', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '犯人を探し出しました。', 'Tôi đã tìm ra được thủ phạm.', '犯人を_____ました。', '探し出し', 'generated' from jp_vocab where id = 'd0939d56-1f47-4d3d-a067-747a7adbfbc7';

-- ---------- 書き出す (かきだす) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('3fd41f3c-35df-40b4-9382-8affe310c024', 'N2', NULL, 'word', '書き出す', 'かきだす', 'Viết ra', NULL, NULL, '複合動詞', 57, '書き出す', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '要点を書き出します。', 'Tôi viết ra các điểm chính.', '要点を_____ます。', '書き出し', 'generated' from jp_vocab where id = '3fd41f3c-35df-40b4-9382-8affe310c024';

-- ---------- 貸し出す (かしだす) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('f38154e7-db10-4895-ac7a-576f5423c9fd', 'N2', NULL, 'word', '貸し出す', 'かしだす', 'Cho mượn', NULL, NULL, '複合動詞', 57, '貸し出す', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '本を貸し出します。', 'Tôi cho mượn sách.', '本を_____ます。', '貸し出し', 'generated' from jp_vocab where id = 'f38154e7-db10-4895-ac7a-576f5423c9fd';

-- ---------- 逃げ出す (にげだす) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('d221776f-508f-4704-a91f-eb9b2aacc06a', 'N2', NULL, 'word', '逃げ出す', 'にげだす', 'Bỏ trốn, chạy trốn', NULL, NULL, '複合動詞', 57, '逃げ出す', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '家から逃げ出しました。', 'Anh ta đã bỏ trốn khỏi nhà.', '家から_____ました。', '逃げ出し', 'generated' from jp_vocab where id = 'd221776f-508f-4704-a91f-eb9b2aacc06a';

-- ---------- jp_vocab_questions: generated, 4 câu/từ ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"聞き出す" có nghĩa là gì?', 'Buông bỏ, quẳng ra', 'Viết ra', 'Chất vấn, hỏi ra', 'Đuổi cổ, đuổi đi', 'Chất vấn, hỏi ra', 'generated' from jp_vocab where id = 'f3a10b2d-cc4d-4e9d-a70a-9cfb83272a62';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Chất vấn, hỏi ra"?', '連れ出す', '聞き出す', '引っ張り出す', '投げ出す', '聞き出す', 'generated' from jp_vocab where id = 'f3a10b2d-cc4d-4e9d-a70a-9cfb83272a62';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"聞き出す" đọc là gì?', 'ひっぱりだす', 'ききだす', 'ほうりだす', 'かしだす', 'ききだす', 'generated' from jp_vocab where id = 'f3a10b2d-cc4d-4e9d-a70a-9cfb83272a62';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 秘密を_____ました。', '聞き出し', 'generated' from jp_vocab where id = 'f3a10b2d-cc4d-4e9d-a70a-9cfb83272a62';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"連れ出す" có nghĩa là gì?', 'Ném đi, từ bỏ, ngồi gác chéo chân', 'Lôi ra, bới móc ra', 'Dẫn ra ngoài', 'Cho mượn', 'Dẫn ra ngoài', 'generated' from jp_vocab where id = 'a123cfbc-18d8-4667-884c-95c06748d903';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Dẫn ra ngoài"?', '連れ出す', '引っ張り出す', '探し出す', '投げ出す', '連れ出す', 'generated' from jp_vocab where id = 'a123cfbc-18d8-4667-884c-95c06748d903';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"連れ出す" đọc là gì?', 'つれだす', 'ひっぱりだす', 'もちだす', 'にげだす', 'つれだす', 'generated' from jp_vocab where id = 'a123cfbc-18d8-4667-884c-95c06748d903';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 子供を_____ます。', '連れ出し', 'generated' from jp_vocab where id = 'a123cfbc-18d8-4667-884c-95c06748d903';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"投げ出す" có nghĩa là gì?', 'Cho mượn', 'Ném đi, từ bỏ, ngồi gác chéo chân', 'Chất vấn, hỏi ra', 'Mang ra ngoài; Mang một vấn đề, chủ đề ra nói', 'Ném đi, từ bỏ, ngồi gác chéo chân', 'generated' from jp_vocab where id = '36aec999-96f1-4920-83be-0dbd1939703d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Ném đi, từ bỏ, ngồi gác chéo chân"?', '貸し出す', '投げ出す', '逃げ出す', '引っ張り出す', '投げ出す', 'generated' from jp_vocab where id = '36aec999-96f1-4920-83be-0dbd1939703d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"投げ出す" đọc là gì?', 'さがしだす', 'かしだす', 'なげだす', 'みつけだす', 'なげだす', 'generated' from jp_vocab where id = '36aec999-96f1-4920-83be-0dbd1939703d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 仕事を_____ました。', '投げ出し', 'generated' from jp_vocab where id = '36aec999-96f1-4920-83be-0dbd1939703d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"放り出す" có nghĩa là gì?', 'Mang ra ngoài; Mang một vấn đề, chủ đề ra nói', 'Cho mượn', 'Bỏ trốn, chạy trốn', 'Buông bỏ, quẳng ra', 'Buông bỏ, quẳng ra', 'generated' from jp_vocab where id = 'b94d5d2c-5582-48a1-a762-9de7c1d50a54';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Buông bỏ, quẳng ra"?', '放り出す', '探し出す', '貸し出す', '見つけ出す', '放り出す', 'generated' from jp_vocab where id = 'b94d5d2c-5582-48a1-a762-9de7c1d50a54';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"放り出す" đọc là gì?', 'つれだす', 'ひっぱりだす', 'かしだす', 'ほうりだす', 'ほうりだす', 'generated' from jp_vocab where id = 'b94d5d2c-5582-48a1-a762-9de7c1d50a54';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 荷物を_____ました。', '放り出し', 'generated' from jp_vocab where id = 'b94d5d2c-5582-48a1-a762-9de7c1d50a54';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"持ち出す" có nghĩa là gì?', 'Dẫn ra ngoài', 'Lôi ra, bới móc ra', 'Mang ra ngoài; Mang một vấn đề, chủ đề ra nói', 'Đuổi cổ, đuổi đi', 'Mang ra ngoài; Mang một vấn đề, chủ đề ra nói', 'generated' from jp_vocab where id = '22e20cc1-d261-4070-8b04-a858f0311317';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Mang ra ngoài; Mang một vấn đề, chủ đề ra nói"?', '追い出す', '持ち出す', '聞き出す', '見つけ出す', '持ち出す', 'generated' from jp_vocab where id = '22e20cc1-d261-4070-8b04-a858f0311317';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"持ち出す" đọc là gì?', 'さがしだす', 'ひっぱりだす', 'もちだす', 'ききだす', 'もちだす', 'generated' from jp_vocab where id = '22e20cc1-d261-4070-8b04-a858f0311317';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 問題を_____ました。', '持ち出し', 'generated' from jp_vocab where id = '22e20cc1-d261-4070-8b04-a858f0311317';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"追い出す" có nghĩa là gì?', 'Cho mượn', 'Bỏ trốn, chạy trốn', 'Viết ra', 'Đuổi cổ, đuổi đi', 'Đuổi cổ, đuổi đi', 'generated' from jp_vocab where id = '18392aa7-6cde-40aa-b2f8-b7a92aa664c0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Đuổi cổ, đuổi đi"?', '逃げ出す', '連れ出す', '引っ張り出す', '追い出す', '追い出す', 'generated' from jp_vocab where id = '18392aa7-6cde-40aa-b2f8-b7a92aa664c0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"追い出す" đọc là gì?', 'もちだす', 'おいだす', 'ききだす', 'かしだす', 'おいだす', 'generated' from jp_vocab where id = '18392aa7-6cde-40aa-b2f8-b7a92aa664c0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 猫を_____ました。', '追い出し', 'generated' from jp_vocab where id = '18392aa7-6cde-40aa-b2f8-b7a92aa664c0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"引っ張り出す" có nghĩa là gì?', 'Lôi ra, bới móc ra', 'Tìm thấy được', 'Cho mượn', 'Ném đi, từ bỏ, ngồi gác chéo chân', 'Lôi ra, bới móc ra', 'generated' from jp_vocab where id = '49113cda-0485-48c6-b86c-938b0b3f1c92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Lôi ra, bới móc ra"?', '引っ張り出す', '持ち出す', '逃げ出す', '貸し出す', '引っ張り出す', 'generated' from jp_vocab where id = '49113cda-0485-48c6-b86c-938b0b3f1c92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"引っ張り出す" đọc là gì?', 'つれだす', 'さがしだす', 'ひっぱりだす', 'ききだす', 'ひっぱりだす', 'generated' from jp_vocab where id = '49113cda-0485-48c6-b86c-938b0b3f1c92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 箱から_____ました。', '引っ張り出し', 'generated' from jp_vocab where id = '49113cda-0485-48c6-b86c-938b0b3f1c92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"見つけ出す" có nghĩa là gì?', 'Tìm ra, tìm thấy', 'Viết ra', 'Buông bỏ, quẳng ra', 'Chất vấn, hỏi ra', 'Tìm ra, tìm thấy', 'generated' from jp_vocab where id = 'bef9834a-fa50-4997-a9e0-cb412ef93d2f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Tìm ra, tìm thấy"?', '見つけ出す', '逃げ出す', '放り出す', '引っ張り出す', '見つけ出す', 'generated' from jp_vocab where id = 'bef9834a-fa50-4997-a9e0-cb412ef93d2f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"見つけ出す" đọc là gì?', 'みつけだす', 'もちだす', 'かしだす', 'にげだす', 'みつけだす', 'generated' from jp_vocab where id = 'bef9834a-fa50-4997-a9e0-cb412ef93d2f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 解決策を_____ました。', '見つけ出し', 'generated' from jp_vocab where id = 'bef9834a-fa50-4997-a9e0-cb412ef93d2f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"探し出す" có nghĩa là gì?', 'Viết ra', 'Bỏ trốn, chạy trốn', 'Dẫn ra ngoài', 'Tìm thấy được', 'Tìm thấy được', 'generated' from jp_vocab where id = 'd0939d56-1f47-4d3d-a067-747a7adbfbc7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Tìm thấy được"?', '見つけ出す', '探し出す', '放り出す', '書き出す', '探し出す', 'generated' from jp_vocab where id = 'd0939d56-1f47-4d3d-a067-747a7adbfbc7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"探し出す" đọc là gì?', 'つれだす', 'さがしだす', 'ほうりだす', 'ひっぱりだす', 'さがしだす', 'generated' from jp_vocab where id = 'd0939d56-1f47-4d3d-a067-747a7adbfbc7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 犯人を_____ました。', '探し出し', 'generated' from jp_vocab where id = 'd0939d56-1f47-4d3d-a067-747a7adbfbc7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"書き出す" có nghĩa là gì?', 'Viết ra', 'Buông bỏ, quẳng ra', 'Mang ra ngoài; Mang một vấn đề, chủ đề ra nói', 'Bỏ trốn, chạy trốn', 'Viết ra', 'generated' from jp_vocab where id = '3fd41f3c-35df-40b4-9382-8affe310c024';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Viết ra"?', '引っ張り出す', '書き出す', '追い出す', '貸し出す', '書き出す', 'generated' from jp_vocab where id = '3fd41f3c-35df-40b4-9382-8affe310c024';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"書き出す" đọc là gì?', 'なげだす', 'さがしだす', 'ほうりだす', 'かきだす', 'かきだす', 'generated' from jp_vocab where id = '3fd41f3c-35df-40b4-9382-8affe310c024';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 要点を_____ます。', '書き出し', 'generated' from jp_vocab where id = '3fd41f3c-35df-40b4-9382-8affe310c024';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"貸し出す" có nghĩa là gì?', 'Mang ra ngoài; Mang một vấn đề, chủ đề ra nói', 'Viết ra', 'Bỏ trốn, chạy trốn', 'Cho mượn', 'Cho mượn', 'generated' from jp_vocab where id = 'f38154e7-db10-4895-ac7a-576f5423c9fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Cho mượn"?', '貸し出す', '放り出す', '探し出す', '追い出す', '貸し出す', 'generated' from jp_vocab where id = 'f38154e7-db10-4895-ac7a-576f5423c9fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"貸し出す" đọc là gì?', 'かきだす', 'つれだす', 'さがしだす', 'かしだす', 'かしだす', 'generated' from jp_vocab where id = 'f38154e7-db10-4895-ac7a-576f5423c9fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 本を_____ます。', '貸し出し', 'generated' from jp_vocab where id = 'f38154e7-db10-4895-ac7a-576f5423c9fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"逃げ出す" có nghĩa là gì?', 'Bỏ trốn, chạy trốn', 'Chất vấn, hỏi ra', 'Mang ra ngoài; Mang một vấn đề, chủ đề ra nói', 'Tìm ra, tìm thấy', 'Bỏ trốn, chạy trốn', 'generated' from jp_vocab where id = 'd221776f-508f-4704-a91f-eb9b2aacc06a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Bỏ trốn, chạy trốn"?', '逃げ出す', '追い出す', '投げ出す', '連れ出す', '逃げ出す', 'generated' from jp_vocab where id = 'd221776f-508f-4704-a91f-eb9b2aacc06a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"逃げ出す" đọc là gì?', 'ききだす', 'にげだす', 'なげだす', 'みつけだす', 'にげだす', 'generated' from jp_vocab where id = 'd221776f-508f-4704-a91f-eb9b2aacc06a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 家から_____ました。', '逃げ出し', 'generated' from jp_vocab where id = 'd221776f-508f-4704-a91f-eb9b2aacc06a';

-- Tổng 48 câu hỏi generated cho 12 từ.
