-- ============================================================
-- jp-go — Từ vựng N2, round 22 (nhóm 複合動詞 ～込む, trang in 57-58,
-- 26 từ). Nguồn: PDF "Tổng hợp kiến thức N2" (Dũng Mori), PART 2 -
-- 語彙. word_class='複合動詞'.
-- ============================================================

-- ---------- 飛び込む (とびこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('f2de90b3-3b37-4fa9-a4f8-4a91fa7084d4', 'N2', NULL, 'word', '飛び込む', 'とびこむ', 'Nhảy vào, lao vào', NULL, NULL, '複合動詞', 57, '飛び込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'プールに飛び込みます。', 'Tôi nhảy xuống hồ bơi.', 'プールに_____ます。', '飛び込み', 'generated' from jp_vocab where id = 'f2de90b3-3b37-4fa9-a4f8-4a91fa7084d4';

-- ---------- 駆け込む (かけこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('bc3fa3b3-f1cf-4d5a-8db3-d0535432f676', 'N2', NULL, 'word', '駆け込む', 'かけこむ', 'Chạy lao vào', NULL, NULL, '複合動詞', 57, '駆け込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '電車に駆け込みました。', 'Tôi đã chạy lao vào tàu điện.', '電車に_____ました。', '駆け込み', 'generated' from jp_vocab where id = 'bc3fa3b3-f1cf-4d5a-8db3-d0535432f676';

-- ---------- 詰め込む (つめこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('ef31aae6-2f28-4258-92d4-db7b87f9a40a', 'N2', NULL, 'word', '詰め込む', 'つめこむ', 'Nhét vào, nhồi nhét', NULL, NULL, '複合動詞', 57, '詰め込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'かばんに詰め込みます。', 'Tôi nhồi nhét vào cặp.', 'かばんに_____ます。', '詰め込み', 'generated' from jp_vocab where id = 'ef31aae6-2f28-4258-92d4-db7b87f9a40a';

-- ---------- 飲み込む (のみこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('ee142f2e-2c33-48a9-b29b-2c7550975c16', 'N2', NULL, 'word', '飲み込む', 'のみこむ', 'Hiểu, thành thục; Nuốt vào', NULL, NULL, '複合動詞', 57, '飲み込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'コツを飲み込みました。', 'Tôi đã nắm được bí quyết.', 'コツを_____ました。', '飲み込み', 'generated' from jp_vocab where id = 'ee142f2e-2c33-48a9-b29b-2c7550975c16';

-- ---------- 書き込む (かきこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('1437cfdb-ed21-4b3c-830b-7d2c397098ad', 'N2', NULL, 'word', '書き込む', 'かきこむ', 'Viết vào, nhập vào', NULL, NULL, '複合動詞', 57, '書き込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '名前を書き込みます。', 'Tôi điền tên vào.', '名前を_____ます。', '書き込み', 'generated' from jp_vocab where id = '1437cfdb-ed21-4b3c-830b-7d2c397098ad';

-- ---------- 巻き込む (まきこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('6cd97b7b-d268-4e86-82c7-9197548467a4', 'N2', NULL, 'word', '巻き込む', 'まきこむ', 'Cuộn vào; Dính líu', NULL, NULL, '複合動詞', 57, '巻き込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '事件に巻き込まれました。', 'Tôi đã bị cuốn vào vụ việc.', '事件に_____まれました。', '巻き込', 'generated' from jp_vocab where id = '6cd97b7b-d268-4e86-82c7-9197548467a4';

-- ---------- 呼び込む (よびこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('cb3c76d9-cf9b-482c-83a4-03962b8e4785', 'N2', NULL, 'word', '呼び込む', 'よびこむ', 'Mời gọi, lôi kéo, thu hút', NULL, NULL, '複合動詞', 57, '呼び込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お客を呼び込みます。', 'Tôi thu hút khách hàng.', 'お客を_____ます。', '呼び込み', 'generated' from jp_vocab where id = 'cb3c76d9-cf9b-482c-83a4-03962b8e4785';

-- ---------- 座り込む (すわりこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('3ce71dda-e207-45f8-ad0d-3efbbec5454e', 'N2', NULL, 'word', '座り込む', 'すわりこむ', 'Ngồi bệt xuống', NULL, NULL, '複合動詞', 57, '座り込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '床に座り込みました。', 'Tôi đã ngồi bệt xuống sàn.', '床に_____ました。', '座り込み', 'generated' from jp_vocab where id = '3ce71dda-e207-45f8-ad0d-3efbbec5454e';

-- ---------- 寝込む (ねこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('7533961a-f949-4bb4-88d9-b16c284055ab', 'N2', NULL, 'word', '寝込む', 'ねこむ', 'Ngủ say, ngủ li bì, nằm liệt giường', NULL, NULL, '複合動詞', 57, '寝込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '風邪で寝込みました。', 'Tôi đã nằm liệt giường vì cảm.', '風邪で_____ました。', '寝込み', 'generated' from jp_vocab where id = '7533961a-f949-4bb4-88d9-b16c284055ab';

-- ---------- 泊まり込む (とまりこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('fa7167c2-7aba-4dcb-817f-68abc3539657', 'N2', NULL, 'word', '泊まり込む', 'とまりこむ', 'Trọ lại, ở lại', NULL, NULL, '複合動詞', 57, '泊まり込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '会社に泊まり込みます。', 'Tôi ở lại qua đêm tại công ty.', '会社に_____ます。', '泊まり込み', 'generated' from jp_vocab where id = 'fa7167c2-7aba-4dcb-817f-68abc3539657';

-- ---------- 住み込む (すみこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('a10bd339-2fc8-43d8-9542-20554f2ce3cf', 'N2', NULL, 'word', '住み込む', 'すみこむ', 'Chuyển vào sống', NULL, NULL, '複合動詞', 57, '住み込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '住み込みで働きます。', 'Tôi làm việc và ở luôn tại chỗ.', '_____で働きます。', '住み込み', 'generated' from jp_vocab where id = 'a10bd339-2fc8-43d8-9542-20554f2ce3cf';

-- ---------- 割り込む (わりこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('4e88ca03-0b8e-4406-986f-ae4ea5bb9f4f', 'N2', NULL, 'word', '割り込む', 'わりこむ', 'Chen vào, xen ngang', NULL, NULL, '複合動詞', 57, '割り込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '列に割り込みました。', 'Anh ta đã chen vào hàng.', '列に_____ました。', '割り込み', 'generated' from jp_vocab where id = '4e88ca03-0b8e-4406-986f-ae4ea5bb9f4f';

-- ---------- 差し込む (さしこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('c74542fd-a145-4596-904d-ea6e0f0eb11d', 'N2', NULL, 'word', '差し込む', 'さしこむ', '(Ánh sáng) chiếu vào; Cắm vào', NULL, NULL, '複合動詞', 57, '差し込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '光が差し込みます。', 'Ánh sáng chiếu vào.', '光が_____ます。', '差し込み', 'generated' from jp_vocab where id = 'c74542fd-a145-4596-904d-ea6e0f0eb11d';

-- ---------- 染み込む (しみこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('5442929b-ce78-406f-9955-00e95683def9', 'N2', NULL, 'word', '染み込む', 'しみこむ', 'Thấm, ngấm', NULL, NULL, '複合動詞', 57, '染み込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '水が染み込みました。', 'Nước đã thấm vào.', '水が_____ました。', '染み込み', 'generated' from jp_vocab where id = '5442929b-ce78-406f-9955-00e95683def9';

-- ---------- 引っ込む (ひっこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('7929ac99-4894-45f5-b8dd-fb5e987f39cd', 'N2', NULL, 'word', '引っ込む', 'ひっこむ', 'Co lại, lùi về', NULL, NULL, '複合動詞', 57, '引っ込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '部屋に引っ込みました。', 'Tôi lui về phòng.', '部屋に_____ました。', '引っ込み', 'generated' from jp_vocab where id = '7929ac99-4894-45f5-b8dd-fb5e987f39cd';

-- ---------- 引き込む (ひきこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('15924f96-0bb4-45a9-9a4e-9637425c8b4c', 'N2', NULL, 'word', '引き込む', 'ひきこむ', 'Lôi kéo, dẫn vào', NULL, NULL, '複合動詞', 58, '引き込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '話に引き込まれました。', 'Tôi bị cuốn vào câu chuyện.', '話に_____まれました。', '引き込', 'generated' from jp_vocab where id = '15924f96-0bb4-45a9-9a4e-9637425c8b4c';

-- ---------- 運び込む (はこびこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('1a909633-1878-4602-b213-d2d130acc325', 'N2', NULL, 'word', '運び込む', 'はこびこむ', 'Mang vào, đem vào', NULL, NULL, '複合動詞', 58, '運び込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '荷物を運び込みます。', 'Tôi mang hành lý vào.', '荷物を_____ます。', '運び込み', 'generated' from jp_vocab where id = '1a909633-1878-4602-b213-d2d130acc325';

-- ---------- 注ぎ込む (そそぎこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('3a939e2d-9c07-4c3c-82bf-b3ce93a62673', 'N2', NULL, 'word', '注ぎ込む', 'そそぎこむ', 'Đổ vào trong', NULL, NULL, '複合動詞', 58, '注ぎ込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '資金を注ぎ込みます。', 'Tôi đổ vốn vào.', '資金を_____ます。', '注ぎ込み', 'generated' from jp_vocab where id = '3a939e2d-9c07-4c3c-82bf-b3ce93a62673';

-- ---------- 追い込む (おいこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('9583aab5-da76-4790-b7ca-f1f865092bde', 'N2', NULL, 'word', '追い込む', 'おいこむ', 'Lùa vào, dồn vào', NULL, NULL, '複合動詞', 58, '追い込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '窮地に追い込まれました。', 'Tôi bị dồn vào thế bí.', '窮地に_____まれました。', '追い込', 'generated' from jp_vocab where id = '9583aab5-da76-4790-b7ca-f1f865092bde';

-- ---------- 話し込む (はなしこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('feb038f9-879e-4b30-840c-d7ceb5315526', 'N2', NULL, 'word', '話し込む', 'はなしこむ', 'Say sưa nói chuyện', NULL, NULL, '複合動詞', 58, '話し込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '友達と話し込みました。', 'Tôi đã say sưa nói chuyện với bạn.', '友達と_____ました。', '話し込み', 'generated' from jp_vocab where id = 'feb038f9-879e-4b30-840c-d7ceb5315526';

-- ---------- 黙り込む (だまりこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('8eeda157-99a4-48be-a71c-ede03e627dfa', 'N2', NULL, 'word', '黙り込む', 'だまりこむ', 'Giữ im lặng', NULL, NULL, '複合動詞', 58, '黙り込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彼は黙り込みました。', 'Anh ấy đã im lặng.', '彼は_____ました。', '黙り込み', 'generated' from jp_vocab where id = '8eeda157-99a4-48be-a71c-ede03e627dfa';

-- ---------- 打ち込む (うちこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('664ac970-6b4d-4db3-b9cf-6323a7946087', 'N2', NULL, 'word', '打ち込む', 'うちこむ', 'Nhập vào, gõ; Cống hiến hết mình vì; Tập trung, đắm chìm', NULL, NULL, '複合動詞', 58, '打ち込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '仕事に打ち込みます。', 'Tôi cống hiến hết mình cho công việc.', '仕事に_____ます。', '打ち込み', 'generated' from jp_vocab where id = '664ac970-6b4d-4db3-b9cf-6323a7946087';

-- ---------- 煮込む (にこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('4bb746f7-6b58-453a-af4d-b4bf92104a46', 'N2', NULL, 'word', '煮込む', 'にこむ', 'Nấu, ninh', NULL, NULL, '複合動詞', 58, '煮込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'スープを煮込みます。', 'Tôi ninh súp.', 'スープを_____ます。', '煮込み', 'generated' from jp_vocab where id = '4bb746f7-6b58-453a-af4d-b4bf92104a46';

-- ---------- 売り込む (うりこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('dafdb15a-f591-4f86-adee-9a0e5c309936', 'N2', NULL, 'word', '売り込む', 'うりこむ', 'Tiếp thị, mời gọi', NULL, NULL, '複合動詞', 58, '売り込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '商品を売り込みます。', 'Tôi tiếp thị sản phẩm.', '商品を_____ます。', '売り込み', 'generated' from jp_vocab where id = 'dafdb15a-f591-4f86-adee-9a0e5c309936';

-- ---------- 頼み込む (たのみこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('1d30983b-9529-4652-9aa6-cd476bd03960', 'N2', NULL, 'word', '頼み込む', 'たのみこむ', 'Nhờ vả, khẩn khoản xin', NULL, NULL, '複合動詞', 58, '頼み込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '頼み込んで許可をもらいました。', 'Tôi đã khẩn khoản xin và được cho phép.', '_____で許可をもらいました。', '頼み込ん', 'generated' from jp_vocab where id = '1d30983b-9529-4652-9aa6-cd476bd03960';

-- ---------- 教え込む (おしえこむ) ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('d9231371-fb38-4173-94d3-265a2d96bc87', 'N2', NULL, 'word', '教え込む', 'おしえこむ', 'Dạy, huấn luyện', NULL, NULL, '複合動詞', 58, '教え込む', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '子供に教え込みます。', 'Tôi dạy dỗ con cái.', '子供に_____ます。', '教え込み', 'generated' from jp_vocab where id = 'd9231371-fb38-4173-94d3-265a2d96bc87';

-- ---------- jp_vocab_questions: generated, 4 câu/từ ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"飛び込む" có nghĩa là gì?', 'Đổ vào trong', 'Say sưa nói chuyện', 'Ngủ say, ngủ li bì, nằm liệt giường', 'Nhảy vào, lao vào', 'Nhảy vào, lao vào', 'generated' from jp_vocab where id = 'f2de90b3-3b37-4fa9-a4f8-4a91fa7084d4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Nhảy vào, lao vào"?', '染み込む', '打ち込む', '飛び込む', '詰め込む', '飛び込む', 'generated' from jp_vocab where id = 'f2de90b3-3b37-4fa9-a4f8-4a91fa7084d4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"飛び込む" đọc là gì?', 'はこびこむ', 'とびこむ', 'うりこむ', 'ねこむ', 'とびこむ', 'generated' from jp_vocab where id = 'f2de90b3-3b37-4fa9-a4f8-4a91fa7084d4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: プールに_____ます。', '飛び込み', 'generated' from jp_vocab where id = 'f2de90b3-3b37-4fa9-a4f8-4a91fa7084d4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"駆け込む" có nghĩa là gì?', 'Đổ vào trong', 'Tiếp thị, mời gọi', 'Trọ lại, ở lại', 'Chạy lao vào', 'Chạy lao vào', 'generated' from jp_vocab where id = 'bc3fa3b3-f1cf-4d5a-8db3-d0535432f676';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Chạy lao vào"?', '巻き込む', '染み込む', '駆け込む', '教え込む', '駆け込む', 'generated' from jp_vocab where id = 'bc3fa3b3-f1cf-4d5a-8db3-d0535432f676';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"駆け込む" đọc là gì?', 'ねこむ', 'だまりこむ', 'かけこむ', 'おしえこむ', 'かけこむ', 'generated' from jp_vocab where id = 'bc3fa3b3-f1cf-4d5a-8db3-d0535432f676';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 電車に_____ました。', '駆け込み', 'generated' from jp_vocab where id = 'bc3fa3b3-f1cf-4d5a-8db3-d0535432f676';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"詰め込む" có nghĩa là gì?', 'Dạy, huấn luyện', 'Mang vào, đem vào', 'Ngồi bệt xuống', 'Nhét vào, nhồi nhét', 'Nhét vào, nhồi nhét', 'generated' from jp_vocab where id = 'ef31aae6-2f28-4258-92d4-db7b87f9a40a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Nhét vào, nhồi nhét"?', '詰め込む', '書き込む', '引き込む', '教え込む', '詰め込む', 'generated' from jp_vocab where id = 'ef31aae6-2f28-4258-92d4-db7b87f9a40a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"詰め込む" đọc là gì?', 'すみこむ', 'よびこむ', 'おいこむ', 'つめこむ', 'つめこむ', 'generated' from jp_vocab where id = 'ef31aae6-2f28-4258-92d4-db7b87f9a40a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: かばんに_____ます。', '詰め込み', 'generated' from jp_vocab where id = 'ef31aae6-2f28-4258-92d4-db7b87f9a40a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"飲み込む" có nghĩa là gì?', 'Say sưa nói chuyện', 'Lùa vào, dồn vào', 'Cuộn vào; Dính líu', 'Hiểu, thành thục; Nuốt vào', 'Hiểu, thành thục; Nuốt vào', 'generated' from jp_vocab where id = 'ee142f2e-2c33-48a9-b29b-2c7550975c16';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Hiểu, thành thục; Nuốt vào"?', '引き込む', '飲み込む', '詰め込む', '話し込む', '飲み込む', 'generated' from jp_vocab where id = 'ee142f2e-2c33-48a9-b29b-2c7550975c16';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"飲み込む" đọc là gì?', 'まきこむ', 'うりこむ', 'のみこむ', 'ひきこむ', 'のみこむ', 'generated' from jp_vocab where id = 'ee142f2e-2c33-48a9-b29b-2c7550975c16';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: コツを_____ました。', '飲み込み', 'generated' from jp_vocab where id = 'ee142f2e-2c33-48a9-b29b-2c7550975c16';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"書き込む" có nghĩa là gì?', 'Thấm, ngấm', 'Co lại, lùi về', 'Viết vào, nhập vào', 'Nhảy vào, lao vào', 'Viết vào, nhập vào', 'generated' from jp_vocab where id = '1437cfdb-ed21-4b3c-830b-7d2c397098ad';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Viết vào, nhập vào"?', '引っ込む', '書き込む', '泊まり込む', '巻き込む', '書き込む', 'generated' from jp_vocab where id = '1437cfdb-ed21-4b3c-830b-7d2c397098ad';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"書き込む" đọc là gì?', 'かきこむ', 'よびこむ', 'しみこむ', 'はこびこむ', 'かきこむ', 'generated' from jp_vocab where id = '1437cfdb-ed21-4b3c-830b-7d2c397098ad';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 名前を_____ます。', '書き込み', 'generated' from jp_vocab where id = '1437cfdb-ed21-4b3c-830b-7d2c397098ad';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"巻き込む" có nghĩa là gì?', 'Ngủ say, ngủ li bì, nằm liệt giường', 'Mời gọi, lôi kéo, thu hút', 'Tiếp thị, mời gọi', 'Cuộn vào; Dính líu', 'Cuộn vào; Dính líu', 'generated' from jp_vocab where id = '6cd97b7b-d268-4e86-82c7-9197548467a4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Cuộn vào; Dính líu"?', '話し込む', '巻き込む', '書き込む', '運び込む', '巻き込む', 'generated' from jp_vocab where id = '6cd97b7b-d268-4e86-82c7-9197548467a4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"巻き込む" đọc là gì?', 'だまりこむ', 'まきこむ', 'にこむ', 'ひっこむ', 'まきこむ', 'generated' from jp_vocab where id = '6cd97b7b-d268-4e86-82c7-9197548467a4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 事件に_____まれました。', '巻き込', 'generated' from jp_vocab where id = '6cd97b7b-d268-4e86-82c7-9197548467a4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"呼び込む" có nghĩa là gì?', 'Nhét vào, nhồi nhét', 'Hiểu, thành thục; Nuốt vào', 'Chuyển vào sống', 'Mời gọi, lôi kéo, thu hút', 'Mời gọi, lôi kéo, thu hút', 'generated' from jp_vocab where id = 'cb3c76d9-cf9b-482c-83a4-03962b8e4785';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Mời gọi, lôi kéo, thu hút"?', '教え込む', '呼び込む', '引き込む', '話し込む', '呼び込む', 'generated' from jp_vocab where id = 'cb3c76d9-cf9b-482c-83a4-03962b8e4785';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"呼び込む" đọc là gì?', 'うちこむ', 'よびこむ', 'おしえこむ', 'だまりこむ', 'よびこむ', 'generated' from jp_vocab where id = 'cb3c76d9-cf9b-482c-83a4-03962b8e4785';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: お客を_____ます。', '呼び込み', 'generated' from jp_vocab where id = 'cb3c76d9-cf9b-482c-83a4-03962b8e4785';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"座り込む" có nghĩa là gì?', 'Tiếp thị, mời gọi', 'Chạy lao vào', 'Ngồi bệt xuống', 'Nhập vào, gõ; Cống hiến hết mình vì; Tập trung, đắm chìm', 'Ngồi bệt xuống', 'generated' from jp_vocab where id = '3ce71dda-e207-45f8-ad0d-3efbbec5454e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Ngồi bệt xuống"?', '煮込む', '詰め込む', '黙り込む', '座り込む', '座り込む', 'generated' from jp_vocab where id = '3ce71dda-e207-45f8-ad0d-3efbbec5454e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"座り込む" đọc là gì?', 'とびこむ', 'とまりこむ', 'うりこむ', 'すわりこむ', 'すわりこむ', 'generated' from jp_vocab where id = '3ce71dda-e207-45f8-ad0d-3efbbec5454e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 床に_____ました。', '座り込み', 'generated' from jp_vocab where id = '3ce71dda-e207-45f8-ad0d-3efbbec5454e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"寝込む" có nghĩa là gì?', 'Ngồi bệt xuống', 'Ngủ say, ngủ li bì, nằm liệt giường', 'Nhảy vào, lao vào', 'Lôi kéo, dẫn vào', 'Ngủ say, ngủ li bì, nằm liệt giường', 'generated' from jp_vocab where id = '7533961a-f949-4bb4-88d9-b16c284055ab';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Ngủ say, ngủ li bì, nằm liệt giường"?', '話し込む', '寝込む', '染み込む', '座り込む', '寝込む', 'generated' from jp_vocab where id = '7533961a-f949-4bb4-88d9-b16c284055ab';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"寝込む" đọc là gì?', 'ねこむ', 'にこむ', 'とびこむ', 'だまりこむ', 'ねこむ', 'generated' from jp_vocab where id = '7533961a-f949-4bb4-88d9-b16c284055ab';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 風邪で_____ました。', '寝込み', 'generated' from jp_vocab where id = '7533961a-f949-4bb4-88d9-b16c284055ab';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"泊まり込む" có nghĩa là gì?', 'Hiểu, thành thục; Nuốt vào', 'Co lại, lùi về', 'Trọ lại, ở lại', 'Chạy lao vào', 'Trọ lại, ở lại', 'generated' from jp_vocab where id = 'fa7167c2-7aba-4dcb-817f-68abc3539657';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Trọ lại, ở lại"?', '寝込む', '飛び込む', '割り込む', '泊まり込む', '泊まり込む', 'generated' from jp_vocab where id = 'fa7167c2-7aba-4dcb-817f-68abc3539657';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"泊まり込む" đọc là gì?', 'とびこむ', 'おしえこむ', 'よびこむ', 'とまりこむ', 'とまりこむ', 'generated' from jp_vocab where id = 'fa7167c2-7aba-4dcb-817f-68abc3539657';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 会社に_____ます。', '泊まり込み', 'generated' from jp_vocab where id = 'fa7167c2-7aba-4dcb-817f-68abc3539657';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"住み込む" có nghĩa là gì?', 'Nhập vào, gõ; Cống hiến hết mình vì; Tập trung, đắm chìm', 'Dạy, huấn luyện', 'Nhảy vào, lao vào', 'Chuyển vào sống', 'Chuyển vào sống', 'generated' from jp_vocab where id = 'a10bd339-2fc8-43d8-9542-20554f2ce3cf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Chuyển vào sống"?', '追い込む', '差し込む', '駆け込む', '住み込む', '住み込む', 'generated' from jp_vocab where id = 'a10bd339-2fc8-43d8-9542-20554f2ce3cf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"住み込む" đọc là gì?', 'はこびこむ', 'まきこむ', 'すみこむ', 'かけこむ', 'すみこむ', 'generated' from jp_vocab where id = 'a10bd339-2fc8-43d8-9542-20554f2ce3cf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で働きます。', '住み込み', 'generated' from jp_vocab where id = 'a10bd339-2fc8-43d8-9542-20554f2ce3cf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"割り込む" có nghĩa là gì?', 'Nhảy vào, lao vào', 'Thấm, ngấm', 'Giữ im lặng', 'Chen vào, xen ngang', 'Chen vào, xen ngang', 'generated' from jp_vocab where id = '4e88ca03-0b8e-4406-986f-ae4ea5bb9f4f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Chen vào, xen ngang"?', '割り込む', '飲み込む', '頼み込む', '駆け込む', '割り込む', 'generated' from jp_vocab where id = '4e88ca03-0b8e-4406-986f-ae4ea5bb9f4f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"割り込む" đọc là gì?', 'とまりこむ', 'わりこむ', 'にこむ', 'すみこむ', 'わりこむ', 'generated' from jp_vocab where id = '4e88ca03-0b8e-4406-986f-ae4ea5bb9f4f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 列に_____ました。', '割り込み', 'generated' from jp_vocab where id = '4e88ca03-0b8e-4406-986f-ae4ea5bb9f4f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"差し込む" có nghĩa là gì?', 'Trọ lại, ở lại', 'Nấu, ninh', '(Ánh sáng) chiếu vào; Cắm vào', 'Tiếp thị, mời gọi', '(Ánh sáng) chiếu vào; Cắm vào', 'generated' from jp_vocab where id = 'c74542fd-a145-4596-904d-ea6e0f0eb11d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "(Ánh sáng) chiếu vào; Cắm vào"?', '住み込む', '黙り込む', '差し込む', '注ぎ込む', '差し込む', 'generated' from jp_vocab where id = 'c74542fd-a145-4596-904d-ea6e0f0eb11d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"差し込む" đọc là gì?', 'さしこむ', 'のみこむ', 'わりこむ', 'とびこむ', 'さしこむ', 'generated' from jp_vocab where id = 'c74542fd-a145-4596-904d-ea6e0f0eb11d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 光が_____ます。', '差し込み', 'generated' from jp_vocab where id = 'c74542fd-a145-4596-904d-ea6e0f0eb11d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"染み込む" có nghĩa là gì?', 'Ngồi bệt xuống', 'Thấm, ngấm', 'Lùa vào, dồn vào', 'Tiếp thị, mời gọi', 'Thấm, ngấm', 'generated' from jp_vocab where id = '5442929b-ce78-406f-9955-00e95683def9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Thấm, ngấm"?', '書き込む', '注ぎ込む', '話し込む', '染み込む', '染み込む', 'generated' from jp_vocab where id = '5442929b-ce78-406f-9955-00e95683def9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"染み込む" đọc là gì?', 'おしえこむ', 'しみこむ', 'ひきこむ', 'たのみこむ', 'しみこむ', 'generated' from jp_vocab where id = '5442929b-ce78-406f-9955-00e95683def9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 水が_____ました。', '染み込み', 'generated' from jp_vocab where id = '5442929b-ce78-406f-9955-00e95683def9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"引っ込む" có nghĩa là gì?', 'Nhập vào, gõ; Cống hiến hết mình vì; Tập trung, đắm chìm', 'Chạy lao vào', 'Co lại, lùi về', 'Lôi kéo, dẫn vào', 'Co lại, lùi về', 'generated' from jp_vocab where id = '7929ac99-4894-45f5-b8dd-fb5e987f39cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Co lại, lùi về"?', '座り込む', '割り込む', '引っ込む', '飲み込む', '引っ込む', 'generated' from jp_vocab where id = '7929ac99-4894-45f5-b8dd-fb5e987f39cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"引っ込む" đọc là gì?', 'ひっこむ', 'すみこむ', 'はなしこむ', 'はこびこむ', 'ひっこむ', 'generated' from jp_vocab where id = '7929ac99-4894-45f5-b8dd-fb5e987f39cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 部屋に_____ました。', '引っ込み', 'generated' from jp_vocab where id = '7929ac99-4894-45f5-b8dd-fb5e987f39cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"引き込む" có nghĩa là gì?', 'Nhập vào, gõ; Cống hiến hết mình vì; Tập trung, đắm chìm', 'Lôi kéo, dẫn vào', 'Trọ lại, ở lại', 'Cuộn vào; Dính líu', 'Lôi kéo, dẫn vào', 'generated' from jp_vocab where id = '15924f96-0bb4-45a9-9a4e-9637425c8b4c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Lôi kéo, dẫn vào"?', '教え込む', '割り込む', '詰め込む', '引き込む', '引き込む', 'generated' from jp_vocab where id = '15924f96-0bb4-45a9-9a4e-9637425c8b4c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"引き込む" đọc là gì?', 'とびこむ', 'ひきこむ', 'かきこむ', 'しみこむ', 'ひきこむ', 'generated' from jp_vocab where id = '15924f96-0bb4-45a9-9a4e-9637425c8b4c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 話に_____まれました。', '引き込', 'generated' from jp_vocab where id = '15924f96-0bb4-45a9-9a4e-9637425c8b4c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"運び込む" có nghĩa là gì?', 'Trọ lại, ở lại', 'Nhờ vả, khẩn khoản xin', 'Say sưa nói chuyện', 'Mang vào, đem vào', 'Mang vào, đem vào', 'generated' from jp_vocab where id = '1a909633-1878-4602-b213-d2d130acc325';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Mang vào, đem vào"?', '巻き込む', '運び込む', '引き込む', '駆け込む', '運び込む', 'generated' from jp_vocab where id = '1a909633-1878-4602-b213-d2d130acc325';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"運び込む" đọc là gì?', 'すみこむ', 'ひっこむ', 'はこびこむ', 'はなしこむ', 'はこびこむ', 'generated' from jp_vocab where id = '1a909633-1878-4602-b213-d2d130acc325';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 荷物を_____ます。', '運び込み', 'generated' from jp_vocab where id = '1a909633-1878-4602-b213-d2d130acc325';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"注ぎ込む" có nghĩa là gì?', 'Mời gọi, lôi kéo, thu hút', 'Giữ im lặng', 'Lôi kéo, dẫn vào', 'Đổ vào trong', 'Đổ vào trong', 'generated' from jp_vocab where id = '3a939e2d-9c07-4c3c-82bf-b3ce93a62673';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Đổ vào trong"?', '注ぎ込む', '住み込む', '追い込む', '駆け込む', '注ぎ込む', 'generated' from jp_vocab where id = '3a939e2d-9c07-4c3c-82bf-b3ce93a62673';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"注ぎ込む" đọc là gì?', 'そそぎこむ', 'かきこむ', 'おいこむ', 'とまりこむ', 'そそぎこむ', 'generated' from jp_vocab where id = '3a939e2d-9c07-4c3c-82bf-b3ce93a62673';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 資金を_____ます。', '注ぎ込み', 'generated' from jp_vocab where id = '3a939e2d-9c07-4c3c-82bf-b3ce93a62673';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"追い込む" có nghĩa là gì?', 'Tiếp thị, mời gọi', 'Nhờ vả, khẩn khoản xin', 'Lùa vào, dồn vào', 'Viết vào, nhập vào', 'Lùa vào, dồn vào', 'generated' from jp_vocab where id = '9583aab5-da76-4790-b7ca-f1f865092bde';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Lùa vào, dồn vào"?', '寝込む', '運び込む', '泊まり込む', '追い込む', '追い込む', 'generated' from jp_vocab where id = '9583aab5-da76-4790-b7ca-f1f865092bde';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"追い込む" đọc là gì?', 'おいこむ', 'とびこむ', 'よびこむ', 'はこびこむ', 'おいこむ', 'generated' from jp_vocab where id = '9583aab5-da76-4790-b7ca-f1f865092bde';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 窮地に_____まれました。', '追い込', 'generated' from jp_vocab where id = '9583aab5-da76-4790-b7ca-f1f865092bde';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"話し込む" có nghĩa là gì?', 'Say sưa nói chuyện', 'Nhét vào, nhồi nhét', 'Nhập vào, gõ; Cống hiến hết mình vì; Tập trung, đắm chìm', 'Ngủ say, ngủ li bì, nằm liệt giường', 'Say sưa nói chuyện', 'generated' from jp_vocab where id = 'feb038f9-879e-4b30-840c-d7ceb5315526';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Say sưa nói chuyện"?', '引き込む', '泊まり込む', '教え込む', '話し込む', '話し込む', 'generated' from jp_vocab where id = 'feb038f9-879e-4b30-840c-d7ceb5315526';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"話し込む" đọc là gì?', 'うりこむ', 'つめこむ', 'はなしこむ', 'すわりこむ', 'はなしこむ', 'generated' from jp_vocab where id = 'feb038f9-879e-4b30-840c-d7ceb5315526';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 友達と_____ました。', '話し込み', 'generated' from jp_vocab where id = 'feb038f9-879e-4b30-840c-d7ceb5315526';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"黙り込む" có nghĩa là gì?', 'Cuộn vào; Dính líu', 'Co lại, lùi về', 'Giữ im lặng', 'Nhờ vả, khẩn khoản xin', 'Giữ im lặng', 'generated' from jp_vocab where id = '8eeda157-99a4-48be-a71c-ede03e627dfa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Giữ im lặng"?', '詰め込む', '黙り込む', '割り込む', '巻き込む', '黙り込む', 'generated' from jp_vocab where id = '8eeda157-99a4-48be-a71c-ede03e627dfa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"黙り込む" đọc là gì?', 'はこびこむ', 'まきこむ', 'さしこむ', 'だまりこむ', 'だまりこむ', 'generated' from jp_vocab where id = '8eeda157-99a4-48be-a71c-ede03e627dfa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 彼は_____ました。', '黙り込み', 'generated' from jp_vocab where id = '8eeda157-99a4-48be-a71c-ede03e627dfa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"打ち込む" có nghĩa là gì?', 'Nhập vào, gõ; Cống hiến hết mình vì; Tập trung, đắm chìm', 'Trọ lại, ở lại', 'Thấm, ngấm', 'Đổ vào trong', 'Nhập vào, gõ; Cống hiến hết mình vì; Tập trung, đắm chìm', 'generated' from jp_vocab where id = '664ac970-6b4d-4db3-b9cf-6323a7946087';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Nhập vào, gõ; Cống hiến hết mình vì; Tập trung, đắm chìm"?', '飲み込む', '座り込む', '打ち込む', '注ぎ込む', '打ち込む', 'generated' from jp_vocab where id = '664ac970-6b4d-4db3-b9cf-6323a7946087';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"打ち込む" đọc là gì?', 'ひきこむ', 'うちこむ', 'とびこむ', 'おいこむ', 'うちこむ', 'generated' from jp_vocab where id = '664ac970-6b4d-4db3-b9cf-6323a7946087';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 仕事に_____ます。', '打ち込み', 'generated' from jp_vocab where id = '664ac970-6b4d-4db3-b9cf-6323a7946087';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"煮込む" có nghĩa là gì?', 'Nhập vào, gõ; Cống hiến hết mình vì; Tập trung, đắm chìm', 'Chạy lao vào', 'Tiếp thị, mời gọi', 'Nấu, ninh', 'Nấu, ninh', 'generated' from jp_vocab where id = '4bb746f7-6b58-453a-af4d-b4bf92104a46';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Nấu, ninh"?', '書き込む', '引き込む', '運び込む', '煮込む', '煮込む', 'generated' from jp_vocab where id = '4bb746f7-6b58-453a-af4d-b4bf92104a46';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"煮込む" đọc là gì?', 'そそぎこむ', 'ひきこむ', 'おしえこむ', 'にこむ', 'にこむ', 'generated' from jp_vocab where id = '4bb746f7-6b58-453a-af4d-b4bf92104a46';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: スープを_____ます。', '煮込み', 'generated' from jp_vocab where id = '4bb746f7-6b58-453a-af4d-b4bf92104a46';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"売り込む" có nghĩa là gì?', 'Lôi kéo, dẫn vào', 'Hiểu, thành thục; Nuốt vào', 'Chen vào, xen ngang', 'Tiếp thị, mời gọi', 'Tiếp thị, mời gọi', 'generated' from jp_vocab where id = 'dafdb15a-f591-4f86-adee-9a0e5c309936';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Tiếp thị, mời gọi"?', '打ち込む', '売り込む', '注ぎ込む', '詰め込む', '売り込む', 'generated' from jp_vocab where id = 'dafdb15a-f591-4f86-adee-9a0e5c309936';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"売り込む" đọc là gì?', 'よびこむ', 'とまりこむ', 'すみこむ', 'うりこむ', 'うりこむ', 'generated' from jp_vocab where id = 'dafdb15a-f591-4f86-adee-9a0e5c309936';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 商品を_____ます。', '売り込み', 'generated' from jp_vocab where id = 'dafdb15a-f591-4f86-adee-9a0e5c309936';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"頼み込む" có nghĩa là gì?', 'Viết vào, nhập vào', 'Lôi kéo, dẫn vào', 'Nhờ vả, khẩn khoản xin', 'Nấu, ninh', 'Nhờ vả, khẩn khoản xin', 'generated' from jp_vocab where id = '1d30983b-9529-4652-9aa6-cd476bd03960';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Nhờ vả, khẩn khoản xin"?', '飛び込む', '泊まり込む', '詰め込む', '頼み込む', '頼み込む', 'generated' from jp_vocab where id = '1d30983b-9529-4652-9aa6-cd476bd03960';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"頼み込む" đọc là gì?', 'たのみこむ', 'うりこむ', 'おしえこむ', 'はこびこむ', 'たのみこむ', 'generated' from jp_vocab where id = '1d30983b-9529-4652-9aa6-cd476bd03960';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で許可をもらいました。', '頼み込ん', 'generated' from jp_vocab where id = '1d30983b-9529-4652-9aa6-cd476bd03960';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"教え込む" có nghĩa là gì?', 'Viết vào, nhập vào', 'Hiểu, thành thục; Nuốt vào', 'Dạy, huấn luyện', 'Say sưa nói chuyện', 'Dạy, huấn luyện', 'generated' from jp_vocab where id = 'd9231371-fb38-4173-94d3-265a2d96bc87';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Dạy, huấn luyện"?', '売り込む', '教え込む', '差し込む', '巻き込む', '教え込む', 'generated' from jp_vocab where id = 'd9231371-fb38-4173-94d3-265a2d96bc87';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"教え込む" đọc là gì?', 'かけこむ', 'よびこむ', 'つめこむ', 'おしえこむ', 'おしえこむ', 'generated' from jp_vocab where id = 'd9231371-fb38-4173-94d3-265a2d96bc87';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 子供に_____ます。', '教え込み', 'generated' from jp_vocab where id = 'd9231371-fb38-4173-94d3-265a2d96bc87';

-- Tổng 104 câu hỏi generated cho 26 từ.
