-- ============================================================
-- jp-go — Từ vựng N2, round 27 (trang in 61 — TRANG CUỐI PART 2 -
-- 語彙). Nguồn: PDF "Tổng hợp kiến thức N2" (Dũng Mori).
--
-- Nhóm 1: カタカナ (7 từ, hoàn tất nhóm カタカナ: 36+54+7=97 từ).
-- Nhóm 2: まとめ (25 từ, word_class='名詞' vì không có tiêu đề từ
-- loại riêng trong PDF, đa số là danh từ Hán-Việt).
--
-- Trang này có câu hỏi trắc nghiệm thật Q8 tự chứa (câu hỏi và đáp
-- án cùng trang, ＊答-❸スタイル) — chưa insert, gộp vào migration
-- tổng hợp 8 câu hỏi thật cuối module Từ vựng N2.
-- ============================================================

-- ---------- Nhóm カタカナ (phần 3/3) (カタカナ) ----------
-- ---------- パターン ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('8c7c6d72-4343-4de7-a1c5-a59b68a9aaeb', 'N2', NULL, 'word', 'パターン', 'パターン', 'Kiểu, mẫu, hoa tiết', NULL, NULL, 'カタカナ', 61, 'パターン', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'いつも同じパターンです。', 'Lúc nào cũng theo cùng một khuôn mẫu.', 'いつも同じ_____です。', 'パターン', 'generated' from jp_vocab where id = '8c7c6d72-4343-4de7-a1c5-a59b68a9aaeb';

-- ---------- パス ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('6ba82752-c924-43bb-acd9-0fcc05ba397c', 'N2', NULL, 'word', 'パス', 'パス', 'Qua, đỗ, bỏ qua', NULL, NULL, 'カタカナ', 61, 'パス', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '試験にパスしました。', 'Tôi đã đỗ kỳ thi.', '試験に_____しました。', 'パス', 'generated' from jp_vocab where id = '6ba82752-c924-43bb-acd9-0fcc05ba397c';

-- ---------- プラン ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('4c24608f-747f-4952-b45b-10b93da25881', 'N2', NULL, 'word', 'プラン', 'プラン', 'Kế hoạch', NULL, NULL, 'カタカナ', 61, 'プラン', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '新しいプランを立てます。', 'Tôi lập một kế hoạch mới.', '新しい_____を立てます。', 'プラン', 'generated' from jp_vocab where id = '4c24608f-747f-4952-b45b-10b93da25881';

-- ---------- プレシャー ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('a0972e6f-7607-4a68-9a6a-e3695c3edb34', 'N2', NULL, 'word', 'プレシャー', 'プレシャー', 'Áp lực', NULL, NULL, 'カタカナ', 61, 'プレシャー', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '仕事のプレシャーを感じます。', 'Tôi cảm thấy áp lực công việc.', '仕事の_____を感じます。', 'プレシャー', 'generated' from jp_vocab where id = 'a0972e6f-7607-4a68-9a6a-e3695c3edb34';

-- ---------- プログラム ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('5ef771e4-7cbc-431e-9a0e-22f34f314666', 'N2', NULL, 'word', 'プログラム', 'プログラム', 'Chương trình', NULL, NULL, 'カタカナ', 61, 'プログラム', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '今日のプログラムを確認します。', 'Tôi kiểm tra chương trình hôm nay.', '今日の_____を確認します。', 'プログラム', 'generated' from jp_vocab where id = '5ef771e4-7cbc-431e-9a0e-22f34f314666';

-- ---------- ペア ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('6d67d7e2-e988-48a2-98cc-4dc2bfdefa99', 'N2', NULL, 'word', 'ペア', 'ペア', 'Cặp', NULL, NULL, 'カタカナ', 61, 'ペア', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ペアになって練習します。', 'Chúng tôi luyện tập theo từng cặp.', '_____になって練習します。', 'ペア', 'generated' from jp_vocab where id = '6d67d7e2-e988-48a2-98cc-4dc2bfdefa99';

-- ---------- ポイント ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('7448182b-76b7-44b9-9db7-a4e85e24ebfb', 'N2', NULL, 'word', 'ポイント', 'ポイント', 'Điểm, mấu chốt', NULL, NULL, 'カタカナ', 61, 'ポイント', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ここがポイントです。', 'Đây là điểm mấu chốt.', 'ここが_____です。', 'ポイント', 'generated' from jp_vocab where id = '7448182b-76b7-44b9-9db7-a4e85e24ebfb';

-- ---------- jp_vocab_questions cho nhóm カタカナ (phần 3/3): generated, 4 câu/từ ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"パターン" có nghĩa là gì?', 'Cặp', 'Qua, đỗ, bỏ qua', 'Kiểu, mẫu, hoa tiết', 'Áp lực', 'Kiểu, mẫu, hoa tiết', 'generated' from jp_vocab where id = '8c7c6d72-4343-4de7-a1c5-a59b68a9aaeb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Kiểu, mẫu, hoa tiết"?', 'プログラム', 'プラン', 'パターン', 'プレシャー', 'パターン', 'generated' from jp_vocab where id = '8c7c6d72-4343-4de7-a1c5-a59b68a9aaeb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"パターン" đọc là gì?', 'パターン', 'プラン', 'パス', 'プログラム', 'パターン', 'generated' from jp_vocab where id = '8c7c6d72-4343-4de7-a1c5-a59b68a9aaeb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: いつも同じ_____です。', 'パターン', 'generated' from jp_vocab where id = '8c7c6d72-4343-4de7-a1c5-a59b68a9aaeb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"パス" có nghĩa là gì?', 'Qua, đỗ, bỏ qua', 'Kiểu, mẫu, hoa tiết', 'Chương trình', 'Cặp', 'Qua, đỗ, bỏ qua', 'generated' from jp_vocab where id = '6ba82752-c924-43bb-acd9-0fcc05ba397c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Qua, đỗ, bỏ qua"?', 'プログラム', 'パターン', 'プレシャー', 'パス', 'パス', 'generated' from jp_vocab where id = '6ba82752-c924-43bb-acd9-0fcc05ba397c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"パス" đọc là gì?', 'パス', 'ペア', 'プログラム', 'パターン', 'パス', 'generated' from jp_vocab where id = '6ba82752-c924-43bb-acd9-0fcc05ba397c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 試験に_____しました。', 'パス', 'generated' from jp_vocab where id = '6ba82752-c924-43bb-acd9-0fcc05ba397c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"プラン" có nghĩa là gì?', 'Chương trình', 'Áp lực', 'Kế hoạch', 'Qua, đỗ, bỏ qua', 'Kế hoạch', 'generated' from jp_vocab where id = '4c24608f-747f-4952-b45b-10b93da25881';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Kế hoạch"?', 'プログラム', 'ペア', 'プラン', 'パス', 'プラン', 'generated' from jp_vocab where id = '4c24608f-747f-4952-b45b-10b93da25881';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"プラン" đọc là gì?', 'パターン', 'ポイント', 'プラン', 'プレシャー', 'プラン', 'generated' from jp_vocab where id = '4c24608f-747f-4952-b45b-10b93da25881';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 新しい_____を立てます。', 'プラン', 'generated' from jp_vocab where id = '4c24608f-747f-4952-b45b-10b93da25881';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"プレシャー" có nghĩa là gì?', 'Qua, đỗ, bỏ qua', 'Kiểu, mẫu, hoa tiết', 'Áp lực', 'Chương trình', 'Áp lực', 'generated' from jp_vocab where id = 'a0972e6f-7607-4a68-9a6a-e3695c3edb34';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Áp lực"?', 'プラン', 'プレシャー', 'パス', 'ポイント', 'プレシャー', 'generated' from jp_vocab where id = 'a0972e6f-7607-4a68-9a6a-e3695c3edb34';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"プレシャー" đọc là gì?', 'プレシャー', 'パターン', 'パス', 'ペア', 'プレシャー', 'generated' from jp_vocab where id = 'a0972e6f-7607-4a68-9a6a-e3695c3edb34';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 仕事の_____を感じます。', 'プレシャー', 'generated' from jp_vocab where id = 'a0972e6f-7607-4a68-9a6a-e3695c3edb34';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"プログラム" có nghĩa là gì?', 'Chương trình', 'Điểm, mấu chốt', 'Cặp', 'Áp lực', 'Chương trình', 'generated' from jp_vocab where id = '5ef771e4-7cbc-431e-9a0e-22f34f314666';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Chương trình"?', 'パターン', 'プログラム', 'プラン', 'パス', 'プログラム', 'generated' from jp_vocab where id = '5ef771e4-7cbc-431e-9a0e-22f34f314666';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"プログラム" đọc là gì?', 'ペア', 'プログラム', 'プラン', 'ポイント', 'プログラム', 'generated' from jp_vocab where id = '5ef771e4-7cbc-431e-9a0e-22f34f314666';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 今日の_____を確認します。', 'プログラム', 'generated' from jp_vocab where id = '5ef771e4-7cbc-431e-9a0e-22f34f314666';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ペア" có nghĩa là gì?', 'Cặp', 'Điểm, mấu chốt', 'Kiểu, mẫu, hoa tiết', 'Qua, đỗ, bỏ qua', 'Cặp', 'generated' from jp_vocab where id = '6d67d7e2-e988-48a2-98cc-4dc2bfdefa99';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Cặp"?', 'ペア', 'プレシャー', 'パターン', 'プラン', 'ペア', 'generated' from jp_vocab where id = '6d67d7e2-e988-48a2-98cc-4dc2bfdefa99';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ペア" đọc là gì?', 'プレシャー', 'プログラム', 'パス', 'ペア', 'ペア', 'generated' from jp_vocab where id = '6d67d7e2-e988-48a2-98cc-4dc2bfdefa99';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____になって練習します。', 'ペア', 'generated' from jp_vocab where id = '6d67d7e2-e988-48a2-98cc-4dc2bfdefa99';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ポイント" có nghĩa là gì?', 'Áp lực', 'Điểm, mấu chốt', 'Kế hoạch', 'Chương trình', 'Điểm, mấu chốt', 'generated' from jp_vocab where id = '7448182b-76b7-44b9-9db7-a4e85e24ebfb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Điểm, mấu chốt"?', 'ポイント', 'プラン', 'パス', 'ペア', 'ポイント', 'generated' from jp_vocab where id = '7448182b-76b7-44b9-9db7-a4e85e24ebfb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ポイント" đọc là gì?', 'プレシャー', 'プログラム', 'ペア', 'ポイント', 'ポイント', 'generated' from jp_vocab where id = '7448182b-76b7-44b9-9db7-a4e85e24ebfb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: ここが_____です。', 'ポイント', 'generated' from jp_vocab where id = '7448182b-76b7-44b9-9db7-a4e85e24ebfb';

-- Tổng 28 câu hỏi generated cho 7 từ nhóm カタカナ (phần 3/3).

-- ---------- Nhóm まとめ (名詞) ----------
-- ---------- 改正 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('eebdbaab-8e35-4664-b9de-349b9c0277d5', 'N2', NULL, 'word', '改正', 'かいせい', 'Sự thay đổi, sự chỉnh sửa', NULL, NULL, '名詞', 61, '改正', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '法律が改正されました。', 'Luật đã được sửa đổi.', '法律が_____されました。', '改正', 'generated' from jp_vocab where id = 'eebdbaab-8e35-4664-b9de-349b9c0277d5';

-- ---------- 改定 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('f40cc449-da73-444d-92ed-5a1c8d81092d', 'N2', NULL, 'word', '改定', 'かいてい', 'Sửa đổi', NULL, NULL, '名詞', 61, '改定', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '料金が改定されました。', 'Mức phí đã được sửa đổi.', '料金が_____されました。', '改定', 'generated' from jp_vocab where id = 'f40cc449-da73-444d-92ed-5a1c8d81092d';

-- ---------- 改修 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('c7237cdd-9657-41be-8235-0f093cdc6560', 'N2', NULL, 'word', '改修', 'かいしゅう', 'Cải tiến; nâng cấp; sự cải tạo', NULL, NULL, '名詞', 61, '改修', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '道路の改修工事をしています。', 'Đang tiến hành cải tạo đường.', '道路の_____工事をしています。', '改修', 'generated' from jp_vocab where id = 'c7237cdd-9657-41be-8235-0f093cdc6560';

-- ---------- 改革 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('d74c5eda-7240-4733-aa33-67f8f1425c92', 'N2', NULL, 'word', '改革', 'かいかく', 'Cải cách', NULL, NULL, '名詞', 61, '改革', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '経済の改革を進めます。', 'Chúng tôi thúc đẩy cải cách kinh tế.', '経済の_____を進めます。', '改革', 'generated' from jp_vocab where id = 'd74c5eda-7240-4733-aa33-67f8f1425c92';

-- ---------- 改善 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('b98739f7-e6ac-4364-bf06-31a0f091de25', 'N2', NULL, 'word', '改善', 'かいぜん', 'Sự cải thiện', NULL, NULL, '名詞', 61, '改善', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '環境を改善します。', 'Tôi cải thiện môi trường.', '環境を_____します。', '改善', 'generated' from jp_vocab where id = 'b98739f7-e6ac-4364-bf06-31a0f091de25';

-- ---------- 改良 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('2e5b8ec0-eeb2-4d31-a74c-c7dde15c05d5', 'N2', NULL, 'word', '改良', 'かいりょう', 'Sự cải thiện, cải tiến', NULL, NULL, '名詞', 61, '改良', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '製品を改良しました。', 'Tôi đã cải tiến sản phẩm.', '製品を_____しました。', '改良', 'generated' from jp_vocab where id = '2e5b8ec0-eeb2-4d31-a74c-c7dde15c05d5';

-- ---------- 開業 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('c470a327-512c-4153-9266-665c596b390a', 'N2', NULL, 'word', '開業', 'かいぎょう', 'Bắt đầu kinh doanh, khai trương', NULL, NULL, '名詞', 61, '開業', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '来月開業する予定です。', 'Dự kiến khai trương vào tháng sau.', '来月_____する予定です。', '開業', 'generated' from jp_vocab where id = 'c470a327-512c-4153-9266-665c596b390a';

-- ---------- 開発 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('459dd5ad-4305-4527-8f39-fb998c3a74fb', 'N2', NULL, 'word', '開発', 'かいはつ', 'Sự phát triển', NULL, NULL, '名詞', 61, '開発', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '新製品を開発します。', 'Chúng tôi phát triển sản phẩm mới.', '新製品を_____します。', '開発', 'generated' from jp_vocab where id = '459dd5ad-4305-4527-8f39-fb998c3a74fb';

-- ---------- 開店 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('c808350d-72e7-4505-b6b8-3e660302ad68', 'N2', NULL, 'word', '開店', 'かいてん', 'Sự mở cửa hàng', NULL, NULL, '名詞', 61, '開店', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '午前10時に開店します。', 'Cửa hàng mở cửa lúc 10 giờ sáng.', '午前10時に_____します。', '開店', 'generated' from jp_vocab where id = 'c808350d-72e7-4505-b6b8-3e660302ad68';

-- ---------- 開催 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('fe9a65d2-87bf-4b2a-bd66-7229d8a70d76', 'N2', NULL, 'word', '開催', 'かいさい', 'Sự tổ chức, tổ chức', NULL, NULL, '名詞', 61, '開催', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '大会が開催されます。', 'Đại hội sẽ được tổ chức.', '大会が_____されます。', '開催', 'generated' from jp_vocab where id = 'fe9a65d2-87bf-4b2a-bd66-7229d8a70d76';

-- ---------- 開放 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('977592ed-4ff6-4f75-b198-1060d57e19a3', 'N2', NULL, 'word', '開放', 'かいほう', 'Sự mở cửa; sự tự do hóa', NULL, NULL, '名詞', 61, '開放', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '市場が開放されました。', 'Thị trường đã được mở cửa.', '市場が_____されました。', '開放', 'generated' from jp_vocab where id = '977592ed-4ff6-4f75-b198-1060d57e19a3';

-- ---------- 閉鎖 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('e3019dc6-c511-4c51-a24d-2f83e35f6a1a', 'N2', NULL, 'word', '閉鎖', 'へいさ', 'Sự phong bế; sự phong tỏa', NULL, NULL, '名詞', 61, '閉鎖', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '工場が閉鎖されました。', 'Nhà máy đã bị đóng cửa.', '工場が_____されました。', '閉鎖', 'generated' from jp_vocab where id = 'e3019dc6-c511-4c51-a24d-2f83e35f6a1a';

-- ---------- 密閉 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('aa394ac5-ff75-4033-922c-b7bd0f512200', 'N2', NULL, 'word', '密閉', 'みっぺい', 'Kín mít, niêm phong', NULL, NULL, '名詞', 61, '密閉', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '容器を密閉します。', 'Tôi niêm phong kín hộp đựng.', '容器を_____します。', '密閉', 'generated' from jp_vocab where id = 'aa394ac5-ff75-4033-922c-b7bd0f512200';

-- ---------- 増税 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('dfe34827-28fc-419a-bf42-b1694dafb405', 'N2', NULL, 'word', '増税', 'ぞうぜい', 'Sự tăng thuế', NULL, NULL, '名詞', 61, '増税', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '来年から増税されます。', 'Từ năm sau sẽ tăng thuế.', '来年から_____されます。', '増税', 'generated' from jp_vocab where id = 'dfe34827-28fc-419a-bf42-b1694dafb405';

-- ---------- 増大 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('d6cc805a-977a-4d2d-8ed9-cc72891bbe0e', 'N2', NULL, 'word', '増大', 'ぞうだい', 'Sự tăng về lượng', NULL, NULL, '名詞', 61, '増大', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '需要が増大しています。', 'Nhu cầu đang tăng lên.', '需要が_____しています。', '増大', 'generated' from jp_vocab where id = 'd6cc805a-977a-4d2d-8ed9-cc72891bbe0e';

-- ---------- 増員 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('d45ba090-f954-472c-81ec-26c1771c3cb5', 'N2', NULL, 'word', '増員', 'ぞういん', 'Tăng số lượng người', NULL, NULL, '名詞', 61, '増員', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'スタッフを増員しました。', 'Chúng tôi đã tăng thêm nhân viên.', 'スタッフを_____しました。', '増員', 'generated' from jp_vocab where id = 'd45ba090-f954-472c-81ec-26c1771c3cb5';

-- ---------- 増量 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('90fbc135-18af-418d-923b-b8b31262773c', 'N2', NULL, 'word', '増量', 'ぞうりょう', 'Sự tăng thêm', NULL, NULL, '名詞', 61, '増量', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '今だけ増量サービス中です。', 'Chỉ hôm nay có dịch vụ tăng thêm số lượng.', '今だけ_____サービス中です。', '増量', 'generated' from jp_vocab where id = '90fbc135-18af-418d-923b-b8b31262773c';

-- ---------- 減量 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('8f12b7a3-c1d2-4bd3-a1ab-07dbc95cd584', 'N2', NULL, 'word', '減量', 'げんりょう', 'Giảm cân, giảm trọng lượng', NULL, NULL, '名詞', 61, '減量', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '健康のために減量します。', 'Tôi giảm cân vì sức khỏe.', '健康のために_____します。', '減量', 'generated' from jp_vocab where id = '8f12b7a3-c1d2-4bd3-a1ab-07dbc95cd584';

-- ---------- 減点 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('ad586e19-6edd-4175-a768-fcd291018b0b', 'N2', NULL, 'word', '減点', 'げんてん', 'Giảm điểm số', NULL, NULL, '名詞', 61, '減点', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ミスがあると減点されます。', 'Nếu có lỗi sai sẽ bị trừ điểm.', 'ミスがあると_____されます。', '減点', 'generated' from jp_vocab where id = 'ad586e19-6edd-4175-a768-fcd291018b0b';

-- ---------- 減退 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('cfbde97e-9017-4f82-b4bc-6b729800fe2c', 'N2', NULL, 'word', '減退', 'げんたい', 'Sự giảm sút, sự suy yếu', NULL, NULL, '名詞', 61, '減退', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '食欲が減退しました。', 'Sự thèm ăn đã giảm sút.', '食欲が_____しました。', '減退', 'generated' from jp_vocab where id = 'cfbde97e-9017-4f82-b4bc-6b729800fe2c';

-- ---------- 一流 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('8c9d966b-28a8-4809-a412-77808ba7c484', 'N2', NULL, 'word', '一流', 'いちりゅう', 'Hạng nhất, hàng đầu, cao cấp', NULL, NULL, '名詞', 61, '一流', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '一流のホテルに泊まりました。', 'Tôi đã ở một khách sạn hạng sang.', '_____のホテルに泊まりました。', '一流', 'generated' from jp_vocab where id = '8c9d966b-28a8-4809-a412-77808ba7c484';

-- ---------- 一定 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('ef1c02b5-6cf0-4e91-9093-9fe90eb6adb5', 'N2', NULL, 'word', '一定', 'いってい', 'Cố định, nhất định', NULL, NULL, '名詞', 61, '一定', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '一定のルールを守ります。', 'Tôi tuân theo một quy tắc nhất định.', '_____のルールを守ります。', '一定', 'generated' from jp_vocab where id = 'ef1c02b5-6cf0-4e91-9093-9fe90eb6adb5';

-- ---------- 一致 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('565a4869-0939-40e4-87b3-6ce4bd8c78be', 'N2', NULL, 'word', '一致', 'いっち', 'Sự nhất trí, sự giống nhau, sự thống nhất', NULL, NULL, '名詞', 61, '一致', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '意見が一致しました。', 'Ý kiến đã thống nhất.', '意見が_____しました。', '一致', 'generated' from jp_vocab where id = '565a4869-0939-40e4-87b3-6ce4bd8c78be';

-- ---------- 一方 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('7df6aae1-3034-4b22-b106-a6cf8da109cb', 'N2', NULL, 'word', '一方', 'いっぽう', 'Một mặt, mặt khác', NULL, NULL, '名詞', 61, '一方', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '一方で問題も残っています。', 'Mặt khác vẫn còn tồn tại vấn đề.', '_____で問題も残っています。', '一方', 'generated' from jp_vocab where id = '7df6aae1-3034-4b22-b106-a6cf8da109cb';

-- ---------- 一人前 ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, group_key, word_class, source_page, source_text, source_type, review_status) values ('cb85e15a-00c5-43fe-a0b8-ce8ca3edb823', 'N2', NULL, 'word', '一人前', 'いちにんまえ', 'Người trưởng thành, khẩu phần một người', NULL, NULL, '名詞', 61, '一人前', 'pdf', 'ok')
on conflict (level, word_class, word_jp, reading_furigana) where lesson_no is null do nothing;
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彼は一人前の職人になりました。', 'Anh ấy đã trở thành một người thợ lành nghề.', '彼は_____の職人になりました。', '一人前', 'generated' from jp_vocab where id = 'cb85e15a-00c5-43fe-a0b8-ce8ca3edb823';

-- ---------- jp_vocab_questions cho nhóm まとめ: generated, 4 câu/từ ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"改正" có nghĩa là gì?', 'Sự cải thiện, cải tiến', 'Sự thay đổi, sự chỉnh sửa', 'Sự tăng thêm', 'Sửa đổi', 'Sự thay đổi, sự chỉnh sửa', 'generated' from jp_vocab where id = 'eebdbaab-8e35-4664-b9de-349b9c0277d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự thay đổi, sự chỉnh sửa"?', '減量', '増員', '改正', '開店', '改正', 'generated' from jp_vocab where id = 'eebdbaab-8e35-4664-b9de-349b9c0277d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"改正" đọc là gì?', 'げんりょう', 'かいせい', 'ぞうりょう', 'かいかく', 'かいせい', 'generated' from jp_vocab where id = 'eebdbaab-8e35-4664-b9de-349b9c0277d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 法律が_____されました。', '改正', 'generated' from jp_vocab where id = 'eebdbaab-8e35-4664-b9de-349b9c0277d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"改定" có nghĩa là gì?', 'Sự tổ chức, tổ chức', 'Sửa đổi', 'Sự cải thiện', 'Sự mở cửa hàng', 'Sửa đổi', 'generated' from jp_vocab where id = 'f40cc449-da73-444d-92ed-5a1c8d81092d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sửa đổi"?', '閉鎖', '減点', '一定', '改定', '改定', 'generated' from jp_vocab where id = 'f40cc449-da73-444d-92ed-5a1c8d81092d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"改定" đọc là gì?', 'かいてい', 'かいはつ', 'げんりょう', 'かいぜん', 'かいてい', 'generated' from jp_vocab where id = 'f40cc449-da73-444d-92ed-5a1c8d81092d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 料金が_____されました。', '改定', 'generated' from jp_vocab where id = 'f40cc449-da73-444d-92ed-5a1c8d81092d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"改修" có nghĩa là gì?', 'Cải tiến; nâng cấp; sự cải tạo', 'Giảm điểm số', 'Cải cách', 'Sự cải thiện, cải tiến', 'Cải tiến; nâng cấp; sự cải tạo', 'generated' from jp_vocab where id = 'c7237cdd-9657-41be-8235-0f093cdc6560';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Cải tiến; nâng cấp; sự cải tạo"?', '一人前', '開業', '改修', '閉鎖', '改修', 'generated' from jp_vocab where id = 'c7237cdd-9657-41be-8235-0f093cdc6560';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"改修" đọc là gì?', 'かいしゅう', 'かいせい', 'いっぽう', 'かいぎょう', 'かいしゅう', 'generated' from jp_vocab where id = 'c7237cdd-9657-41be-8235-0f093cdc6560';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 道路の_____工事をしています。', '改修', 'generated' from jp_vocab where id = 'c7237cdd-9657-41be-8235-0f093cdc6560';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"改革" có nghĩa là gì?', 'Tăng số lượng người', 'Cải cách', 'Sự thay đổi, sự chỉnh sửa', 'Sự tăng về lượng', 'Cải cách', 'generated' from jp_vocab where id = 'd74c5eda-7240-4733-aa33-67f8f1425c92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Cải cách"?', '改革', '開店', '増量', '減点', '改革', 'generated' from jp_vocab where id = 'd74c5eda-7240-4733-aa33-67f8f1425c92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"改革" đọc là gì?', 'かいてい', 'かいかく', 'ぞういん', 'ぞうりょう', 'かいかく', 'generated' from jp_vocab where id = 'd74c5eda-7240-4733-aa33-67f8f1425c92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 経済の_____を進めます。', '改革', 'generated' from jp_vocab where id = 'd74c5eda-7240-4733-aa33-67f8f1425c92';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"改善" có nghĩa là gì?', 'Sự mở cửa hàng', 'Sự tăng thuế', 'Sự cải thiện', 'Sự nhất trí, sự giống nhau, sự thống nhất', 'Sự cải thiện', 'generated' from jp_vocab where id = 'b98739f7-e6ac-4364-bf06-31a0f091de25';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự cải thiện"?', '減量', '減退', '改善', '改正', '改善', 'generated' from jp_vocab where id = 'b98739f7-e6ac-4364-bf06-31a0f091de25';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"改善" đọc là gì?', 'かいぜん', 'ぞうりょう', 'ぞうぜい', 'ぞういん', 'かいぜん', 'generated' from jp_vocab where id = 'b98739f7-e6ac-4364-bf06-31a0f091de25';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 環境を_____します。', '改善', 'generated' from jp_vocab where id = 'b98739f7-e6ac-4364-bf06-31a0f091de25';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"改良" có nghĩa là gì?', 'Cải cách', 'Sự nhất trí, sự giống nhau, sự thống nhất', 'Sự cải thiện, cải tiến', 'Cải tiến; nâng cấp; sự cải tạo', 'Sự cải thiện, cải tiến', 'generated' from jp_vocab where id = '2e5b8ec0-eeb2-4d31-a74c-c7dde15c05d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự cải thiện, cải tiến"?', '増税', '改定', '減点', '改良', '改良', 'generated' from jp_vocab where id = '2e5b8ec0-eeb2-4d31-a74c-c7dde15c05d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"改良" đọc là gì?', 'かいぜん', 'かいてん', 'いっぽう', 'かいりょう', 'かいりょう', 'generated' from jp_vocab where id = '2e5b8ec0-eeb2-4d31-a74c-c7dde15c05d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 製品を_____しました。', '改良', 'generated' from jp_vocab where id = '2e5b8ec0-eeb2-4d31-a74c-c7dde15c05d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"開業" có nghĩa là gì?', 'Sự thay đổi, sự chỉnh sửa', 'Bắt đầu kinh doanh, khai trương', 'Sự phát triển', 'Cải tiến; nâng cấp; sự cải tạo', 'Bắt đầu kinh doanh, khai trương', 'generated' from jp_vocab where id = 'c470a327-512c-4153-9266-665c596b390a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Bắt đầu kinh doanh, khai trương"?', '開業', '改良', '一流', '改修', '開業', 'generated' from jp_vocab where id = 'c470a327-512c-4153-9266-665c596b390a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"開業" đọc là gì?', 'かいさい', 'いってい', 'かいてん', 'かいぎょう', 'かいぎょう', 'generated' from jp_vocab where id = 'c470a327-512c-4153-9266-665c596b390a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 来月_____する予定です。', '開業', 'generated' from jp_vocab where id = 'c470a327-512c-4153-9266-665c596b390a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"開発" có nghĩa là gì?', 'Cải cách', 'Một mặt, mặt khác', 'Sự phát triển', 'Sự tăng thêm', 'Sự phát triển', 'generated' from jp_vocab where id = '459dd5ad-4305-4527-8f39-fb998c3a74fb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự phát triển"?', '一流', '増税', '一人前', '開発', '開発', 'generated' from jp_vocab where id = '459dd5ad-4305-4527-8f39-fb998c3a74fb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"開発" đọc là gì?', 'かいかく', 'かいはつ', 'かいさい', 'いちりゅう', 'かいはつ', 'generated' from jp_vocab where id = '459dd5ad-4305-4527-8f39-fb998c3a74fb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 新製品を_____します。', '開発', 'generated' from jp_vocab where id = '459dd5ad-4305-4527-8f39-fb998c3a74fb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"開店" có nghĩa là gì?', 'Tăng số lượng người', 'Hạng nhất, hàng đầu, cao cấp', 'Sự tăng về lượng', 'Sự mở cửa hàng', 'Sự mở cửa hàng', 'generated' from jp_vocab where id = 'c808350d-72e7-4505-b6b8-3e660302ad68';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự mở cửa hàng"?', '開店', '改正', '開催', '一流', '開店', 'generated' from jp_vocab where id = 'c808350d-72e7-4505-b6b8-3e660302ad68';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"開店" đọc là gì?', 'いってい', 'かいてん', 'かいせい', 'げんたい', 'かいてん', 'generated' from jp_vocab where id = 'c808350d-72e7-4505-b6b8-3e660302ad68';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 午前10時に_____します。', '開店', 'generated' from jp_vocab where id = 'c808350d-72e7-4505-b6b8-3e660302ad68';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"開催" có nghĩa là gì?', 'Người trưởng thành, khẩu phần một người', 'Sự tổ chức, tổ chức', 'Giảm cân, giảm trọng lượng', 'Sự tăng thuế', 'Sự tổ chức, tổ chức', 'generated' from jp_vocab where id = 'fe9a65d2-87bf-4b2a-bd66-7229d8a70d76';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự tổ chức, tổ chức"?', '増大', '開催', '改定', '増員', '開催', 'generated' from jp_vocab where id = 'fe9a65d2-87bf-4b2a-bd66-7229d8a70d76';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"開催" đọc là gì?', 'へいさ', 'かいさい', 'かいてい', 'かいかく', 'かいさい', 'generated' from jp_vocab where id = 'fe9a65d2-87bf-4b2a-bd66-7229d8a70d76';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 大会が_____されます。', '開催', 'generated' from jp_vocab where id = 'fe9a65d2-87bf-4b2a-bd66-7229d8a70d76';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"開放" có nghĩa là gì?', 'Sự tăng về lượng', 'Sự mở cửa; sự tự do hóa', 'Sự phát triển', 'Sự cải thiện', 'Sự mở cửa; sự tự do hóa', 'generated' from jp_vocab where id = '977592ed-4ff6-4f75-b198-1060d57e19a3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự mở cửa; sự tự do hóa"?', '開放', '一致', '減点', '開発', '開放', 'generated' from jp_vocab where id = '977592ed-4ff6-4f75-b198-1060d57e19a3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"開放" đọc là gì?', 'いっぽう', 'かいてい', 'かいりょう', 'かいほう', 'かいほう', 'generated' from jp_vocab where id = '977592ed-4ff6-4f75-b198-1060d57e19a3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 市場が_____されました。', '開放', 'generated' from jp_vocab where id = '977592ed-4ff6-4f75-b198-1060d57e19a3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"閉鎖" có nghĩa là gì?', 'Hạng nhất, hàng đầu, cao cấp', 'Sự giảm sút, sự suy yếu', 'Sự phong bế; sự phong tỏa', 'Sự phát triển', 'Sự phong bế; sự phong tỏa', 'generated' from jp_vocab where id = 'e3019dc6-c511-4c51-a24d-2f83e35f6a1a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự phong bế; sự phong tỏa"?', '閉鎖', '改革', '開放', '開業', '閉鎖', 'generated' from jp_vocab where id = 'e3019dc6-c511-4c51-a24d-2f83e35f6a1a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"閉鎖" đọc là gì?', 'へいさ', 'かいてい', 'かいぜん', 'かいりょう', 'へいさ', 'generated' from jp_vocab where id = 'e3019dc6-c511-4c51-a24d-2f83e35f6a1a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 工場が_____されました。', '閉鎖', 'generated' from jp_vocab where id = 'e3019dc6-c511-4c51-a24d-2f83e35f6a1a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"密閉" có nghĩa là gì?', 'Kín mít, niêm phong', 'Sự tổ chức, tổ chức', 'Sự mở cửa; sự tự do hóa', 'Cải cách', 'Kín mít, niêm phong', 'generated' from jp_vocab where id = 'aa394ac5-ff75-4033-922c-b7bd0f512200';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Kín mít, niêm phong"?', '改善', '一人前', '密閉', '一方', '密閉', 'generated' from jp_vocab where id = 'aa394ac5-ff75-4033-922c-b7bd0f512200';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"密閉" đọc là gì?', 'かいぎょう', 'かいさい', 'みっぺい', 'かいほう', 'みっぺい', 'generated' from jp_vocab where id = 'aa394ac5-ff75-4033-922c-b7bd0f512200';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 容器を_____します。', '密閉', 'generated' from jp_vocab where id = 'aa394ac5-ff75-4033-922c-b7bd0f512200';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"増税" có nghĩa là gì?', 'Sự giảm sút, sự suy yếu', 'Sự tăng về lượng', 'Sự tăng thuế', 'Sự nhất trí, sự giống nhau, sự thống nhất', 'Sự tăng thuế', 'generated' from jp_vocab where id = 'dfe34827-28fc-419a-bf42-b1694dafb405';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự tăng thuế"?', '増税', '減点', '増量', '開発', '増税', 'generated' from jp_vocab where id = 'dfe34827-28fc-419a-bf42-b1694dafb405';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"増税" đọc là gì?', 'ぞうぜい', 'かいしゅう', 'かいりょう', 'かいぎょう', 'ぞうぜい', 'generated' from jp_vocab where id = 'dfe34827-28fc-419a-bf42-b1694dafb405';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 来年から_____されます。', '増税', 'generated' from jp_vocab where id = 'dfe34827-28fc-419a-bf42-b1694dafb405';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"増大" có nghĩa là gì?', 'Sự mở cửa hàng', 'Giảm điểm số', 'Sự phong bế; sự phong tỏa', 'Sự tăng về lượng', 'Sự tăng về lượng', 'generated' from jp_vocab where id = 'd6cc805a-977a-4d2d-8ed9-cc72891bbe0e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự tăng về lượng"?', '閉鎖', '減退', '増大', '増量', '増大', 'generated' from jp_vocab where id = 'd6cc805a-977a-4d2d-8ed9-cc72891bbe0e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"増大" đọc là gì?', 'ぞうだい', 'みっぺい', 'かいぎょう', 'かいりょう', 'ぞうだい', 'generated' from jp_vocab where id = 'd6cc805a-977a-4d2d-8ed9-cc72891bbe0e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 需要が_____しています。', '増大', 'generated' from jp_vocab where id = 'd6cc805a-977a-4d2d-8ed9-cc72891bbe0e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"増員" có nghĩa là gì?', 'Sự cải thiện', 'Tăng số lượng người', 'Cố định, nhất định', 'Giảm cân, giảm trọng lượng', 'Tăng số lượng người', 'generated' from jp_vocab where id = 'd45ba090-f954-472c-81ec-26c1771c3cb5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Tăng số lượng người"?', '開放', '一流', '増員', '減量', '増員', 'generated' from jp_vocab where id = 'd45ba090-f954-472c-81ec-26c1771c3cb5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"増員" đọc là gì?', 'いちりゅう', 'げんりょう', 'ぞういん', 'ぞうだい', 'ぞういん', 'generated' from jp_vocab where id = 'd45ba090-f954-472c-81ec-26c1771c3cb5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: スタッフを_____しました。', '増員', 'generated' from jp_vocab where id = 'd45ba090-f954-472c-81ec-26c1771c3cb5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"増量" có nghĩa là gì?', 'Sự thay đổi, sự chỉnh sửa', 'Sự giảm sút, sự suy yếu', 'Sự tăng thêm', 'Hạng nhất, hàng đầu, cao cấp', 'Sự tăng thêm', 'generated' from jp_vocab where id = '90fbc135-18af-418d-923b-b8b31262773c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự tăng thêm"?', '閉鎖', '改革', '改善', '増量', '増量', 'generated' from jp_vocab where id = '90fbc135-18af-418d-923b-b8b31262773c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"増量" đọc là gì?', 'かいぜん', 'かいはつ', 'へいさ', 'ぞうりょう', 'ぞうりょう', 'generated' from jp_vocab where id = '90fbc135-18af-418d-923b-b8b31262773c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 今だけ_____サービス中です。', '増量', 'generated' from jp_vocab where id = '90fbc135-18af-418d-923b-b8b31262773c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"減量" có nghĩa là gì?', 'Sự tăng thuế', 'Người trưởng thành, khẩu phần một người', 'Sự nhất trí, sự giống nhau, sự thống nhất', 'Giảm cân, giảm trọng lượng', 'Giảm cân, giảm trọng lượng', 'generated' from jp_vocab where id = '8f12b7a3-c1d2-4bd3-a1ab-07dbc95cd584';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Giảm cân, giảm trọng lượng"?', '改正', '減量', '密閉', '改革', '減量', 'generated' from jp_vocab where id = '8f12b7a3-c1d2-4bd3-a1ab-07dbc95cd584';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"減量" đọc là gì?', 'かいりょう', 'げんりょう', 'かいぜん', 'げんたい', 'げんりょう', 'generated' from jp_vocab where id = '8f12b7a3-c1d2-4bd3-a1ab-07dbc95cd584';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 健康のために_____します。', '減量', 'generated' from jp_vocab where id = '8f12b7a3-c1d2-4bd3-a1ab-07dbc95cd584';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"減点" có nghĩa là gì?', 'Sự cải thiện', 'Sự mở cửa hàng', 'Tăng số lượng người', 'Giảm điểm số', 'Giảm điểm số', 'generated' from jp_vocab where id = 'ad586e19-6edd-4175-a768-fcd291018b0b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Giảm điểm số"?', '開業', '減点', '改定', '開発', '減点', 'generated' from jp_vocab where id = 'ad586e19-6edd-4175-a768-fcd291018b0b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"減点" đọc là gì?', 'げんてん', 'へいさ', 'いってい', 'いっち', 'げんてん', 'generated' from jp_vocab where id = 'ad586e19-6edd-4175-a768-fcd291018b0b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: ミスがあると_____されます。', '減点', 'generated' from jp_vocab where id = 'ad586e19-6edd-4175-a768-fcd291018b0b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"減退" có nghĩa là gì?', 'Tăng số lượng người', 'Sự giảm sút, sự suy yếu', 'Cố định, nhất định', 'Sự thay đổi, sự chỉnh sửa', 'Sự giảm sút, sự suy yếu', 'generated' from jp_vocab where id = 'cfbde97e-9017-4f82-b4bc-6b729800fe2c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự giảm sút, sự suy yếu"?', '改善', '開放', '改修', '減退', '減退', 'generated' from jp_vocab where id = 'cfbde97e-9017-4f82-b4bc-6b729800fe2c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"減退" đọc là gì?', 'いちりゅう', 'げんたい', 'ぞうだい', 'かいりょう', 'げんたい', 'generated' from jp_vocab where id = 'cfbde97e-9017-4f82-b4bc-6b729800fe2c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 食欲が_____しました。', '減退', 'generated' from jp_vocab where id = 'cfbde97e-9017-4f82-b4bc-6b729800fe2c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"一流" có nghĩa là gì?', 'Sự mở cửa; sự tự do hóa', 'Sự tăng về lượng', 'Sự giảm sút, sự suy yếu', 'Hạng nhất, hàng đầu, cao cấp', 'Hạng nhất, hàng đầu, cao cấp', 'generated' from jp_vocab where id = '8c9d966b-28a8-4809-a412-77808ba7c484';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Hạng nhất, hàng đầu, cao cấp"?', '一流', '改定', '改善', '増大', '一流', 'generated' from jp_vocab where id = '8c9d966b-28a8-4809-a412-77808ba7c484';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"一流" đọc là gì?', 'いちにんまえ', 'かいさい', 'いちりゅう', 'げんりょう', 'いちりゅう', 'generated' from jp_vocab where id = '8c9d966b-28a8-4809-a412-77808ba7c484';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____のホテルに泊まりました。', '一流', 'generated' from jp_vocab where id = '8c9d966b-28a8-4809-a412-77808ba7c484';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"一定" có nghĩa là gì?', 'Cố định, nhất định', 'Sự phát triển', 'Giảm điểm số', 'Sự tăng thêm', 'Cố định, nhất định', 'generated' from jp_vocab where id = 'ef1c02b5-6cf0-4e91-9093-9fe90eb6adb5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Cố định, nhất định"?', '開店', '一定', '改修', '減量', '一定', 'generated' from jp_vocab where id = 'ef1c02b5-6cf0-4e91-9093-9fe90eb6adb5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"一定" đọc là gì?', 'いってい', 'げんてん', 'いちりゅう', 'ぞうだい', 'いってい', 'generated' from jp_vocab where id = 'ef1c02b5-6cf0-4e91-9093-9fe90eb6adb5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____のルールを守ります。', '一定', 'generated' from jp_vocab where id = 'ef1c02b5-6cf0-4e91-9093-9fe90eb6adb5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"一致" có nghĩa là gì?', 'Cố định, nhất định', 'Sự nhất trí, sự giống nhau, sự thống nhất', 'Sự mở cửa hàng', 'Sự thay đổi, sự chỉnh sửa', 'Sự nhất trí, sự giống nhau, sự thống nhất', 'generated' from jp_vocab where id = '565a4869-0939-40e4-87b3-6ce4bd8c78be';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sự nhất trí, sự giống nhau, sự thống nhất"?', '増員', '一方', '開放', '一致', '一致', 'generated' from jp_vocab where id = '565a4869-0939-40e4-87b3-6ce4bd8c78be';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"一致" đọc là gì?', 'かいはつ', 'いちりゅう', 'いっち', 'いちにんまえ', 'いっち', 'generated' from jp_vocab where id = '565a4869-0939-40e4-87b3-6ce4bd8c78be';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 意見が_____しました。', '一致', 'generated' from jp_vocab where id = '565a4869-0939-40e4-87b3-6ce4bd8c78be';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"一方" có nghĩa là gì?', 'Cải cách', 'Sự cải thiện', 'Sự giảm sút, sự suy yếu', 'Một mặt, mặt khác', 'Một mặt, mặt khác', 'generated' from jp_vocab where id = '7df6aae1-3034-4b22-b106-a6cf8da109cb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Một mặt, mặt khác"?', '開催', '改修', '開発', '一方', '一方', 'generated' from jp_vocab where id = '7df6aae1-3034-4b22-b106-a6cf8da109cb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"一方" đọc là gì?', 'いっぽう', 'げんたい', 'かいしゅう', 'かいさい', 'いっぽう', 'generated' from jp_vocab where id = '7df6aae1-3034-4b22-b106-a6cf8da109cb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で問題も残っています。', '一方', 'generated' from jp_vocab where id = '7df6aae1-3034-4b22-b106-a6cf8da109cb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"一人前" có nghĩa là gì?', 'Người trưởng thành, khẩu phần một người', 'Sự mở cửa hàng', 'Sự giảm sút, sự suy yếu', 'Sự nhất trí, sự giống nhau, sự thống nhất', 'Người trưởng thành, khẩu phần một người', 'generated' from jp_vocab where id = 'cb85e15a-00c5-43fe-a0b8-ce8ca3edb823';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Người trưởng thành, khẩu phần một người"?', '改善', '一人前', '開発', '減点', '一人前', 'generated' from jp_vocab where id = 'cb85e15a-00c5-43fe-a0b8-ce8ca3edb823';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"一人前" đọc là gì?', 'かいほう', 'いちにんまえ', 'げんてん', 'かいてい', 'いちにんまえ', 'generated' from jp_vocab where id = 'cb85e15a-00c5-43fe-a0b8-ce8ca3edb823';
insert into jp_vocab_questions (vocab_id, question_type, question_text, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 彼は_____の職人になりました。', '一人前', 'generated' from jp_vocab where id = 'cb85e15a-00c5-43fe-a0b8-ce8ca3edb823';

-- Tổng 100 câu hỏi generated cho 25 từ nhóm まとめ.

