-- ============================================================
-- jp-go — Ngữ pháp N2, round 1 (PILOT — 9 mẫu, trang in 63).
-- Nguồn: PDF "Tổng hợp kiến thức N2" (Dũng Mori), PART 3 - 文法.
-- Mẫu nhiều usage (Vていく/てくる: 5, だけに: 2) tách bảng
-- jp_grammar_usages theo đúng thiết kế schema. Mỗi usage đủ 3 ví
-- dụ (1 từ PDF + 2 tự soạn). Bài tập 100% generated (PDF không có
-- phần 問題 cho Ngữ pháp).
-- ============================================================

-- ---------- jp_grammar ----------
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('57723ef9-94a0-443b-ae2c-14018b133558', 'N2', 'Aい／Aな／Vたい ＋ げ', 'Trông có vẻ... (dựa trên biểu hiện/ấn tượng bên ngoài)', NULL, 'Aい(bỏ い)／Aな(bỏ な)／Vたい(bỏ い) ＋ げ', 'Diễn tả ấn tượng/vẻ ngoài trông có vẻ như thế nào, hay dùng cho tính từ chỉ cảm xúc/trạng thái', NULL, NULL, NULL, '{}', NULL, 63, 'Aい／Aな／Vたい ＋ げ', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('62cc1680-aeca-4531-9946-53d98465573e', 'N2', '普通形 ＋ とか', 'Thấy bảo hình như là... (nghe nói, truyền đạt lại thông tin không chắc chắn)', NULL, '普通形 ＋ とか', 'Truyền đạt lại thông tin nghe được từ người khác mà bản thân không chắc chắn', NULL, NULL, NULL, '{}', NULL, 63, '普通形 ＋ とか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('8c2610ae-dde7-428c-baaa-048775750da1', 'N2', 'Vていく／Vてくる', '① Diễn tả hành động rồi tiếp tục diễn biến/di chuyển xa dần　② Diễn tả trạng thái/hành động đã diễn ra liên tục đến hiện tại　③ Diễn tả sự thay đổi dần dần của 1 trạng thái mới　④ Chỉ hướng của hành động từ điểm nhìn người nói　⑤ Diễn tả sự xuất hiện bất ngờ của 1 trạng thái mới', NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 63, 'Vていく／Vてくる', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('1c7b18c3-a86b-4008-860f-4ed2da58fa5a', 'N2', 'Vます ＋ がたい', 'Không thể nào mà.../Khó mà... (khó có thể làm được vì lý do tâm lý/tình cảm)', NULL, 'Vます(bỏ ます) ＋ がたい', 'Diễn tả việc rất khó/không thể làm được điều gì đó', NULL, NULL, NULL, '{}', NULL, 63, 'Vます ＋ がたい', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('caf38505-7fb3-485d-a470-f967b9cdc8fe', 'N2', 'Vた ＋ かと思うと／かと思ったら', 'Vừa mới... đã ngay lập tức...', NULL, 'Vた ＋ かと思うと／かと思ったら', 'Diễn tả 2 sự việc xảy ra liên tiếp nhau gần như ngay lập tức, thường mang sắc thái bất ngờ', NULL, NULL, NULL, '{}', NULL, 63, 'Vた ＋ かと思うと／かと思ったら', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('1c83676e-9dcb-4f8d-b465-21a043e1dae8', 'N2', 'Vる／Vた ＋ か＋Vない＋かのうちに', 'Ngay khi vừa mới...thì... (chưa rõ đã xong hay chưa đã xảy ra việc tiếp theo)', NULL, 'Vる／Vた ＋ か ＋ Vない ＋ かのうちに', 'Diễn tả việc thứ 2 xảy ra ngay khi việc thứ nhất còn chưa hoàn tất rõ ràng', NULL, NULL, NULL, '{}', NULL, 63, 'Vる／Vた ＋ か＋Vない＋かのうちに', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('5a93a38b-2f49-48b7-82c4-54a19a048d2e', 'N2', 'V普通形／Aな／N(である) ＋ だけあって', 'Quả nhiên là vì... nên (khen ngợi kết quả tương xứng với nguyên nhân/nỗ lực/địa vị đã nêu)', NULL, 'V普通形／Aな／N(である) ＋ だけあって', 'Đánh giá 1 kết quả là hợp lý/tương xứng dựa trên lý do đã nêu', NULL, NULL, NULL, '{}', NULL, 63, 'V普通形／Aな／N(である) ＋ だけあって', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', 'N2', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', '① Chính bởi... thế nên là...　② Chính bởi...nên lại càng...', NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 63, 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('367824bf-c6e3-4e63-b45a-74e2a620a9e3', 'N2', 'Vば／Aければ／Aなであれば／Nであれば ＋ こそ', 'Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)', NULL, 'Vば／Aければ／Aなであれば／Nであれば ＋ こそ', 'Nhấn mạnh rằng chính lý do/điều kiện đã nêu mới là nguyên nhân thực sự dẫn đến vế sau', NULL, NULL, NULL, '{}', NULL, 63, 'Vば／Aければ／Aなであれば／Nであれば ＋ こそ', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;

-- ---------- jp_grammar_usages (chỉ mẫu nhiều usage) ----------
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('c90c4dc8-6ce8-4457-8c5b-93d644f4d918', '8c2610ae-dde7-428c-baaa-048775750da1', 1, 'Làm hành động gì đó rồi di chuyển đến đâu đó (diễn biến xa dần theo thời gian)', 'Vて ＋ いく', 'Diễn tả hành động/xu hướng sẽ tiếp tục diễn ra/lan rộng trong tương lai', NULL, 63, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('9627836e-7014-45ab-a897-701f797475fd', '8c2610ae-dde7-428c-baaa-048775750da1', 2, 'Diễn tả trạng thái/hành động đã diễn ra liên tục cho tới thời điểm nói', 'Vて ＋ きた', 'Kể lại 1 việc đã hoàn thành/trải qua trước khi quay về hiện tại', NULL, 63, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('5ba014bf-98b9-4883-a5b9-9dfabb1c608a', '8c2610ae-dde7-428c-baaa-048775750da1', 3, 'Diễn tả sự thay đổi dần dần sang 1 trạng thái mới', 'Vて ＋ きた', 'Miêu tả 1 trạng thái đang dần hình thành/thay đổi tính đến thời điểm nói', NULL, 63, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('56ee71dd-d5d4-4864-9a65-19c0eb8dc1bb', '8c2610ae-dde7-428c-baaa-048775750da1', 4, 'Chỉ hướng của hành động hướng về phía người nói/điểm quan sát', 'Vて ＋ きた', 'Diễn tả hành động di chuyển/tiếp diễn về phía người nói hoặc về hiện tại', NULL, 63, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('41190dd9-2941-4c3d-88ab-c213102bc4a5', '8c2610ae-dde7-428c-baaa-048775750da1', 5, 'Diễn tả sự xuất hiện bất ngờ của 1 trạng thái/cảm giác mới', 'Vて ＋ きた', 'Diễn tả 1 hiện tượng/cảm giác bắt đầu xuất hiện', NULL, 63, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('2475d51d-406b-4f06-a10b-b5f05b7d0d18', 'ea139d2d-1294-44e3-bf4d-1c417ee37d73', 1, 'Chính bởi lý do đã nêu, thế nên dẫn đến kết quả/tâm trạng như vậy', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'Nêu lý do rồi diễn giải kết quả/cảm xúc hợp lý xuất phát từ chính lý do đó', NULL, 63, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('6dc30eac-8539-458d-8d10-23cc708cc1fa', 'ea139d2d-1294-44e3-bf4d-1c417ee37d73', 2, 'Chính bởi đã nỗ lực/kỳ vọng thế nào đó, nên cảm xúc/kết quả trái ngược lại càng mạnh hơn', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'Nhấn mạnh mức độ cảm xúc (thường tiêu cực) tăng lên do đã bỏ công sức/kỳ vọng trước đó', NULL, 63, 'pdf');

-- ---------- jp_grammar_examples ----------
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('57723ef9-94a0-443b-ae2c-14018b133558', NULL, 1, 'standard', '彼は先生に対し何か言いたげな様子であった。', 'Anh ấy có vẻ đang muốn nói gì đó với giáo viên.', '彼は先生に対し何か言い＿＿＿な様子であった。', 'たげ', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('57723ef9-94a0-443b-ae2c-14018b133558', NULL, 2, 'daily', '彼女は嬉しげな顔をしている。', 'Cô ấy có vẻ mặt vui vẻ.', '彼女は嬉し＿＿＿な顔をしている。', 'げ', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('57723ef9-94a0-443b-ae2c-14018b133558', NULL, 3, 'daily', '子供は眠たげにあくびをした。', 'Đứa trẻ ngáp một cách có vẻ buồn ngủ.', '子供は眠た＿＿＿にあくびをした。', 'げ', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('62cc1680-aeca-4531-9946-53d98465573e', NULL, 1, 'standard', '最近は若者にタピオカという飲み物が人気だとか。', 'Nghe nói dạo này giới trẻ đang chuộng loại đồ uống tên là trân châu.', '最近は若者にタピオカという飲み物が人気＿＿＿。', 'だとか', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('62cc1680-aeca-4531-9946-53d98465573e', NULL, 2, 'daily', '彼は来月結婚するとか。', 'Nghe nói anh ấy sẽ kết hôn vào tháng sau.', '彼は来月結婚する＿＿＿。', 'とか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('62cc1680-aeca-4531-9946-53d98465573e', NULL, 3, 'daily', 'あの店のラーメンはとても美味しいとか。', 'Nghe nói mì ramen của quán đó rất ngon.', 'あの店のラーメンはとても美味しい＿＿＿。', 'とか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', 'c90c4dc8-6ce8-4457-8c5b-93d644f4d918', 1, 'standard', 'これから、日本語を勉強するベトナム人が増えていくだろう。', 'Có lẽ là từ giờ trở đi người Việt Nam học tiếng Nhật sẽ ngày càng tăng lên.', 'これから、日本語を勉強するベトナム人が増え＿＿＿だろう。', 'ていく', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', 'c90c4dc8-6ce8-4457-8c5b-93d644f4d918', 2, 'daily', '環境問題はこれからますます深刻になっていくでしょう。', 'Vấn đề môi trường từ giờ chắc sẽ ngày càng nghiêm trọng hơn.', '環境問題はこれからますます深刻になっ＿＿＿でしょう。', 'ていく', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', 'c90c4dc8-6ce8-4457-8c5b-93d644f4d918', 3, 'daily', '子供たちはこれから大きく成長していく。', 'Những đứa trẻ từ giờ sẽ lớn lên.', '子供たちはこれから大きく成長し＿＿＿。', 'ていく', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '9627836e-7014-45ab-a897-701f797475fd', 1, 'standard', '今日は、仕事の後飲み会に行ってきた。', 'Hôm nay, sau giờ làm tôi đã đi nhậu rồi mới về.', '今日は、仕事の後飲み会に行っ＿＿＿。', 'てきた', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '9627836e-7014-45ab-a897-701f797475fd', 2, 'daily', '彼は長い間この会社で働いてきた。', 'Anh ấy đã làm việc ở công ty này trong một thời gian dài.', '彼は長い間この会社で働い＿＿＿。', 'てきた', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '9627836e-7014-45ab-a897-701f797475fd', 3, 'daily', '私たちはずっと友達として付き合ってきた。', 'Chúng tôi đã luôn gắn bó với nhau như bạn bè.', '私たちはずっと友達として付き合っ＿＿＿。', 'てきた', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '5ba014bf-98b9-4883-a5b9-9dfabb1c608a', 1, 'standard', '公園で友達と遊んでいたら、母が声をかけてきた。', 'Khi tôi đang chơi với bạn ở công viên, mẹ đã gọi tôi.', '公園で友達と遊んでいたら、母が声をかけ＿＿＿。', 'てきた', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '5ba014bf-98b9-4883-a5b9-9dfabb1c608a', 2, 'daily', '空が急に暗くなってきた。', 'Bầu trời đột nhiên tối sầm lại.', '空が急に暗くなっ＿＿＿。', 'てきた', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '5ba014bf-98b9-4883-a5b9-9dfabb1c608a', 3, 'daily', 'だんだん寒くなってきたので、コートを着た。', 'Vì trời dần trở lạnh nên tôi đã mặc áo khoác.', 'だんだん寒くなっ＿＿＿ので、コートを着た。', 'てきた', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '56ee71dd-d5d4-4864-9a65-19c0eb8dc1bb', 1, 'standard', '私は、3歳の頃からバイオリンを習ってきた。', 'Tôi đã học violin từ năm 3 tuổi tới bây giờ.', '私は、3歳の頃からバイオリンを習っ＿＿＿。', 'てきた', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '56ee71dd-d5d4-4864-9a65-19c0eb8dc1bb', 2, 'daily', '田中さんがこちらに向かって歩いてきた。', 'Anh Tanaka đã đi bộ về phía này.', '田中さんがこちらに向かって歩い＿＿＿。', 'てきた', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '56ee71dd-d5d4-4864-9a65-19c0eb8dc1bb', 3, 'daily', '猫が私の方に走ってきた。', 'Con mèo đã chạy về phía tôi.', '猫が私の方に走っ＿＿＿。', 'てきた', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '41190dd9-2941-4c3d-88ab-c213102bc4a5', 1, 'standard', 'お腹に子どもができてきたら、心配事が出てきた。', 'Những nỗi lo lắng bắt đầu xuất hiện kể từ khi cô ấy mang bầu.', 'お腹に子どもができてきたら、心配事が出＿＿＿。', 'てきた', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '41190dd9-2941-4c3d-88ab-c213102bc4a5', 2, 'daily', '最近、頭痛がしてきた。', 'Gần đây, tôi bắt đầu bị đau đầu.', '最近、頭痛がし＿＿＿。', 'てきた', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '41190dd9-2941-4c3d-88ab-c213102bc4a5', 3, 'daily', '夜になって、雨が降ってきた。', 'Khi trời tối, mưa bắt đầu rơi.', '夜になって、雨が降っ＿＿＿。', 'てきた', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('1c7b18c3-a86b-4008-860f-4ed2da58fa5a', NULL, 1, 'standard', 'この番組は、間違った情報を発信しているので信じがたい。', 'Chương trình truyền hình này đưa những thông tin sai lệch nên khó mà tin được.', 'この番組は、間違った情報を発信しているので信じ＿＿＿。', 'がたい', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('1c7b18c3-a86b-4008-860f-4ed2da58fa5a', NULL, 2, 'daily', '彼の言うことは理解しがたい。', 'Lời nói của anh ấy thật khó mà hiểu được.', '彼の言うことは理解し＿＿＿。', 'がたい', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('1c7b18c3-a86b-4008-860f-4ed2da58fa5a', NULL, 3, 'daily', 'その事実は受け入れがたいものだった。', 'Sự thật đó là điều khó mà chấp nhận được.', 'その事実は受け入れ＿＿＿ものだった。', 'がたい', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('caf38505-7fb3-485d-a470-f967b9cdc8fe', NULL, 1, 'standard', '仕事が一段落したかと思うと、またすぐに別の仕事を任された。', 'Vừa xong công việc này thì lại bị giao công việc khác ngay.', '仕事が一段落した＿＿＿、またすぐに別の仕事を任された。', 'かと思うと', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('caf38505-7fb3-485d-a470-f967b9cdc8fe', NULL, 2, 'daily', '子供は泣いたかと思うと、すぐに笑い出した。', 'Đứa trẻ vừa mới khóc thì đã cười ngay lập tức.', '子供は泣いた＿＿＿、すぐに笑い出した。', 'かと思うと', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('caf38505-7fb3-485d-a470-f967b9cdc8fe', NULL, 3, 'daily', '空が晴れたかと思ったら、また雨が降り出した。', 'Trời vừa mới hửng nắng thì lại bắt đầu mưa.', '空が晴れた＿＿＿、また雨が降り出した。', 'かと思ったら', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('1c83676e-9dcb-4f8d-b465-21a043e1dae8', NULL, 1, 'standard', '息子はベッドに入るか入らないかのうちに寝てしまった。', 'Con tôi vừa mới vào giường đã ngủ mất rồi.', '息子はベッドに入る＿＿＿寝てしまった。', 'か入らないかのうちに', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('1c83676e-9dcb-4f8d-b465-21a043e1dae8', NULL, 2, 'daily', '電車のドアが閉まるか閉まらないかのうちに、彼は飛び乗った。', 'Ngay khi cửa tàu điện còn chưa kịp đóng hẳn, anh ấy đã nhảy lên.', '電車のドアが閉まる＿＿＿、彼は飛び乗った。', 'か閉まらないかのうちに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('1c83676e-9dcb-4f8d-b465-21a043e1dae8', NULL, 3, 'daily', '授業が始まるか始まらないかのうちに、彼は教室を出て行った。', 'Ngay khi giờ học vừa mới bắt đầu, anh ấy đã ra khỏi lớp.', '授業が始まる＿＿＿、彼は教室を出て行った。', 'か始まらないかのうちに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('5a93a38b-2f49-48b7-82c4-54a19a048d2e', NULL, 1, 'standard', '10年日本に住んでるだけあって、発音がとても自然だ。', 'Quả đã sống ở Nhật 10 năm rồi nên phát âm rất tự nhiên.', '10年日本に住んでる＿＿＿、発音がとても自然だ。', 'だけあって', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('5a93a38b-2f49-48b7-82c4-54a19a048d2e', NULL, 2, 'daily', '彼はプロの選手だけあって、動きが速い。', 'Quả là vận động viên chuyên nghiệp nên động tác rất nhanh.', '彼はプロの選手＿＿＿、動きが速い。', 'だけあって', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('5a93a38b-2f49-48b7-82c4-54a19a048d2e', NULL, 3, 'daily', '高級レストランだけあって、料理がとても美味しい。', 'Quả là nhà hàng cao cấp nên món ăn rất ngon.', '高級レストラン＿＿＿、料理がとても美味しい。', 'だけあって', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', '2475d51d-406b-4f06-a10b-b5f05b7d0d18', 1, 'standard', 'この物件は、安いだけに何かあるのではないかと不安になる。', 'Cái toà nhà này chính vì rẻ nên tôi cảm thấy bất an không biết có điều gì không ổn.', 'この物件は、安い＿＿＿何かあるのではないかと不安になる。', 'だけに', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', '2475d51d-406b-4f06-a10b-b5f05b7d0d18', 2, 'daily', '彼は経験が豊富なだけに、対応が早い。', 'Chính vì anh ấy nhiều kinh nghiệm nên xử lý rất nhanh.', '彼は経験が豊富な＿＿＿、対応が早い。', 'だけに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', '2475d51d-406b-4f06-a10b-b5f05b7d0d18', 3, 'daily', '有名な店だけに、いつも混んでいる。', 'Chính vì là quán nổi tiếng nên lúc nào cũng đông.', '有名な店＿＿＿、いつも混んでいる。', 'だけに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', '6dc30eac-8539-458d-8d10-23cc708cc1fa', 1, 'standard', '一生懸命練習しただけに試合で負けたことは大変ショックだった。', 'Chính bởi tôi đã luyện tập hết mình nên việc thua ở trận đấu lại càng làm tôi sốc.', '一生懸命練習した＿＿＿試合で負けたことは大変ショックだった。', 'だけに', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', '6dc30eac-8539-458d-8d10-23cc708cc1fa', 2, 'daily', '頑張って勉強しただけに、試験に落ちてとても悔しい。', 'Chính vì đã cố gắng học hành nên trượt kỳ thi lại càng cảm thấy tiếc nuối.', '頑張って勉強した＿＿＿、試験に落ちてとても悔しい。', 'だけに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', '6dc30eac-8539-458d-8d10-23cc708cc1fa', 3, 'daily', '期待していただけに、失望も大きかった。', 'Chính vì đã kỳ vọng nhiều nên thất vọng cũng lớn hơn.', '期待していた＿＿＿、失望も大きかった。', 'だけに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('367824bf-c6e3-4e63-b45a-74e2a620a9e3', NULL, 1, 'standard', '忙しければこそ、自分で工夫して時間を作る。', 'Chính vì bận rộn nên tôi phải tự mình tỉ mỉ phân chia thời gian.', '忙し＿＿＿、自分で工夫して時間を作る。', 'ければこそ', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('367824bf-c6e3-4e63-b45a-74e2a620a9e3', NULL, 2, 'daily', '愛していればこそ、厳しいことも言える。', 'Chính vì yêu thương nên mới có thể nói những điều nghiêm khắc.', '愛して＿＿＿、厳しいことも言える。', 'いればこそ', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('367824bf-c6e3-4e63-b45a-74e2a620a9e3', NULL, 3, 'daily', '若ければこそ、いろいろな挑戦ができる。', 'Chính vì còn trẻ nên mới có thể thử thách nhiều điều.', '若＿＿＿、いろいろな挑戦ができる。', 'ければこそ', 'generated');

-- ---------- jp_grammar_questions: generated (fill_blank/choose_meaning/choose_connection) ----------
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('57723ef9-94a0-443b-ae2c-14018b133558', NULL, 'fill_blank', 'Điền vào chỗ trống: 彼は先生に対し何か言い＿＿＿な様子であった。', 'たげ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('57723ef9-94a0-443b-ae2c-14018b133558', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Aい／Aな／Vたい ＋ げ" (usage này) có nghĩa là gì?', 'Quả nhiên là vì... nên (khen ngợi kết quả tương xứng với nguyên nhân/nỗ lực/địa vị đã nêu)', 'Thấy bảo hình như là... (nghe nói, truyền đạt lại thông tin không chắc chắn)', 'Trông có vẻ... (dựa trên biểu hiện/ấn tượng bên ngoài)', 'Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)', 'Trông có vẻ... (dựa trên biểu hiện/ấn tượng bên ngoài)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('57723ef9-94a0-443b-ae2c-14018b133558', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Trông có vẻ... (dựa trên biểu hiện/ấn tượng bên ngoài)"?', 'Vる／Vた ＋ か＋Vない＋かのうちに', 'Vます ＋ がたい', 'Aい／Aな／Vたい ＋ げ', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'Aい／Aな／Vたい ＋ げ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('62cc1680-aeca-4531-9946-53d98465573e', NULL, 'fill_blank', 'Điền vào chỗ trống: 最近は若者にタピオカという飲み物が人気＿＿＿。', 'だとか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('62cc1680-aeca-4531-9946-53d98465573e', NULL, 'choose_meaning', 'Mẫu ngữ pháp "普通形 ＋ とか" (usage này) có nghĩa là gì?', '① Diễn tả hành động rồi tiếp tục diễn biến/di chuyển xa dần　② Diễn tả trạng thái/hành động đã diễn ra liên tục đến hiện tại　③ Diễn tả sự thay đổi dần dần của 1 trạng thái mới　④ Chỉ hướng của hành động từ điểm nhìn người nói　⑤ Diễn tả sự xuất hiện bất ngờ của 1 trạng thái mới', 'Vừa mới... đã ngay lập tức...', 'Thấy bảo hình như là... (nghe nói, truyền đạt lại thông tin không chắc chắn)', 'Quả nhiên là vì... nên (khen ngợi kết quả tương xứng với nguyên nhân/nỗ lực/địa vị đã nêu)', 'Thấy bảo hình như là... (nghe nói, truyền đạt lại thông tin không chắc chắn)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('62cc1680-aeca-4531-9946-53d98465573e', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Thấy bảo hình như là... (nghe nói, truyền đạt lại thông tin không chắc chắn)"?', 'Vば／Aければ／Aなであれば／Nであれば ＋ こそ', '普通形 ＋ とか', 'Vる／Vた ＋ か＋Vない＋かのうちに', 'V普通形／Aな／N(である) ＋ だけあって', '普通形 ＋ とか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', 'c90c4dc8-6ce8-4457-8c5b-93d644f4d918', 'fill_blank', 'Điền vào chỗ trống: これから、日本語を勉強するベトナム人が増え＿＿＿だろう。', 'ていく', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', 'c90c4dc8-6ce8-4457-8c5b-93d644f4d918', 'choose_meaning', 'Mẫu ngữ pháp "Vていく／Vてくる" (usage này) có nghĩa là gì?', 'Vừa mới... đã ngay lập tức...', 'Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)', 'Quả nhiên là vì... nên (khen ngợi kết quả tương xứng với nguyên nhân/nỗ lực/địa vị đã nêu)', 'Làm hành động gì đó rồi di chuyển đến đâu đó (diễn biến xa dần theo thời gian)', 'Làm hành động gì đó rồi di chuyển đến đâu đó (diễn biến xa dần theo thời gian)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', 'c90c4dc8-6ce8-4457-8c5b-93d644f4d918', 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Làm hành động gì đó rồi di chuyển đến đâu đó (diễn biến xa dần theo thời gian)"?', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'Vます ＋ がたい', 'Vていく／Vてくる', 'Aい／Aな／Vたい ＋ げ', 'Vていく／Vてくる', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '9627836e-7014-45ab-a897-701f797475fd', 'fill_blank', 'Điền vào chỗ trống: 今日は、仕事の後飲み会に行っ＿＿＿。', 'てきた', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '9627836e-7014-45ab-a897-701f797475fd', 'choose_meaning', 'Mẫu ngữ pháp "Vていく／Vてくる" (usage này) có nghĩa là gì?', 'Trông có vẻ... (dựa trên biểu hiện/ấn tượng bên ngoài)', 'Diễn tả trạng thái/hành động đã diễn ra liên tục cho tới thời điểm nói', 'Vừa mới... đã ngay lập tức...', 'Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)', 'Diễn tả trạng thái/hành động đã diễn ra liên tục cho tới thời điểm nói', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '9627836e-7014-45ab-a897-701f797475fd', 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Diễn tả trạng thái/hành động đã diễn ra liên tục cho tới thời điểm nói"?', 'Vていく／Vてくる', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'Vば／Aければ／Aなであれば／Nであれば ＋ こそ', 'Vます ＋ がたい', 'Vていく／Vてくる', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '5ba014bf-98b9-4883-a5b9-9dfabb1c608a', 'fill_blank', 'Điền vào chỗ trống: 公園で友達と遊んでいたら、母が声をかけ＿＿＿。', 'てきた', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '5ba014bf-98b9-4883-a5b9-9dfabb1c608a', 'choose_meaning', 'Mẫu ngữ pháp "Vていく／Vてくる" (usage này) có nghĩa là gì?', '① Chính bởi... thế nên là...　② Chính bởi...nên lại càng...', 'Diễn tả sự thay đổi dần dần sang 1 trạng thái mới', 'Ngay khi vừa mới...thì... (chưa rõ đã xong hay chưa đã xảy ra việc tiếp theo)', 'Vừa mới... đã ngay lập tức...', 'Diễn tả sự thay đổi dần dần sang 1 trạng thái mới', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '5ba014bf-98b9-4883-a5b9-9dfabb1c608a', 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Diễn tả sự thay đổi dần dần sang 1 trạng thái mới"?', '普通形 ＋ とか', 'Aい／Aな／Vたい ＋ げ', 'Vていく／Vてくる', 'Vた ＋ かと思うと／かと思ったら', 'Vていく／Vてくる', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '56ee71dd-d5d4-4864-9a65-19c0eb8dc1bb', 'fill_blank', 'Điền vào chỗ trống: 私は、3歳の頃からバイオリンを習っ＿＿＿。', 'てきた', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '56ee71dd-d5d4-4864-9a65-19c0eb8dc1bb', 'choose_meaning', 'Mẫu ngữ pháp "Vていく／Vてくる" (usage này) có nghĩa là gì?', 'Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)', 'Chỉ hướng của hành động hướng về phía người nói/điểm quan sát', 'Trông có vẻ... (dựa trên biểu hiện/ấn tượng bên ngoài)', 'Quả nhiên là vì... nên (khen ngợi kết quả tương xứng với nguyên nhân/nỗ lực/địa vị đã nêu)', 'Chỉ hướng của hành động hướng về phía người nói/điểm quan sát', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '56ee71dd-d5d4-4864-9a65-19c0eb8dc1bb', 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Chỉ hướng của hành động hướng về phía người nói/điểm quan sát"?', 'Vていく／Vてくる', 'Vる／Vた ＋ か＋Vない＋かのうちに', 'Vば／Aければ／Aなであれば／Nであれば ＋ こそ', 'Vた ＋ かと思うと／かと思ったら', 'Vていく／Vてくる', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '41190dd9-2941-4c3d-88ab-c213102bc4a5', 'fill_blank', 'Điền vào chỗ trống: お腹に子どもができてきたら、心配事が出＿＿＿。', 'てきた', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '41190dd9-2941-4c3d-88ab-c213102bc4a5', 'choose_meaning', 'Mẫu ngữ pháp "Vていく／Vてくる" (usage này) có nghĩa là gì?', 'Diễn tả sự xuất hiện bất ngờ của 1 trạng thái/cảm giác mới', 'Quả nhiên là vì... nên (khen ngợi kết quả tương xứng với nguyên nhân/nỗ lực/địa vị đã nêu)', 'Trông có vẻ... (dựa trên biểu hiện/ấn tượng bên ngoài)', '① Chính bởi... thế nên là...　② Chính bởi...nên lại càng...', 'Diễn tả sự xuất hiện bất ngờ của 1 trạng thái/cảm giác mới', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('8c2610ae-dde7-428c-baaa-048775750da1', '41190dd9-2941-4c3d-88ab-c213102bc4a5', 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Diễn tả sự xuất hiện bất ngờ của 1 trạng thái/cảm giác mới"?', 'Vた ＋ かと思うと／かと思ったら', 'Vば／Aければ／Aなであれば／Nであれば ＋ こそ', 'Vる／Vた ＋ か＋Vない＋かのうちに', 'Vていく／Vてくる', 'Vていく／Vてくる', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('1c7b18c3-a86b-4008-860f-4ed2da58fa5a', NULL, 'fill_blank', 'Điền vào chỗ trống: この番組は、間違った情報を発信しているので信じ＿＿＿。', 'がたい', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('1c7b18c3-a86b-4008-860f-4ed2da58fa5a', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vます ＋ がたい" (usage này) có nghĩa là gì?', 'Trông có vẻ... (dựa trên biểu hiện/ấn tượng bên ngoài)', 'Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)', 'Không thể nào mà.../Khó mà... (khó có thể làm được vì lý do tâm lý/tình cảm)', '① Diễn tả hành động rồi tiếp tục diễn biến/di chuyển xa dần　② Diễn tả trạng thái/hành động đã diễn ra liên tục đến hiện tại　③ Diễn tả sự thay đổi dần dần của 1 trạng thái mới　④ Chỉ hướng của hành động từ điểm nhìn người nói　⑤ Diễn tả sự xuất hiện bất ngờ của 1 trạng thái mới', 'Không thể nào mà.../Khó mà... (khó có thể làm được vì lý do tâm lý/tình cảm)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('1c7b18c3-a86b-4008-860f-4ed2da58fa5a', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Không thể nào mà.../Khó mà... (khó có thể làm được vì lý do tâm lý/tình cảm)"?', 'Vば／Aければ／Aなであれば／Nであれば ＋ こそ', 'Vた ＋ かと思うと／かと思ったら', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'Vます ＋ がたい', 'Vます ＋ がたい', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('caf38505-7fb3-485d-a470-f967b9cdc8fe', NULL, 'fill_blank', 'Điền vào chỗ trống: 仕事が一段落した＿＿＿、またすぐに別の仕事を任された。', 'かと思うと', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('caf38505-7fb3-485d-a470-f967b9cdc8fe', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vた ＋ かと思うと／かと思ったら" (usage này) có nghĩa là gì?', 'Vừa mới... đã ngay lập tức...', 'Thấy bảo hình như là... (nghe nói, truyền đạt lại thông tin không chắc chắn)', 'Không thể nào mà.../Khó mà... (khó có thể làm được vì lý do tâm lý/tình cảm)', '① Chính bởi... thế nên là...　② Chính bởi...nên lại càng...', 'Vừa mới... đã ngay lập tức...', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('caf38505-7fb3-485d-a470-f967b9cdc8fe', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Vừa mới... đã ngay lập tức..."?', 'Vた ＋ かと思うと／かと思ったら', 'Aい／Aな／Vたい ＋ げ', 'Vていく／Vてくる', 'Vる／Vた ＋ か＋Vない＋かのうちに', 'Vた ＋ かと思うと／かと思ったら', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('1c83676e-9dcb-4f8d-b465-21a043e1dae8', NULL, 'fill_blank', 'Điền vào chỗ trống: 息子はベッドに入る＿＿＿寝てしまった。', 'か入らないかのうちに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('1c83676e-9dcb-4f8d-b465-21a043e1dae8', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vる／Vた ＋ か＋Vない＋かのうちに" (usage này) có nghĩa là gì?', 'Không thể nào mà.../Khó mà... (khó có thể làm được vì lý do tâm lý/tình cảm)', 'Ngay khi vừa mới...thì... (chưa rõ đã xong hay chưa đã xảy ra việc tiếp theo)', 'Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)', 'Quả nhiên là vì... nên (khen ngợi kết quả tương xứng với nguyên nhân/nỗ lực/địa vị đã nêu)', 'Ngay khi vừa mới...thì... (chưa rõ đã xong hay chưa đã xảy ra việc tiếp theo)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('1c83676e-9dcb-4f8d-b465-21a043e1dae8', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Ngay khi vừa mới...thì... (chưa rõ đã xong hay chưa đã xảy ra việc tiếp theo)"?', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'Vば／Aければ／Aなであれば／Nであれば ＋ こそ', '普通形 ＋ とか', 'Vる／Vた ＋ か＋Vない＋かのうちに', 'Vる／Vた ＋ か＋Vない＋かのうちに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('5a93a38b-2f49-48b7-82c4-54a19a048d2e', NULL, 'fill_blank', 'Điền vào chỗ trống: 10年日本に住んでる＿＿＿、発音がとても自然だ。', 'だけあって', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('5a93a38b-2f49-48b7-82c4-54a19a048d2e', NULL, 'choose_meaning', 'Mẫu ngữ pháp "V普通形／Aな／N(である) ＋ だけあって" (usage này) có nghĩa là gì?', 'Thấy bảo hình như là... (nghe nói, truyền đạt lại thông tin không chắc chắn)', 'Quả nhiên là vì... nên (khen ngợi kết quả tương xứng với nguyên nhân/nỗ lực/địa vị đã nêu)', 'Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)', '① Diễn tả hành động rồi tiếp tục diễn biến/di chuyển xa dần　② Diễn tả trạng thái/hành động đã diễn ra liên tục đến hiện tại　③ Diễn tả sự thay đổi dần dần của 1 trạng thái mới　④ Chỉ hướng của hành động từ điểm nhìn người nói　⑤ Diễn tả sự xuất hiện bất ngờ của 1 trạng thái mới', 'Quả nhiên là vì... nên (khen ngợi kết quả tương xứng với nguyên nhân/nỗ lực/địa vị đã nêu)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('5a93a38b-2f49-48b7-82c4-54a19a048d2e', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Quả nhiên là vì... nên (khen ngợi kết quả tương xứng với nguyên nhân/nỗ lực/địa vị đã nêu)"?', 'Vていく／Vてくる', 'Vる／Vた ＋ か＋Vない＋かのうちに', 'V普通形／Aな／N(である) ＋ だけあって', 'Aい／Aな／Vたい ＋ げ', 'V普通形／Aな／N(である) ＋ だけあって', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', '2475d51d-406b-4f06-a10b-b5f05b7d0d18', 'fill_blank', 'Điền vào chỗ trống: この物件は、安い＿＿＿何かあるのではないかと不安になる。', 'だけに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', '2475d51d-406b-4f06-a10b-b5f05b7d0d18', 'choose_meaning', 'Mẫu ngữ pháp "V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに" (usage này) có nghĩa là gì?', 'Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)', 'Không thể nào mà.../Khó mà... (khó có thể làm được vì lý do tâm lý/tình cảm)', 'Ngay khi vừa mới...thì... (chưa rõ đã xong hay chưa đã xảy ra việc tiếp theo)', 'Chính bởi lý do đã nêu, thế nên dẫn đến kết quả/tâm trạng như vậy', 'Chính bởi lý do đã nêu, thế nên dẫn đến kết quả/tâm trạng như vậy', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', '2475d51d-406b-4f06-a10b-b5f05b7d0d18', 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Chính bởi lý do đã nêu, thế nên dẫn đến kết quả/tâm trạng như vậy"?', 'Vます ＋ がたい', '普通形 ＋ とか', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'Vた ＋ かと思うと／かと思ったら', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', '6dc30eac-8539-458d-8d10-23cc708cc1fa', 'fill_blank', 'Điền vào chỗ trống: 一生懸命練習した＿＿＿試合で負けたことは大変ショックだった。', 'だけに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', '6dc30eac-8539-458d-8d10-23cc708cc1fa', 'choose_meaning', 'Mẫu ngữ pháp "V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに" (usage này) có nghĩa là gì?', 'Vừa mới... đã ngay lập tức...', 'Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)', 'Chính bởi đã nỗ lực/kỳ vọng thế nào đó, nên cảm xúc/kết quả trái ngược lại càng mạnh hơn', 'Ngay khi vừa mới...thì... (chưa rõ đã xong hay chưa đã xảy ra việc tiếp theo)', 'Chính bởi đã nỗ lực/kỳ vọng thế nào đó, nên cảm xúc/kết quả trái ngược lại càng mạnh hơn', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ea139d2d-1294-44e3-bf4d-1c417ee37d73', '6dc30eac-8539-458d-8d10-23cc708cc1fa', 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Chính bởi đã nỗ lực/kỳ vọng thế nào đó, nên cảm xúc/kết quả trái ngược lại càng mạnh hơn"?', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'Vる／Vた ＋ か＋Vない＋かのうちに', 'Vた ＋ かと思うと／かと思ったら', 'Aい／Aな／Vたい ＋ げ', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('367824bf-c6e3-4e63-b45a-74e2a620a9e3', NULL, 'fill_blank', 'Điền vào chỗ trống: 忙し＿＿＿、自分で工夫して時間を作る。', 'ければこそ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('367824bf-c6e3-4e63-b45a-74e2a620a9e3', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vば／Aければ／Aなであれば／Nであれば ＋ こそ" (usage này) có nghĩa là gì?', '① Chính bởi... thế nên là...　② Chính bởi...nên lại càng...', 'Quả nhiên là vì... nên (khen ngợi kết quả tương xứng với nguyên nhân/nỗ lực/địa vị đã nêu)', 'Vừa mới... đã ngay lập tức...', 'Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)', 'Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('367824bf-c6e3-4e63-b45a-74e2a620a9e3', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Chính vì... nên mới... (nhấn mạnh lý do chính đáng, duy nhất dẫn đến hành động/kết quả)"?', 'V(普)／Aい(普)／Aな／Aなである／N(である) ＋ だけに', 'Vば／Aければ／Aなであれば／Nであれば ＋ こそ', 'V普通形／Aな／N(である) ＋ だけあって', '普通形 ＋ とか', 'Vば／Aければ／Aなであれば／Nであれば ＋ こそ', 'generated');

-- Tổng 42 câu hỏi generated cho 9 mẫu ngữ pháp (14 usage).
