-- ============================================================
-- jp-go — Ngữ pháp N2, round 4 (10 mẫu, trang in 66).
-- Nguồn: PDF "Tổng hợp kiến thức N2" (Dũng Mori), PART 3 - 文法.
-- Mẫu に限って và まい có 2 usage đánh số trong PDF, tách bảng
-- jp_grammar_usages. Mỗi usage đủ 3 ví dụ (1 từ PDF + 2 tự soạn).
-- Bài tập 100% generated.
-- ============================================================

-- ---------- jp_grammar ----------
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('cb50015e-0351-4bfc-bab0-047775fa7cb9', 'N2', 'Aい／Aな ＋ かぎりだ', 'Cảm thấy rất.../Vô cùng... (cảm thán về mức độ cảm xúc)', NULL, 'Aい／Aな ＋ かぎりだ', 'Nhấn mạnh mức độ cảm xúc của người nói là tối đa, cực điểm', NULL, NULL, NULL, '{}', NULL, 66, 'Aい／Aな ＋ かぎりだ', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('bd2d5467-d48e-4312-a0f7-ef714be205d1', 'N2', 'N ＋ に限らず', 'Không chỉ...mà còn... (mở rộng phạm vi ra ngoài đối tượng đã nêu)', NULL, 'N ＋ に限らず', 'Mở rộng phạm vi áp dụng ra ngoài phạm vi hẹp đã nêu ban đầu', NULL, NULL, NULL, '{}', NULL, 66, 'N ＋ に限らず', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('4083a286-805f-4145-826c-60844390fcb7', 'N2', 'Nの／Vる・Vた／Vている ＋ 限り(では)', 'Trong phạm vi.../Ở mức độ... (giới hạn phạm vi thông tin/hiểu biết của người nói)', NULL, 'Nの／Vる・Vた／Vている ＋ 限り(では)', 'Giới hạn nhận định trong phạm vi thông tin/kiến thức mà người nói biết', NULL, NULL, NULL, '{}', NULL, 66, 'Nの／Vる・Vた／Vている ＋ 限り(では)', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('8e628b6e-6c0f-4f1c-ac15-ab9ec6acac8a', 'N2', 'Aい／V(普)／Aな・である／Nである ＋ 限り(は)', 'Trong lúc.../Khi... (chừng nào điều kiện đó còn đúng)', NULL, 'Aい／V(普)／Aな・である／Nである ＋ 限り(は)', 'Diễn tả 1 điều kiện/trạng thái vẫn còn tiếp diễn thì vế sau vẫn đúng', NULL, NULL, NULL, '{}', NULL, 66, 'Aい／V(普)／Aな・である／Nである ＋ 限り(は)', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('31b43943-99e3-47de-b883-19fd196597f2', 'N2', 'N に限り、.../N に限る。', 'Chỉ trong/Chỉ đối với/Chỉ riêng ~ (giới hạn đối tượng/phạm vi được áp dụng)', NULL, 'N ＋ に限り／に限る', 'Giới hạn phạm vi áp dụng của 1 quy định/ưu đãi chỉ đúng với đối tượng đã nêu', NULL, NULL, NULL, '{}', NULL, 66, 'N に限り、.../N に限る。', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', 'N2', 'N ＋ に限って', '① Ai chứ, gì chứ ~ (tin tưởng tuyệt đối vào đối tượng)　② Đúng vào lúc ~ (trớ trêu, không may)', NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 66, 'N ＋ に限って', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('ce015143-2d0a-4c76-9c40-b4046cabbaf0', 'N2', 'Vる・ない／N ＋ に限る', '~ Là tốt nhất (khuyến nghị lựa chọn tốt nhất trong số các lựa chọn)', NULL, 'Vる・ない／N ＋ に限る', 'Đưa ra ý kiến cá nhân về lựa chọn tốt nhất nên làm trong tình huống đã nêu', NULL, NULL, NULL, '{}', NULL, 66, 'Vる・ない／N ＋ に限る', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', 'N2', 'Vる(II:Vます・する→すまい・来る→来まい) ＋ まい', '① Sẽ không~ (ý chí phủ định mạnh mẽ)　② Có lẽ không ~ (suy đoán phủ định)', NULL, NULL, NULL, NULL, NULL, NULL, '{}', NULL, 66, 'Vる(II:Vます・する→すまい・来る→来まい) ＋ まい', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('b779fae7-1142-418c-920b-8fbb8ba69a41', 'N2', 'Vようか Vるまいか', 'Làm hay là không... (phân vân, do dự giữa làm và không làm)', NULL, 'Vよう(ý chí) か Vる/Vます／する まいか', 'Diễn tả sự phân vân, do dự của người nói giữa việc làm và không làm 1 việc gì đó', NULL, NULL, NULL, '{}', NULL, 66, 'Vようか Vるまいか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('e0077cae-c799-481f-a23e-0a79f15e44b6', 'N2', 'N1にしろN2にしろ／Vるにしろ Vないにしろ', 'Dù...dù... (dù trường hợp nào trong 2 trường hợp đối lập cũng vậy)', NULL, 'N1にしろN2にしろ／Vる1にしろVる2にしろ／Vるにしろ Vないにしろ', 'Nêu 2 khả năng đối lập nhau, khẳng định kết luận/thái độ vế sau đúng trong cả 2 trường hợp', NULL, NULL, NULL, '{}', NULL, 66, 'N1にしろN2にしろ／Vるにしろ Vないにしろ', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;

-- ---------- jp_grammar_usages (chỉ mẫu nhiều usage) ----------
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('2e8b242d-3bcf-4511-a893-af379cf74e9b', 'c78541e9-2873-48a6-b627-da88fb3e1dac', 1, 'Ai chứ, gì chứ ~ (khẳng định tin tưởng tuyệt đối, loại trừ khả năng ngược lại)', 'N ＋ に限って', 'Khẳng định đối tượng đã nêu chắc chắn không thể làm/không có khả năng xảy ra điều tiêu cực', NULL, 66, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('2cde7c11-9235-496a-b237-372c71d8006f', 'c78541e9-2873-48a6-b627-da88fb3e1dac', 2, 'Đúng vào lúc ~ (sự việc trớ trêu, không may xảy ra đúng lúc)', 'N ＋ に限って', 'Diễn tả sự việc không may/trớ trêu xảy ra đúng vào thời điểm/trường hợp đã nêu', NULL, 66, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('dd30b34f-4d04-4f5a-bd06-6964d4f879e7', 'b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', 1, 'Sẽ không~ (ý chí phủ định mạnh mẽ của người nói)', 'Vる（辞書形／グループ2 bỏ る） ＋ まい', 'Diễn tả quyết tâm/ý chí mạnh mẽ sẽ không làm 1 việc gì đó nữa', NULL, 66, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('64fa7ebc-78f4-422b-8155-443b2dd390c2', 'b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', 2, 'Có lẽ không ~ (suy đoán mang tính phủ định của người nói)', 'Vる（辞書形／グループ2 bỏ る） ＋ まい', 'Diễn tả suy đoán của người nói rằng 1 việc gì đó khó có khả năng xảy ra', NULL, 66, 'pdf');

-- ---------- jp_grammar_examples ----------
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('cb50015e-0351-4bfc-bab0-047775fa7cb9', NULL, 1, 'standard', 'あのレストランが来月で閉店だなんて残念な限りだ。', 'Cái nhà hàng đó tháng sau đóng cửa thì tiếc thật đấy.', 'あのレストランが来月で閉店だなんて残念な＿＿＿。', '限りだ', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('cb50015e-0351-4bfc-bab0-047775fa7cb9', NULL, 2, 'daily', '試験に一発で合格できて嬉しい限りだ。', 'Thi đỗ ngay lần đầu thì vui vô cùng.', '試験に一発で合格できて嬉しい＿＿＿。', '限りだ', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('cb50015e-0351-4bfc-bab0-047775fa7cb9', NULL, 3, 'daily', '一人で全部やらされて心細い限りだ。', 'Bị bắt làm hết một mình thì thấy bất an vô cùng.', '一人で全部やらされて心細い＿＿＿。', '限りだ', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('bd2d5467-d48e-4312-a0f7-ef714be205d1', NULL, 1, 'standard', 'ここの店は、休日に限らず平日も大勢の人が訪れる。', 'Cửa hàng này không chỉ ngày nghỉ mà ngày thường cũng rất nhiều người ghé đến.', 'ここの店は、休日＿＿＿平日も大勢の人が訪れる。', 'に限らず', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('bd2d5467-d48e-4312-a0f7-ef714be205d1', NULL, 2, 'daily', 'この問題は日本に限らず、世界中で起きている。', 'Vấn đề này không chỉ ở Nhật mà đang xảy ra trên toàn thế giới.', 'この問題は日本＿＿＿、世界中で起きている。', 'に限らず', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('bd2d5467-d48e-4312-a0f7-ef714be205d1', NULL, 3, 'daily', '彼は英語に限らず、フランス語も話せる。', 'Anh ấy không chỉ tiếng Anh mà còn nói được cả tiếng Pháp.', '彼は英語＿＿＿、フランス語も話せる。', 'に限らず', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4083a286-805f-4145-826c-60844390fcb7', NULL, 1, 'standard', '私の知る限り、あの男は事件の犯人ではない。', 'Trong phạm vi mà tôi biết thì người đàn ông kia không phải nghi phạm của vụ án.', '私の知る＿＿＿、あの男は事件の犯人ではない。', '限り', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4083a286-805f-4145-826c-60844390fcb7', NULL, 2, 'daily', '私が調べた限りでは、そのような記録は残っていない。', 'Trong phạm vi tôi đã tra cứu thì không còn ghi chép nào như vậy.', '私が調べた＿＿＿、そのような記録は残っていない。', '限りでは', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4083a286-805f-4145-826c-60844390fcb7', NULL, 3, 'daily', '見た限りでは、この製品に問題はなさそうだ。', 'Ở mức độ đã xem qua thì có vẻ sản phẩm này không có vấn đề gì.', '見た＿＿＿、この製品に問題はなさそうだ。', '限りでは', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8e628b6e-6c0f-4f1c-ac15-ab9ec6acac8a', NULL, 1, 'standard', '日本に住んでいる限り、日本のルールを守らなければならない。', 'Khi sống ở Nhật Bản cần phải tuân theo quy tắc của Nhật Bản.', '日本に住んでいる＿＿＿、日本のルールを守らなければならない。', '限り', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8e628b6e-6c0f-4f1c-ac15-ab9ec6acac8a', NULL, 2, 'daily', '元気である限り、働き続けたい。', 'Chừng nào còn khỏe mạnh, tôi muốn tiếp tục làm việc.', '元気である＿＿＿、働き続けたい。', '限り', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('8e628b6e-6c0f-4f1c-ac15-ab9ec6acac8a', NULL, 3, 'daily', 'お金がある限り、旅行を楽しみたい。', 'Chừng nào còn tiền, tôi muốn tận hưởng du lịch.', 'お金がある＿＿＿、旅行を楽しみたい。', '限り', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('31b43943-99e3-47de-b883-19fd196597f2', NULL, 1, 'standard', '毎月、第一金曜日に限り、1000円で映画を鑑賞できる。', 'Chỉ thứ 6 đầu tiên của mỗi tháng thì có thể xem những bộ phim trong rạp với giá 1000 yên.', '毎月、第一金曜日＿＿＿、1000円で映画を鑑賞できる。', 'に限り', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('31b43943-99e3-47de-b883-19fd196597f2', NULL, 2, 'daily', '本日に限り、全品20%オフです。', 'Chỉ riêng hôm nay, toàn bộ sản phẩm giảm giá 20%.', '本日＿＿＿、全品20%オフです。', 'に限り', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('31b43943-99e3-47de-b883-19fd196597f2', NULL, 3, 'daily', '会員に限り、無料で利用できます。', 'Chỉ dành riêng cho hội viên, có thể sử dụng miễn phí.', '会員＿＿＿、無料で利用できます。', 'に限り', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', '2e8b242d-3bcf-4511-a893-af379cf74e9b', 1, 'standard', 'あの人に限って、寝坊なんて、何かあったに違いない。', 'Ai chứ người đó thì việc ngủ dậy muộn chắc chắn phải có việc gì đó mới như vậy.', 'あの人＿＿＿、寝坊なんて、何かあったに違いない。', 'に限って', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', '2e8b242d-3bcf-4511-a893-af379cf74e9b', 2, 'daily', '彼に限って、そんな嘘をつくはずがない。', 'Ai chứ anh ấy thì không thể nào nói dối như vậy được.', '彼＿＿＿、そんな嘘をつくはずがない。', 'に限って', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', '2e8b242d-3bcf-4511-a893-af379cf74e9b', 3, 'daily', 'うちの子に限って、いじめをするなんて考えられない。', 'Ai chứ con tôi thì không thể nghĩ là nó đi bắt nạt người khác được.', 'うちの子＿＿＿、いじめをするなんて考えられない。', 'に限って', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', '2cde7c11-9235-496a-b237-372c71d8006f', 1, 'standard', 'デートの日に限って雨が降る。', 'Vào đúng ngày hẹn hò thì trời lại mưa.', 'デートの日＿＿＿雨が降る。', 'に限って', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', '2cde7c11-9235-496a-b237-372c71d8006f', 2, 'daily', '急いでいる時に限って、電車が遅れる。', 'Đúng lúc đang vội thì tàu điện lại đến muộn.', '急いでいる時＿＿＿、電車が遅れる。', 'に限って', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', '2cde7c11-9235-496a-b237-372c71d8006f', 3, 'daily', '傘を忘れた日に限って、大雨が降る。', 'Đúng ngày quên mang ô thì trời lại mưa to.', '傘を忘れた日＿＿＿、大雨が降る。', 'に限って', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ce015143-2d0a-4c76-9c40-b4046cabbaf0', NULL, 1, 'standard', 'ダイエットは食事制限をするより、運動に限る。', 'Đối với việc ăn kiêng, thay vì hạn chế ăn uống, tốt nhất là nên vận động.', 'ダイエットは食事制限をするより、運動＿＿＿。', 'に限る', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ce015143-2d0a-4c76-9c40-b4046cabbaf0', NULL, 2, 'daily', '疲れた時は寝るに限る。', 'Khi mệt thì tốt nhất là nên ngủ.', '疲れた時は寝る＿＿＿。', 'に限る', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ce015143-2d0a-4c76-9c40-b4046cabbaf0', NULL, 3, 'daily', '夏はやっぱりビールに限る。', 'Mùa hè thì đúng là bia là ngon nhất.', '夏はやっぱりビール＿＿＿。', 'に限る', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', 'dd30b34f-4d04-4f5a-bd06-6964d4f879e7', 1, 'standard', '毎回誘っても断られるので、二度と誘うまい。', 'Lần nào rủ cũng bị từ chối, nên tôi sẽ không bao giờ rủ nữa.', '毎回誘っても断られるので、二度と＿＿＿。', '誘うまい', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', 'dd30b34f-4d04-4f5a-bd06-6964d4f879e7', 2, 'daily', 'もう二度とお酒は飲むまい。', 'Tôi sẽ không bao giờ uống rượu nữa.', 'もう二度とお酒は＿＿＿。', '飲むまい', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', 'dd30b34f-4d04-4f5a-bd06-6964d4f879e7', 3, 'daily', 'こんな失敗は二度と繰り返すまい。', 'Tôi sẽ không lặp lại thất bại như thế này lần nữa.', 'こんな失敗は二度と＿＿＿。', '繰り返すまい', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', '64fa7ebc-78f4-422b-8155-443b2dd390c2', 1, 'standard', 'あの人はよく嘘をつくので、誰も信じまい。', 'Vì người đó hay nói dối nên sẽ chẳng có ai tin nữa.', 'あの人はよく嘘をつくので、誰も＿＿＿。', '信じまい', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', '64fa7ebc-78f4-422b-8155-443b2dd390c2', 2, 'daily', 'この天気ではもう客は来まい。', 'Với thời tiết thế này chắc sẽ không còn khách đến nữa.', 'この天気ではもう客は＿＿＿。', '来まい', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', '64fa7ebc-78f4-422b-8155-443b2dd390c2', 3, 'daily', '彼はもうここには戻るまい。', 'Có lẽ anh ấy sẽ không quay lại đây nữa.', '彼はもうここには＿＿＿。', '戻るまい', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b779fae7-1142-418c-920b-8fbb8ba69a41', NULL, 1, 'standard', '春休みに、実家に帰省しようか、するまいか、考えている。', 'Tôi đang suy nghĩ có nên về quê vào kỳ nghỉ xuân hay không.', '春休みに、実家に帰省しようか、＿＿＿、考えている。', 'するまいか', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b779fae7-1142-418c-920b-8fbb8ba69a41', NULL, 2, 'daily', 'この仕事を引き受けようか、引き受けまいか、迷っている。', 'Tôi đang phân vân có nên nhận công việc này hay không.', 'この仕事を引き受けようか、＿＿＿、迷っている。', '引き受けまいか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b779fae7-1142-418c-920b-8fbb8ba69a41', NULL, 3, 'daily', '彼に本当のことを話そうか、話すまいか、悩んでいる。', 'Tôi đang trăn trở có nên nói sự thật với anh ấy hay không.', '彼に本当のことを話そうか、＿＿＿、悩んでいる。', '話すまいか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e0077cae-c799-481f-a23e-0a79f15e44b6', NULL, 1, 'standard', '進学にしろ、就職にしろ、自分の将来なのでしっかりと考える。', 'Dù học tiếp hay đi xin việc, vì là tương lai của mình nên tôi cần suy nghĩ nghiêm túc.', '進学にしろ、就職＿＿＿、自分の将来なのでしっかりと考える。', 'にしろ', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e0077cae-c799-481f-a23e-0a79f15e44b6', NULL, 2, 'daily', '行くにしろ行かないにしろ、早く返事をしてください。', 'Dù đi hay không đi, hãy trả lời sớm cho tôi.', '行くにしろ行か＿＿＿、早く返事をしてください。', 'ないにしろ', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e0077cae-c799-481f-a23e-0a79f15e44b6', NULL, 3, 'daily', '賛成にしろ反対にしろ、意見をはっきり言うべきだ。', 'Dù tán thành hay phản đối, cũng nên nói rõ ý kiến của mình.', '賛成にしろ反対＿＿＿、意見をはっきり言うべきだ。', 'にしろ', 'generated');

-- ---------- jp_grammar_questions: generated (fill_blank/choose_meaning/choose_connection) ----------
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('cb50015e-0351-4bfc-bab0-047775fa7cb9', NULL, 'fill_blank', 'Điền vào chỗ trống: あのレストランが来月で閉店だなんて残念な＿＿＿。', '限りだ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('cb50015e-0351-4bfc-bab0-047775fa7cb9', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Aい／Aな ＋ かぎりだ" (usage này) có nghĩa là gì?', 'Cảm thấy rất.../Vô cùng... (cảm thán về mức độ cảm xúc)', 'Trong phạm vi.../Ở mức độ... (giới hạn phạm vi thông tin/hiểu biết của người nói)', 'Trong lúc.../Khi... (chừng nào điều kiện đó còn đúng)', 'Chỉ trong/Chỉ đối với/Chỉ riêng ~ (giới hạn đối tượng/phạm vi được áp dụng)', 'Cảm thấy rất.../Vô cùng... (cảm thán về mức độ cảm xúc)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('cb50015e-0351-4bfc-bab0-047775fa7cb9', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Cảm thấy rất.../Vô cùng... (cảm thán về mức độ cảm xúc)"?', 'Vようか Vるまいか', 'Nの／Vる・Vた／Vている ＋ 限り(では)', 'Aい／Aな ＋ かぎりだ', 'N1にしろN2にしろ／Vるにしろ Vないにしろ', 'Aい／Aな ＋ かぎりだ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('bd2d5467-d48e-4312-a0f7-ef714be205d1', NULL, 'fill_blank', 'Điền vào chỗ trống: ここの店は、休日＿＿＿平日も大勢の人が訪れる。', 'に限らず', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('bd2d5467-d48e-4312-a0f7-ef714be205d1', NULL, 'choose_meaning', 'Mẫu ngữ pháp "N ＋ に限らず" (usage này) có nghĩa là gì?', '① Ai chứ, gì chứ ~ (tin tưởng tuyệt đối vào đối tượng)　② Đúng vào lúc ~ (trớ trêu, không may)', 'Không chỉ...mà còn... (mở rộng phạm vi ra ngoài đối tượng đã nêu)', 'Trong lúc.../Khi... (chừng nào điều kiện đó còn đúng)', 'Làm hay là không... (phân vân, do dự giữa làm và không làm)', 'Không chỉ...mà còn... (mở rộng phạm vi ra ngoài đối tượng đã nêu)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('bd2d5467-d48e-4312-a0f7-ef714be205d1', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Không chỉ...mà còn... (mở rộng phạm vi ra ngoài đối tượng đã nêu)"?', 'N1にしろN2にしろ／Vるにしろ Vないにしろ', 'N ＋ に限らず', 'Vる・ない／N ＋ に限る', 'N ＋ に限って', 'N ＋ に限らず', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('4083a286-805f-4145-826c-60844390fcb7', NULL, 'fill_blank', 'Điền vào chỗ trống: 私の知る＿＿＿、あの男は事件の犯人ではない。', '限り', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4083a286-805f-4145-826c-60844390fcb7', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Nの／Vる・Vた／Vている ＋ 限り(では)" (usage này) có nghĩa là gì?', '① Ai chứ, gì chứ ~ (tin tưởng tuyệt đối vào đối tượng)　② Đúng vào lúc ~ (trớ trêu, không may)', '~ Là tốt nhất (khuyến nghị lựa chọn tốt nhất trong số các lựa chọn)', 'Không chỉ...mà còn... (mở rộng phạm vi ra ngoài đối tượng đã nêu)', 'Trong phạm vi.../Ở mức độ... (giới hạn phạm vi thông tin/hiểu biết của người nói)', 'Trong phạm vi.../Ở mức độ... (giới hạn phạm vi thông tin/hiểu biết của người nói)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4083a286-805f-4145-826c-60844390fcb7', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Trong phạm vi.../Ở mức độ... (giới hạn phạm vi thông tin/hiểu biết của người nói)"?', 'Nの／Vる・Vた／Vている ＋ 限り(では)', 'N に限り、.../N に限る。', 'Aい／V(普)／Aな・である／Nである ＋ 限り(は)', 'N ＋ に限って', 'Nの／Vる・Vた／Vている ＋ 限り(では)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('8e628b6e-6c0f-4f1c-ac15-ab9ec6acac8a', NULL, 'fill_blank', 'Điền vào chỗ trống: 日本に住んでいる＿＿＿、日本のルールを守らなければならない。', '限り', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('8e628b6e-6c0f-4f1c-ac15-ab9ec6acac8a', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Aい／V(普)／Aな・である／Nである ＋ 限り(は)" (usage này) có nghĩa là gì?', 'Chỉ trong/Chỉ đối với/Chỉ riêng ~ (giới hạn đối tượng/phạm vi được áp dụng)', '① Ai chứ, gì chứ ~ (tin tưởng tuyệt đối vào đối tượng)　② Đúng vào lúc ~ (trớ trêu, không may)', 'Trong lúc.../Khi... (chừng nào điều kiện đó còn đúng)', 'Trong phạm vi.../Ở mức độ... (giới hạn phạm vi thông tin/hiểu biết của người nói)', 'Trong lúc.../Khi... (chừng nào điều kiện đó còn đúng)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('8e628b6e-6c0f-4f1c-ac15-ab9ec6acac8a', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Trong lúc.../Khi... (chừng nào điều kiện đó còn đúng)"?', 'Aい／V(普)／Aな・である／Nである ＋ 限り(は)', 'Vようか Vるまいか', 'Vる・ない／N ＋ に限る', 'Vる(II:Vます・する→すまい・来る→来まい) ＋ まい', 'Aい／V(普)／Aな・である／Nである ＋ 限り(は)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('31b43943-99e3-47de-b883-19fd196597f2', NULL, 'fill_blank', 'Điền vào chỗ trống: 毎月、第一金曜日＿＿＿、1000円で映画を鑑賞できる。', 'に限り', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('31b43943-99e3-47de-b883-19fd196597f2', NULL, 'choose_meaning', 'Mẫu ngữ pháp "N に限り、.../N に限る。" (usage này) có nghĩa là gì?', '① Sẽ không~ (ý chí phủ định mạnh mẽ)　② Có lẽ không ~ (suy đoán phủ định)', 'Làm hay là không... (phân vân, do dự giữa làm và không làm)', '① Ai chứ, gì chứ ~ (tin tưởng tuyệt đối vào đối tượng)　② Đúng vào lúc ~ (trớ trêu, không may)', 'Chỉ trong/Chỉ đối với/Chỉ riêng ~ (giới hạn đối tượng/phạm vi được áp dụng)', 'Chỉ trong/Chỉ đối với/Chỉ riêng ~ (giới hạn đối tượng/phạm vi được áp dụng)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('31b43943-99e3-47de-b883-19fd196597f2', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Chỉ trong/Chỉ đối với/Chỉ riêng ~ (giới hạn đối tượng/phạm vi được áp dụng)"?', 'Aい／V(普)／Aな・である／Nである ＋ 限り(は)', 'N ＋ に限って', 'N に限り、.../N に限る。', 'N1にしろN2にしろ／Vるにしろ Vないにしろ', 'N に限り、.../N に限る。', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', '2e8b242d-3bcf-4511-a893-af379cf74e9b', 'fill_blank', 'Điền vào chỗ trống: あの人＿＿＿、寝坊なんて、何かあったに違いない。', 'に限って', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', '2e8b242d-3bcf-4511-a893-af379cf74e9b', 'choose_meaning', 'Mẫu ngữ pháp "N ＋ に限って" (usage này) có nghĩa là gì?', 'Dù...dù... (dù trường hợp nào trong 2 trường hợp đối lập cũng vậy)', 'Không chỉ...mà còn... (mở rộng phạm vi ra ngoài đối tượng đã nêu)', 'Ai chứ, gì chứ ~ (khẳng định tin tưởng tuyệt đối, loại trừ khả năng ngược lại)', 'Chỉ trong/Chỉ đối với/Chỉ riêng ~ (giới hạn đối tượng/phạm vi được áp dụng)', 'Ai chứ, gì chứ ~ (khẳng định tin tưởng tuyệt đối, loại trừ khả năng ngược lại)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', '2e8b242d-3bcf-4511-a893-af379cf74e9b', 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Ai chứ, gì chứ ~ (khẳng định tin tưởng tuyệt đối, loại trừ khả năng ngược lại)"?', 'N ＋ に限らず', 'Vる・ない／N ＋ に限る', 'Nの／Vる・Vた／Vている ＋ 限り(では)', 'N ＋ に限って', 'N ＋ に限って', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', '2cde7c11-9235-496a-b237-372c71d8006f', 'fill_blank', 'Điền vào chỗ trống: デートの日＿＿＿雨が降る。', 'に限って', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', '2cde7c11-9235-496a-b237-372c71d8006f', 'choose_meaning', 'Mẫu ngữ pháp "N ＋ に限って" (usage này) có nghĩa là gì?', 'Trong phạm vi.../Ở mức độ... (giới hạn phạm vi thông tin/hiểu biết của người nói)', 'Trong lúc.../Khi... (chừng nào điều kiện đó còn đúng)', 'Làm hay là không... (phân vân, do dự giữa làm và không làm)', 'Đúng vào lúc ~ (sự việc trớ trêu, không may xảy ra đúng lúc)', 'Đúng vào lúc ~ (sự việc trớ trêu, không may xảy ra đúng lúc)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c78541e9-2873-48a6-b627-da88fb3e1dac', '2cde7c11-9235-496a-b237-372c71d8006f', 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Đúng vào lúc ~ (sự việc trớ trêu, không may xảy ra đúng lúc)"?', 'N ＋ に限って', 'Aい／V(普)／Aな・である／Nである ＋ 限り(は)', 'Aい／Aな ＋ かぎりだ', 'N に限り、.../N に限る。', 'N ＋ に限って', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('ce015143-2d0a-4c76-9c40-b4046cabbaf0', NULL, 'fill_blank', 'Điền vào chỗ trống: ダイエットは食事制限をするより、運動＿＿＿。', 'に限る', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ce015143-2d0a-4c76-9c40-b4046cabbaf0', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vる・ない／N ＋ に限る" (usage này) có nghĩa là gì?', 'Cảm thấy rất.../Vô cùng... (cảm thán về mức độ cảm xúc)', 'Không chỉ...mà còn... (mở rộng phạm vi ra ngoài đối tượng đã nêu)', '~ Là tốt nhất (khuyến nghị lựa chọn tốt nhất trong số các lựa chọn)', 'Làm hay là không... (phân vân, do dự giữa làm và không làm)', '~ Là tốt nhất (khuyến nghị lựa chọn tốt nhất trong số các lựa chọn)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ce015143-2d0a-4c76-9c40-b4046cabbaf0', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "~ Là tốt nhất (khuyến nghị lựa chọn tốt nhất trong số các lựa chọn)"?', 'N ＋ に限らず', 'N ＋ に限って', 'Vる・ない／N ＋ に限る', 'Vようか Vるまいか', 'Vる・ない／N ＋ に限る', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', 'dd30b34f-4d04-4f5a-bd06-6964d4f879e7', 'fill_blank', 'Điền vào chỗ trống: 毎回誘っても断られるので、二度と＿＿＿。', '誘うまい', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', 'dd30b34f-4d04-4f5a-bd06-6964d4f879e7', 'choose_meaning', 'Mẫu ngữ pháp "Vる(II:Vます・する→すまい・来る→来まい) ＋ まい" (usage này) có nghĩa là gì?', 'Sẽ không~ (ý chí phủ định mạnh mẽ của người nói)', 'Làm hay là không... (phân vân, do dự giữa làm và không làm)', 'Dù...dù... (dù trường hợp nào trong 2 trường hợp đối lập cũng vậy)', '① Ai chứ, gì chứ ~ (tin tưởng tuyệt đối vào đối tượng)　② Đúng vào lúc ~ (trớ trêu, không may)', 'Sẽ không~ (ý chí phủ định mạnh mẽ của người nói)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', 'dd30b34f-4d04-4f5a-bd06-6964d4f879e7', 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Sẽ không~ (ý chí phủ định mạnh mẽ của người nói)"?', 'Vる(II:Vます・する→すまい・来る→来まい) ＋ まい', 'N ＋ に限らず', 'Aい／V(普)／Aな・である／Nである ＋ 限り(は)', 'Aい／Aな ＋ かぎりだ', 'Vる(II:Vます・する→すまい・来る→来まい) ＋ まい', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', '64fa7ebc-78f4-422b-8155-443b2dd390c2', 'fill_blank', 'Điền vào chỗ trống: あの人はよく嘘をつくので、誰も＿＿＿。', '信じまい', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', '64fa7ebc-78f4-422b-8155-443b2dd390c2', 'choose_meaning', 'Mẫu ngữ pháp "Vる(II:Vます・する→すまい・来る→来まい) ＋ まい" (usage này) có nghĩa là gì?', 'Chỉ trong/Chỉ đối với/Chỉ riêng ~ (giới hạn đối tượng/phạm vi được áp dụng)', 'Cảm thấy rất.../Vô cùng... (cảm thán về mức độ cảm xúc)', 'Trong lúc.../Khi... (chừng nào điều kiện đó còn đúng)', 'Có lẽ không ~ (suy đoán mang tính phủ định của người nói)', 'Có lẽ không ~ (suy đoán mang tính phủ định của người nói)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b7c60cdd-0352-4cd7-b6bd-d606f0b548a1', '64fa7ebc-78f4-422b-8155-443b2dd390c2', 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Có lẽ không ~ (suy đoán mang tính phủ định của người nói)"?', 'Vる・ない／N ＋ に限る', 'N ＋ に限らず', 'Aい／Aな ＋ かぎりだ', 'Vる(II:Vます・する→すまい・来る→来まい) ＋ まい', 'Vる(II:Vます・する→すまい・来る→来まい) ＋ まい', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('b779fae7-1142-418c-920b-8fbb8ba69a41', NULL, 'fill_blank', 'Điền vào chỗ trống: 春休みに、実家に帰省しようか、＿＿＿、考えている。', 'するまいか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b779fae7-1142-418c-920b-8fbb8ba69a41', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vようか Vるまいか" (usage này) có nghĩa là gì?', '~ Là tốt nhất (khuyến nghị lựa chọn tốt nhất trong số các lựa chọn)', 'Làm hay là không... (phân vân, do dự giữa làm và không làm)', 'Dù...dù... (dù trường hợp nào trong 2 trường hợp đối lập cũng vậy)', '① Ai chứ, gì chứ ~ (tin tưởng tuyệt đối vào đối tượng)　② Đúng vào lúc ~ (trớ trêu, không may)', 'Làm hay là không... (phân vân, do dự giữa làm và không làm)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b779fae7-1142-418c-920b-8fbb8ba69a41', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Làm hay là không... (phân vân, do dự giữa làm và không làm)"?', 'N1にしろN2にしろ／Vるにしろ Vないにしろ', 'N ＋ に限って', 'Vようか Vるまいか', 'Nの／Vる・Vた／Vている ＋ 限り(では)', 'Vようか Vるまいか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, correct_answer, source_type) values ('e0077cae-c799-481f-a23e-0a79f15e44b6', NULL, 'fill_blank', 'Điền vào chỗ trống: 進学にしろ、就職＿＿＿、自分の将来なのでしっかりと考える。', 'にしろ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e0077cae-c799-481f-a23e-0a79f15e44b6', NULL, 'choose_meaning', 'Mẫu ngữ pháp "N1にしろN2にしろ／Vるにしろ Vないにしろ" (usage này) có nghĩa là gì?', 'Cảm thấy rất.../Vô cùng... (cảm thán về mức độ cảm xúc)', 'Chỉ trong/Chỉ đối với/Chỉ riêng ~ (giới hạn đối tượng/phạm vi được áp dụng)', 'Dù...dù... (dù trường hợp nào trong 2 trường hợp đối lập cũng vậy)', 'Làm hay là không... (phân vân, do dự giữa làm và không làm)', 'Dù...dù... (dù trường hợp nào trong 2 trường hợp đối lập cũng vậy)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e0077cae-c799-481f-a23e-0a79f15e44b6', NULL, 'choose_connection', 'Cách nối nào tạo ra nghĩa: "Dù...dù... (dù trường hợp nào trong 2 trường hợp đối lập cũng vậy)"?', 'N ＋ に限って', 'Vる・ない／N ＋ に限る', 'N1にしろN2にしろ／Vるにしろ Vないにしろ', 'N ＋ に限らず', 'N1にしろN2にしろ／Vるにしろ Vないにしろ', 'generated');

-- Tổng 36 câu hỏi generated cho 10 mẫu ngữ pháp (12 usage).
