-- ============================================================
-- jp-go — Từ vựng N4, PILOT (10 từ đầu 課26, trang in 17).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙.
-- Dùng song song lesson_no (課26, nối tiếp N5 課1-25) VÀ
-- word_class (bắt buộc, tự phân loại theo 4 nhóm chính).
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e595b358-15f0-452b-b942-d33e4bfe6a3e', 'N4', 26, 'word', '見る・診る', 'みる', 'nhìn, xem / khám bệnh', NULL, '動詞', 17, '見る・診る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('dd6f4085-750c-4225-8a82-132e8a8fd0b2', 'N4', 26, 'word', '探す', 'さがす', 'tìm kiếm', NULL, '動詞', 17, '探す', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b6e06d84-9994-4748-b444-71a4bde52762', 'N4', 26, 'word', '遅れる', 'おくれる', 'chậm, trễ', 'thường dùng dạng [時間に〜]', '動詞', 17, '遅れる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('930d38a2-626c-4db6-8bf3-aeaac5ff2c78', 'N4', 26, 'word', '間に合う', 'まにあう', 'kịp (giờ)', 'thường dùng dạng [時間に〜]', '動詞', 17, '間に合う', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a31a5410-997b-4058-bbfe-b3fc52676c60', 'N4', 26, 'word', 'やる', 'やる', 'làm', NULL, '動詞', 17, 'やる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a989b5d1-031b-493a-9bf6-b184455472a2', 'N4', 26, 'word', '拾う', 'ひろう', 'nhặt', NULL, '動詞', 17, '拾う', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e0088d35-28a2-44a1-ba23-42a0c495e26b', 'N4', 26, 'word', '出す', 'だす', 'đưa ra, gửi đi; [ごみを〜] đổ (rác); [レポートを〜] nộp (báo cáo)', NULL, '動詞', 17, '出す', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a7216e13-cafb-42c3-a0a7-fdb70f818048', 'N4', 26, 'word', '連絡する', 'れんらくする', 'liên lạc', NULL, '動詞', 17, '連絡する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('29824f8a-05e9-4d1b-a6d7-803228cc7bfa', 'N4', 26, 'phrase', '気分がいい', 'きぶんがいい', 'cảm thấy thoải mái, cảm thấy khỏe', NULL, 'い形容詞', 17, '気分がいい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('277cb8f8-992f-484c-828f-62c2c33ca0d9', 'N4', 26, 'phrase', '気分が悪い', 'きぶんがわるい', 'cảm thấy không thoải mái, cảm thấy mệt', NULL, 'い形容詞', 17, '気分が悪い', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彼はテレビでドラマを見る。', 'Anh ấy xem phim truyền hình trên tivi.', '彼はテレビでドラマを_____。', '見る', 'generated' from jp_vocab where id = 'e595b358-15f0-452b-b942-d33e4bfe6a3e';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '鍵をどこに置いたか探す。', 'Tôi tìm xem đã để chìa khóa ở đâu.', '鍵をどこに置いたか_____。', '探す', 'generated' from jp_vocab where id = 'dd6f4085-750c-4225-8a82-132e8a8fd0b2';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '会議の時間に遅れないでください。', 'Xin đừng đến trễ giờ họp.', '会議の時間に_____ないでください。', '遅れ', 'generated' from jp_vocab where id = 'b6e06d84-9994-4748-b444-71a4bde52762';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '急げば電車に間に合う。', 'Nếu vội thì sẽ kịp chuyến tàu.', '急げば電車に_____。', '間に合う', 'generated' from jp_vocab where id = '930d38a2-626c-4db6-8bf3-aeaac5ff2c78';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '宿題は自分でやりなさい。', 'Hãy tự làm bài tập của mình.', '宿題は自分で_____なさい。', 'やり', 'generated' from jp_vocab where id = 'a31a5410-997b-4058-bbfe-b3fc52676c60';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '道でお金を拾った。', 'Tôi đã nhặt được tiền trên đường.', '道でお金を_____た。', '拾っ', 'generated' from jp_vocab where id = 'a989b5d1-031b-493a-9bf6-b184455472a2';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '毎朝ごみを出す。', 'Mỗi sáng tôi đổ rác.', '毎朝ごみを_____。', '出す', 'generated' from jp_vocab where id = 'e0088d35-28a2-44a1-ba23-42a0c495e26b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '後で先生に連絡する。', 'Lát nữa tôi sẽ liên lạc với thầy/cô.', '後で先生に_____。', '連絡する', 'generated' from jp_vocab where id = 'a7216e13-cafb-42c3-a0a7-fdb70f818048';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '今日はとても気分がいい。', 'Hôm nay tôi cảm thấy rất thoải mái.', '今日はとても_____。', '気分がいい', 'generated' from jp_vocab where id = '29824f8a-05e9-4d1b-a6d7-803228cc7bfa';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '食べ過ぎて気分が悪い。', 'Vì ăn quá nhiều nên tôi cảm thấy khó chịu.', '食べ過ぎて_____。', '気分が悪い', 'generated' from jp_vocab where id = '277cb8f8-992f-484c-828f-62c2c33ca0d9';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"見る・診る" có nghĩa là gì?', 'cảm thấy thoải mái, cảm thấy khỏe', 'nhìn, xem / khám bệnh', 'làm', 'kịp (giờ)', 'nhìn, xem / khám bệnh', 'generated' from jp_vocab where id = 'e595b358-15f0-452b-b942-d33e4bfe6a3e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhìn, xem / khám bệnh"?', 'やる', '連絡する', '遅れる', '見る・診る', '見る・診る', 'generated' from jp_vocab where id = 'e595b358-15f0-452b-b942-d33e4bfe6a3e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"見る・診る" đọc là gì?', 'さがす', 'みる', 'やる', 'ひろう', 'みる', 'generated' from jp_vocab where id = 'e595b358-15f0-452b-b942-d33e4bfe6a3e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 彼はテレビでドラマを_____。', NULL, NULL, NULL, NULL, '見る', 'generated' from jp_vocab where id = 'e595b358-15f0-452b-b942-d33e4bfe6a3e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"探す" có nghĩa là gì?', 'tìm kiếm', 'nhặt', 'cảm thấy không thoải mái, cảm thấy mệt', 'kịp (giờ)', 'tìm kiếm', 'generated' from jp_vocab where id = 'dd6f4085-750c-4225-8a82-132e8a8fd0b2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tìm kiếm"?', '気分がいい', '遅れる', 'やる', '探す', '探す', 'generated' from jp_vocab where id = 'dd6f4085-750c-4225-8a82-132e8a8fd0b2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"探す" đọc là gì?', 'さがす', 'まにあう', 'だす', 'みる', 'さがす', 'generated' from jp_vocab where id = 'dd6f4085-750c-4225-8a82-132e8a8fd0b2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 鍵をどこに置いたか_____。', NULL, NULL, NULL, NULL, '探す', 'generated' from jp_vocab where id = 'dd6f4085-750c-4225-8a82-132e8a8fd0b2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"遅れる" có nghĩa là gì?', 'nhìn, xem / khám bệnh', 'chậm, trễ', 'tìm kiếm', 'đưa ra, gửi đi; [ごみを〜] đổ (rác); [レポートを〜] nộp (báo cáo)', 'chậm, trễ', 'generated' from jp_vocab where id = 'b6e06d84-9994-4748-b444-71a4bde52762';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chậm, trễ"?', '出す', '気分が悪い', '間に合う', '遅れる', '遅れる', 'generated' from jp_vocab where id = 'b6e06d84-9994-4748-b444-71a4bde52762';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"遅れる" đọc là gì?', 'だす', 'やる', 'みる', 'おくれる', 'おくれる', 'generated' from jp_vocab where id = 'b6e06d84-9994-4748-b444-71a4bde52762';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 会議の時間に_____ないでください。', NULL, NULL, NULL, NULL, '遅れ', 'generated' from jp_vocab where id = 'b6e06d84-9994-4748-b444-71a4bde52762';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"間に合う" có nghĩa là gì?', 'liên lạc', 'đưa ra, gửi đi; [ごみを〜] đổ (rác); [レポートを〜] nộp (báo cáo)', 'kịp (giờ)', 'cảm thấy không thoải mái, cảm thấy mệt', 'kịp (giờ)', 'generated' from jp_vocab where id = '930d38a2-626c-4db6-8bf3-aeaac5ff2c78';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "kịp (giờ)"?', '気分がいい', 'やる', '見る・診る', '間に合う', '間に合う', 'generated' from jp_vocab where id = '930d38a2-626c-4db6-8bf3-aeaac5ff2c78';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"間に合う" đọc là gì?', 'ひろう', 'れんらくする', 'やる', 'まにあう', 'まにあう', 'generated' from jp_vocab where id = '930d38a2-626c-4db6-8bf3-aeaac5ff2c78';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 急げば電車に_____。', NULL, NULL, NULL, NULL, '間に合う', 'generated' from jp_vocab where id = '930d38a2-626c-4db6-8bf3-aeaac5ff2c78';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"やる" có nghĩa là gì?', 'chậm, trễ', 'làm', 'cảm thấy thoải mái, cảm thấy khỏe', 'liên lạc', 'làm', 'generated' from jp_vocab where id = 'a31a5410-997b-4058-bbfe-b3fc52676c60';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "làm"?', '間に合う', 'やる', '気分が悪い', '探す', 'やる', 'generated' from jp_vocab where id = 'a31a5410-997b-4058-bbfe-b3fc52676c60';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"やる" đọc là gì?', 'みる', 'れんらくする', 'やる', 'まにあう', 'やる', 'generated' from jp_vocab where id = 'a31a5410-997b-4058-bbfe-b3fc52676c60';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 宿題は自分で_____なさい。', NULL, NULL, NULL, NULL, 'やり', 'generated' from jp_vocab where id = 'a31a5410-997b-4058-bbfe-b3fc52676c60';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"拾う" có nghĩa là gì?', 'liên lạc', 'kịp (giờ)', 'nhặt', 'làm', 'nhặt', 'generated' from jp_vocab where id = 'a989b5d1-031b-493a-9bf6-b184455472a2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhặt"?', '出す', '連絡する', '拾う', '気分が悪い', '拾う', 'generated' from jp_vocab where id = 'a989b5d1-031b-493a-9bf6-b184455472a2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"拾う" đọc là gì?', 'きぶんがいい', 'ひろう', 'おくれる', 'れんらくする', 'ひろう', 'generated' from jp_vocab where id = 'a989b5d1-031b-493a-9bf6-b184455472a2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 道でお金を_____た。', NULL, NULL, NULL, NULL, '拾っ', 'generated' from jp_vocab where id = 'a989b5d1-031b-493a-9bf6-b184455472a2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"出す" có nghĩa là gì?', 'làm', 'kịp (giờ)', 'đưa ra, gửi đi; [ごみを〜] đổ (rác); [レポートを〜] nộp (báo cáo)', 'cảm thấy không thoải mái, cảm thấy mệt', 'đưa ra, gửi đi; [ごみを〜] đổ (rác); [レポートを〜] nộp (báo cáo)', 'generated' from jp_vocab where id = 'e0088d35-28a2-44a1-ba23-42a0c495e26b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đưa ra, gửi đi; [ごみを〜] đổ (rác); [レポートを〜] nộp (báo cáo)"?', '連絡する', '探す', '拾う', '出す', '出す', 'generated' from jp_vocab where id = 'e0088d35-28a2-44a1-ba23-42a0c495e26b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"出す" đọc là gì?', 'まにあう', 'れんらくする', 'だす', 'ひろう', 'だす', 'generated' from jp_vocab where id = 'e0088d35-28a2-44a1-ba23-42a0c495e26b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 毎朝ごみを_____。', NULL, NULL, NULL, NULL, '出す', 'generated' from jp_vocab where id = 'e0088d35-28a2-44a1-ba23-42a0c495e26b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"連絡する" có nghĩa là gì?', 'liên lạc', 'kịp (giờ)', 'nhặt', 'cảm thấy thoải mái, cảm thấy khỏe', 'liên lạc', 'generated' from jp_vocab where id = 'a7216e13-cafb-42c3-a0a7-fdb70f818048';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "liên lạc"?', '拾う', '出す', '連絡する', '見る・診る', '連絡する', 'generated' from jp_vocab where id = 'a7216e13-cafb-42c3-a0a7-fdb70f818048';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"連絡する" đọc là gì?', 'きぶんがいい', 'れんらくする', 'おくれる', 'きぶんがわるい', 'れんらくする', 'generated' from jp_vocab where id = 'a7216e13-cafb-42c3-a0a7-fdb70f818048';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 後で先生に_____。', NULL, NULL, NULL, NULL, '連絡する', 'generated' from jp_vocab where id = 'a7216e13-cafb-42c3-a0a7-fdb70f818048';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"気分がいい" có nghĩa là gì?', 'nhặt', 'đưa ra, gửi đi; [ごみを〜] đổ (rác); [レポートを〜] nộp (báo cáo)', 'cảm thấy thoải mái, cảm thấy khỏe', 'liên lạc', 'cảm thấy thoải mái, cảm thấy khỏe', 'generated' from jp_vocab where id = '29824f8a-05e9-4d1b-a6d7-803228cc7bfa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cảm thấy thoải mái, cảm thấy khỏe"?', '気分が悪い', '気分がいい', '見る・診る', '連絡する', '気分がいい', 'generated' from jp_vocab where id = '29824f8a-05e9-4d1b-a6d7-803228cc7bfa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"気分がいい" đọc là gì?', 'さがす', 'まにあう', 'きぶんがいい', 'きぶんがわるい', 'きぶんがいい', 'generated' from jp_vocab where id = '29824f8a-05e9-4d1b-a6d7-803228cc7bfa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 今日はとても_____。', NULL, NULL, NULL, NULL, '気分がいい', 'generated' from jp_vocab where id = '29824f8a-05e9-4d1b-a6d7-803228cc7bfa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"気分が悪い" có nghĩa là gì?', 'nhặt', 'làm', 'cảm thấy không thoải mái, cảm thấy mệt', 'đưa ra, gửi đi; [ごみを〜] đổ (rác); [レポートを〜] nộp (báo cáo)', 'cảm thấy không thoải mái, cảm thấy mệt', 'generated' from jp_vocab where id = '277cb8f8-992f-484c-828f-62c2c33ca0d9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cảm thấy không thoải mái, cảm thấy mệt"?', '遅れる', 'やる', '気分が悪い', '見る・診る', '気分が悪い', 'generated' from jp_vocab where id = '277cb8f8-992f-484c-828f-62c2c33ca0d9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"気分が悪い" đọc là gì?', 'れんらくする', 'おくれる', 'さがす', 'きぶんがわるい', 'きぶんがわるい', 'generated' from jp_vocab where id = '277cb8f8-992f-484c-828f-62c2c33ca0d9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 食べ過ぎて_____。', NULL, NULL, NULL, NULL, '気分が悪い', 'generated' from jp_vocab where id = '277cb8f8-992f-484c-828f-62c2c33ca0d9';
