-- ============================================================
-- jp-go — Từ vựng N4, 課28 (phần còn lại, 30 từ, mục 22-51).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 19.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('fe322e73-6948-499d-a0a8-0f79a74627f9', 'N4', 28, 'word', '値段', 'ねだん', 'giá cả', NULL, '名詞', 19, '値段', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('32b349f3-7fec-45da-8cb3-9c5a0059ab52', 'N4', 28, 'word', '給料', 'きゅうりょう', 'lương', NULL, '名詞', 19, '給料', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3058fdc3-7417-4446-839b-38c1dedbd0ab', 'N4', 28, 'word', 'ボーナス', 'ボーナス', 'thưởng', NULL, '名詞', 19, 'ボーナス', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('0f06a9f7-b32c-4a5b-ba01-24b45cf9414d', 'N4', 28, 'word', 'ゲーム', 'ゲーム', 'trò chơi, game', NULL, '名詞', 19, 'ゲーム', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('9af58017-8820-4966-8461-db8615748322', 'N4', 28, 'word', '番組', 'ばんぐみ', 'chương trình truyền hình', NULL, '名詞', 19, '番組', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('cf91c8fe-1a15-4273-997f-b499255a8657', 'N4', 28, 'word', '歌手', 'かしゅ', 'ca sĩ', NULL, '名詞', 19, '歌手', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('0680e5d3-2a79-42a6-a704-4569f07d949d', 'N4', 28, 'word', 'ドラマ', 'ドラマ', 'phim truyền hình', NULL, '名詞', 19, 'ドラマ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('29c9d069-d574-4bfe-bda7-4fe16c858d9b', 'N4', 28, 'word', '小説', 'しょうせつ', 'tiểu thuyết', NULL, '名詞', 19, '小説', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('4c5cff40-e82e-4dbd-8ac0-73bb042fd40a', 'N4', 28, 'word', '小説家', 'しょうせつか', 'tiểu thuyết gia, nhà văn', NULL, '名詞', 19, '小説家', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('253ee6cd-6652-4c1d-9119-3e15aeb70016', 'N4', 28, 'word', '息子', 'むすこ', 'con trai mình', NULL, '名詞', 19, '息子', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('58c220ad-b308-41de-9175-5baabcaa1519', 'N4', 28, 'word', '息子さん', 'むすこさん', 'con trai người khác', NULL, '名詞', 19, '息子さん', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('5951100a-9a01-4eed-ba34-be3ac98ea35c', 'N4', 28, 'word', '娘', 'むすめ', 'con gái mình', NULL, '名詞', 19, '娘', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('f4fc50a0-db1c-4625-b073-ffd409b8aa27', 'N4', 28, 'word', '娘さん', 'むすめさん', 'con gái người khác', NULL, '名詞', 19, '娘さん', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('20a0ec44-52e3-47d4-971a-9f65ab3988bd', 'N4', 28, 'word', '自分', 'じぶん', 'mình', NULL, '名詞', 19, '自分', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('f709afaa-823a-4a36-8446-0e53e06f96c7', 'N4', 28, 'word', 'しばらく', 'しばらく', 'một lúc', NULL, '副詞', 19, 'しばらく', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3f611f4a-e771-4bc9-b726-37c85520db2a', 'N4', 28, 'word', 'たいてい', 'たいてい', 'thường thì', NULL, '副詞', 19, 'たいてい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('56d40c61-a982-4e0f-a7e9-7aa8b9368e33', 'N4', 28, 'word', 'それに', 'それに', 'hơn nữa', NULL, '接続詞', 19, 'それに', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('5e1b507d-7166-41bf-9327-2b141f2ea891', 'N4', 28, 'word', 'それで', 'それで', 'vì thế', NULL, '接続詞', 19, 'それで', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('160e34fa-669e-48ae-b8d1-8a88c9d72263', 'N4', 28, 'word', '実は', 'じつは', 'thực ra', NULL, '副詞', 19, '実は', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e9a4eeb4-06c2-4992-b4e9-cf4ffd62548e', 'N4', 28, 'word', '会話', 'かいわ', 'hội thoại', NULL, '名詞', 19, '会話', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e6f4df79-7535-4212-9191-3429561e69e5', 'N4', 28, 'word', '体育館', 'たいいくかん', 'nhà thi đấu thể thao', NULL, '名詞', 19, '体育館', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('26460b98-9594-4428-9444-4252152a671b', 'N4', 28, 'word', '無料', 'むりょう', 'miễn phí', NULL, '名詞', 19, '無料', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('144840b3-4765-43db-8944-e30b7deca3c0', 'N4', 28, 'word', 'イベント', 'イベント', 'sự kiện', NULL, '名詞', 19, 'イベント', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('9b2be8bb-85d6-4a0d-9250-b28ab94112d5', 'N4', 28, 'word', 'お知らせ', 'おしらせ', 'thông báo', NULL, '名詞', 19, 'お知らせ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a9baabab-3dc2-49c0-b6fa-5017b56c7c89', 'N4', 28, 'word', '革', 'かわ', 'chất liệu da', NULL, '名詞', 19, '革', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7335c3d4-2b0b-4cc5-97cc-2d66e1199b9f', 'N4', 28, 'word', '安全', 'あんぜん', 'an toàn', NULL, 'な形容詞', 19, '安全', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7702cc9b-33ef-442b-91bc-096e3dd4e948', 'N4', 28, 'word', 'まずい', 'まずい', 'dở', NULL, 'い形容詞', 19, 'まずい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e9d42aef-157d-44c8-92c3-0e1d5fefe401', 'N4', 28, 'word', '面倒くさい', 'めんどうくさい', 'phiền phức', NULL, 'い形容詞', 19, '面倒くさい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('5ed2762e-164e-40c8-adf7-0d0b8f076cf7', 'N4', 28, 'word', '付き合う', 'つきあう', 'hẹn hò', NULL, '動詞', 19, '付き合う', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('69153561-5705-4ba1-941d-8cd75e114376', 'N4', 28, 'word', '誘う', 'さそう', 'mời, rủ', NULL, '動詞', 19, '誘う', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'この靴の値段はいくらですか。', 'Giá của đôi giày này bao nhiêu?', 'この靴の_____はいくらですか。', '値段', 'generated' from jp_vocab where id = 'fe322e73-6948-499d-a0a8-0f79a74627f9';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '今月の給料をもらった。', 'Tôi đã nhận lương tháng này.', '今月の_____をもらった。', '給料', 'generated' from jp_vocab where id = '32b349f3-7fec-45da-8cb3-9c5a0059ab52';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '夏にボーナスが出る。', 'Mùa hè có tiền thưởng.', '夏に_____が出る。', 'ボーナス', 'generated' from jp_vocab where id = '3058fdc3-7417-4446-839b-38c1dedbd0ab';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '子供はゲームが好きだ。', 'Trẻ con thích chơi game.', '子供は_____が好きだ。', 'ゲーム', 'generated' from jp_vocab where id = '0f06a9f7-b32c-4a5b-ba01-24b45cf9414d';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '好きなテレビ番組がある。', 'Có chương trình truyền hình tôi thích.', '好きなテレビ_____がある。', '番組', 'generated' from jp_vocab where id = '9af58017-8820-4966-8461-db8615748322';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彼女は有名な歌手だ。', 'Cô ấy là một ca sĩ nổi tiếng.', '彼女は有名な_____だ。', '歌手', 'generated' from jp_vocab where id = 'cf91c8fe-1a15-4273-997f-b499255a8657';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '毎晩ドラマを見る。', 'Mỗi tối tôi xem phim truyền hình.', '毎晩_____を見る。', 'ドラマ', 'generated' from jp_vocab where id = '0680e5d3-2a79-42a6-a704-4569f07d949d';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'この小説はとても面白い。', 'Cuốn tiểu thuyết này rất thú vị.', 'この_____はとても面白い。', '小説', 'generated' from jp_vocab where id = '29c9d069-d574-4bfe-bda7-4fe16c858d9b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彼は有名な小説家です。', 'Anh ấy là một nhà văn nổi tiếng.', '彼は有名な_____です。', '小説家', 'generated' from jp_vocab where id = '4c5cff40-e82e-4dbd-8ac0-73bb042fd40a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '息子は大学生です。', 'Con trai tôi là sinh viên đại học.', '_____は大学生です。', '息子', 'generated' from jp_vocab where id = '253ee6cd-6652-4c1d-9119-3e15aeb70016';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '息子さんはおいくつですか。', 'Con trai của anh/chị bao nhiêu tuổi rồi?', '_____はおいくつですか。', '息子さん', 'generated' from jp_vocab where id = '58c220ad-b308-41de-9175-5baabcaa1519';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '娘はまだ小さいです。', 'Con gái tôi vẫn còn nhỏ.', '_____はまだ小さいです。', '娘', 'generated' from jp_vocab where id = '5951100a-9a01-4eed-ba34-be3ac98ea35c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '娘さんは元気ですか。', 'Con gái của anh/chị khỏe không?', '_____は元気ですか。', '娘さん', 'generated' from jp_vocab where id = 'f4fc50a0-db1c-4625-b073-ffd409b8aa27';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '自分でやってみます。', 'Tôi sẽ tự mình thử làm.', '_____でやってみます。', '自分', 'generated' from jp_vocab where id = '20a0ec44-52e3-47d4-971a-9f65ab3988bd';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'しばらくお待ちください。', 'Xin hãy chờ một lúc.', '_____お待ちください。', 'しばらく', 'generated' from jp_vocab where id = 'f709afaa-823a-4a36-8446-0e53e06f96c7';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '週末はたいてい家にいます。', 'Cuối tuần tôi thường ở nhà.', '週末は_____家にいます。', 'たいてい', 'generated' from jp_vocab where id = '3f611f4a-e771-4bc9-b726-37c85520db2a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'この店は安い。それにおいしい。', 'Cửa hàng này rẻ. Hơn nữa còn ngon.', 'この店は安い。_____おいしい。', 'それに', 'generated' from jp_vocab where id = '56d40c61-a982-4e0f-a7e9-7aa8b9368e33';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '電車が遅れた。それで遅刻した。', 'Tàu bị trễ. Vì thế tôi đã đến muộn.', '電車が遅れた。_____遅刻した。', 'それで', 'generated' from jp_vocab where id = '5e1b507d-7166-41bf-9327-2b141f2ea891';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '実は、彼が心配です。', 'Thực ra, tôi lo lắng cho anh ấy.', '_____、彼が心配です。', '実は', 'generated' from jp_vocab where id = '160e34fa-669e-48ae-b8d1-8a88c9d72263';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '日本語で会話を練習する。', 'Luyện tập hội thoại bằng tiếng Nhật.', '日本語で_____を練習する。', '会話', 'generated' from jp_vocab where id = 'e9a4eeb4-06c2-4992-b4e9-cf4ffd62548e';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '体育館でバスケットボールをする。', 'Chơi bóng rổ trong nhà thi đấu thể thao.', '_____でバスケットボールをする。', '体育館', 'generated' from jp_vocab where id = 'e6f4df79-7535-4212-9191-3429561e69e5';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'このイベントは無料です。', 'Sự kiện này miễn phí.', 'このイベントは_____です。', '無料', 'generated' from jp_vocab where id = '26460b98-9594-4428-9444-4252152a671b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '来週、イベントがあります。', 'Tuần sau có một sự kiện.', '来週、_____があります。', 'イベント', 'generated' from jp_vocab where id = '144840b3-4765-43db-8944-e30b7deca3c0';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '新しいお知らせを確認してください。', 'Hãy kiểm tra thông báo mới.', '新しい_____を確認してください。', 'お知らせ', 'generated' from jp_vocab where id = '9b2be8bb-85d6-4a0d-9250-b28ab94112d5';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'このかばんは革でできている。', 'Cái túi này được làm bằng da.', 'このかばんは_____でできている。', '革', 'generated' from jp_vocab where id = 'a9baabab-3dc2-49c0-b6fa-5017b56c7c89';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'この道は安全です。', 'Con đường này an toàn.', 'この道は_____です。', '安全', 'generated' from jp_vocab where id = '7335c3d4-2b0b-4cc5-97cc-2d66e1199b9f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'この料理はまずい。', 'Món ăn này dở.', 'この料理は_____。', 'まずい', 'generated' from jp_vocab where id = '7702cc9b-33ef-442b-91bc-096e3dd4e948';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '掃除するのは面倒くさい。', 'Dọn dẹp thật phiền phức.', '掃除するのは_____。', '面倒くさい', 'generated' from jp_vocab where id = 'e9d42aef-157d-44c8-92c3-0e1d5fefe401';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彼女と三年付き合っている。', 'Tôi đã hẹn hò với cô ấy được 3 năm.', '彼女と三年_____いる。', '付き合って', 'generated' from jp_vocab where id = '5ed2762e-164e-40c8-adf7-0d0b8f076cf7';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '友達を映画に誘う。', 'Rủ bạn đi xem phim.', '友達を映画に_____。', '誘う', 'generated' from jp_vocab where id = '69153561-5705-4ba1-941d-8cd75e114376';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"値段" có nghĩa là gì?', 'hội thoại', 'mời, rủ', 'thưởng', 'giá cả', 'giá cả', 'generated' from jp_vocab where id = 'fe322e73-6948-499d-a0a8-0f79a74627f9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "giá cả"?', '面倒くさい', '値段', 'ボーナス', '自分', '値段', 'generated' from jp_vocab where id = 'fe322e73-6948-499d-a0a8-0f79a74627f9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"値段" đọc là gì?', 'むりょう', 'むすめ', 'しょうせつか', 'ねだん', 'ねだん', 'generated' from jp_vocab where id = 'fe322e73-6948-499d-a0a8-0f79a74627f9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: この靴の_____はいくらですか。', NULL, NULL, NULL, NULL, '値段', 'generated' from jp_vocab where id = 'fe322e73-6948-499d-a0a8-0f79a74627f9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"給料" có nghĩa là gì?', 'con gái mình', 'lương', 'vì thế', 'trò chơi, game', 'lương', 'generated' from jp_vocab where id = '32b349f3-7fec-45da-8cb3-9c5a0059ab52';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "lương"?', '給料', 'まずい', '歌手', '革', '給料', 'generated' from jp_vocab where id = '32b349f3-7fec-45da-8cb3-9c5a0059ab52';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"給料" đọc là gì?', 'かいわ', 'かわ', 'さそう', 'きゅうりょう', 'きゅうりょう', 'generated' from jp_vocab where id = '32b349f3-7fec-45da-8cb3-9c5a0059ab52';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 今月の_____をもらった。', NULL, NULL, NULL, NULL, '給料', 'generated' from jp_vocab where id = '32b349f3-7fec-45da-8cb3-9c5a0059ab52';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ボーナス" có nghĩa là gì?', 'trò chơi, game', 'dở', 'mình', 'thưởng', 'thưởng', 'generated' from jp_vocab where id = '3058fdc3-7417-4446-839b-38c1dedbd0ab';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thưởng"?', '娘', 'たいてい', 'ボーナス', 'それに', 'ボーナス', 'generated' from jp_vocab where id = '3058fdc3-7417-4446-839b-38c1dedbd0ab';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ボーナス" đọc là gì?', 'ボーナス', 'まずい', 'しょうせつか', 'じぶん', 'ボーナス', 'generated' from jp_vocab where id = '3058fdc3-7417-4446-839b-38c1dedbd0ab';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 夏に_____が出る。', NULL, NULL, NULL, NULL, 'ボーナス', 'generated' from jp_vocab where id = '3058fdc3-7417-4446-839b-38c1dedbd0ab';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ゲーム" có nghĩa là gì?', 'con trai mình', 'nhà thi đấu thể thao', 'trò chơi, game', 'dở', 'trò chơi, game', 'generated' from jp_vocab where id = '0f06a9f7-b32c-4a5b-ba01-24b45cf9414d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "trò chơi, game"?', '体育館', '息子さん', 'ボーナス', 'ゲーム', 'ゲーム', 'generated' from jp_vocab where id = '0f06a9f7-b32c-4a5b-ba01-24b45cf9414d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ゲーム" đọc là gì?', 'かいわ', 'かしゅ', 'たいいくかん', 'ゲーム', 'ゲーム', 'generated' from jp_vocab where id = '0f06a9f7-b32c-4a5b-ba01-24b45cf9414d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 子供は_____が好きだ。', NULL, NULL, NULL, NULL, 'ゲーム', 'generated' from jp_vocab where id = '0f06a9f7-b32c-4a5b-ba01-24b45cf9414d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"番組" có nghĩa là gì?', 'con trai người khác', 'chương trình truyền hình', 'một lúc', 'tiểu thuyết gia, nhà văn', 'chương trình truyền hình', 'generated' from jp_vocab where id = '9af58017-8820-4966-8461-db8615748322';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chương trình truyền hình"?', '息子さん', '小説', '番組', '歌手', '番組', 'generated' from jp_vocab where id = '9af58017-8820-4966-8461-db8615748322';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"番組" đọc là gì?', 'イベント', 'ばんぐみ', 'むすめさん', 'しょうせつ', 'ばんぐみ', 'generated' from jp_vocab where id = '9af58017-8820-4966-8461-db8615748322';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 好きなテレビ_____がある。', NULL, NULL, NULL, NULL, '番組', 'generated' from jp_vocab where id = '9af58017-8820-4966-8461-db8615748322';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"歌手" có nghĩa là gì?', 'con gái người khác', 'ca sĩ', 'con trai người khác', 'thông báo', 'ca sĩ', 'generated' from jp_vocab where id = 'cf91c8fe-1a15-4273-997f-b499255a8657';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "ca sĩ"?', '誘う', '無料', '息子さん', '歌手', '歌手', 'generated' from jp_vocab where id = 'cf91c8fe-1a15-4273-997f-b499255a8657';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"歌手" đọc là gì?', 'かしゅ', 'つきあう', 'おしらせ', 'かわ', 'かしゅ', 'generated' from jp_vocab where id = 'cf91c8fe-1a15-4273-997f-b499255a8657';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 彼女は有名な_____だ。', NULL, NULL, NULL, NULL, '歌手', 'generated' from jp_vocab where id = 'cf91c8fe-1a15-4273-997f-b499255a8657';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ドラマ" có nghĩa là gì?', 'nhà thi đấu thể thao', 'vì thế', 'phim truyền hình', 'tiểu thuyết gia, nhà văn', 'phim truyền hình', 'generated' from jp_vocab where id = '0680e5d3-2a79-42a6-a704-4569f07d949d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phim truyền hình"?', '歌手', '会話', '誘う', 'ドラマ', 'ドラマ', 'generated' from jp_vocab where id = '0680e5d3-2a79-42a6-a704-4569f07d949d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ドラマ" đọc là gì?', 'おしらせ', 'ドラマ', 'むすめ', 'ねだん', 'ドラマ', 'generated' from jp_vocab where id = '0680e5d3-2a79-42a6-a704-4569f07d949d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 毎晩_____を見る。', NULL, NULL, NULL, NULL, 'ドラマ', 'generated' from jp_vocab where id = '0680e5d3-2a79-42a6-a704-4569f07d949d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"小説" có nghĩa là gì?', 'trò chơi, game', 'thưởng', 'tiểu thuyết', 'hội thoại', 'tiểu thuyết', 'generated' from jp_vocab where id = '29c9d069-d574-4bfe-bda7-4fe16c858d9b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tiểu thuyết"?', 'ゲーム', '給料', '小説家', '小説', '小説', 'generated' from jp_vocab where id = '29c9d069-d574-4bfe-bda7-4fe16c858d9b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"小説" đọc là gì?', 'じつは', 'つきあう', 'しばらく', 'しょうせつ', 'しょうせつ', 'generated' from jp_vocab where id = '29c9d069-d574-4bfe-bda7-4fe16c858d9b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: この_____はとても面白い。', NULL, NULL, NULL, NULL, '小説', 'generated' from jp_vocab where id = '29c9d069-d574-4bfe-bda7-4fe16c858d9b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"小説家" có nghĩa là gì?', 'tiểu thuyết gia, nhà văn', 'con gái mình', 'thưởng', 'hội thoại', 'tiểu thuyết gia, nhà văn', 'generated' from jp_vocab where id = '4c5cff40-e82e-4dbd-8ac0-73bb042fd40a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tiểu thuyết gia, nhà văn"?', '値段', 'ボーナス', '給料', '小説家', '小説家', 'generated' from jp_vocab where id = '4c5cff40-e82e-4dbd-8ac0-73bb042fd40a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"小説家" đọc là gì?', 'しばらく', 'むすこさん', 'じぶん', 'しょうせつか', 'しょうせつか', 'generated' from jp_vocab where id = '4c5cff40-e82e-4dbd-8ac0-73bb042fd40a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 彼は有名な_____です。', NULL, NULL, NULL, NULL, '小説家', 'generated' from jp_vocab where id = '4c5cff40-e82e-4dbd-8ac0-73bb042fd40a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"息子" có nghĩa là gì?', 'con trai mình', 'phiền phức', 'thưởng', 'chất liệu da', 'con trai mình', 'generated' from jp_vocab where id = '253ee6cd-6652-4c1d-9119-3e15aeb70016';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "con trai mình"?', '息子', '実は', '息子さん', '歌手', '息子', 'generated' from jp_vocab where id = '253ee6cd-6652-4c1d-9119-3e15aeb70016';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"息子" đọc là gì?', 'むすこ', 'イベント', 'ドラマ', 'まずい', 'むすこ', 'generated' from jp_vocab where id = '253ee6cd-6652-4c1d-9119-3e15aeb70016';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____は大学生です。', NULL, NULL, NULL, NULL, '息子', 'generated' from jp_vocab where id = '253ee6cd-6652-4c1d-9119-3e15aeb70016';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"息子さん" có nghĩa là gì?', 'con gái mình', 'một lúc', 'thường thì', 'con trai người khác', 'con trai người khác', 'generated' from jp_vocab where id = '58c220ad-b308-41de-9175-5baabcaa1519';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "con trai người khác"?', 'それで', '小説家', '息子さん', '面倒くさい', '息子さん', 'generated' from jp_vocab where id = '58c220ad-b308-41de-9175-5baabcaa1519';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"息子さん" đọc là gì?', 'イベント', 'むすこさん', 'しばらく', 'それで', 'むすこさん', 'generated' from jp_vocab where id = '58c220ad-b308-41de-9175-5baabcaa1519';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____はおいくつですか。', NULL, NULL, NULL, NULL, '息子さん', 'generated' from jp_vocab where id = '58c220ad-b308-41de-9175-5baabcaa1519';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"娘" có nghĩa là gì?', 'hơn nữa', 'ca sĩ', 'vì thế', 'con gái mình', 'con gái mình', 'generated' from jp_vocab where id = '5951100a-9a01-4eed-ba34-be3ac98ea35c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "con gái mình"?', '無料', '実は', '娘', '息子', '娘', 'generated' from jp_vocab where id = '5951100a-9a01-4eed-ba34-be3ac98ea35c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"娘" đọc là gì?', 'しょうせつ', 'むすこ', 'むすめ', 'むすこさん', 'むすめ', 'generated' from jp_vocab where id = '5951100a-9a01-4eed-ba34-be3ac98ea35c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____はまだ小さいです。', NULL, NULL, NULL, NULL, '娘', 'generated' from jp_vocab where id = '5951100a-9a01-4eed-ba34-be3ac98ea35c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"娘さん" có nghĩa là gì?', 'giá cả', 'hẹn hò', 'con gái người khác', 'một lúc', 'con gái người khác', 'generated' from jp_vocab where id = 'f4fc50a0-db1c-4625-b073-ffd409b8aa27';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "con gái người khác"?', '会話', '娘さん', '給料', 'イベント', '娘さん', 'generated' from jp_vocab where id = 'f4fc50a0-db1c-4625-b073-ffd409b8aa27';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"娘さん" đọc là gì?', 'きゅうりょう', 'むすめさん', 'じぶん', 'ねだん', 'むすめさん', 'generated' from jp_vocab where id = 'f4fc50a0-db1c-4625-b073-ffd409b8aa27';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____は元気ですか。', NULL, NULL, NULL, NULL, '娘さん', 'generated' from jp_vocab where id = 'f4fc50a0-db1c-4625-b073-ffd409b8aa27';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"自分" có nghĩa là gì?', 'tiểu thuyết gia, nhà văn', 'lương', 'mình', 'thông báo', 'mình', 'generated' from jp_vocab where id = '20a0ec44-52e3-47d4-971a-9f65ab3988bd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "mình"?', '小説家', '小説', '自分', '無料', '自分', 'generated' from jp_vocab where id = '20a0ec44-52e3-47d4-971a-9f65ab3988bd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"自分" đọc là gì?', 'ボーナス', 'じぶん', 'むすめさん', 'たいてい', 'じぶん', 'generated' from jp_vocab where id = '20a0ec44-52e3-47d4-971a-9f65ab3988bd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____でやってみます。', NULL, NULL, NULL, NULL, '自分', 'generated' from jp_vocab where id = '20a0ec44-52e3-47d4-971a-9f65ab3988bd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"しばらく" có nghĩa là gì?', 'một lúc', 'con gái người khác', 'lương', 'chất liệu da', 'một lúc', 'generated' from jp_vocab where id = 'f709afaa-823a-4a36-8446-0e53e06f96c7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "một lúc"?', '歌手', '給料', 'しばらく', '娘', 'しばらく', 'generated' from jp_vocab where id = 'f709afaa-823a-4a36-8446-0e53e06f96c7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"しばらく" đọc là gì?', 'たいてい', 'さそう', 'しばらく', 'ゲーム', 'しばらく', 'generated' from jp_vocab where id = 'f709afaa-823a-4a36-8446-0e53e06f96c7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____お待ちください。', NULL, NULL, NULL, NULL, 'しばらく', 'generated' from jp_vocab where id = 'f709afaa-823a-4a36-8446-0e53e06f96c7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"たいてい" có nghĩa là gì?', 'giá cả', 'miễn phí', 'phim truyền hình', 'thường thì', 'thường thì', 'generated' from jp_vocab where id = '3f611f4a-e771-4bc9-b726-37c85520db2a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thường thì"?', 'しばらく', '小説', 'それに', 'たいてい', 'たいてい', 'generated' from jp_vocab where id = '3f611f4a-e771-4bc9-b726-37c85520db2a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"たいてい" đọc là gì?', 'きゅうりょう', 'たいいくかん', 'むすめさん', 'たいてい', 'たいてい', 'generated' from jp_vocab where id = '3f611f4a-e771-4bc9-b726-37c85520db2a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 週末は_____家にいます。', NULL, NULL, NULL, NULL, 'たいてい', 'generated' from jp_vocab where id = '3f611f4a-e771-4bc9-b726-37c85520db2a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"それに" có nghĩa là gì?', 'thông báo', 'thường thì', 'một lúc', 'hơn nữa', 'hơn nữa', 'generated' from jp_vocab where id = '56d40c61-a982-4e0f-a7e9-7aa8b9368e33';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "hơn nữa"?', '自分', 'それに', '会話', '息子さん', 'それに', 'generated' from jp_vocab where id = '56d40c61-a982-4e0f-a7e9-7aa8b9368e33';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"それに" đọc là gì?', 'それに', 'しばらく', 'めんどうくさい', 'かいわ', 'それに', 'generated' from jp_vocab where id = '56d40c61-a982-4e0f-a7e9-7aa8b9368e33';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: この店は安い。_____おいしい。', NULL, NULL, NULL, NULL, 'それに', 'generated' from jp_vocab where id = '56d40c61-a982-4e0f-a7e9-7aa8b9368e33';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"それで" có nghĩa là gì?', 'trò chơi, game', 'miễn phí', 'một lúc', 'vì thế', 'vì thế', 'generated' from jp_vocab where id = '5e1b507d-7166-41bf-9327-2b141f2ea891';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vì thế"?', 'それで', 'ボーナス', '安全', '小説家', 'それで', 'generated' from jp_vocab where id = '5e1b507d-7166-41bf-9327-2b141f2ea891';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"それで" đọc là gì?', 'それで', 'むすめ', 'しばらく', 'たいいくかん', 'それで', 'generated' from jp_vocab where id = '5e1b507d-7166-41bf-9327-2b141f2ea891';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 電車が遅れた。_____遅刻した。', NULL, NULL, NULL, NULL, 'それで', 'generated' from jp_vocab where id = '5e1b507d-7166-41bf-9327-2b141f2ea891';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"実は" có nghĩa là gì?', 'thực ra', 'thường thì', 'phiền phức', 'thông báo', 'thực ra', 'generated' from jp_vocab where id = '160e34fa-669e-48ae-b8d1-8a88c9d72263';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thực ra"?', '息子さん', '実は', 'まずい', '革', '実は', 'generated' from jp_vocab where id = '160e34fa-669e-48ae-b8d1-8a88c9d72263';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"実は" đọc là gì?', 'むすめさん', 'たいてい', 'じつは', 'しょうせつ', 'じつは', 'generated' from jp_vocab where id = '160e34fa-669e-48ae-b8d1-8a88c9d72263';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____、彼が心配です。', NULL, NULL, NULL, NULL, '実は', 'generated' from jp_vocab where id = '160e34fa-669e-48ae-b8d1-8a88c9d72263';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"会話" có nghĩa là gì?', 'con gái mình', 'hội thoại', 'thực ra', 'con trai người khác', 'hội thoại', 'generated' from jp_vocab where id = 'e9a4eeb4-06c2-4992-b4e9-cf4ffd62548e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "hội thoại"?', 'それに', '革', 'ボーナス', '会話', '会話', 'generated' from jp_vocab where id = 'e9a4eeb4-06c2-4992-b4e9-cf4ffd62548e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"会話" đọc là gì?', 'まずい', 'しばらく', 'さそう', 'かいわ', 'かいわ', 'generated' from jp_vocab where id = 'e9a4eeb4-06c2-4992-b4e9-cf4ffd62548e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 日本語で_____を練習する。', NULL, NULL, NULL, NULL, '会話', 'generated' from jp_vocab where id = 'e9a4eeb4-06c2-4992-b4e9-cf4ffd62548e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"体育館" có nghĩa là gì?', 'nhà thi đấu thể thao', 'lương', 'an toàn', 'con trai người khác', 'nhà thi đấu thể thao', 'generated' from jp_vocab where id = 'e6f4df79-7535-4212-9191-3429561e69e5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhà thi đấu thể thao"?', '誘う', 'たいてい', 'ドラマ', '体育館', '体育館', 'generated' from jp_vocab where id = 'e6f4df79-7535-4212-9191-3429561e69e5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"体育館" đọc là gì?', 'むすこ', 'あんぜん', 'むすめ', 'たいいくかん', 'たいいくかん', 'generated' from jp_vocab where id = 'e6f4df79-7535-4212-9191-3429561e69e5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____でバスケットボールをする。', NULL, NULL, NULL, NULL, '体育館', 'generated' from jp_vocab where id = 'e6f4df79-7535-4212-9191-3429561e69e5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"無料" có nghĩa là gì?', 'hơn nữa', 'miễn phí', 'chất liệu da', 'tiểu thuyết gia, nhà văn', 'miễn phí', 'generated' from jp_vocab where id = '26460b98-9594-4428-9444-4252152a671b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "miễn phí"?', 'それに', '値段', '無料', '娘', '無料', 'generated' from jp_vocab where id = '26460b98-9594-4428-9444-4252152a671b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"無料" đọc là gì?', 'かいわ', 'むりょう', 'じつは', 'しょうせつか', 'むりょう', 'generated' from jp_vocab where id = '26460b98-9594-4428-9444-4252152a671b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: このイベントは_____です。', NULL, NULL, NULL, NULL, '無料', 'generated' from jp_vocab where id = '26460b98-9594-4428-9444-4252152a671b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"イベント" có nghĩa là gì?', 'an toàn', 'sự kiện', 'hẹn hò', 'thông báo', 'sự kiện', 'generated' from jp_vocab where id = '144840b3-4765-43db-8944-e30b7deca3c0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sự kiện"?', '付き合う', 'イベント', '息子', 'それに', 'イベント', 'generated' from jp_vocab where id = '144840b3-4765-43db-8944-e30b7deca3c0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"イベント" đọc là gì?', 'イベント', 'じつは', 'それに', 'しょうせつか', 'イベント', 'generated' from jp_vocab where id = '144840b3-4765-43db-8944-e30b7deca3c0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 来週、_____があります。', NULL, NULL, NULL, NULL, 'イベント', 'generated' from jp_vocab where id = '144840b3-4765-43db-8944-e30b7deca3c0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"お知らせ" có nghĩa là gì?', 'thường thì', 'nhà thi đấu thể thao', 'tiểu thuyết', 'thông báo', 'thông báo', 'generated' from jp_vocab where id = '9b2be8bb-85d6-4a0d-9250-b28ab94112d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thông báo"?', 'お知らせ', '革', '誘う', 'ボーナス', 'お知らせ', 'generated' from jp_vocab where id = '9b2be8bb-85d6-4a0d-9250-b28ab94112d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"お知らせ" đọc là gì?', 'じつは', 'むすこさん', 'おしらせ', 'かしゅ', 'おしらせ', 'generated' from jp_vocab where id = '9b2be8bb-85d6-4a0d-9250-b28ab94112d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 新しい_____を確認してください。', NULL, NULL, NULL, NULL, 'お知らせ', 'generated' from jp_vocab where id = '9b2be8bb-85d6-4a0d-9250-b28ab94112d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"革" có nghĩa là gì?', 'một lúc', 'chất liệu da', 'thường thì', 'tiểu thuyết', 'chất liệu da', 'generated' from jp_vocab where id = 'a9baabab-3dc2-49c0-b6fa-5017b56c7c89';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chất liệu da"?', 'イベント', 'ゲーム', '革', '実は', '革', 'generated' from jp_vocab where id = 'a9baabab-3dc2-49c0-b6fa-5017b56c7c89';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"革" đọc là gì?', 'かわ', 'むすめさん', 'かしゅ', 'おしらせ', 'かわ', 'generated' from jp_vocab where id = 'a9baabab-3dc2-49c0-b6fa-5017b56c7c89';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: このかばんは_____でできている。', NULL, NULL, NULL, NULL, '革', 'generated' from jp_vocab where id = 'a9baabab-3dc2-49c0-b6fa-5017b56c7c89';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"安全" có nghĩa là gì?', 'thưởng', 'một lúc', 'an toàn', 'hơn nữa', 'an toàn', 'generated' from jp_vocab where id = '7335c3d4-2b0b-4cc5-97cc-2d66e1199b9f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "an toàn"?', '安全', '給料', '娘さん', 'イベント', '安全', 'generated' from jp_vocab where id = '7335c3d4-2b0b-4cc5-97cc-2d66e1199b9f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"安全" đọc là gì?', 'さそう', 'たいてい', 'それで', 'あんぜん', 'あんぜん', 'generated' from jp_vocab where id = '7335c3d4-2b0b-4cc5-97cc-2d66e1199b9f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: この道は_____です。', NULL, NULL, NULL, NULL, '安全', 'generated' from jp_vocab where id = '7335c3d4-2b0b-4cc5-97cc-2d66e1199b9f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"まずい" có nghĩa là gì?', 'dở', 'miễn phí', 'mời, rủ', 'thường thì', 'dở', 'generated' from jp_vocab where id = '7702cc9b-33ef-442b-91bc-096e3dd4e948';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "dở"?', '小説家', '娘', 'たいてい', 'まずい', 'まずい', 'generated' from jp_vocab where id = '7702cc9b-33ef-442b-91bc-096e3dd4e948';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"まずい" đọc là gì?', 'しばらく', 'めんどうくさい', 'まずい', 'あんぜん', 'まずい', 'generated' from jp_vocab where id = '7702cc9b-33ef-442b-91bc-096e3dd4e948';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: この料理は_____。', NULL, NULL, NULL, NULL, 'まずい', 'generated' from jp_vocab where id = '7702cc9b-33ef-442b-91bc-096e3dd4e948';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"面倒くさい" có nghĩa là gì?', 'một lúc', 'sự kiện', 'phiền phức', 'miễn phí', 'phiền phức', 'generated' from jp_vocab where id = 'e9d42aef-157d-44c8-92c3-0e1d5fefe401';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phiền phức"?', '面倒くさい', '息子さん', '無料', 'たいてい', '面倒くさい', 'generated' from jp_vocab where id = 'e9d42aef-157d-44c8-92c3-0e1d5fefe401';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"面倒くさい" đọc là gì?', 'それに', 'むすこさん', 'むすめさん', 'めんどうくさい', 'めんどうくさい', 'generated' from jp_vocab where id = 'e9d42aef-157d-44c8-92c3-0e1d5fefe401';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 掃除するのは_____。', NULL, NULL, NULL, NULL, '面倒くさい', 'generated' from jp_vocab where id = 'e9d42aef-157d-44c8-92c3-0e1d5fefe401';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"付き合う" có nghĩa là gì?', 'ca sĩ', 'hẹn hò', 'một lúc', 'mình', 'hẹn hò', 'generated' from jp_vocab where id = '5ed2762e-164e-40c8-adf7-0d0b8f076cf7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "hẹn hò"?', '付き合う', '番組', '息子', 'それに', '付き合う', 'generated' from jp_vocab where id = '5ed2762e-164e-40c8-adf7-0d0b8f076cf7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"付き合う" đọc là gì?', 'つきあう', 'じぶん', 'イベント', 'きゅうりょう', 'つきあう', 'generated' from jp_vocab where id = '5ed2762e-164e-40c8-adf7-0d0b8f076cf7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 彼女と三年_____いる。', NULL, NULL, NULL, NULL, '付き合って', 'generated' from jp_vocab where id = '5ed2762e-164e-40c8-adf7-0d0b8f076cf7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"誘う" có nghĩa là gì?', 'mời, rủ', 'một lúc', 'lương', 'thực ra', 'mời, rủ', 'generated' from jp_vocab where id = '69153561-5705-4ba1-941d-8cd75e114376';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "mời, rủ"?', '面倒くさい', '会話', '誘う', '小説', '誘う', 'generated' from jp_vocab where id = '69153561-5705-4ba1-941d-8cd75e114376';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"誘う" đọc là gì?', 'さそう', 'しょうせつ', 'たいてい', 'ゲーム', 'さそう', 'generated' from jp_vocab where id = '69153561-5705-4ba1-941d-8cd75e114376';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 友達を映画に_____。', NULL, NULL, NULL, NULL, '誘う', 'generated' from jp_vocab where id = '69153561-5705-4ba1-941d-8cd75e114376';
