-- ============================================================
-- jp-go — Từ vựng N4, 課31 (34 từ, trọn lesson).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 21.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('67b6acc0-84ee-49ce-b56f-db9b76ddb164', 'N4', 31, 'word', '見つける', 'みつける', 'tìm thấy', NULL, '動詞', 21, '見つける', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3267e5fe-b142-45e6-bd7b-c31a4a650b55', 'N4', 31, 'word', '続ける', 'つづける', 'tiếp tục', NULL, '動詞', 21, '続ける', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('6d08adfa-e67e-4881-8aef-17588e243cbe', 'N4', 31, 'word', '取る', 'とる', 'xin (nghỉ)', 'thường dùng dạng [休みを〜]', '動詞', 21, '取る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('64b12e55-a0b4-4160-ad87-a171d8a033eb', 'N4', 31, 'word', '受ける', 'うける', 'dự (thi)', 'thường dùng dạng [試験を〜]', '動詞', 21, '受ける', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7b34d2e7-77d1-4a11-b038-257ce57af7a5', 'N4', 31, 'word', '申し込む', 'もうしこむ', 'đăng ký', NULL, '動詞', 21, '申し込む', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('df2109e9-1bb5-4359-ab88-3c239c67dabe', 'N4', 31, 'word', '休憩する', 'きゅうけいする', 'nghỉ giải lao', NULL, '動詞', 21, '休憩する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e0c08012-6306-4870-a6bc-50a34dabf3ac', 'N4', 31, 'word', '残る', 'のこる', 'sót lại, thừa lại; ở lại', NULL, '動詞', 21, '残る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('9408e28b-9fa1-4606-973c-23b0e3b0488b', 'N4', 31, 'word', '卒業する', 'そつぎょうする', 'tốt nghiệp', NULL, '動詞', 21, '卒業する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('55e96fc8-ffc8-418c-a4fe-c9564e12f842', 'N4', 31, 'word', '閉じる', 'とじる', 'nhắm mắt', 'thường dùng dạng [目を〜]', '動詞', 21, '閉じる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('73bbde67-db4f-43e5-b9ae-866edbd61b3f', 'N4', 31, 'word', '連休', 'れんきゅう', 'kì nghỉ dài, ngày nghỉ liên tục', NULL, '名詞', 21, '連休', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('acff302d-b397-4d49-8c98-7508b804a197', 'N4', 31, 'word', '作文', 'さくぶん', 'bài tập làm văn', NULL, '名詞', 21, '作文', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('ad2e4aa5-11cc-4505-b743-7106a1259925', 'N4', 31, 'word', '発表', 'はっぴょう', 'phát biểu, công bố', NULL, '名詞', 21, '発表', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('496c4cfa-b7a3-4aad-a6b9-53ee0b735bbb', 'N4', 31, 'word', '展覧会', 'てんらんかい', 'cuộc triển lãm', NULL, '名詞', 21, '展覧会', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('51cb10bd-13eb-46ae-95ce-66fdbfb314c7', 'N4', 31, 'word', '結婚式', 'けっこんしき', 'lễ cưới', NULL, '名詞', 21, '結婚式', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('332d8164-39a7-4450-b923-51ae9d0b0287', 'N4', 31, 'word', '葬式', 'そうしき', 'đám tang', NULL, '名詞', 21, '葬式', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('f28c5473-cc48-481b-be69-cac54db4b9c5', 'N4', 31, 'word', '式', 'しき', 'lễ', NULL, '名詞', 21, '式', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('35c0541e-8218-47bd-ae02-4c7425bb1901', 'N4', 31, 'word', '本社', 'ほんしゃ', 'trụ sở chính', NULL, '名詞', 21, '本社', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('dad43b79-6cc9-4858-a8d1-0f756915951a', 'N4', 31, 'word', '支店', 'してん', 'cửa hàng chi nhánh', NULL, '名詞', 21, '支店', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('59c4c2e9-2c0e-42a1-8793-a09ed92c44f8', 'N4', 31, 'word', '教会', 'きょうかい', 'nhà thờ', NULL, '名詞', 21, '教会', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('afbde83a-d959-4d7c-809f-7b9ae805e41b', 'N4', 31, 'word', '和室', 'わしつ', 'phòng kiểu Nhật', NULL, '名詞', 21, '和室', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('abbd09ba-95d5-4ae7-980f-b09429063a2d', 'N4', 31, 'word', '大学院', 'だいがくいん', 'cao học', NULL, '名詞', 21, '大学院', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d0e61890-9dcf-4ac5-9064-2bd56493c234', 'N4', 31, 'word', '動物園', 'どうぶつえん', 'sở thú', NULL, '名詞', 21, '動物園', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('646e6db0-881f-458c-b5a4-1911608d97b3', 'N4', 31, 'word', '温泉', 'おんせん', 'suối nước nóng', NULL, '名詞', 21, '温泉', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7abdd4d9-5898-4f27-a496-1a18045a3d59', 'N4', 31, 'word', '帰り', 'かえり', 'sự trở về', NULL, '名詞', 21, '帰り', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('70fc69d0-95ce-4a1b-9f83-99a09f647d00', 'N4', 31, 'word', 'お子さん', 'おこさん', 'con (của người khác)', NULL, '名詞', 21, 'お子さん', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b37414d7-ea95-4556-b8f9-42d5462c3d02', 'N4', 31, 'word', 'ずっと', 'ずっと', 'suốt', NULL, '副詞', 21, 'ずっと', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('748543b0-7d9b-4e6e-8401-fbedba2ce43a', 'N4', 31, 'word', '入学試験', 'にゅうがくしけん', 'kì thi đầu vào', NULL, '名詞', 21, '入学試験', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('45e0c591-fa42-4057-b088-202636e6f7f7', 'N4', 31, 'word', '都会', 'とかい', 'thành phố lớn', NULL, '名詞', 21, '都会', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('4c6a38c6-c434-453f-a0a6-a472f910d161', 'N4', 31, 'word', '記念日', 'きねんび', 'ngày kỉ niệm', NULL, '名詞', 21, '記念日', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('993b6fdf-7bf2-40c8-811d-f205bc0ebdf9', 'N4', 31, 'word', 'プロポーズ', 'プロポーズ', 'cầu hôn, tỏ tình', NULL, '名詞', 21, 'プロポーズ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a798b1cc-50d8-493e-aa13-760f200bcb0a', 'N4', 31, 'word', '乾杯', 'かんぱい', 'cạn ly', NULL, '名詞', 21, '乾杯', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('46131d08-dead-4fc2-8bf5-21cc0af73886', 'N4', 31, 'word', '過ぎる', 'すぎる', 'quá', NULL, '動詞', 21, '過ぎる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e510b217-41ad-45c0-be29-cae04b4014ad', 'N4', 31, 'word', '村', 'むら', 'làng', NULL, '名詞', 21, '村', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('2639dd8c-d041-4614-bd0e-72e51a81bb99', 'N4', 31, 'word', '田舎', 'いなか', 'nông thôn', NULL, '名詞', 21, '田舎', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '探していた本を見つけた。', 'Tôi đã tìm thấy cuốn sách mình đang tìm.', '探していた本を_____た。', '見つけ', 'generated' from jp_vocab where id = '67b6acc0-84ee-49ce-b56f-db9b76ddb164';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '毎日運動を続ける。', 'Tiếp tục tập thể dục mỗi ngày.', '毎日運動を_____。', '続ける', 'generated' from jp_vocab where id = '3267e5fe-b142-45e6-bd7b-c31a4a650b55';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '来週、休みを取る。', 'Tuần sau tôi sẽ xin nghỉ.', '来週、休みを_____。', '取る', 'generated' from jp_vocab where id = '6d08adfa-e67e-4881-8aef-17588e243cbe';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '来月、試験を受ける。', 'Tháng sau tôi sẽ dự thi.', '来月、試験を_____。', '受ける', 'generated' from jp_vocab where id = '64b12e55-a0b4-4160-ad87-a171d8a033eb';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '大学に申し込む。', 'Đăng ký vào đại học.', '大学に_____。', '申し込む', 'generated' from jp_vocab where id = '7b34d2e7-77d1-4a11-b038-257ce57af7a5';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '少し休憩する。', 'Nghỉ giải lao một chút.', '少し_____。', '休憩する', 'generated' from jp_vocab where id = 'df2109e9-1bb5-4359-ab88-3c239c67dabe';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'まだ仕事が残っている。', 'Vẫn còn công việc chưa xong.', 'まだ仕事が_____いる。', '残って', 'generated' from jp_vocab where id = 'e0c08012-6306-4870-a6bc-50a34dabf3ac';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '来年、大学を卒業する。', 'Năm sau tôi sẽ tốt nghiệp đại học.', '来年、大学を_____。', '卒業する', 'generated' from jp_vocab where id = '9408e28b-9fa1-4606-973c-23b0e3b0488b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '目を閉じて考える。', 'Nhắm mắt suy nghĩ.', '目を_____て考える。', '閉じ', 'generated' from jp_vocab where id = '55e96fc8-ffc8-418c-a4fe-c9564e12f842';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '今年の連休は長い。', 'Kì nghỉ dài năm nay khá dài.', '今年の_____は長い。', '連休', 'generated' from jp_vocab where id = '73bbde67-db4f-43e5-b9ae-866edbd61b3f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '日本語で作文を書く。', 'Viết bài tập làm văn bằng tiếng Nhật.', '日本語で_____を書く。', '作文', 'generated' from jp_vocab where id = 'acff302d-b397-4d49-8c98-7508b804a197';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '研究の結果を発表する。', 'Công bố kết quả nghiên cứu.', '研究の結果を_____する。', '発表', 'generated' from jp_vocab where id = 'ad2e4aa5-11cc-4505-b743-7106a1259925';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '絵の展覧会を見に行く。', 'Đi xem cuộc triển lãm tranh.', '絵の_____を見に行く。', '展覧会', 'generated' from jp_vocab where id = '496c4cfa-b7a3-4aad-a6b9-53ee0b735bbb';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '来月、結婚式を挙げる。', 'Tháng sau tôi sẽ tổ chức lễ cưới.', '来月、_____を挙げる。', '結婚式', 'generated' from jp_vocab where id = '51cb10bd-13eb-46ae-95ce-66fdbfb314c7';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '葬式に参加する。', 'Tham dự đám tang.', '_____に参加する。', '葬式', 'generated' from jp_vocab where id = '332d8164-39a7-4450-b923-51ae9d0b0287';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '卒業式は三月にある。', 'Lễ tốt nghiệp diễn ra vào tháng 3.', '卒業_____は三月にある。', '式', 'generated' from jp_vocab where id = 'f28c5473-cc48-481b-be69-cac54db4b9c5';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '本社は東京にある。', 'Trụ sở chính ở Tokyo.', '_____は東京にある。', '本社', 'generated' from jp_vocab where id = '35c0541e-8218-47bd-ae02-4c7425bb1901';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '大阪に支店を作る。', 'Mở chi nhánh ở Osaka.', '大阪に_____を作る。', '支店', 'generated' from jp_vocab where id = 'dad43b79-6cc9-4858-a8d1-0f756915951a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '日曜日に教会へ行く。', 'Chủ nhật đi nhà thờ.', '日曜日に_____へ行く。', '教会', 'generated' from jp_vocab where id = '59c4c2e9-2c0e-42a1-8793-a09ed92c44f8';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '和室で寝る。', 'Ngủ trong phòng kiểu Nhật.', '_____で寝る。', '和室', 'generated' from jp_vocab where id = 'afbde83a-d959-4d7c-809f-7b9ae805e41b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '大学院に進む。', 'Học lên cao học.', '_____に進む。', '大学院', 'generated' from jp_vocab where id = 'abbd09ba-95d5-4ae7-980f-b09429063a2d';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '家族で動物園に行った。', 'Cả nhà đã đi sở thú.', '家族で_____に行った。', '動物園', 'generated' from jp_vocab where id = 'd0e61890-9dcf-4ac5-9064-2bd56493c234';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '温泉に入る。', 'Tắm suối nước nóng.', '_____に入る。', '温泉', 'generated' from jp_vocab where id = '646e6db0-881f-458c-b5a4-1911608d97b3';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '帰りに買い物をする。', 'Mua sắm trên đường về.', '_____に買い物をする。', '帰り', 'generated' from jp_vocab where id = '7abdd4d9-5898-4f27-a496-1a18045a3d59';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お子さんは何歳ですか。', 'Con của anh/chị bao nhiêu tuổi?', '_____は何歳ですか。', 'お子さん', 'generated' from jp_vocab where id = '70fc69d0-95ce-4a1b-9f83-99a09f647d00';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ずっと待っていた。', 'Tôi đã chờ suốt.', '_____待っていた。', 'ずっと', 'generated' from jp_vocab where id = 'b37414d7-ea95-4556-b8f9-42d5462c3d02';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '入学試験に合格する。', 'Đỗ kì thi đầu vào.', '_____に合格する。', '入学試験', 'generated' from jp_vocab where id = '748543b0-7d9b-4e6e-8401-fbedba2ce43a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彼は都会で働いている。', 'Anh ấy đang làm việc ở thành phố lớn.', '彼は_____で働いている。', '都会', 'generated' from jp_vocab where id = '45e0c591-fa42-4057-b088-202636e6f7f7';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '今日は結婚記念日です。', 'Hôm nay là ngày kỷ niệm kết hôn.', '今日は結婚_____です。', '記念日', 'generated' from jp_vocab where id = '4c6a38c6-c434-453f-a0a6-a472f910d161';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彼にプロポーズされた。', 'Tôi đã được anh ấy cầu hôn.', '彼に_____された。', 'プロポーズ', 'generated' from jp_vocab where id = '993b6fdf-7bf2-40c8-811d-f205bc0ebdf9';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'みんなで乾杯する。', 'Mọi người cùng cạn ly.', 'みんなで_____する。', '乾杯', 'generated' from jp_vocab where id = 'a798b1cc-50d8-493e-aa13-760f200bcb0a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'もう九時を過ぎた。', 'Đã qua 9 giờ rồi.', 'もう九時を_____た。', '過ぎ', 'generated' from jp_vocab where id = '46131d08-dead-4fc2-8bf5-21cc0af73886';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '小さな村に住んでいる。', 'Sống ở một ngôi làng nhỏ.', '小さな_____に住んでいる。', '村', 'generated' from jp_vocab where id = 'e510b217-41ad-45c0-be29-cae04b4014ad';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '田舎で育った。', 'Tôi lớn lên ở nông thôn.', '_____で育った。', '田舎', 'generated' from jp_vocab where id = '2639dd8c-d041-4614-bd0e-72e51a81bb99';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"見つける" có nghĩa là gì?', 'bài tập làm văn', 'kì thi đầu vào', 'tìm thấy', 'nhà thờ', 'tìm thấy', 'generated' from jp_vocab where id = '67b6acc0-84ee-49ce-b56f-db9b76ddb164';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tìm thấy"?', '入学試験', '帰り', '見つける', '続ける', '見つける', 'generated' from jp_vocab where id = '67b6acc0-84ee-49ce-b56f-db9b76ddb164';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"見つける" đọc là gì?', 'みつける', 'てんらんかい', 'さくぶん', 'むら', 'みつける', 'generated' from jp_vocab where id = '67b6acc0-84ee-49ce-b56f-db9b76ddb164';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 探していた本を_____た。', NULL, NULL, NULL, NULL, '見つけ', 'generated' from jp_vocab where id = '67b6acc0-84ee-49ce-b56f-db9b76ddb164';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"続ける" có nghĩa là gì?', 'tiếp tục', 'làng', 'bài tập làm văn', 'con (của người khác)', 'tiếp tục', 'generated' from jp_vocab where id = '3267e5fe-b142-45e6-bd7b-c31a4a650b55';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tiếp tục"?', '卒業する', 'プロポーズ', '取る', '続ける', '続ける', 'generated' from jp_vocab where id = '3267e5fe-b142-45e6-bd7b-c31a4a650b55';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"続ける" đọc là gì?', 'はっぴょう', 'のこる', 'つづける', 'おこさん', 'つづける', 'generated' from jp_vocab where id = '3267e5fe-b142-45e6-bd7b-c31a4a650b55';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 毎日運動を_____。', NULL, NULL, NULL, NULL, '続ける', 'generated' from jp_vocab where id = '3267e5fe-b142-45e6-bd7b-c31a4a650b55';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"取る" có nghĩa là gì?', 'cầu hôn, tỏ tình', 'dự (thi)', 'xin (nghỉ)', 'nhà thờ', 'xin (nghỉ)', 'generated' from jp_vocab where id = '6d08adfa-e67e-4881-8aef-17588e243cbe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "xin (nghỉ)"?', '休憩する', '取る', '本社', '受ける', '取る', 'generated' from jp_vocab where id = '6d08adfa-e67e-4881-8aef-17588e243cbe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"取る" đọc là gì?', 'おんせん', 'むら', 'かえり', 'とる', 'とる', 'generated' from jp_vocab where id = '6d08adfa-e67e-4881-8aef-17588e243cbe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 来週、休みを_____。', NULL, NULL, NULL, NULL, '取る', 'generated' from jp_vocab where id = '6d08adfa-e67e-4881-8aef-17588e243cbe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"受ける" có nghĩa là gì?', 'nông thôn', 'phòng kiểu Nhật', 'dự (thi)', 'con (của người khác)', 'dự (thi)', 'generated' from jp_vocab where id = '64b12e55-a0b4-4160-ad87-a171d8a033eb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "dự (thi)"?', '休憩する', '展覧会', '式', '受ける', '受ける', 'generated' from jp_vocab where id = '64b12e55-a0b4-4160-ad87-a171d8a033eb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"受ける" đọc là gì?', 'はっぴょう', 'とじる', 'ずっと', 'うける', 'うける', 'generated' from jp_vocab where id = '64b12e55-a0b4-4160-ad87-a171d8a033eb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 来月、試験を_____。', NULL, NULL, NULL, NULL, '受ける', 'generated' from jp_vocab where id = '64b12e55-a0b4-4160-ad87-a171d8a033eb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"申し込む" có nghĩa là gì?', 'ngày kỉ niệm', 'kì thi đầu vào', 'đăng ký', 'cầu hôn, tỏ tình', 'đăng ký', 'generated' from jp_vocab where id = '7b34d2e7-77d1-4a11-b038-257ce57af7a5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đăng ký"?', '式', '取る', '申し込む', '教会', '申し込む', 'generated' from jp_vocab where id = '7b34d2e7-77d1-4a11-b038-257ce57af7a5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"申し込む" đọc là gì?', 'もうしこむ', 'のこる', 'おこさん', 'とる', 'もうしこむ', 'generated' from jp_vocab where id = '7b34d2e7-77d1-4a11-b038-257ce57af7a5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 大学に_____。', NULL, NULL, NULL, NULL, '申し込む', 'generated' from jp_vocab where id = '7b34d2e7-77d1-4a11-b038-257ce57af7a5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"休憩する" có nghĩa là gì?', 'lễ cưới', 'suốt', 'nghỉ giải lao', 'bài tập làm văn', 'nghỉ giải lao', 'generated' from jp_vocab where id = 'df2109e9-1bb5-4359-ab88-3c239c67dabe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nghỉ giải lao"?', '乾杯', '取る', '大学院', '休憩する', '休憩する', 'generated' from jp_vocab where id = 'df2109e9-1bb5-4359-ab88-3c239c67dabe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"休憩する" đọc là gì?', 'とる', 'のこる', 'きゅうけいする', 'すぎる', 'きゅうけいする', 'generated' from jp_vocab where id = 'df2109e9-1bb5-4359-ab88-3c239c67dabe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 少し_____。', NULL, NULL, NULL, NULL, '休憩する', 'generated' from jp_vocab where id = 'df2109e9-1bb5-4359-ab88-3c239c67dabe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"残る" có nghĩa là gì?', 'con (của người khác)', 'sót lại, thừa lại; ở lại', 'cửa hàng chi nhánh', 'nông thôn', 'sót lại, thừa lại; ở lại', 'generated' from jp_vocab where id = 'e0c08012-6306-4870-a6bc-50a34dabf3ac';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sót lại, thừa lại; ở lại"?', '支店', '過ぎる', '残る', '動物園', '残る', 'generated' from jp_vocab where id = 'e0c08012-6306-4870-a6bc-50a34dabf3ac';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"残る" đọc là gì?', 'してん', 'どうぶつえん', 'のこる', 'みつける', 'のこる', 'generated' from jp_vocab where id = 'e0c08012-6306-4870-a6bc-50a34dabf3ac';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: まだ仕事が_____いる。', NULL, NULL, NULL, NULL, '残って', 'generated' from jp_vocab where id = 'e0c08012-6306-4870-a6bc-50a34dabf3ac';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"卒業する" có nghĩa là gì?', 'tốt nghiệp', 'cao học', 'trụ sở chính', 'quá', 'tốt nghiệp', 'generated' from jp_vocab where id = '9408e28b-9fa1-4606-973c-23b0e3b0488b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tốt nghiệp"?', '卒業する', '都会', '閉じる', '受ける', '卒業する', 'generated' from jp_vocab where id = '9408e28b-9fa1-4606-973c-23b0e3b0488b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"卒業する" đọc là gì?', 'そつぎょうする', 'きゅうけいする', 'わしつ', 'おこさん', 'そつぎょうする', 'generated' from jp_vocab where id = '9408e28b-9fa1-4606-973c-23b0e3b0488b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 来年、大学を_____。', NULL, NULL, NULL, NULL, '卒業する', 'generated' from jp_vocab where id = '9408e28b-9fa1-4606-973c-23b0e3b0488b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"閉じる" có nghĩa là gì?', 'lễ cưới', 'kì thi đầu vào', 'lễ', 'nhắm mắt', 'nhắm mắt', 'generated' from jp_vocab where id = '55e96fc8-ffc8-418c-a4fe-c9564e12f842';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhắm mắt"?', 'ずっと', '閉じる', '乾杯', '過ぎる', '閉じる', 'generated' from jp_vocab where id = '55e96fc8-ffc8-418c-a4fe-c9564e12f842';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"閉じる" đọc là gì?', 'おこさん', 'とじる', 'うける', 'きゅうけいする', 'とじる', 'generated' from jp_vocab where id = '55e96fc8-ffc8-418c-a4fe-c9564e12f842';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 目を_____て考える。', NULL, NULL, NULL, NULL, '閉じ', 'generated' from jp_vocab where id = '55e96fc8-ffc8-418c-a4fe-c9564e12f842';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"連休" có nghĩa là gì?', 'kì nghỉ dài, ngày nghỉ liên tục', 'lễ', 'nhắm mắt', 'tìm thấy', 'kì nghỉ dài, ngày nghỉ liên tục', 'generated' from jp_vocab where id = '73bbde67-db4f-43e5-b9ae-866edbd61b3f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "kì nghỉ dài, ngày nghỉ liên tục"?', '都会', '残る', '結婚式', '連休', '連休', 'generated' from jp_vocab where id = '73bbde67-db4f-43e5-b9ae-866edbd61b3f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"連休" đọc là gì?', 'れんきゅう', 'はっぴょう', 'プロポーズ', 'しき', 'れんきゅう', 'generated' from jp_vocab where id = '73bbde67-db4f-43e5-b9ae-866edbd61b3f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 今年の_____は長い。', NULL, NULL, NULL, NULL, '連休', 'generated' from jp_vocab where id = '73bbde67-db4f-43e5-b9ae-866edbd61b3f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"作文" có nghĩa là gì?', 'bài tập làm văn', 'xin (nghỉ)', 'phòng kiểu Nhật', 'suối nước nóng', 'bài tập làm văn', 'generated' from jp_vocab where id = 'acff302d-b397-4d49-8c98-7508b804a197';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "bài tập làm văn"?', '作文', '過ぎる', '入学試験', '葬式', '作文', 'generated' from jp_vocab where id = 'acff302d-b397-4d49-8c98-7508b804a197';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"作文" đọc là gì?', 'とかい', 'さくぶん', 'けっこんしき', 'のこる', 'さくぶん', 'generated' from jp_vocab where id = 'acff302d-b397-4d49-8c98-7508b804a197';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 日本語で_____を書く。', NULL, NULL, NULL, NULL, '作文', 'generated' from jp_vocab where id = 'acff302d-b397-4d49-8c98-7508b804a197';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"発表" có nghĩa là gì?', 'nhắm mắt', 'phát biểu, công bố', 'sở thú', 'suối nước nóng', 'phát biểu, công bố', 'generated' from jp_vocab where id = 'ad2e4aa5-11cc-4505-b743-7106a1259925';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phát biểu, công bố"?', '帰り', '受ける', '発表', '残る', '発表', 'generated' from jp_vocab where id = 'ad2e4aa5-11cc-4505-b743-7106a1259925';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"発表" đọc là gì?', 'むら', 'すぎる', 'だいがくいん', 'はっぴょう', 'はっぴょう', 'generated' from jp_vocab where id = 'ad2e4aa5-11cc-4505-b743-7106a1259925';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 研究の結果を_____する。', NULL, NULL, NULL, NULL, '発表', 'generated' from jp_vocab where id = 'ad2e4aa5-11cc-4505-b743-7106a1259925';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"展覧会" có nghĩa là gì?', 'cuộc triển lãm', 'nghỉ giải lao', 'phòng kiểu Nhật', 'tìm thấy', 'cuộc triển lãm', 'generated' from jp_vocab where id = '496c4cfa-b7a3-4aad-a6b9-53ee0b735bbb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cuộc triển lãm"?', '展覧会', '田舎', '発表', '都会', '展覧会', 'generated' from jp_vocab where id = '496c4cfa-b7a3-4aad-a6b9-53ee0b735bbb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"展覧会" đọc là gì?', 'きゅうけいする', 'てんらんかい', 'きょうかい', 'とかい', 'てんらんかい', 'generated' from jp_vocab where id = '496c4cfa-b7a3-4aad-a6b9-53ee0b735bbb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 絵の_____を見に行く。', NULL, NULL, NULL, NULL, '展覧会', 'generated' from jp_vocab where id = '496c4cfa-b7a3-4aad-a6b9-53ee0b735bbb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"結婚式" có nghĩa là gì?', 'sót lại, thừa lại; ở lại', 'thành phố lớn', 'xin (nghỉ)', 'lễ cưới', 'lễ cưới', 'generated' from jp_vocab where id = '51cb10bd-13eb-46ae-95ce-66fdbfb314c7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "lễ cưới"?', '取る', '結婚式', '温泉', 'お子さん', '結婚式', 'generated' from jp_vocab where id = '51cb10bd-13eb-46ae-95ce-66fdbfb314c7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"結婚式" đọc là gì?', 'おこさん', 'のこる', 'けっこんしき', 'とかい', 'けっこんしき', 'generated' from jp_vocab where id = '51cb10bd-13eb-46ae-95ce-66fdbfb314c7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 来月、_____を挙げる。', NULL, NULL, NULL, NULL, '結婚式', 'generated' from jp_vocab where id = '51cb10bd-13eb-46ae-95ce-66fdbfb314c7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"葬式" có nghĩa là gì?', 'suối nước nóng', 'đám tang', 'nhà thờ', 'kì thi đầu vào', 'đám tang', 'generated' from jp_vocab where id = '332d8164-39a7-4450-b923-51ae9d0b0287';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đám tang"?', '葬式', 'ずっと', '村', '続ける', '葬式', 'generated' from jp_vocab where id = '332d8164-39a7-4450-b923-51ae9d0b0287';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"葬式" đọc là gì?', 'れんきゅう', 'すぎる', 'どうぶつえん', 'そうしき', 'そうしき', 'generated' from jp_vocab where id = '332d8164-39a7-4450-b923-51ae9d0b0287';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に参加する。', NULL, NULL, NULL, NULL, '葬式', 'generated' from jp_vocab where id = '332d8164-39a7-4450-b923-51ae9d0b0287';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"式" có nghĩa là gì?', 'làng', 'cầu hôn, tỏ tình', 'lễ', 'sự trở về', 'lễ', 'generated' from jp_vocab where id = 'f28c5473-cc48-481b-be69-cac54db4b9c5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "lễ"?', '帰り', '式', '都会', '温泉', '式', 'generated' from jp_vocab where id = 'f28c5473-cc48-481b-be69-cac54db4b9c5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"式" đọc là gì?', 'しき', 'そつぎょうする', 'さくぶん', 'うける', 'しき', 'generated' from jp_vocab where id = 'f28c5473-cc48-481b-be69-cac54db4b9c5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 卒業_____は三月にある。', NULL, NULL, NULL, NULL, '式', 'generated' from jp_vocab where id = 'f28c5473-cc48-481b-be69-cac54db4b9c5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"本社" có nghĩa là gì?', 'suốt', 'bài tập làm văn', 'đám tang', 'trụ sở chính', 'trụ sở chính', 'generated' from jp_vocab where id = '35c0541e-8218-47bd-ae02-4c7425bb1901';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "trụ sở chính"?', '本社', '結婚式', '展覧会', '作文', '本社', 'generated' from jp_vocab where id = '35c0541e-8218-47bd-ae02-4c7425bb1901';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"本社" đọc là gì?', 'ほんしゃ', 'てんらんかい', 'とる', 'きねんび', 'ほんしゃ', 'generated' from jp_vocab where id = '35c0541e-8218-47bd-ae02-4c7425bb1901';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____は東京にある。', NULL, NULL, NULL, NULL, '本社', 'generated' from jp_vocab where id = '35c0541e-8218-47bd-ae02-4c7425bb1901';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"支店" có nghĩa là gì?', 'tìm thấy', 'cửa hàng chi nhánh', 'quá', 'trụ sở chính', 'cửa hàng chi nhánh', 'generated' from jp_vocab where id = 'dad43b79-6cc9-4858-a8d1-0f756915951a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cửa hàng chi nhánh"?', '支店', '本社', 'お子さん', '受ける', '支店', 'generated' from jp_vocab where id = 'dad43b79-6cc9-4858-a8d1-0f756915951a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"支店" đọc là gì?', 'れんきゅう', 'ずっと', 'してん', 'もうしこむ', 'してん', 'generated' from jp_vocab where id = 'dad43b79-6cc9-4858-a8d1-0f756915951a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 大阪に_____を作る。', NULL, NULL, NULL, NULL, '支店', 'generated' from jp_vocab where id = 'dad43b79-6cc9-4858-a8d1-0f756915951a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"教会" có nghĩa là gì?', 'trụ sở chính', 'lễ', 'nhà thờ', 'dự (thi)', 'nhà thờ', 'generated' from jp_vocab where id = '59c4c2e9-2c0e-42a1-8793-a09ed92c44f8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhà thờ"?', '閉じる', '卒業する', '作文', '教会', '教会', 'generated' from jp_vocab where id = '59c4c2e9-2c0e-42a1-8793-a09ed92c44f8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"教会" đọc là gì?', 'きょうかい', 'みつける', 'しき', 'てんらんかい', 'きょうかい', 'generated' from jp_vocab where id = '59c4c2e9-2c0e-42a1-8793-a09ed92c44f8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 日曜日に_____へ行く。', NULL, NULL, NULL, NULL, '教会', 'generated' from jp_vocab where id = '59c4c2e9-2c0e-42a1-8793-a09ed92c44f8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"和室" có nghĩa là gì?', 'phòng kiểu Nhật', 'cạn ly', 'cửa hàng chi nhánh', 'tìm thấy', 'phòng kiểu Nhật', 'generated' from jp_vocab where id = 'afbde83a-d959-4d7c-809f-7b9ae805e41b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phòng kiểu Nhật"?', '取る', '発表', '連休', '和室', '和室', 'generated' from jp_vocab where id = 'afbde83a-d959-4d7c-809f-7b9ae805e41b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"和室" đọc là gì?', 'きゅうけいする', 'すぎる', 'わしつ', 'にゅうがくしけん', 'わしつ', 'generated' from jp_vocab where id = 'afbde83a-d959-4d7c-809f-7b9ae805e41b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で寝る。', NULL, NULL, NULL, NULL, '和室', 'generated' from jp_vocab where id = 'afbde83a-d959-4d7c-809f-7b9ae805e41b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"大学院" có nghĩa là gì?', 'cầu hôn, tỏ tình', 'cao học', 'quá', 'lễ cưới', 'cao học', 'generated' from jp_vocab where id = 'abbd09ba-95d5-4ae7-980f-b09429063a2d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cao học"?', '大学院', '申し込む', '入学試験', '続ける', '大学院', 'generated' from jp_vocab where id = 'abbd09ba-95d5-4ae7-980f-b09429063a2d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"大学院" đọc là gì?', 'きゅうけいする', 'はっぴょう', 'そうしき', 'だいがくいん', 'だいがくいん', 'generated' from jp_vocab where id = 'abbd09ba-95d5-4ae7-980f-b09429063a2d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に進む。', NULL, NULL, NULL, NULL, '大学院', 'generated' from jp_vocab where id = 'abbd09ba-95d5-4ae7-980f-b09429063a2d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"動物園" có nghĩa là gì?', 'sở thú', 'dự (thi)', 'con (của người khác)', 'trụ sở chính', 'sở thú', 'generated' from jp_vocab where id = 'd0e61890-9dcf-4ac5-9064-2bd56493c234';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sở thú"?', '過ぎる', '結婚式', '大学院', '動物園', '動物園', 'generated' from jp_vocab where id = 'd0e61890-9dcf-4ac5-9064-2bd56493c234';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"動物園" đọc là gì?', 'してん', 'どうぶつえん', 'はっぴょう', 'さくぶん', 'どうぶつえん', 'generated' from jp_vocab where id = 'd0e61890-9dcf-4ac5-9064-2bd56493c234';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 家族で_____に行った。', NULL, NULL, NULL, NULL, '動物園', 'generated' from jp_vocab where id = 'd0e61890-9dcf-4ac5-9064-2bd56493c234';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"温泉" có nghĩa là gì?', 'kì nghỉ dài, ngày nghỉ liên tục', 'suối nước nóng', 'lễ cưới', 'xin (nghỉ)', 'suối nước nóng', 'generated' from jp_vocab where id = '646e6db0-881f-458c-b5a4-1911608d97b3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "suối nước nóng"?', 'お子さん', '卒業する', '村', '温泉', '温泉', 'generated' from jp_vocab where id = '646e6db0-881f-458c-b5a4-1911608d97b3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"温泉" đọc là gì?', 'きねんび', 'とる', 'どうぶつえん', 'おんせん', 'おんせん', 'generated' from jp_vocab where id = '646e6db0-881f-458c-b5a4-1911608d97b3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に入る。', NULL, NULL, NULL, NULL, '温泉', 'generated' from jp_vocab where id = '646e6db0-881f-458c-b5a4-1911608d97b3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"帰り" có nghĩa là gì?', 'ngày kỉ niệm', 'cạn ly', 'sự trở về', 'nghỉ giải lao', 'sự trở về', 'generated' from jp_vocab where id = '7abdd4d9-5898-4f27-a496-1a18045a3d59';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sự trở về"?', '本社', '過ぎる', '記念日', '帰り', '帰り', 'generated' from jp_vocab where id = '7abdd4d9-5898-4f27-a496-1a18045a3d59';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"帰り" đọc là gì?', 'かえり', 'ずっと', 'けっこんしき', 'わしつ', 'かえり', 'generated' from jp_vocab where id = '7abdd4d9-5898-4f27-a496-1a18045a3d59';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に買い物をする。', NULL, NULL, NULL, NULL, '帰り', 'generated' from jp_vocab where id = '7abdd4d9-5898-4f27-a496-1a18045a3d59';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"お子さん" có nghĩa là gì?', 'nông thôn', 'con (của người khác)', 'quá', 'nghỉ giải lao', 'con (của người khác)', 'generated' from jp_vocab where id = '70fc69d0-95ce-4a1b-9f83-99a09f647d00';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "con (của người khác)"?', '村', 'お子さん', '取る', '続ける', 'お子さん', 'generated' from jp_vocab where id = '70fc69d0-95ce-4a1b-9f83-99a09f647d00';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"お子さん" đọc là gì?', 'かえり', 'おこさん', 'もうしこむ', 'けっこんしき', 'おこさん', 'generated' from jp_vocab where id = '70fc69d0-95ce-4a1b-9f83-99a09f647d00';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____は何歳ですか。', NULL, NULL, NULL, NULL, 'お子さん', 'generated' from jp_vocab where id = '70fc69d0-95ce-4a1b-9f83-99a09f647d00';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ずっと" có nghĩa là gì?', 'cuộc triển lãm', 'phòng kiểu Nhật', 'nhắm mắt', 'suốt', 'suốt', 'generated' from jp_vocab where id = 'b37414d7-ea95-4556-b8f9-42d5462c3d02';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "suốt"?', '展覧会', '休憩する', '温泉', 'ずっと', 'ずっと', 'generated' from jp_vocab where id = 'b37414d7-ea95-4556-b8f9-42d5462c3d02';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ずっと" đọc là gì?', 'はっぴょう', 'いなか', 'そつぎょうする', 'ずっと', 'ずっと', 'generated' from jp_vocab where id = 'b37414d7-ea95-4556-b8f9-42d5462c3d02';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____待っていた。', NULL, NULL, NULL, NULL, 'ずっと', 'generated' from jp_vocab where id = 'b37414d7-ea95-4556-b8f9-42d5462c3d02';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"入学試験" có nghĩa là gì?', 'sở thú', 'ngày kỉ niệm', 'lễ', 'kì thi đầu vào', 'kì thi đầu vào', 'generated' from jp_vocab where id = '748543b0-7d9b-4e6e-8401-fbedba2ce43a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "kì thi đầu vào"?', 'お子さん', '発表', '入学試験', '支店', '入学試験', 'generated' from jp_vocab where id = '748543b0-7d9b-4e6e-8401-fbedba2ce43a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"入学試験" đọc là gì?', 'のこる', 'どうぶつえん', 'すぎる', 'にゅうがくしけん', 'にゅうがくしけん', 'generated' from jp_vocab where id = '748543b0-7d9b-4e6e-8401-fbedba2ce43a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に合格する。', NULL, NULL, NULL, NULL, '入学試験', 'generated' from jp_vocab where id = '748543b0-7d9b-4e6e-8401-fbedba2ce43a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"都会" có nghĩa là gì?', 'ngày kỉ niệm', 'bài tập làm văn', 'thành phố lớn', 'tốt nghiệp', 'thành phố lớn', 'generated' from jp_vocab where id = '45e0c591-fa42-4057-b088-202636e6f7f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thành phố lớn"?', '本社', '教会', '閉じる', '都会', '都会', 'generated' from jp_vocab where id = '45e0c591-fa42-4057-b088-202636e6f7f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"都会" đọc là gì?', 'のこる', 'そつぎょうする', 'むら', 'とかい', 'とかい', 'generated' from jp_vocab where id = '45e0c591-fa42-4057-b088-202636e6f7f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 彼は_____で働いている。', NULL, NULL, NULL, NULL, '都会', 'generated' from jp_vocab where id = '45e0c591-fa42-4057-b088-202636e6f7f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"記念日" có nghĩa là gì?', 'kì nghỉ dài, ngày nghỉ liên tục', 'ngày kỉ niệm', 'tiếp tục', 'lễ cưới', 'ngày kỉ niệm', 'generated' from jp_vocab where id = '4c6a38c6-c434-453f-a0a6-a472f910d161';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "ngày kỉ niệm"?', '記念日', '休憩する', '帰り', '乾杯', '記念日', 'generated' from jp_vocab where id = '4c6a38c6-c434-453f-a0a6-a472f910d161';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"記念日" đọc là gì?', 'かんぱい', 'うける', 'きねんび', 'とかい', 'きねんび', 'generated' from jp_vocab where id = '4c6a38c6-c434-453f-a0a6-a472f910d161';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 今日は結婚_____です。', NULL, NULL, NULL, NULL, '記念日', 'generated' from jp_vocab where id = '4c6a38c6-c434-453f-a0a6-a472f910d161';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"プロポーズ" có nghĩa là gì?', 'suối nước nóng', 'kì thi đầu vào', 'cầu hôn, tỏ tình', 'cạn ly', 'cầu hôn, tỏ tình', 'generated' from jp_vocab where id = '993b6fdf-7bf2-40c8-811d-f205bc0ebdf9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cầu hôn, tỏ tình"?', '村', 'プロポーズ', '田舎', '見つける', 'プロポーズ', 'generated' from jp_vocab where id = '993b6fdf-7bf2-40c8-811d-f205bc0ebdf9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"プロポーズ" đọc là gì?', 'うける', 'かんぱい', 'プロポーズ', 'はっぴょう', 'プロポーズ', 'generated' from jp_vocab where id = '993b6fdf-7bf2-40c8-811d-f205bc0ebdf9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 彼に_____された。', NULL, NULL, NULL, NULL, 'プロポーズ', 'generated' from jp_vocab where id = '993b6fdf-7bf2-40c8-811d-f205bc0ebdf9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"乾杯" có nghĩa là gì?', 'quá', 'lễ', 'cạn ly', 'xin (nghỉ)', 'cạn ly', 'generated' from jp_vocab where id = 'a798b1cc-50d8-493e-aa13-760f200bcb0a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cạn ly"?', '続ける', '乾杯', '受ける', '和室', '乾杯', 'generated' from jp_vocab where id = 'a798b1cc-50d8-493e-aa13-760f200bcb0a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"乾杯" đọc là gì?', 'かんぱい', 'むら', 'おんせん', 'もうしこむ', 'かんぱい', 'generated' from jp_vocab where id = 'a798b1cc-50d8-493e-aa13-760f200bcb0a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: みんなで_____する。', NULL, NULL, NULL, NULL, '乾杯', 'generated' from jp_vocab where id = 'a798b1cc-50d8-493e-aa13-760f200bcb0a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"過ぎる" có nghĩa là gì?', 'kì nghỉ dài, ngày nghỉ liên tục', 'làng', 'quá', 'kì thi đầu vào', 'quá', 'generated' from jp_vocab where id = '46131d08-dead-4fc2-8bf5-21cc0af73886';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "quá"?', '過ぎる', '取る', '記念日', '申し込む', '過ぎる', 'generated' from jp_vocab where id = '46131d08-dead-4fc2-8bf5-21cc0af73886';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"過ぎる" đọc là gì?', 'だいがくいん', 'ずっと', 'すぎる', 'そつぎょうする', 'すぎる', 'generated' from jp_vocab where id = '46131d08-dead-4fc2-8bf5-21cc0af73886';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: もう九時を_____た。', NULL, NULL, NULL, NULL, '過ぎ', 'generated' from jp_vocab where id = '46131d08-dead-4fc2-8bf5-21cc0af73886';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"村" có nghĩa là gì?', 'làng', 'tìm thấy', 'cuộc triển lãm', 'lễ cưới', 'làng', 'generated' from jp_vocab where id = 'e510b217-41ad-45c0-be29-cae04b4014ad';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "làng"?', '村', '過ぎる', '取る', 'お子さん', '村', 'generated' from jp_vocab where id = 'e510b217-41ad-45c0-be29-cae04b4014ad';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"村" đọc là gì?', 'にゅうがくしけん', 'どうぶつえん', 'れんきゅう', 'むら', 'むら', 'generated' from jp_vocab where id = 'e510b217-41ad-45c0-be29-cae04b4014ad';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 小さな_____に住んでいる。', NULL, NULL, NULL, NULL, '村', 'generated' from jp_vocab where id = 'e510b217-41ad-45c0-be29-cae04b4014ad';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"田舎" có nghĩa là gì?', 'tốt nghiệp', 'nông thôn', 'kì thi đầu vào', 'nghỉ giải lao', 'nông thôn', 'generated' from jp_vocab where id = '2639dd8c-d041-4614-bd0e-72e51a81bb99';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nông thôn"?', '村', '記念日', '田舎', '連休', '田舎', 'generated' from jp_vocab where id = '2639dd8c-d041-4614-bd0e-72e51a81bb99';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"田舎" đọc là gì?', 'きょうかい', 'いなか', 'みつける', 'だいがくいん', 'いなか', 'generated' from jp_vocab where id = '2639dd8c-d041-4614-bd0e-72e51a81bb99';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で育った。', NULL, NULL, NULL, NULL, '田舎', 'generated' from jp_vocab where id = '2639dd8c-d041-4614-bd0e-72e51a81bb99';
