-- ============================================================
-- jp-go — Từ vựng N4, 課32 (phần 1, 25 từ đầu).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 22.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e829cd53-09ae-40e9-98b3-48fcee05afae', 'N4', 32, 'word', '運動する', 'うんどうする', 'vận động', NULL, '動詞', 22, '運動する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3147a39a-3133-4365-a50f-f7f57bd75221', 'N4', 32, 'word', '成功する', 'せいこうする', 'thành công', NULL, '動詞', 22, '成功する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('6c90e278-c756-4cba-9e3f-92bc447a6b27', 'N4', 32, 'word', '失敗する', 'しっぱいする', 'thất bại, trượt (kì thi)', 'thường dùng dạng [試験に〜]', '動詞', 22, '失敗する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('5c2f8fb8-e277-4431-a21f-30ad4b2246b8', 'N4', 32, 'word', '合格する', 'ごうかくする', 'đỗ (kì thi)', 'thường dùng dạng [試験に〜]', '動詞', 22, '合格する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d53f8464-a367-45e8-8ff9-014816b88305', 'N4', 32, 'word', 'やむ', 'やむ', 'tạnh (mưa)', 'thường dùng dạng [雨が〜]', '動詞', 22, 'やむ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('59b73efa-1962-42fe-87c2-d888ec57d263', 'N4', 32, 'word', '晴れる', 'はれる', 'quang đãng, nắng đẹp', NULL, '動詞', 22, '晴れる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7e40040f-26ea-4551-9282-0026abf10965', 'N4', 32, 'word', '曇る', 'くもる', 'có mây', NULL, '動詞', 22, '曇る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('dab61535-69a5-472d-85dd-1088e46e8855', 'N4', 32, 'word', '続く', 'つづく', 'kéo dài, liên tiếp', NULL, '動詞', 22, '続く', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('bbc58bcf-66e9-44a8-b714-0fdeb4eb6578', 'N4', 32, 'word', '引く', 'ひく', 'bị cảm', 'thường dùng dạng [風邪を〜]', '動詞', 22, '引く', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('c3f5de13-9983-48de-bb0f-a292fe0f3c90', 'N4', 32, 'word', '冷やす', 'ひやす', 'làm mát, làm lạnh', NULL, '動詞', 22, '冷やす', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a92858b1-3c31-47bd-bbe8-eabaa40ae5cf', 'N4', 32, 'word', '込む', 'こむ', 'đông đúc', NULL, '動詞', 22, '込む', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3edd83be-2584-478d-a322-01acc0cd6ff9', 'N4', 32, 'word', '空く', 'すく', 'vắng', NULL, '動詞', 22, '空く', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3a0421e0-4038-4fb4-90bf-48d7b926fed7', 'N4', 32, 'word', '当たる', 'あたる', 'trúng (xổ số)', 'thường dùng dạng [宝くじが〜]', '動詞', 22, '当たる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e2e1b58c-9d56-4d16-b764-ae352408cb06', 'N4', 32, 'word', '出る', 'でる', 'tham gia (trận đấu)', 'thường dùng dạng [試合に〜]', '動詞', 22, '出る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('02cc679d-947a-433f-917e-1cd1acbc13c5', 'N4', 32, 'phrase', '無理をする', 'むりをする', 'gắng sức', NULL, '動詞', 22, '無理をする', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('ad2a5f65-3853-4928-8534-4a5ba5dd2a8e', 'N4', 32, 'word', '働き過ぎ', 'はたらきすぎ', 'làm việc quá sức', NULL, '名詞', 22, '働き過ぎ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('117342eb-9f04-4659-bcfc-68f5bcc255e0', 'N4', 32, 'word', '十分', 'じゅうぶん', 'đủ', NULL, 'な形容詞', 22, '十分', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b2a27afe-3bec-48d6-87a2-7760a45dd6f3', 'N4', 32, 'word', 'おかしい', 'おかしい', 'lạ, thú vị', NULL, 'い形容詞', 22, 'おかしい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('4f5b4432-e628-46bc-a81d-fbfa4efbc47a', 'N4', 32, 'word', 'うるさい', 'うるさい', 'ồn ào', NULL, 'い形容詞', 22, 'うるさい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7d8b4f2f-51e6-4256-b8e0-7349bb0803f8', 'N4', 32, 'word', '先生', 'せんせい', 'bác sĩ', NULL, '名詞', 22, '先生', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('c1d00eae-8540-4083-89ea-8dc91aa11355', 'N4', 32, 'word', '火傷', 'やけど', '(bị) bỏng', 'thường dùng dạng [〜をする]', '名詞', 22, '火傷', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('86a1214b-94b4-4a06-a8f0-5f5aefeab602', 'N4', 32, 'word', '怪我', 'けが', '(bị) thương', 'thường dùng dạng [〜をする]', '名詞', 22, '怪我', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('bad4070c-4dd7-41f2-af3e-36723e9c37f2', 'N4', 32, 'phrase', '咳をする', 'せきをする', 'ho', NULL, '動詞', 22, '咳をする', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('416a91ea-161d-48f8-9af2-240f146785c9', 'N4', 32, 'phrase', '咳が出る', 'せきがでる', '(bị) ho', NULL, '動詞', 22, '咳が出る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('8a4d165a-b831-4149-b002-ea97c19b0cf1', 'N4', 32, 'word', '太陽', 'たいよう', 'mặt trời', NULL, '名詞', 22, '太陽', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '毎朝運動する。', 'Tập thể dục mỗi sáng.', '毎朝_____。', '運動する', 'generated' from jp_vocab where id = 'e829cd53-09ae-40e9-98b3-48fcee05afae';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '事業に成功する。', 'Thành công trong sự nghiệp.', '事業に_____。', '成功する', 'generated' from jp_vocab where id = '3147a39a-3133-4365-a50f-f7f57bd75221';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '試験に失敗した。', 'Tôi đã trượt kì thi.', '試験に_____した。', '失敗', 'generated' from jp_vocab where id = '6c90e278-c756-4cba-9e3f-92bc447a6b27';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '試験に合格した。', 'Tôi đã đỗ kì thi.', '試験に_____した。', '合格', 'generated' from jp_vocab where id = '5c2f8fb8-e277-4431-a21f-30ad4b2246b8';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '雨がやんだ。', 'Mưa đã tạnh.', '雨が_____た。', 'やん', 'generated' from jp_vocab where id = 'd53f8464-a367-45e8-8ff9-014816b88305';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '明日は晴れるでしょう。', 'Ngày mai chắc sẽ nắng đẹp.', '明日は_____でしょう。', '晴れる', 'generated' from jp_vocab where id = '59b73efa-1962-42fe-87c2-d888ec57d263';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '空が曇ってきた。', 'Trời bắt đầu có mây.', '空が_____てきた。', '曇っ', 'generated' from jp_vocab where id = '7e40040f-26ea-4551-9282-0026abf10965';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '雨が三日続いている。', 'Mưa kéo dài đã 3 ngày.', '雨が三日_____いる。', '続いて', 'generated' from jp_vocab where id = 'dab61535-69a5-472d-85dd-1088e46e8855';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '風邪を引いた。', 'Tôi đã bị cảm.', '風邪を_____た。', '引い', 'generated' from jp_vocab where id = 'bbc58bcf-66e9-44a8-b714-0fdeb4eb6578';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ビールを冷やす。', 'Làm lạnh bia.', 'ビールを_____。', '冷やす', 'generated' from jp_vocab where id = 'c3f5de13-9983-48de-bb0f-a292fe0f3c90';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '電車が込んでいる。', 'Tàu điện đông đúc.', '電車が_____いる。', '込んで', 'generated' from jp_vocab where id = 'a92858b1-3c31-47bd-bbe8-eabaa40ae5cf';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '電車が空いている。', 'Tàu điện vắng.', '電車が_____いる。', '空いて', 'generated' from jp_vocab where id = '3edd83be-2584-478d-a322-01acc0cd6ff9';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '宝くじが当たった。', 'Tôi đã trúng xổ số.', '宝くじが_____た。', '当たっ', 'generated' from jp_vocab where id = '3a0421e0-4038-4fb4-90bf-48d7b926fed7';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '試合に出る。', 'Tham gia trận đấu.', '試合に_____。', '出る', 'generated' from jp_vocab where id = 'e2e1b58c-9d56-4d16-b764-ae352408cb06';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '無理をしないでください。', 'Xin đừng gắng sức quá.', '_____しないでください。', '無理をする', 'generated' from jp_vocab where id = '02cc679d-947a-433f-917e-1cd1acbc13c5';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '働き過ぎは体に悪い。', 'Làm việc quá sức không tốt cho cơ thể.', '_____は体に悪い。', '働き過ぎ', 'generated' from jp_vocab where id = 'ad2a5f65-3853-4928-8534-4a5ba5dd2a8e';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'もう十分です。', 'Đủ rồi.', 'もう_____です。', '十分', 'generated' from jp_vocab where id = '117342eb-9f04-4659-bcfc-68f5bcc255e0';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'この話はおかしい。', 'Câu chuyện này lạ thật.', 'この話は_____。', 'おかしい', 'generated' from jp_vocab where id = 'b2a27afe-3bec-48d6-87a2-7760a45dd6f3';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '外がうるさい。', 'Bên ngoài ồn ào.', '外が_____。', 'うるさい', 'generated' from jp_vocab where id = '4f5b4432-e628-46bc-a81d-fbfa4efbc47a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '先生に診てもらう。', 'Được bác sĩ khám cho.', '_____に診てもらう。', '先生', 'generated' from jp_vocab where id = '7d8b4f2f-51e6-4256-b8e0-7349bb0803f8';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '料理中に火傷をした。', 'Tôi đã bị bỏng khi nấu ăn.', '料理中に_____をした。', '火傷', 'generated' from jp_vocab where id = 'c1d00eae-8540-4083-89ea-8dc91aa11355';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'サッカーで怪我をした。', 'Tôi đã bị thương khi chơi bóng đá.', 'サッカーで_____をした。', '怪我', 'generated' from jp_vocab where id = '86a1214b-94b4-4a06-a8f0-5f5aefeab602';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '咳をすると苦しい。', 'Ho thì khó chịu.', '_____と苦しい。', '咳をする', 'generated' from jp_vocab where id = 'bad4070c-4dd7-41f2-af3e-36723e9c37f2';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '風邪で咳が出る。', 'Vì cảm nên bị ho.', '風邪で_____。', '咳が出る', 'generated' from jp_vocab where id = '416a91ea-161d-48f8-9af2-240f146785c9';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '太陽が昇る。', 'Mặt trời mọc.', '_____が昇る。', '太陽', 'generated' from jp_vocab where id = '8a4d165a-b831-4149-b002-ea97c19b0cf1';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"運動する" có nghĩa là gì?', 'vận động', 'làm việc quá sức', '(bị) thương', 'kéo dài, liên tiếp', 'vận động', 'generated' from jp_vocab where id = 'e829cd53-09ae-40e9-98b3-48fcee05afae';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vận động"?', '運動する', 'やむ', '合格する', '引く', '運動する', 'generated' from jp_vocab where id = 'e829cd53-09ae-40e9-98b3-48fcee05afae';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"運動する" đọc là gì?', 'むりをする', 'すく', 'あたる', 'うんどうする', 'うんどうする', 'generated' from jp_vocab where id = 'e829cd53-09ae-40e9-98b3-48fcee05afae';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 毎朝_____。', NULL, NULL, NULL, NULL, '運動する', 'generated' from jp_vocab where id = 'e829cd53-09ae-40e9-98b3-48fcee05afae';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"成功する" có nghĩa là gì?', 'thành công', 'có mây', 'quang đãng, nắng đẹp', 'thất bại, trượt (kì thi)', 'thành công', 'generated' from jp_vocab where id = '3147a39a-3133-4365-a50f-f7f57bd75221';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thành công"?', '失敗する', '咳をする', '成功する', '晴れる', '成功する', 'generated' from jp_vocab where id = '3147a39a-3133-4365-a50f-f7f57bd75221';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"成功する" đọc là gì?', 'せいこうする', 'すく', 'ひく', 'ひやす', 'せいこうする', 'generated' from jp_vocab where id = '3147a39a-3133-4365-a50f-f7f57bd75221';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 事業に_____。', NULL, NULL, NULL, NULL, '成功する', 'generated' from jp_vocab where id = '3147a39a-3133-4365-a50f-f7f57bd75221';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"失敗する" có nghĩa là gì?', 'thất bại, trượt (kì thi)', 'trúng (xổ số)', 'lạ, thú vị', 'vắng', 'thất bại, trượt (kì thi)', 'generated' from jp_vocab where id = '6c90e278-c756-4cba-9e3f-92bc447a6b27';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thất bại, trượt (kì thi)"?', '太陽', '成功する', '失敗する', '合格する', '失敗する', 'generated' from jp_vocab where id = '6c90e278-c756-4cba-9e3f-92bc447a6b27';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"失敗する" đọc là gì?', 'くもる', 'すく', 'しっぱいする', 'でる', 'しっぱいする', 'generated' from jp_vocab where id = '6c90e278-c756-4cba-9e3f-92bc447a6b27';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 試験に_____した。', NULL, NULL, NULL, NULL, '失敗', 'generated' from jp_vocab where id = '6c90e278-c756-4cba-9e3f-92bc447a6b27';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"合格する" có nghĩa là gì?', 'làm mát, làm lạnh', 'đủ', 'đỗ (kì thi)', 'quang đãng, nắng đẹp', 'đỗ (kì thi)', 'generated' from jp_vocab where id = '5c2f8fb8-e277-4431-a21f-30ad4b2246b8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đỗ (kì thi)"?', '曇る', '引く', '合格する', 'おかしい', '合格する', 'generated' from jp_vocab where id = '5c2f8fb8-e277-4431-a21f-30ad4b2246b8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"合格する" đọc là gì?', 'せきがでる', 'ごうかくする', 'むりをする', 'でる', 'ごうかくする', 'generated' from jp_vocab where id = '5c2f8fb8-e277-4431-a21f-30ad4b2246b8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 試験に_____した。', NULL, NULL, NULL, NULL, '合格', 'generated' from jp_vocab where id = '5c2f8fb8-e277-4431-a21f-30ad4b2246b8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"やむ" có nghĩa là gì?', 'vận động', 'ồn ào', 'làm mát, làm lạnh', 'tạnh (mưa)', 'tạnh (mưa)', 'generated' from jp_vocab where id = 'd53f8464-a367-45e8-8ff9-014816b88305';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tạnh (mưa)"?', '怪我', 'おかしい', 'うるさい', 'やむ', 'やむ', 'generated' from jp_vocab where id = 'd53f8464-a367-45e8-8ff9-014816b88305';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"やむ" đọc là gì?', 'やむ', 'せきがでる', 'けが', 'すく', 'やむ', 'generated' from jp_vocab where id = 'd53f8464-a367-45e8-8ff9-014816b88305';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 雨が_____た。', NULL, NULL, NULL, NULL, 'やん', 'generated' from jp_vocab where id = 'd53f8464-a367-45e8-8ff9-014816b88305';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"晴れる" có nghĩa là gì?', 'quang đãng, nắng đẹp', 'bác sĩ', 'tham gia (trận đấu)', 'vắng', 'quang đãng, nắng đẹp', 'generated' from jp_vocab where id = '59b73efa-1962-42fe-87c2-d888ec57d263';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "quang đãng, nắng đẹp"?', '晴れる', '火傷', '無理をする', '太陽', '晴れる', 'generated' from jp_vocab where id = '59b73efa-1962-42fe-87c2-d888ec57d263';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"晴れる" đọc là gì?', 'やむ', 'はれる', 'せきをする', 'たいよう', 'はれる', 'generated' from jp_vocab where id = '59b73efa-1962-42fe-87c2-d888ec57d263';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 明日は_____でしょう。', NULL, NULL, NULL, NULL, '晴れる', 'generated' from jp_vocab where id = '59b73efa-1962-42fe-87c2-d888ec57d263';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"曇る" có nghĩa là gì?', 'tham gia (trận đấu)', 'làm việc quá sức', 'tạnh (mưa)', 'có mây', 'có mây', 'generated' from jp_vocab where id = '7e40040f-26ea-4551-9282-0026abf10965';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "có mây"?', '曇る', 'おかしい', '無理をする', 'うるさい', '曇る', 'generated' from jp_vocab where id = '7e40040f-26ea-4551-9282-0026abf10965';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"曇る" đọc là gì?', 'あたる', 'くもる', 'じゅうぶん', 'やけど', 'くもる', 'generated' from jp_vocab where id = '7e40040f-26ea-4551-9282-0026abf10965';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 空が_____てきた。', NULL, NULL, NULL, NULL, '曇っ', 'generated' from jp_vocab where id = '7e40040f-26ea-4551-9282-0026abf10965';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"続く" có nghĩa là gì?', 'ồn ào', 'kéo dài, liên tiếp', 'lạ, thú vị', 'trúng (xổ số)', 'kéo dài, liên tiếp', 'generated' from jp_vocab where id = 'dab61535-69a5-472d-85dd-1088e46e8855';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "kéo dài, liên tiếp"?', '続く', '先生', '怪我', '十分', '続く', 'generated' from jp_vocab where id = 'dab61535-69a5-472d-85dd-1088e46e8855';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"続く" đọc là gì?', 'せいこうする', 'じゅうぶん', 'つづく', 'あたる', 'つづく', 'generated' from jp_vocab where id = 'dab61535-69a5-472d-85dd-1088e46e8855';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 雨が三日_____いる。', NULL, NULL, NULL, NULL, '続いて', 'generated' from jp_vocab where id = 'dab61535-69a5-472d-85dd-1088e46e8855';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"引く" có nghĩa là gì?', 'bị cảm', 'đông đúc', 'bác sĩ', '(bị) bỏng', 'bị cảm', 'generated' from jp_vocab where id = 'bbc58bcf-66e9-44a8-b714-0fdeb4eb6578';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "bị cảm"?', '引く', '当たる', '怪我', '先生', '引く', 'generated' from jp_vocab where id = 'bbc58bcf-66e9-44a8-b714-0fdeb4eb6578';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"引く" đọc là gì?', 'せきをする', 'じゅうぶん', 'ひく', 'せんせい', 'ひく', 'generated' from jp_vocab where id = 'bbc58bcf-66e9-44a8-b714-0fdeb4eb6578';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 風邪を_____た。', NULL, NULL, NULL, NULL, '引い', 'generated' from jp_vocab where id = 'bbc58bcf-66e9-44a8-b714-0fdeb4eb6578';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"冷やす" có nghĩa là gì?', 'làm mát, làm lạnh', 'vắng', 'kéo dài, liên tiếp', 'ồn ào', 'làm mát, làm lạnh', 'generated' from jp_vocab where id = 'c3f5de13-9983-48de-bb0f-a292fe0f3c90';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "làm mát, làm lạnh"?', '冷やす', '無理をする', '引く', '咳が出る', '冷やす', 'generated' from jp_vocab where id = 'c3f5de13-9983-48de-bb0f-a292fe0f3c90';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"冷やす" đọc là gì?', 'せきがでる', 'せきをする', 'ひやす', 'しっぱいする', 'ひやす', 'generated' from jp_vocab where id = 'c3f5de13-9983-48de-bb0f-a292fe0f3c90';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: ビールを_____。', NULL, NULL, NULL, NULL, '冷やす', 'generated' from jp_vocab where id = 'c3f5de13-9983-48de-bb0f-a292fe0f3c90';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"込む" có nghĩa là gì?', 'mặt trời', 'thất bại, trượt (kì thi)', 'đông đúc', 'ồn ào', 'đông đúc', 'generated' from jp_vocab where id = 'a92858b1-3c31-47bd-bbe8-eabaa40ae5cf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đông đúc"?', '込む', '怪我', '合格する', '続く', '込む', 'generated' from jp_vocab where id = 'a92858b1-3c31-47bd-bbe8-eabaa40ae5cf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"込む" đọc là gì?', 'こむ', 'おかしい', 'はれる', 'ひく', 'こむ', 'generated' from jp_vocab where id = 'a92858b1-3c31-47bd-bbe8-eabaa40ae5cf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 電車が_____いる。', NULL, NULL, NULL, NULL, '込んで', 'generated' from jp_vocab where id = 'a92858b1-3c31-47bd-bbe8-eabaa40ae5cf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"空く" có nghĩa là gì?', 'bác sĩ', 'vắng', '(bị) bỏng', 'trúng (xổ số)', 'vắng', 'generated' from jp_vocab where id = '3edd83be-2584-478d-a322-01acc0cd6ff9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vắng"?', '十分', '空く', 'やむ', '晴れる', '空く', 'generated' from jp_vocab where id = '3edd83be-2584-478d-a322-01acc0cd6ff9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"空く" đọc là gì?', 'せきがでる', 'すく', 'じゅうぶん', 'うるさい', 'すく', 'generated' from jp_vocab where id = '3edd83be-2584-478d-a322-01acc0cd6ff9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 電車が_____いる。', NULL, NULL, NULL, NULL, '空いて', 'generated' from jp_vocab where id = '3edd83be-2584-478d-a322-01acc0cd6ff9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"当たる" có nghĩa là gì?', 'kéo dài, liên tiếp', 'thất bại, trượt (kì thi)', 'có mây', 'trúng (xổ số)', 'trúng (xổ số)', 'generated' from jp_vocab where id = '3a0421e0-4038-4fb4-90bf-48d7b926fed7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "trúng (xổ số)"?', '空く', '当たる', '先生', '失敗する', '当たる', 'generated' from jp_vocab where id = '3a0421e0-4038-4fb4-90bf-48d7b926fed7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"当たる" đọc là gì?', 'あたる', 'やけど', 'ひやす', 'やむ', 'あたる', 'generated' from jp_vocab where id = '3a0421e0-4038-4fb4-90bf-48d7b926fed7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 宝くじが_____た。', NULL, NULL, NULL, NULL, '当たっ', 'generated' from jp_vocab where id = '3a0421e0-4038-4fb4-90bf-48d7b926fed7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"出る" có nghĩa là gì?', 'tham gia (trận đấu)', 'vắng', 'bác sĩ', 'trúng (xổ số)', 'tham gia (trận đấu)', 'generated' from jp_vocab where id = 'e2e1b58c-9d56-4d16-b764-ae352408cb06';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tham gia (trận đấu)"?', '火傷', '出る', '曇る', '無理をする', '出る', 'generated' from jp_vocab where id = 'e2e1b58c-9d56-4d16-b764-ae352408cb06';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"出る" đọc là gì?', 'やけど', 'はたらきすぎ', 'でる', 'けが', 'でる', 'generated' from jp_vocab where id = 'e2e1b58c-9d56-4d16-b764-ae352408cb06';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 試合に_____。', NULL, NULL, NULL, NULL, '出る', 'generated' from jp_vocab where id = 'e2e1b58c-9d56-4d16-b764-ae352408cb06';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"無理をする" có nghĩa là gì?', 'bác sĩ', 'lạ, thú vị', 'gắng sức', 'vận động', 'gắng sức', 'generated' from jp_vocab where id = '02cc679d-947a-433f-917e-1cd1acbc13c5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "gắng sức"?', '無理をする', '合格する', '失敗する', '晴れる', '無理をする', 'generated' from jp_vocab where id = '02cc679d-947a-433f-917e-1cd1acbc13c5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"無理をする" đọc là gì?', 'あたる', 'でる', 'うんどうする', 'むりをする', 'むりをする', 'generated' from jp_vocab where id = '02cc679d-947a-433f-917e-1cd1acbc13c5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____しないでください。', NULL, NULL, NULL, NULL, '無理をする', 'generated' from jp_vocab where id = '02cc679d-947a-433f-917e-1cd1acbc13c5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"働き過ぎ" có nghĩa là gì?', 'kéo dài, liên tiếp', 'có mây', 'làm việc quá sức', 'đỗ (kì thi)', 'làm việc quá sức', 'generated' from jp_vocab where id = 'ad2a5f65-3853-4928-8534-4a5ba5dd2a8e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "làm việc quá sức"?', '続く', '成功する', '働き過ぎ', '運動する', '働き過ぎ', 'generated' from jp_vocab where id = 'ad2a5f65-3853-4928-8534-4a5ba5dd2a8e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"働き過ぎ" đọc là gì?', 'けが', 'はたらきすぎ', 'あたる', 'やけど', 'はたらきすぎ', 'generated' from jp_vocab where id = 'ad2a5f65-3853-4928-8534-4a5ba5dd2a8e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____は体に悪い。', NULL, NULL, NULL, NULL, '働き過ぎ', 'generated' from jp_vocab where id = 'ad2a5f65-3853-4928-8534-4a5ba5dd2a8e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"十分" có nghĩa là gì?', 'đủ', '(bị) ho', 'bị cảm', 'mặt trời', 'đủ', 'generated' from jp_vocab where id = '117342eb-9f04-4659-bcfc-68f5bcc255e0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đủ"?', '十分', '咳をする', '続く', '込む', '十分', 'generated' from jp_vocab where id = '117342eb-9f04-4659-bcfc-68f5bcc255e0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"十分" đọc là gì?', 'はたらきすぎ', 'せんせい', 'うるさい', 'じゅうぶん', 'じゅうぶん', 'generated' from jp_vocab where id = '117342eb-9f04-4659-bcfc-68f5bcc255e0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: もう_____です。', NULL, NULL, NULL, NULL, '十分', 'generated' from jp_vocab where id = '117342eb-9f04-4659-bcfc-68f5bcc255e0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"おかしい" có nghĩa là gì?', 'đông đúc', 'làm việc quá sức', 'lạ, thú vị', '(bị) ho', 'lạ, thú vị', 'generated' from jp_vocab where id = 'b2a27afe-3bec-48d6-87a2-7760a45dd6f3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "lạ, thú vị"?', '空く', 'おかしい', '運動する', '咳をする', 'おかしい', 'generated' from jp_vocab where id = 'b2a27afe-3bec-48d6-87a2-7760a45dd6f3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"おかしい" đọc là gì?', 'あたる', 'うるさい', 'おかしい', 'たいよう', 'おかしい', 'generated' from jp_vocab where id = 'b2a27afe-3bec-48d6-87a2-7760a45dd6f3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: この話は_____。', NULL, NULL, NULL, NULL, 'おかしい', 'generated' from jp_vocab where id = 'b2a27afe-3bec-48d6-87a2-7760a45dd6f3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"うるさい" có nghĩa là gì?', 'ồn ào', 'ho', '(bị) bỏng', 'tạnh (mưa)', 'ồn ào', 'generated' from jp_vocab where id = '4f5b4432-e628-46bc-a81d-fbfa4efbc47a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "ồn ào"?', 'うるさい', '咳が出る', 'やむ', '空く', 'うるさい', 'generated' from jp_vocab where id = '4f5b4432-e628-46bc-a81d-fbfa4efbc47a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"うるさい" đọc là gì?', 'うるさい', 'でる', 'つづく', 'すく', 'うるさい', 'generated' from jp_vocab where id = '4f5b4432-e628-46bc-a81d-fbfa4efbc47a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 外が_____。', NULL, NULL, NULL, NULL, 'うるさい', 'generated' from jp_vocab where id = '4f5b4432-e628-46bc-a81d-fbfa4efbc47a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"先生" có nghĩa là gì?', 'đỗ (kì thi)', 'bác sĩ', 'mặt trời', '(bị) bỏng', 'bác sĩ', 'generated' from jp_vocab where id = '7d8b4f2f-51e6-4256-b8e0-7349bb0803f8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "bác sĩ"?', '先生', '十分', '咳が出る', '空く', '先生', 'generated' from jp_vocab where id = '7d8b4f2f-51e6-4256-b8e0-7349bb0803f8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"先生" đọc là gì?', 'しっぱいする', 'すく', 'こむ', 'せんせい', 'せんせい', 'generated' from jp_vocab where id = '7d8b4f2f-51e6-4256-b8e0-7349bb0803f8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に診てもらう。', NULL, NULL, NULL, NULL, '先生', 'generated' from jp_vocab where id = '7d8b4f2f-51e6-4256-b8e0-7349bb0803f8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"火傷" có nghĩa là gì?', 'đông đúc', 'mặt trời', '(bị) bỏng', 'bị cảm', '(bị) bỏng', 'generated' from jp_vocab where id = 'c1d00eae-8540-4083-89ea-8dc91aa11355';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "(bị) bỏng"?', '怪我', '火傷', '先生', '合格する', '火傷', 'generated' from jp_vocab where id = 'c1d00eae-8540-4083-89ea-8dc91aa11355';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"火傷" đọc là gì?', 'やけど', 'ごうかくする', 'けが', 'すく', 'やけど', 'generated' from jp_vocab where id = 'c1d00eae-8540-4083-89ea-8dc91aa11355';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 料理中に_____をした。', NULL, NULL, NULL, NULL, '火傷', 'generated' from jp_vocab where id = 'c1d00eae-8540-4083-89ea-8dc91aa11355';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"怪我" có nghĩa là gì?', 'đủ', '(bị) bỏng', '(bị) thương', '(bị) ho', '(bị) thương', 'generated' from jp_vocab where id = '86a1214b-94b4-4a06-a8f0-5f5aefeab602';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "(bị) thương"?', '火傷', '怪我', '咳が出る', 'おかしい', '怪我', 'generated' from jp_vocab where id = '86a1214b-94b4-4a06-a8f0-5f5aefeab602';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"怪我" đọc là gì?', 'せきがでる', 'せいこうする', 'せきをする', 'けが', 'けが', 'generated' from jp_vocab where id = '86a1214b-94b4-4a06-a8f0-5f5aefeab602';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: サッカーで_____をした。', NULL, NULL, NULL, NULL, '怪我', 'generated' from jp_vocab where id = '86a1214b-94b4-4a06-a8f0-5f5aefeab602';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"咳をする" có nghĩa là gì?', 'gắng sức', 'ho', 'bị cảm', 'thất bại, trượt (kì thi)', 'ho', 'generated' from jp_vocab where id = 'bad4070c-4dd7-41f2-af3e-36723e9c37f2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "ho"?', '咳をする', '無理をする', '失敗する', '十分', '咳をする', 'generated' from jp_vocab where id = 'bad4070c-4dd7-41f2-af3e-36723e9c37f2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"咳をする" đọc là gì?', 'くもる', 'せきをする', 'うんどうする', 'でる', 'せきをする', 'generated' from jp_vocab where id = 'bad4070c-4dd7-41f2-af3e-36723e9c37f2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____と苦しい。', NULL, NULL, NULL, NULL, '咳をする', 'generated' from jp_vocab where id = 'bad4070c-4dd7-41f2-af3e-36723e9c37f2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"咳が出る" có nghĩa là gì?', '(bị) ho', 'thành công', 'tạnh (mưa)', 'đông đúc', '(bị) ho', 'generated' from jp_vocab where id = '416a91ea-161d-48f8-9af2-240f146785c9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "(bị) ho"?', '火傷', '咳が出る', '無理をする', '引く', '咳が出る', 'generated' from jp_vocab where id = '416a91ea-161d-48f8-9af2-240f146785c9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"咳が出る" đọc là gì?', 'おかしい', 'やむ', 'ひやす', 'せきがでる', 'せきがでる', 'generated' from jp_vocab where id = '416a91ea-161d-48f8-9af2-240f146785c9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 風邪で_____。', NULL, NULL, NULL, NULL, '咳が出る', 'generated' from jp_vocab where id = '416a91ea-161d-48f8-9af2-240f146785c9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"太陽" có nghĩa là gì?', 'tạnh (mưa)', 'mặt trời', 'tham gia (trận đấu)', '(bị) bỏng', 'mặt trời', 'generated' from jp_vocab where id = '8a4d165a-b831-4149-b002-ea97c19b0cf1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "mặt trời"?', 'おかしい', '込む', '太陽', 'やむ', '太陽', 'generated' from jp_vocab where id = '8a4d165a-b831-4149-b002-ea97c19b0cf1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"太陽" đọc là gì?', 'やけど', 'たいよう', 'おかしい', 'はたらきすぎ', 'たいよう', 'generated' from jp_vocab where id = '8a4d165a-b831-4149-b002-ea97c19b0cf1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が昇る。', NULL, NULL, NULL, NULL, '太陽', 'generated' from jp_vocab where id = '8a4d165a-b831-4149-b002-ea97c19b0cf1';
