-- ============================================================
-- jp-go — Từ vựng N4, 課32 (phần 2, 27 từ còn lại).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 22.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b43dc4c7-4ef2-4c48-af6b-64c5c398c736', 'N4', 32, 'word', '石', 'いし', 'hòn đá', NULL, '名詞', 22, '石', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e2c82536-b4a4-4ca8-8437-0d46a79f9ccd', 'N4', 32, 'word', '星', 'ほし', 'sao', NULL, '名詞', 22, '星', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b01d16a9-5402-4443-9e22-c02524d73d02', 'N4', 32, 'word', '風', 'かぜ', 'gió', NULL, '名詞', 22, '風', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('14e0dbc3-8a2a-4e3c-8852-5ee186950d0a', 'N4', 32, 'word', '東', 'ひがし', 'phía Đông', NULL, '名詞', 22, '東', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7f657cf5-9487-4df7-ac39-0bad6dce137c', 'N4', 32, 'word', '西', 'にし', 'phía Tây', NULL, '名詞', 22, '西', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d45c86e3-07fa-40c5-91ec-135a6fc413a3', 'N4', 32, 'word', '南', 'みなみ', 'phía Nam', NULL, '名詞', 22, '南', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('ecb2e7fa-97f7-4fcc-9630-86d4755cbf85', 'N4', 32, 'word', '北', 'きた', 'phía Bắc', NULL, '名詞', 22, '北', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b31ec76b-de58-4a74-9cfa-ac12eebb0c4f', 'N4', 32, 'word', '国際', 'こくさい', 'quốc tế', NULL, '名詞', 22, '国際', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('0b453e35-8d5f-421a-bd2e-5826e2f80269', 'N4', 32, 'word', '水道', 'すいどう', 'nước máy', NULL, '名詞', 22, '水道', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('1b9c8c2b-0544-4d9a-bc6e-9fcabf8d4dc0', 'N4', 32, 'word', 'エンジン', 'エンジン', 'động cơ', NULL, '名詞', 22, 'エンジン', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('efe11926-cb12-4bb0-a30b-062496830ec9', 'N4', 32, 'word', 'チーム', 'チーム', 'đội', NULL, '名詞', 22, 'チーム', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e3a14e3f-6d4a-421d-a58e-525313905efb', 'N4', 32, 'word', '夕方', 'ゆうがた', 'chiều tối', NULL, '名詞', 22, '夕方', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('775a2c84-95fd-4af6-a354-39ad3e3fe2d2', 'N4', 32, 'word', '昨夜', 'ゆうべ', 'tối hôm qua', NULL, '名詞', 22, '昨夜', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('c96f1820-606b-405c-8b31-3abbcbec22dd', 'N4', 32, 'word', '遅く', 'おそく', 'muộn', NULL, '副詞', 22, '遅く', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('34c1b306-9885-4b6a-8493-b3bc6b7bb8b3', 'N4', 32, 'word', 'こんなに', 'こんなに', 'như thế này', NULL, '副詞', 22, 'こんなに', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b756c6a5-6842-40d4-a246-b91ac2eb4d4a', 'N4', 32, 'word', 'そんなに', 'そんなに', 'như thế đó', NULL, '副詞', 22, 'そんなに', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('392b9943-a6ae-4af4-ac81-12f92d2b9d09', 'N4', 32, 'word', 'あんなに', 'あんなに', 'như thế kia', NULL, '副詞', 22, 'あんなに', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d2da4b8c-4d41-4ef3-8181-3f47b27d01e3', 'N4', 32, 'word', '元気', 'げんき', 'khỏe mạnh', NULL, 'な形容詞', 22, '元気', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d1e6d515-836e-47d6-b7dd-af6057878103', 'N4', 32, 'word', '胃', 'い', 'dạ dày', NULL, '名詞', 22, '胃', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('60f20bf1-4775-493c-943a-738414347679', 'N4', 32, 'word', 'ストレス', 'ストレス', 'căng thẳng', NULL, '名詞', 22, 'ストレス', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('1f6b2138-a4ac-40f7-bc26-eeb74131d8f1', 'N4', 32, 'word', '星占い', 'ほしうらない', 'chiêm tinh, bói sao', NULL, '名詞', 22, '星占い', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b0d79284-a8f8-48b4-92bb-ac8354eb1d4b', 'N4', 32, 'word', '体調', 'たいちょう', 'tình trạng cơ thể', NULL, '名詞', 22, '体調', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a6a9438a-32cf-49f0-bd07-e836d5bef245', 'N4', 32, 'word', '渋滞', 'じゅうたい', 'tắc đường', NULL, '名詞', 22, '渋滞', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('9aea8507-c798-4dd5-ad37-22a6da15e6b8', 'N4', 32, 'word', '牡牛座', 'おうしざ', 'Sao Kim ngưu', NULL, '名詞', 22, '牡牛座', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('4d79f698-6ad5-4d25-9110-87bd0bd70cff', 'N4', 32, 'word', '健康', 'けんこう', 'sức khỏe', NULL, '名詞', 22, '健康', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('16270dce-ac85-4cd4-8471-856989f41f05', 'N4', 32, 'word', '恋愛', 'れんあい', 'tình yêu', NULL, '名詞', 22, '恋愛', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('1dc6c6af-159d-472c-89b2-2fa6d5727bb8', 'N4', 32, 'word', 'ラッキーアイテム', 'ラッキーアイテム', 'vật mang lại may mắn', NULL, '名詞', 22, 'ラッキーアイテム', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '川で石を拾う。', 'Nhặt hòn đá ở sông.', '川で_____を拾う。', '石', 'generated' from jp_vocab where id = 'b43dc4c7-4ef2-4c48-af6b-64c5c398c736';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '夜空に星が見える。', 'Nhìn thấy sao trên bầu trời đêm.', '夜空に_____が見える。', '星', 'generated' from jp_vocab where id = 'e2c82536-b4a4-4ca8-8437-0d46a79f9ccd';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '強い風が吹く。', 'Gió mạnh thổi.', '強い_____が吹く。', '風', 'generated' from jp_vocab where id = 'b01d16a9-5402-4443-9e22-c02524d73d02';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '太陽は東から昇る。', 'Mặt trời mọc từ phía Đông.', '太陽は_____から昇る。', '東', 'generated' from jp_vocab where id = '14e0dbc3-8a2a-4e3c-8852-5ee186950d0a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '太陽は西に沈む。', 'Mặt trời lặn ở phía Tây.', '太陽は_____に沈む。', '西', 'generated' from jp_vocab where id = '7f657cf5-9487-4df7-ac39-0bad6dce137c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '南の島へ旅行する。', 'Đi du lịch đảo phía Nam.', '_____の島へ旅行する。', '南', 'generated' from jp_vocab where id = 'd45c86e3-07fa-40c5-91ec-135a6fc413a3';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '北の方は寒い。', 'Phía Bắc lạnh.', '_____の方は寒い。', '北', 'generated' from jp_vocab where id = 'ecb2e7fa-97f7-4fcc-9630-86d4755cbf85';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '国際会議に出席する。', 'Tham dự hội nghị quốc tế.', '_____会議に出席する。', '国際', 'generated' from jp_vocab where id = 'b31ec76b-de58-4a74-9cfa-ac12eebb0c4f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '水道の水を飲む。', 'Uống nước máy.', '_____の水を飲む。', '水道', 'generated' from jp_vocab where id = '0b453e35-8d5f-421a-bd2e-5826e2f80269';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '車のエンジンをかける。', 'Nổ máy xe.', '車の_____をかける。', 'エンジン', 'generated' from jp_vocab where id = '1b9c8c2b-0544-4d9a-bc6e-9fcabf8d4dc0';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '私たちのチームが勝った。', 'Đội của chúng tôi đã thắng.', '私たちの_____が勝った。', 'チーム', 'generated' from jp_vocab where id = 'efe11926-cb12-4bb0-a30b-062496830ec9';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '夕方に散歩する。', 'Đi dạo vào chiều tối.', '_____に散歩する。', '夕方', 'generated' from jp_vocab where id = 'e3a14e3f-6d4a-421d-a58e-525313905efb';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '昨夜、雨が降った。', 'Tối hôm qua trời mưa.', '_____、雨が降った。', '昨夜', 'generated' from jp_vocab where id = '775a2c84-95fd-4af6-a354-39ad3e3fe2d2';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '昨夜は遅くまで働いた。', 'Tối qua tôi đã làm việc đến muộn.', '昨夜は_____まで働いた。', '遅く', 'generated' from jp_vocab where id = 'c96f1820-606b-405c-8b31-3abbcbec22dd';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'こんなに大きいとは思わなかった。', 'Tôi không nghĩ nó lại lớn như thế này.', '_____大きいとは思わなかった。', 'こんなに', 'generated' from jp_vocab where id = '34c1b306-9885-4b6a-8493-b3bc6b7bb8b3';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'そんなに心配しないで。', 'Đừng lo lắng như thế đó.', '_____心配しないで。', 'そんなに', 'generated' from jp_vocab where id = 'b756c6a5-6842-40d4-a246-b91ac2eb4d4a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'あんなに頑張ったのに。', 'Đã cố gắng như thế kia mà.', '_____頑張ったのに。', 'あんなに', 'generated' from jp_vocab where id = '392b9943-a6ae-4af4-ac81-12f92d2b9d09';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '元気になりましたか。', 'Bạn đã khỏe lại chưa?', '_____になりましたか。', '元気', 'generated' from jp_vocab where id = 'd2da4b8c-4d41-4ef3-8181-3f47b27d01e3';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '胃が痛い。', 'Đau dạ dày.', '_____が痛い。', '胃', 'generated' from jp_vocab where id = 'd1e6d515-836e-47d6-b7dd-af6057878103';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '仕事でストレスがたまる。', 'Căng thẳng tích tụ vì công việc.', '仕事で_____がたまる。', 'ストレス', 'generated' from jp_vocab where id = '60f20bf1-4775-493c-943a-738414347679';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '星占いを見るのが好きだ。', 'Thích xem chiêm tinh.', '_____を見るのが好きだ。', '星占い', 'generated' from jp_vocab where id = '1f6b2138-a4ac-40f7-bc26-eeb74131d8f1';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '体調が悪い。', 'Tình trạng cơ thể không tốt.', '_____が悪い。', '体調', 'generated' from jp_vocab where id = 'b0d79284-a8f8-48b4-92bb-ac8354eb1d4b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '道が渋滞している。', 'Đường đang tắc.', '道が_____している。', '渋滞', 'generated' from jp_vocab where id = 'a6a9438a-32cf-49f0-bd07-e836d5bef245';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '私は牡牛座です。', 'Tôi là cung Kim Ngưu.', '私は_____です。', '牡牛座', 'generated' from jp_vocab where id = '9aea8507-c798-4dd5-ad37-22a6da15e6b8';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '健康に気をつける。', 'Chú ý đến sức khỏe.', '_____に気をつける。', '健康', 'generated' from jp_vocab where id = '4d79f698-6ad5-4d25-9110-87bd0bd70cff';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彼らは恋愛している。', 'Họ đang yêu nhau.', '彼らは_____している。', '恋愛', 'generated' from jp_vocab where id = '16270dce-ac85-4cd4-8471-856989f41f05';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '今日のラッキーアイテムは赤い財布です。', 'Vật may mắn hôm nay là ví đỏ.', '今日の_____は赤い財布です。', 'ラッキーアイテム', 'generated' from jp_vocab where id = '1dc6c6af-159d-472c-89b2-2fa6d5727bb8';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"石" có nghĩa là gì?', 'hòn đá', 'chiêm tinh, bói sao', 'như thế này', 'nước máy', 'hòn đá', 'generated' from jp_vocab where id = 'b43dc4c7-4ef2-4c48-af6b-64c5c398c736';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "hòn đá"?', '胃', '石', '渋滞', '南', '石', 'generated' from jp_vocab where id = 'b43dc4c7-4ef2-4c48-af6b-64c5c398c736';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"石" đọc là gì?', 'おそく', 'そんなに', 'いし', 'すいどう', 'いし', 'generated' from jp_vocab where id = 'b43dc4c7-4ef2-4c48-af6b-64c5c398c736';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 川で_____を拾う。', NULL, NULL, NULL, NULL, '石', 'generated' from jp_vocab where id = 'b43dc4c7-4ef2-4c48-af6b-64c5c398c736';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"星" có nghĩa là gì?', 'dạ dày', 'như thế đó', 'như thế này', 'sao', 'sao', 'generated' from jp_vocab where id = 'e2c82536-b4a4-4ca8-8437-0d46a79f9ccd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sao"?', '胃', 'ラッキーアイテム', 'あんなに', '星', '星', 'generated' from jp_vocab where id = 'e2c82536-b4a4-4ca8-8437-0d46a79f9ccd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"星" đọc là gì?', 'かぜ', 'ほし', 'げんき', 'あんなに', 'ほし', 'generated' from jp_vocab where id = 'e2c82536-b4a4-4ca8-8437-0d46a79f9ccd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 夜空に_____が見える。', NULL, NULL, NULL, NULL, '星', 'generated' from jp_vocab where id = 'e2c82536-b4a4-4ca8-8437-0d46a79f9ccd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"風" có nghĩa là gì?', 'gió', 'căng thẳng', 'phía Đông', 'động cơ', 'gió', 'generated' from jp_vocab where id = 'b01d16a9-5402-4443-9e22-c02524d73d02';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "gió"?', '昨夜', '北', '健康', '風', '風', 'generated' from jp_vocab where id = 'b01d16a9-5402-4443-9e22-c02524d73d02';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"風" đọc là gì?', 'そんなに', 'あんなに', 'かぜ', 'ひがし', 'かぜ', 'generated' from jp_vocab where id = 'b01d16a9-5402-4443-9e22-c02524d73d02';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 強い_____が吹く。', NULL, NULL, NULL, NULL, '風', 'generated' from jp_vocab where id = 'b01d16a9-5402-4443-9e22-c02524d73d02';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"東" có nghĩa là gì?', 'như thế này', 'phía Tây', 'phía Bắc', 'phía Đông', 'phía Đông', 'generated' from jp_vocab where id = '14e0dbc3-8a2a-4e3c-8852-5ee186950d0a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phía Đông"?', 'エンジン', '恋愛', '東', '渋滞', '東', 'generated' from jp_vocab where id = '14e0dbc3-8a2a-4e3c-8852-5ee186950d0a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"東" đọc là gì?', 'けんこう', 'ほしうらない', 'いし', 'ひがし', 'ひがし', 'generated' from jp_vocab where id = '14e0dbc3-8a2a-4e3c-8852-5ee186950d0a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 太陽は_____から昇る。', NULL, NULL, NULL, NULL, '東', 'generated' from jp_vocab where id = '14e0dbc3-8a2a-4e3c-8852-5ee186950d0a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"西" có nghĩa là gì?', 'phía Tây', 'động cơ', 'căng thẳng', 'Sao Kim ngưu', 'phía Tây', 'generated' from jp_vocab where id = '7f657cf5-9487-4df7-ac39-0bad6dce137c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phía Tây"?', '西', '国際', '北', '恋愛', '西', 'generated' from jp_vocab where id = '7f657cf5-9487-4df7-ac39-0bad6dce137c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"西" đọc là gì?', 'にし', 'おうしざ', 'すいどう', 'そんなに', 'にし', 'generated' from jp_vocab where id = '7f657cf5-9487-4df7-ac39-0bad6dce137c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 太陽は_____に沈む。', NULL, NULL, NULL, NULL, '西', 'generated' from jp_vocab where id = '7f657cf5-9487-4df7-ac39-0bad6dce137c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"南" có nghĩa là gì?', 'phía Đông', 'phía Nam', 'như thế này', 'phía Tây', 'phía Nam', 'generated' from jp_vocab where id = 'd45c86e3-07fa-40c5-91ec-135a6fc413a3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phía Nam"?', '健康', 'エンジン', '南', 'ストレス', '南', 'generated' from jp_vocab where id = 'd45c86e3-07fa-40c5-91ec-135a6fc413a3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"南" đọc là gì?', 'ゆうべ', 'い', 'いし', 'みなみ', 'みなみ', 'generated' from jp_vocab where id = 'd45c86e3-07fa-40c5-91ec-135a6fc413a3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____の島へ旅行する。', NULL, NULL, NULL, NULL, '南', 'generated' from jp_vocab where id = 'd45c86e3-07fa-40c5-91ec-135a6fc413a3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"北" có nghĩa là gì?', 'phía Bắc', 'phía Đông', 'như thế kia', 'phía Tây', 'phía Bắc', 'generated' from jp_vocab where id = 'ecb2e7fa-97f7-4fcc-9630-86d4755cbf85';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phía Bắc"?', '北', '国際', '元気', '星', '北', 'generated' from jp_vocab where id = 'ecb2e7fa-97f7-4fcc-9630-86d4755cbf85';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"北" đọc là gì?', 'ほし', 'じゅうたい', 'きた', 'げんき', 'きた', 'generated' from jp_vocab where id = 'ecb2e7fa-97f7-4fcc-9630-86d4755cbf85';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____の方は寒い。', NULL, NULL, NULL, NULL, '北', 'generated' from jp_vocab where id = 'ecb2e7fa-97f7-4fcc-9630-86d4755cbf85';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"国際" có nghĩa là gì?', 'muộn', 'sức khỏe', 'phía Đông', 'quốc tế', 'quốc tế', 'generated' from jp_vocab where id = 'b31ec76b-de58-4a74-9cfa-ac12eebb0c4f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "quốc tế"?', 'チーム', '昨夜', '国際', '胃', '国際', 'generated' from jp_vocab where id = 'b31ec76b-de58-4a74-9cfa-ac12eebb0c4f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"国際" đọc là gì?', 'すいどう', 'けんこう', 'ほしうらない', 'こくさい', 'こくさい', 'generated' from jp_vocab where id = 'b31ec76b-de58-4a74-9cfa-ac12eebb0c4f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____会議に出席する。', NULL, NULL, NULL, NULL, '国際', 'generated' from jp_vocab where id = 'b31ec76b-de58-4a74-9cfa-ac12eebb0c4f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"水道" có nghĩa là gì?', 'như thế này', 'tình trạng cơ thể', 'sao', 'nước máy', 'nước máy', 'generated' from jp_vocab where id = '0b453e35-8d5f-421a-bd2e-5826e2f80269';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nước máy"?', '西', '水道', '夕方', 'そんなに', '水道', 'generated' from jp_vocab where id = '0b453e35-8d5f-421a-bd2e-5826e2f80269';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"水道" đọc là gì?', 'すいどう', 'じゅうたい', 'こんなに', 'チーム', 'すいどう', 'generated' from jp_vocab where id = '0b453e35-8d5f-421a-bd2e-5826e2f80269';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____の水を飲む。', NULL, NULL, NULL, NULL, '水道', 'generated' from jp_vocab where id = '0b453e35-8d5f-421a-bd2e-5826e2f80269';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"エンジン" có nghĩa là gì?', 'tình yêu', 'vật mang lại may mắn', 'động cơ', 'chiêm tinh, bói sao', 'động cơ', 'generated' from jp_vocab where id = '1b9c8c2b-0544-4d9a-bc6e-9fcabf8d4dc0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "động cơ"?', '東', 'エンジン', '恋愛', '星', 'エンジン', 'generated' from jp_vocab where id = '1b9c8c2b-0544-4d9a-bc6e-9fcabf8d4dc0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"エンジン" đọc là gì?', 'ラッキーアイテム', 'エンジン', 'おうしざ', 'チーム', 'エンジン', 'generated' from jp_vocab where id = '1b9c8c2b-0544-4d9a-bc6e-9fcabf8d4dc0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 車の_____をかける。', NULL, NULL, NULL, NULL, 'エンジン', 'generated' from jp_vocab where id = '1b9c8c2b-0544-4d9a-bc6e-9fcabf8d4dc0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"チーム" có nghĩa là gì?', 'tình trạng cơ thể', 'tắc đường', 'đội', 'tình yêu', 'đội', 'generated' from jp_vocab where id = 'efe11926-cb12-4bb0-a30b-062496830ec9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đội"?', 'チーム', '遅く', 'そんなに', 'ストレス', 'チーム', 'generated' from jp_vocab where id = 'efe11926-cb12-4bb0-a30b-062496830ec9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"チーム" đọc là gì?', 'ストレス', 'すいどう', 'チーム', 'じゅうたい', 'チーム', 'generated' from jp_vocab where id = 'efe11926-cb12-4bb0-a30b-062496830ec9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 私たちの_____が勝った。', NULL, NULL, NULL, NULL, 'チーム', 'generated' from jp_vocab where id = 'efe11926-cb12-4bb0-a30b-062496830ec9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"夕方" có nghĩa là gì?', 'chiều tối', 'chiêm tinh, bói sao', 'nước máy', 'tắc đường', 'chiều tối', 'generated' from jp_vocab where id = 'e3a14e3f-6d4a-421d-a58e-525313905efb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chiều tối"?', '夕方', '石', 'ラッキーアイテム', '牡牛座', '夕方', 'generated' from jp_vocab where id = 'e3a14e3f-6d4a-421d-a58e-525313905efb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"夕方" đọc là gì?', 'じゅうたい', 'あんなに', 'すいどう', 'ゆうがた', 'ゆうがた', 'generated' from jp_vocab where id = 'e3a14e3f-6d4a-421d-a58e-525313905efb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に散歩する。', NULL, NULL, NULL, NULL, '夕方', 'generated' from jp_vocab where id = 'e3a14e3f-6d4a-421d-a58e-525313905efb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"昨夜" có nghĩa là gì?', 'phía Nam', 'tình trạng cơ thể', 'tối hôm qua', 'phía Bắc', 'tối hôm qua', 'generated' from jp_vocab where id = '775a2c84-95fd-4af6-a354-39ad3e3fe2d2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tối hôm qua"?', '風', '昨夜', '北', '胃', '昨夜', 'generated' from jp_vocab where id = '775a2c84-95fd-4af6-a354-39ad3e3fe2d2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"昨夜" đọc là gì?', 'ほし', 'ゆうべ', 'ストレス', 'みなみ', 'ゆうべ', 'generated' from jp_vocab where id = '775a2c84-95fd-4af6-a354-39ad3e3fe2d2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____、雨が降った。', NULL, NULL, NULL, NULL, '昨夜', 'generated' from jp_vocab where id = '775a2c84-95fd-4af6-a354-39ad3e3fe2d2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"遅く" có nghĩa là gì?', 'muộn', 'tắc đường', 'như thế kia', 'như thế này', 'muộn', 'generated' from jp_vocab where id = 'c96f1820-606b-405c-8b31-3abbcbec22dd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "muộn"?', '体調', 'チーム', '遅く', 'ストレス', '遅く', 'generated' from jp_vocab where id = 'c96f1820-606b-405c-8b31-3abbcbec22dd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"遅く" đọc là gì?', 'おそく', 'にし', 'こくさい', 'チーム', 'おそく', 'generated' from jp_vocab where id = 'c96f1820-606b-405c-8b31-3abbcbec22dd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 昨夜は_____まで働いた。', NULL, NULL, NULL, NULL, '遅く', 'generated' from jp_vocab where id = 'c96f1820-606b-405c-8b31-3abbcbec22dd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"こんなに" có nghĩa là gì?', 'tình yêu', 'vật mang lại may mắn', 'như thế này', 'phía Tây', 'như thế này', 'generated' from jp_vocab where id = '34c1b306-9885-4b6a-8493-b3bc6b7bb8b3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "như thế này"?', '遅く', '星', '南', 'こんなに', 'こんなに', 'generated' from jp_vocab where id = '34c1b306-9885-4b6a-8493-b3bc6b7bb8b3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"こんなに" đọc là gì?', 'チーム', 'いし', 'れんあい', 'こんなに', 'こんなに', 'generated' from jp_vocab where id = '34c1b306-9885-4b6a-8493-b3bc6b7bb8b3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____大きいとは思わなかった。', NULL, NULL, NULL, NULL, 'こんなに', 'generated' from jp_vocab where id = '34c1b306-9885-4b6a-8493-b3bc6b7bb8b3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"そんなに" có nghĩa là gì?', 'như thế này', 'muộn', 'như thế đó', 'tối hôm qua', 'như thế đó', 'generated' from jp_vocab where id = 'b756c6a5-6842-40d4-a246-b91ac2eb4d4a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "như thế đó"?', '東', '元気', 'そんなに', '北', 'そんなに', 'generated' from jp_vocab where id = 'b756c6a5-6842-40d4-a246-b91ac2eb4d4a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"そんなに" đọc là gì?', 'きた', 'そんなに', 'ラッキーアイテム', 'たいちょう', 'そんなに', 'generated' from jp_vocab where id = 'b756c6a5-6842-40d4-a246-b91ac2eb4d4a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____心配しないで。', NULL, NULL, NULL, NULL, 'そんなに', 'generated' from jp_vocab where id = 'b756c6a5-6842-40d4-a246-b91ac2eb4d4a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"あんなに" có nghĩa là gì?', 'sức khỏe', 'như thế kia', 'đội', 'căng thẳng', 'như thế kia', 'generated' from jp_vocab where id = '392b9943-a6ae-4af4-ac81-12f92d2b9d09';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "như thế kia"?', 'あんなに', '恋愛', '牡牛座', '西', 'あんなに', 'generated' from jp_vocab where id = '392b9943-a6ae-4af4-ac81-12f92d2b9d09';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"あんなに" đọc là gì?', 'あんなに', 'ストレス', 'みなみ', 'おうしざ', 'あんなに', 'generated' from jp_vocab where id = '392b9943-a6ae-4af4-ac81-12f92d2b9d09';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____頑張ったのに。', NULL, NULL, NULL, NULL, 'あんなに', 'generated' from jp_vocab where id = '392b9943-a6ae-4af4-ac81-12f92d2b9d09';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"元気" có nghĩa là gì?', 'sức khỏe', 'căng thẳng', 'dạ dày', 'khỏe mạnh', 'khỏe mạnh', 'generated' from jp_vocab where id = 'd2da4b8c-4d41-4ef3-8181-3f47b27d01e3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "khỏe mạnh"?', '国際', '北', '元気', '昨夜', '元気', 'generated' from jp_vocab where id = 'd2da4b8c-4d41-4ef3-8181-3f47b27d01e3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"元気" đọc là gì?', 'げんき', 'けんこう', 'みなみ', 'すいどう', 'げんき', 'generated' from jp_vocab where id = 'd2da4b8c-4d41-4ef3-8181-3f47b27d01e3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____になりましたか。', NULL, NULL, NULL, NULL, '元気', 'generated' from jp_vocab where id = 'd2da4b8c-4d41-4ef3-8181-3f47b27d01e3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"胃" có nghĩa là gì?', 'tình yêu', 'hòn đá', 'dạ dày', 'như thế này', 'dạ dày', 'generated' from jp_vocab where id = 'd1e6d515-836e-47d6-b7dd-af6057878103';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "dạ dày"?', '石', 'エンジン', '胃', '牡牛座', '胃', 'generated' from jp_vocab where id = 'd1e6d515-836e-47d6-b7dd-af6057878103';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"胃" đọc là gì?', 'けんこう', 'エンジン', 'い', 'チーム', 'い', 'generated' from jp_vocab where id = 'd1e6d515-836e-47d6-b7dd-af6057878103';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が痛い。', NULL, NULL, NULL, NULL, '胃', 'generated' from jp_vocab where id = 'd1e6d515-836e-47d6-b7dd-af6057878103';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ストレス" có nghĩa là gì?', 'chiều tối', 'căng thẳng', 'tắc đường', 'tình trạng cơ thể', 'căng thẳng', 'generated' from jp_vocab where id = '60f20bf1-4775-493c-943a-738414347679';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "căng thẳng"?', '夕方', '国際', 'ストレス', '胃', 'ストレス', 'generated' from jp_vocab where id = '60f20bf1-4775-493c-943a-738414347679';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ストレス" đọc là gì?', 'ストレス', 'こんなに', 'チーム', 'じゅうたい', 'ストレス', 'generated' from jp_vocab where id = '60f20bf1-4775-493c-943a-738414347679';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 仕事で_____がたまる。', NULL, NULL, NULL, NULL, 'ストレス', 'generated' from jp_vocab where id = '60f20bf1-4775-493c-943a-738414347679';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"星占い" có nghĩa là gì?', 'tắc đường', 'chiêm tinh, bói sao', 'động cơ', 'phía Đông', 'chiêm tinh, bói sao', 'generated' from jp_vocab where id = '1f6b2138-a4ac-40f7-bc26-eeb74131d8f1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chiêm tinh, bói sao"?', '東', '胃', '星占い', '国際', '星占い', 'generated' from jp_vocab where id = '1f6b2138-a4ac-40f7-bc26-eeb74131d8f1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"星占い" đọc là gì?', 'たいちょう', 'みなみ', 'きた', 'ほしうらない', 'ほしうらない', 'generated' from jp_vocab where id = '1f6b2138-a4ac-40f7-bc26-eeb74131d8f1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を見るのが好きだ。', NULL, NULL, NULL, NULL, '星占い', 'generated' from jp_vocab where id = '1f6b2138-a4ac-40f7-bc26-eeb74131d8f1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"体調" có nghĩa là gì?', 'phía Bắc', 'chiêm tinh, bói sao', 'tình trạng cơ thể', 'phía Đông', 'tình trạng cơ thể', 'generated' from jp_vocab where id = 'b0d79284-a8f8-48b4-92bb-ac8354eb1d4b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tình trạng cơ thể"?', '西', '風', '体調', 'こんなに', '体調', 'generated' from jp_vocab where id = 'b0d79284-a8f8-48b4-92bb-ac8354eb1d4b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"体調" đọc là gì?', 'ほし', 'いし', 'たいちょう', 'にし', 'たいちょう', 'generated' from jp_vocab where id = 'b0d79284-a8f8-48b4-92bb-ac8354eb1d4b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が悪い。', NULL, NULL, NULL, NULL, '体調', 'generated' from jp_vocab where id = 'b0d79284-a8f8-48b4-92bb-ac8354eb1d4b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"渋滞" có nghĩa là gì?', 'phía Nam', 'tắc đường', 'phía Tây', 'quốc tế', 'tắc đường', 'generated' from jp_vocab where id = 'a6a9438a-32cf-49f0-bd07-e836d5bef245';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tắc đường"?', '水道', 'チーム', '遅く', '渋滞', '渋滞', 'generated' from jp_vocab where id = 'a6a9438a-32cf-49f0-bd07-e836d5bef245';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"渋滞" đọc là gì?', 'ゆうべ', 'こくさい', 'じゅうたい', 'こんなに', 'じゅうたい', 'generated' from jp_vocab where id = 'a6a9438a-32cf-49f0-bd07-e836d5bef245';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 道が_____している。', NULL, NULL, NULL, NULL, '渋滞', 'generated' from jp_vocab where id = 'a6a9438a-32cf-49f0-bd07-e836d5bef245';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"牡牛座" có nghĩa là gì?', 'tình yêu', 'Sao Kim ngưu', 'căng thẳng', 'gió', 'Sao Kim ngưu', 'generated' from jp_vocab where id = '9aea8507-c798-4dd5-ad37-22a6da15e6b8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Sao Kim ngưu"?', '水道', '国際', '牡牛座', '夕方', '牡牛座', 'generated' from jp_vocab where id = '9aea8507-c798-4dd5-ad37-22a6da15e6b8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"牡牛座" đọc là gì?', 'おうしざ', 'ゆうがた', 'けんこう', 'エンジン', 'おうしざ', 'generated' from jp_vocab where id = '9aea8507-c798-4dd5-ad37-22a6da15e6b8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 私は_____です。', NULL, NULL, NULL, NULL, '牡牛座', 'generated' from jp_vocab where id = '9aea8507-c798-4dd5-ad37-22a6da15e6b8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"健康" có nghĩa là gì?', 'phía Tây', 'phía Bắc', 'sức khỏe', 'tình trạng cơ thể', 'sức khỏe', 'generated' from jp_vocab where id = '4d79f698-6ad5-4d25-9110-87bd0bd70cff';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sức khỏe"?', '健康', 'ストレス', '昨夜', '体調', '健康', 'generated' from jp_vocab where id = '4d79f698-6ad5-4d25-9110-87bd0bd70cff';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"健康" đọc là gì?', 'チーム', 'けんこう', 'こくさい', 'ひがし', 'けんこう', 'generated' from jp_vocab where id = '4d79f698-6ad5-4d25-9110-87bd0bd70cff';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に気をつける。', NULL, NULL, NULL, NULL, '健康', 'generated' from jp_vocab where id = '4d79f698-6ad5-4d25-9110-87bd0bd70cff';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"恋愛" có nghĩa là gì?', 'tình yêu', 'quốc tế', 'căng thẳng', 'như thế này', 'tình yêu', 'generated' from jp_vocab where id = '16270dce-ac85-4cd4-8471-856989f41f05';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tình yêu"?', '恋愛', 'チーム', '体調', '胃', '恋愛', 'generated' from jp_vocab where id = '16270dce-ac85-4cd4-8471-856989f41f05';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"恋愛" đọc là gì?', 'こくさい', 'きた', 'れんあい', 'かぜ', 'れんあい', 'generated' from jp_vocab where id = '16270dce-ac85-4cd4-8471-856989f41f05';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 彼らは_____している。', NULL, NULL, NULL, NULL, '恋愛', 'generated' from jp_vocab where id = '16270dce-ac85-4cd4-8471-856989f41f05';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ラッキーアイテム" có nghĩa là gì?', 'vật mang lại may mắn', 'khỏe mạnh', 'tắc đường', 'tối hôm qua', 'vật mang lại may mắn', 'generated' from jp_vocab where id = '1dc6c6af-159d-472c-89b2-2fa6d5727bb8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vật mang lại may mắn"?', 'ラッキーアイテム', '水道', '星', '胃', 'ラッキーアイテム', 'generated' from jp_vocab where id = '1dc6c6af-159d-472c-89b2-2fa6d5727bb8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ラッキーアイテム" đọc là gì?', 'ラッキーアイテム', 'エンジン', 'けんこう', 'げんき', 'ラッキーアイテム', 'generated' from jp_vocab where id = '1dc6c6af-159d-472c-89b2-2fa6d5727bb8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 今日の_____は赤い財布です。', NULL, NULL, NULL, NULL, 'ラッキーアイテム', 'generated' from jp_vocab where id = '1dc6c6af-159d-472c-89b2-2fa6d5727bb8';
