-- ============================================================
-- jp-go — Từ vựng N4, 課34 (phần 2, 22 từ còn lại).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 24.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('1a2d237e-01b8-4fef-9f9b-0463939f6d3e', 'N4', 34, 'word', '醤油', 'しょうゆ', 'xì dầu', NULL, '名詞', 24, '醤油', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('9683db9d-3d9f-4021-a361-db11be673fab', 'N4', 34, 'word', '材料', 'ざいりょう', 'nguyên liệu', NULL, '名詞', 24, '材料', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('455e414f-6126-46cc-8ad7-7876445b2507', 'N4', 34, 'word', '城', 'しろ', 'lâu đài', 'thường dùng dạng [お〜]', '名詞', 24, '城', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('348c33ef-0a3a-4b4a-a325-514448e8e6df', 'N4', 34, 'word', '天才', 'てんさい', 'thiên tài', NULL, '名詞', 24, '天才', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d2271fcc-5e12-4c1c-a30f-db3b8c4d67f9', 'N4', 34, 'word', 'お客さん', 'おきゃくさん', 'khách hàng', NULL, '名詞', 24, 'お客さん', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('81622af4-7f51-4eac-8379-222fe5b3ff2b', 'N4', 34, 'word', 'さっき', 'さっき', 'lúc nãy', NULL, '副詞', 24, 'さっき', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('c2725c5f-d88f-4cdf-b4f9-c23bb1ccd5e1', 'N4', 34, 'phrase', 'いかがですか', 'いかがですか', 'như thế nào ạ?', NULL, '副詞', 24, 'いかがですか', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a882f30e-f727-44ee-b221-ffee185c0f6d', 'N4', 34, 'word', '実家', 'じっか', 'quê', NULL, '名詞', 24, '実家', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d92d304e-8526-4d95-9916-280f780698ea', 'N4', 34, 'word', '計画', 'けいかく', 'kế hoạch', NULL, '名詞', 24, '計画', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('40cf557e-2a17-4677-bbd6-d906a3ccc619', 'N4', 34, 'word', '発音', 'はつおん', 'phát âm', NULL, '名詞', 24, '発音', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('c2529248-bef0-439f-987d-bea175198c3c', 'N4', 34, 'word', 'レインコート', 'レインコート', 'áo mưa', NULL, '名詞', 24, 'レインコート', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e86c7cae-75e3-4baa-a555-4a5277ff5494', 'N4', 34, 'word', 'マフラー', 'マフラー', 'khăn quàng cổ', NULL, '名詞', 24, 'マフラー', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('f216caca-2cdc-4e59-9258-1eb961e6842a', 'N4', 34, 'word', '様', 'さま', '(là cách nói lịch sự của ~さん)', 'hậu tố kính ngữ gắn sau tên, dùng thay cho 〜さん trang trọng hơn', '名詞', 24, '様', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e703b731-b82b-47c3-8bfc-abd9a24cc867', 'N4', 34, 'word', '鶏肉', 'とりにく', 'thịt gà', NULL, '名詞', 24, '鶏肉', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a7a62089-523f-4d57-9b38-6154cd39e7cf', 'N4', 34, 'word', '玉ねぎ', 'たまねぎ', 'hành tây', NULL, '名詞', 24, '玉ねぎ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('77fc90d3-b48c-44b6-b565-229e4904dd3b', 'N4', 34, 'word', '調味料', 'ちょうみりょう', 'gia vị', NULL, '名詞', 24, '調味料', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('6450c01a-7ac7-4d69-87d6-e37cab34ffc1', 'N4', 34, 'word', '適当な', 'てきとうな', 'thích hợp; đại khái, qua loa', NULL, 'な形容詞', 24, '適当な', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e9537ad1-80bf-450e-9a76-298bc52fdd19', 'N4', 34, 'phrase', '火にかける', 'ひにかける', 'bắc lên bếp', NULL, '動詞', 24, '火にかける', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('2ca70937-e8cf-48e5-976f-b61d10a1606c', 'N4', 34, 'phrase', '火を消す', 'ひをけす', 'tắt bếp', NULL, '動詞', 24, '火を消す', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('8fb0ec44-6d9c-441f-9921-b4735a7f8e44', 'N4', 34, 'word', '煮る', 'にる', 'nấu, ninh', NULL, '動詞', 24, '煮る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('1e5b0581-1e5e-4be9-91a9-5e35927bd08f', 'N4', 34, 'word', '載せる', 'のせる', 'chất lên, đặt lên', NULL, '動詞', 24, '載せる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a953f8a6-416d-4433-9a1d-374fa9243aec', 'N4', 34, 'word', '丼', 'どんぶり', 'bát tô', NULL, '名詞', 24, '丼', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '醤油をかける。', 'Rưới xì dầu lên.', '_____をかける。', '醤油', 'generated' from jp_vocab where id = '1a2d237e-01b8-4fef-9f9b-0463939f6d3e';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '料理の材料を買う。', 'Mua nguyên liệu nấu ăn.', '料理の_____を買う。', '材料', 'generated' from jp_vocab where id = '9683db9d-3d9f-4021-a361-db11be673fab';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お城を見学する。', 'Đi tham quan lâu đài.', '_____を見学する。', 'お城', 'generated' from jp_vocab where id = '455e414f-6126-46cc-8ad7-7876445b2507';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彼は天才だ。', 'Anh ấy là một thiên tài.', '彼は_____だ。', '天才', 'generated' from jp_vocab where id = '348c33ef-0a3a-4b4a-a325-514448e8e6df';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お客さんが来た。', 'Khách hàng đã đến.', '_____が来た。', 'お客さん', 'generated' from jp_vocab where id = 'd2271fcc-5e12-4c1c-a30f-db3b8c4d67f9';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'さっき電話があった。', 'Lúc nãy có điện thoại gọi đến.', '_____電話があった。', 'さっき', 'generated' from jp_vocab where id = '81622af4-7f51-4eac-8379-222fe5b3ff2b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'コーヒーはいかがですか。', 'Anh/chị dùng cà phê thế nào ạ?', 'コーヒーは_____。', 'いかがですか', 'generated' from jp_vocab where id = 'c2725c5f-d88f-4cdf-b4f9-c23bb1ccd5e1';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '実家に帰る。', 'Về quê.', '_____に帰る。', '実家', 'generated' from jp_vocab where id = 'a882f30e-f727-44ee-b221-ffee185c0f6d';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '旅行の計画を立てる。', 'Lập kế hoạch du lịch.', '旅行の_____を立てる。', '計画', 'generated' from jp_vocab where id = 'd92d304e-8526-4d95-9916-280f780698ea';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '発音を練習する。', 'Luyện tập phát âm.', '_____を練習する。', '発音', 'generated' from jp_vocab where id = '40cf557e-2a17-4677-bbd6-d906a3ccc619';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '雨の日はレインコートを着る。', 'Ngày mưa mặc áo mưa.', '雨の日は_____を着る。', 'レインコート', 'generated' from jp_vocab where id = 'c2529248-bef0-439f-987d-bea175198c3c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '冬はマフラーを巻く。', 'Mùa đông quàng khăn.', '冬は_____を巻く。', 'マフラー', 'generated' from jp_vocab where id = 'e86c7cae-75e3-4baa-a555-4a5277ff5494';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '田中様、こちらへどうぞ。', 'Anh/chị Tanaka, xin mời lối này.', '田中_____、こちらへどうぞ。', '様', 'generated' from jp_vocab where id = 'f216caca-2cdc-4e59-9258-1eb961e6842a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '鶏肉を焼く。', 'Nướng thịt gà.', '_____を焼く。', '鶏肉', 'generated' from jp_vocab where id = 'e703b731-b82b-47c3-8bfc-abd9a24cc867';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '玉ねぎを切る。', 'Cắt hành tây.', '_____を切る。', '玉ねぎ', 'generated' from jp_vocab where id = 'a7a62089-523f-4d57-9b38-6154cd39e7cf';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '調味料を加える。', 'Thêm gia vị.', '_____を加える。', '調味料', 'generated' from jp_vocab where id = '77fc90d3-b48c-44b6-b565-229e4904dd3b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '適当な返事をする。', 'Trả lời qua loa.', '_____返事をする。', '適当な', 'generated' from jp_vocab where id = '6450c01a-7ac7-4d69-87d6-e37cab34ffc1';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '鍋を火にかける。', 'Bắc nồi lên bếp.', '鍋を_____。', '火にかける', 'generated' from jp_vocab where id = 'e9537ad1-80bf-450e-9a76-298bc52fdd19';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '火を消してください。', 'Xin hãy tắt bếp.', '_____てください。', '火を消し', 'generated' from jp_vocab where id = '2ca70937-e8cf-48e5-976f-b61d10a1606c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '野菜を煮る。', 'Ninh rau củ.', '野菜を_____。', '煮る', 'generated' from jp_vocab where id = '8fb0ec44-6d9c-441f-9921-b4735a7f8e44';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '荷物を車に載せる。', 'Chất hành lý lên xe.', '荷物を車に_____。', '載せる', 'generated' from jp_vocab where id = '1e5b0581-1e5e-4be9-91a9-5e35927bd08f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '丼にご飯を入れる。', 'Cho cơm vào bát tô.', '_____にご飯を入れる。', '丼', 'generated' from jp_vocab where id = 'a953f8a6-416d-4433-9a1d-374fa9243aec';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"醤油" có nghĩa là gì?', 'nguyên liệu', 'xì dầu', 'như thế nào ạ?', 'phát âm', 'xì dầu', 'generated' from jp_vocab where id = '1a2d237e-01b8-4fef-9f9b-0463939f6d3e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "xì dầu"?', '玉ねぎ', '適当な', '醤油', '城', '醤油', 'generated' from jp_vocab where id = '1a2d237e-01b8-4fef-9f9b-0463939f6d3e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"醤油" đọc là gì?', 'しょうゆ', 'ちょうみりょう', 'はつおん', 'レインコート', 'しょうゆ', 'generated' from jp_vocab where id = '1a2d237e-01b8-4fef-9f9b-0463939f6d3e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____をかける。', NULL, NULL, NULL, NULL, '醤油', 'generated' from jp_vocab where id = '1a2d237e-01b8-4fef-9f9b-0463939f6d3e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"材料" có nghĩa là gì?', 'nguyên liệu', '(là cách nói lịch sự của ~さん)', 'tắt bếp', 'bát tô', 'nguyên liệu', 'generated' from jp_vocab where id = '9683db9d-3d9f-4021-a361-db11be673fab';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nguyên liệu"?', '様', '載せる', '計画', '材料', '材料', 'generated' from jp_vocab where id = '9683db9d-3d9f-4021-a361-db11be673fab';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"材料" đọc là gì?', 'ざいりょう', 'いかがですか', 'にる', 'たまねぎ', 'ざいりょう', 'generated' from jp_vocab where id = '9683db9d-3d9f-4021-a361-db11be673fab';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 料理の_____を買う。', NULL, NULL, NULL, NULL, '材料', 'generated' from jp_vocab where id = '9683db9d-3d9f-4021-a361-db11be673fab';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"城" có nghĩa là gì?', 'kế hoạch', 'lâu đài', 'bắc lên bếp', 'phát âm', 'lâu đài', 'generated' from jp_vocab where id = '455e414f-6126-46cc-8ad7-7876445b2507';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "lâu đài"?', '丼', 'さっき', '城', 'マフラー', '城', 'generated' from jp_vocab where id = '455e414f-6126-46cc-8ad7-7876445b2507';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"城" đọc là gì?', 'はつおん', 'ちょうみりょう', 'さっき', 'しろ', 'しろ', 'generated' from jp_vocab where id = '455e414f-6126-46cc-8ad7-7876445b2507';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を見学する。', NULL, NULL, NULL, NULL, 'お城', 'generated' from jp_vocab where id = '455e414f-6126-46cc-8ad7-7876445b2507';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"天才" có nghĩa là gì?', 'bắc lên bếp', 'như thế nào ạ?', 'kế hoạch', 'thiên tài', 'thiên tài', 'generated' from jp_vocab where id = '348c33ef-0a3a-4b4a-a325-514448e8e6df';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thiên tài"?', '調味料', '煮る', '材料', '天才', '天才', 'generated' from jp_vocab where id = '348c33ef-0a3a-4b4a-a325-514448e8e6df';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"天才" đọc là gì?', 'マフラー', 'てんさい', 'ひにかける', 'のせる', 'てんさい', 'generated' from jp_vocab where id = '348c33ef-0a3a-4b4a-a325-514448e8e6df';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 彼は_____だ。', NULL, NULL, NULL, NULL, '天才', 'generated' from jp_vocab where id = '348c33ef-0a3a-4b4a-a325-514448e8e6df';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"お客さん" có nghĩa là gì?', 'khăn quàng cổ', 'nấu, ninh', 'khách hàng', 'xì dầu', 'khách hàng', 'generated' from jp_vocab where id = 'd2271fcc-5e12-4c1c-a30f-db3b8c4d67f9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "khách hàng"?', '城', 'お客さん', '実家', '様', 'お客さん', 'generated' from jp_vocab where id = 'd2271fcc-5e12-4c1c-a30f-db3b8c4d67f9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"お客さん" đọc là gì?', 'おきゃくさん', 'さっき', 'てんさい', 'マフラー', 'おきゃくさん', 'generated' from jp_vocab where id = 'd2271fcc-5e12-4c1c-a30f-db3b8c4d67f9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が来た。', NULL, NULL, NULL, NULL, 'お客さん', 'generated' from jp_vocab where id = 'd2271fcc-5e12-4c1c-a30f-db3b8c4d67f9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"さっき" có nghĩa là gì?', 'lúc nãy', 'quê', 'xì dầu', '(là cách nói lịch sự của ~さん)', 'lúc nãy', 'generated' from jp_vocab where id = '81622af4-7f51-4eac-8379-222fe5b3ff2b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "lúc nãy"?', 'マフラー', '煮る', 'さっき', 'レインコート', 'さっき', 'generated' from jp_vocab where id = '81622af4-7f51-4eac-8379-222fe5b3ff2b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"さっき" đọc là gì?', 'マフラー', 'ひをけす', 'けいかく', 'さっき', 'さっき', 'generated' from jp_vocab where id = '81622af4-7f51-4eac-8379-222fe5b3ff2b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____電話があった。', NULL, NULL, NULL, NULL, 'さっき', 'generated' from jp_vocab where id = '81622af4-7f51-4eac-8379-222fe5b3ff2b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"いかがですか" có nghĩa là gì?', 'lúc nãy', 'như thế nào ạ?', 'hành tây', 'khăn quàng cổ', 'như thế nào ạ?', 'generated' from jp_vocab where id = 'c2725c5f-d88f-4cdf-b4f9-c23bb1ccd5e1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "như thế nào ạ?"?', '火にかける', 'いかがですか', '天才', '計画', 'いかがですか', 'generated' from jp_vocab where id = 'c2725c5f-d88f-4cdf-b4f9-c23bb1ccd5e1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"いかがですか" đọc là gì?', 'たまねぎ', 'けいかく', 'ひをけす', 'いかがですか', 'いかがですか', 'generated' from jp_vocab where id = 'c2725c5f-d88f-4cdf-b4f9-c23bb1ccd5e1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: コーヒーは_____。', NULL, NULL, NULL, NULL, 'いかがですか', 'generated' from jp_vocab where id = 'c2725c5f-d88f-4cdf-b4f9-c23bb1ccd5e1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"実家" có nghĩa là gì?', 'quê', 'nấu, ninh', 'gia vị', 'bắc lên bếp', 'quê', 'generated' from jp_vocab where id = 'a882f30e-f727-44ee-b221-ffee185c0f6d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "quê"?', '鶏肉', '実家', '丼', '載せる', '実家', 'generated' from jp_vocab where id = 'a882f30e-f727-44ee-b221-ffee185c0f6d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"実家" đọc là gì?', 'マフラー', 'けいかく', 'しょうゆ', 'じっか', 'じっか', 'generated' from jp_vocab where id = 'a882f30e-f727-44ee-b221-ffee185c0f6d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に帰る。', NULL, NULL, NULL, NULL, '実家', 'generated' from jp_vocab where id = 'a882f30e-f727-44ee-b221-ffee185c0f6d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"計画" có nghĩa là gì?', 'kế hoạch', 'xì dầu', 'nguyên liệu', 'khách hàng', 'kế hoạch', 'generated' from jp_vocab where id = 'd92d304e-8526-4d95-9916-280f780698ea';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "kế hoạch"?', '発音', 'お客さん', '計画', '玉ねぎ', '計画', 'generated' from jp_vocab where id = 'd92d304e-8526-4d95-9916-280f780698ea';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"計画" đọc là gì?', 'じっか', 'のせる', 'ざいりょう', 'けいかく', 'けいかく', 'generated' from jp_vocab where id = 'd92d304e-8526-4d95-9916-280f780698ea';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 旅行の_____を立てる。', NULL, NULL, NULL, NULL, '計画', 'generated' from jp_vocab where id = 'd92d304e-8526-4d95-9916-280f780698ea';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"発音" có nghĩa là gì?', 'phát âm', 'gia vị', 'nguyên liệu', 'thích hợp; đại khái, qua loa', 'phát âm', 'generated' from jp_vocab where id = '40cf557e-2a17-4677-bbd6-d906a3ccc619';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phát âm"?', '天才', 'いかがですか', '発音', '調味料', '発音', 'generated' from jp_vocab where id = '40cf557e-2a17-4677-bbd6-d906a3ccc619';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"発音" đọc là gì?', 'とりにく', 'はつおん', 'ひをけす', 'ひにかける', 'はつおん', 'generated' from jp_vocab where id = '40cf557e-2a17-4677-bbd6-d906a3ccc619';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を練習する。', NULL, NULL, NULL, NULL, '発音', 'generated' from jp_vocab where id = '40cf557e-2a17-4677-bbd6-d906a3ccc619';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"レインコート" có nghĩa là gì?', '(là cách nói lịch sự của ~さん)', 'áo mưa', 'tắt bếp', 'chất lên, đặt lên', 'áo mưa', 'generated' from jp_vocab where id = 'c2529248-bef0-439f-987d-bea175198c3c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "áo mưa"?', '天才', '火を消す', 'レインコート', '調味料', 'レインコート', 'generated' from jp_vocab where id = 'c2529248-bef0-439f-987d-bea175198c3c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"レインコート" đọc là gì?', 'どんぶり', 'レインコート', 'しょうゆ', 'ひにかける', 'レインコート', 'generated' from jp_vocab where id = 'c2529248-bef0-439f-987d-bea175198c3c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 雨の日は_____を着る。', NULL, NULL, NULL, NULL, 'レインコート', 'generated' from jp_vocab where id = 'c2529248-bef0-439f-987d-bea175198c3c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"マフラー" có nghĩa là gì?', 'bắc lên bếp', '(là cách nói lịch sự của ~さん)', 'phát âm', 'khăn quàng cổ', 'khăn quàng cổ', 'generated' from jp_vocab where id = 'e86c7cae-75e3-4baa-a555-4a5277ff5494';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "khăn quàng cổ"?', '材料', 'マフラー', 'さっき', '天才', 'マフラー', 'generated' from jp_vocab where id = 'e86c7cae-75e3-4baa-a555-4a5277ff5494';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"マフラー" đọc là gì?', 'ちょうみりょう', 'マフラー', 'しょうゆ', 'てきとうな', 'マフラー', 'generated' from jp_vocab where id = 'e86c7cae-75e3-4baa-a555-4a5277ff5494';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 冬は_____を巻く。', NULL, NULL, NULL, NULL, 'マフラー', 'generated' from jp_vocab where id = 'e86c7cae-75e3-4baa-a555-4a5277ff5494';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"様" có nghĩa là gì?', 'xì dầu', '(là cách nói lịch sự của ~さん)', 'lúc nãy', 'nguyên liệu', '(là cách nói lịch sự của ~さん)', 'generated' from jp_vocab where id = 'f216caca-2cdc-4e59-9258-1eb961e6842a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "(là cách nói lịch sự của ~さん)"?', '火を消す', '様', 'マフラー', '材料', '様', 'generated' from jp_vocab where id = 'f216caca-2cdc-4e59-9258-1eb961e6842a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"様" đọc là gì?', 'じっか', 'けいかく', 'ざいりょう', 'さま', 'さま', 'generated' from jp_vocab where id = 'f216caca-2cdc-4e59-9258-1eb961e6842a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 田中_____、こちらへどうぞ。', NULL, NULL, NULL, NULL, '様', 'generated' from jp_vocab where id = 'f216caca-2cdc-4e59-9258-1eb961e6842a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"鶏肉" có nghĩa là gì?', 'bắc lên bếp', '(là cách nói lịch sự của ~さん)', 'lúc nãy', 'thịt gà', 'thịt gà', 'generated' from jp_vocab where id = 'e703b731-b82b-47c3-8bfc-abd9a24cc867';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thịt gà"?', '鶏肉', '城', '実家', 'いかがですか', '鶏肉', 'generated' from jp_vocab where id = 'e703b731-b82b-47c3-8bfc-abd9a24cc867';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"鶏肉" đọc là gì?', 'にる', 'レインコート', 'とりにく', 'おきゃくさん', 'とりにく', 'generated' from jp_vocab where id = 'e703b731-b82b-47c3-8bfc-abd9a24cc867';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を焼く。', NULL, NULL, NULL, NULL, '鶏肉', 'generated' from jp_vocab where id = 'e703b731-b82b-47c3-8bfc-abd9a24cc867';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"玉ねぎ" có nghĩa là gì?', 'thiên tài', 'hành tây', 'khách hàng', 'áo mưa', 'hành tây', 'generated' from jp_vocab where id = 'a7a62089-523f-4d57-9b38-6154cd39e7cf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "hành tây"?', '鶏肉', '玉ねぎ', '城', '天才', '玉ねぎ', 'generated' from jp_vocab where id = 'a7a62089-523f-4d57-9b38-6154cd39e7cf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"玉ねぎ" đọc là gì?', 'さま', 'ひにかける', 'どんぶり', 'たまねぎ', 'たまねぎ', 'generated' from jp_vocab where id = 'a7a62089-523f-4d57-9b38-6154cd39e7cf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を切る。', NULL, NULL, NULL, NULL, '玉ねぎ', 'generated' from jp_vocab where id = 'a7a62089-523f-4d57-9b38-6154cd39e7cf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"調味料" có nghĩa là gì?', 'nấu, ninh', 'áo mưa', 'lâu đài', 'gia vị', 'gia vị', 'generated' from jp_vocab where id = '77fc90d3-b48c-44b6-b565-229e4904dd3b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "gia vị"?', '調味料', 'マフラー', '城', '計画', '調味料', 'generated' from jp_vocab where id = '77fc90d3-b48c-44b6-b565-229e4904dd3b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"調味料" đọc là gì?', 'ちょうみりょう', 'いかがですか', 'じっか', 'おきゃくさん', 'ちょうみりょう', 'generated' from jp_vocab where id = '77fc90d3-b48c-44b6-b565-229e4904dd3b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を加える。', NULL, NULL, NULL, NULL, '調味料', 'generated' from jp_vocab where id = '77fc90d3-b48c-44b6-b565-229e4904dd3b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"適当な" có nghĩa là gì?', 'khăn quàng cổ', 'thích hợp; đại khái, qua loa', 'áo mưa', 'như thế nào ạ?', 'thích hợp; đại khái, qua loa', 'generated' from jp_vocab where id = '6450c01a-7ac7-4d69-87d6-e37cab34ffc1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thích hợp; đại khái, qua loa"?', '調味料', '城', 'さっき', '適当な', '適当な', 'generated' from jp_vocab where id = '6450c01a-7ac7-4d69-87d6-e37cab34ffc1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"適当な" đọc là gì?', 'マフラー', 'のせる', 'てきとうな', 'ひをけす', 'てきとうな', 'generated' from jp_vocab where id = '6450c01a-7ac7-4d69-87d6-e37cab34ffc1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____返事をする。', NULL, NULL, NULL, NULL, '適当な', 'generated' from jp_vocab where id = '6450c01a-7ac7-4d69-87d6-e37cab34ffc1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"火にかける" có nghĩa là gì?', 'lúc nãy', 'bắc lên bếp', 'thịt gà', 'thích hợp; đại khái, qua loa', 'bắc lên bếp', 'generated' from jp_vocab where id = 'e9537ad1-80bf-450e-9a76-298bc52fdd19';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "bắc lên bếp"?', '醤油', '調味料', '玉ねぎ', '火にかける', '火にかける', 'generated' from jp_vocab where id = 'e9537ad1-80bf-450e-9a76-298bc52fdd19';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"火にかける" đọc là gì?', 'にる', 'とりにく', 'ひにかける', 'てきとうな', 'ひにかける', 'generated' from jp_vocab where id = 'e9537ad1-80bf-450e-9a76-298bc52fdd19';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 鍋を_____。', NULL, NULL, NULL, NULL, '火にかける', 'generated' from jp_vocab where id = 'e9537ad1-80bf-450e-9a76-298bc52fdd19';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"火を消す" có nghĩa là gì?', 'tắt bếp', 'thiên tài', 'như thế nào ạ?', 'nấu, ninh', 'tắt bếp', 'generated' from jp_vocab where id = '2ca70937-e8cf-48e5-976f-b61d10a1606c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tắt bếp"?', 'お客さん', 'マフラー', '火を消す', '材料', '火を消す', 'generated' from jp_vocab where id = '2ca70937-e8cf-48e5-976f-b61d10a1606c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"火を消す" đọc là gì?', 'とりにく', 'てきとうな', 'はつおん', 'ひをけす', 'ひをけす', 'generated' from jp_vocab where id = '2ca70937-e8cf-48e5-976f-b61d10a1606c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____てください。', NULL, NULL, NULL, NULL, '火を消し', 'generated' from jp_vocab where id = '2ca70937-e8cf-48e5-976f-b61d10a1606c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"煮る" có nghĩa là gì?', 'thiên tài', '(là cách nói lịch sự của ~さん)', 'phát âm', 'nấu, ninh', 'nấu, ninh', 'generated' from jp_vocab where id = '8fb0ec44-6d9c-441f-9921-b4735a7f8e44';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nấu, ninh"?', 'さっき', '発音', '煮る', '様', '煮る', 'generated' from jp_vocab where id = '8fb0ec44-6d9c-441f-9921-b4735a7f8e44';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"煮る" đọc là gì?', 'ざいりょう', 'おきゃくさん', 'にる', 'どんぶり', 'にる', 'generated' from jp_vocab where id = '8fb0ec44-6d9c-441f-9921-b4735a7f8e44';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 野菜を_____。', NULL, NULL, NULL, NULL, '煮る', 'generated' from jp_vocab where id = '8fb0ec44-6d9c-441f-9921-b4735a7f8e44';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"載せる" có nghĩa là gì?', 'chất lên, đặt lên', 'hành tây', 'nguyên liệu', 'khăn quàng cổ', 'chất lên, đặt lên', 'generated' from jp_vocab where id = '1e5b0581-1e5e-4be9-91a9-5e35927bd08f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chất lên, đặt lên"?', '調味料', '鶏肉', '載せる', '適当な', '載せる', 'generated' from jp_vocab where id = '1e5b0581-1e5e-4be9-91a9-5e35927bd08f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"載せる" đọc là gì?', 'さま', 'ひをけす', 'のせる', 'ひにかける', 'のせる', 'generated' from jp_vocab where id = '1e5b0581-1e5e-4be9-91a9-5e35927bd08f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 荷物を車に_____。', NULL, NULL, NULL, NULL, '載せる', 'generated' from jp_vocab where id = '1e5b0581-1e5e-4be9-91a9-5e35927bd08f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"丼" có nghĩa là gì?', 'thịt gà', 'áo mưa', 'bát tô', 'khăn quàng cổ', 'bát tô', 'generated' from jp_vocab where id = 'a953f8a6-416d-4433-9a1d-374fa9243aec';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "bát tô"?', '丼', 'マフラー', 'お客さん', '材料', '丼', 'generated' from jp_vocab where id = 'a953f8a6-416d-4433-9a1d-374fa9243aec';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"丼" đọc là gì?', 'いかがですか', 'どんぶり', 'のせる', 'レインコート', 'どんぶり', 'generated' from jp_vocab where id = 'a953f8a6-416d-4433-9a1d-374fa9243aec';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____にご飯を入れる。', NULL, NULL, NULL, NULL, '丼', 'generated' from jp_vocab where id = 'a953f8a6-416d-4433-9a1d-374fa9243aec';
