-- ============================================================
-- jp-go — Từ vựng N4, 課35 (phần 1, 19 từ đầu).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 24 (6 từ đầu) + trang in 25 (13 từ tiếp theo).
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('f178906d-b240-478c-81cb-8fe7f3d45321', 'N4', 35, 'word', '変わる', 'かわる', 'đổi, thay đổi', NULL, '動詞', 24, '変わる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('6671e488-3083-49eb-8f74-a1513948f873', 'N4', 35, 'word', '困る', 'こまる', 'khó khăn', NULL, '動詞', 24, '困る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('92d4cc91-a559-443a-9841-92b8ba7cfabb', 'N4', 35, 'word', '付ける', 'つける', 'đánh dấu (tròn)', 'thường dùng dạng [丸を〜]', '動詞', 24, '付ける', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('63b7b3f7-51a1-4294-828d-4b3e2912000d', 'N4', 35, 'word', '治る', 'なおる', 'khỏi (bệnh)', 'thường dùng dạng [病気が〜]', '動詞', 24, '治る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d6affa57-c627-4e18-a6a0-7ba36be5994f', 'N4', 35, 'word', '直る', 'なおる', '(hỏng hóc) được sửa xong', 'thường dùng dạng [故障が〜]', '動詞', 24, '直る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('9eb69b44-07fb-496a-8d94-90bb45ce4ba3', 'N4', 35, 'word', '入力する', 'にゅうりょくする', 'nhập vào', NULL, '動詞', 24, '入力する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e1229b82-e78b-45a6-be2a-f2cddbd60bb9', 'N4', 35, 'word', '仲良くする', 'なかよくする', 'chơi thân với (cô ấy)', 'thường dùng dạng [彼女と〜]', '動詞', 25, '仲良くする', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('46911948-0e28-4299-824b-7f924c88ebba', 'N4', 35, 'word', 'クリックする', 'クリックする', 'click chuột', NULL, '動詞', 25, 'クリックする', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('dc9bbbad-3ac7-402c-b902-cd9391632319', 'N4', 35, 'word', '咲く', 'さく', '(hoa) nở', 'thường dùng dạng [花が〜]', '動詞', 25, '咲く', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('41b71b63-1a29-401b-8635-a173d5787b08', 'N4', 35, 'word', '向こう', 'むこう', 'đằng ấy, phía đối diện', NULL, '名詞', 25, '向こう', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('4f19f286-ccb4-48bd-a545-679b0f0d823d', 'N4', 35, 'word', '島', 'しま', 'đảo', NULL, '名詞', 25, '島', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('41a63d57-b5e6-4b81-97a0-e21b56e4cf5e', 'N4', 35, 'word', '港', 'みなと', 'cảng', NULL, '名詞', 25, '港', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('0470acc3-e0a6-4ccc-8ee8-0d844ce2bc3f', 'N4', 35, 'word', '近所', 'きんじょ', 'hàng xóm, gần quanh đây', NULL, '名詞', 25, '近所', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e219ea6f-3bf4-4e19-ba1f-15df7c0c3c60', 'N4', 35, 'word', '屋上', 'おくじょう', 'tầng thượng', NULL, '名詞', 25, '屋上', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('8c2e848c-477d-455b-92d1-6adbdfe03b9b', 'N4', 35, 'word', '海外', 'かいがい', 'nước ngoài', NULL, '名詞', 25, '海外', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b872df5d-e91e-4dce-a3e7-e4560156c3c8', 'N4', 35, 'word', '山登り', 'やまのぼり', 'leo núi', NULL, '名詞', 25, '山登り', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('2a30d795-3b7d-4b82-a92e-e7536093315a', 'N4', 35, 'word', '歴史', 'れきし', 'lịch sử', NULL, '名詞', 25, '歴史', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('6819d2d6-63d5-42b0-bd08-40529b1db4b5', 'N4', 35, 'word', '機会', 'きかい', 'cơ hội', NULL, '名詞', 25, '機会', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('bf41ca0c-2ab2-4581-bd9b-d9b881db1185', 'N4', 35, 'word', '許可', 'きょか', 'sự cho phép', NULL, '名詞', 25, '許可', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '天気が変わる。', 'Thời tiết thay đổi.', '天気が_____。', '変わる', 'generated' from jp_vocab where id = 'f178906d-b240-478c-81cb-8fe7f3d45321';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お金がなくて困る。', 'Khó khăn vì không có tiền.', 'お金がなくて_____。', '困る', 'generated' from jp_vocab where id = '6671e488-3083-49eb-8f74-a1513948f873';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '正しい答えに丸を付ける。', 'Đánh dấu tròn vào đáp án đúng.', '正しい答えに丸を_____。', '付ける', 'generated' from jp_vocab where id = '92d4cc91-a559-443a-9841-92b8ba7cfabb';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '病気が治った。', 'Bệnh đã khỏi.', '病気が_____た。', '治っ', 'generated' from jp_vocab where id = '63b7b3f7-51a1-4294-828d-4b3e2912000d';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '故障が直った。', 'Hỏng hóc đã được sửa xong.', '故障が_____た。', '直っ', 'generated' from jp_vocab where id = 'd6affa57-c627-4e18-a6a0-7ba36be5994f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'パスワードを入力する。', 'Nhập mật khẩu.', 'パスワードを_____。', '入力する', 'generated' from jp_vocab where id = '9eb69b44-07fb-496a-8d94-90bb45ce4ba3';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彼女と仲良くする。', 'Chơi thân với cô ấy.', '彼女と_____。', '仲良くする', 'generated' from jp_vocab where id = 'e1229b82-e78b-45a6-be2a-f2cddbd60bb9';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ここをクリックする。', 'Click chuột vào đây.', 'ここを_____。', 'クリックする', 'generated' from jp_vocab where id = '46911948-0e28-4299-824b-7f924c88ebba';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '桜の花が咲く。', 'Hoa anh đào nở.', '桜の花が_____。', '咲く', 'generated' from jp_vocab where id = 'dc9bbbad-3ac7-402c-b902-cd9391632319';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '向こうに山が見える。', 'Nhìn thấy núi ở đằng kia.', '_____に山が見える。', '向こう', 'generated' from jp_vocab where id = '41b71b63-1a29-401b-8635-a173d5787b08';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '小さな島に住む。', 'Sống trên một hòn đảo nhỏ.', '小さな_____に住む。', '島', 'generated' from jp_vocab where id = '4f19f286-ccb4-48bd-a545-679b0f0d823d';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '港に船が着く。', 'Tàu cập cảng.', '_____に船が着く。', '港', 'generated' from jp_vocab where id = '41a63d57-b5e6-4b81-97a0-e21b56e4cf5e';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '近所に住んでいる。', 'Sống ở gần đây.', '_____に住んでいる。', '近所', 'generated' from jp_vocab where id = '0470acc3-e0a6-4ccc-8ee8-0d844ce2bc3f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '屋上から景色を見る。', 'Ngắm cảnh từ tầng thượng.', '_____から景色を見る。', '屋上', 'generated' from jp_vocab where id = 'e219ea6f-3bf4-4e19-ba1f-15df7c0c3c60';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '海外で働く。', 'Làm việc ở nước ngoài.', '_____で働く。', '海外', 'generated' from jp_vocab where id = '8c2e848c-477d-455b-92d1-6adbdfe03b9b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '週末は山登りをする。', 'Cuối tuần đi leo núi.', '週末は_____をする。', '山登り', 'generated' from jp_vocab where id = 'b872df5d-e91e-4dce-a3e7-e4560156c3c8';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '日本の歴史を学ぶ。', 'Học lịch sử Nhật Bản.', '日本の_____を学ぶ。', '歴史', 'generated' from jp_vocab where id = '2a30d795-3b7d-4b82-a92e-e7536093315a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'いい機会だ。', 'Đây là cơ hội tốt.', 'いい_____だ。', '機会', 'generated' from jp_vocab where id = '6819d2d6-63d5-42b0-bd08-40529b1db4b5';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '入る許可をもらう。', 'Xin được cho phép vào.', '入る_____をもらう。', '許可', 'generated' from jp_vocab where id = 'bf41ca0c-2ab2-4581-bd9b-d9b881db1185';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"変わる" có nghĩa là gì?', 'lịch sử', 'đổi, thay đổi', 'đảo', 'cảng', 'đổi, thay đổi', 'generated' from jp_vocab where id = 'f178906d-b240-478c-81cb-8fe7f3d45321';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đổi, thay đổi"?', '近所', '変わる', '屋上', 'クリックする', '変わる', 'generated' from jp_vocab where id = 'f178906d-b240-478c-81cb-8fe7f3d45321';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"変わる" đọc là gì?', 'にゅうりょくする', 'かわる', 'きかい', 'さく', 'かわる', 'generated' from jp_vocab where id = 'f178906d-b240-478c-81cb-8fe7f3d45321';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 天気が_____。', NULL, NULL, NULL, NULL, '変わる', 'generated' from jp_vocab where id = 'f178906d-b240-478c-81cb-8fe7f3d45321';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"困る" có nghĩa là gì?', 'đánh dấu (tròn)', 'khó khăn', 'sự cho phép', 'đảo', 'khó khăn', 'generated' from jp_vocab where id = '6671e488-3083-49eb-8f74-a1513948f873';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "khó khăn"?', '向こう', '付ける', '困る', '山登り', '困る', 'generated' from jp_vocab where id = '6671e488-3083-49eb-8f74-a1513948f873';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"困る" đọc là gì?', 'こまる', 'つける', 'おくじょう', 'みなと', 'こまる', 'generated' from jp_vocab where id = '6671e488-3083-49eb-8f74-a1513948f873';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: お金がなくて_____。', NULL, NULL, NULL, NULL, '困る', 'generated' from jp_vocab where id = '6671e488-3083-49eb-8f74-a1513948f873';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"付ける" có nghĩa là gì?', 'khó khăn', 'khỏi (bệnh)', 'đánh dấu (tròn)', 'cơ hội', 'đánh dấu (tròn)', 'generated' from jp_vocab where id = '92d4cc91-a559-443a-9841-92b8ba7cfabb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đánh dấu (tròn)"?', '付ける', '困る', '機会', '向こう', '付ける', 'generated' from jp_vocab where id = '92d4cc91-a559-443a-9841-92b8ba7cfabb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"付ける" đọc là gì?', 'クリックする', 'きょか', 'なおる', 'つける', 'つける', 'generated' from jp_vocab where id = '92d4cc91-a559-443a-9841-92b8ba7cfabb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 正しい答えに丸を_____。', NULL, NULL, NULL, NULL, '付ける', 'generated' from jp_vocab where id = '92d4cc91-a559-443a-9841-92b8ba7cfabb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"治る" có nghĩa là gì?', 'nhập vào', 'tầng thượng', 'chơi thân với (cô ấy)', 'khỏi (bệnh)', 'khỏi (bệnh)', 'generated' from jp_vocab where id = '63b7b3f7-51a1-4294-828d-4b3e2912000d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "khỏi (bệnh)"?', '歴史', '治る', 'クリックする', '咲く', '治る', 'generated' from jp_vocab where id = '63b7b3f7-51a1-4294-828d-4b3e2912000d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"治る" đọc là gì?', 'なおる', 'きかい', 'おくじょう', 'しま', 'なおる', 'generated' from jp_vocab where id = '63b7b3f7-51a1-4294-828d-4b3e2912000d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 病気が_____た。', NULL, NULL, NULL, NULL, '治っ', 'generated' from jp_vocab where id = '63b7b3f7-51a1-4294-828d-4b3e2912000d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"直る" có nghĩa là gì?', 'sự cho phép', '(hỏng hóc) được sửa xong', 'đảo', 'nhập vào', '(hỏng hóc) được sửa xong', 'generated' from jp_vocab where id = 'd6affa57-c627-4e18-a6a0-7ba36be5994f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "(hỏng hóc) được sửa xong"?', '仲良くする', '直る', '許可', '付ける', '直る', 'generated' from jp_vocab where id = 'd6affa57-c627-4e18-a6a0-7ba36be5994f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"直る" đọc là gì?', 'きかい', 'なおる', 'きょか', 'きんじょ', 'なおる', 'generated' from jp_vocab where id = 'd6affa57-c627-4e18-a6a0-7ba36be5994f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 故障が_____た。', NULL, NULL, NULL, NULL, '直っ', 'generated' from jp_vocab where id = 'd6affa57-c627-4e18-a6a0-7ba36be5994f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"入力する" có nghĩa là gì?', 'hàng xóm, gần quanh đây', 'nước ngoài', 'nhập vào', 'leo núi', 'nhập vào', 'generated' from jp_vocab where id = '9eb69b44-07fb-496a-8d94-90bb45ce4ba3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhập vào"?', '困る', '変わる', '直る', '入力する', '入力する', 'generated' from jp_vocab where id = '9eb69b44-07fb-496a-8d94-90bb45ce4ba3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"入力する" đọc là gì?', 'こまる', 'きかい', 'さく', 'にゅうりょくする', 'にゅうりょくする', 'generated' from jp_vocab where id = '9eb69b44-07fb-496a-8d94-90bb45ce4ba3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: パスワードを_____。', NULL, NULL, NULL, NULL, '入力する', 'generated' from jp_vocab where id = '9eb69b44-07fb-496a-8d94-90bb45ce4ba3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"仲良くする" có nghĩa là gì?', 'sự cho phép', 'leo núi', 'đằng ấy, phía đối diện', 'chơi thân với (cô ấy)', 'chơi thân với (cô ấy)', 'generated' from jp_vocab where id = 'e1229b82-e78b-45a6-be2a-f2cddbd60bb9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chơi thân với (cô ấy)"?', '困る', '付ける', '仲良くする', '変わる', '仲良くする', 'generated' from jp_vocab where id = 'e1229b82-e78b-45a6-be2a-f2cddbd60bb9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"仲良くする" đọc là gì?', 'なかよくする', 'かいがい', 'きんじょ', 'やまのぼり', 'なかよくする', 'generated' from jp_vocab where id = 'e1229b82-e78b-45a6-be2a-f2cddbd60bb9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 彼女と_____。', NULL, NULL, NULL, NULL, '仲良くする', 'generated' from jp_vocab where id = 'e1229b82-e78b-45a6-be2a-f2cddbd60bb9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"クリックする" có nghĩa là gì?', 'đổi, thay đổi', 'đằng ấy, phía đối diện', 'click chuột', 'cơ hội', 'click chuột', 'generated' from jp_vocab where id = '46911948-0e28-4299-824b-7f924c88ebba';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "click chuột"?', '入力する', 'クリックする', '近所', '機会', 'クリックする', 'generated' from jp_vocab where id = '46911948-0e28-4299-824b-7f924c88ebba';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"クリックする" đọc là gì?', 'むこう', 'かわる', 'つける', 'クリックする', 'クリックする', 'generated' from jp_vocab where id = '46911948-0e28-4299-824b-7f924c88ebba';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: ここを_____。', NULL, NULL, NULL, NULL, 'クリックする', 'generated' from jp_vocab where id = '46911948-0e28-4299-824b-7f924c88ebba';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"咲く" có nghĩa là gì?', 'nhập vào', 'leo núi', 'sự cho phép', '(hoa) nở', '(hoa) nở', 'generated' from jp_vocab where id = 'dc9bbbad-3ac7-402c-b902-cd9391632319';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "(hoa) nở"?', '屋上', '直る', '咲く', '付ける', '咲く', 'generated' from jp_vocab where id = 'dc9bbbad-3ac7-402c-b902-cd9391632319';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"咲く" đọc là gì?', 'クリックする', 'さく', 'なおる', 'かわる', 'さく', 'generated' from jp_vocab where id = 'dc9bbbad-3ac7-402c-b902-cd9391632319';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 桜の花が_____。', NULL, NULL, NULL, NULL, '咲く', 'generated' from jp_vocab where id = 'dc9bbbad-3ac7-402c-b902-cd9391632319';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"向こう" có nghĩa là gì?', 'đánh dấu (tròn)', 'đằng ấy, phía đối diện', 'leo núi', 'sự cho phép', 'đằng ấy, phía đối diện', 'generated' from jp_vocab where id = '41b71b63-1a29-401b-8635-a173d5787b08';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đằng ấy, phía đối diện"?', '仲良くする', '向こう', '近所', '許可', '向こう', 'generated' from jp_vocab where id = '41b71b63-1a29-401b-8635-a173d5787b08';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"向こう" đọc là gì?', 'さく', 'むこう', 'クリックする', 'みなと', 'むこう', 'generated' from jp_vocab where id = '41b71b63-1a29-401b-8635-a173d5787b08';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に山が見える。', NULL, NULL, NULL, NULL, '向こう', 'generated' from jp_vocab where id = '41b71b63-1a29-401b-8635-a173d5787b08';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"島" có nghĩa là gì?', 'đảo', '(hỏng hóc) được sửa xong', 'đánh dấu (tròn)', 'hàng xóm, gần quanh đây', 'đảo', 'generated' from jp_vocab where id = '4f19f286-ccb4-48bd-a545-679b0f0d823d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đảo"?', '海外', '島', '歴史', '困る', '島', 'generated' from jp_vocab where id = '4f19f286-ccb4-48bd-a545-679b0f0d823d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"島" đọc là gì?', 'しま', 'にゅうりょくする', 'なおる', 'なかよくする', 'しま', 'generated' from jp_vocab where id = '4f19f286-ccb4-48bd-a545-679b0f0d823d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 小さな_____に住む。', NULL, NULL, NULL, NULL, '島', 'generated' from jp_vocab where id = '4f19f286-ccb4-48bd-a545-679b0f0d823d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"港" có nghĩa là gì?', 'khó khăn', 'cảng', 'đánh dấu (tròn)', 'leo núi', 'cảng', 'generated' from jp_vocab where id = '41a63d57-b5e6-4b81-97a0-e21b56e4cf5e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cảng"?', '治る', '歴史', '直る', '港', '港', 'generated' from jp_vocab where id = '41a63d57-b5e6-4b81-97a0-e21b56e4cf5e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"港" đọc là gì?', 'きょか', 'かわる', 'みなと', 'しま', 'みなと', 'generated' from jp_vocab where id = '41a63d57-b5e6-4b81-97a0-e21b56e4cf5e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に船が着く。', NULL, NULL, NULL, NULL, '港', 'generated' from jp_vocab where id = '41a63d57-b5e6-4b81-97a0-e21b56e4cf5e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"近所" có nghĩa là gì?', 'sự cho phép', 'tầng thượng', 'đánh dấu (tròn)', 'hàng xóm, gần quanh đây', 'hàng xóm, gần quanh đây', 'generated' from jp_vocab where id = '0470acc3-e0a6-4ccc-8ee8-0d844ce2bc3f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "hàng xóm, gần quanh đây"?', '近所', '港', '機会', '付ける', '近所', 'generated' from jp_vocab where id = '0470acc3-e0a6-4ccc-8ee8-0d844ce2bc3f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"近所" đọc là gì?', 'きんじょ', 'つける', 'クリックする', 'さく', 'きんじょ', 'generated' from jp_vocab where id = '0470acc3-e0a6-4ccc-8ee8-0d844ce2bc3f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に住んでいる。', NULL, NULL, NULL, NULL, '近所', 'generated' from jp_vocab where id = '0470acc3-e0a6-4ccc-8ee8-0d844ce2bc3f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"屋上" có nghĩa là gì?', 'tầng thượng', 'khó khăn', 'đổi, thay đổi', 'cảng', 'tầng thượng', 'generated' from jp_vocab where id = 'e219ea6f-3bf4-4e19-ba1f-15df7c0c3c60';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tầng thượng"?', '治る', '島', '入力する', '屋上', '屋上', 'generated' from jp_vocab where id = 'e219ea6f-3bf4-4e19-ba1f-15df7c0c3c60';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"屋上" đọc là gì?', 'きかい', 'おくじょう', 'やまのぼり', 'なかよくする', 'おくじょう', 'generated' from jp_vocab where id = 'e219ea6f-3bf4-4e19-ba1f-15df7c0c3c60';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____から景色を見る。', NULL, NULL, NULL, NULL, '屋上', 'generated' from jp_vocab where id = 'e219ea6f-3bf4-4e19-ba1f-15df7c0c3c60';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"海外" có nghĩa là gì?', 'đảo', 'sự cho phép', 'lịch sử', 'nước ngoài', 'nước ngoài', 'generated' from jp_vocab where id = '8c2e848c-477d-455b-92d1-6adbdfe03b9b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nước ngoài"?', '許可', '向こう', '海外', '屋上', '海外', 'generated' from jp_vocab where id = '8c2e848c-477d-455b-92d1-6adbdfe03b9b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"海外" đọc là gì?', 'かいがい', 'しま', 'おくじょう', 'にゅうりょくする', 'かいがい', 'generated' from jp_vocab where id = '8c2e848c-477d-455b-92d1-6adbdfe03b9b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で働く。', NULL, NULL, NULL, NULL, '海外', 'generated' from jp_vocab where id = '8c2e848c-477d-455b-92d1-6adbdfe03b9b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"山登り" có nghĩa là gì?', 'cảng', 'đánh dấu (tròn)', 'leo núi', '(hoa) nở', 'leo núi', 'generated' from jp_vocab where id = 'b872df5d-e91e-4dce-a3e7-e4560156c3c8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "leo núi"?', '困る', '向こう', '山登り', 'クリックする', '山登り', 'generated' from jp_vocab where id = 'b872df5d-e91e-4dce-a3e7-e4560156c3c8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"山登り" đọc là gì?', 'おくじょう', 'なおる', 'クリックする', 'やまのぼり', 'やまのぼり', 'generated' from jp_vocab where id = 'b872df5d-e91e-4dce-a3e7-e4560156c3c8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 週末は_____をする。', NULL, NULL, NULL, NULL, '山登り', 'generated' from jp_vocab where id = 'b872df5d-e91e-4dce-a3e7-e4560156c3c8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"歴史" có nghĩa là gì?', 'lịch sử', 'chơi thân với (cô ấy)', 'tầng thượng', 'đảo', 'lịch sử', 'generated' from jp_vocab where id = '2a30d795-3b7d-4b82-a92e-e7536093315a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "lịch sử"?', '歴史', '困る', '向こう', '屋上', '歴史', 'generated' from jp_vocab where id = '2a30d795-3b7d-4b82-a92e-e7536093315a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"歴史" đọc là gì?', 'きんじょ', 'れきし', 'むこう', 'みなと', 'れきし', 'generated' from jp_vocab where id = '2a30d795-3b7d-4b82-a92e-e7536093315a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 日本の_____を学ぶ。', NULL, NULL, NULL, NULL, '歴史', 'generated' from jp_vocab where id = '2a30d795-3b7d-4b82-a92e-e7536093315a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"機会" có nghĩa là gì?', 'cơ hội', '(hoa) nở', 'đằng ấy, phía đối diện', 'hàng xóm, gần quanh đây', 'cơ hội', 'generated' from jp_vocab where id = '6819d2d6-63d5-42b0-bd08-40529b1db4b5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cơ hội"?', '港', '困る', '変わる', '機会', '機会', 'generated' from jp_vocab where id = '6819d2d6-63d5-42b0-bd08-40529b1db4b5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"機会" đọc là gì?', 'かわる', 'れきし', 'やまのぼり', 'きかい', 'きかい', 'generated' from jp_vocab where id = '6819d2d6-63d5-42b0-bd08-40529b1db4b5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: いい_____だ。', NULL, NULL, NULL, NULL, '機会', 'generated' from jp_vocab where id = '6819d2d6-63d5-42b0-bd08-40529b1db4b5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"許可" có nghĩa là gì?', 'đánh dấu (tròn)', 'nhập vào', 'khỏi (bệnh)', 'sự cho phép', 'sự cho phép', 'generated' from jp_vocab where id = 'bf41ca0c-2ab2-4581-bd9b-d9b881db1185';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sự cho phép"?', '仲良くする', '許可', '歴史', '向こう', '許可', 'generated' from jp_vocab where id = 'bf41ca0c-2ab2-4581-bd9b-d9b881db1185';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"許可" đọc là gì?', 'やまのぼり', 'なかよくする', 'きょか', 'にゅうりょくする', 'きょか', 'generated' from jp_vocab where id = 'bf41ca0c-2ab2-4581-bd9b-d9b881db1185';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 入る_____をもらう。', NULL, NULL, NULL, NULL, '許可', 'generated' from jp_vocab where id = 'bf41ca0c-2ab2-4581-bd9b-d9b881db1185';
