-- ============================================================
-- jp-go — Từ vựng N4, 課35 (phần 2, 18 từ còn lại).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 25.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('8c638c82-2b32-4a64-8a43-e7077dfc79ec', 'N4', 35, 'word', '丸', 'まる', 'dấu tròn', NULL, '名詞', 25, '丸', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a0cdb105-ed3d-44ca-b9c0-56c4960bb787', 'N4', 35, 'word', 'ふりがな', 'ふりがな', 'chữ Furigana (dùng để phiên âm cách đọc kanji)', NULL, '名詞', 25, 'ふりがな', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e2af71a3-b85c-4ded-bbbe-8cab33b1478f', 'N4', 35, 'word', '設備', 'せつび', 'thiết bị', NULL, '名詞', 25, '設備', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('db704acd-b6a9-4100-9317-725c43646ff4', 'N4', 35, 'word', '紐', 'ひも', 'sợi dây', NULL, '名詞', 25, '紐', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e8fe620d-1bf9-4ad1-a477-447c0d968515', 'N4', 35, 'word', '炊飯器', 'すいはんき', 'nồi cơm điện', NULL, '名詞', 25, '炊飯器', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d67a3526-8421-48d2-9916-ae8ed10b58fe', 'N4', 35, 'word', '葉', 'は', 'lá', NULL, '名詞', 25, '葉', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('2510877a-7441-4530-bb26-648ffac50174', 'N4', 35, 'word', '昔', 'むかし', 'ngày xưa', NULL, '名詞', 25, '昔', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('99236afc-f7c5-41e9-a945-75b0031002c4', 'N4', 35, 'word', 'レバー', 'レバー', 'cần, cần gạt', NULL, '名詞', 25, 'レバー', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('dc512e51-55e6-4f1e-a1fc-bdbfbd407026', 'N4', 35, 'word', 'カーテン', 'カーテン', 'rèm cửa', NULL, '名詞', 25, 'カーテン', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('07bc1884-d7a7-4712-9896-6ca92eef61f6', 'N4', 35, 'word', '夜行バス', 'やこうバス', 'xe buýt đêm', NULL, '名詞', 25, '夜行バス', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('712340fe-f4e2-47c6-a07f-bf60ba9c30fd', 'N4', 35, 'word', '旅行社', 'りょこうしゃ', 'công ty du lịch', NULL, '名詞', 25, '旅行社', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('ada748da-2bed-4435-ad64-d11b7d823384', 'N4', 35, 'word', 'スキー場', 'スキーじょう', 'sân trượt tuyết', NULL, '名詞', 25, 'スキー場', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('f6fbf7ad-6691-43cc-8c00-3a02e8bd5f22', 'N4', 35, 'word', 'ことわざ', 'ことわざ', 'thành ngữ', NULL, '名詞', 25, 'ことわざ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('0f0ef73f-2293-4e1c-9ee6-792950fa900f', 'N4', 35, 'word', '詳しい', 'くわしい', 'cụ thể, chi tiết', NULL, 'い形容詞', 25, '詳しい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('71f2947f-b68d-4df3-b1a3-5bd8164b00d0', 'N4', 35, 'word', '正しい', 'ただしい', 'đúng, chính xác', NULL, 'い形容詞', 25, '正しい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d6e12933-6eb1-4fe7-97a5-3fc0071f5a4b', 'N4', 35, 'word', '必要', 'ひつよう', 'cần thiết', NULL, 'な形容詞', 25, '必要', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('07f6f173-5fc1-4bd5-9920-3a16c671cb8d', 'N4', 35, 'word', 'おかゆ', 'おかゆ', 'cháo', NULL, '名詞', 25, 'おかゆ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('46cd3692-e0b3-471a-a2bb-089bf34aca57', 'N4', 35, 'word', '関係', 'かんけい', 'quan hệ', NULL, '名詞', 25, '関係', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '丸をつける。', 'Đánh dấu tròn.', '_____をつける。', '丸', 'generated' from jp_vocab where id = '8c638c82-2b32-4a64-8a43-e7077dfc79ec';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '漢字にふりがなをつける。', 'Ghi Furigana lên kanji.', '漢字に_____をつける。', 'ふりがな', 'generated' from jp_vocab where id = 'a0cdb105-ed3d-44ca-b9c0-56c4960bb787';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '新しい設備を導入する。', 'Đưa vào sử dụng thiết bị mới.', '新しい_____を導入する。', '設備', 'generated' from jp_vocab where id = 'e2af71a3-b85c-4ded-bbbe-8cab33b1478f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '紐で結ぶ。', 'Buộc bằng sợi dây.', '_____で結ぶ。', '紐', 'generated' from jp_vocab where id = 'db704acd-b6a9-4100-9317-725c43646ff4';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '炊飯器でご飯を炊く。', 'Nấu cơm bằng nồi cơm điện.', '_____でご飯を炊く。', '炊飯器', 'generated' from jp_vocab where id = 'e8fe620d-1bf9-4ad1-a477-447c0d968515';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '木の葉が落ちる。', 'Lá cây rụng.', '木の_____が落ちる。', '葉', 'generated' from jp_vocab where id = 'd67a3526-8421-48d2-9916-ae8ed10b58fe';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '昔の話をする。', 'Kể chuyện ngày xưa.', '_____の話をする。', '昔', 'generated' from jp_vocab where id = '2510877a-7441-4530-bb26-648ffac50174';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'レバーを引く。', 'Kéo cần gạt.', '_____を引く。', 'レバー', 'generated' from jp_vocab where id = '99236afc-f7c5-41e9-a945-75b0031002c4';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'カーテンを閉める。', 'Kéo rèm cửa lại.', '_____を閉める。', 'カーテン', 'generated' from jp_vocab where id = 'dc512e51-55e6-4f1e-a1fc-bdbfbd407026';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '夜行バスで旅行する。', 'Đi du lịch bằng xe buýt đêm.', '_____で旅行する。', '夜行バス', 'generated' from jp_vocab where id = '07bc1884-d7a7-4712-9896-6ca92eef61f6';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '旅行社でチケットを買う。', 'Mua vé ở công ty du lịch.', '_____でチケットを買う。', '旅行社', 'generated' from jp_vocab where id = '712340fe-f4e2-47c6-a07f-bf60ba9c30fd';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'スキー場で滑る。', 'Trượt tuyết ở sân trượt tuyết.', '_____で滑る。', 'スキー場', 'generated' from jp_vocab where id = 'ada748da-2bed-4435-ad64-d11b7d823384';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'このことわざを知っていますか。', 'Bạn có biết thành ngữ này không?', 'この_____を知っていますか。', 'ことわざ', 'generated' from jp_vocab where id = 'f6fbf7ad-6691-43cc-8c00-3a02e8bd5f22';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'もっと詳しく説明する。', 'Giải thích cụ thể hơn.', 'もっと_____説明する。', '詳しく', 'generated' from jp_vocab where id = '0f0ef73f-2293-4e1c-9ee6-792950fa900f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '正しい答えを選ぶ。', 'Chọn câu trả lời đúng.', '_____答えを選ぶ。', '正しい', 'generated' from jp_vocab where id = '71f2947f-b68d-4df3-b1a3-5bd8164b00d0';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お金が必要だ。', 'Cần tiền.', 'お金が_____だ。', '必要', 'generated' from jp_vocab where id = 'd6e12933-6eb1-4fe7-97a5-3fc0071f5a4b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '病気のときはおかゆを食べる。', 'Khi bị bệnh thì ăn cháo.', '病気のときは_____を食べる。', 'おかゆ', 'generated' from jp_vocab where id = '07f6f173-5fc1-4bd5-9920-3a16c671cb8d';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '二人の関係がいい。', 'Quan hệ giữa hai người tốt.', '二人の_____がいい。', '関係', 'generated' from jp_vocab where id = '46cd3692-e0b3-471a-a2bb-089bf34aca57';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"丸" có nghĩa là gì?', 'dấu tròn', 'rèm cửa', 'lá', 'cụ thể, chi tiết', 'dấu tròn', 'generated' from jp_vocab where id = '8c638c82-2b32-4a64-8a43-e7077dfc79ec';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "dấu tròn"?', 'おかゆ', '昔', '丸', '夜行バス', '丸', 'generated' from jp_vocab where id = '8c638c82-2b32-4a64-8a43-e7077dfc79ec';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"丸" đọc là gì?', 'ひつよう', 'は', 'ひも', 'まる', 'まる', 'generated' from jp_vocab where id = '8c638c82-2b32-4a64-8a43-e7077dfc79ec';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____をつける。', NULL, NULL, NULL, NULL, '丸', 'generated' from jp_vocab where id = '8c638c82-2b32-4a64-8a43-e7077dfc79ec';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ふりがな" có nghĩa là gì?', 'sợi dây', 'thành ngữ', 'chữ Furigana (dùng để phiên âm cách đọc kanji)', 'xe buýt đêm', 'chữ Furigana (dùng để phiên âm cách đọc kanji)', 'generated' from jp_vocab where id = 'a0cdb105-ed3d-44ca-b9c0-56c4960bb787';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chữ Furigana (dùng để phiên âm cách đọc kanji)"?', '設備', 'ふりがな', 'レバー', '必要', 'ふりがな', 'generated' from jp_vocab where id = 'a0cdb105-ed3d-44ca-b9c0-56c4960bb787';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ふりがな" đọc là gì?', 'ひも', 'せつび', 'すいはんき', 'ふりがな', 'ふりがな', 'generated' from jp_vocab where id = 'a0cdb105-ed3d-44ca-b9c0-56c4960bb787';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 漢字に_____をつける。', NULL, NULL, NULL, NULL, 'ふりがな', 'generated' from jp_vocab where id = 'a0cdb105-ed3d-44ca-b9c0-56c4960bb787';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"設備" có nghĩa là gì?', 'xe buýt đêm', 'cụ thể, chi tiết', 'lá', 'thiết bị', 'thiết bị', 'generated' from jp_vocab where id = 'e2af71a3-b85c-4ded-bbbe-8cab33b1478f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thiết bị"?', '設備', 'スキー場', '夜行バス', 'おかゆ', '設備', 'generated' from jp_vocab where id = 'e2af71a3-b85c-4ded-bbbe-8cab33b1478f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"設備" đọc là gì?', 'ひつよう', 'せつび', 'すいはんき', 'ひも', 'せつび', 'generated' from jp_vocab where id = 'e2af71a3-b85c-4ded-bbbe-8cab33b1478f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 新しい_____を導入する。', NULL, NULL, NULL, NULL, '設備', 'generated' from jp_vocab where id = 'e2af71a3-b85c-4ded-bbbe-8cab33b1478f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"紐" có nghĩa là gì?', 'chữ Furigana (dùng để phiên âm cách đọc kanji)', 'sân trượt tuyết', 'quan hệ', 'sợi dây', 'sợi dây', 'generated' from jp_vocab where id = 'db704acd-b6a9-4100-9317-725c43646ff4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sợi dây"?', '関係', '設備', '紐', 'おかゆ', '紐', 'generated' from jp_vocab where id = 'db704acd-b6a9-4100-9317-725c43646ff4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"紐" đọc là gì?', 'ひも', 'は', 'レバー', 'むかし', 'ひも', 'generated' from jp_vocab where id = 'db704acd-b6a9-4100-9317-725c43646ff4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で結ぶ。', NULL, NULL, NULL, NULL, '紐', 'generated' from jp_vocab where id = 'db704acd-b6a9-4100-9317-725c43646ff4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"炊飯器" có nghĩa là gì?', 'thành ngữ', 'nồi cơm điện', 'đúng, chính xác', 'cháo', 'nồi cơm điện', 'generated' from jp_vocab where id = 'e8fe620d-1bf9-4ad1-a477-447c0d968515';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nồi cơm điện"?', 'おかゆ', '関係', '丸', '炊飯器', '炊飯器', 'generated' from jp_vocab where id = 'e8fe620d-1bf9-4ad1-a477-447c0d968515';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"炊飯器" đọc là gì?', 'は', 'カーテン', 'すいはんき', 'せつび', 'すいはんき', 'generated' from jp_vocab where id = 'e8fe620d-1bf9-4ad1-a477-447c0d968515';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____でご飯を炊く。', NULL, NULL, NULL, NULL, '炊飯器', 'generated' from jp_vocab where id = 'e8fe620d-1bf9-4ad1-a477-447c0d968515';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"葉" có nghĩa là gì?', 'dấu tròn', 'lá', 'nồi cơm điện', 'công ty du lịch', 'lá', 'generated' from jp_vocab where id = 'd67a3526-8421-48d2-9916-ae8ed10b58fe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "lá"?', '炊飯器', '必要', 'おかゆ', '葉', '葉', 'generated' from jp_vocab where id = 'd67a3526-8421-48d2-9916-ae8ed10b58fe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"葉" đọc là gì?', 'かんけい', 'くわしい', 'は', 'りょこうしゃ', 'は', 'generated' from jp_vocab where id = 'd67a3526-8421-48d2-9916-ae8ed10b58fe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 木の_____が落ちる。', NULL, NULL, NULL, NULL, '葉', 'generated' from jp_vocab where id = 'd67a3526-8421-48d2-9916-ae8ed10b58fe';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"昔" có nghĩa là gì?', 'quan hệ', 'lá', 'ngày xưa', 'cần, cần gạt', 'ngày xưa', 'generated' from jp_vocab where id = '2510877a-7441-4530-bb26-648ffac50174';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "ngày xưa"?', '夜行バス', '昔', 'ことわざ', '必要', '昔', 'generated' from jp_vocab where id = '2510877a-7441-4530-bb26-648ffac50174';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"昔" đọc là gì?', 'せつび', 'おかゆ', 'むかし', 'まる', 'むかし', 'generated' from jp_vocab where id = '2510877a-7441-4530-bb26-648ffac50174';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____の話をする。', NULL, NULL, NULL, NULL, '昔', 'generated' from jp_vocab where id = '2510877a-7441-4530-bb26-648ffac50174';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"レバー" có nghĩa là gì?', 'nồi cơm điện', 'cháo', 'công ty du lịch', 'cần, cần gạt', 'cần, cần gạt', 'generated' from jp_vocab where id = '99236afc-f7c5-41e9-a945-75b0031002c4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cần, cần gạt"?', '夜行バス', 'スキー場', 'レバー', '昔', 'レバー', 'generated' from jp_vocab where id = '99236afc-f7c5-41e9-a945-75b0031002c4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"レバー" đọc là gì?', 'は', 'レバー', 'かんけい', 'やこうバス', 'レバー', 'generated' from jp_vocab where id = '99236afc-f7c5-41e9-a945-75b0031002c4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を引く。', NULL, NULL, NULL, NULL, 'レバー', 'generated' from jp_vocab where id = '99236afc-f7c5-41e9-a945-75b0031002c4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"カーテン" có nghĩa là gì?', 'sợi dây', 'rèm cửa', 'cần thiết', 'cụ thể, chi tiết', 'rèm cửa', 'generated' from jp_vocab where id = 'dc512e51-55e6-4f1e-a1fc-bdbfbd407026';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "rèm cửa"?', 'スキー場', 'カーテン', '関係', '炊飯器', 'カーテン', 'generated' from jp_vocab where id = 'dc512e51-55e6-4f1e-a1fc-bdbfbd407026';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"カーテン" đọc là gì?', 'カーテン', 'は', 'くわしい', 'やこうバス', 'カーテン', 'generated' from jp_vocab where id = 'dc512e51-55e6-4f1e-a1fc-bdbfbd407026';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を閉める。', NULL, NULL, NULL, NULL, 'カーテン', 'generated' from jp_vocab where id = 'dc512e51-55e6-4f1e-a1fc-bdbfbd407026';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"夜行バス" có nghĩa là gì?', 'nồi cơm điện', 'chữ Furigana (dùng để phiên âm cách đọc kanji)', 'xe buýt đêm', 'ngày xưa', 'xe buýt đêm', 'generated' from jp_vocab where id = '07bc1884-d7a7-4712-9896-6ca92eef61f6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "xe buýt đêm"?', '葉', '詳しい', 'レバー', '夜行バス', '夜行バス', 'generated' from jp_vocab where id = '07bc1884-d7a7-4712-9896-6ca92eef61f6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"夜行バス" đọc là gì?', 'やこうバス', 'ただしい', 'かんけい', 'ことわざ', 'やこうバス', 'generated' from jp_vocab where id = '07bc1884-d7a7-4712-9896-6ca92eef61f6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で旅行する。', NULL, NULL, NULL, NULL, '夜行バス', 'generated' from jp_vocab where id = '07bc1884-d7a7-4712-9896-6ca92eef61f6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"旅行社" có nghĩa là gì?', 'cần thiết', 'thành ngữ', 'lá', 'công ty du lịch', 'công ty du lịch', 'generated' from jp_vocab where id = '712340fe-f4e2-47c6-a07f-bf60ba9c30fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "công ty du lịch"?', '紐', 'ふりがな', '葉', '旅行社', '旅行社', 'generated' from jp_vocab where id = '712340fe-f4e2-47c6-a07f-bf60ba9c30fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"旅行社" đọc là gì?', 'りょこうしゃ', 'スキーじょう', 'ただしい', 'おかゆ', 'りょこうしゃ', 'generated' from jp_vocab where id = '712340fe-f4e2-47c6-a07f-bf60ba9c30fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____でチケットを買う。', NULL, NULL, NULL, NULL, '旅行社', 'generated' from jp_vocab where id = '712340fe-f4e2-47c6-a07f-bf60ba9c30fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"スキー場" có nghĩa là gì?', 'sân trượt tuyết', 'cháo', 'thành ngữ', 'lá', 'sân trượt tuyết', 'generated' from jp_vocab where id = 'ada748da-2bed-4435-ad64-d11b7d823384';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sân trượt tuyết"?', '葉', '紐', 'スキー場', 'ことわざ', 'スキー場', 'generated' from jp_vocab where id = 'ada748da-2bed-4435-ad64-d11b7d823384';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"スキー場" đọc là gì?', 'ただしい', 'スキーじょう', 'やこうバス', 'せつび', 'スキーじょう', 'generated' from jp_vocab where id = 'ada748da-2bed-4435-ad64-d11b7d823384';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で滑る。', NULL, NULL, NULL, NULL, 'スキー場', 'generated' from jp_vocab where id = 'ada748da-2bed-4435-ad64-d11b7d823384';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ことわざ" có nghĩa là gì?', 'rèm cửa', 'lá', 'thành ngữ', 'dấu tròn', 'thành ngữ', 'generated' from jp_vocab where id = 'f6fbf7ad-6691-43cc-8c00-3a02e8bd5f22';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thành ngữ"?', '関係', 'ことわざ', 'おかゆ', '夜行バス', 'ことわざ', 'generated' from jp_vocab where id = 'f6fbf7ad-6691-43cc-8c00-3a02e8bd5f22';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ことわざ" đọc là gì?', 'ことわざ', 'やこうバス', 'すいはんき', 'まる', 'ことわざ', 'generated' from jp_vocab where id = 'f6fbf7ad-6691-43cc-8c00-3a02e8bd5f22';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: この_____を知っていますか。', NULL, NULL, NULL, NULL, 'ことわざ', 'generated' from jp_vocab where id = 'f6fbf7ad-6691-43cc-8c00-3a02e8bd5f22';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"詳しい" có nghĩa là gì?', 'cụ thể, chi tiết', 'cần, cần gạt', 'cần thiết', 'thiết bị', 'cụ thể, chi tiết', 'generated' from jp_vocab where id = '0f0ef73f-2293-4e1c-9ee6-792950fa900f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cụ thể, chi tiết"?', '詳しい', '関係', 'レバー', '夜行バス', '詳しい', 'generated' from jp_vocab where id = '0f0ef73f-2293-4e1c-9ee6-792950fa900f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"詳しい" đọc là gì?', 'くわしい', 'ひも', 'やこうバス', 'りょこうしゃ', 'くわしい', 'generated' from jp_vocab where id = '0f0ef73f-2293-4e1c-9ee6-792950fa900f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: もっと_____説明する。', NULL, NULL, NULL, NULL, '詳しく', 'generated' from jp_vocab where id = '0f0ef73f-2293-4e1c-9ee6-792950fa900f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"正しい" có nghĩa là gì?', 'nồi cơm điện', 'đúng, chính xác', 'thành ngữ', 'quan hệ', 'đúng, chính xác', 'generated' from jp_vocab where id = '71f2947f-b68d-4df3-b1a3-5bd8164b00d0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đúng, chính xác"?', '正しい', '夜行バス', '詳しい', 'ふりがな', '正しい', 'generated' from jp_vocab where id = '71f2947f-b68d-4df3-b1a3-5bd8164b00d0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"正しい" đọc là gì?', 'カーテン', 'すいはんき', 'ただしい', 'むかし', 'ただしい', 'generated' from jp_vocab where id = '71f2947f-b68d-4df3-b1a3-5bd8164b00d0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____答えを選ぶ。', NULL, NULL, NULL, NULL, '正しい', 'generated' from jp_vocab where id = '71f2947f-b68d-4df3-b1a3-5bd8164b00d0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"必要" có nghĩa là gì?', 'chữ Furigana (dùng để phiên âm cách đọc kanji)', 'cháo', 'sợi dây', 'cần thiết', 'cần thiết', 'generated' from jp_vocab where id = 'd6e12933-6eb1-4fe7-97a5-3fc0071f5a4b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cần thiết"?', '必要', '詳しい', '炊飯器', '昔', '必要', 'generated' from jp_vocab where id = 'd6e12933-6eb1-4fe7-97a5-3fc0071f5a4b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"必要" đọc là gì?', 'レバー', 'ただしい', 'ひつよう', 'むかし', 'ひつよう', 'generated' from jp_vocab where id = 'd6e12933-6eb1-4fe7-97a5-3fc0071f5a4b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: お金が_____だ。', NULL, NULL, NULL, NULL, '必要', 'generated' from jp_vocab where id = 'd6e12933-6eb1-4fe7-97a5-3fc0071f5a4b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"おかゆ" có nghĩa là gì?', 'ngày xưa', 'lá', 'cháo', 'quan hệ', 'cháo', 'generated' from jp_vocab where id = '07f6f173-5fc1-4bd5-9920-3a16c671cb8d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cháo"?', '旅行社', '丸', 'スキー場', 'おかゆ', 'おかゆ', 'generated' from jp_vocab where id = '07f6f173-5fc1-4bd5-9920-3a16c671cb8d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"おかゆ" đọc là gì?', 'りょこうしゃ', 'ことわざ', 'ひつよう', 'おかゆ', 'おかゆ', 'generated' from jp_vocab where id = '07f6f173-5fc1-4bd5-9920-3a16c671cb8d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 病気のときは_____を食べる。', NULL, NULL, NULL, NULL, 'おかゆ', 'generated' from jp_vocab where id = '07f6f173-5fc1-4bd5-9920-3a16c671cb8d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"関係" có nghĩa là gì?', 'lá', 'cần thiết', 'quan hệ', 'cần, cần gạt', 'quan hệ', 'generated' from jp_vocab where id = '46cd3692-e0b3-471a-a2bb-089bf34aca57';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "quan hệ"?', '詳しい', '関係', '旅行社', '昔', '関係', 'generated' from jp_vocab where id = '46cd3692-e0b3-471a-a2bb-089bf34aca57';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"関係" đọc là gì?', 'かんけい', 'カーテン', 'おかゆ', 'ひも', 'かんけい', 'generated' from jp_vocab where id = '46cd3692-e0b3-471a-a2bb-089bf34aca57';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 二人の_____がいい。', NULL, NULL, NULL, NULL, '関係', 'generated' from jp_vocab where id = '46cd3692-e0b3-471a-a2bb-089bf34aca57';
