-- ============================================================
-- jp-go — Từ vựng N4, 課36 (phần 2, 14 từ còn lại).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 26.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('68069284-3dc9-4abd-9117-81b41f6ed503', 'N4', 36, 'word', 'お客様', 'おきゃくさま', 'quý khách', NULL, '名詞', 26, 'お客様', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('ccf8da3b-8a63-428a-b61d-d0bcba29cc42', 'N4', 36, 'word', '特別', 'とくべつ', 'đặc biệt', NULL, 'な形容詞', 26, '特別', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('ee4ac0a0-9f67-417d-872f-c9f92d1560fa', 'N4', 36, 'word', '水泳', 'すいえい', 'bơi lội', NULL, '名詞', 26, '水泳', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('4ff742e6-6e1e-4bfe-876a-00155b23981f', 'N4', 36, 'word', '珍しい', 'めずらしい', 'hiếm', NULL, 'い形容詞', 26, '珍しい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('f66c607d-dde5-4cd5-8b80-662e1c08274f', 'N4', 36, 'word', '乗り物', 'のりもの', 'phương tiện đi lại', NULL, '名詞', 26, '乗り物', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('99bba841-e61e-4b7e-9a1d-8f5686f4d551', 'N4', 36, 'word', '剣道', 'けんどう', 'kiếm đạo', NULL, '名詞', 26, '剣道', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3d55fb07-9272-42bd-9b6e-de1854aa0be3', 'N4', 36, 'word', 'お弁当', 'おべんとう', 'cơm hộp', NULL, '名詞', 26, 'お弁当', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('767b36c2-2296-4011-a3a7-063247009cd4', 'N4', 36, 'phrase', 'うがいをする', 'うがいをする', 'súc miệng', NULL, '動詞', 26, 'うがいをする', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('64ba3035-00e2-47dd-921a-749350dc7a14', 'N4', 36, 'word', 'ヨーロッパ', 'ヨーロッパ', 'châu Âu', NULL, '名詞', 26, 'ヨーロッパ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('69c16e8e-e7a8-4886-a5dd-6e27c87b643c', 'N4', 36, 'word', '汽車', 'きしゃ', 'tàu hỏa chạy bằng hơi nước', NULL, '名詞', 26, '汽車', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('1cddb25b-eb18-40ed-be29-556db973d280', 'N4', 36, 'word', '汽船', 'きせん', 'tàu thủy chạy bằng hơi nước', NULL, '名詞', 26, '汽船', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a712ff7b-4ade-4081-adab-d511b60617d9', 'N4', 36, 'word', '大勢の人', 'おおぜいのひと', 'nhiều người', NULL, '名詞', 26, '大勢の人', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('aa563ebd-19d7-4f1c-8ac7-e5b853e12410', 'N4', 36, 'word', '運ぶ', 'はこぶ', 'vận chuyển', NULL, '動詞', 26, '運ぶ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('5d146862-8569-4ab9-b1c4-9a985cbb1ab9', 'N4', 36, 'word', '利用', 'りよう', 'sử dụng', NULL, '名詞', 26, '利用', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お客様をお迎えする。', 'Đón tiếp quý khách.', '_____をお迎えする。', 'お客様', 'generated' from jp_vocab where id = '68069284-3dc9-4abd-9117-81b41f6ed503';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '特別なプレゼントをもらった。', 'Đã nhận được món quà đặc biệt.', '_____なプレゼントをもらった。', '特別', 'generated' from jp_vocab where id = 'ccf8da3b-8a63-428a-b61d-d0bcba29cc42';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '水泳を習う。', 'Học bơi lội.', '_____を習う。', '水泳', 'generated' from jp_vocab where id = 'ee4ac0a0-9f67-417d-872f-c9f92d1560fa';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'これは珍しい花だ。', 'Đây là loài hoa hiếm.', 'これは_____花だ。', '珍しい', 'generated' from jp_vocab where id = '4ff742e6-6e1e-4bfe-876a-00155b23981f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '好きな乗り物は電車です。', 'Phương tiện đi lại tôi thích là tàu điện.', '好きな_____は電車です。', '乗り物', 'generated' from jp_vocab where id = 'f66c607d-dde5-4cd5-8b80-662e1c08274f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '剣道を習っている。', 'Đang học kiếm đạo.', '_____を習っている。', '剣道', 'generated' from jp_vocab where id = '99bba841-e61e-4b7e-9a1d-8f5686f4d551';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お弁当を作る。', 'Làm cơm hộp.', '_____を作る。', 'お弁当', 'generated' from jp_vocab where id = '3d55fb07-9272-42bd-9b6e-de1854aa0be3';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '帰ったらうがいをする。', 'Về nhà thì súc miệng.', '帰ったら_____。', 'うがいをする', 'generated' from jp_vocab where id = '767b36c2-2296-4011-a3a7-063247009cd4';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ヨーロッパを旅行する。', 'Đi du lịch châu Âu.', '_____を旅行する。', 'ヨーロッパ', 'generated' from jp_vocab where id = '64ba3035-00e2-47dd-921a-749350dc7a14';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '昔は汽車に乗った。', 'Ngày xưa đã đi tàu hỏa chạy bằng hơi nước.', '昔は_____に乗った。', '汽車', 'generated' from jp_vocab where id = '69c16e8e-e7a8-4886-a5dd-6e27c87b643c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '汽船で海を渡る。', 'Vượt biển bằng tàu thủy chạy bằng hơi nước.', '_____で海を渡る。', '汽船', 'generated' from jp_vocab where id = '1cddb25b-eb18-40ed-be29-556db973d280';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '大勢の人が集まった。', 'Nhiều người đã tụ tập lại.', '_____が集まった。', '大勢の人', 'generated' from jp_vocab where id = 'a712ff7b-4ade-4081-adab-d511b60617d9';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '荷物を運ぶ。', 'Vận chuyển hành lý.', '荷物を_____。', '運ぶ', 'generated' from jp_vocab where id = 'aa563ebd-19d7-4f1c-8ac7-e5b853e12410';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'バスを利用する。', 'Sử dụng xe buýt.', 'バスを_____する。', '利用', 'generated' from jp_vocab where id = '5d146862-8569-4ab9-b1c4-9a985cbb1ab9';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"お客様" có nghĩa là gì?', 'tàu thủy chạy bằng hơi nước', 'sử dụng', 'châu Âu', 'quý khách', 'quý khách', 'generated' from jp_vocab where id = '68069284-3dc9-4abd-9117-81b41f6ed503';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "quý khách"?', '剣道', 'ヨーロッパ', 'お客様', '運ぶ', 'お客様', 'generated' from jp_vocab where id = '68069284-3dc9-4abd-9117-81b41f6ed503';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"お客様" đọc là gì?', 'とくべつ', 'おきゃくさま', 'おおぜいのひと', 'おべんとう', 'おきゃくさま', 'generated' from jp_vocab where id = '68069284-3dc9-4abd-9117-81b41f6ed503';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____をお迎えする。', NULL, NULL, NULL, NULL, 'お客様', 'generated' from jp_vocab where id = '68069284-3dc9-4abd-9117-81b41f6ed503';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"特別" có nghĩa là gì?', 'châu Âu', 'nhiều người', 'súc miệng', 'đặc biệt', 'đặc biệt', 'generated' from jp_vocab where id = 'ccf8da3b-8a63-428a-b61d-d0bcba29cc42';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đặc biệt"?', '汽車', '運ぶ', 'ヨーロッパ', '特別', '特別', 'generated' from jp_vocab where id = 'ccf8da3b-8a63-428a-b61d-d0bcba29cc42';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"特別" đọc là gì?', 'とくべつ', 'めずらしい', 'おおぜいのひと', 'りよう', 'とくべつ', 'generated' from jp_vocab where id = 'ccf8da3b-8a63-428a-b61d-d0bcba29cc42';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____なプレゼントをもらった。', NULL, NULL, NULL, NULL, '特別', 'generated' from jp_vocab where id = 'ccf8da3b-8a63-428a-b61d-d0bcba29cc42';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"水泳" có nghĩa là gì?', 'vận chuyển', 'bơi lội', 'cơm hộp', 'châu Âu', 'bơi lội', 'generated' from jp_vocab where id = 'ee4ac0a0-9f67-417d-872f-c9f92d1560fa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "bơi lội"?', '運ぶ', '汽船', '汽車', '水泳', '水泳', 'generated' from jp_vocab where id = 'ee4ac0a0-9f67-417d-872f-c9f92d1560fa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"水泳" đọc là gì?', 'とくべつ', 'りよう', 'のりもの', 'すいえい', 'すいえい', 'generated' from jp_vocab where id = 'ee4ac0a0-9f67-417d-872f-c9f92d1560fa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を習う。', NULL, NULL, NULL, NULL, '水泳', 'generated' from jp_vocab where id = 'ee4ac0a0-9f67-417d-872f-c9f92d1560fa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"珍しい" có nghĩa là gì?', 'sử dụng', 'đặc biệt', 'tàu thủy chạy bằng hơi nước', 'hiếm', 'hiếm', 'generated' from jp_vocab where id = '4ff742e6-6e1e-4bfe-876a-00155b23981f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "hiếm"?', 'お弁当', '利用', '珍しい', 'お客様', '珍しい', 'generated' from jp_vocab where id = '4ff742e6-6e1e-4bfe-876a-00155b23981f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"珍しい" đọc là gì?', 'おべんとう', 'めずらしい', 'とくべつ', 'のりもの', 'めずらしい', 'generated' from jp_vocab where id = '4ff742e6-6e1e-4bfe-876a-00155b23981f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: これは_____花だ。', NULL, NULL, NULL, NULL, '珍しい', 'generated' from jp_vocab where id = '4ff742e6-6e1e-4bfe-876a-00155b23981f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"乗り物" có nghĩa là gì?', 'vận chuyển', 'phương tiện đi lại', 'sử dụng', 'bơi lội', 'phương tiện đi lại', 'generated' from jp_vocab where id = 'f66c607d-dde5-4cd5-8b80-662e1c08274f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phương tiện đi lại"?', 'お弁当', '珍しい', '特別', '乗り物', '乗り物', 'generated' from jp_vocab where id = 'f66c607d-dde5-4cd5-8b80-662e1c08274f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"乗り物" đọc là gì?', 'きせん', 'おおぜいのひと', 'のりもの', 'すいえい', 'のりもの', 'generated' from jp_vocab where id = 'f66c607d-dde5-4cd5-8b80-662e1c08274f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 好きな_____は電車です。', NULL, NULL, NULL, NULL, '乗り物', 'generated' from jp_vocab where id = 'f66c607d-dde5-4cd5-8b80-662e1c08274f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"剣道" có nghĩa là gì?', 'quý khách', 'phương tiện đi lại', 'kiếm đạo', 'châu Âu', 'kiếm đạo', 'generated' from jp_vocab where id = '99bba841-e61e-4b7e-9a1d-8f5686f4d551';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "kiếm đạo"?', '剣道', 'ヨーロッパ', '乗り物', '大勢の人', '剣道', 'generated' from jp_vocab where id = '99bba841-e61e-4b7e-9a1d-8f5686f4d551';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"剣道" đọc là gì?', 'けんどう', 'おべんとう', 'おきゃくさま', 'のりもの', 'けんどう', 'generated' from jp_vocab where id = '99bba841-e61e-4b7e-9a1d-8f5686f4d551';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を習っている。', NULL, NULL, NULL, NULL, '剣道', 'generated' from jp_vocab where id = '99bba841-e61e-4b7e-9a1d-8f5686f4d551';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"お弁当" có nghĩa là gì?', 'súc miệng', 'cơm hộp', 'quý khách', 'kiếm đạo', 'cơm hộp', 'generated' from jp_vocab where id = '3d55fb07-9272-42bd-9b6e-de1854aa0be3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cơm hộp"?', 'ヨーロッパ', '運ぶ', 'お客様', 'お弁当', 'お弁当', 'generated' from jp_vocab where id = '3d55fb07-9272-42bd-9b6e-de1854aa0be3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"お弁当" đọc là gì?', 'けんどう', 'すいえい', 'おべんとう', 'きしゃ', 'おべんとう', 'generated' from jp_vocab where id = '3d55fb07-9272-42bd-9b6e-de1854aa0be3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を作る。', NULL, NULL, NULL, NULL, 'お弁当', 'generated' from jp_vocab where id = '3d55fb07-9272-42bd-9b6e-de1854aa0be3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"うがいをする" có nghĩa là gì?', 'súc miệng', 'cơm hộp', 'vận chuyển', 'tàu thủy chạy bằng hơi nước', 'súc miệng', 'generated' from jp_vocab where id = '767b36c2-2296-4011-a3a7-063247009cd4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "súc miệng"?', 'お客様', 'ヨーロッパ', 'うがいをする', '特別', 'うがいをする', 'generated' from jp_vocab where id = '767b36c2-2296-4011-a3a7-063247009cd4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"うがいをする" đọc là gì?', 'おおぜいのひと', 'うがいをする', 'とくべつ', 'めずらしい', 'うがいをする', 'generated' from jp_vocab where id = '767b36c2-2296-4011-a3a7-063247009cd4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 帰ったら_____。', NULL, NULL, NULL, NULL, 'うがいをする', 'generated' from jp_vocab where id = '767b36c2-2296-4011-a3a7-063247009cd4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ヨーロッパ" có nghĩa là gì?', 'kiếm đạo', 'châu Âu', 'hiếm', 'phương tiện đi lại', 'châu Âu', 'generated' from jp_vocab where id = '64ba3035-00e2-47dd-921a-749350dc7a14';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "châu Âu"?', '剣道', '水泳', 'ヨーロッパ', '特別', 'ヨーロッパ', 'generated' from jp_vocab where id = '64ba3035-00e2-47dd-921a-749350dc7a14';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ヨーロッパ" đọc là gì?', 'おおぜいのひと', 'のりもの', 'ヨーロッパ', 'りよう', 'ヨーロッパ', 'generated' from jp_vocab where id = '64ba3035-00e2-47dd-921a-749350dc7a14';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を旅行する。', NULL, NULL, NULL, NULL, 'ヨーロッパ', 'generated' from jp_vocab where id = '64ba3035-00e2-47dd-921a-749350dc7a14';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"汽車" có nghĩa là gì?', 'châu Âu', 'phương tiện đi lại', 'sử dụng', 'tàu hỏa chạy bằng hơi nước', 'tàu hỏa chạy bằng hơi nước', 'generated' from jp_vocab where id = '69c16e8e-e7a8-4886-a5dd-6e27c87b643c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tàu hỏa chạy bằng hơi nước"?', '乗り物', '汽船', 'うがいをする', '汽車', '汽車', 'generated' from jp_vocab where id = '69c16e8e-e7a8-4886-a5dd-6e27c87b643c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"汽車" đọc là gì?', 'けんどう', 'のりもの', 'おべんとう', 'きしゃ', 'きしゃ', 'generated' from jp_vocab where id = '69c16e8e-e7a8-4886-a5dd-6e27c87b643c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 昔は_____に乗った。', NULL, NULL, NULL, NULL, '汽車', 'generated' from jp_vocab where id = '69c16e8e-e7a8-4886-a5dd-6e27c87b643c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"汽船" có nghĩa là gì?', 'vận chuyển', 'kiếm đạo', 'tàu thủy chạy bằng hơi nước', 'sử dụng', 'tàu thủy chạy bằng hơi nước', 'generated' from jp_vocab where id = '1cddb25b-eb18-40ed-be29-556db973d280';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tàu thủy chạy bằng hơi nước"?', '特別', '汽船', '利用', 'ヨーロッパ', '汽船', 'generated' from jp_vocab where id = '1cddb25b-eb18-40ed-be29-556db973d280';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"汽船" đọc là gì?', 'のりもの', 'うがいをする', 'はこぶ', 'きせん', 'きせん', 'generated' from jp_vocab where id = '1cddb25b-eb18-40ed-be29-556db973d280';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で海を渡る。', NULL, NULL, NULL, NULL, '汽船', 'generated' from jp_vocab where id = '1cddb25b-eb18-40ed-be29-556db973d280';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"大勢の人" có nghĩa là gì?', 'cơm hộp', 'nhiều người', 'sử dụng', 'vận chuyển', 'nhiều người', 'generated' from jp_vocab where id = 'a712ff7b-4ade-4081-adab-d511b60617d9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhiều người"?', '汽船', 'お客様', '大勢の人', '剣道', '大勢の人', 'generated' from jp_vocab where id = 'a712ff7b-4ade-4081-adab-d511b60617d9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"大勢の人" đọc là gì?', 'おおぜいのひと', 'ヨーロッパ', 'めずらしい', 'のりもの', 'おおぜいのひと', 'generated' from jp_vocab where id = 'a712ff7b-4ade-4081-adab-d511b60617d9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が集まった。', NULL, NULL, NULL, NULL, '大勢の人', 'generated' from jp_vocab where id = 'a712ff7b-4ade-4081-adab-d511b60617d9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"運ぶ" có nghĩa là gì?', 'vận chuyển', 'tàu thủy chạy bằng hơi nước', 'kiếm đạo', 'châu Âu', 'vận chuyển', 'generated' from jp_vocab where id = 'aa563ebd-19d7-4f1c-8ac7-e5b853e12410';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vận chuyển"?', '水泳', '運ぶ', '剣道', '汽船', '運ぶ', 'generated' from jp_vocab where id = 'aa563ebd-19d7-4f1c-8ac7-e5b853e12410';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"運ぶ" đọc là gì?', 'めずらしい', 'のりもの', 'はこぶ', 'すいえい', 'はこぶ', 'generated' from jp_vocab where id = 'aa563ebd-19d7-4f1c-8ac7-e5b853e12410';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 荷物を_____。', NULL, NULL, NULL, NULL, '運ぶ', 'generated' from jp_vocab where id = 'aa563ebd-19d7-4f1c-8ac7-e5b853e12410';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"利用" có nghĩa là gì?', 'quý khách', 'hiếm', 'sử dụng', 'đặc biệt', 'sử dụng', 'generated' from jp_vocab where id = '5d146862-8569-4ab9-b1c4-9a985cbb1ab9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sử dụng"?', '利用', '大勢の人', 'ヨーロッパ', 'うがいをする', '利用', 'generated' from jp_vocab where id = '5d146862-8569-4ab9-b1c4-9a985cbb1ab9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"利用" đọc là gì?', 'ヨーロッパ', 'とくべつ', 'りよう', 'おきゃくさま', 'りよう', 'generated' from jp_vocab where id = '5d146862-8569-4ab9-b1c4-9a985cbb1ab9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: バスを_____する。', NULL, NULL, NULL, NULL, '利用', 'generated' from jp_vocab where id = '5d146862-8569-4ab9-b1c4-9a985cbb1ab9';
