-- ============================================================
-- jp-go — Từ vựng N4, 課37 (phần 2, 25 từ còn lại).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 26 (10 từ cuối) + trang in 27 (15 từ đầu).
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e9829df6-63e0-41e5-80b4-87f81f136774', 'N4', 37, 'word', '原料', 'げんりょう', 'nguyên liệu thô', NULL, '名詞', 26, '原料', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a3066a19-af9e-44dd-80ff-44471274a29e', 'N4', 37, 'word', '泥棒', 'どろぼう', 'kẻ trộm', NULL, '名詞', 26, '泥棒', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b98d9716-996e-4986-9ac0-7a82aa96db57', 'N4', 37, 'word', '警官', 'けいかん', 'cảnh sát', NULL, '名詞', 26, '警官', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e3fd3f82-9af9-4ea6-a3c6-d63f469ea96c', 'N4', 37, 'word', '世界中', 'せかいじゅう', 'trên toàn thế giới', NULL, '名詞', 26, '世界中', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('55ccf029-31bf-4ab6-830e-c7817a8bb479', 'N4', 37, 'word', '誰か', 'だれか', 'ai đó', NULL, '名詞', 26, '誰か', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('59dd2af4-a3c1-4bc6-bea7-881147e661a4', 'N4', 37, 'word', 'インスタントラーメン', 'インスタントラーメン', 'mỳ ăn liền, mỳ gói', NULL, '名詞', 26, 'インスタントラーメン', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e916152f-cf81-42a1-b8a6-2371e4a07c6a', 'N4', 37, 'word', 'デート', 'デート', 'hẹn hò', NULL, '名詞', 26, 'デート', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('16aa7be0-40fd-4c22-9f4d-1aeb16c403d9', 'N4', 37, 'word', '皆様', 'みなさま', 'quý vị', NULL, '名詞', 26, '皆様', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('707768ba-5e3d-4612-a768-ddf2e5cb3626', 'N4', 37, 'word', '金色', 'きんいろ', 'màu vàng kim', NULL, '名詞', 26, '金色', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('5a373bea-a459-4ed9-a050-ddcddb29e632', 'N4', 37, 'word', '本物', 'ほんもの', 'đồ thật', NULL, '名詞', 26, '本物', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('418b5c1b-c64f-42a7-81fc-a46cc8155a21', 'N4', 37, 'word', '豪華', 'ごうか', 'sang trọng, hoành tráng', NULL, 'な形容詞', 27, '豪華', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d1c7c196-faea-4e3f-aec7-023c5f6af704', 'N4', 37, 'word', '彫刻', 'ちょうこく', 'điêu khắc', NULL, '名詞', 27, '彫刻', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('839bbc02-63cd-4ffc-ac59-7a6207323180', 'N4', 37, 'word', '仲間', 'なかま', 'đồng nghiệp', NULL, '名詞', 27, '仲間', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e86411cf-0270-4e92-a744-53d9f93f05cd', 'N4', 37, 'word', '言い伝え', 'いいつたえ', 'truyền miệng', NULL, '名詞', 27, '言い伝え', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('932be22d-ecf1-440e-9666-5d043bbd4326', 'N4', 37, 'phrase', '良かったですね', 'よかったですね', 'Hay quá nhỉ!/Tốt quá rồi!', NULL, 'い形容詞', 27, '良かったですね', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('90c4772a-0cb7-4f49-970f-1cb431611645', 'N4', 37, 'word', 'グラハム・ベル', 'グラハムベル', 'Nhà khoa học Graham Bell', NULL, '名詞', 27, 'グラハム・ベル', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('6ebf6eb2-ebad-47ce-9d89-8bcc13403c05', 'N4', 37, 'word', 'ライト兄弟', 'ライトきょうだい', 'Anh em nhà Wright', NULL, '名詞', 27, 'ライト兄弟', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e3372be7-51b1-46d8-a90b-b1a0f45924e7', 'N4', 37, 'word', 'ゴッホ', 'ゴッホ', 'họa sĩ Vincent Van Gogh', NULL, '名詞', 27, 'ゴッホ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('51aec1a3-47ce-406c-a9ca-c9608c87ab74', 'N4', 37, 'word', 'ピカソ', 'ピカソ', 'Họa sĩ - nhà điêu khắc Picasso', NULL, '名詞', 27, 'ピカソ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('096d89e0-9db7-4ba6-b0d6-8af200222e77', 'N4', 37, 'word', 'コロンブス', 'コロンブス', 'nhà thám hiểm Christopher Columbus', NULL, '名詞', 27, 'コロンブス', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('4ae7c075-f04a-4655-a3a4-cddbcb6137bc', 'N4', 37, 'word', '毛糸', 'けいと', 'sợi len', NULL, '名詞', 27, '毛糸', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('066db3a1-a5b2-4ef8-b751-97964e81ef97', 'N4', 37, 'word', '日光東照宮', 'にっこうとうしょうぐう', 'Đền Nikkou Toshougu', NULL, '名詞', 27, '日光東照宮', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('66e5ed80-7bba-4718-a801-ede138655fcb', 'N4', 37, 'word', '左甚五郎', 'ひだりじんごろう', 'Nhà điêu khắc Jin gorou (người thuận tay trái)', NULL, '名詞', 27, '左甚五郎', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('fcfb2673-114e-499c-9dfc-827c32d0a02b', 'N4', 37, 'word', '一生懸命', 'いっしょうけんめい', 'chăm chỉ, cố gắng hết sức', NULL, '副詞', 27, '一生懸命', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d5822698-df78-4d9a-815d-9a0f3da686aa', 'N4', 37, 'word', '彫る', 'ほる', 'trạm, khắc', NULL, '動詞', 27, '彫る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '石油は多くの製品の原料だ。', 'Dầu mỏ là nguyên liệu thô của nhiều sản phẩm.', '石油は多くの製品の_____だ。', '原料', 'generated' from jp_vocab where id = 'e9829df6-63e0-41e5-80b4-87f81f136774';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '泥棒が入った。', 'Kẻ trộm đã đột nhập.', '_____が入った。', '泥棒', 'generated' from jp_vocab where id = 'a3066a19-af9e-44dd-80ff-44471274a29e';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '警官に道を聞く。', 'Hỏi đường cảnh sát.', '_____に道を聞く。', '警官', 'generated' from jp_vocab where id = 'b98d9716-996e-4986-9ac0-7a82aa96db57';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '世界中を旅行する。', 'Đi du lịch khắp thế giới.', '_____を旅行する。', '世界中', 'generated' from jp_vocab where id = 'e3fd3f82-9af9-4ea6-a3c6-d63f469ea96c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '誰か手伝ってください。', 'Ai đó hãy giúp tôi với.', '_____手伝ってください。', '誰か', 'generated' from jp_vocab where id = '55ccf029-31bf-4ab6-830e-c7817a8bb479';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'インスタントラーメンを食べる。', 'Ăn mì ăn liền.', '_____を食べる。', 'インスタントラーメン', 'generated' from jp_vocab where id = '59dd2af4-a3c1-4bc6-bea7-881147e661a4';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彼女とデートする。', 'Hẹn hò với bạn gái.', '彼女と_____する。', 'デート', 'generated' from jp_vocab where id = 'e916152f-cf81-42a1-b8a6-2371e4a07c6a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '皆様、ありがとうございます。', 'Cảm ơn quý vị.', '_____、ありがとうございます。', '皆様', 'generated' from jp_vocab where id = '16aa7be0-40fd-4c22-9f4d-1aeb16c403d9';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '金色の指輪をもらった。', 'Đã nhận được chiếc nhẫn màu vàng kim.', '_____の指輪をもらった。', '金色', 'generated' from jp_vocab where id = '707768ba-5e3d-4612-a768-ddf2e5cb3626';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'これは本物のダイヤモンドだ。', 'Đây là kim cương đồ thật.', 'これは_____のダイヤモンドだ。', '本物', 'generated' from jp_vocab where id = '5a373bea-a459-4ed9-a050-ddcddb29e632';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '豪華なホテルに泊まる。', 'Ở khách sạn sang trọng.', '_____なホテルに泊まる。', '豪華', 'generated' from jp_vocab where id = '418b5c1b-c64f-42a7-81fc-a46cc8155a21';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '彫刻を見に行く。', 'Đi xem điêu khắc.', '_____を見に行く。', '彫刻', 'generated' from jp_vocab where id = 'd1c7c196-faea-4e3f-aec7-023c5f6af704';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '会社の仲間と話す。', 'Nói chuyện với đồng nghiệp công ty.', '会社の_____と話す。', '仲間', 'generated' from jp_vocab where id = '839bbc02-63cd-4ffc-ac59-7a6207323180';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'この話は言い伝えだ。', 'Câu chuyện này là truyền miệng.', 'この話は_____だ。', '言い伝え', 'generated' from jp_vocab where id = 'e86411cf-0270-4e92-a744-53d9f93f05cd';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '試験に合格して良かったですね。', 'Đỗ kì thi thật là tốt quá nhỉ!', '試験に合格して_____。', '良かったですね', 'generated' from jp_vocab where id = '932be22d-ecf1-440e-9666-5d043bbd4326';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'グラハム・ベルは電話を発明した。', 'Graham Bell đã phát minh ra điện thoại.', '_____は電話を発明した。', 'グラハム・ベル', 'generated' from jp_vocab where id = '90c4772a-0cb7-4f49-970f-1cb431611645';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ライト兄弟は飛行機を発明した。', 'Anh em nhà Wright đã phát minh ra máy bay.', '_____は飛行機を発明した。', 'ライト兄弟', 'generated' from jp_vocab where id = '6ebf6eb2-ebad-47ce-9d89-8bcc13403c05';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ゴッホの絵が好きだ。', 'Tôi thích tranh của Van Gogh.', '_____の絵が好きだ。', 'ゴッホ', 'generated' from jp_vocab where id = 'e3372be7-51b1-46d8-a90b-b1a0f45924e7';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ピカソの作品を見る。', 'Xem tác phẩm của Picasso.', '_____の作品を見る。', 'ピカソ', 'generated' from jp_vocab where id = '51aec1a3-47ce-406c-a9ca-c9608c87ab74';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'コロンブスはアメリカを発見した。', 'Columbus đã phát hiện ra châu Mỹ.', '_____はアメリカを発見した。', 'コロンブス', 'generated' from jp_vocab where id = '096d89e0-9db7-4ba6-b0d6-8af200222e77';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '毛糸でセーターを編む。', 'Đan áo len bằng sợi len.', '_____でセーターを編む。', '毛糸', 'generated' from jp_vocab where id = '4ae7c075-f04a-4655-a3a4-cddbcb6137bc';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '日光東照宮を見学する。', 'Tham quan đền Nikkou Toshougu.', '_____を見学する。', '日光東照宮', 'generated' from jp_vocab where id = '066db3a1-a5b2-4ef8-b751-97964e81ef97';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '左甚五郎は有名な彫刻家だ。', 'Jin gorou là nhà điêu khắc nổi tiếng.', '_____は有名な彫刻家だ。', '左甚五郎', 'generated' from jp_vocab where id = '66e5ed80-7bba-4718-a801-ede138655fcb';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '一生懸命勉強する。', 'Học chăm chỉ, cố gắng hết sức.', '_____勉強する。', '一生懸命', 'generated' from jp_vocab where id = 'fcfb2673-114e-499c-9dfc-827c32d0a02b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '木に絵を彫る。', 'Khắc tranh lên gỗ.', '木に絵を_____。', '彫る', 'generated' from jp_vocab where id = 'd5822698-df78-4d9a-815d-9a0f3da686aa';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"原料" có nghĩa là gì?', 'Đền Nikkou Toshougu', 'nguyên liệu thô', 'màu vàng kim', 'truyền miệng', 'nguyên liệu thô', 'generated' from jp_vocab where id = 'e9829df6-63e0-41e5-80b4-87f81f136774';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nguyên liệu thô"?', 'コロンブス', '皆様', '原料', '左甚五郎', '原料', 'generated' from jp_vocab where id = 'e9829df6-63e0-41e5-80b4-87f81f136774';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"原料" đọc là gì?', 'げんりょう', 'いっしょうけんめい', 'きんいろ', 'よかったですね', 'げんりょう', 'generated' from jp_vocab where id = 'e9829df6-63e0-41e5-80b4-87f81f136774';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 石油は多くの製品の_____だ。', NULL, NULL, NULL, NULL, '原料', 'generated' from jp_vocab where id = 'e9829df6-63e0-41e5-80b4-87f81f136774';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"泥棒" có nghĩa là gì?', 'kẻ trộm', 'Nhà khoa học Graham Bell', 'trạm, khắc', 'màu vàng kim', 'kẻ trộm', 'generated' from jp_vocab where id = 'a3066a19-af9e-44dd-80ff-44471274a29e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "kẻ trộm"?', 'インスタントラーメン', 'ゴッホ', '泥棒', '彫刻', '泥棒', 'generated' from jp_vocab where id = 'a3066a19-af9e-44dd-80ff-44471274a29e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"泥棒" đọc là gì?', 'どろぼう', 'ピカソ', 'インスタントラーメン', 'げんりょう', 'どろぼう', 'generated' from jp_vocab where id = 'a3066a19-af9e-44dd-80ff-44471274a29e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が入った。', NULL, NULL, NULL, NULL, '泥棒', 'generated' from jp_vocab where id = 'a3066a19-af9e-44dd-80ff-44471274a29e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"警官" có nghĩa là gì?', 'nhà thám hiểm Christopher Columbus', 'hẹn hò', 'nguyên liệu thô', 'cảnh sát', 'cảnh sát', 'generated' from jp_vocab where id = 'b98d9716-996e-4986-9ac0-7a82aa96db57';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cảnh sát"?', 'インスタントラーメン', 'デート', '警官', '一生懸命', '警官', 'generated' from jp_vocab where id = 'b98d9716-996e-4986-9ac0-7a82aa96db57';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"警官" đọc là gì?', 'ちょうこく', 'ごうか', 'グラハムベル', 'けいかん', 'けいかん', 'generated' from jp_vocab where id = 'b98d9716-996e-4986-9ac0-7a82aa96db57';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に道を聞く。', NULL, NULL, NULL, NULL, '警官', 'generated' from jp_vocab where id = 'b98d9716-996e-4986-9ac0-7a82aa96db57';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"世界中" có nghĩa là gì?', 'Đền Nikkou Toshougu', 'Hay quá nhỉ!/Tốt quá rồi!', 'nhà thám hiểm Christopher Columbus', 'trên toàn thế giới', 'trên toàn thế giới', 'generated' from jp_vocab where id = 'e3fd3f82-9af9-4ea6-a3c6-d63f469ea96c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "trên toàn thế giới"?', '世界中', '誰か', '言い伝え', 'ピカソ', '世界中', 'generated' from jp_vocab where id = 'e3fd3f82-9af9-4ea6-a3c6-d63f469ea96c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"世界中" đọc là gì?', 'けいと', 'せかいじゅう', 'きんいろ', 'ピカソ', 'せかいじゅう', 'generated' from jp_vocab where id = 'e3fd3f82-9af9-4ea6-a3c6-d63f469ea96c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を旅行する。', NULL, NULL, NULL, NULL, '世界中', 'generated' from jp_vocab where id = 'e3fd3f82-9af9-4ea6-a3c6-d63f469ea96c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"誰か" có nghĩa là gì?', 'truyền miệng', 'họa sĩ Vincent Van Gogh', 'sợi len', 'ai đó', 'ai đó', 'generated' from jp_vocab where id = '55ccf029-31bf-4ab6-830e-c7817a8bb479';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "ai đó"?', '金色', '誰か', '豪華', 'ゴッホ', '誰か', 'generated' from jp_vocab where id = '55ccf029-31bf-4ab6-830e-c7817a8bb479';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"誰か" đọc là gì?', 'なかま', 'いいつたえ', 'ゴッホ', 'だれか', 'だれか', 'generated' from jp_vocab where id = '55ccf029-31bf-4ab6-830e-c7817a8bb479';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____手伝ってください。', NULL, NULL, NULL, NULL, '誰か', 'generated' from jp_vocab where id = '55ccf029-31bf-4ab6-830e-c7817a8bb479';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"インスタントラーメン" có nghĩa là gì?', 'mỳ ăn liền, mỳ gói', 'truyền miệng', 'sang trọng, hoành tráng', 'sợi len', 'mỳ ăn liền, mỳ gói', 'generated' from jp_vocab where id = '59dd2af4-a3c1-4bc6-bea7-881147e661a4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "mỳ ăn liền, mỳ gói"?', 'インスタントラーメン', 'グラハム・ベル', '仲間', '彫刻', 'インスタントラーメン', 'generated' from jp_vocab where id = '59dd2af4-a3c1-4bc6-bea7-881147e661a4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"インスタントラーメン" đọc là gì?', 'インスタントラーメン', 'どろぼう', 'ごうか', 'きんいろ', 'インスタントラーメン', 'generated' from jp_vocab where id = '59dd2af4-a3c1-4bc6-bea7-881147e661a4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を食べる。', NULL, NULL, NULL, NULL, 'インスタントラーメン', 'generated' from jp_vocab where id = '59dd2af4-a3c1-4bc6-bea7-881147e661a4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"デート" có nghĩa là gì?', 'cảnh sát', 'Hay quá nhỉ!/Tốt quá rồi!', 'truyền miệng', 'hẹn hò', 'hẹn hò', 'generated' from jp_vocab where id = 'e916152f-cf81-42a1-b8a6-2371e4a07c6a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "hẹn hò"?', '左甚五郎', 'インスタントラーメン', '皆様', 'デート', 'デート', 'generated' from jp_vocab where id = 'e916152f-cf81-42a1-b8a6-2371e4a07c6a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"デート" đọc là gì?', 'デート', 'ひだりじんごろう', 'インスタントラーメン', 'ほる', 'デート', 'generated' from jp_vocab where id = 'e916152f-cf81-42a1-b8a6-2371e4a07c6a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 彼女と_____する。', NULL, NULL, NULL, NULL, 'デート', 'generated' from jp_vocab where id = 'e916152f-cf81-42a1-b8a6-2371e4a07c6a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"皆様" có nghĩa là gì?', 'quý vị', 'sợi len', 'chăm chỉ, cố gắng hết sức', 'Họa sĩ - nhà điêu khắc Picasso', 'quý vị', 'generated' from jp_vocab where id = '16aa7be0-40fd-4c22-9f4d-1aeb16c403d9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "quý vị"?', '彫刻', '彫る', '皆様', '金色', '皆様', 'generated' from jp_vocab where id = '16aa7be0-40fd-4c22-9f4d-1aeb16c403d9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"皆様" đọc là gì?', 'みなさま', 'いっしょうけんめい', 'にっこうとうしょうぐう', 'なかま', 'みなさま', 'generated' from jp_vocab where id = '16aa7be0-40fd-4c22-9f4d-1aeb16c403d9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____、ありがとうございます。', NULL, NULL, NULL, NULL, '皆様', 'generated' from jp_vocab where id = '16aa7be0-40fd-4c22-9f4d-1aeb16c403d9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"金色" có nghĩa là gì?', 'màu vàng kim', 'cảnh sát', 'nguyên liệu thô', 'Nhà khoa học Graham Bell', 'màu vàng kim', 'generated' from jp_vocab where id = '707768ba-5e3d-4612-a768-ddf2e5cb3626';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "màu vàng kim"?', '皆様', '彫刻', '言い伝え', '金色', '金色', 'generated' from jp_vocab where id = '707768ba-5e3d-4612-a768-ddf2e5cb3626';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"金色" đọc là gì?', 'ごうか', 'きんいろ', 'せかいじゅう', 'グラハムベル', 'きんいろ', 'generated' from jp_vocab where id = '707768ba-5e3d-4612-a768-ddf2e5cb3626';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____の指輪をもらった。', NULL, NULL, NULL, NULL, '金色', 'generated' from jp_vocab where id = '707768ba-5e3d-4612-a768-ddf2e5cb3626';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"本物" có nghĩa là gì?', 'Nhà khoa học Graham Bell', 'màu vàng kim', 'đồ thật', 'sợi len', 'đồ thật', 'generated' from jp_vocab where id = '5a373bea-a459-4ed9-a050-ddcddb29e632';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đồ thật"?', '本物', '皆様', '泥棒', 'グラハム・ベル', '本物', 'generated' from jp_vocab where id = '5a373bea-a459-4ed9-a050-ddcddb29e632';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"本物" đọc là gì?', 'ほんもの', 'いいつたえ', 'ライトきょうだい', 'けいと', 'ほんもの', 'generated' from jp_vocab where id = '5a373bea-a459-4ed9-a050-ddcddb29e632';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: これは_____のダイヤモンドだ。', NULL, NULL, NULL, NULL, '本物', 'generated' from jp_vocab where id = '5a373bea-a459-4ed9-a050-ddcddb29e632';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"豪華" có nghĩa là gì?', 'họa sĩ Vincent Van Gogh', 'quý vị', 'ai đó', 'sang trọng, hoành tráng', 'sang trọng, hoành tráng', 'generated' from jp_vocab where id = '418b5c1b-c64f-42a7-81fc-a46cc8155a21';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sang trọng, hoành tráng"?', '仲間', '豪華', '泥棒', '彫刻', '豪華', 'generated' from jp_vocab where id = '418b5c1b-c64f-42a7-81fc-a46cc8155a21';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"豪華" đọc là gì?', 'きんいろ', 'ごうか', 'ひだりじんごろう', 'ほんもの', 'ごうか', 'generated' from jp_vocab where id = '418b5c1b-c64f-42a7-81fc-a46cc8155a21';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____なホテルに泊まる。', NULL, NULL, NULL, NULL, '豪華', 'generated' from jp_vocab where id = '418b5c1b-c64f-42a7-81fc-a46cc8155a21';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"彫刻" có nghĩa là gì?', 'đồ thật', 'trên toàn thế giới', 'chăm chỉ, cố gắng hết sức', 'điêu khắc', 'điêu khắc', 'generated' from jp_vocab where id = 'd1c7c196-faea-4e3f-aec7-023c5f6af704';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "điêu khắc"?', '彫刻', 'ピカソ', 'ゴッホ', '日光東照宮', '彫刻', 'generated' from jp_vocab where id = 'd1c7c196-faea-4e3f-aec7-023c5f6af704';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"彫刻" đọc là gì?', 'だれか', 'げんりょう', 'ちょうこく', 'インスタントラーメン', 'ちょうこく', 'generated' from jp_vocab where id = 'd1c7c196-faea-4e3f-aec7-023c5f6af704';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を見に行く。', NULL, NULL, NULL, NULL, '彫刻', 'generated' from jp_vocab where id = 'd1c7c196-faea-4e3f-aec7-023c5f6af704';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"仲間" có nghĩa là gì?', 'đồng nghiệp', 'chăm chỉ, cố gắng hết sức', 'sang trọng, hoành tráng', 'trên toàn thế giới', 'đồng nghiệp', 'generated' from jp_vocab where id = '839bbc02-63cd-4ffc-ac59-7a6207323180';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đồng nghiệp"?', '彫る', 'ゴッホ', '仲間', '豪華', '仲間', 'generated' from jp_vocab where id = '839bbc02-63cd-4ffc-ac59-7a6207323180';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"仲間" đọc là gì?', 'なかま', 'ちょうこく', 'いっしょうけんめい', 'げんりょう', 'なかま', 'generated' from jp_vocab where id = '839bbc02-63cd-4ffc-ac59-7a6207323180';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 会社の_____と話す。', NULL, NULL, NULL, NULL, '仲間', 'generated' from jp_vocab where id = '839bbc02-63cd-4ffc-ac59-7a6207323180';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"言い伝え" có nghĩa là gì?', 'trên toàn thế giới', 'họa sĩ Vincent Van Gogh', 'Nhà điêu khắc Jin gorou (người thuận tay trái)', 'truyền miệng', 'truyền miệng', 'generated' from jp_vocab where id = 'e86411cf-0270-4e92-a744-53d9f93f05cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "truyền miệng"?', '毛糸', '警官', '泥棒', '言い伝え', '言い伝え', 'generated' from jp_vocab where id = 'e86411cf-0270-4e92-a744-53d9f93f05cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"言い伝え" đọc là gì?', 'ごうか', 'ひだりじんごろう', 'いいつたえ', 'グラハムベル', 'いいつたえ', 'generated' from jp_vocab where id = 'e86411cf-0270-4e92-a744-53d9f93f05cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: この話は_____だ。', NULL, NULL, NULL, NULL, '言い伝え', 'generated' from jp_vocab where id = 'e86411cf-0270-4e92-a744-53d9f93f05cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"良かったですね" có nghĩa là gì?', 'Hay quá nhỉ!/Tốt quá rồi!', 'nhà thám hiểm Christopher Columbus', 'trên toàn thế giới', 'màu vàng kim', 'Hay quá nhỉ!/Tốt quá rồi!', 'generated' from jp_vocab where id = '932be22d-ecf1-440e-9666-5d043bbd4326';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Hay quá nhỉ!/Tốt quá rồi!"?', '良かったですね', '一生懸命', '警官', 'ライト兄弟', '良かったですね', 'generated' from jp_vocab where id = '932be22d-ecf1-440e-9666-5d043bbd4326';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"良かったですね" đọc là gì?', 'よかったですね', 'コロンブス', 'いいつたえ', 'けいかん', 'よかったですね', 'generated' from jp_vocab where id = '932be22d-ecf1-440e-9666-5d043bbd4326';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 試験に合格して_____。', NULL, NULL, NULL, NULL, '良かったですね', 'generated' from jp_vocab where id = '932be22d-ecf1-440e-9666-5d043bbd4326';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"グラハム・ベル" có nghĩa là gì?', 'họa sĩ Vincent Van Gogh', 'Nhà khoa học Graham Bell', 'màu vàng kim', 'Đền Nikkou Toshougu', 'Nhà khoa học Graham Bell', 'generated' from jp_vocab where id = '90c4772a-0cb7-4f49-970f-1cb431611645';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Nhà khoa học Graham Bell"?', 'グラハム・ベル', '良かったですね', 'インスタントラーメン', '誰か', 'グラハム・ベル', 'generated' from jp_vocab where id = '90c4772a-0cb7-4f49-970f-1cb431611645';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"グラハム・ベル" đọc là gì?', 'げんりょう', 'グラハムベル', 'よかったですね', 'ピカソ', 'グラハムベル', 'generated' from jp_vocab where id = '90c4772a-0cb7-4f49-970f-1cb431611645';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____は電話を発明した。', NULL, NULL, NULL, NULL, 'グラハム・ベル', 'generated' from jp_vocab where id = '90c4772a-0cb7-4f49-970f-1cb431611645';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ライト兄弟" có nghĩa là gì?', 'hẹn hò', 'cảnh sát', 'Hay quá nhỉ!/Tốt quá rồi!', 'Anh em nhà Wright', 'Anh em nhà Wright', 'generated' from jp_vocab where id = '6ebf6eb2-ebad-47ce-9d89-8bcc13403c05';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Anh em nhà Wright"?', 'ライト兄弟', '彫る', '言い伝え', '金色', 'ライト兄弟', 'generated' from jp_vocab where id = '6ebf6eb2-ebad-47ce-9d89-8bcc13403c05';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ライト兄弟" đọc là gì?', 'ライトきょうだい', 'だれか', 'ピカソ', 'なかま', 'ライトきょうだい', 'generated' from jp_vocab where id = '6ebf6eb2-ebad-47ce-9d89-8bcc13403c05';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____は飛行機を発明した。', NULL, NULL, NULL, NULL, 'ライト兄弟', 'generated' from jp_vocab where id = '6ebf6eb2-ebad-47ce-9d89-8bcc13403c05';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ゴッホ" có nghĩa là gì?', 'cảnh sát', 'họa sĩ Vincent Van Gogh', 'nguyên liệu thô', 'màu vàng kim', 'họa sĩ Vincent Van Gogh', 'generated' from jp_vocab where id = 'e3372be7-51b1-46d8-a90b-b1a0f45924e7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "họa sĩ Vincent Van Gogh"?', '仲間', 'グラハム・ベル', '誰か', 'ゴッホ', 'ゴッホ', 'generated' from jp_vocab where id = 'e3372be7-51b1-46d8-a90b-b1a0f45924e7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ゴッホ" đọc là gì?', 'ほんもの', 'ごうか', 'コロンブス', 'ゴッホ', 'ゴッホ', 'generated' from jp_vocab where id = 'e3372be7-51b1-46d8-a90b-b1a0f45924e7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____の絵が好きだ。', NULL, NULL, NULL, NULL, 'ゴッホ', 'generated' from jp_vocab where id = 'e3372be7-51b1-46d8-a90b-b1a0f45924e7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ピカソ" có nghĩa là gì?', 'Đền Nikkou Toshougu', 'sợi len', 'Họa sĩ - nhà điêu khắc Picasso', 'nhà thám hiểm Christopher Columbus', 'Họa sĩ - nhà điêu khắc Picasso', 'generated' from jp_vocab where id = '51aec1a3-47ce-406c-a9ca-c9608c87ab74';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Họa sĩ - nhà điêu khắc Picasso"?', 'ピカソ', '彫刻', '毛糸', 'グラハム・ベル', 'ピカソ', 'generated' from jp_vocab where id = '51aec1a3-47ce-406c-a9ca-c9608c87ab74';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ピカソ" đọc là gì?', 'だれか', 'インスタントラーメン', 'せかいじゅう', 'ピカソ', 'ピカソ', 'generated' from jp_vocab where id = '51aec1a3-47ce-406c-a9ca-c9608c87ab74';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____の作品を見る。', NULL, NULL, NULL, NULL, 'ピカソ', 'generated' from jp_vocab where id = '51aec1a3-47ce-406c-a9ca-c9608c87ab74';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"コロンブス" có nghĩa là gì?', 'nhà thám hiểm Christopher Columbus', 'quý vị', 'chăm chỉ, cố gắng hết sức', 'trạm, khắc', 'nhà thám hiểm Christopher Columbus', 'generated' from jp_vocab where id = '096d89e0-9db7-4ba6-b0d6-8af200222e77';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhà thám hiểm Christopher Columbus"?', '一生懸命', 'コロンブス', '彫る', '世界中', 'コロンブス', 'generated' from jp_vocab where id = '096d89e0-9db7-4ba6-b0d6-8af200222e77';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"コロンブス" đọc là gì?', 'コロンブス', 'ほんもの', 'いっしょうけんめい', 'ちょうこく', 'コロンブス', 'generated' from jp_vocab where id = '096d89e0-9db7-4ba6-b0d6-8af200222e77';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____はアメリカを発見した。', NULL, NULL, NULL, NULL, 'コロンブス', 'generated' from jp_vocab where id = '096d89e0-9db7-4ba6-b0d6-8af200222e77';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"毛糸" có nghĩa là gì?', 'đồng nghiệp', 'truyền miệng', 'sang trọng, hoành tráng', 'sợi len', 'sợi len', 'generated' from jp_vocab where id = '4ae7c075-f04a-4655-a3a4-cddbcb6137bc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sợi len"?', '原料', '彫る', '豪華', '毛糸', '毛糸', 'generated' from jp_vocab where id = '4ae7c075-f04a-4655-a3a4-cddbcb6137bc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"毛糸" đọc là gì?', 'ほんもの', 'グラハムベル', 'けいと', 'いいつたえ', 'けいと', 'generated' from jp_vocab where id = '4ae7c075-f04a-4655-a3a4-cddbcb6137bc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____でセーターを編む。', NULL, NULL, NULL, NULL, '毛糸', 'generated' from jp_vocab where id = '4ae7c075-f04a-4655-a3a4-cddbcb6137bc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"日光東照宮" có nghĩa là gì?', 'Đền Nikkou Toshougu', 'hẹn hò', 'Nhà điêu khắc Jin gorou (người thuận tay trái)', 'đồ thật', 'Đền Nikkou Toshougu', 'generated' from jp_vocab where id = '066db3a1-a5b2-4ef8-b751-97964e81ef97';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Đền Nikkou Toshougu"?', '日光東照宮', '良かったですね', '一生懸命', '誰か', '日光東照宮', 'generated' from jp_vocab where id = '066db3a1-a5b2-4ef8-b751-97964e81ef97';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"日光東照宮" đọc là gì?', 'ライトきょうだい', 'よかったですね', 'にっこうとうしょうぐう', 'グラハムベル', 'にっこうとうしょうぐう', 'generated' from jp_vocab where id = '066db3a1-a5b2-4ef8-b751-97964e81ef97';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を見学する。', NULL, NULL, NULL, NULL, '日光東照宮', 'generated' from jp_vocab where id = '066db3a1-a5b2-4ef8-b751-97964e81ef97';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"左甚五郎" có nghĩa là gì?', 'trạm, khắc', 'cảnh sát', 'sợi len', 'Nhà điêu khắc Jin gorou (người thuận tay trái)', 'Nhà điêu khắc Jin gorou (người thuận tay trái)', 'generated' from jp_vocab where id = '66e5ed80-7bba-4718-a801-ede138655fcb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Nhà điêu khắc Jin gorou (người thuận tay trái)"?', '左甚五郎', '泥棒', '毛糸', '彫る', '左甚五郎', 'generated' from jp_vocab where id = '66e5ed80-7bba-4718-a801-ede138655fcb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"左甚五郎" đọc là gì?', 'ピカソ', 'ひだりじんごろう', 'けいと', 'ほる', 'ひだりじんごろう', 'generated' from jp_vocab where id = '66e5ed80-7bba-4718-a801-ede138655fcb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____は有名な彫刻家だ。', NULL, NULL, NULL, NULL, '左甚五郎', 'generated' from jp_vocab where id = '66e5ed80-7bba-4718-a801-ede138655fcb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"一生懸命" có nghĩa là gì?', 'ai đó', 'trên toàn thế giới', 'chăm chỉ, cố gắng hết sức', 'Hay quá nhỉ!/Tốt quá rồi!', 'chăm chỉ, cố gắng hết sức', 'generated' from jp_vocab where id = 'fcfb2673-114e-499c-9dfc-827c32d0a02b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chăm chỉ, cố gắng hết sức"?', '彫刻', '一生懸命', '原料', '左甚五郎', '一生懸命', 'generated' from jp_vocab where id = 'fcfb2673-114e-499c-9dfc-827c32d0a02b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"一生懸命" đọc là gì?', 'いっしょうけんめい', 'ピカソ', 'ライトきょうだい', 'きんいろ', 'いっしょうけんめい', 'generated' from jp_vocab where id = 'fcfb2673-114e-499c-9dfc-827c32d0a02b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____勉強する。', NULL, NULL, NULL, NULL, '一生懸命', 'generated' from jp_vocab where id = 'fcfb2673-114e-499c-9dfc-827c32d0a02b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"彫る" có nghĩa là gì?', 'sợi len', 'Đền Nikkou Toshougu', 'nguyên liệu thô', 'trạm, khắc', 'trạm, khắc', 'generated' from jp_vocab where id = 'd5822698-df78-4d9a-815d-9a0f3da686aa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "trạm, khắc"?', 'インスタントラーメン', '彫る', '警官', 'ゴッホ', '彫る', 'generated' from jp_vocab where id = 'd5822698-df78-4d9a-815d-9a0f3da686aa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"彫る" đọc là gì?', 'ほる', 'ライトきょうだい', 'ひだりじんごろう', 'げんりょう', 'ほる', 'generated' from jp_vocab where id = 'd5822698-df78-4d9a-815d-9a0f3da686aa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 木に絵を_____。', NULL, NULL, NULL, NULL, '彫る', 'generated' from jp_vocab where id = 'd5822698-df78-4d9a-815d-9a0f3da686aa';
