-- ============================================================
-- jp-go — Từ vựng N4, 課38 (phần 1, 22 từ đầu).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 27.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('7c3312d0-1dd5-43c8-bbb7-a819d3b2c732', 'N4', 38, 'word', '参加する', 'さんかする', 'tham gia (bữa tiệc)', 'thường dùng dạng [パーティーに〜]', '動詞', 27, '参加する', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('12b9e2c4-399d-428a-affd-2b244fa29028', 'N4', 38, 'word', '育てる', 'そだてる', 'mắng', NULL, '動詞', 27, '育てる', 'pdf', 'needs_review', 'Chuẩn nghĩa của 育てる là "nuôi dưỡng, nuôi lớn, giáo dục" — PDF in nghĩa "mắng" (khớp với 叱る ở 課37), nghi PDF bị lệch dòng giữa 育てる và 頼む. Giữ nguyên như PDF, cần đối chiếu lại sách gốc.')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('0639dd4a-5da0-4603-ae1c-23b12bd3bec4', 'N4', 38, 'word', '誘う', 'さそう', 'mời, rủ', NULL, '動詞', 27, '誘う', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('d39634a0-eb49-444f-bf26-cdd6a09f3ae9', 'N4', 38, 'word', '招待する', 'しょうたいする', 'mời', NULL, '動詞', 27, '招待する', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('ee1b496b-e100-4ce4-912f-d8e7e9aab458', 'N4', 38, 'word', '頼む', 'たのむ', 'chăm sóc, nuôi dưỡng', NULL, '動詞', 27, '頼む', 'pdf', 'needs_review', 'Chuẩn nghĩa của 頼む là "nhờ, yêu cầu" — PDF in nghĩa "chăm sóc, nuôi dưỡng" (khớp với 育てる), nghi PDF bị lệch dòng giữa 育てる và 頼む. Giữ nguyên như PDF, cần đối chiếu lại sách gốc.')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('11cbfe43-c750-414a-b24b-35a774a7f644', 'N4', 38, 'word', '運ぶ', 'はこぶ', 'vận chuyển', NULL, '動詞', 27, '運ぶ', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('67312ce3-c0c7-40d4-890f-61041398f2dc', 'N4', 38, 'word', '入院する', 'にゅういんする', 'nhập viện', NULL, '動詞', 27, '入院する', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('043f72d2-4539-4703-a14e-77118bda48d1', 'N4', 38, 'word', '退院する', 'たいいんする', 'xuất viện', NULL, '動詞', 27, '退院する', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('b283622e-951e-47a3-9030-6325a47efdc8', 'N4', 38, 'word', '整理する', 'せいりする', 'chỉnh sửa, sắp xếp', NULL, '動詞', 27, '整理する', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('a7e67011-132d-4dce-bcdb-fbc71a2f8396', 'N4', 38, 'word', '入れる', 'いれる', 'bật (nguồn điện)', 'thường dùng dạng [電源を〜]', '動詞', 27, '入れる', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('361c8edf-e521-4370-8faa-12bd2d1eb5af', 'N4', 38, 'word', '切る', 'きる', 'tắt (nguồn điện)', 'thường dùng dạng [電源を〜]', '動詞', 27, '切る', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('30773bc9-5cce-4826-8f6a-d2495670ad58', 'N4', 38, 'word', '掛ける', 'かける', 'khóa (ổ khóa)', 'thường dùng dạng [鍵を〜]', '動詞', 27, '掛ける', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('428aff63-6962-45f4-a069-552b3dc9c6d0', 'N4', 38, 'word', 'つく', 'つく', 'nói dối', 'thường dùng dạng [うそを〜]', '動詞', 27, 'つく', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('f68a0e16-6440-45ae-91a2-6c7fcc41de62', 'N4', 38, 'phrase', '気持ちがいい', 'きもちがいい', 'tâm trạng sảng khoái, cảm thấy dễ chịu', NULL, 'い形容詞', 27, '気持ちがいい', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('5d1617b2-b89d-4528-9382-d751536b8ebf', 'N4', 38, 'phrase', '気持ちが悪い', 'きもちがわるい', 'tâm trạng không tốt, cảm thấy khó chịu', NULL, 'い形容詞', 27, '気持ちが悪い', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('2b99a041-b84b-4ed3-af25-725ccf3ea12c', 'N4', 38, 'word', '赤ちゃん', 'あかちゃん', 'em bé', NULL, '名詞', 27, '赤ちゃん', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('6ebe15f7-5933-4af3-8d6d-ad275eef0909', 'N4', 38, 'word', '小学生', 'しょうがくせい', 'học sinh tiểu học', NULL, '名詞', 27, '小学生', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('46abf878-275b-4697-b26c-26eaa1f52d8e', 'N4', 38, 'word', '中学生', 'ちゅうがくせい', 'học sinh cấp 2', NULL, '名詞', 27, '中学生', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('363d0f09-3889-4cfe-930a-7895c7356f50', 'N4', 38, 'word', '高校生', 'こうこうせい', 'học sinh cấp 3', NULL, '名詞', 27, '高校生', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('d46bba6f-dc20-4dfa-8c99-149698e70f04', 'N4', 38, 'word', '小学校', 'しょうがっこう', 'trường tiểu học', NULL, '名詞', 27, '小学校', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('6f99ae2f-849a-4666-b204-306e8c623e9f', 'N4', 38, 'word', '中学校', 'ちゅうがっこう', 'trường cấp hai', NULL, '名詞', 27, '中学校', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status, correction_note) values ('202a235f-b184-40a2-9409-21ed31f8dc86', 'N4', 38, 'word', '海岸', 'かいがん', 'bờ biển', NULL, '名詞', 27, '海岸', 'pdf', 'ok', NULL)
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'パーティーに参加する。', 'Tham gia bữa tiệc.', 'パーティーに_____。', '参加する', 'generated' from jp_vocab where id = '7c3312d0-1dd5-43c8-bbb7-a819d3b2c732';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '子供を育てる。', 'Nuôi dạy con cái.', '子供を_____。', '育てる', 'generated' from jp_vocab where id = '12b9e2c4-399d-428a-affd-2b244fa29028';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '友達を映画に誘う。', 'Rủ bạn đi xem phim.', '友達を映画に_____。', '誘う', 'generated' from jp_vocab where id = '0639dd4a-5da0-4603-ae1c-23b12bd3bec4';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '誕生日会に招待する。', 'Mời đến tiệc sinh nhật.', '誕生日会に_____。', '招待する', 'generated' from jp_vocab where id = 'd39634a0-eb49-444f-bf26-cdd6a09f3ae9';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '手伝いを頼む。', 'Nhờ giúp đỡ.', '手伝いを_____。', '頼む', 'generated' from jp_vocab where id = 'ee1b496b-e100-4ce4-912f-d8e7e9aab458';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '荷物を運ぶ。', 'Vận chuyển hành lý.', '荷物を_____。', '運ぶ', 'generated' from jp_vocab where id = '11cbfe43-c750-414a-b24b-35a774a7f644';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '病院に入院する。', 'Nhập viện.', '病院に_____。', '入院する', 'generated' from jp_vocab where id = '67312ce3-c0c7-40d4-890f-61041398f2dc';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '来週退院する。', 'Tuần sau xuất viện.', '来週_____。', '退院する', 'generated' from jp_vocab where id = '043f72d2-4539-4703-a14e-77118bda48d1';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '部屋を整理する。', 'Sắp xếp phòng.', '部屋を_____。', '整理する', 'generated' from jp_vocab where id = 'b283622e-951e-47a3-9030-6325a47efdc8';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'テレビの電源を入れる。', 'Bật nguồn điện của tivi.', 'テレビの電源を_____。', '入れる', 'generated' from jp_vocab where id = 'a7e67011-132d-4dce-bcdb-fbc71a2f8396';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'パソコンの電源を切る。', 'Tắt nguồn điện của máy tính.', 'パソコンの電源を_____。', '切る', 'generated' from jp_vocab where id = '361c8edf-e521-4370-8faa-12bd2d1eb5af';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ドアに鍵を掛ける。', 'Khóa cửa.', 'ドアに鍵を_____。', '掛ける', 'generated' from jp_vocab where id = '30773bc9-5cce-4826-8f6a-d2495670ad58';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'うそをつく。', 'Nói dối.', '_____をつく。', 'うそ', 'generated' from jp_vocab where id = '428aff63-6962-45f4-a069-552b3dc9c6d0';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '温泉に入ると気持ちがいい。', 'Tắm suối nước nóng thì thấy dễ chịu.', '温泉に入ると_____。', '気持ちがいい', 'generated' from jp_vocab where id = 'f68a0e16-6440-45ae-91a2-6c7fcc41de62';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '船に酔って気持ちが悪い。', 'Say tàu nên thấy khó chịu.', '船に酔って_____。', '気持ちが悪い', 'generated' from jp_vocab where id = '5d1617b2-b89d-4528-9382-d751536b8ebf';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '赤ちゃんが生まれた。', 'Em bé đã ra đời.', '_____が生まれた。', '赤ちゃん', 'generated' from jp_vocab where id = '2b99a041-b84b-4ed3-af25-725ccf3ea12c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '小学生に勉強を教える。', 'Dạy học cho học sinh tiểu học.', '_____に勉強を教える。', '小学生', 'generated' from jp_vocab where id = '6ebe15f7-5933-4af3-8d6d-ad275eef0909';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '中学生になる。', 'Trở thành học sinh cấp 2.', '_____になる。', '中学生', 'generated' from jp_vocab where id = '46abf878-275b-4697-b26c-26eaa1f52d8e';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '高校生の頃を思い出す。', 'Nhớ lại thời học sinh cấp 3.', '_____の頃を思い出す。', '高校生', 'generated' from jp_vocab where id = '363d0f09-3889-4cfe-930a-7895c7356f50';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '小学校に入学する。', 'Vào học trường tiểu học.', '_____に入学する。', '小学校', 'generated' from jp_vocab where id = 'd46bba6f-dc20-4dfa-8c99-149698e70f04';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '中学校を卒業する。', 'Tốt nghiệp trường cấp hai.', '_____を卒業する。', '中学校', 'generated' from jp_vocab where id = '6f99ae2f-849a-4666-b204-306e8c623e9f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '海岸を散歩する。', 'Đi dạo dọc bờ biển.', '_____を散歩する。', '海岸', 'generated' from jp_vocab where id = '202a235f-b184-40a2-9409-21ed31f8dc86';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"参加する" có nghĩa là gì?', 'mắng', 'vận chuyển', 'tham gia (bữa tiệc)', 'học sinh tiểu học', 'tham gia (bữa tiệc)', 'generated' from jp_vocab where id = '7c3312d0-1dd5-43c8-bbb7-a819d3b2c732';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tham gia (bữa tiệc)"?', '参加する', '高校生', '退院する', '誘う', '参加する', 'generated' from jp_vocab where id = '7c3312d0-1dd5-43c8-bbb7-a819d3b2c732';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"参加する" đọc là gì?', 'さんかする', 'にゅういんする', 'せいりする', 'そだてる', 'さんかする', 'generated' from jp_vocab where id = '7c3312d0-1dd5-43c8-bbb7-a819d3b2c732';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: パーティーに_____。', NULL, NULL, NULL, NULL, '参加する', 'generated' from jp_vocab where id = '7c3312d0-1dd5-43c8-bbb7-a819d3b2c732';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"育てる" có nghĩa là gì?', 'mắng', 'khóa (ổ khóa)', 'học sinh cấp 2', 'bờ biển', 'mắng', 'generated' from jp_vocab where id = '12b9e2c4-399d-428a-affd-2b244fa29028';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "mắng"?', '育てる', '切る', '海岸', '整理する', '育てる', 'generated' from jp_vocab where id = '12b9e2c4-399d-428a-affd-2b244fa29028';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"育てる" đọc là gì?', 'しょうがっこう', 'こうこうせい', 'そだてる', 'あかちゃん', 'そだてる', 'generated' from jp_vocab where id = '12b9e2c4-399d-428a-affd-2b244fa29028';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 子供を_____。', NULL, NULL, NULL, NULL, '育てる', 'generated' from jp_vocab where id = '12b9e2c4-399d-428a-affd-2b244fa29028';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"誘う" có nghĩa là gì?', 'chăm sóc, nuôi dưỡng', 'mời, rủ', 'vận chuyển', 'chỉnh sửa, sắp xếp', 'mời, rủ', 'generated' from jp_vocab where id = '0639dd4a-5da0-4603-ae1c-23b12bd3bec4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "mời, rủ"?', '高校生', '育てる', '誘う', '入れる', '誘う', 'generated' from jp_vocab where id = '0639dd4a-5da0-4603-ae1c-23b12bd3bec4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"誘う" đọc là gì?', 'いれる', 'しょうがっこう', 'たいいんする', 'さそう', 'さそう', 'generated' from jp_vocab where id = '0639dd4a-5da0-4603-ae1c-23b12bd3bec4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 友達を映画に_____。', NULL, NULL, NULL, NULL, '誘う', 'generated' from jp_vocab where id = '0639dd4a-5da0-4603-ae1c-23b12bd3bec4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"招待する" có nghĩa là gì?', 'tham gia (bữa tiệc)', 'học sinh cấp 2', 'mời', 'trường tiểu học', 'mời', 'generated' from jp_vocab where id = 'd39634a0-eb49-444f-bf26-cdd6a09f3ae9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "mời"?', 'つく', '整理する', '招待する', '高校生', '招待する', 'generated' from jp_vocab where id = 'd39634a0-eb49-444f-bf26-cdd6a09f3ae9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"招待する" đọc là gì?', 'きる', 'しょうたいする', 'かいがん', 'たのむ', 'しょうたいする', 'generated' from jp_vocab where id = 'd39634a0-eb49-444f-bf26-cdd6a09f3ae9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 誕生日会に_____。', NULL, NULL, NULL, NULL, '招待する', 'generated' from jp_vocab where id = 'd39634a0-eb49-444f-bf26-cdd6a09f3ae9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"頼む" có nghĩa là gì?', 'chăm sóc, nuôi dưỡng', 'tắt (nguồn điện)', 'học sinh cấp 2', 'tâm trạng sảng khoái, cảm thấy dễ chịu', 'chăm sóc, nuôi dưỡng', 'generated' from jp_vocab where id = 'ee1b496b-e100-4ce4-912f-d8e7e9aab458';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chăm sóc, nuôi dưỡng"?', '整理する', '参加する', '切る', '頼む', '頼む', 'generated' from jp_vocab where id = 'ee1b496b-e100-4ce4-912f-d8e7e9aab458';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"頼む" đọc là gì?', 'はこぶ', 'たのむ', 'かける', 'あかちゃん', 'たのむ', 'generated' from jp_vocab where id = 'ee1b496b-e100-4ce4-912f-d8e7e9aab458';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 手伝いを_____。', NULL, NULL, NULL, NULL, '頼む', 'generated' from jp_vocab where id = 'ee1b496b-e100-4ce4-912f-d8e7e9aab458';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"運ぶ" có nghĩa là gì?', 'học sinh cấp 2', 'khóa (ổ khóa)', 'vận chuyển', 'tâm trạng sảng khoái, cảm thấy dễ chịu', 'vận chuyển', 'generated' from jp_vocab where id = '11cbfe43-c750-414a-b24b-35a774a7f644';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vận chuyển"?', '小学校', '海岸', '運ぶ', '気持ちがいい', '運ぶ', 'generated' from jp_vocab where id = '11cbfe43-c750-414a-b24b-35a774a7f644';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"運ぶ" đọc là gì?', 'はこぶ', 'さそう', 'さんかする', 'しょうたいする', 'はこぶ', 'generated' from jp_vocab where id = '11cbfe43-c750-414a-b24b-35a774a7f644';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 荷物を_____。', NULL, NULL, NULL, NULL, '運ぶ', 'generated' from jp_vocab where id = '11cbfe43-c750-414a-b24b-35a774a7f644';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"入院する" có nghĩa là gì?', 'tắt (nguồn điện)', 'nhập viện', 'chăm sóc, nuôi dưỡng', 'tham gia (bữa tiệc)', 'nhập viện', 'generated' from jp_vocab where id = '67312ce3-c0c7-40d4-890f-61041398f2dc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhập viện"?', '小学校', '入院する', '気持ちがいい', '中学生', '入院する', 'generated' from jp_vocab where id = '67312ce3-c0c7-40d4-890f-61041398f2dc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"入院する" đọc là gì?', 'いれる', 'そだてる', 'にゅういんする', 'かける', 'にゅういんする', 'generated' from jp_vocab where id = '67312ce3-c0c7-40d4-890f-61041398f2dc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 病院に_____。', NULL, NULL, NULL, NULL, '入院する', 'generated' from jp_vocab where id = '67312ce3-c0c7-40d4-890f-61041398f2dc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"退院する" có nghĩa là gì?', 'mời', 'tâm trạng sảng khoái, cảm thấy dễ chịu', 'xuất viện', 'khóa (ổ khóa)', 'xuất viện', 'generated' from jp_vocab where id = '043f72d2-4539-4703-a14e-77118bda48d1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "xuất viện"?', '赤ちゃん', '退院する', '中学生', '育てる', '退院する', 'generated' from jp_vocab where id = '043f72d2-4539-4703-a14e-77118bda48d1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"退院する" đọc là gì?', 'しょうがくせい', 'たいいんする', 'つく', 'きもちがいい', 'たいいんする', 'generated' from jp_vocab where id = '043f72d2-4539-4703-a14e-77118bda48d1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 来週_____。', NULL, NULL, NULL, NULL, '退院する', 'generated' from jp_vocab where id = '043f72d2-4539-4703-a14e-77118bda48d1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"整理する" có nghĩa là gì?', 'học sinh cấp 3', 'chỉnh sửa, sắp xếp', 'học sinh tiểu học', 'học sinh cấp 2', 'chỉnh sửa, sắp xếp', 'generated' from jp_vocab where id = 'b283622e-951e-47a3-9030-6325a47efdc8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chỉnh sửa, sắp xếp"?', '高校生', '整理する', '気持ちがいい', '中学生', '整理する', 'generated' from jp_vocab where id = 'b283622e-951e-47a3-9030-6325a47efdc8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"整理する" đọc là gì?', 'きもちがわるい', 'にゅういんする', 'ちゅうがっこう', 'せいりする', 'せいりする', 'generated' from jp_vocab where id = 'b283622e-951e-47a3-9030-6325a47efdc8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 部屋を_____。', NULL, NULL, NULL, NULL, '整理する', 'generated' from jp_vocab where id = 'b283622e-951e-47a3-9030-6325a47efdc8';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"入れる" có nghĩa là gì?', 'trường cấp hai', 'bật (nguồn điện)', 'mời, rủ', 'chỉnh sửa, sắp xếp', 'bật (nguồn điện)', 'generated' from jp_vocab where id = 'a7e67011-132d-4dce-bcdb-fbc71a2f8396';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "bật (nguồn điện)"?', '気持ちが悪い', '参加する', '整理する', '入れる', '入れる', 'generated' from jp_vocab where id = 'a7e67011-132d-4dce-bcdb-fbc71a2f8396';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"入れる" đọc là gì?', 'しょうがくせい', 'きもちがわるい', 'いれる', 'つく', 'いれる', 'generated' from jp_vocab where id = 'a7e67011-132d-4dce-bcdb-fbc71a2f8396';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: テレビの電源を_____。', NULL, NULL, NULL, NULL, '入れる', 'generated' from jp_vocab where id = 'a7e67011-132d-4dce-bcdb-fbc71a2f8396';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"切る" có nghĩa là gì?', 'học sinh tiểu học', 'trường tiểu học', 'tắt (nguồn điện)', 'xuất viện', 'tắt (nguồn điện)', 'generated' from jp_vocab where id = '361c8edf-e521-4370-8faa-12bd2d1eb5af';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tắt (nguồn điện)"?', '切る', '参加する', 'つく', '赤ちゃん', '切る', 'generated' from jp_vocab where id = '361c8edf-e521-4370-8faa-12bd2d1eb5af';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"切る" đọc là gì?', 'きる', 'せいりする', 'しょうがっこう', 'つく', 'きる', 'generated' from jp_vocab where id = '361c8edf-e521-4370-8faa-12bd2d1eb5af';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: パソコンの電源を_____。', NULL, NULL, NULL, NULL, '切る', 'generated' from jp_vocab where id = '361c8edf-e521-4370-8faa-12bd2d1eb5af';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"掛ける" có nghĩa là gì?', 'trường tiểu học', 'chỉnh sửa, sắp xếp', 'khóa (ổ khóa)', 'bật (nguồn điện)', 'khóa (ổ khóa)', 'generated' from jp_vocab where id = '30773bc9-5cce-4826-8f6a-d2495670ad58';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "khóa (ổ khóa)"?', '整理する', '掛ける', '運ぶ', '小学生', '掛ける', 'generated' from jp_vocab where id = '30773bc9-5cce-4826-8f6a-d2495670ad58';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"掛ける" đọc là gì?', 'かける', 'さんかする', 'あかちゃん', 'にゅういんする', 'かける', 'generated' from jp_vocab where id = '30773bc9-5cce-4826-8f6a-d2495670ad58';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: ドアに鍵を_____。', NULL, NULL, NULL, NULL, '掛ける', 'generated' from jp_vocab where id = '30773bc9-5cce-4826-8f6a-d2495670ad58';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"つく" có nghĩa là gì?', 'trường tiểu học', 'khóa (ổ khóa)', 'mời, rủ', 'nói dối', 'nói dối', 'generated' from jp_vocab where id = '428aff63-6962-45f4-a069-552b3dc9c6d0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nói dối"?', '高校生', 'つく', '整理する', '入院する', 'つく', 'generated' from jp_vocab where id = '428aff63-6962-45f4-a069-552b3dc9c6d0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"つく" đọc là gì?', 'いれる', 'ちゅうがっこう', 'さそう', 'つく', 'つく', 'generated' from jp_vocab where id = '428aff63-6962-45f4-a069-552b3dc9c6d0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____をつく。', NULL, NULL, NULL, NULL, 'うそ', 'generated' from jp_vocab where id = '428aff63-6962-45f4-a069-552b3dc9c6d0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"気持ちがいい" có nghĩa là gì?', 'học sinh cấp 2', 'em bé', 'mời', 'tâm trạng sảng khoái, cảm thấy dễ chịu', 'tâm trạng sảng khoái, cảm thấy dễ chịu', 'generated' from jp_vocab where id = 'f68a0e16-6440-45ae-91a2-6c7fcc41de62';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tâm trạng sảng khoái, cảm thấy dễ chịu"?', '気持ちがいい', '高校生', '招待する', '運ぶ', '気持ちがいい', 'generated' from jp_vocab where id = 'f68a0e16-6440-45ae-91a2-6c7fcc41de62';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"気持ちがいい" đọc là gì?', 'きもちがわるい', 'たいいんする', 'そだてる', 'きもちがいい', 'きもちがいい', 'generated' from jp_vocab where id = 'f68a0e16-6440-45ae-91a2-6c7fcc41de62';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 温泉に入ると_____。', NULL, NULL, NULL, NULL, '気持ちがいい', 'generated' from jp_vocab where id = 'f68a0e16-6440-45ae-91a2-6c7fcc41de62';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"気持ちが悪い" có nghĩa là gì?', 'tâm trạng sảng khoái, cảm thấy dễ chịu', 'khóa (ổ khóa)', 'tắt (nguồn điện)', 'tâm trạng không tốt, cảm thấy khó chịu', 'tâm trạng không tốt, cảm thấy khó chịu', 'generated' from jp_vocab where id = '5d1617b2-b89d-4528-9382-d751536b8ebf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tâm trạng không tốt, cảm thấy khó chịu"?', 'つく', '整理する', '中学校', '気持ちが悪い', '気持ちが悪い', 'generated' from jp_vocab where id = '5d1617b2-b89d-4528-9382-d751536b8ebf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"気持ちが悪い" đọc là gì?', 'こうこうせい', 'せいりする', 'しょうがくせい', 'きもちがわるい', 'きもちがわるい', 'generated' from jp_vocab where id = '5d1617b2-b89d-4528-9382-d751536b8ebf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 船に酔って_____。', NULL, NULL, NULL, NULL, '気持ちが悪い', 'generated' from jp_vocab where id = '5d1617b2-b89d-4528-9382-d751536b8ebf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"赤ちゃん" có nghĩa là gì?', 'mắng', 'em bé', 'xuất viện', 'tâm trạng không tốt, cảm thấy khó chịu', 'em bé', 'generated' from jp_vocab where id = '2b99a041-b84b-4ed3-af25-725ccf3ea12c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "em bé"?', '高校生', '赤ちゃん', '育てる', '海岸', '赤ちゃん', 'generated' from jp_vocab where id = '2b99a041-b84b-4ed3-af25-725ccf3ea12c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"赤ちゃん" đọc là gì?', 'あかちゃん', 'しょうがっこう', 'たのむ', 'しょうたいする', 'あかちゃん', 'generated' from jp_vocab where id = '2b99a041-b84b-4ed3-af25-725ccf3ea12c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が生まれた。', NULL, NULL, NULL, NULL, '赤ちゃん', 'generated' from jp_vocab where id = '2b99a041-b84b-4ed3-af25-725ccf3ea12c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"小学生" có nghĩa là gì?', 'trường cấp hai', 'chăm sóc, nuôi dưỡng', 'học sinh tiểu học', 'nói dối', 'học sinh tiểu học', 'generated' from jp_vocab where id = '6ebe15f7-5933-4af3-8d6d-ad275eef0909';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "học sinh tiểu học"?', '気持ちがいい', '誘う', '小学生', '小学校', '小学生', 'generated' from jp_vocab where id = '6ebe15f7-5933-4af3-8d6d-ad275eef0909';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"小学生" đọc là gì?', 'きもちがわるい', 'きもちがいい', 'いれる', 'しょうがくせい', 'しょうがくせい', 'generated' from jp_vocab where id = '6ebe15f7-5933-4af3-8d6d-ad275eef0909';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に勉強を教える。', NULL, NULL, NULL, NULL, '小学生', 'generated' from jp_vocab where id = '6ebe15f7-5933-4af3-8d6d-ad275eef0909';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"中学生" có nghĩa là gì?', 'vận chuyển', 'bật (nguồn điện)', 'chăm sóc, nuôi dưỡng', 'học sinh cấp 2', 'học sinh cấp 2', 'generated' from jp_vocab where id = '46abf878-275b-4697-b26c-26eaa1f52d8e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "học sinh cấp 2"?', '気持ちが悪い', '中学生', '頼む', '入れる', '中学生', 'generated' from jp_vocab where id = '46abf878-275b-4697-b26c-26eaa1f52d8e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"中学生" đọc là gì?', 'つく', 'そだてる', 'いれる', 'ちゅうがくせい', 'ちゅうがくせい', 'generated' from jp_vocab where id = '46abf878-275b-4697-b26c-26eaa1f52d8e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____になる。', NULL, NULL, NULL, NULL, '中学生', 'generated' from jp_vocab where id = '46abf878-275b-4697-b26c-26eaa1f52d8e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"高校生" có nghĩa là gì?', 'tâm trạng sảng khoái, cảm thấy dễ chịu', 'mời, rủ', 'học sinh cấp 3', 'bờ biển', 'học sinh cấp 3', 'generated' from jp_vocab where id = '363d0f09-3889-4cfe-930a-7895c7356f50';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "học sinh cấp 3"?', '整理する', '高校生', '招待する', '中学生', '高校生', 'generated' from jp_vocab where id = '363d0f09-3889-4cfe-930a-7895c7356f50';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"高校生" đọc là gì?', 'しょうがっこう', 'あかちゃん', 'きもちがわるい', 'こうこうせい', 'こうこうせい', 'generated' from jp_vocab where id = '363d0f09-3889-4cfe-930a-7895c7356f50';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____の頃を思い出す。', NULL, NULL, NULL, NULL, '高校生', 'generated' from jp_vocab where id = '363d0f09-3889-4cfe-930a-7895c7356f50';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"小学校" có nghĩa là gì?', 'mắng', 'bờ biển', 'chăm sóc, nuôi dưỡng', 'trường tiểu học', 'trường tiểu học', 'generated' from jp_vocab where id = 'd46bba6f-dc20-4dfa-8c99-149698e70f04';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "trường tiểu học"?', '小学校', '運ぶ', 'つく', '招待する', '小学校', 'generated' from jp_vocab where id = 'd46bba6f-dc20-4dfa-8c99-149698e70f04';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"小学校" đọc là gì?', 'つく', 'こうこうせい', 'しょうがっこう', 'さんかする', 'しょうがっこう', 'generated' from jp_vocab where id = 'd46bba6f-dc20-4dfa-8c99-149698e70f04';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に入学する。', NULL, NULL, NULL, NULL, '小学校', 'generated' from jp_vocab where id = 'd46bba6f-dc20-4dfa-8c99-149698e70f04';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"中学校" có nghĩa là gì?', 'bờ biển', 'trường cấp hai', 'bật (nguồn điện)', 'chăm sóc, nuôi dưỡng', 'trường cấp hai', 'generated' from jp_vocab where id = '6f99ae2f-849a-4666-b204-306e8c623e9f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "trường cấp hai"?', '退院する', '中学校', '中学生', '入院する', '中学校', 'generated' from jp_vocab where id = '6f99ae2f-849a-4666-b204-306e8c623e9f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"中学校" đọc là gì?', 'かいがん', 'きもちがいい', 'きる', 'ちゅうがっこう', 'ちゅうがっこう', 'generated' from jp_vocab where id = '6f99ae2f-849a-4666-b204-306e8c623e9f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を卒業する。', NULL, NULL, NULL, NULL, '中学校', 'generated' from jp_vocab where id = '6f99ae2f-849a-4666-b204-306e8c623e9f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"海岸" có nghĩa là gì?', 'bờ biển', 'học sinh cấp 2', 'mời, rủ', 'em bé', 'bờ biển', 'generated' from jp_vocab where id = '202a235f-b184-40a2-9409-21ed31f8dc86';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "bờ biển"?', '海岸', '切る', '入れる', '入院する', '海岸', 'generated' from jp_vocab where id = '202a235f-b184-40a2-9409-21ed31f8dc86';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"海岸" đọc là gì?', 'ちゅうがっこう', 'さそう', 'そだてる', 'かいがん', 'かいがん', 'generated' from jp_vocab where id = '202a235f-b184-40a2-9409-21ed31f8dc86';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を散歩する。', NULL, NULL, NULL, NULL, '海岸', 'generated' from jp_vocab where id = '202a235f-b184-40a2-9409-21ed31f8dc86';
