-- ============================================================
-- jp-go — Từ vựng N4, 課39 (phần 1, 20 từ đầu).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 28.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('485980cb-5130-451c-8929-9ffca70a8693', 'N4', 39, 'word', '答える', 'こたえる', 'trả lời (câu hỏi)', 'thường dùng dạng [質問に〜]', '動詞', 28, '答える', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('f2c9f685-c881-40e9-b44a-bf5cf82ee826', 'N4', 39, 'word', '倒れる', 'たおれる', '(tòa nhà) đổ/ (người) ngất', NULL, '動詞', 28, '倒れる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b40301a0-86d6-40ef-9415-c3dd5238ef04', 'N4', 39, 'word', '通る', 'とおる', 'đi (xuyên) qua (đường)', 'thường dùng dạng [道を〜]', '動詞', 28, '通る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('289b7214-3a6e-4a80-8d73-3376d345b486', 'N4', 39, 'word', '死ぬ', 'しぬ', 'chết', NULL, '動詞', 28, '死ぬ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('8d38fecd-584f-4e67-a200-664647b10128', 'N4', 39, 'word', '西洋化する', 'せいようかする', 'Tây Âu hóa', NULL, '動詞', 28, '西洋化する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e6c37ab8-1d24-459b-a257-9b1a48abc353', 'N4', 39, 'word', 'びっくりする', 'びっくりする', 'giật mình', NULL, '動詞', 28, 'びっくりする', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3e2e2ee0-ba4c-4008-bafc-ddfd33088ed0', 'N4', 39, 'word', 'がっかりする', 'がっかりする', 'thất vọng', NULL, '動詞', 28, 'がっかりする', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('49fb3097-f47f-48cc-bb3a-2de2f321c1f0', 'N4', 39, 'word', '安心する', 'あんしんする', 'yên tâm', NULL, '動詞', 28, '安心する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3059cd35-20c4-4985-a3f4-fd484279f5a0', 'N4', 39, 'word', '喧嘩する', 'けんかする', 'cãi nhau', NULL, '動詞', 28, '喧嘩する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('69691f91-16f1-4a76-9b41-7e4aa8dd7d30', 'N4', 39, 'word', '離婚する', 'りこんする', 'ly hôn', NULL, '動詞', 28, '離婚する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b940bcdf-139c-4a38-b84b-e8883a866088', 'N4', 39, 'word', '太る', 'ふとる', 'béo ra', NULL, '動詞', 28, '太る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3986fca1-e588-487e-a85f-d18ff6fead36', 'N4', 39, 'word', '痩せる', 'やせる', 'gầy đi', NULL, '動詞', 28, '痩せる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b6013c87-0d23-495a-831b-9f284bd45c8b', 'N4', 39, 'word', '複雑', 'ふくざつ', 'phức tạp', NULL, 'な形容詞', 28, '複雑', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('974f18a2-0cd8-4e3a-8c59-84eb28d6a107', 'N4', 39, 'word', '邪魔', 'じゃま', 'vướng, vướng víu', NULL, 'な形容詞', 28, '邪魔', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d9ee9dd7-e8bc-4860-9ce9-1ab77a363e94', 'N4', 39, 'word', '硬い', 'かたい', 'cứng', NULL, 'い形容詞', 28, '硬い', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b6a31387-1e97-4214-8218-2898574d77fc', 'N4', 39, 'word', '柔らかい', 'やわらかい', 'mềm', NULL, 'い形容詞', 28, '柔らかい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b75f5c8f-75d8-4993-8d50-f02bb49ead49', 'N4', 39, 'word', '汚い', 'きたない', 'bẩn', NULL, 'い形容詞', 28, '汚い', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b53e68ef-87d6-47db-8a54-41d193143856', 'N4', 39, 'word', '悲しい', 'かなしい', 'buồn', NULL, 'い形容詞', 28, '悲しい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('1482fbd5-077b-40f1-a19b-692e159a5abf', 'N4', 39, 'word', '恥ずかしい', 'はずかしい', 'xấu hổ', NULL, 'い形容詞', 28, '恥ずかしい', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('74033ba4-6cba-4231-9172-c133c7ff1710', 'N4', 39, 'word', '大人', 'おとな', 'người lớn', NULL, '名詞', 28, '大人', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '質問に答える。', 'Trả lời câu hỏi.', '質問に_____。', '答える', 'generated' from jp_vocab where id = '485980cb-5130-451c-8929-9ffca70a8693';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ビルが倒れた。', 'Tòa nhà đã đổ.', 'ビルが_____た。', '倒れ', 'generated' from jp_vocab where id = 'f2c9f685-c881-40e9-b44a-bf5cf82ee826';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'この道を通る。', 'Đi qua con đường này.', 'この道を_____。', '通る', 'generated' from jp_vocab where id = 'b40301a0-86d6-40ef-9415-c3dd5238ef04';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '事故で死ぬ。', 'Chết vì tai nạn.', '事故で_____。', '死ぬ', 'generated' from jp_vocab where id = '289b7214-3a6e-4a80-8d73-3376d345b486';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '日本の食生活が西洋化する。', 'Đời sống ẩm thực Nhật Bản bị Tây Âu hóa.', '日本の食生活が_____。', '西洋化する', 'generated' from jp_vocab where id = '8d38fecd-584f-4e67-a200-664647b10128';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '大きな音にびっくりする。', 'Giật mình vì tiếng động lớn.', '大きな音に_____。', 'びっくりする', 'generated' from jp_vocab where id = 'e6c37ab8-1d24-459b-a257-9b1a48abc353';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '試験に落ちてがっかりする。', 'Thất vọng vì trượt kì thi.', '試験に落ちて_____。', 'がっかりする', 'generated' from jp_vocab where id = '3e2e2ee0-ba4c-4008-bafc-ddfd33088ed0';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '連絡をもらって安心する。', 'Yên tâm khi nhận được liên lạc.', '連絡をもらって_____。', '安心する', 'generated' from jp_vocab where id = '49fb3097-f47f-48cc-bb3a-2de2f321c1f0';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '兄弟と喧嘩する。', 'Cãi nhau với anh em.', '兄弟と_____。', '喧嘩する', 'generated' from jp_vocab where id = '3059cd35-20c4-4985-a3f4-fd484279f5a0';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '二人は離婚した。', 'Hai người đã ly hôn.', '二人は_____た。', '離婚し', 'generated' from jp_vocab where id = '69691f91-16f1-4a76-9b41-7e4aa8dd7d30';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '最近太った。', 'Dạo này béo ra.', '最近_____た。', '太っ', 'generated' from jp_vocab where id = 'b940bcdf-139c-4a38-b84b-e8883a866088';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ダイエットして痩せた。', 'Ăn kiêng nên đã gầy đi.', 'ダイエットして_____た。', '痩せ', 'generated' from jp_vocab where id = '3986fca1-e588-487e-a85f-d18ff6fead36';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'この問題は複雑だ。', 'Vấn đề này phức tạp.', 'この問題は_____だ。', '複雑', 'generated' from jp_vocab where id = 'b6013c87-0d23-495a-831b-9f284bd45c8b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '荷物が邪魔だ。', 'Hành lý vướng víu.', '荷物が_____だ。', '邪魔', 'generated' from jp_vocab where id = '974f18a2-0cd8-4e3a-8c59-84eb28d6a107';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'このパンは硬い。', 'Bánh mì này cứng.', 'このパンは_____。', '硬い', 'generated' from jp_vocab where id = 'd9ee9dd7-e8bc-4860-9ce9-1ab77a363e94';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '柔らかいベッドで寝る。', 'Ngủ trên chiếc giường mềm.', '_____ベッドで寝る。', '柔らかい', 'generated' from jp_vocab where id = 'b6a31387-1e97-4214-8218-2898574d77fc';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '部屋が汚い。', 'Phòng bẩn.', '部屋が_____。', '汚い', 'generated' from jp_vocab where id = 'b75f5c8f-75d8-4993-8d50-f02bb49ead49';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '別れて悲しい。', 'Chia tay nên buồn.', '別れて_____。', '悲しい', 'generated' from jp_vocab where id = 'b53e68ef-87d6-47db-8a54-41d193143856';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '間違えて恥ずかしい。', 'Nhầm nên xấu hổ.', '間違えて_____。', '恥ずかしい', 'generated' from jp_vocab where id = '1482fbd5-077b-40f1-a19b-692e159a5abf';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '大人になる。', 'Trở thành người lớn.', '_____になる。', '大人', 'generated' from jp_vocab where id = '74033ba4-6cba-4231-9172-c133c7ff1710';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"答える" có nghĩa là gì?', 'béo ra', 'đi (xuyên) qua (đường)', 'trả lời (câu hỏi)', 'ly hôn', 'trả lời (câu hỏi)', 'generated' from jp_vocab where id = '485980cb-5130-451c-8929-9ffca70a8693';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "trả lời (câu hỏi)"?', '喧嘩する', 'がっかりする', '倒れる', '答える', '答える', 'generated' from jp_vocab where id = '485980cb-5130-451c-8929-9ffca70a8693';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"答える" đọc là gì?', 'やせる', 'びっくりする', 'おとな', 'こたえる', 'こたえる', 'generated' from jp_vocab where id = '485980cb-5130-451c-8929-9ffca70a8693';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 質問に_____。', NULL, NULL, NULL, NULL, '答える', 'generated' from jp_vocab where id = '485980cb-5130-451c-8929-9ffca70a8693';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"倒れる" có nghĩa là gì?', '(tòa nhà) đổ/ (người) ngất', 'giật mình', 'béo ra', 'phức tạp', '(tòa nhà) đổ/ (người) ngất', 'generated' from jp_vocab where id = 'f2c9f685-c881-40e9-b44a-bf5cf82ee826';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "(tòa nhà) đổ/ (người) ngất"?', 'がっかりする', '柔らかい', '倒れる', '西洋化する', '倒れる', 'generated' from jp_vocab where id = 'f2c9f685-c881-40e9-b44a-bf5cf82ee826';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"倒れる" đọc là gì?', 'あんしんする', 'びっくりする', 'やせる', 'たおれる', 'たおれる', 'generated' from jp_vocab where id = 'f2c9f685-c881-40e9-b44a-bf5cf82ee826';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: ビルが_____た。', NULL, NULL, NULL, NULL, '倒れ', 'generated' from jp_vocab where id = 'f2c9f685-c881-40e9-b44a-bf5cf82ee826';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"通る" có nghĩa là gì?', 'đi (xuyên) qua (đường)', 'bẩn', 'buồn', 'xấu hổ', 'đi (xuyên) qua (đường)', 'generated' from jp_vocab where id = 'b40301a0-86d6-40ef-9415-c3dd5238ef04';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đi (xuyên) qua (đường)"?', '通る', '答える', 'がっかりする', '邪魔', '通る', 'generated' from jp_vocab where id = 'b40301a0-86d6-40ef-9415-c3dd5238ef04';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"通る" đọc là gì?', 'とおる', 'けんかする', 'きたない', 'おとな', 'とおる', 'generated' from jp_vocab where id = 'b40301a0-86d6-40ef-9415-c3dd5238ef04';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: この道を_____。', NULL, NULL, NULL, NULL, '通る', 'generated' from jp_vocab where id = 'b40301a0-86d6-40ef-9415-c3dd5238ef04';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"死ぬ" có nghĩa là gì?', 'buồn', 'thất vọng', 'chết', 'Tây Âu hóa', 'chết', 'generated' from jp_vocab where id = '289b7214-3a6e-4a80-8d73-3376d345b486';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chết"?', '通る', '汚い', '複雑', '死ぬ', '死ぬ', 'generated' from jp_vocab where id = '289b7214-3a6e-4a80-8d73-3376d345b486';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"死ぬ" đọc là gì?', 'たおれる', 'がっかりする', 'しぬ', 'やわらかい', 'しぬ', 'generated' from jp_vocab where id = '289b7214-3a6e-4a80-8d73-3376d345b486';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 事故で_____。', NULL, NULL, NULL, NULL, '死ぬ', 'generated' from jp_vocab where id = '289b7214-3a6e-4a80-8d73-3376d345b486';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"西洋化する" có nghĩa là gì?', 'chết', 'cãi nhau', 'Tây Âu hóa', 'vướng, vướng víu', 'Tây Âu hóa', 'generated' from jp_vocab where id = '8d38fecd-584f-4e67-a200-664647b10128';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Tây Âu hóa"?', '痩せる', 'がっかりする', '答える', '西洋化する', '西洋化する', 'generated' from jp_vocab where id = '8d38fecd-584f-4e67-a200-664647b10128';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"西洋化する" đọc là gì?', 'がっかりする', 'りこんする', 'せいようかする', 'あんしんする', 'せいようかする', 'generated' from jp_vocab where id = '8d38fecd-584f-4e67-a200-664647b10128';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 日本の食生活が_____。', NULL, NULL, NULL, NULL, '西洋化する', 'generated' from jp_vocab where id = '8d38fecd-584f-4e67-a200-664647b10128';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"びっくりする" có nghĩa là gì?', 'giật mình', 'bẩn', 'xấu hổ', 'cứng', 'giật mình', 'generated' from jp_vocab where id = 'e6c37ab8-1d24-459b-a257-9b1a48abc353';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "giật mình"?', '太る', 'がっかりする', '柔らかい', 'びっくりする', 'びっくりする', 'generated' from jp_vocab where id = 'e6c37ab8-1d24-459b-a257-9b1a48abc353';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"びっくりする" đọc là gì?', 'あんしんする', 'がっかりする', 'びっくりする', 'じゃま', 'びっくりする', 'generated' from jp_vocab where id = 'e6c37ab8-1d24-459b-a257-9b1a48abc353';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 大きな音に_____。', NULL, NULL, NULL, NULL, 'びっくりする', 'generated' from jp_vocab where id = 'e6c37ab8-1d24-459b-a257-9b1a48abc353';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"がっかりする" có nghĩa là gì?', 'yên tâm', 'thất vọng', 'vướng, vướng víu', 'buồn', 'thất vọng', 'generated' from jp_vocab where id = '3e2e2ee0-ba4c-4008-bafc-ddfd33088ed0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thất vọng"?', '悲しい', '安心する', '太る', 'がっかりする', 'がっかりする', 'generated' from jp_vocab where id = '3e2e2ee0-ba4c-4008-bafc-ddfd33088ed0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"がっかりする" đọc là gì?', 'きたない', 'がっかりする', 'おとな', 'びっくりする', 'がっかりする', 'generated' from jp_vocab where id = '3e2e2ee0-ba4c-4008-bafc-ddfd33088ed0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 試験に落ちて_____。', NULL, NULL, NULL, NULL, 'がっかりする', 'generated' from jp_vocab where id = '3e2e2ee0-ba4c-4008-bafc-ddfd33088ed0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"安心する" có nghĩa là gì?', 'buồn', 'yên tâm', 'thất vọng', 'giật mình', 'yên tâm', 'generated' from jp_vocab where id = '49fb3097-f47f-48cc-bb3a-2de2f321c1f0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "yên tâm"?', '悲しい', '安心する', '太る', '硬い', '安心する', 'generated' from jp_vocab where id = '49fb3097-f47f-48cc-bb3a-2de2f321c1f0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"安心する" đọc là gì?', 'きたない', 'あんしんする', 'けんかする', 'ふとる', 'あんしんする', 'generated' from jp_vocab where id = '49fb3097-f47f-48cc-bb3a-2de2f321c1f0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 連絡をもらって_____。', NULL, NULL, NULL, NULL, '安心する', 'generated' from jp_vocab where id = '49fb3097-f47f-48cc-bb3a-2de2f321c1f0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"喧嘩する" có nghĩa là gì?', 'cãi nhau', 'béo ra', 'ly hôn', 'người lớn', 'cãi nhau', 'generated' from jp_vocab where id = '3059cd35-20c4-4985-a3f4-fd484279f5a0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cãi nhau"?', '恥ずかしい', '喧嘩する', '離婚する', 'びっくりする', '喧嘩する', 'generated' from jp_vocab where id = '3059cd35-20c4-4985-a3f4-fd484279f5a0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"喧嘩する" đọc là gì?', 'けんかする', 'じゃま', 'りこんする', 'せいようかする', 'けんかする', 'generated' from jp_vocab where id = '3059cd35-20c4-4985-a3f4-fd484279f5a0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 兄弟と_____。', NULL, NULL, NULL, NULL, '喧嘩する', 'generated' from jp_vocab where id = '3059cd35-20c4-4985-a3f4-fd484279f5a0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"離婚する" có nghĩa là gì?', 'giật mình', 'chết', '(tòa nhà) đổ/ (người) ngất', 'ly hôn', 'ly hôn', 'generated' from jp_vocab where id = '69691f91-16f1-4a76-9b41-7e4aa8dd7d30';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "ly hôn"?', '安心する', '硬い', '痩せる', '離婚する', '離婚する', 'generated' from jp_vocab where id = '69691f91-16f1-4a76-9b41-7e4aa8dd7d30';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"離婚する" đọc là gì?', 'こたえる', 'びっくりする', 'りこんする', 'たおれる', 'りこんする', 'generated' from jp_vocab where id = '69691f91-16f1-4a76-9b41-7e4aa8dd7d30';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 二人は_____た。', NULL, NULL, NULL, NULL, '離婚し', 'generated' from jp_vocab where id = '69691f91-16f1-4a76-9b41-7e4aa8dd7d30';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"太る" có nghĩa là gì?', 'béo ra', 'cãi nhau', 'bẩn', 'đi (xuyên) qua (đường)', 'béo ra', 'generated' from jp_vocab where id = 'b940bcdf-139c-4a38-b84b-e8883a866088';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "béo ra"?', '太る', '死ぬ', '恥ずかしい', 'びっくりする', '太る', 'generated' from jp_vocab where id = 'b940bcdf-139c-4a38-b84b-e8883a866088';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"太る" đọc là gì?', 'ふくざつ', 'こたえる', 'じゃま', 'ふとる', 'ふとる', 'generated' from jp_vocab where id = 'b940bcdf-139c-4a38-b84b-e8883a866088';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 最近_____た。', NULL, NULL, NULL, NULL, '太っ', 'generated' from jp_vocab where id = 'b940bcdf-139c-4a38-b84b-e8883a866088';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"痩せる" có nghĩa là gì?', 'Tây Âu hóa', 'trả lời (câu hỏi)', 'người lớn', 'gầy đi', 'gầy đi', 'generated' from jp_vocab where id = '3986fca1-e588-487e-a85f-d18ff6fead36';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "gầy đi"?', 'がっかりする', '太る', '悲しい', '痩せる', '痩せる', 'generated' from jp_vocab where id = '3986fca1-e588-487e-a85f-d18ff6fead36';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"痩せる" đọc là gì?', 'かなしい', 'やせる', 'りこんする', 'ふとる', 'やせる', 'generated' from jp_vocab where id = '3986fca1-e588-487e-a85f-d18ff6fead36';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: ダイエットして_____た。', NULL, NULL, NULL, NULL, '痩せ', 'generated' from jp_vocab where id = '3986fca1-e588-487e-a85f-d18ff6fead36';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"複雑" có nghĩa là gì?', '(tòa nhà) đổ/ (người) ngất', 'phức tạp', 'cãi nhau', 'bẩn', 'phức tạp', 'generated' from jp_vocab where id = 'b6013c87-0d23-495a-831b-9f284bd45c8b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phức tạp"?', '西洋化する', '複雑', '安心する', '大人', '複雑', 'generated' from jp_vocab where id = 'b6013c87-0d23-495a-831b-9f284bd45c8b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"複雑" đọc là gì?', 'はずかしい', 'せいようかする', 'じゃま', 'ふくざつ', 'ふくざつ', 'generated' from jp_vocab where id = 'b6013c87-0d23-495a-831b-9f284bd45c8b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: この問題は_____だ。', NULL, NULL, NULL, NULL, '複雑', 'generated' from jp_vocab where id = 'b6013c87-0d23-495a-831b-9f284bd45c8b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"邪魔" có nghĩa là gì?', 'bẩn', 'người lớn', 'vướng, vướng víu', 'gầy đi', 'vướng, vướng víu', 'generated' from jp_vocab where id = '974f18a2-0cd8-4e3a-8c59-84eb28d6a107';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vướng, vướng víu"?', 'がっかりする', '邪魔', '硬い', '柔らかい', '邪魔', 'generated' from jp_vocab where id = '974f18a2-0cd8-4e3a-8c59-84eb28d6a107';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"邪魔" đọc là gì?', 'ふとる', 'じゃま', 'やせる', 'かたい', 'じゃま', 'generated' from jp_vocab where id = '974f18a2-0cd8-4e3a-8c59-84eb28d6a107';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 荷物が_____だ。', NULL, NULL, NULL, NULL, '邪魔', 'generated' from jp_vocab where id = '974f18a2-0cd8-4e3a-8c59-84eb28d6a107';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"硬い" có nghĩa là gì?', 'béo ra', 'gầy đi', 'cãi nhau', 'cứng', 'cứng', 'generated' from jp_vocab where id = 'd9ee9dd7-e8bc-4860-9ce9-1ab77a363e94';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cứng"?', '倒れる', '恥ずかしい', '西洋化する', '硬い', '硬い', 'generated' from jp_vocab where id = 'd9ee9dd7-e8bc-4860-9ce9-1ab77a363e94';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"硬い" đọc là gì?', 'かなしい', 'はずかしい', 'かたい', 'やわらかい', 'かたい', 'generated' from jp_vocab where id = 'd9ee9dd7-e8bc-4860-9ce9-1ab77a363e94';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: このパンは_____。', NULL, NULL, NULL, NULL, '硬い', 'generated' from jp_vocab where id = 'd9ee9dd7-e8bc-4860-9ce9-1ab77a363e94';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"柔らかい" có nghĩa là gì?', 'mềm', 'người lớn', 'béo ra', 'yên tâm', 'mềm', 'generated' from jp_vocab where id = 'b6a31387-1e97-4214-8218-2898574d77fc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "mềm"?', '大人', '死ぬ', '汚い', '柔らかい', '柔らかい', 'generated' from jp_vocab where id = 'b6a31387-1e97-4214-8218-2898574d77fc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"柔らかい" đọc là gì?', 'とおる', 'やわらかい', 'きたない', 'あんしんする', 'やわらかい', 'generated' from jp_vocab where id = 'b6a31387-1e97-4214-8218-2898574d77fc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____ベッドで寝る。', NULL, NULL, NULL, NULL, '柔らかい', 'generated' from jp_vocab where id = 'b6a31387-1e97-4214-8218-2898574d77fc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"汚い" có nghĩa là gì?', 'gầy đi', 'bẩn', 'trả lời (câu hỏi)', 'mềm', 'bẩn', 'generated' from jp_vocab where id = 'b75f5c8f-75d8-4993-8d50-f02bb49ead49';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "bẩn"?', '複雑', '汚い', '答える', '痩せる', '汚い', 'generated' from jp_vocab where id = 'b75f5c8f-75d8-4993-8d50-f02bb49ead49';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"汚い" đọc là gì?', 'きたない', 'びっくりする', 'かたい', 'おとな', 'きたない', 'generated' from jp_vocab where id = 'b75f5c8f-75d8-4993-8d50-f02bb49ead49';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 部屋が_____。', NULL, NULL, NULL, NULL, '汚い', 'generated' from jp_vocab where id = 'b75f5c8f-75d8-4993-8d50-f02bb49ead49';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"悲しい" có nghĩa là gì?', 'phức tạp', 'buồn', '(tòa nhà) đổ/ (người) ngất', 'trả lời (câu hỏi)', 'buồn', 'generated' from jp_vocab where id = 'b53e68ef-87d6-47db-8a54-41d193143856';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "buồn"?', '汚い', '安心する', '西洋化する', '悲しい', '悲しい', 'generated' from jp_vocab where id = 'b53e68ef-87d6-47db-8a54-41d193143856';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"悲しい" đọc là gì?', 'けんかする', 'しぬ', 'かたい', 'かなしい', 'かなしい', 'generated' from jp_vocab where id = 'b53e68ef-87d6-47db-8a54-41d193143856';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 別れて_____。', NULL, NULL, NULL, NULL, '悲しい', 'generated' from jp_vocab where id = 'b53e68ef-87d6-47db-8a54-41d193143856';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"恥ずかしい" có nghĩa là gì?', 'gầy đi', 'Tây Âu hóa', 'xấu hổ', 'yên tâm', 'xấu hổ', 'generated' from jp_vocab where id = '1482fbd5-077b-40f1-a19b-692e159a5abf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "xấu hổ"?', '死ぬ', '離婚する', '恥ずかしい', '汚い', '恥ずかしい', 'generated' from jp_vocab where id = '1482fbd5-077b-40f1-a19b-692e159a5abf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"恥ずかしい" đọc là gì?', 'はずかしい', 'りこんする', 'がっかりする', 'びっくりする', 'はずかしい', 'generated' from jp_vocab where id = '1482fbd5-077b-40f1-a19b-692e159a5abf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 間違えて_____。', NULL, NULL, NULL, NULL, '恥ずかしい', 'generated' from jp_vocab where id = '1482fbd5-077b-40f1-a19b-692e159a5abf';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"大人" có nghĩa là gì?', 'yên tâm', 'gầy đi', 'người lớn', 'vướng, vướng víu', 'người lớn', 'generated' from jp_vocab where id = '74033ba4-6cba-4231-9172-c133c7ff1710';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "người lớn"?', '汚い', '痩せる', '悲しい', '大人', '大人', 'generated' from jp_vocab where id = '74033ba4-6cba-4231-9172-c133c7ff1710';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"大人" đọc là gì?', 'けんかする', 'おとな', 'がっかりする', 'たおれる', 'おとな', 'generated' from jp_vocab where id = '74033ba4-6cba-4231-9172-c133c7ff1710';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____になる。', NULL, NULL, NULL, NULL, '大人', 'generated' from jp_vocab where id = '74033ba4-6cba-4231-9172-c133c7ff1710';
