-- ============================================================
-- jp-go — Từ vựng N4, 課40 (phần 1, 23 từ đầu).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 29.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b3ee21e4-c4f2-460a-bd46-b72448cfd01c', 'N4', 40, 'word', '数える', 'かぞえる', 'đếm', NULL, '動詞', 29, '数える', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('64631b45-1eb5-4608-8bbf-031fa4f42946', 'N4', 40, 'word', '測る・量る', 'はかる', 'đo, cân', NULL, '動詞', 29, '測る・量る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e9587bc8-f30f-4e98-851a-65a47bf23558', 'N4', 40, 'word', '確かめる', 'たしかめる', 'xác nhận', NULL, '動詞', 29, '確かめる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('24751d4c-4da5-474d-bc95-72d3b3ead787', 'N4', 40, 'word', '合う', 'あう', 'vừa, phù hợp (cỡ)', 'thường dùng dạng [サイズが〜]', '動詞', 29, '合う', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('056fd1d1-7499-4d94-b7cc-4c87c285f5b0', 'N4', 40, 'word', '出発する', 'しゅっぱつする', 'xuất phát', NULL, '動詞', 29, '出発する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7093c182-5f2f-4f2f-816f-41b773f0beaa', 'N4', 40, 'word', '到着する', 'とうちゃくする', 'đến nơi', NULL, '動詞', 29, '到着する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('1a188dff-79ea-413b-bbdc-8d99c14243cd', 'N4', 40, 'word', '酔う', 'よう', 'say (rượu)', NULL, '動詞', 29, '酔う', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('2ea90890-efb5-4dd5-a452-5a6b8343e3ef', 'N4', 40, 'word', 'うまくいく', 'うまくいく', 'thuận lợi', NULL, '動詞', 29, 'うまくいく', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('5c57728b-b1d3-43a5-b4b4-05e42d649df6', 'N4', 40, 'word', '相談する', 'そうだんする', 'nói chuyện, thảo luận', NULL, '動詞', 29, '相談する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('81013cc4-92fb-495e-99d8-f992709e65eb', 'N4', 40, 'word', '動かす', 'うごかす', 'di chuyển', NULL, '動詞', 29, '動かす', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('08b28ec7-d9be-4ec1-b7ba-2ba4ca666b80', 'N4', 40, 'word', 'コンテスト', 'コンテスト', 'cuộc thi', NULL, '名詞', 29, 'コンテスト', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('84a10c05-b817-4eb9-82d1-4a7e89d0abc1', 'N4', 40, 'word', '天気予報', 'てんきよほう', 'dự báo thời tiết', NULL, '名詞', 29, '天気予報', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7b9ce4f1-2e85-494d-8b81-d55b00c37f5d', 'N4', 40, 'word', '爆弾', 'ばくだん', 'bom', NULL, '名詞', 29, '爆弾', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('71da4655-9090-4c06-b59b-fc9ca3d43e85', 'N4', 40, 'word', '急に', 'きゅうに', 'đột nhiên', NULL, '副詞', 29, '急に', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('9e0457cd-0458-4113-87a3-dbbc09a25b79', 'N4', 40, 'word', '発表会', 'はっぴょうかい', 'buổi phát biểu', NULL, '名詞', 29, '発表会', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('bf24e8ca-96c7-4585-b6f5-c043b40027ee', 'N4', 40, 'word', '大会', 'たいかい', 'cuộc thi, hội thi', NULL, '名詞', 29, '大会', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('89a8ef40-8fa1-40d4-bfb4-001911b568e1', 'N4', 40, 'word', '表', 'おもて', 'mặt phải, mặt trước', NULL, '名詞', 29, '表', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('cb00107c-40ff-4606-a26a-a533d8aa9a3a', 'N4', 40, 'word', '裏', 'うら', 'mặt trái, mặt sau', NULL, '名詞', 29, '裏', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7d475108-1f94-4b84-8ac5-502400348c07', 'N4', 40, 'word', '間違い', 'まちがい', 'sai sót', NULL, '名詞', 29, '間違い', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('4519c7d4-2e3a-4f64-8fdf-4471c745c04c', 'N4', 40, 'word', '傷', 'きず', 'vết xước, vết trầy, vết thương', NULL, '名詞', 29, '傷', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('75b3d14f-b2d3-4e95-a74d-8b6964389f1b', 'N4', 40, 'word', 'ズボン', 'ズボン', 'quần', NULL, '名詞', 29, 'ズボン', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('09d727ab-3a4b-4c88-866d-0e684d7b082d', 'N4', 40, 'word', '年寄り', 'としより', 'người già, người cao tuổi', NULL, '名詞', 29, '年寄り', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3346b1bc-221b-4f92-b8c3-331c50f17c53', 'N4', 40, 'word', '長さ', 'ながさ', 'chiều dài', NULL, '名詞', 29, '長さ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '人数を数える。', 'Đếm số người.', '人数を_____。', '数える', 'generated' from jp_vocab where id = 'b3ee21e4-c4f2-460a-bd46-b72448cfd01c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '体重を量る。', 'Cân trọng lượng cơ thể.', '体重を_____。', '量る', 'generated' from jp_vocab where id = '64631b45-1eb5-4608-8bbf-031fa4f42946';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '予定を確かめる。', 'Xác nhận lịch trình.', '予定を_____。', '確かめる', 'generated' from jp_vocab where id = 'e9587bc8-f30f-4e98-851a-65a47bf23558';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'このサイズが合う。', 'Cỡ này vừa.', 'このサイズが_____。', '合う', 'generated' from jp_vocab where id = '24751d4c-4da5-474d-bc95-72d3b3ead787';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '朝早く出発する。', 'Xuất phát từ sáng sớm.', '朝早く_____。', '出発する', 'generated' from jp_vocab where id = '056fd1d1-7499-4d94-b7cc-4c87c285f5b0';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '空港に到着する。', 'Đến sân bay.', '空港に_____。', '到着する', 'generated' from jp_vocab where id = '7093c182-5f2f-4f2f-816f-41b773f0beaa';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お酒に酔う。', 'Say rượu.', 'お酒に_____。', '酔う', 'generated' from jp_vocab where id = '1a188dff-79ea-413b-bbdc-8d99c14243cd';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '仕事がうまくいく。', 'Công việc thuận lợi.', '仕事が_____。', 'うまくいく', 'generated' from jp_vocab where id = '2ea90890-efb5-4dd5-a452-5a6b8343e3ef';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '先生に相談する。', 'Thảo luận với thầy/cô.', '先生に_____。', '相談する', 'generated' from jp_vocab where id = '5c57728b-b1d3-43a5-b4b4-05e42d649df6';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '机を動かす。', 'Di chuyển cái bàn.', '机を_____。', '動かす', 'generated' from jp_vocab where id = '81013cc4-92fb-495e-99d8-f992709e65eb';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'スピーチコンテストに出る。', 'Tham gia cuộc thi diễn văn.', 'スピーチ_____に出る。', 'コンテスト', 'generated' from jp_vocab where id = '08b28ec7-d9be-4ec1-b7ba-2ba4ca666b80';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '天気予報を見る。', 'Xem dự báo thời tiết.', '_____を見る。', '天気予報', 'generated' from jp_vocab where id = '84a10c05-b817-4eb9-82d1-4a7e89d0abc1';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '爆弾が見つかった。', 'Đã tìm thấy quả bom.', '_____が見つかった。', '爆弾', 'generated' from jp_vocab where id = '7b9ce4f1-2e85-494d-8b81-d55b00c37f5d';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '急に雨が降った。', 'Trời đột nhiên mưa.', '_____雨が降った。', '急に', 'generated' from jp_vocab where id = '71da4655-9090-4c06-b59b-fc9ca3d43e85';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ピアノの発表会がある。', 'Có buổi phát biểu piano.', 'ピアノの_____がある。', '発表会', 'generated' from jp_vocab where id = '9e0457cd-0458-4113-87a3-dbbc09a25b79';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'スポーツ大会に出る。', 'Tham gia hội thi thể thao.', 'スポーツ_____に出る。', '大会', 'generated' from jp_vocab where id = 'bf24e8ca-96c7-4585-b6f5-c043b40027ee';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '紙の表に書く。', 'Viết vào mặt phải của tờ giấy.', '紙の_____に書く。', '表', 'generated' from jp_vocab where id = '89a8ef40-8fa1-40d4-bfb4-001911b568e1';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '紙の裏に書く。', 'Viết vào mặt sau của tờ giấy.', '紙の_____に書く。', '裏', 'generated' from jp_vocab where id = 'cb00107c-40ff-4606-a26a-a533d8aa9a3a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '間違いを直す。', 'Sửa sai sót.', '_____を直す。', '間違い', 'generated' from jp_vocab where id = '7d475108-1f94-4b84-8ac5-502400348c07';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '傷ができた。', 'Đã có vết thương.', '_____ができた。', '傷', 'generated' from jp_vocab where id = '4519c7d4-2e3a-4f64-8fdf-4471c745c04c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ズボンをはく。', 'Mặc quần.', '_____をはく。', 'ズボン', 'generated' from jp_vocab where id = '75b3d14f-b2d3-4e95-a74d-8b6964389f1b';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '年寄りに席を譲る。', 'Nhường ghế cho người già.', '_____に席を譲る。', '年寄り', 'generated' from jp_vocab where id = '09d727ab-3a4b-4c88-866d-0e684d7b082d';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'この紐の長さを測る。', 'Đo chiều dài của sợi dây này.', 'この紐の_____を測る。', '長さ', 'generated' from jp_vocab where id = '3346b1bc-221b-4f92-b8c3-331c50f17c53';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"数える" có nghĩa là gì?', 'sai sót', 'buổi phát biểu', 'đếm', 'xuất phát', 'đếm', 'generated' from jp_vocab where id = 'b3ee21e4-c4f2-460a-bd46-b72448cfd01c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đếm"?', '数える', '測る・量る', '合う', '傷', '数える', 'generated' from jp_vocab where id = 'b3ee21e4-c4f2-460a-bd46-b72448cfd01c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"数える" đọc là gì?', 'かぞえる', 'ながさ', 'きゅうに', 'よう', 'かぞえる', 'generated' from jp_vocab where id = 'b3ee21e4-c4f2-460a-bd46-b72448cfd01c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 人数を_____。', NULL, NULL, NULL, NULL, '数える', 'generated' from jp_vocab where id = 'b3ee21e4-c4f2-460a-bd46-b72448cfd01c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"測る・量る" có nghĩa là gì?', 'đo, cân', 'đếm', 'mặt phải, mặt trước', 'mặt trái, mặt sau', 'đo, cân', 'generated' from jp_vocab where id = '64631b45-1eb5-4608-8bbf-031fa4f42946';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đo, cân"?', '動かす', '測る・量る', '年寄り', '大会', '測る・量る', 'generated' from jp_vocab where id = '64631b45-1eb5-4608-8bbf-031fa4f42946';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"測る・量る" đọc là gì?', 'ズボン', 'はかる', 'しゅっぱつする', 'うまくいく', 'はかる', 'generated' from jp_vocab where id = '64631b45-1eb5-4608-8bbf-031fa4f42946';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 体重を_____。', NULL, NULL, NULL, NULL, '量る', 'generated' from jp_vocab where id = '64631b45-1eb5-4608-8bbf-031fa4f42946';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"確かめる" có nghĩa là gì?', 'quần', 'vết xước, vết trầy, vết thương', 'bom', 'xác nhận', 'xác nhận', 'generated' from jp_vocab where id = 'e9587bc8-f30f-4e98-851a-65a47bf23558';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "xác nhận"?', '合う', '確かめる', '急に', '相談する', '確かめる', 'generated' from jp_vocab where id = 'e9587bc8-f30f-4e98-851a-65a47bf23558';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"確かめる" đọc là gì?', 'ながさ', 'はかる', 'とうちゃくする', 'たしかめる', 'たしかめる', 'generated' from jp_vocab where id = 'e9587bc8-f30f-4e98-851a-65a47bf23558';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 予定を_____。', NULL, NULL, NULL, NULL, '確かめる', 'generated' from jp_vocab where id = 'e9587bc8-f30f-4e98-851a-65a47bf23558';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"合う" có nghĩa là gì?', 'say (rượu)', 'mặt phải, mặt trước', 'vừa, phù hợp (cỡ)', 'quần', 'vừa, phù hợp (cỡ)', 'generated' from jp_vocab where id = '24751d4c-4da5-474d-bc95-72d3b3ead787';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vừa, phù hợp (cỡ)"?', '合う', 'コンテスト', '動かす', '相談する', '合う', 'generated' from jp_vocab where id = '24751d4c-4da5-474d-bc95-72d3b3ead787';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"合う" đọc là gì?', 'ながさ', 'あう', 'はっぴょうかい', 'しゅっぱつする', 'あう', 'generated' from jp_vocab where id = '24751d4c-4da5-474d-bc95-72d3b3ead787';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: このサイズが_____。', NULL, NULL, NULL, NULL, '合う', 'generated' from jp_vocab where id = '24751d4c-4da5-474d-bc95-72d3b3ead787';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"出発する" có nghĩa là gì?', 'chiều dài', 'xuất phát', 'đo, cân', 'vừa, phù hợp (cỡ)', 'xuất phát', 'generated' from jp_vocab where id = '056fd1d1-7499-4d94-b7cc-4c87c285f5b0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "xuất phát"?', '合う', '測る・量る', '出発する', '発表会', '出発する', 'generated' from jp_vocab where id = '056fd1d1-7499-4d94-b7cc-4c87c285f5b0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"出発する" đọc là gì?', 'たいかい', 'うごかす', 'ばくだん', 'しゅっぱつする', 'しゅっぱつする', 'generated' from jp_vocab where id = '056fd1d1-7499-4d94-b7cc-4c87c285f5b0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 朝早く_____。', NULL, NULL, NULL, NULL, '出発する', 'generated' from jp_vocab where id = '056fd1d1-7499-4d94-b7cc-4c87c285f5b0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"到着する" có nghĩa là gì?', 'đến nơi', 'quần', 'dự báo thời tiết', 'chiều dài', 'đến nơi', 'generated' from jp_vocab where id = '7093c182-5f2f-4f2f-816f-41b773f0beaa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đến nơi"?', '発表会', '到着する', '急に', '数える', '到着する', 'generated' from jp_vocab where id = '7093c182-5f2f-4f2f-816f-41b773f0beaa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"到着する" đọc là gì?', 'あう', 'たいかい', 'とうちゃくする', 'てんきよほう', 'とうちゃくする', 'generated' from jp_vocab where id = '7093c182-5f2f-4f2f-816f-41b773f0beaa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 空港に_____。', NULL, NULL, NULL, NULL, '到着する', 'generated' from jp_vocab where id = '7093c182-5f2f-4f2f-816f-41b773f0beaa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"酔う" có nghĩa là gì?', 'say (rượu)', 'bom', 'xuất phát', 'chiều dài', 'say (rượu)', 'generated' from jp_vocab where id = '1a188dff-79ea-413b-bbdc-8d99c14243cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "say (rượu)"?', '酔う', '出発する', '動かす', '急に', '酔う', 'generated' from jp_vocab where id = '1a188dff-79ea-413b-bbdc-8d99c14243cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"酔う" đọc là gì?', 'ながさ', 'かぞえる', 'ズボン', 'よう', 'よう', 'generated' from jp_vocab where id = '1a188dff-79ea-413b-bbdc-8d99c14243cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: お酒に_____。', NULL, NULL, NULL, NULL, '酔う', 'generated' from jp_vocab where id = '1a188dff-79ea-413b-bbdc-8d99c14243cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"うまくいく" có nghĩa là gì?', 'thuận lợi', 'dự báo thời tiết', 'mặt trái, mặt sau', 'vừa, phù hợp (cỡ)', 'thuận lợi', 'generated' from jp_vocab where id = '2ea90890-efb5-4dd5-a452-5a6b8343e3ef';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thuận lợi"?', '天気予報', 'うまくいく', '傷', '確かめる', 'うまくいく', 'generated' from jp_vocab where id = '2ea90890-efb5-4dd5-a452-5a6b8343e3ef';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"うまくいく" đọc là gì?', 'うまくいく', 'としより', 'きず', 'ながさ', 'うまくいく', 'generated' from jp_vocab where id = '2ea90890-efb5-4dd5-a452-5a6b8343e3ef';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 仕事が_____。', NULL, NULL, NULL, NULL, 'うまくいく', 'generated' from jp_vocab where id = '2ea90890-efb5-4dd5-a452-5a6b8343e3ef';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"相談する" có nghĩa là gì?', 'nói chuyện, thảo luận', 'đo, cân', 'thuận lợi', 'người già, người cao tuổi', 'nói chuyện, thảo luận', 'generated' from jp_vocab where id = '5c57728b-b1d3-43a5-b4b4-05e42d649df6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nói chuyện, thảo luận"?', 'コンテスト', '年寄り', '相談する', '天気予報', '相談する', 'generated' from jp_vocab where id = '5c57728b-b1d3-43a5-b4b4-05e42d649df6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"相談する" đọc là gì?', 'あう', 'おもて', 'うごかす', 'そうだんする', 'そうだんする', 'generated' from jp_vocab where id = '5c57728b-b1d3-43a5-b4b4-05e42d649df6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 先生に_____。', NULL, NULL, NULL, NULL, '相談する', 'generated' from jp_vocab where id = '5c57728b-b1d3-43a5-b4b4-05e42d649df6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"動かす" có nghĩa là gì?', 'xuất phát', 'bom', 'di chuyển', 'nói chuyện, thảo luận', 'di chuyển', 'generated' from jp_vocab where id = '81013cc4-92fb-495e-99d8-f992709e65eb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "di chuyển"?', '合う', '出発する', '動かす', '測る・量る', '動かす', 'generated' from jp_vocab where id = '81013cc4-92fb-495e-99d8-f992709e65eb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"動かす" đọc là gì?', 'ながさ', 'ばくだん', 'うごかす', 'しゅっぱつする', 'うごかす', 'generated' from jp_vocab where id = '81013cc4-92fb-495e-99d8-f992709e65eb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 机を_____。', NULL, NULL, NULL, NULL, '動かす', 'generated' from jp_vocab where id = '81013cc4-92fb-495e-99d8-f992709e65eb';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"コンテスト" có nghĩa là gì?', 'đột nhiên', 'cuộc thi', 'xuất phát', 'cuộc thi, hội thi', 'cuộc thi', 'generated' from jp_vocab where id = '08b28ec7-d9be-4ec1-b7ba-2ba4ca666b80';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cuộc thi"?', '傷', '大会', 'コンテスト', '相談する', 'コンテスト', 'generated' from jp_vocab where id = '08b28ec7-d9be-4ec1-b7ba-2ba4ca666b80';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"コンテスト" đọc là gì?', 'コンテスト', 'ばくだん', 'よう', 'としより', 'コンテスト', 'generated' from jp_vocab where id = '08b28ec7-d9be-4ec1-b7ba-2ba4ca666b80';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: スピーチ_____に出る。', NULL, NULL, NULL, NULL, 'コンテスト', 'generated' from jp_vocab where id = '08b28ec7-d9be-4ec1-b7ba-2ba4ca666b80';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"天気予報" có nghĩa là gì?', 'chiều dài', 'buổi phát biểu', 'di chuyển', 'dự báo thời tiết', 'dự báo thời tiết', 'generated' from jp_vocab where id = '84a10c05-b817-4eb9-82d1-4a7e89d0abc1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "dự báo thời tiết"?', '天気予報', 'コンテスト', '裏', '測る・量る', '天気予報', 'generated' from jp_vocab where id = '84a10c05-b817-4eb9-82d1-4a7e89d0abc1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"天気予報" đọc là gì?', 'てんきよほう', 'うごかす', 'まちがい', 'おもて', 'てんきよほう', 'generated' from jp_vocab where id = '84a10c05-b817-4eb9-82d1-4a7e89d0abc1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を見る。', NULL, NULL, NULL, NULL, '天気予報', 'generated' from jp_vocab where id = '84a10c05-b817-4eb9-82d1-4a7e89d0abc1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"爆弾" có nghĩa là gì?', 'bom', 'say (rượu)', 'sai sót', 'cuộc thi', 'bom', 'generated' from jp_vocab where id = '7b9ce4f1-2e85-494d-8b81-d55b00c37f5d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "bom"?', '爆弾', '測る・量る', '到着する', '出発する', '爆弾', 'generated' from jp_vocab where id = '7b9ce4f1-2e85-494d-8b81-d55b00c37f5d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"爆弾" đọc là gì?', 'ばくだん', 'てんきよほう', 'とうちゃくする', 'しゅっぱつする', 'ばくだん', 'generated' from jp_vocab where id = '7b9ce4f1-2e85-494d-8b81-d55b00c37f5d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が見つかった。', NULL, NULL, NULL, NULL, '爆弾', 'generated' from jp_vocab where id = '7b9ce4f1-2e85-494d-8b81-d55b00c37f5d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"急に" có nghĩa là gì?', 'cuộc thi, hội thi', 'di chuyển', 'đột nhiên', 'người già, người cao tuổi', 'đột nhiên', 'generated' from jp_vocab where id = '71da4655-9090-4c06-b59b-fc9ca3d43e85';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đột nhiên"?', '出発する', '発表会', 'うまくいく', '急に', '急に', 'generated' from jp_vocab where id = '71da4655-9090-4c06-b59b-fc9ca3d43e85';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"急に" đọc là gì?', 'おもて', 'まちがい', 'うまくいく', 'きゅうに', 'きゅうに', 'generated' from jp_vocab where id = '71da4655-9090-4c06-b59b-fc9ca3d43e85';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____雨が降った。', NULL, NULL, NULL, NULL, '急に', 'generated' from jp_vocab where id = '71da4655-9090-4c06-b59b-fc9ca3d43e85';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"発表会" có nghĩa là gì?', 'cuộc thi', 'mặt phải, mặt trước', 'buổi phát biểu', 'di chuyển', 'buổi phát biểu', 'generated' from jp_vocab where id = '9e0457cd-0458-4113-87a3-dbbc09a25b79';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "buổi phát biểu"?', '発表会', '合う', '裏', '相談する', '発表会', 'generated' from jp_vocab where id = '9e0457cd-0458-4113-87a3-dbbc09a25b79';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"発表会" đọc là gì?', 'はっぴょうかい', 'ばくだん', 'はかる', 'うら', 'はっぴょうかい', 'generated' from jp_vocab where id = '9e0457cd-0458-4113-87a3-dbbc09a25b79';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: ピアノの_____がある。', NULL, NULL, NULL, NULL, '発表会', 'generated' from jp_vocab where id = '9e0457cd-0458-4113-87a3-dbbc09a25b79';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"大会" có nghĩa là gì?', 'đếm', 'mặt phải, mặt trước', 'say (rượu)', 'cuộc thi, hội thi', 'cuộc thi, hội thi', 'generated' from jp_vocab where id = 'bf24e8ca-96c7-4585-b6f5-c043b40027ee';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cuộc thi, hội thi"?', '表', '大会', '急に', '出発する', '大会', 'generated' from jp_vocab where id = 'bf24e8ca-96c7-4585-b6f5-c043b40027ee';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"大会" đọc là gì?', 'おもて', 'まちがい', 'たいかい', 'はっぴょうかい', 'たいかい', 'generated' from jp_vocab where id = 'bf24e8ca-96c7-4585-b6f5-c043b40027ee';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: スポーツ_____に出る。', NULL, NULL, NULL, NULL, '大会', 'generated' from jp_vocab where id = 'bf24e8ca-96c7-4585-b6f5-c043b40027ee';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"表" có nghĩa là gì?', 'say (rượu)', 'đến nơi', 'chiều dài', 'mặt phải, mặt trước', 'mặt phải, mặt trước', 'generated' from jp_vocab where id = '89a8ef40-8fa1-40d4-bfb4-001911b568e1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "mặt phải, mặt trước"?', '間違い', '表', '測る・量る', '動かす', '表', 'generated' from jp_vocab where id = '89a8ef40-8fa1-40d4-bfb4-001911b568e1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"表" đọc là gì?', 'あう', 'おもて', 'そうだんする', 'はかる', 'おもて', 'generated' from jp_vocab where id = '89a8ef40-8fa1-40d4-bfb4-001911b568e1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 紙の_____に書く。', NULL, NULL, NULL, NULL, '表', 'generated' from jp_vocab where id = '89a8ef40-8fa1-40d4-bfb4-001911b568e1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"裏" có nghĩa là gì?', 'mặt trái, mặt sau', 'chiều dài', 'đột nhiên', 'sai sót', 'mặt trái, mặt sau', 'generated' from jp_vocab where id = 'cb00107c-40ff-4606-a26a-a533d8aa9a3a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "mặt trái, mặt sau"?', '傷', '裏', 'ズボン', 'うまくいく', '裏', 'generated' from jp_vocab where id = 'cb00107c-40ff-4606-a26a-a533d8aa9a3a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"裏" đọc là gì?', 'うら', 'かぞえる', 'ばくだん', 'ズボン', 'うら', 'generated' from jp_vocab where id = 'cb00107c-40ff-4606-a26a-a533d8aa9a3a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 紙の_____に書く。', NULL, NULL, NULL, NULL, '裏', 'generated' from jp_vocab where id = 'cb00107c-40ff-4606-a26a-a533d8aa9a3a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"間違い" có nghĩa là gì?', 'thuận lợi', 'sai sót', 'xuất phát', 'đo, cân', 'sai sót', 'generated' from jp_vocab where id = '7d475108-1f94-4b84-8ac5-502400348c07';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sai sót"?', 'ズボン', '動かす', '間違い', '爆弾', '間違い', 'generated' from jp_vocab where id = '7d475108-1f94-4b84-8ac5-502400348c07';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"間違い" đọc là gì?', 'しゅっぱつする', 'ズボン', 'まちがい', 'たしかめる', 'まちがい', 'generated' from jp_vocab where id = '7d475108-1f94-4b84-8ac5-502400348c07';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を直す。', NULL, NULL, NULL, NULL, '間違い', 'generated' from jp_vocab where id = '7d475108-1f94-4b84-8ac5-502400348c07';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"傷" có nghĩa là gì?', 'vừa, phù hợp (cỡ)', 'đo, cân', 'dự báo thời tiết', 'vết xước, vết trầy, vết thương', 'vết xước, vết trầy, vết thương', 'generated' from jp_vocab where id = '4519c7d4-2e3a-4f64-8fdf-4471c745c04c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vết xước, vết trầy, vết thương"?', '合う', '天気予報', '長さ', '傷', '傷', 'generated' from jp_vocab where id = '4519c7d4-2e3a-4f64-8fdf-4471c745c04c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"傷" đọc là gì?', 'きず', 'ばくだん', 'うごかす', 'よう', 'きず', 'generated' from jp_vocab where id = '4519c7d4-2e3a-4f64-8fdf-4471c745c04c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____ができた。', NULL, NULL, NULL, NULL, '傷', 'generated' from jp_vocab where id = '4519c7d4-2e3a-4f64-8fdf-4471c745c04c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ズボン" có nghĩa là gì?', 'vết xước, vết trầy, vết thương', 'quần', 'thuận lợi', 'đếm', 'quần', 'generated' from jp_vocab where id = '75b3d14f-b2d3-4e95-a74d-8b6964389f1b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "quần"?', '年寄り', '出発する', 'コンテスト', 'ズボン', 'ズボン', 'generated' from jp_vocab where id = '75b3d14f-b2d3-4e95-a74d-8b6964389f1b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ズボン" đọc là gì?', 'そうだんする', 'ズボン', 'うら', 'はかる', 'ズボン', 'generated' from jp_vocab where id = '75b3d14f-b2d3-4e95-a74d-8b6964389f1b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____をはく。', NULL, NULL, NULL, NULL, 'ズボン', 'generated' from jp_vocab where id = '75b3d14f-b2d3-4e95-a74d-8b6964389f1b';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"年寄り" có nghĩa là gì?', 'cuộc thi', 'người già, người cao tuổi', 'đếm', 'vết xước, vết trầy, vết thương', 'người già, người cao tuổi', 'generated' from jp_vocab where id = '09d727ab-3a4b-4c88-866d-0e684d7b082d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "người già, người cao tuổi"?', '合う', '年寄り', '酔う', '動かす', '年寄り', 'generated' from jp_vocab where id = '09d727ab-3a4b-4c88-866d-0e684d7b082d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"年寄り" đọc là gì?', 'たしかめる', 'としより', 'きゅうに', 'よう', 'としより', 'generated' from jp_vocab where id = '09d727ab-3a4b-4c88-866d-0e684d7b082d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に席を譲る。', NULL, NULL, NULL, NULL, '年寄り', 'generated' from jp_vocab where id = '09d727ab-3a4b-4c88-866d-0e684d7b082d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"長さ" có nghĩa là gì?', 'xuất phát', 'nói chuyện, thảo luận', 'cuộc thi', 'chiều dài', 'chiều dài', 'generated' from jp_vocab where id = '3346b1bc-221b-4f92-b8c3-331c50f17c53';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chiều dài"?', '長さ', '相談する', '出発する', '数える', '長さ', 'generated' from jp_vocab where id = '3346b1bc-221b-4f92-b8c3-331c50f17c53';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"長さ" đọc là gì?', 'としより', 'きゅうに', 'おもて', 'ながさ', 'ながさ', 'generated' from jp_vocab where id = '3346b1bc-221b-4f92-b8c3-331c50f17c53';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: この紐の_____を測る。', NULL, NULL, NULL, NULL, '長さ', 'generated' from jp_vocab where id = '3346b1bc-221b-4f92-b8c3-331c50f17c53';
