-- ============================================================
-- jp-go — Từ vựng N4, 課41 (phần 3, 17 từ cuối, hoàn tất 課41).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 30.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d437dc84-aa8d-4ed5-9aa0-98e73db934d5', 'N4', 41, 'word', '叔母さん', 'おばさん', 'cô, dì, bác (của người khác)', NULL, '名詞', 30, '叔母さん', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b85901e1-2c23-4245-b608-0bd330b9ed70', 'N4', 41, 'word', '管理人', 'かんりにん', 'người quản lý', NULL, '名詞', 30, '管理人', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('639bae0d-366a-4bf7-b9d3-79a659eb0221', 'N4', 41, 'word', 'この間', 'このあいだ', 'đợt vừa rồi', NULL, '副詞', 30, 'この間', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('6667e9b7-0d6f-428a-8f10-743da5192f2c', 'N4', 41, 'word', '一言', 'ひとこと', 'đôi lời', NULL, '名詞', 30, '一言', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('1759a234-f943-4b46-82d7-3a8eb5e19e94', 'N4', 41, 'word', 'お宅', 'おたく', 'nhà (kính ngữ của うち；いえ)', NULL, '名詞', 30, 'お宅', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('301c0a4b-0d8d-477a-8fee-7e993c78d7cc', 'N4', 41, 'phrase', 'どうぞお幸せに', 'どうぞおしあわせに', 'Chúc hai người hạnh phúc!', NULL, 'な形容詞', 30, 'どうぞお幸せに', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('150f642a-bdf5-4af8-8931-55e2a243e926', 'N4', 41, 'word', '中身', 'なかみ', 'bên trong, nội dung', NULL, '名詞', 30, '中身', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7262943f-c317-48c6-88b1-49c7cb32b411', 'N4', 41, 'word', '真っ白', 'まっしろ', 'trắng toát', NULL, 'い形容詞', 30, '真っ白', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('c5fd671e-50e9-49c8-a58b-3cf34f8de87a', 'N4', 41, 'word', '素敵な', 'すてきな', 'tuyệt vời', NULL, 'な形容詞', 30, '素敵な', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('f9420e30-a8d1-4103-81ef-a0057fd91c58', 'N4', 41, 'word', '上司', 'じょうし', 'cấp trên', NULL, '名詞', 30, '上司', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3ed75676-207f-425f-9399-9a8af15899e3', 'N4', 41, 'word', 'アルバイト', 'アルバイト', 'làm thêm', NULL, '名詞', 30, 'アルバイト', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('76b4fc5a-b9a0-488c-bf17-45b08ccbdbe2', 'N4', 41, 'word', 'ご馳走', 'ごちそう', 'khao, chiêu đãi', NULL, '名詞', 30, 'ご馳走', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('2e7e6bfe-f79b-45c9-a95e-7bf5d6c33d3a', 'N4', 41, 'word', '亀', 'かめ', 'con rùa', NULL, '名詞', 30, '亀', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('2a4da318-95c6-47be-be36-e8a4927ffc65', 'N4', 41, 'word', 'お姫様', 'おひめさま', 'công chúa', NULL, '名詞', 30, 'お姫様', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('68a9953a-0bf2-46ae-83ae-ad7c49a5e4c1', 'N4', 41, 'word', '暮らす', 'くらす', 'sinh sống', NULL, '動詞', 30, '暮らす', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a92a8f5b-b1a2-45fe-abe3-47e1a6f86620', 'N4', 41, 'word', '陸', 'りく', 'đất liền', NULL, '名詞', 30, '陸', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a1ae4833-eb7b-4580-9c14-f44a8a13c384', 'N4', 41, 'word', '煙', 'けむり', 'khói', NULL, '名詞', 30, '煙', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '叔母さんにお土産をあげる。', 'Tặng quà cho cô/dì.', '_____にお土産をあげる。', '叔母さん', 'generated' from jp_vocab where id = 'd437dc84-aa8d-4ed5-9aa0-98e73db934d5';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'マンションの管理人に聞く。', 'Hỏi người quản lý chung cư.', 'マンションの_____に聞く。', '管理人', 'generated' from jp_vocab where id = 'b85901e1-2c23-4245-b608-0bd330b9ed70';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'この間、彼に会った。', 'Dạo vừa rồi tôi đã gặp anh ấy.', '_____、彼に会った。', 'この間', 'generated' from jp_vocab where id = '639bae0d-366a-4bf7-b9d3-79a659eb0221';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '一言お願いします。', 'Xin nói vài lời.', '_____お願いします。', '一言', 'generated' from jp_vocab where id = '6667e9b7-0d6f-428a-8f10-743da5192f2c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お宅はどちらですか。', 'Nhà anh/chị ở đâu?', '_____はどちらですか。', 'お宅', 'generated' from jp_vocab where id = '1759a234-f943-4b46-82d7-3a8eb5e19e94';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ご結婚おめでとうございます。どうぞお幸せに。', 'Chúc mừng đám cưới. Chúc hai người hạnh phúc!', 'ご結婚おめでとうございます。_____。', 'どうぞお幸せに', 'generated' from jp_vocab where id = '301c0a4b-0d8d-477a-8fee-7e993c78d7cc';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '箱の中身を確認する。', 'Kiểm tra bên trong hộp.', '箱の_____を確認する。', '中身', 'generated' from jp_vocab where id = '150f642a-bdf5-4af8-8931-55e2a243e926';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '壁を真っ白に塗る。', 'Sơn tường trắng toát.', '壁を_____に塗る。', '真っ白', 'generated' from jp_vocab where id = '7262943f-c317-48c6-88b1-49c7cb32b411';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '素敵な服を着ている。', 'Đang mặc bộ quần áo tuyệt vời.', '_____服を着ている。', '素敵な', 'generated' from jp_vocab where id = 'c5fd671e-50e9-49c8-a58b-3cf34f8de87a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '上司に相談する。', 'Thảo luận với cấp trên.', '_____に相談する。', '上司', 'generated' from jp_vocab where id = 'f9420e30-a8d1-4103-81ef-a0057fd91c58';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'アルバイトをする。', 'Đi làm thêm.', '_____をする。', 'アルバイト', 'generated' from jp_vocab where id = '3ed75676-207f-425f-9399-9a8af15899e3';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ご馳走になる。', 'Được chiêu đãi.', '_____になる。', 'ご馳走', 'generated' from jp_vocab where id = '76b4fc5a-b9a0-488c-bf17-45b08ccbdbe2';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '亀を飼う。', 'Nuôi rùa.', '_____を飼う。', '亀', 'generated' from jp_vocab where id = '2e7e6bfe-f79b-45c9-a95e-7bf5d6c33d3a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お姫様のドレスを着る。', 'Mặc váy công chúa.', '_____のドレスを着る。', 'お姫様', 'generated' from jp_vocab where id = '2a4da318-95c6-47be-be36-e8a4927ffc65';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '田舎で暮らす。', 'Sinh sống ở nông thôn.', '田舎で_____。', '暮らす', 'generated' from jp_vocab where id = '68a9953a-0bf2-46ae-83ae-ad7c49a5e4c1';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '陸に上がる。', 'Lên đất liền.', '_____に上がる。', '陸', 'generated' from jp_vocab where id = 'a92a8f5b-b1a2-45fe-abe3-47e1a6f86620';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '煙が出る。', 'Khói bốc ra.', '_____が出る。', '煙', 'generated' from jp_vocab where id = 'a1ae4833-eb7b-4580-9c14-f44a8a13c384';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"叔母さん" có nghĩa là gì?', 'tuyệt vời', 'Chúc hai người hạnh phúc!', 'bên trong, nội dung', 'cô, dì, bác (của người khác)', 'cô, dì, bác (của người khác)', 'generated' from jp_vocab where id = 'd437dc84-aa8d-4ed5-9aa0-98e73db934d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cô, dì, bác (của người khác)"?', '叔母さん', '煙', '暮らす', '上司', '叔母さん', 'generated' from jp_vocab where id = 'd437dc84-aa8d-4ed5-9aa0-98e73db934d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"叔母さん" đọc là gì?', 'すてきな', 'なかみ', 'おばさん', 'アルバイト', 'おばさん', 'generated' from jp_vocab where id = 'd437dc84-aa8d-4ed5-9aa0-98e73db934d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____にお土産をあげる。', NULL, NULL, NULL, NULL, '叔母さん', 'generated' from jp_vocab where id = 'd437dc84-aa8d-4ed5-9aa0-98e73db934d5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"管理人" có nghĩa là gì?', 'Chúc hai người hạnh phúc!', 'người quản lý', 'công chúa', 'con rùa', 'người quản lý', 'generated' from jp_vocab where id = 'b85901e1-2c23-4245-b608-0bd330b9ed70';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "người quản lý"?', '煙', '管理人', '陸', 'お宅', '管理人', 'generated' from jp_vocab where id = 'b85901e1-2c23-4245-b608-0bd330b9ed70';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"管理人" đọc là gì?', 'りく', 'かんりにん', 'このあいだ', 'ごちそう', 'かんりにん', 'generated' from jp_vocab where id = 'b85901e1-2c23-4245-b608-0bd330b9ed70';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: マンションの_____に聞く。', NULL, NULL, NULL, NULL, '管理人', 'generated' from jp_vocab where id = 'b85901e1-2c23-4245-b608-0bd330b9ed70';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"この間" có nghĩa là gì?', 'con rùa', 'Chúc hai người hạnh phúc!', 'cô, dì, bác (của người khác)', 'đợt vừa rồi', 'đợt vừa rồi', 'generated' from jp_vocab where id = '639bae0d-366a-4bf7-b9d3-79a659eb0221';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đợt vừa rồi"?', '暮らす', '陸', '中身', 'この間', 'この間', 'generated' from jp_vocab where id = '639bae0d-366a-4bf7-b9d3-79a659eb0221';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"この間" đọc là gì?', 'まっしろ', 'かんりにん', 'おたく', 'このあいだ', 'このあいだ', 'generated' from jp_vocab where id = '639bae0d-366a-4bf7-b9d3-79a659eb0221';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____、彼に会った。', NULL, NULL, NULL, NULL, 'この間', 'generated' from jp_vocab where id = '639bae0d-366a-4bf7-b9d3-79a659eb0221';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"一言" có nghĩa là gì?', 'con rùa', 'đôi lời', 'làm thêm', 'cô, dì, bác (của người khác)', 'đôi lời', 'generated' from jp_vocab where id = '6667e9b7-0d6f-428a-8f10-743da5192f2c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đôi lời"?', 'どうぞお幸せに', '亀', '真っ白', '一言', '一言', 'generated' from jp_vocab where id = '6667e9b7-0d6f-428a-8f10-743da5192f2c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"一言" đọc là gì?', 'ひとこと', 'くらす', 'どうぞおしあわせに', 'おひめさま', 'ひとこと', 'generated' from jp_vocab where id = '6667e9b7-0d6f-428a-8f10-743da5192f2c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____お願いします。', NULL, NULL, NULL, NULL, '一言', 'generated' from jp_vocab where id = '6667e9b7-0d6f-428a-8f10-743da5192f2c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"お宅" có nghĩa là gì?', 'trắng toát', 'người quản lý', 'nhà (kính ngữ của うち；いえ)', 'tuyệt vời', 'nhà (kính ngữ của うち；いえ)', 'generated' from jp_vocab where id = '1759a234-f943-4b46-82d7-3a8eb5e19e94';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhà (kính ngữ của うち；いえ)"?', '陸', 'どうぞお幸せに', 'アルバイト', 'お宅', 'お宅', 'generated' from jp_vocab where id = '1759a234-f943-4b46-82d7-3a8eb5e19e94';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"お宅" đọc là gì?', 'けむり', 'すてきな', 'ごちそう', 'おたく', 'おたく', 'generated' from jp_vocab where id = '1759a234-f943-4b46-82d7-3a8eb5e19e94';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____はどちらですか。', NULL, NULL, NULL, NULL, 'お宅', 'generated' from jp_vocab where id = '1759a234-f943-4b46-82d7-3a8eb5e19e94';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"どうぞお幸せに" có nghĩa là gì?', 'Chúc hai người hạnh phúc!', 'sinh sống', 'người quản lý', 'đất liền', 'Chúc hai người hạnh phúc!', 'generated' from jp_vocab where id = '301c0a4b-0d8d-477a-8fee-7e993c78d7cc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Chúc hai người hạnh phúc!"?', 'どうぞお幸せに', '上司', 'アルバイト', 'お姫様', 'どうぞお幸せに', 'generated' from jp_vocab where id = '301c0a4b-0d8d-477a-8fee-7e993c78d7cc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"どうぞお幸せに" đọc là gì?', 'アルバイト', 'りく', 'どうぞおしあわせに', 'ひとこと', 'どうぞおしあわせに', 'generated' from jp_vocab where id = '301c0a4b-0d8d-477a-8fee-7e993c78d7cc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: ご結婚おめでとうございます。_____。', NULL, NULL, NULL, NULL, 'どうぞお幸せに', 'generated' from jp_vocab where id = '301c0a4b-0d8d-477a-8fee-7e993c78d7cc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"中身" có nghĩa là gì?', 'con rùa', 'trắng toát', 'đất liền', 'bên trong, nội dung', 'bên trong, nội dung', 'generated' from jp_vocab where id = '150f642a-bdf5-4af8-8931-55e2a243e926';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "bên trong, nội dung"?', '管理人', '中身', '叔母さん', 'アルバイト', '中身', 'generated' from jp_vocab where id = '150f642a-bdf5-4af8-8931-55e2a243e926';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"中身" đọc là gì?', 'なかみ', 'おばさん', 'かんりにん', 'どうぞおしあわせに', 'なかみ', 'generated' from jp_vocab where id = '150f642a-bdf5-4af8-8931-55e2a243e926';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 箱の_____を確認する。', NULL, NULL, NULL, NULL, '中身', 'generated' from jp_vocab where id = '150f642a-bdf5-4af8-8931-55e2a243e926';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"真っ白" có nghĩa là gì?', 'trắng toát', 'cấp trên', 'làm thêm', 'sinh sống', 'trắng toát', 'generated' from jp_vocab where id = '7262943f-c317-48c6-88b1-49c7cb32b411';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "trắng toát"?', '陸', 'お姫様', 'ご馳走', '真っ白', '真っ白', 'generated' from jp_vocab where id = '7262943f-c317-48c6-88b1-49c7cb32b411';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"真っ白" đọc là gì?', 'かめ', 'このあいだ', 'おばさん', 'まっしろ', 'まっしろ', 'generated' from jp_vocab where id = '7262943f-c317-48c6-88b1-49c7cb32b411';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 壁を_____に塗る。', NULL, NULL, NULL, NULL, '真っ白', 'generated' from jp_vocab where id = '7262943f-c317-48c6-88b1-49c7cb32b411';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"素敵な" có nghĩa là gì?', 'tuyệt vời', 'đôi lời', 'khao, chiêu đãi', 'con rùa', 'tuyệt vời', 'generated' from jp_vocab where id = 'c5fd671e-50e9-49c8-a58b-3cf34f8de87a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tuyệt vời"?', '素敵な', '真っ白', '管理人', 'この間', '素敵な', 'generated' from jp_vocab where id = 'c5fd671e-50e9-49c8-a58b-3cf34f8de87a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"素敵な" đọc là gì?', 'どうぞおしあわせに', 'かんりにん', 'すてきな', 'ごちそう', 'すてきな', 'generated' from jp_vocab where id = 'c5fd671e-50e9-49c8-a58b-3cf34f8de87a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____服を着ている。', NULL, NULL, NULL, NULL, '素敵な', 'generated' from jp_vocab where id = 'c5fd671e-50e9-49c8-a58b-3cf34f8de87a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"上司" có nghĩa là gì?', 'đôi lời', 'làm thêm', 'người quản lý', 'cấp trên', 'cấp trên', 'generated' from jp_vocab where id = 'f9420e30-a8d1-4103-81ef-a0057fd91c58';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "cấp trên"?', '暮らす', '上司', 'お姫様', '管理人', '上司', 'generated' from jp_vocab where id = 'f9420e30-a8d1-4103-81ef-a0057fd91c58';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"上司" đọc là gì?', 'じょうし', 'すてきな', 'アルバイト', 'かめ', 'じょうし', 'generated' from jp_vocab where id = 'f9420e30-a8d1-4103-81ef-a0057fd91c58';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に相談する。', NULL, NULL, NULL, NULL, '上司', 'generated' from jp_vocab where id = 'f9420e30-a8d1-4103-81ef-a0057fd91c58';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"アルバイト" có nghĩa là gì?', 'con rùa', 'làm thêm', 'khói', 'đất liền', 'làm thêm', 'generated' from jp_vocab where id = '3ed75676-207f-425f-9399-9a8af15899e3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "làm thêm"?', '暮らす', '叔母さん', 'アルバイト', 'この間', 'アルバイト', 'generated' from jp_vocab where id = '3ed75676-207f-425f-9399-9a8af15899e3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"アルバイト" đọc là gì?', 'りく', 'かめ', 'すてきな', 'アルバイト', 'アルバイト', 'generated' from jp_vocab where id = '3ed75676-207f-425f-9399-9a8af15899e3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____をする。', NULL, NULL, NULL, NULL, 'アルバイト', 'generated' from jp_vocab where id = '3ed75676-207f-425f-9399-9a8af15899e3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ご馳走" có nghĩa là gì?', 'nhà (kính ngữ của うち；いえ)', 'khao, chiêu đãi', 'sinh sống', 'tuyệt vời', 'khao, chiêu đãi', 'generated' from jp_vocab where id = '76b4fc5a-b9a0-488c-bf17-45b08ccbdbe2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "khao, chiêu đãi"?', '一言', '亀', 'アルバイト', 'ご馳走', 'ご馳走', 'generated' from jp_vocab where id = '76b4fc5a-b9a0-488c-bf17-45b08ccbdbe2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ご馳走" đọc là gì?', 'ごちそう', 'じょうし', 'くらす', 'すてきな', 'ごちそう', 'generated' from jp_vocab where id = '76b4fc5a-b9a0-488c-bf17-45b08ccbdbe2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____になる。', NULL, NULL, NULL, NULL, 'ご馳走', 'generated' from jp_vocab where id = '76b4fc5a-b9a0-488c-bf17-45b08ccbdbe2';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"亀" có nghĩa là gì?', 'cô, dì, bác (của người khác)', 'khói', 'trắng toát', 'con rùa', 'con rùa', 'generated' from jp_vocab where id = '2e7e6bfe-f79b-45c9-a95e-7bf5d6c33d3a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "con rùa"?', '一言', '亀', '素敵な', 'どうぞお幸せに', '亀', 'generated' from jp_vocab where id = '2e7e6bfe-f79b-45c9-a95e-7bf5d6c33d3a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"亀" đọc là gì?', 'まっしろ', 'かめ', 'けむり', 'おばさん', 'かめ', 'generated' from jp_vocab where id = '2e7e6bfe-f79b-45c9-a95e-7bf5d6c33d3a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を飼う。', NULL, NULL, NULL, NULL, '亀', 'generated' from jp_vocab where id = '2e7e6bfe-f79b-45c9-a95e-7bf5d6c33d3a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"お姫様" có nghĩa là gì?', 'công chúa', 'đôi lời', 'Chúc hai người hạnh phúc!', 'khói', 'công chúa', 'generated' from jp_vocab where id = '2a4da318-95c6-47be-be36-e8a4927ffc65';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "công chúa"?', '中身', 'ご馳走', 'どうぞお幸せに', 'お姫様', 'お姫様', 'generated' from jp_vocab where id = '2a4da318-95c6-47be-be36-e8a4927ffc65';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"お姫様" đọc là gì?', 'じょうし', 'すてきな', 'くらす', 'おひめさま', 'おひめさま', 'generated' from jp_vocab where id = '2a4da318-95c6-47be-be36-e8a4927ffc65';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____のドレスを着る。', NULL, NULL, NULL, NULL, 'お姫様', 'generated' from jp_vocab where id = '2a4da318-95c6-47be-be36-e8a4927ffc65';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"暮らす" có nghĩa là gì?', 'sinh sống', 'công chúa', 'đợt vừa rồi', 'con rùa', 'sinh sống', 'generated' from jp_vocab where id = '68a9953a-0bf2-46ae-83ae-ad7c49a5e4c1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "sinh sống"?', '陸', '叔母さん', '暮らす', 'ご馳走', '暮らす', 'generated' from jp_vocab where id = '68a9953a-0bf2-46ae-83ae-ad7c49a5e4c1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"暮らす" đọc là gì?', 'くらす', 'けむり', 'ごちそう', 'ひとこと', 'くらす', 'generated' from jp_vocab where id = '68a9953a-0bf2-46ae-83ae-ad7c49a5e4c1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 田舎で_____。', NULL, NULL, NULL, NULL, '暮らす', 'generated' from jp_vocab where id = '68a9953a-0bf2-46ae-83ae-ad7c49a5e4c1';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"陸" có nghĩa là gì?', 'đôi lời', 'tuyệt vời', 'đất liền', 'bên trong, nội dung', 'đất liền', 'generated' from jp_vocab where id = 'a92a8f5b-b1a2-45fe-abe3-47e1a6f86620';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đất liền"?', '陸', '一言', 'ご馳走', '管理人', '陸', 'generated' from jp_vocab where id = 'a92a8f5b-b1a2-45fe-abe3-47e1a6f86620';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"陸" đọc là gì?', 'すてきな', 'くらす', 'かめ', 'りく', 'りく', 'generated' from jp_vocab where id = 'a92a8f5b-b1a2-45fe-abe3-47e1a6f86620';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に上がる。', NULL, NULL, NULL, NULL, '陸', 'generated' from jp_vocab where id = 'a92a8f5b-b1a2-45fe-abe3-47e1a6f86620';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"煙" có nghĩa là gì?', 'đợt vừa rồi', 'công chúa', 'khói', 'đôi lời', 'khói', 'generated' from jp_vocab where id = 'a1ae4833-eb7b-4580-9c14-f44a8a13c384';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "khói"?', '管理人', '煙', 'お宅', '一言', '煙', 'generated' from jp_vocab where id = 'a1ae4833-eb7b-4580-9c14-f44a8a13c384';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"煙" đọc là gì?', 'おひめさま', 'なかみ', 'けむり', 'ひとこと', 'けむり', 'generated' from jp_vocab where id = 'a1ae4833-eb7b-4580-9c14-f44a8a13c384';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が出る。', NULL, NULL, NULL, NULL, '煙', 'generated' from jp_vocab where id = 'a1ae4833-eb7b-4580-9c14-f44a8a13c384';
