-- ============================================================
-- jp-go — Từ vựng N4, 課42 (phần 1, 23 từ đầu).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 31.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('be0c586c-1e53-4553-898b-5c1d5932f3da', 'N4', 42, 'word', '包む', 'つつむ', 'gói, bọc', NULL, '動詞', 31, '包む', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('8e405ab4-cf15-43f2-b109-9a88026bd245', 'N4', 42, 'word', '沸かす', 'わかす', 'đun sôi', NULL, '動詞', 31, '沸かす', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('4a7ba125-b64a-441d-a321-2b6443c6f8b3', 'N4', 42, 'word', '混ぜる', 'まぜる', 'trộn', NULL, '動詞', 31, '混ぜる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('23a95ab2-b13d-4af9-8aa2-8e92baa8f791', 'N4', 42, 'word', '計算する', 'けいさんする', 'tính, tính toán', NULL, '動詞', 31, '計算する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7d5b7e26-7dd7-426f-b115-fa40517ac44e', 'N4', 42, 'word', '並ぶ', 'ならぶ', 'xếp hàng', NULL, '動詞', 31, '並ぶ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('2e148469-02a1-43e0-8e3c-a33edf168b3d', 'N4', 42, 'word', '広める', 'ひろめる', 'tuyên truyền, quảng bá', NULL, '動詞', 31, '広める', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('29bf8133-1799-4f83-9dc5-e4d2fc4201c6', 'N4', 42, 'word', '丈夫', 'じょうぶ', 'chắc chắn', NULL, 'な形容詞', 31, '丈夫', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d808078c-f36f-48cc-9b68-7347ca19dff0', 'N4', 42, 'word', 'アパート', 'アパート', 'căn hộ', NULL, '名詞', 31, 'アパート', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('06071e8f-633b-483d-891e-5c6341476539', 'N4', 42, 'word', '弁護士', 'べんごし', 'luật sư', NULL, '名詞', 31, '弁護士', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('329c6c92-c3d2-4095-88a1-e2746fb252a5', 'N4', 42, 'word', '音楽家', 'おんがくか', 'nhạc sĩ', NULL, '名詞', 31, '音楽家', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('420489e4-7d41-4f25-a07d-a70fa1c4b355', 'N4', 42, 'word', '子供たち', 'こどもたち', 'những đứa trẻ, bọn trẻ', NULL, '名詞', 31, '子供たち', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a1a6d8d6-6360-4091-8645-707e77864942', 'N4', 42, 'word', '自然', 'しぜん', 'tự nhiên', NULL, '名詞', 31, '自然', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('c07ea3bb-7685-4342-9043-2af72a89b6cd', 'N4', 42, 'word', '教育', 'きょういく', 'giáo dục', NULL, '名詞', 31, '教育', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('99c3d1a0-478f-4f7c-9722-4804aaf1d6ad', 'N4', 42, 'word', '文化', 'ぶんか', 'văn hóa', NULL, '名詞', 31, '文化', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('cf88e944-0275-452e-b3c9-b9eb6d545185', 'N4', 42, 'word', '社会', 'しゃかい', 'xã hội', NULL, '名詞', 31, '社会', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('37c3cac2-75f4-4072-b3bc-60e88ce11ffc', 'N4', 42, 'word', '発音', 'はつおん', 'phát âm', NULL, '名詞', 31, '発音', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('5cb70c6f-aa88-4585-83aa-c245353d537a', 'N4', 42, 'word', '猿', 'さる', 'con khỉ', NULL, '名詞', 31, '猿', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('ebee8348-5284-4ead-839d-af416e12fc48', 'N4', 42, 'word', '餌', 'えさ', 'thức ăn (cho động vật)', NULL, '名詞', 31, '餌', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('29e86087-4e4c-4921-a3a7-b7321f9e9d7f', 'N4', 42, 'word', '政治', 'せいじ', 'chính trị', NULL, '名詞', 31, '政治', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('fddb4de6-f010-47f7-97c4-f797ed925f2c', 'N4', 42, 'word', '法律', 'ほうりつ', 'pháp luật', NULL, '名詞', 31, '法律', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7393e495-4da4-477d-bc0f-4b333a9ede71', 'N4', 42, 'word', '戦争', 'せんそう', 'chiến tranh', NULL, '名詞', 31, '戦争', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b424e7d5-9595-4be6-87c4-9f269bda2040', 'N4', 42, 'word', '平和', 'へいわ', 'hòa bình', NULL, '名詞', 31, '平和', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('66bb2296-e4fb-4550-9326-e6d586d899ee', 'N4', 42, 'word', '目的', 'もくてき', 'mục đích', NULL, '名詞', 31, '目的', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'プレゼントを包む。', 'Gói quà.', 'プレゼントを_____。', '包む', 'generated' from jp_vocab where id = 'be0c586c-1e53-4553-898b-5c1d5932f3da';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お湯を沸かす。', 'Đun sôi nước.', 'お湯を_____。', '沸かす', 'generated' from jp_vocab where id = '8e405ab4-cf15-43f2-b109-9a88026bd245';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '卵と砂糖を混ぜる。', 'Trộn trứng và đường.', '卵と砂糖を_____。', '混ぜる', 'generated' from jp_vocab where id = '4a7ba125-b64a-441d-a321-2b6443c6f8b3';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'お金を計算する。', 'Tính tiền.', 'お金を_____。', '計算する', 'generated' from jp_vocab where id = '23a95ab2-b13d-4af9-8aa2-8e92baa8f791';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '列に並ぶ。', 'Xếp hàng.', '列に_____。', '並ぶ', 'generated' from jp_vocab where id = '7d5b7e26-7dd7-426f-b115-fa40517ac44e';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '知識を広める。', 'Tuyên truyền kiến thức.', '知識を_____。', '広める', 'generated' from jp_vocab where id = '2e148469-02a1-43e0-8e3c-a33edf168b3d';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'この箱は丈夫だ。', 'Cái hộp này chắc chắn.', 'この箱は_____だ。', '丈夫', 'generated' from jp_vocab where id = '29bf8133-1799-4f83-9dc5-e4d2fc4201c6';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'アパートに住む。', 'Sống trong căn hộ.', '_____に住む。', 'アパート', 'generated' from jp_vocab where id = 'd808078c-f36f-48cc-9b68-7347ca19dff0';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '弁護士に相談する。', 'Tư vấn luật sư.', '_____に相談する。', '弁護士', 'generated' from jp_vocab where id = '06071e8f-633b-483d-891e-5c6341476539';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '有名な音楽家。', 'Nhạc sĩ nổi tiếng.', '有名な_____。', '音楽家', 'generated' from jp_vocab where id = '329c6c92-c3d2-4095-88a1-e2746fb252a5';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '子供たちが遊んでいる。', 'Bọn trẻ đang chơi đùa.', '_____が遊んでいる。', '子供たち', 'generated' from jp_vocab where id = '420489e4-7d41-4f25-a07d-a70fa1c4b355';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '自然を守る。', 'Bảo vệ tự nhiên.', '_____を守る。', '自然', 'generated' from jp_vocab where id = 'a1a6d8d6-6360-4091-8645-707e77864942';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '教育を受ける。', 'Nhận giáo dục.', '_____を受ける。', '教育', 'generated' from jp_vocab where id = 'c07ea3bb-7685-4342-9043-2af72a89b6cd';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '日本の文化を学ぶ。', 'Học văn hóa Nhật Bản.', '日本の_____を学ぶ。', '文化', 'generated' from jp_vocab where id = '99c3d1a0-478f-4f7c-9722-4804aaf1d6ad';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '社会に出る。', 'Bước ra xã hội.', '_____に出る。', '社会', 'generated' from jp_vocab where id = 'cf88e944-0275-452e-b3c9-b9eb6d545185';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '発音を練習する。', 'Luyện phát âm.', '_____を練習する。', '発音', 'generated' from jp_vocab where id = '37c3cac2-75f4-4072-b3bc-60e88ce11ffc';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '猿が木に登る。', 'Con khỉ leo cây.', '_____が木に登る。', '猿', 'generated' from jp_vocab where id = '5cb70c6f-aa88-4585-83aa-c245353d537a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '魚に餌をやる。', 'Cho cá ăn.', '魚に_____をやる。', '餌', 'generated' from jp_vocab where id = 'ebee8348-5284-4ead-839d-af416e12fc48';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '政治に興味がある。', 'Có hứng thú với chính trị.', '_____に興味がある。', '政治', 'generated' from jp_vocab where id = '29e86087-4e4c-4921-a3a7-b7321f9e9d7f';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '法律を守る。', 'Tuân thủ pháp luật.', '_____を守る。', '法律', 'generated' from jp_vocab where id = 'fddb4de6-f010-47f7-97c4-f797ed925f2c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '戦争が終わった。', 'Chiến tranh đã kết thúc.', '_____が終わった。', '戦争', 'generated' from jp_vocab where id = '7393e495-4da4-477d-bc0f-4b333a9ede71';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '平和を願う。', 'Mong ước hòa bình.', '_____を願う。', '平和', 'generated' from jp_vocab where id = 'b424e7d5-9595-4be6-87c4-9f269bda2040';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '旅行の目的は何ですか。', 'Mục đích chuyến du lịch là gì?', '旅行の_____は何ですか。', '目的', 'generated' from jp_vocab where id = '66bb2296-e4fb-4550-9326-e6d586d899ee';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"包む" có nghĩa là gì?', 'gói, bọc', 'văn hóa', 'luật sư', 'nhạc sĩ', 'gói, bọc', 'generated' from jp_vocab where id = 'be0c586c-1e53-4553-898b-5c1d5932f3da';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "gói, bọc"?', '包む', '音楽家', '子供たち', '目的', '包む', 'generated' from jp_vocab where id = 'be0c586c-1e53-4553-898b-5c1d5932f3da';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"包む" đọc là gì?', 'ひろめる', 'じょうぶ', 'わかす', 'つつむ', 'つつむ', 'generated' from jp_vocab where id = 'be0c586c-1e53-4553-898b-5c1d5932f3da';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: プレゼントを_____。', NULL, NULL, NULL, NULL, '包む', 'generated' from jp_vocab where id = 'be0c586c-1e53-4553-898b-5c1d5932f3da';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"沸かす" có nghĩa là gì?', 'xã hội', 'đun sôi', 'chính trị', 'gói, bọc', 'đun sôi', 'generated' from jp_vocab where id = '8e405ab4-cf15-43f2-b109-9a88026bd245';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đun sôi"?', '社会', '子供たち', '猿', '沸かす', '沸かす', 'generated' from jp_vocab where id = '8e405ab4-cf15-43f2-b109-9a88026bd245';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"沸かす" đọc là gì?', 'きょういく', 'わかす', 'さる', 'じょうぶ', 'わかす', 'generated' from jp_vocab where id = '8e405ab4-cf15-43f2-b109-9a88026bd245';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: お湯を_____。', NULL, NULL, NULL, NULL, '沸かす', 'generated' from jp_vocab where id = '8e405ab4-cf15-43f2-b109-9a88026bd245';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"混ぜる" có nghĩa là gì?', 'luật sư', 'những đứa trẻ, bọn trẻ', 'chiến tranh', 'trộn', 'trộn', 'generated' from jp_vocab where id = '4a7ba125-b64a-441d-a321-2b6443c6f8b3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "trộn"?', '平和', '子供たち', '混ぜる', '餌', '混ぜる', 'generated' from jp_vocab where id = '4a7ba125-b64a-441d-a321-2b6443c6f8b3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"混ぜる" đọc là gì?', 'まぜる', 'わかす', 'もくてき', 'ひろめる', 'まぜる', 'generated' from jp_vocab where id = '4a7ba125-b64a-441d-a321-2b6443c6f8b3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 卵と砂糖を_____。', NULL, NULL, NULL, NULL, '混ぜる', 'generated' from jp_vocab where id = '4a7ba125-b64a-441d-a321-2b6443c6f8b3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"計算する" có nghĩa là gì?', 'thức ăn (cho động vật)', 'tính, tính toán', 'văn hóa', 'luật sư', 'tính, tính toán', 'generated' from jp_vocab where id = '23a95ab2-b13d-4af9-8aa2-8e92baa8f791';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tính, tính toán"?', '計算する', '文化', '子供たち', '発音', '計算する', 'generated' from jp_vocab where id = '23a95ab2-b13d-4af9-8aa2-8e92baa8f791';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"計算する" đọc là gì?', 'しぜん', 'けいさんする', 'ぶんか', 'へいわ', 'けいさんする', 'generated' from jp_vocab where id = '23a95ab2-b13d-4af9-8aa2-8e92baa8f791';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: お金を_____。', NULL, NULL, NULL, NULL, '計算する', 'generated' from jp_vocab where id = '23a95ab2-b13d-4af9-8aa2-8e92baa8f791';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"並ぶ" có nghĩa là gì?', 'mục đích', 'gói, bọc', 'hòa bình', 'xếp hàng', 'xếp hàng', 'generated' from jp_vocab where id = '7d5b7e26-7dd7-426f-b115-fa40517ac44e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "xếp hàng"?', 'アパート', '並ぶ', '法律', '発音', '並ぶ', 'generated' from jp_vocab where id = '7d5b7e26-7dd7-426f-b115-fa40517ac44e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"並ぶ" đọc là gì?', 'ならぶ', 'こどもたち', 'ほうりつ', 'きょういく', 'ならぶ', 'generated' from jp_vocab where id = '7d5b7e26-7dd7-426f-b115-fa40517ac44e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 列に_____。', NULL, NULL, NULL, NULL, '並ぶ', 'generated' from jp_vocab where id = '7d5b7e26-7dd7-426f-b115-fa40517ac44e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"広める" có nghĩa là gì?', 'chính trị', 'tuyên truyền, quảng bá', 'xã hội', 'văn hóa', 'tuyên truyền, quảng bá', 'generated' from jp_vocab where id = '2e148469-02a1-43e0-8e3c-a33edf168b3d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tuyên truyền, quảng bá"?', '広める', '平和', '沸かす', '発音', '広める', 'generated' from jp_vocab where id = '2e148469-02a1-43e0-8e3c-a33edf168b3d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"広める" đọc là gì?', 'しぜん', 'ひろめる', 'けいさんする', 'せいじ', 'ひろめる', 'generated' from jp_vocab where id = '2e148469-02a1-43e0-8e3c-a33edf168b3d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 知識を_____。', NULL, NULL, NULL, NULL, '広める', 'generated' from jp_vocab where id = '2e148469-02a1-43e0-8e3c-a33edf168b3d';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"丈夫" có nghĩa là gì?', 'trộn', 'chắc chắn', 'nhạc sĩ', 'phát âm', 'chắc chắn', 'generated' from jp_vocab where id = '29bf8133-1799-4f83-9dc5-e4d2fc4201c6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chắc chắn"?', '教育', '混ぜる', '平和', '丈夫', '丈夫', 'generated' from jp_vocab where id = '29bf8133-1799-4f83-9dc5-e4d2fc4201c6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"丈夫" đọc là gì?', 'べんごし', 'じょうぶ', 'つつむ', 'アパート', 'じょうぶ', 'generated' from jp_vocab where id = '29bf8133-1799-4f83-9dc5-e4d2fc4201c6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: この箱は_____だ。', NULL, NULL, NULL, NULL, '丈夫', 'generated' from jp_vocab where id = '29bf8133-1799-4f83-9dc5-e4d2fc4201c6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"アパート" có nghĩa là gì?', 'hòa bình', 'gói, bọc', 'đun sôi', 'căn hộ', 'căn hộ', 'generated' from jp_vocab where id = 'd808078c-f36f-48cc-9b68-7347ca19dff0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "căn hộ"?', '法律', '包む', 'アパート', '混ぜる', 'アパート', 'generated' from jp_vocab where id = 'd808078c-f36f-48cc-9b68-7347ca19dff0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"アパート" đọc là gì?', 'せんそう', 'けいさんする', 'つつむ', 'アパート', 'アパート', 'generated' from jp_vocab where id = 'd808078c-f36f-48cc-9b68-7347ca19dff0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に住む。', NULL, NULL, NULL, NULL, 'アパート', 'generated' from jp_vocab where id = 'd808078c-f36f-48cc-9b68-7347ca19dff0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"弁護士" có nghĩa là gì?', 'nhạc sĩ', 'tự nhiên', 'thức ăn (cho động vật)', 'luật sư', 'luật sư', 'generated' from jp_vocab where id = '06071e8f-633b-483d-891e-5c6341476539';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "luật sư"?', 'アパート', '丈夫', '弁護士', '政治', '弁護士', 'generated' from jp_vocab where id = '06071e8f-633b-483d-891e-5c6341476539';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"弁護士" đọc là gì?', 'もくてき', 'アパート', 'しゃかい', 'べんごし', 'べんごし', 'generated' from jp_vocab where id = '06071e8f-633b-483d-891e-5c6341476539';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に相談する。', NULL, NULL, NULL, NULL, '弁護士', 'generated' from jp_vocab where id = '06071e8f-633b-483d-891e-5c6341476539';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"音楽家" có nghĩa là gì?', 'chính trị', 'nhạc sĩ', 'văn hóa', 'đun sôi', 'nhạc sĩ', 'generated' from jp_vocab where id = '329c6c92-c3d2-4095-88a1-e2746fb252a5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhạc sĩ"?', '音楽家', 'アパート', '広める', '弁護士', '音楽家', 'generated' from jp_vocab where id = '329c6c92-c3d2-4095-88a1-e2746fb252a5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"音楽家" đọc là gì?', 'つつむ', 'おんがくか', 'こどもたち', 'さる', 'おんがくか', 'generated' from jp_vocab where id = '329c6c92-c3d2-4095-88a1-e2746fb252a5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 有名な_____。', NULL, NULL, NULL, NULL, '音楽家', 'generated' from jp_vocab where id = '329c6c92-c3d2-4095-88a1-e2746fb252a5';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"子供たち" có nghĩa là gì?', 'chắc chắn', 'chiến tranh', 'gói, bọc', 'những đứa trẻ, bọn trẻ', 'những đứa trẻ, bọn trẻ', 'generated' from jp_vocab where id = '420489e4-7d41-4f25-a07d-a70fa1c4b355';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "những đứa trẻ, bọn trẻ"?', '発音', 'アパート', '子供たち', '目的', '子供たち', 'generated' from jp_vocab where id = '420489e4-7d41-4f25-a07d-a70fa1c4b355';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"子供たち" đọc là gì?', 'ぶんか', 'こどもたち', 'せんそう', 'わかす', 'こどもたち', 'generated' from jp_vocab where id = '420489e4-7d41-4f25-a07d-a70fa1c4b355';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が遊んでいる。', NULL, NULL, NULL, NULL, '子供たち', 'generated' from jp_vocab where id = '420489e4-7d41-4f25-a07d-a70fa1c4b355';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"自然" có nghĩa là gì?', 'tự nhiên', 'chiến tranh', 'văn hóa', 'xếp hàng', 'tự nhiên', 'generated' from jp_vocab where id = 'a1a6d8d6-6360-4091-8645-707e77864942';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tự nhiên"?', '包む', '子供たち', '混ぜる', '自然', '自然', 'generated' from jp_vocab where id = 'a1a6d8d6-6360-4091-8645-707e77864942';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"自然" đọc là gì?', 'おんがくか', 'しぜん', 'せいじ', 'しゃかい', 'しぜん', 'generated' from jp_vocab where id = 'a1a6d8d6-6360-4091-8645-707e77864942';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を守る。', NULL, NULL, NULL, NULL, '自然', 'generated' from jp_vocab where id = 'a1a6d8d6-6360-4091-8645-707e77864942';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"教育" có nghĩa là gì?', 'luật sư', 'giáo dục', 'chắc chắn', 'đun sôi', 'giáo dục', 'generated' from jp_vocab where id = 'c07ea3bb-7685-4342-9043-2af72a89b6cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "giáo dục"?', '法律', '教育', '平和', '音楽家', '教育', 'generated' from jp_vocab where id = 'c07ea3bb-7685-4342-9043-2af72a89b6cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"教育" đọc là gì?', 'さる', 'アパート', 'せいじ', 'きょういく', 'きょういく', 'generated' from jp_vocab where id = 'c07ea3bb-7685-4342-9043-2af72a89b6cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を受ける。', NULL, NULL, NULL, NULL, '教育', 'generated' from jp_vocab where id = 'c07ea3bb-7685-4342-9043-2af72a89b6cd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"文化" có nghĩa là gì?', 'văn hóa', 'xã hội', 'hòa bình', 'pháp luật', 'văn hóa', 'generated' from jp_vocab where id = '99c3d1a0-478f-4f7c-9722-4804aaf1d6ad';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "văn hóa"?', '子供たち', '丈夫', '教育', '文化', '文化', 'generated' from jp_vocab where id = '99c3d1a0-478f-4f7c-9722-4804aaf1d6ad';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"文化" đọc là gì?', 'しぜん', 'きょういく', 'べんごし', 'ぶんか', 'ぶんか', 'generated' from jp_vocab where id = '99c3d1a0-478f-4f7c-9722-4804aaf1d6ad';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 日本の_____を学ぶ。', NULL, NULL, NULL, NULL, '文化', 'generated' from jp_vocab where id = '99c3d1a0-478f-4f7c-9722-4804aaf1d6ad';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"社会" có nghĩa là gì?', 'hòa bình', 'thức ăn (cho động vật)', 'xã hội', 'giáo dục', 'xã hội', 'generated' from jp_vocab where id = 'cf88e944-0275-452e-b3c9-b9eb6d545185';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "xã hội"?', '社会', '包む', '広める', '音楽家', '社会', 'generated' from jp_vocab where id = 'cf88e944-0275-452e-b3c9-b9eb6d545185';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"社会" đọc là gì?', 'アパート', 'きょういく', 'しゃかい', 'おんがくか', 'しゃかい', 'generated' from jp_vocab where id = 'cf88e944-0275-452e-b3c9-b9eb6d545185';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に出る。', NULL, NULL, NULL, NULL, '社会', 'generated' from jp_vocab where id = 'cf88e944-0275-452e-b3c9-b9eb6d545185';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"発音" có nghĩa là gì?', 'tự nhiên', 'pháp luật', 'hòa bình', 'phát âm', 'phát âm', 'generated' from jp_vocab where id = '37c3cac2-75f4-4072-b3bc-60e88ce11ffc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phát âm"?', '混ぜる', '計算する', '発音', '社会', '発音', 'generated' from jp_vocab where id = '37c3cac2-75f4-4072-b3bc-60e88ce11ffc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"発音" đọc là gì?', 'ひろめる', 'はつおん', 'ならぶ', 'せんそう', 'はつおん', 'generated' from jp_vocab where id = '37c3cac2-75f4-4072-b3bc-60e88ce11ffc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を練習する。', NULL, NULL, NULL, NULL, '発音', 'generated' from jp_vocab where id = '37c3cac2-75f4-4072-b3bc-60e88ce11ffc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"猿" có nghĩa là gì?', 'phát âm', 'tự nhiên', 'con khỉ', 'pháp luật', 'con khỉ', 'generated' from jp_vocab where id = '5cb70c6f-aa88-4585-83aa-c245353d537a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "con khỉ"?', '猿', '包む', '平和', '音楽家', '猿', 'generated' from jp_vocab where id = '5cb70c6f-aa88-4585-83aa-c245353d537a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"猿" đọc là gì?', 'しぜん', 'さる', 'ひろめる', 'せいじ', 'さる', 'generated' from jp_vocab where id = '5cb70c6f-aa88-4585-83aa-c245353d537a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が木に登る。', NULL, NULL, NULL, NULL, '猿', 'generated' from jp_vocab where id = '5cb70c6f-aa88-4585-83aa-c245353d537a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"餌" có nghĩa là gì?', 'căn hộ', 'thức ăn (cho động vật)', 'văn hóa', 'trộn', 'thức ăn (cho động vật)', 'generated' from jp_vocab where id = 'ebee8348-5284-4ead-839d-af416e12fc48';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thức ăn (cho động vật)"?', '弁護士', '丈夫', '餌', '社会', '餌', 'generated' from jp_vocab where id = 'ebee8348-5284-4ead-839d-af416e12fc48';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"餌" đọc là gì?', 'おんがくか', 'えさ', 'べんごし', 'ぶんか', 'えさ', 'generated' from jp_vocab where id = 'ebee8348-5284-4ead-839d-af416e12fc48';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 魚に_____をやる。', NULL, NULL, NULL, NULL, '餌', 'generated' from jp_vocab where id = 'ebee8348-5284-4ead-839d-af416e12fc48';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"政治" có nghĩa là gì?', 'luật sư', 'chính trị', 'con khỉ', 'mục đích', 'chính trị', 'generated' from jp_vocab where id = '29e86087-4e4c-4921-a3a7-b7321f9e9d7f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chính trị"?', '餌', '社会', '子供たち', '政治', '政治', 'generated' from jp_vocab where id = '29e86087-4e4c-4921-a3a7-b7321f9e9d7f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"政治" đọc là gì?', 'おんがくか', 'けいさんする', 'せいじ', 'つつむ', 'せいじ', 'generated' from jp_vocab where id = '29e86087-4e4c-4921-a3a7-b7321f9e9d7f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に興味がある。', NULL, NULL, NULL, NULL, '政治', 'generated' from jp_vocab where id = '29e86087-4e4c-4921-a3a7-b7321f9e9d7f';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"法律" có nghĩa là gì?', 'tuyên truyền, quảng bá', 'pháp luật', 'những đứa trẻ, bọn trẻ', 'trộn', 'pháp luật', 'generated' from jp_vocab where id = 'fddb4de6-f010-47f7-97c4-f797ed925f2c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "pháp luật"?', '混ぜる', '法律', '自然', '並ぶ', '法律', 'generated' from jp_vocab where id = 'fddb4de6-f010-47f7-97c4-f797ed925f2c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"法律" đọc là gì?', 'しゃかい', 'ほうりつ', 'わかす', 'もくてき', 'ほうりつ', 'generated' from jp_vocab where id = 'fddb4de6-f010-47f7-97c4-f797ed925f2c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を守る。', NULL, NULL, NULL, NULL, '法律', 'generated' from jp_vocab where id = 'fddb4de6-f010-47f7-97c4-f797ed925f2c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"戦争" có nghĩa là gì?', 'pháp luật', 'chính trị', 'xếp hàng', 'chiến tranh', 'chiến tranh', 'generated' from jp_vocab where id = '7393e495-4da4-477d-bc0f-4b333a9ede71';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chiến tranh"?', '法律', '教育', '子供たち', '戦争', '戦争', 'generated' from jp_vocab where id = '7393e495-4da4-477d-bc0f-4b333a9ede71';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"戦争" đọc là gì?', 'じょうぶ', 'アパート', 'へいわ', 'せんそう', 'せんそう', 'generated' from jp_vocab where id = '7393e495-4da4-477d-bc0f-4b333a9ede71';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が終わった。', NULL, NULL, NULL, NULL, '戦争', 'generated' from jp_vocab where id = '7393e495-4da4-477d-bc0f-4b333a9ede71';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"平和" có nghĩa là gì?', 'tự nhiên', 'pháp luật', 'trộn', 'hòa bình', 'hòa bình', 'generated' from jp_vocab where id = 'b424e7d5-9595-4be6-87c4-9f269bda2040';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "hòa bình"?', '計算する', '平和', '法律', '発音', '平和', 'generated' from jp_vocab where id = 'b424e7d5-9595-4be6-87c4-9f269bda2040';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"平和" đọc là gì?', 'ほうりつ', 'へいわ', 'べんごし', 'せんそう', 'へいわ', 'generated' from jp_vocab where id = 'b424e7d5-9595-4be6-87c4-9f269bda2040';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を願う。', NULL, NULL, NULL, NULL, '平和', 'generated' from jp_vocab where id = 'b424e7d5-9595-4be6-87c4-9f269bda2040';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"目的" có nghĩa là gì?', 'đun sôi', 'nhạc sĩ', 'giáo dục', 'mục đích', 'mục đích', 'generated' from jp_vocab where id = '66bb2296-e4fb-4550-9326-e6d586d899ee';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "mục đích"?', '子供たち', '目的', '音楽家', '発音', '目的', 'generated' from jp_vocab where id = '66bb2296-e4fb-4550-9326-e6d586d899ee';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"目的" đọc là gì?', 'もくてき', 'ならぶ', 'しゃかい', 'わかす', 'もくてき', 'generated' from jp_vocab where id = '66bb2296-e4fb-4550-9326-e6d586d899ee';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 旅行の_____は何ですか。', NULL, NULL, NULL, NULL, '目的', 'generated' from jp_vocab where id = '66bb2296-e4fb-4550-9326-e6d586d899ee';
