-- ============================================================
-- jp-go — Từ vựng N4, 課46 (phần 1, 18 từ đầu).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 33.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e23ae31e-17fa-4653-ae21-521820f08996', 'N4', 46, 'word', '渡す', 'わたす', 'đưa, trao', NULL, '動詞', 33, '渡す', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('2a259359-7581-4f59-92d6-7d3cb37c917e', 'N4', 46, 'word', '帰ってくる', 'かえってくる', 'trở về', NULL, '動詞', 33, '帰ってくる', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('357cf0f8-8dd4-480b-b5ec-7c0f9a068766', 'N4', 46, 'phrase', 'バスが出る', 'ばすがでる', 'xuất phát, rời bến (xe bus)', NULL, '動詞', 33, 'バスが出る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7c09b2f7-f465-4bcd-973f-8851335a91cc', 'N4', 46, 'phrase', '荷物が出る', 'にもつがでる', 'đến (hành lý)', NULL, '動詞', 33, '荷物が出る', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('9ac4d084-2896-4f28-b072-cc41fe4b76ae', 'N4', 46, 'word', '入学する', 'にゅうがくする', 'nhập học (đại học)', 'thường dùng dạng [大学に〜]', '動詞', 33, '入学する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('52ad83a0-55a6-4291-84e3-9ffa38ba6c94', 'N4', 46, 'word', '卒業する', 'そつぎょうする', 'tốt nghiệp (đại học)', 'thường dùng dạng [大学を〜]', '動詞', 33, '卒業する', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('50918960-9af5-46b6-b408-95f669175cfc', 'N4', 46, 'word', '焼く', 'やく', 'nướng', NULL, '動詞', 33, '焼く', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('40915ef3-c2d8-447f-bc71-d2f40d91b6f4', 'N4', 46, 'word', '焼ける', 'やける', '(thịt) nướng chín/ (nhà) bị cháy', NULL, '動詞', 33, '焼ける', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('badab330-6260-417c-8cb4-1aab1b7f36e3', 'N4', 46, 'word', '留守', 'るす', 'vắng nhà, đi vắng', NULL, '名詞', 33, '留守', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('501d238a-d48f-4a73-92d4-5bde1a43eda6', 'N4', 46, 'word', '宅配便', 'たくはいびん', 'dịch vụ chuyển phát tận nhà', NULL, '名詞', 33, '宅配便', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('eceb0b92-25af-4c6a-8864-e2c806e18561', 'N4', 46, 'word', '航空便', 'こうくうびん', 'gửi đường hàng không', NULL, '名詞', 33, '航空便', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('8325249d-79b9-4d1a-b458-1c4f29144e25', 'N4', 46, 'word', '船便', 'ふなびん', 'gửi đường biển', NULL, '名詞', 33, '船便', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('33bcc566-9833-4be6-9078-649cc795adaa', 'N4', 46, 'word', '原因', 'げんいん', 'nguyên nhân', NULL, '名詞', 33, '原因', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('3aeb8b82-179f-4a08-85b1-8f21976ee5fd', 'N4', 46, 'word', '具合', 'ぐあい', 'tình trạng, thể trạng', NULL, '名詞', 33, '具合', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('24490ac4-64d5-43d0-acc5-c4a74f8231f7', 'N4', 46, 'word', 'こちら', 'こちら', 'phía tôi', NULL, '名詞', 33, 'こちら', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('38b5d28d-a7f9-41d2-9e03-e59f950e8410', 'N4', 46, 'word', 'ところ', 'ところ', 'chỗ -', 'thường dùng dạng [〜のところ]', '名詞', 33, 'ところ', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('ed03482e-e27d-492e-a3c1-4278be11fde9', 'N4', 46, 'word', '半年', 'はんとし', 'nửa năm', NULL, '名詞', 33, '半年', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('62d15274-d916-4942-a163-562356d69834', 'N4', 46, 'word', 'ちょうど', 'ちょうど', 'vừa đúng', NULL, '副詞', 33, 'ちょうど', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '手紙を渡す。', 'Trao bức thư.', '手紙を_____。', '渡す', 'generated' from jp_vocab where id = 'e23ae31e-17fa-4653-ae21-521820f08996';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '家に帰ってくる。', 'Trở về nhà.', '家に_____。', '帰ってくる', 'generated' from jp_vocab where id = '2a259359-7581-4f59-92d6-7d3cb37c917e';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'バスが出る。', 'Xe buýt xuất phát.', '_____。', 'バスが出る', 'generated' from jp_vocab where id = '357cf0f8-8dd4-480b-b5ec-7c0f9a068766';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '荷物が出る。', 'Hành lý được đưa ra.', '_____。', '荷物が出る', 'generated' from jp_vocab where id = '7c09b2f7-f465-4bcd-973f-8851335a91cc';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '大学に入学する。', 'Nhập học đại học.', '大学に_____。', '入学する', 'generated' from jp_vocab where id = '9ac4d084-2896-4f28-b072-cc41fe4b76ae';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '大学を卒業する。', 'Tốt nghiệp đại học.', '大学を_____。', '卒業する', 'generated' from jp_vocab where id = '52ad83a0-55a6-4291-84e3-9ffa38ba6c94';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '魚を焼く。', 'Nướng cá.', '魚を_____。', '焼く', 'generated' from jp_vocab where id = '50918960-9af5-46b6-b408-95f669175cfc';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '肉がよく焼ける。', 'Thịt nướng chín kỹ.', '肉がよく_____。', '焼ける', 'generated' from jp_vocab where id = '40915ef3-c2d8-447f-bc71-d2f40d91b6f4';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '家は留守だった。', 'Nhà không có ai (đi vắng).', '家は_____だった。', '留守', 'generated' from jp_vocab where id = 'badab330-6260-417c-8cb4-1aab1b7f36e3';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '宅配便で送る。', 'Gửi bằng dịch vụ chuyển phát tận nhà.', '_____で送る。', '宅配便', 'generated' from jp_vocab where id = '501d238a-d48f-4a73-92d4-5bde1a43eda6';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '航空便で送る。', 'Gửi bằng đường hàng không.', '_____で送る。', '航空便', 'generated' from jp_vocab where id = 'eceb0b92-25af-4c6a-8864-e2c806e18561';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '船便で送る。', 'Gửi bằng đường biển.', '_____で送る。', '船便', 'generated' from jp_vocab where id = '8325249d-79b9-4d1a-b458-1c4f29144e25';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '事故の原因を調べる。', 'Điều tra nguyên nhân tai nạn.', '事故の_____を調べる。', '原因', 'generated' from jp_vocab where id = '33bcc566-9833-4be6-9078-649cc795adaa';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '具合が悪い。', 'Thể trạng không tốt.', '_____が悪い。', '具合', 'generated' from jp_vocab where id = '3aeb8b82-179f-4a08-85b1-8f21976ee5fd';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'こちらへどうぞ。', 'Xin mời lối này.', '_____へどうぞ。', 'こちら', 'generated' from jp_vocab where id = '24490ac4-64d5-43d0-acc5-c4a74f8231f7';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '先生のところへ行く。', 'Đi đến chỗ thầy/cô.', '先生の_____へ行く。', 'ところ', 'generated' from jp_vocab where id = '38b5d28d-a7f9-41d2-9e03-e59f950e8410';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '半年前に来た。', 'Đã đến nửa năm trước.', '_____前に来た。', '半年', 'generated' from jp_vocab where id = 'ed03482e-e27d-492e-a3c1-4278be11fde9';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ちょうど良かった。', 'Vừa đúng lúc tốt.', '_____良かった。', 'ちょうど', 'generated' from jp_vocab where id = '62d15274-d916-4942-a163-562356d69834';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"渡す" có nghĩa là gì?', 'vắng nhà, đi vắng', '(thịt) nướng chín/ (nhà) bị cháy', 'đưa, trao', 'tốt nghiệp (đại học)', 'đưa, trao', 'generated' from jp_vocab where id = 'e23ae31e-17fa-4653-ae21-521820f08996';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đưa, trao"?', '具合', '帰ってくる', '渡す', '原因', '渡す', 'generated' from jp_vocab where id = 'e23ae31e-17fa-4653-ae21-521820f08996';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"渡す" đọc là gì?', 'わたす', 'ふなびん', 'にゅうがくする', 'やける', 'わたす', 'generated' from jp_vocab where id = 'e23ae31e-17fa-4653-ae21-521820f08996';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 手紙を_____。', NULL, NULL, NULL, NULL, '渡す', 'generated' from jp_vocab where id = 'e23ae31e-17fa-4653-ae21-521820f08996';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"帰ってくる" có nghĩa là gì?', 'trở về', 'gửi đường hàng không', 'gửi đường biển', 'đưa, trao', 'trở về', 'generated' from jp_vocab where id = '2a259359-7581-4f59-92d6-7d3cb37c917e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "trở về"?', '渡す', '具合', '入学する', '帰ってくる', '帰ってくる', 'generated' from jp_vocab where id = '2a259359-7581-4f59-92d6-7d3cb37c917e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"帰ってくる" đọc là gì?', 'ぐあい', 'たくはいびん', 'かえってくる', 'わたす', 'かえってくる', 'generated' from jp_vocab where id = '2a259359-7581-4f59-92d6-7d3cb37c917e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 家に_____。', NULL, NULL, NULL, NULL, '帰ってくる', 'generated' from jp_vocab where id = '2a259359-7581-4f59-92d6-7d3cb37c917e';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"バスが出る" có nghĩa là gì?', 'đưa, trao', 'trở về', 'xuất phát, rời bến (xe bus)', 'chỗ -', 'xuất phát, rời bến (xe bus)', 'generated' from jp_vocab where id = '357cf0f8-8dd4-480b-b5ec-7c0f9a068766';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "xuất phát, rời bến (xe bus)"?', 'ところ', '具合', 'こちら', 'バスが出る', 'バスが出る', 'generated' from jp_vocab where id = '357cf0f8-8dd4-480b-b5ec-7c0f9a068766';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"バスが出る" đọc là gì?', 'にもつがでる', 'ばすがでる', 'にゅうがくする', 'こうくうびん', 'ばすがでる', 'generated' from jp_vocab where id = '357cf0f8-8dd4-480b-b5ec-7c0f9a068766';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____。', NULL, NULL, NULL, NULL, 'バスが出る', 'generated' from jp_vocab where id = '357cf0f8-8dd4-480b-b5ec-7c0f9a068766';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"荷物が出る" có nghĩa là gì?', 'gửi đường biển', 'đưa, trao', 'nguyên nhân', 'đến (hành lý)', 'đến (hành lý)', 'generated' from jp_vocab where id = '7c09b2f7-f465-4bcd-973f-8851335a91cc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "đến (hành lý)"?', '荷物が出る', '渡す', '原因', 'ところ', '荷物が出る', 'generated' from jp_vocab where id = '7c09b2f7-f465-4bcd-973f-8851335a91cc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"荷物が出る" đọc là gì?', 'にもつがでる', 'かえってくる', 'げんいん', 'こちら', 'にもつがでる', 'generated' from jp_vocab where id = '7c09b2f7-f465-4bcd-973f-8851335a91cc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____。', NULL, NULL, NULL, NULL, '荷物が出る', 'generated' from jp_vocab where id = '7c09b2f7-f465-4bcd-973f-8851335a91cc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"入学する" có nghĩa là gì?', 'đến (hành lý)', 'vừa đúng', 'nhập học (đại học)', 'tình trạng, thể trạng', 'nhập học (đại học)', 'generated' from jp_vocab where id = '9ac4d084-2896-4f28-b072-cc41fe4b76ae';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhập học (đại học)"?', 'こちら', '渡す', '入学する', '帰ってくる', '入学する', 'generated' from jp_vocab where id = '9ac4d084-2896-4f28-b072-cc41fe4b76ae';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"入学する" đọc là gì?', 'わたす', 'こちら', 'やける', 'にゅうがくする', 'にゅうがくする', 'generated' from jp_vocab where id = '9ac4d084-2896-4f28-b072-cc41fe4b76ae';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 大学に_____。', NULL, NULL, NULL, NULL, '入学する', 'generated' from jp_vocab where id = '9ac4d084-2896-4f28-b072-cc41fe4b76ae';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"卒業する" có nghĩa là gì?', 'gửi đường hàng không', 'phía tôi', 'vắng nhà, đi vắng', 'tốt nghiệp (đại học)', 'tốt nghiệp (đại học)', 'generated' from jp_vocab where id = '52ad83a0-55a6-4291-84e3-9ffa38ba6c94';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tốt nghiệp (đại học)"?', '帰ってくる', '航空便', '渡す', '卒業する', '卒業する', 'generated' from jp_vocab where id = '52ad83a0-55a6-4291-84e3-9ffa38ba6c94';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"卒業する" đọc là gì?', 'にゅうがくする', 'こちら', 'ちょうど', 'そつぎょうする', 'そつぎょうする', 'generated' from jp_vocab where id = '52ad83a0-55a6-4291-84e3-9ffa38ba6c94';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 大学を_____。', NULL, NULL, NULL, NULL, '卒業する', 'generated' from jp_vocab where id = '52ad83a0-55a6-4291-84e3-9ffa38ba6c94';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"焼く" có nghĩa là gì?', 'dịch vụ chuyển phát tận nhà', 'đến (hành lý)', 'nửa năm', 'nướng', 'nướng', 'generated' from jp_vocab where id = '50918960-9af5-46b6-b408-95f669175cfc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nướng"?', '具合', '渡す', '焼く', '卒業する', '焼く', 'generated' from jp_vocab where id = '50918960-9af5-46b6-b408-95f669175cfc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"焼く" đọc là gì?', 'ぐあい', 'やく', 'ばすがでる', 'げんいん', 'やく', 'generated' from jp_vocab where id = '50918960-9af5-46b6-b408-95f669175cfc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 魚を_____。', NULL, NULL, NULL, NULL, '焼く', 'generated' from jp_vocab where id = '50918960-9af5-46b6-b408-95f669175cfc';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"焼ける" có nghĩa là gì?', '(thịt) nướng chín/ (nhà) bị cháy', 'gửi đường hàng không', 'dịch vụ chuyển phát tận nhà', 'nhập học (đại học)', '(thịt) nướng chín/ (nhà) bị cháy', 'generated' from jp_vocab where id = '40915ef3-c2d8-447f-bc71-d2f40d91b6f4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "(thịt) nướng chín/ (nhà) bị cháy"?', '船便', '帰ってくる', '焼ける', '荷物が出る', '焼ける', 'generated' from jp_vocab where id = '40915ef3-c2d8-447f-bc71-d2f40d91b6f4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"焼ける" đọc là gì?', 'にもつがでる', 'やける', 'たくはいびん', 'にゅうがくする', 'やける', 'generated' from jp_vocab where id = '40915ef3-c2d8-447f-bc71-d2f40d91b6f4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 肉がよく_____。', NULL, NULL, NULL, NULL, '焼ける', 'generated' from jp_vocab where id = '40915ef3-c2d8-447f-bc71-d2f40d91b6f4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"留守" có nghĩa là gì?', 'đến (hành lý)', 'vắng nhà, đi vắng', 'nướng', 'chỗ -', 'vắng nhà, đi vắng', 'generated' from jp_vocab where id = 'badab330-6260-417c-8cb4-1aab1b7f36e3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vắng nhà, đi vắng"?', '原因', 'ところ', '留守', '帰ってくる', '留守', 'generated' from jp_vocab where id = 'badab330-6260-417c-8cb4-1aab1b7f36e3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"留守" đọc là gì?', 'にゅうがくする', 'るす', 'ちょうど', 'たくはいびん', 'るす', 'generated' from jp_vocab where id = 'badab330-6260-417c-8cb4-1aab1b7f36e3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 家は_____だった。', NULL, NULL, NULL, NULL, '留守', 'generated' from jp_vocab where id = 'badab330-6260-417c-8cb4-1aab1b7f36e3';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"宅配便" có nghĩa là gì?', 'đến (hành lý)', 'gửi đường biển', 'vừa đúng', 'dịch vụ chuyển phát tận nhà', 'dịch vụ chuyển phát tận nhà', 'generated' from jp_vocab where id = '501d238a-d48f-4a73-92d4-5bde1a43eda6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "dịch vụ chuyển phát tận nhà"?', 'ちょうど', '宅配便', '帰ってくる', 'ところ', '宅配便', 'generated' from jp_vocab where id = '501d238a-d48f-4a73-92d4-5bde1a43eda6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"宅配便" đọc là gì?', 'ふなびん', 'にもつがでる', 'かえってくる', 'たくはいびん', 'たくはいびん', 'generated' from jp_vocab where id = '501d238a-d48f-4a73-92d4-5bde1a43eda6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で送る。', NULL, NULL, NULL, NULL, '宅配便', 'generated' from jp_vocab where id = '501d238a-d48f-4a73-92d4-5bde1a43eda6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"航空便" có nghĩa là gì?', 'dịch vụ chuyển phát tận nhà', 'gửi đường hàng không', 'tình trạng, thể trạng', 'đến (hành lý)', 'gửi đường hàng không', 'generated' from jp_vocab where id = 'eceb0b92-25af-4c6a-8864-e2c806e18561';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "gửi đường hàng không"?', '航空便', '入学する', 'ちょうど', 'こちら', '航空便', 'generated' from jp_vocab where id = 'eceb0b92-25af-4c6a-8864-e2c806e18561';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"航空便" đọc là gì?', 'ばすがでる', 'こうくうびん', 'やく', 'にもつがでる', 'こうくうびん', 'generated' from jp_vocab where id = 'eceb0b92-25af-4c6a-8864-e2c806e18561';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で送る。', NULL, NULL, NULL, NULL, '航空便', 'generated' from jp_vocab where id = 'eceb0b92-25af-4c6a-8864-e2c806e18561';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"船便" có nghĩa là gì?', 'vắng nhà, đi vắng', 'trở về', 'gửi đường biển', 'đến (hành lý)', 'gửi đường biển', 'generated' from jp_vocab where id = '8325249d-79b9-4d1a-b458-1c4f29144e25';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "gửi đường biển"?', '原因', '具合', '留守', '船便', '船便', 'generated' from jp_vocab where id = '8325249d-79b9-4d1a-b458-1c4f29144e25';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"船便" đọc là gì?', 'こちら', 'ふなびん', 'ばすがでる', 'はんとし', 'ふなびん', 'generated' from jp_vocab where id = '8325249d-79b9-4d1a-b458-1c4f29144e25';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で送る。', NULL, NULL, NULL, NULL, '船便', 'generated' from jp_vocab where id = '8325249d-79b9-4d1a-b458-1c4f29144e25';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"原因" có nghĩa là gì?', 'nửa năm', 'đến (hành lý)', 'vắng nhà, đi vắng', 'nguyên nhân', 'nguyên nhân', 'generated' from jp_vocab where id = '33bcc566-9833-4be6-9078-649cc795adaa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nguyên nhân"?', '原因', '航空便', '留守', 'こちら', '原因', 'generated' from jp_vocab where id = '33bcc566-9833-4be6-9078-649cc795adaa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"原因" đọc là gì?', 'げんいん', 'そつぎょうする', 'やける', 'にゅうがくする', 'げんいん', 'generated' from jp_vocab where id = '33bcc566-9833-4be6-9078-649cc795adaa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 事故の_____を調べる。', NULL, NULL, NULL, NULL, '原因', 'generated' from jp_vocab where id = '33bcc566-9833-4be6-9078-649cc795adaa';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"具合" có nghĩa là gì?', 'tình trạng, thể trạng', 'nửa năm', 'đưa, trao', 'xuất phát, rời bến (xe bus)', 'tình trạng, thể trạng', 'generated' from jp_vocab where id = '3aeb8b82-179f-4a08-85b1-8f21976ee5fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tình trạng, thể trạng"?', '渡す', '半年', 'ちょうど', '具合', '具合', 'generated' from jp_vocab where id = '3aeb8b82-179f-4a08-85b1-8f21976ee5fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"具合" đọc là gì?', 'げんいん', 'わたす', 'ぐあい', 'ちょうど', 'ぐあい', 'generated' from jp_vocab where id = '3aeb8b82-179f-4a08-85b1-8f21976ee5fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____が悪い。', NULL, NULL, NULL, NULL, '具合', 'generated' from jp_vocab where id = '3aeb8b82-179f-4a08-85b1-8f21976ee5fd';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"こちら" có nghĩa là gì?', 'phía tôi', 'nửa năm', 'vắng nhà, đi vắng', 'gửi đường hàng không', 'phía tôi', 'generated' from jp_vocab where id = '24490ac4-64d5-43d0-acc5-c4a74f8231f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "phía tôi"?', '宅配便', 'こちら', '船便', '航空便', 'こちら', 'generated' from jp_vocab where id = '24490ac4-64d5-43d0-acc5-c4a74f8231f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"こちら" đọc là gì?', 'こちら', 'にゅうがくする', 'かえってくる', 'ふなびん', 'こちら', 'generated' from jp_vocab where id = '24490ac4-64d5-43d0-acc5-c4a74f8231f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____へどうぞ。', NULL, NULL, NULL, NULL, 'こちら', 'generated' from jp_vocab where id = '24490ac4-64d5-43d0-acc5-c4a74f8231f7';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ところ" có nghĩa là gì?', 'vừa đúng', 'dịch vụ chuyển phát tận nhà', 'chỗ -', 'trở về', 'chỗ -', 'generated' from jp_vocab where id = '38b5d28d-a7f9-41d2-9e03-e59f950e8410';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chỗ -"?', 'ところ', 'こちら', '入学する', '半年', 'ところ', 'generated' from jp_vocab where id = '38b5d28d-a7f9-41d2-9e03-e59f950e8410';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ところ" đọc là gì?', 'ところ', 'やける', 'そつぎょうする', 'ばすがでる', 'ところ', 'generated' from jp_vocab where id = '38b5d28d-a7f9-41d2-9e03-e59f950e8410';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 先生の_____へ行く。', NULL, NULL, NULL, NULL, 'ところ', 'generated' from jp_vocab where id = '38b5d28d-a7f9-41d2-9e03-e59f950e8410';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"半年" có nghĩa là gì?', 'nửa năm', 'trở về', 'gửi đường hàng không', 'nướng', 'nửa năm', 'generated' from jp_vocab where id = 'ed03482e-e27d-492e-a3c1-4278be11fde9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nửa năm"?', 'こちら', '帰ってくる', '半年', '原因', '半年', 'generated' from jp_vocab where id = 'ed03482e-e27d-492e-a3c1-4278be11fde9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"半年" đọc là gì?', 'こうくうびん', 'はんとし', 'るす', 'ところ', 'はんとし', 'generated' from jp_vocab where id = 'ed03482e-e27d-492e-a3c1-4278be11fde9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____前に来た。', NULL, NULL, NULL, NULL, '半年', 'generated' from jp_vocab where id = 'ed03482e-e27d-492e-a3c1-4278be11fde9';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ちょうど" có nghĩa là gì?', 'đưa, trao', 'vừa đúng', 'tình trạng, thể trạng', 'tốt nghiệp (đại học)', 'vừa đúng', 'generated' from jp_vocab where id = '62d15274-d916-4942-a163-562356d69834';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vừa đúng"?', '具合', 'ちょうど', 'バスが出る', '船便', 'ちょうど', 'generated' from jp_vocab where id = '62d15274-d916-4942-a163-562356d69834';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ちょうど" đọc là gì?', 'たくはいびん', 'ところ', 'ちょうど', 'かえってくる', 'ちょうど', 'generated' from jp_vocab where id = '62d15274-d916-4942-a163-562356d69834';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____良かった。', NULL, NULL, NULL, NULL, 'ちょうど', 'generated' from jp_vocab where id = '62d15274-d916-4942-a163-562356d69834';
