-- ============================================================
-- jp-go — Từ vựng N4, 課49 (phần 2, 12 từ còn lại, hoàn tất 課49).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 2 - 語彙,
-- trang in 35.
-- ============================================================

-- ---------- jp_vocab ----------
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('e8daa490-fff0-40bb-964a-32fb6bee8bb4', 'N4', 49, 'word', '医学部', 'いがくぶ', 'Khoa Y', NULL, '名詞', 35, '医学部', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('93c81b66-6df8-4cdf-88a3-f6e1fbcf9f13', 'N4', 49, 'word', '細胞', 'さいぼう', 'tế bào', NULL, '名詞', 35, '細胞', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('b289a81b-504d-4920-99d9-75348bc385e0', 'N4', 49, 'word', '旅館', 'りょかん', 'nhà trọ, lữ quán', NULL, '名詞', 35, '旅館', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('a928fb61-1cb6-4543-b404-701dbfefd55a', 'N4', 49, 'word', '経歴', 'けいれき', 'quá trình làm việc, lý lịch việc làm', NULL, '名詞', 35, '経歴', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('f6bbc1ef-61c2-446b-878e-ba5ebf7937ee', 'N4', 49, 'word', 'バス停', 'バスてい', 'trạm xe bus', NULL, '名詞', 35, 'バス停', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('d7444b12-3009-4164-8c6c-563eef1e59df', 'N4', 49, 'word', '奥様', 'おくさま', 'vợ của người khác (kính ngữ của おくさん)', NULL, '名詞', 35, '奥様', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('ce2329ab-3011-42d2-8b26-e445c71f175c', 'N4', 49, 'word', 'たまに', 'たまに', 'thi thoảng', NULL, '副詞', 35, 'たまに', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('78ad325a-196b-4853-bc45-a00535e17c4c', 'N4', 49, 'word', 'どなたでも', 'どなたでも', 'vị nào cũng (kính ngữ của だれでも)', NULL, '名詞', 35, 'どなたでも', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('45742675-b806-4d69-976f-fb3f7f02e489', 'N4', 49, 'word', '進む', 'すすむ', 'tiến lên; tiến triển', NULL, '動詞', 35, '進む', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('7724a18c-b080-47a7-afa2-60864549c4d6', 'N4', 49, 'word', 'マウス', 'マウス', 'chuột (máy tính)', NULL, '名詞', 35, 'マウス', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('892da7a8-822d-41e8-98c6-66e9ad57d3a0', 'N4', 49, 'word', 'ノーベル賞', 'ノーベルしょう', 'giải Nobel', NULL, '名詞', 35, 'ノーベル賞', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;
insert into jp_vocab (id, level, lesson_no, entry_type, word_jp, reading_furigana, meaning_vi, usage_note_vi, word_class, source_page, source_text, source_type, review_status) values ('63396b6c-c0b3-4b25-ab6f-b04f0a84a930', 'N4', 49, 'word', '受賞', 'じゅしょう', 'nhận giải', NULL, '名詞', 35, '受賞', 'pdf', 'ok')
on conflict (level, lesson_no, word_jp, reading_furigana) do nothing;

-- ---------- jp_vocab_examples ----------
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '医学部に入る。', 'Vào học Khoa Y.', '_____に入る。', '医学部', 'generated' from jp_vocab where id = 'e8daa490-fff0-40bb-964a-32fb6bee8bb4';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '細胞を観察する。', 'Quan sát tế bào.', '_____を観察する。', '細胞', 'generated' from jp_vocab where id = '93c81b66-6df8-4cdf-88a3-f6e1fbcf9f13';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '旅館に泊まる。', 'Ở tại nhà trọ.', '_____に泊まる。', '旅館', 'generated' from jp_vocab where id = 'b289a81b-504d-4920-99d9-75348bc385e0';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '経歴を書く。', 'Viết lý lịch làm việc.', '_____を書く。', '経歴', 'generated' from jp_vocab where id = 'a928fb61-1cb6-4543-b404-701dbfefd55a';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'バス停で待つ。', 'Chờ ở trạm xe bus.', '_____で待つ。', 'バス停', 'generated' from jp_vocab where id = 'f6bbc1ef-61c2-446b-878e-ba5ebf7937ee';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '奥様はお元気ですか。', 'Vợ anh có khỏe không ạ?', '_____はお元気ですか。', '奥様', 'generated' from jp_vocab where id = 'd7444b12-3009-4164-8c6c-563eef1e59df';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'たまに映画を見る。', 'Thi thoảng xem phim.', '_____映画を見る。', 'たまに', 'generated' from jp_vocab where id = 'ce2329ab-3011-42d2-8b26-e445c71f175c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'どなたでも参加できます。', 'Vị nào cũng có thể tham gia.', '_____参加できます。', 'どなたでも', 'generated' from jp_vocab where id = '78ad325a-196b-4853-bc45-a00535e17c4c';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '計画が進む。', 'Kế hoạch tiến triển.', '計画が_____。', '進む', 'generated' from jp_vocab where id = '45742675-b806-4d69-976f-fb3f7f02e489';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'マウスを動かす。', 'Di chuyển chuột (máy tính).', '_____を動かす。', 'マウス', 'generated' from jp_vocab where id = '7724a18c-b080-47a7-afa2-60864549c4d6';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, 'ノーベル賞を取る。', 'Đoạt giải Nobel.', '_____を取る。', 'ノーベル賞', 'generated' from jp_vocab where id = '892da7a8-822d-41e8-98c6-66e9ad57d3a0';
insert into jp_vocab_examples (vocab_id, example_jp, example_vi, cloze_jp, answer, source_type) select id, '賞を受賞する。', 'Nhận giải thưởng.', '賞を_____する。', '受賞', 'generated' from jp_vocab where id = '63396b6c-c0b3-4b25-ab6f-b04f0a84a930';

-- ---------- jp_vocab_questions ----------
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"医学部" có nghĩa là gì?', 'nhà trọ, lữ quán', 'trạm xe bus', 'chuột (máy tính)', 'Khoa Y', 'Khoa Y', 'generated' from jp_vocab where id = 'e8daa490-fff0-40bb-964a-32fb6bee8bb4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "Khoa Y"?', '進む', '医学部', 'マウス', 'ノーベル賞', '医学部', 'generated' from jp_vocab where id = 'e8daa490-fff0-40bb-964a-32fb6bee8bb4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"医学部" đọc là gì?', 'いがくぶ', 'すすむ', 'ノーベルしょう', 'りょかん', 'いがくぶ', 'generated' from jp_vocab where id = 'e8daa490-fff0-40bb-964a-32fb6bee8bb4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に入る。', NULL, NULL, NULL, NULL, '医学部', 'generated' from jp_vocab where id = 'e8daa490-fff0-40bb-964a-32fb6bee8bb4';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"細胞" có nghĩa là gì?', 'tế bào', 'nhà trọ, lữ quán', 'chuột (máy tính)', 'vị nào cũng (kính ngữ của だれでも)', 'tế bào', 'generated' from jp_vocab where id = '93c81b66-6df8-4cdf-88a3-f6e1fbcf9f13';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tế bào"?', '進む', '経歴', '医学部', '細胞', '細胞', 'generated' from jp_vocab where id = '93c81b66-6df8-4cdf-88a3-f6e1fbcf9f13';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"細胞" đọc là gì?', 'すすむ', 'どなたでも', 'さいぼう', 'マウス', 'さいぼう', 'generated' from jp_vocab where id = '93c81b66-6df8-4cdf-88a3-f6e1fbcf9f13';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を観察する。', NULL, NULL, NULL, NULL, '細胞', 'generated' from jp_vocab where id = '93c81b66-6df8-4cdf-88a3-f6e1fbcf9f13';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"旅館" có nghĩa là gì?', 'trạm xe bus', 'tế bào', 'nhà trọ, lữ quán', 'tiến lên; tiến triển', 'nhà trọ, lữ quán', 'generated' from jp_vocab where id = 'b289a81b-504d-4920-99d9-75348bc385e0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhà trọ, lữ quán"?', '旅館', '医学部', '進む', 'バス停', '旅館', 'generated' from jp_vocab where id = 'b289a81b-504d-4920-99d9-75348bc385e0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"旅館" đọc là gì?', 'たまに', 'りょかん', 'じゅしょう', 'さいぼう', 'りょかん', 'generated' from jp_vocab where id = 'b289a81b-504d-4920-99d9-75348bc385e0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____に泊まる。', NULL, NULL, NULL, NULL, '旅館', 'generated' from jp_vocab where id = 'b289a81b-504d-4920-99d9-75348bc385e0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"経歴" có nghĩa là gì?', 'trạm xe bus', 'Khoa Y', 'tế bào', 'quá trình làm việc, lý lịch việc làm', 'quá trình làm việc, lý lịch việc làm', 'generated' from jp_vocab where id = 'a928fb61-1cb6-4543-b404-701dbfefd55a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "quá trình làm việc, lý lịch việc làm"?', 'ノーベル賞', 'マウス', '経歴', 'どなたでも', '経歴', 'generated' from jp_vocab where id = 'a928fb61-1cb6-4543-b404-701dbfefd55a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"経歴" đọc là gì?', 'マウス', 'たまに', 'いがくぶ', 'けいれき', 'けいれき', 'generated' from jp_vocab where id = 'a928fb61-1cb6-4543-b404-701dbfefd55a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を書く。', NULL, NULL, NULL, NULL, '経歴', 'generated' from jp_vocab where id = 'a928fb61-1cb6-4543-b404-701dbfefd55a';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"バス停" có nghĩa là gì?', 'vị nào cũng (kính ngữ của だれでも)', 'thi thoảng', 'Khoa Y', 'trạm xe bus', 'trạm xe bus', 'generated' from jp_vocab where id = 'f6bbc1ef-61c2-446b-878e-ba5ebf7937ee';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "trạm xe bus"?', 'どなたでも', 'たまに', 'バス停', '旅館', 'バス停', 'generated' from jp_vocab where id = 'f6bbc1ef-61c2-446b-878e-ba5ebf7937ee';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"バス停" đọc là gì?', 'バスてい', 'マウス', 'ノーベルしょう', 'いがくぶ', 'バスてい', 'generated' from jp_vocab where id = 'f6bbc1ef-61c2-446b-878e-ba5ebf7937ee';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____で待つ。', NULL, NULL, NULL, NULL, 'バス停', 'generated' from jp_vocab where id = 'f6bbc1ef-61c2-446b-878e-ba5ebf7937ee';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"奥様" có nghĩa là gì?', 'nhà trọ, lữ quán', 'trạm xe bus', 'vợ của người khác (kính ngữ của おくさん)', 'Khoa Y', 'vợ của người khác (kính ngữ của おくさん)', 'generated' from jp_vocab where id = 'd7444b12-3009-4164-8c6c-563eef1e59df';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vợ của người khác (kính ngữ của おくさん)"?', 'どなたでも', '進む', 'たまに', '奥様', '奥様', 'generated' from jp_vocab where id = 'd7444b12-3009-4164-8c6c-563eef1e59df';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"奥様" đọc là gì?', 'けいれき', 'おくさま', 'さいぼう', 'りょかん', 'おくさま', 'generated' from jp_vocab where id = 'd7444b12-3009-4164-8c6c-563eef1e59df';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____はお元気ですか。', NULL, NULL, NULL, NULL, '奥様', 'generated' from jp_vocab where id = 'd7444b12-3009-4164-8c6c-563eef1e59df';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"たまに" có nghĩa là gì?', 'vị nào cũng (kính ngữ của だれでも)', 'chuột (máy tính)', 'vợ của người khác (kính ngữ của おくさん)', 'thi thoảng', 'thi thoảng', 'generated' from jp_vocab where id = 'ce2329ab-3011-42d2-8b26-e445c71f175c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "thi thoảng"?', '進む', 'たまに', '受賞', '経歴', 'たまに', 'generated' from jp_vocab where id = 'ce2329ab-3011-42d2-8b26-e445c71f175c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"たまに" đọc là gì?', 'じゅしょう', 'ノーベルしょう', 'すすむ', 'たまに', 'たまに', 'generated' from jp_vocab where id = 'ce2329ab-3011-42d2-8b26-e445c71f175c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____映画を見る。', NULL, NULL, NULL, NULL, 'たまに', 'generated' from jp_vocab where id = 'ce2329ab-3011-42d2-8b26-e445c71f175c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"どなたでも" có nghĩa là gì?', 'vị nào cũng (kính ngữ của だれでも)', 'chuột (máy tính)', 'tiến lên; tiến triển', 'tế bào', 'vị nào cũng (kính ngữ của だれでも)', 'generated' from jp_vocab where id = '78ad325a-196b-4853-bc45-a00535e17c4c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "vị nào cũng (kính ngữ của だれでも)"?', 'どなたでも', '進む', '医学部', 'バス停', 'どなたでも', 'generated' from jp_vocab where id = '78ad325a-196b-4853-bc45-a00535e17c4c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"どなたでも" đọc là gì?', 'どなたでも', 'バスてい', 'ノーベルしょう', 'すすむ', 'どなたでも', 'generated' from jp_vocab where id = '78ad325a-196b-4853-bc45-a00535e17c4c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____参加できます。', NULL, NULL, NULL, NULL, 'どなたでも', 'generated' from jp_vocab where id = '78ad325a-196b-4853-bc45-a00535e17c4c';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"進む" có nghĩa là gì?', 'tiến lên; tiến triển', 'vị nào cũng (kính ngữ của だれでも)', 'vợ của người khác (kính ngữ của おくさん)', 'nhà trọ, lữ quán', 'tiến lên; tiến triển', 'generated' from jp_vocab where id = '45742675-b806-4d69-976f-fb3f7f02e489';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "tiến lên; tiến triển"?', 'ノーベル賞', 'バス停', '進む', '経歴', '進む', 'generated' from jp_vocab where id = '45742675-b806-4d69-976f-fb3f7f02e489';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"進む" đọc là gì?', 'すすむ', 'いがくぶ', 'マウス', 'どなたでも', 'すすむ', 'generated' from jp_vocab where id = '45742675-b806-4d69-976f-fb3f7f02e489';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 計画が_____。', NULL, NULL, NULL, NULL, '進む', 'generated' from jp_vocab where id = '45742675-b806-4d69-976f-fb3f7f02e489';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"マウス" có nghĩa là gì?', 'thi thoảng', 'quá trình làm việc, lý lịch việc làm', 'nhà trọ, lữ quán', 'chuột (máy tính)', 'chuột (máy tính)', 'generated' from jp_vocab where id = '7724a18c-b080-47a7-afa2-60864549c4d6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "chuột (máy tính)"?', 'マウス', '経歴', 'たまに', 'バス停', 'マウス', 'generated' from jp_vocab where id = '7724a18c-b080-47a7-afa2-60864549c4d6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"マウス" đọc là gì?', 'いがくぶ', 'りょかん', 'じゅしょう', 'マウス', 'マウス', 'generated' from jp_vocab where id = '7724a18c-b080-47a7-afa2-60864549c4d6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を動かす。', NULL, NULL, NULL, NULL, 'マウス', 'generated' from jp_vocab where id = '7724a18c-b080-47a7-afa2-60864549c4d6';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"ノーベル賞" có nghĩa là gì?', 'trạm xe bus', 'giải Nobel', 'nhà trọ, lữ quán', 'Khoa Y', 'giải Nobel', 'generated' from jp_vocab where id = '892da7a8-822d-41e8-98c6-66e9ad57d3a0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "giải Nobel"?', 'マウス', 'どなたでも', '進む', 'ノーベル賞', 'ノーベル賞', 'generated' from jp_vocab where id = '892da7a8-822d-41e8-98c6-66e9ad57d3a0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"ノーベル賞" đọc là gì?', 'りょかん', 'ノーベルしょう', 'さいぼう', 'どなたでも', 'ノーベルしょう', 'generated' from jp_vocab where id = '892da7a8-822d-41e8-98c6-66e9ad57d3a0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: _____を取る。', NULL, NULL, NULL, NULL, 'ノーベル賞', 'generated' from jp_vocab where id = '892da7a8-822d-41e8-98c6-66e9ad57d3a0';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_meaning', '"受賞" có nghĩa là gì?', 'nhận giải', 'thi thoảng', 'quá trình làm việc, lý lịch việc làm', 'tế bào', 'nhận giải', 'generated' from jp_vocab where id = '63396b6c-c0b3-4b25-ab6f-b04f0a84a930';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_word_from_meaning', 'Từ nào có nghĩa "nhận giải"?', 'マウス', '旅館', '受賞', 'たまに', '受賞', 'generated' from jp_vocab where id = '63396b6c-c0b3-4b25-ab6f-b04f0a84a930';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'choose_reading', '"受賞" đọc là gì?', 'じゅしょう', 'りょかん', 'おくさま', 'ノーベルしょう', 'じゅしょう', 'generated' from jp_vocab where id = '63396b6c-c0b3-4b25-ab6f-b04f0a84a930';
insert into jp_vocab_questions (vocab_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) select id, 'fill_blank', 'Điền từ còn thiếu: 賞を_____する。', NULL, NULL, NULL, NULL, '受賞', 'generated' from jp_vocab where id = '63396b6c-c0b3-4b25-ab6f-b04f0a84a930';
