-- ============================================================
-- jp-go — Ngữ pháp N4, PILOT (12 mẫu, trang in 38).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 3 - 文法.
-- ============================================================

-- ---------- jp_grammar ----------
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('e782a64b-7797-4519-a216-0e7cf3876aae', 'N4', 'Vていただけませんか', 'Anh/chị ~ giúp tôi được không ạ?', 'いただけませんか = xin phép nhờ ai đó làm gì một cách lịch sự, khiêm nhường', 'V-て + いただけませんか', 'Nhờ vả ai đó làm gì một cách lịch sự, khiêm nhường', 'lịch sự, khiêm nhường ngữ', NULL, NULL, '{}', NULL, 38, 'Vていただけませんか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('a67d61dd-d9a9-4672-9e3e-1b068628ce30', 'N4', '疑問詞 + Vたらいいですか', 'Nên làm như thế nào bây giờ', 'たら + いいですか = hỏi xin ý kiến/lời khuyên', '疑問詞(どう/何/どうやって...) + V(thể た) + らいいですか', 'Hỏi xin lời khuyên/ý kiến nên làm gì', NULL, NULL, NULL, '{}', NULL, 38, '疑問詞 + Vたらいいですか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'N4', 'Vる/Vた/Vない/Aい/A/Nな + んです', 'Giải thích lý do, mào đầu, làm mềm câu', 'んです thêm sắc thái giải thích/xin thông cảm vào câu nói', NULL, NULL, NULL, NULL, NULL, '{}', NULL, 38, 'Vる/Vた/Vない/Aい/A/Nな + んです', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('60671dc5-7e07-4c22-a037-8627c03f4041', 'N4', 'N + が + V(thể khả năng)', 'Thể khả năng (có thể làm gì)', 'Trợ từ を của động từ gốc chuyển thành が khi chia thể khả năng', 'N + が + V(thể khả năng)', 'Diễn tả khả năng làm được việc gì', NULL, NULL, NULL, '{}', NULL, 38, 'N + が + V(thể khả năng)', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('af1ae8f4-759e-4b1e-8882-078bce1a6704', 'N4', 'N1は(+)が、N2は(−)', 'N1 thì ~, nhưng N2 thì ~', 'Đối lập 2 mệnh đề bằng が (nhưng)', 'N1は...ますが、N2はあまり...ません', 'So sánh đối lập khả năng/tình trạng giữa 2 đối tượng', NULL, NULL, NULL, '{}', NULL, 38, 'N1は(+)が、N2は(−)', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('cc6ef598-1afe-463d-931d-d156b4853140', 'N4', 'Nができます。/ Vることができます。', 'Có thể làm / Hoàn thành', 'できる = có thể / xong việc, tùy ngữ cảnh', NULL, NULL, NULL, NULL, NULL, '{}', NULL, 38, 'Nができます。/ Vることができます。', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('a89d36cb-09f1-4928-8523-5e1a8c998a04', 'N4', 'V1ながら、V2', 'Vừa làm việc này, vừa làm việc kia', 'V1(dạng ます, bỏ ます) + ながら', 'V1(bỏ ます) + ながら、V2', 'Diễn tả 2 hành động xảy ra đồng thời', NULL, NULL, NULL, '{}', NULL, 38, 'V1ながら、V2', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('335d2a21-37a3-465e-82e8-859150378ad1', 'N4', 'V1ながら、Vる人が + すき・きらい', 'Thích/Ghét ai đó vừa làm việc này, vừa làm việc kia', 'Áp dụng ながら vào việc nhận xét thói quen của người khác', 'V1ながら + V2る + 人が + 好き／嫌い', 'Bày tỏ cảm xúc thích/ghét về người có thói quen làm 2 việc cùng lúc', NULL, NULL, NULL, '{}', NULL, 38, 'V1ながら、Vる人が + すき・きらい', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('ba4501f1-49b2-43e1-a212-342d92c7b396', 'N4', 'Sは~し、~し、(それに)~', 'Liệt kê các tính chất tương đồng nhau', 'し liệt kê nhiều lý do/tính chất cùng chiều, それに = hơn nữa', 'Sは...し、...し、(それに)...', 'Liệt kê nhiều đặc điểm tốt (hoặc xấu) cùng chiều về 1 chủ thể', NULL, NULL, NULL, '{}', NULL, 38, 'Sは~し、~し、(それに)~', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('6b9cb65b-d7ba-4517-9e9f-d6333da777d8', 'N4', 'Sは~し、~し、(それで)~', 'Liệt kê lý do', 'し liệt kê nhiều lý do, それで = vì thế (kết quả)', 'Sは...し、...し、(それで)...', 'Liệt kê nhiều lý do dẫn đến 1 kết quả/hành động', NULL, NULL, NULL, '{}', NULL, 38, 'Sは~し、~し、(それで)~', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('ee3a4296-4cf9-4b33-a9f2-a76e7828de18', 'N4', 'いつもVています', 'Diễn tả thói quen', 'いつも + V-て + います = luôn luôn làm gì (thói quen)', 'いつも + V-て + います', 'Diễn tả thói quen lặp đi lặp lại', NULL, NULL, NULL, '{}', NULL, 38, 'いつもVています', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', 'N4', 'Vてしまう', 'Hoàn thành / Lỡ làm gì đó (tiếc nuối)', 'てしまう mang 2 sắc thái: hoàn thành trọn vẹn, hoặc lỡ làm (tiếc nuối)', NULL, NULL, NULL, NULL, NULL, '{}', NULL, 38, 'Vてしまう', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;

-- ---------- jp_grammar_usages (chỉ tạo khi multi_usage) ----------
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('3aa11b61-0d9a-4e94-b2fe-53f54e893a96', '0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 1, 'Mào đầu cho cách nói nhờ vả, xin ý kiến', 'Vる/Vた/Vない・Aい・Aな・Nな + んです', NULL, NULL, 38, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('efeea555-90b8-4543-b4de-b0661faf07ce', '0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 2, 'Dùng trong câu hỏi nguyên nhân lí do', 'Vる/Vた/Vない・Aい・Aな・Nな + んです', NULL, NULL, 38, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('e6636fdc-ecb7-4c28-927f-d06f5aef196b', '0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 3, 'Làm mềm câu và tìm hiểu sự tình đối phương', 'Vる/Vた/Vない・Aい・Aな・Nな + んです', NULL, NULL, 38, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('7f075403-f8d8-4890-8342-c92660c69dbe', 'cc6ef598-1afe-463d-931d-d156b4853140', 1, 'Có thể làm gì', 'N + ができます／V(từ điển) + ことができます', NULL, NULL, 38, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('d228ae81-21d0-4f35-b915-3ee5634dfd56', 'cc6ef598-1afe-463d-931d-d156b4853140', 2, 'Làm xong, hoàn thành', 'N + ができます／V(từ điển) + ことができます', NULL, NULL, 38, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('13975bb7-2450-410d-9fd6-0016157b797c', 'eae25fb4-1d8d-4910-a34f-d4bb93063ff2', 1, 'Hoàn thành, sẽ làm xong', 'V-て + しまう', NULL, NULL, 38, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('d613d477-5cf0-4236-a681-05fa172d49e0', 'eae25fb4-1d8d-4910-a34f-d4bb93063ff2', 2, 'Lỡ làm gì đó, thể hiện tâm trạng tiếc nuối', 'V-て + しまう', NULL, NULL, 38, 'pdf');

-- ---------- jp_grammar_examples ----------
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e782a64b-7797-4519-a216-0e7cf3876aae', NULL, 1, 'daily', 'いい先生を紹介していただけませんか。', 'Bạn có thể giới thiệu giúp tôi một giáo viên giỏi không?', 'いい先生を＿＿＿。', '紹介していただけませんか', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e782a64b-7797-4519-a216-0e7cf3876aae', NULL, 2, 'daily', 'この漢字の読み方を教えていただけませんか。', 'Bạn có thể dạy tôi cách đọc kanji này không ạ?', 'この漢字の読み方を＿＿＿。', '教えていただけませんか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e782a64b-7797-4519-a216-0e7cf3876aae', NULL, 3, 'daily', '明日、少し早く来ていただけませんか。', 'Ngày mai anh/chị có thể đến sớm một chút được không ạ?', '明日、少し早く＿＿＿。', '来ていただけませんか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a67d61dd-d9a9-4672-9e3e-1b068628ce30', NULL, 1, 'daily', 'バレンタインデーに女性に何をあげたらいいですか。', 'Nên tặng gì cho bạn gái vào ngày Valentine nhỉ?', 'バレンタインデーに女性に＿＿＿。', '何をあげたらいいですか', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a67d61dd-d9a9-4672-9e3e-1b068628ce30', NULL, 2, 'daily', 'この漢字はどう読んだらいいですか。', 'Kanji này nên đọc như thế nào nhỉ?', 'この漢字は＿＿＿。', 'どう読んだらいいですか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a67d61dd-d9a9-4672-9e3e-1b068628ce30', NULL, 3, 'daily', '駅までどうやって行ったらいいですか。', 'Nên đi đến ga bằng cách nào nhỉ?', '駅まで＿＿＿。', 'どうやって行ったらいいですか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', '3aa11b61-0d9a-4e94-b2fe-53f54e893a96', 1, 'daily', 'まだよくわからないんですが、もう一度教えていただけませんか。', 'Tôi chưa hiểu rõ, bạn có thể chỉ lại cho tôi 1 lần nữa được không?', 'まだよくわからない＿＿＿が、もう一度教えていただけませんか。', 'んです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', '3aa11b61-0d9a-4e94-b2fe-53f54e893a96', 2, 'daily', '明日、旅行に行くんですが、天気は大丈夫でしょうか。', 'Ngày mai tôi đi du lịch, không biết thời tiết có ổn không nhỉ.', '明日、旅行に行く＿＿＿が、天気は大丈夫でしょうか。', 'んです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', '3aa11b61-0d9a-4e94-b2fe-53f54e893a96', 3, 'daily', '今、忙しいんですが、後で連絡してもいいですか。', 'Bây giờ tôi đang bận, lát nữa liên lạc lại có được không?', '今、忙しい＿＿＿が、後で連絡してもいいですか。', 'んです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'efeea555-90b8-4543-b4de-b0661faf07ce', 1, 'daily', 'どうして遅れたんですか。バスが来なかったんです。', 'Tại sao bạn lại đến muộn? Bởi vì xe buýt đã không tới.', 'どうして遅れた＿＿＿か。', 'んです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'efeea555-90b8-4543-b4de-b0661faf07ce', 2, 'daily', 'どうして食べないんですか。お腹がいっぱいなんです。', 'Tại sao bạn không ăn? Vì tôi no rồi.', 'どうして食べない＿＿＿か。', 'んです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'efeea555-90b8-4543-b4de-b0661faf07ce', 3, 'daily', 'どうして休んだんですか。風邪をひいたんです。', 'Tại sao bạn nghỉ? Vì tôi bị cảm.', 'どうして休んだ＿＿＿か。', 'んです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'e6636fdc-ecb7-4c28-927f-d06f5aef196b', 1, 'daily', 'どうしたんですか。調子が悪いんです。', 'Bạn sao thế? Tôi không được khỏe.', 'どうした＿＿＿か。', 'んです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'e6636fdc-ecb7-4c28-927f-d06f5aef196b', 2, 'daily', '顔色が悪いですね。どうしたんですか。ちょっと疲れているんです。', 'Sắc mặt bạn không tốt nhỉ. Bạn sao thế? Tôi hơi mệt.', '顔色が悪いですね。どうした＿＿＿か。', 'んです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'e6636fdc-ecb7-4c28-927f-d06f5aef196b', 3, 'daily', '何を探しているんですか。鍵を探しているんです。', 'Bạn đang tìm gì vậy? Tôi đang tìm chìa khóa.', '何を探している＿＿＿か。', 'んです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('60671dc5-7e07-4c22-a037-8627c03f4041', NULL, 1, 'daily', '漢字が書ける。', 'Tôi có thể viết chữ Hán.', '漢字が＿＿＿。', '書ける', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('60671dc5-7e07-4c22-a037-8627c03f4041', NULL, 2, 'daily', '彼はピアノが弾ける。', 'Anh ấy có thể chơi piano.', '彼はピアノが＿＿＿。', '弾ける', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('60671dc5-7e07-4c22-a037-8627c03f4041', NULL, 3, 'daily', '私は辛い物が食べられる。', 'Tôi có thể ăn đồ cay.', '私は辛い物が＿＿＿。', '食べられる', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('af1ae8f4-759e-4b1e-8882-078bce1a6704', NULL, 1, 'daily', '日本語は話せますが、英語はあまり話せません。', 'Tôi có thể nói tiếng Nhật nhưng tiếng Anh thì không.', '日本語は話せますが、英語は＿＿＿。', 'あまり話せません', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('af1ae8f4-759e-4b1e-8882-078bce1a6704', NULL, 2, 'daily', '漢字は読めますが、書くのは難しいです。', 'Tôi đọc được kanji nhưng viết thì khó.', '漢字は読めますが、書くのは＿＿＿。', '難しいです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('af1ae8f4-759e-4b1e-8882-078bce1a6704', NULL, 3, 'daily', '肉は食べますが、魚はあまり食べません。', 'Tôi ăn thịt nhưng cá thì ít khi ăn.', '肉は食べますが、魚は＿＿＿。', 'あまり食べません', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('cc6ef598-1afe-463d-931d-d156b4853140', '7f075403-f8d8-4890-8342-c92660c69dbe', 1, 'daily', 'テニスができます。', 'Tôi có thể chơi tennis.', 'テニスが＿＿＿。', 'できます', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('cc6ef598-1afe-463d-931d-d156b4853140', '7f075403-f8d8-4890-8342-c92660c69dbe', 2, 'daily', '漢字を書くことができます。', 'Tôi có thể viết chữ Hán.', '漢字を書く＿＿＿。', 'ことができます', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('cc6ef598-1afe-463d-931d-d156b4853140', '7f075403-f8d8-4890-8342-c92660c69dbe', 3, 'daily', '車を運転することができます。', 'Tôi có thể lái xe ô tô.', '車を運転する＿＿＿。', 'ことができます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('cc6ef598-1afe-463d-931d-d156b4853140', 'd228ae81-21d0-4f35-b915-3ee5634dfd56', 1, 'daily', 'レポートはいつできますか。明日できます。', 'Khi nào bạn có thể làm xong báo cáo? Ngày mai tôi có thể làm xong.', 'レポートはいつ＿＿＿か。', 'できます', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('cc6ef598-1afe-463d-931d-d156b4853140', 'd228ae81-21d0-4f35-b915-3ee5634dfd56', 2, 'daily', '宿題はもうできましたか。はい、もうできました。', 'Bài tập đã xong chưa? Vâng, xong rồi.', '宿題はもう＿＿＿か。', 'できました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('cc6ef598-1afe-463d-931d-d156b4853140', 'd228ae81-21d0-4f35-b915-3ee5634dfd56', 3, 'daily', 'この仕事は今日中にできますか。はい、できます。', 'Công việc này có thể xong trong hôm nay không? Vâng, được.', 'この仕事は今日中に＿＿＿か。', 'できますか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a89d36cb-09f1-4928-8523-5e1a8c998a04', NULL, 1, 'daily', 'テレビを見ながら、ご飯を食べます。', 'Chúng tôi vừa ăn cơm vừa xem TV.', 'テレビを＿＿＿、ご飯を食べます。', '見ながら', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a89d36cb-09f1-4928-8523-5e1a8c998a04', NULL, 2, 'daily', '音楽を聞きながら、勉強します。', 'Vừa nghe nhạc vừa học bài.', '音楽を＿＿＿、勉強します。', '聞きながら', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a89d36cb-09f1-4928-8523-5e1a8c998a04', NULL, 3, 'daily', '歩きながら、電話で話します。', 'Vừa đi bộ vừa nói chuyện điện thoại.', '＿＿＿、電話で話します。', '歩きながら', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('335d2a21-37a3-465e-82e8-859150378ad1', NULL, 1, 'daily', '電話を使いながらご飯を食べる人がきらいです。', 'Tôi ghét người mà vừa ăn cơm vừa dùng điện thoại.', '電話を使いながらご飯を食べる人が＿＿＿。', 'きらいです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('335d2a21-37a3-465e-82e8-859150378ad1', NULL, 2, 'daily', '音楽を聞きながら勉強する人が好きです。', 'Tôi thích người vừa nghe nhạc vừa học bài.', '音楽を聞きながら勉強する人が＿＿＿。', '好きです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('335d2a21-37a3-465e-82e8-859150378ad1', NULL, 3, 'daily', '歩きながらタバコを吸う人がきらいです。', 'Tôi ghét người vừa đi bộ vừa hút thuốc.', '歩きながらタバコを吸う人が＿＿＿。', 'きらいです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ba4501f1-49b2-43e1-a212-342d92c7b396', NULL, 1, 'daily', '先生は面白いし、親切だし、それに経験もあります。', 'Giáo viên vui tính, tốt bụng, hơn nữa còn giàu kinh nghiệm.', '先生は面白いし、親切だし、＿＿＿経験もあります。', 'それに', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ba4501f1-49b2-43e1-a212-342d92c7b396', NULL, 2, 'daily', 'この店は安いし、おいしいし、それに店員も親切です。', 'Quán này rẻ, ngon, hơn nữa nhân viên còn thân thiện.', 'この店は安いし、おいしいし、＿＿＿店員も親切です。', 'それに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ba4501f1-49b2-43e1-a212-342d92c7b396', NULL, 3, 'daily', '彼は頭がいいし、優しいし、それにハンサムです。', 'Anh ấy thông minh, hiền lành, hơn nữa còn đẹp trai.', '彼は頭がいいし、優しいし、＿＿＿ハンサムです。', 'それに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('6b9cb65b-d7ba-4517-9e9f-d6333da777d8', NULL, 1, 'daily', '雨も降っているし、荷物も多いし、それでタクシーで帰りました。', 'Trời mưa và có rất nhiều hành lý, vì vậy tôi đã bắt taxi về nhà.', '雨も降っているし、荷物も多いし、＿＿＿タクシーで帰りました。', 'それで', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('6b9cb65b-d7ba-4517-9e9f-d6333da777d8', NULL, 2, 'daily', '頭も痛いし、熱もあるし、それで会社を休みました。', 'Đau đầu và có sốt, vì vậy tôi đã nghỉ làm.', '頭も痛いし、熱もあるし、＿＿＿会社を休みました。', 'それで', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('6b9cb65b-d7ba-4517-9e9f-d6333da777d8', NULL, 3, 'daily', '道も混んでいるし、時間もないし、それで電車で行きました。', 'Đường tắc và không có thời gian, vì vậy tôi đã đi bằng tàu điện.', '道も混んでいるし、時間もないし、＿＿＿電車で行きました。', 'それで', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ee3a4296-4cf9-4b33-a9f2-a76e7828de18', NULL, 1, 'daily', '暇なとき、いつもテレビを見ています。', 'Lúc rảnh rồi tôi thường xem TV.', '暇なとき、いつも＿＿＿。', 'テレビを見ています', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ee3a4296-4cf9-4b33-a9f2-a76e7828de18', NULL, 2, 'daily', '毎朝、いつも六時に起きています。', 'Mỗi sáng tôi luôn dậy lúc 6 giờ.', '毎朝、いつも＿＿＿。', '六時に起きています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ee3a4296-4cf9-4b33-a9f2-a76e7828de18', NULL, 3, 'daily', '休みの日は、いつも家で本を読んでいます。', 'Ngày nghỉ tôi luôn đọc sách ở nhà.', '休みの日は、いつも＿＿＿。', '家で本を読んでいます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', '13975bb7-2450-410d-9fd6-0016157b797c', 1, 'daily', '今、このマンガを読んでしまいます。', 'Tôi sẽ đọc cuốn manga này ngay bây giờ.', '今、このマンガを＿＿＿。', '読んでしまいます', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', '13975bb7-2450-410d-9fd6-0016157b797c', 2, 'daily', '宿題を今日中にやってしまいます。', 'Tôi sẽ làm xong bài tập trong hôm nay.', '宿題を今日中に＿＿＿。', 'やってしまいます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', '13975bb7-2450-410d-9fd6-0016157b797c', 3, 'daily', 'この本を今週中に読んでしまいます。', 'Tôi sẽ đọc xong cuốn sách này trong tuần này.', 'この本を今週中に＿＿＿。', '読んでしまいます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', 'd613d477-5cf0-4236-a681-05fa172d49e0', 1, 'daily', '財布を忘れてしまいました。', 'Tôi đã lỡ quên ví mất rồi.', '財布を＿＿＿。', '忘れてしまいました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', 'd613d477-5cf0-4236-a681-05fa172d49e0', 2, 'daily', '大事な書類をなくしてしまいました。', 'Tôi đã lỡ làm mất tài liệu quan trọng.', '大事な書類を＿＿＿。', 'なくしてしまいました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', 'd613d477-5cf0-4236-a681-05fa172d49e0', 3, 'daily', '電車の中で財布をすられてしまいました。', 'Tôi đã bị móc mất ví trên tàu điện.', '電車の中で財布を＿＿＿。', 'すられてしまいました', 'generated');

-- ---------- jp_grammar_questions (toàn bộ generated) ----------
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e782a64b-7797-4519-a216-0e7cf3876aae', NULL, 'fill_blank', 'Điền vào chỗ trống: いい先生を＿＿＿。', NULL, NULL, NULL, NULL, '紹介していただけませんか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e782a64b-7797-4519-a216-0e7cf3876aae', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vていただけませんか" có nghĩa nào sau đây?', 'Nên làm như thế nào bây giờ', 'Liệt kê lý do', 'Liệt kê các tính chất tương đồng nhau', 'Anh/chị ~ giúp tôi được không ạ?', 'Anh/chị ~ giúp tôi được không ạ?', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e782a64b-7797-4519-a216-0e7cf3876aae', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Anh/chị ~ giúp tôi được không ạ?"?', 'Vていただけませんか', 'Vる/Vた/Vない/Aい/A/Nな + んです', 'Vてしまう', 'Nができます。/ Vることができます。', 'Vていただけませんか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a67d61dd-d9a9-4672-9e3e-1b068628ce30', NULL, 'fill_blank', 'Điền vào chỗ trống: バレンタインデーに女性に＿＿＿。', NULL, NULL, NULL, NULL, '何をあげたらいいですか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a67d61dd-d9a9-4672-9e3e-1b068628ce30', NULL, 'choose_meaning', 'Mẫu ngữ pháp "疑問詞 + Vたらいいですか" có nghĩa nào sau đây?', 'Nên làm như thế nào bây giờ', 'Diễn tả thói quen', 'N1 thì ~, nhưng N2 thì ~', 'Anh/chị ~ giúp tôi được không ạ?', 'Nên làm như thế nào bây giờ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a67d61dd-d9a9-4672-9e3e-1b068628ce30', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Nên làm như thế nào bây giờ"?', 'V1ながら、Vる人が + すき・きらい', 'Vていただけませんか', '疑問詞 + Vたらいいですか', 'いつもVています', '疑問詞 + Vたらいいですか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', '3aa11b61-0d9a-4e94-b2fe-53f54e893a96', 'fill_blank', 'Điền vào chỗ trống: まだよくわからない＿＿＿が、もう一度教えていただけませんか。', NULL, NULL, NULL, NULL, 'んです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', '3aa11b61-0d9a-4e94-b2fe-53f54e893a96', 'choose_meaning', 'Mẫu ngữ pháp "Vる/Vた/Vない/Aい/A/Nな + んです" có nghĩa nào sau đây?', 'Mào đầu cho cách nói nhờ vả, xin ý kiến', 'Thể khả năng (có thể làm gì)', 'Liệt kê lý do', 'Hoàn thành / Lỡ làm gì đó (tiếc nuối)', 'Mào đầu cho cách nói nhờ vả, xin ý kiến', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', '3aa11b61-0d9a-4e94-b2fe-53f54e893a96', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Mào đầu cho cách nói nhờ vả, xin ý kiến"?', 'V1ながら、Vる人が + すき・きらい', 'N + が + V(thể khả năng)', 'Vる/Vた/Vない/Aい/A/Nな + んです', 'Vていただけませんか', 'Vる/Vた/Vない/Aい/A/Nな + んです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'efeea555-90b8-4543-b4de-b0661faf07ce', 'fill_blank', 'Điền vào chỗ trống: どうして遅れた＿＿＿か。', NULL, NULL, NULL, NULL, 'んです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'efeea555-90b8-4543-b4de-b0661faf07ce', 'choose_meaning', 'Mẫu ngữ pháp "Vる/Vた/Vない/Aい/A/Nな + んです" có nghĩa nào sau đây?', 'Dùng trong câu hỏi nguyên nhân lí do', 'Thể khả năng (có thể làm gì)', 'Liệt kê lý do', 'Hoàn thành / Lỡ làm gì đó (tiếc nuối)', 'Dùng trong câu hỏi nguyên nhân lí do', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'efeea555-90b8-4543-b4de-b0661faf07ce', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Dùng trong câu hỏi nguyên nhân lí do"?', 'V1ながら、Vる人が + すき・きらい', 'N + が + V(thể khả năng)', 'Vる/Vた/Vない/Aい/A/Nな + んです', 'Vていただけませんか', 'Vる/Vた/Vない/Aい/A/Nな + んです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'e6636fdc-ecb7-4c28-927f-d06f5aef196b', 'fill_blank', 'Điền vào chỗ trống: どうした＿＿＿か。', NULL, NULL, NULL, NULL, 'んです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'e6636fdc-ecb7-4c28-927f-d06f5aef196b', 'choose_meaning', 'Mẫu ngữ pháp "Vる/Vた/Vない/Aい/A/Nな + んです" có nghĩa nào sau đây?', 'Làm mềm câu và tìm hiểu sự tình đối phương', 'Thể khả năng (có thể làm gì)', 'Liệt kê lý do', 'Hoàn thành / Lỡ làm gì đó (tiếc nuối)', 'Làm mềm câu và tìm hiểu sự tình đối phương', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0e00dbf9-5f33-4c3b-83a1-9fe0c9155c27', 'e6636fdc-ecb7-4c28-927f-d06f5aef196b', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Làm mềm câu và tìm hiểu sự tình đối phương"?', 'V1ながら、Vる人が + すき・きらい', 'N + が + V(thể khả năng)', 'Vる/Vた/Vない/Aい/A/Nな + んです', 'Vていただけませんか', 'Vる/Vた/Vない/Aい/A/Nな + んです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('60671dc5-7e07-4c22-a037-8627c03f4041', NULL, 'fill_blank', 'Điền vào chỗ trống: 漢字が＿＿＿。', NULL, NULL, NULL, NULL, '書ける', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('60671dc5-7e07-4c22-a037-8627c03f4041', NULL, 'choose_meaning', 'Mẫu ngữ pháp "N + が + V(thể khả năng)" có nghĩa nào sau đây?', 'Thể khả năng (có thể làm gì)', 'Có thể làm / Hoàn thành', 'N1 thì ~, nhưng N2 thì ~', 'Nên làm như thế nào bây giờ', 'Thể khả năng (có thể làm gì)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('60671dc5-7e07-4c22-a037-8627c03f4041', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Thể khả năng (có thể làm gì)"?', 'Sは~し、~し、(それに)~', 'V1ながら、V2', 'N + が + V(thể khả năng)', 'いつもVています', 'N + が + V(thể khả năng)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('af1ae8f4-759e-4b1e-8882-078bce1a6704', NULL, 'fill_blank', 'Điền vào chỗ trống: 日本語は話せますが、英語は＿＿＿。', NULL, NULL, NULL, NULL, 'あまり話せません', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('af1ae8f4-759e-4b1e-8882-078bce1a6704', NULL, 'choose_meaning', 'Mẫu ngữ pháp "N1は(+)が、N2は(−)" có nghĩa nào sau đây?', 'Giải thích lý do, mào đầu, làm mềm câu', 'Liệt kê lý do', 'Thể khả năng (có thể làm gì)', 'N1 thì ~, nhưng N2 thì ~', 'N1 thì ~, nhưng N2 thì ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('af1ae8f4-759e-4b1e-8882-078bce1a6704', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "N1 thì ~, nhưng N2 thì ~"?', '疑問詞 + Vたらいいですか', 'Sは~し、~し、(それに)~', 'Vてしまう', 'N1は(+)が、N2は(−)', 'N1は(+)が、N2は(−)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('cc6ef598-1afe-463d-931d-d156b4853140', '7f075403-f8d8-4890-8342-c92660c69dbe', 'fill_blank', 'Điền vào chỗ trống: テニスが＿＿＿。', NULL, NULL, NULL, NULL, 'できます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('cc6ef598-1afe-463d-931d-d156b4853140', '7f075403-f8d8-4890-8342-c92660c69dbe', 'choose_meaning', 'Mẫu ngữ pháp "Nができます。/ Vることができます。" có nghĩa nào sau đây?', 'Liệt kê lý do', 'Hoàn thành / Lỡ làm gì đó (tiếc nuối)', 'Có thể làm gì', 'Vừa làm việc này, vừa làm việc kia', 'Có thể làm gì', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('cc6ef598-1afe-463d-931d-d156b4853140', '7f075403-f8d8-4890-8342-c92660c69dbe', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Có thể làm gì"?', 'Sは~し、~し、(それで)~', 'V1ながら、Vる人が + すき・きらい', 'Vていただけませんか', 'Nができます。/ Vることができます。', 'Nができます。/ Vることができます。', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('cc6ef598-1afe-463d-931d-d156b4853140', 'd228ae81-21d0-4f35-b915-3ee5634dfd56', 'fill_blank', 'Điền vào chỗ trống: レポートはいつ＿＿＿か。', NULL, NULL, NULL, NULL, 'できます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('cc6ef598-1afe-463d-931d-d156b4853140', 'd228ae81-21d0-4f35-b915-3ee5634dfd56', 'choose_meaning', 'Mẫu ngữ pháp "Nができます。/ Vることができます。" có nghĩa nào sau đây?', 'Liệt kê lý do', 'Hoàn thành / Lỡ làm gì đó (tiếc nuối)', 'Làm xong, hoàn thành', 'Vừa làm việc này, vừa làm việc kia', 'Làm xong, hoàn thành', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('cc6ef598-1afe-463d-931d-d156b4853140', 'd228ae81-21d0-4f35-b915-3ee5634dfd56', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Làm xong, hoàn thành"?', 'Sは~し、~し、(それで)~', 'V1ながら、Vる人が + すき・きらい', 'Vていただけませんか', 'Nができます。/ Vることができます。', 'Nができます。/ Vることができます。', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a89d36cb-09f1-4928-8523-5e1a8c998a04', NULL, 'fill_blank', 'Điền vào chỗ trống: テレビを＿＿＿、ご飯を食べます。', NULL, NULL, NULL, NULL, '見ながら', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a89d36cb-09f1-4928-8523-5e1a8c998a04', NULL, 'choose_meaning', 'Mẫu ngữ pháp "V1ながら、V2" có nghĩa nào sau đây?', 'Vừa làm việc này, vừa làm việc kia', 'Thích/Ghét ai đó vừa làm việc này, vừa làm việc kia', 'N1 thì ~, nhưng N2 thì ~', 'Liệt kê lý do', 'Vừa làm việc này, vừa làm việc kia', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a89d36cb-09f1-4928-8523-5e1a8c998a04', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Vừa làm việc này, vừa làm việc kia"?', 'Vていただけませんか', '疑問詞 + Vたらいいですか', 'V1ながら、V2', 'Vてしまう', 'V1ながら、V2', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('335d2a21-37a3-465e-82e8-859150378ad1', NULL, 'fill_blank', 'Điền vào chỗ trống: 電話を使いながらご飯を食べる人が＿＿＿。', NULL, NULL, NULL, NULL, 'きらいです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('335d2a21-37a3-465e-82e8-859150378ad1', NULL, 'choose_meaning', 'Mẫu ngữ pháp "V1ながら、Vる人が + すき・きらい" có nghĩa nào sau đây?', 'Có thể làm / Hoàn thành', 'Thích/Ghét ai đó vừa làm việc này, vừa làm việc kia', 'Nên làm như thế nào bây giờ', 'Liệt kê lý do', 'Thích/Ghét ai đó vừa làm việc này, vừa làm việc kia', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('335d2a21-37a3-465e-82e8-859150378ad1', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Thích/Ghét ai đó vừa làm việc này, vừa làm việc kia"?', 'Sは~し、~し、(それで)~', 'V1ながら、Vる人が + すき・きらい', 'Sは~し、~し、(それに)~', 'いつもVています', 'V1ながら、Vる人が + すき・きらい', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ba4501f1-49b2-43e1-a212-342d92c7b396', NULL, 'fill_blank', 'Điền vào chỗ trống: 先生は面白いし、親切だし、＿＿＿経験もあります。', NULL, NULL, NULL, NULL, 'それに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ba4501f1-49b2-43e1-a212-342d92c7b396', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Sは~し、~し、(それに)~" có nghĩa nào sau đây?', 'Giải thích lý do, mào đầu, làm mềm câu', 'N1 thì ~, nhưng N2 thì ~', 'Anh/chị ~ giúp tôi được không ạ?', 'Liệt kê các tính chất tương đồng nhau', 'Liệt kê các tính chất tương đồng nhau', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ba4501f1-49b2-43e1-a212-342d92c7b396', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Liệt kê các tính chất tương đồng nhau"?', 'N1は(+)が、N2は(−)', 'Vていただけませんか', 'V1ながら、V2', 'Sは~し、~し、(それに)~', 'Sは~し、~し、(それに)~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('6b9cb65b-d7ba-4517-9e9f-d6333da777d8', NULL, 'fill_blank', 'Điền vào chỗ trống: 雨も降っているし、荷物も多いし、＿＿＿タクシーで帰りました。', NULL, NULL, NULL, NULL, 'それで', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('6b9cb65b-d7ba-4517-9e9f-d6333da777d8', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Sは~し、~し、(それで)~" có nghĩa nào sau đây?', 'Hoàn thành / Lỡ làm gì đó (tiếc nuối)', 'Nên làm như thế nào bây giờ', 'Liệt kê lý do', 'Có thể làm / Hoàn thành', 'Liệt kê lý do', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('6b9cb65b-d7ba-4517-9e9f-d6333da777d8', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Liệt kê lý do"?', 'Sは~し、~し、(それで)~', 'Sは~し、~し、(それに)~', 'V1ながら、Vる人が + すき・きらい', 'Vていただけませんか', 'Sは~し、~し、(それで)~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ee3a4296-4cf9-4b33-a9f2-a76e7828de18', NULL, 'fill_blank', 'Điền vào chỗ trống: 暇なとき、いつも＿＿＿。', NULL, NULL, NULL, NULL, 'テレビを見ています', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ee3a4296-4cf9-4b33-a9f2-a76e7828de18', NULL, 'choose_meaning', 'Mẫu ngữ pháp "いつもVています" có nghĩa nào sau đây?', 'Liệt kê lý do', 'Liệt kê các tính chất tương đồng nhau', 'Thể khả năng (có thể làm gì)', 'Diễn tả thói quen', 'Diễn tả thói quen', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ee3a4296-4cf9-4b33-a9f2-a76e7828de18', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Diễn tả thói quen"?', 'Sは~し、~し、(それに)~', '疑問詞 + Vたらいいですか', 'いつもVています', 'Nができます。/ Vることができます。', 'いつもVています', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', '13975bb7-2450-410d-9fd6-0016157b797c', 'fill_blank', 'Điền vào chỗ trống: 今、このマンガを＿＿＿。', NULL, NULL, NULL, NULL, '読んでしまいます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', '13975bb7-2450-410d-9fd6-0016157b797c', 'choose_meaning', 'Mẫu ngữ pháp "Vてしまう" có nghĩa nào sau đây?', 'Thể khả năng (có thể làm gì)', 'N1 thì ~, nhưng N2 thì ~', 'Vừa làm việc này, vừa làm việc kia', 'Hoàn thành, sẽ làm xong', 'Hoàn thành, sẽ làm xong', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', '13975bb7-2450-410d-9fd6-0016157b797c', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Hoàn thành, sẽ làm xong"?', 'Vてしまう', 'Sは~し、~し、(それで)~', 'V1ながら、V2', 'いつもVています', 'Vてしまう', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', 'd613d477-5cf0-4236-a681-05fa172d49e0', 'fill_blank', 'Điền vào chỗ trống: 財布を＿＿＿。', NULL, NULL, NULL, NULL, '忘れてしまいました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', 'd613d477-5cf0-4236-a681-05fa172d49e0', 'choose_meaning', 'Mẫu ngữ pháp "Vてしまう" có nghĩa nào sau đây?', 'Thể khả năng (có thể làm gì)', 'N1 thì ~, nhưng N2 thì ~', 'Vừa làm việc này, vừa làm việc kia', 'Lỡ làm gì đó, thể hiện tâm trạng tiếc nuối', 'Lỡ làm gì đó, thể hiện tâm trạng tiếc nuối', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('eae25fb4-1d8d-4910-a34f-d4bb93063ff2', 'd613d477-5cf0-4236-a681-05fa172d49e0', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Lỡ làm gì đó, thể hiện tâm trạng tiếc nuối"?', 'Vてしまう', 'Sは~し、~し、(それで)~', 'V1ながら、V2', 'いつもVています', 'Vてしまう', 'generated');
