-- ============================================================
-- jp-go — Ngữ pháp N4, round 2 (12 mẫu, trang in 39).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 3 - 文法.
-- ============================================================

-- ---------- jp_grammar ----------
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'N4', 'Vちゃう／Vじゃう (khẩu ngữ của てしまう)', 'Dạng rút gọn khẩu ngữ của てしまう', 'ちゃう/じゃう là cách nói tắt của てしまう/でしまう trong văn nói', NULL, NULL, NULL, NULL, NULL, '{}', NULL, 39, 'Vちゃう／Vじゃう (khẩu ngữ của てしまう)', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('3bf46128-b422-45e6-96e2-87cdd36e3646', 'N4', '[Địa điểm]にNがVたてあります', 'Ở ~ có cái gì đang ~', 'てある dùng cho hành động ai đó đã làm và kết quả còn tồn tại', '[Địa điểm] + に + N + が + V(て form) + あります', 'Miêu tả trạng thái kết quả của 1 hành động chuẩn bị/sắp đặt trước đó tại 1 địa điểm', NULL, NULL, NULL, '{}', NULL, 39, '[Địa điểm]にNがVたてあります', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('5f19e512-bcdf-4259-8869-a8f22216c62e', 'N4', 'Nは[địa điểm]にVたてあります', 'Cái gì đó đang ở đâu', 'Đảo trật tự để nhấn mạnh chủ đề N thay vì địa điểm', 'N + は + [địa điểm] + に + V(て form) + あります', 'Nhấn mạnh vị trí của 1 vật cụ thể đã được ai đó sắp đặt sẵn', NULL, NULL, NULL, '{}', NULL, 39, 'Nは[địa điểm]にVたてあります', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('982c3474-5685-493e-a82b-e00709033c00', 'N4', 'もうVたてあります＝もうVました', 'Đã làm gì trước, đã làm sẵn', 'もう + てある nhấn mạnh việc đã chuẩn bị/hoàn thành sẵn', 'もう + V(て form) + あります', 'Xác nhận 1 việc đã được làm/chuẩn bị xong sẵn', NULL, NULL, NULL, '{}', NULL, 39, 'もうVたてあります＝もうVました', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', 'N4', 'Vておく', 'Chuẩn bị trước / Làm vì mục đích gì đó', 'ておく = làm trước để chuẩn bị cho tương lai', NULL, NULL, NULL, NULL, NULL, '{}', NULL, 39, 'Vておく', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('2f84a542-2103-4e33-88f7-5092092bc66f', 'N4', '(そのまま)Vておいてください', 'Để nguyên trạng thái như vậy', 'そのまま + ておいてください = giữ nguyên hiện trạng', '(そのまま) + V(て form) + おいてください', 'Yêu cầu ai đó giữ nguyên/không thay đổi 1 trạng thái', NULL, NULL, NULL, '{}', NULL, 39, '(そのまま)Vておいてください', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('437b4ce0-dfd7-4923-ae89-2324e31870fb', 'N4', 'Vとく＝Vておく (khẩu ngữ)', 'Cứ ~ như vậy (văn nói)', 'とく là cách nói tắt của ておく trong văn nói', 'V(て form, bỏ て) + とく', 'Dạng rút gọn khẩu ngữ của ておく trong hội thoại thân mật', NULL, NULL, NULL, '{}', NULL, 39, 'Vとく＝Vておく (khẩu ngữ)', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'N4', 'まだVています／まだVていません', 'Vẫn còn đang ~ / Vẫn chưa ~', 'まだ mang 2 nghĩa tùy thể khẳng định (vẫn còn) hay phủ định (vẫn chưa)', NULL, NULL, NULL, NULL, NULL, '{}', NULL, 39, 'まだVています／まだVていません', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('acf97be1-26e4-4c39-9b10-f706261d33d5', 'N4', 'Vようと思います', 'Định làm gì đó ~', 'ようと思う = ý định nảy sinh tại thời điểm nói', 'V(thể ý chí, bỏ る thêm よう／おう) + と思います', 'Diễn tả ý định nhất thời, mới nảy sinh khi nói', NULL, NULL, NULL, '{}', NULL, 39, 'Vようと思います', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('51218d5e-df2e-4c13-b6f8-ab9d8a53ca00', 'N4', 'Vようと思っています', 'Định sẽ làm ~ (diễn tả dự định, ý chí đã có từ trước)', 'ようと思っています = ý định đã có sẵn từ trước, không phải mới nảy sinh', 'V(thể ý chí) + と思っています', 'Diễn tả dự định, ý chí đã ấp ủ từ trước sẽ làm trong tương lai', NULL, NULL, NULL, '{}', NULL, 39, 'Vようと思っています', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('03cad5a7-cae1-4950-b57e-96ba1658d021', 'N4', 'Vるつもりです', 'Dự định sẽ làm gì', 'つもり = dự định, kế hoạch', 'V(thể từ điển) + つもりです', 'Diễn tả dự định sẽ làm gì trong tương lai', NULL, NULL, NULL, '{}', NULL, 39, 'Vるつもりです', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('ab6c4855-1faa-4edb-b2a8-9cc27caa62e4', 'N4', 'Vないつもりです', 'Dự định không làm gì', 'V thể ない + つもりです = phủ định của dự định', 'V(thể ない) + つもりです', 'Diễn tả dự định KHÔNG làm gì trong tương lai', NULL, NULL, NULL, '{}', NULL, 39, 'Vないつもりです', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;

-- ---------- jp_grammar_usages (chỉ tạo khi multi_usage) ----------
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('a1e05f4b-132f-46ac-a831-b9c417f0b81b', 'b9918354-bd5b-4c29-bbab-ac41a0198ba8', 1, 'Luôn... nhé/ Luôn... không? (ý định làm ngay)', 'V-て(bỏ て, thêm ちゃう) hoặc V-で(bỏ で, thêm じゃう)', NULL, NULL, 39, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('fc0d4f5e-eaed-41b6-be53-db8f0da80bdc', 'b9918354-bd5b-4c29-bbab-ac41a0198ba8', 2, 'Lỡ ~ mất (thể hiện tâm trạng tiếc nuối)', 'V-て(bỏ て, thêm ちゃう) hoặc V-で(bỏ で, thêm じゃう)', NULL, NULL, 39, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('17c9d0ab-3375-4e06-ae3d-759bd35da46e', 'b896afe8-bf96-4f27-ad18-3a62706f5d13', 1, 'Chuẩn bị trước, làm trước ~', 'V(て form) + おく', NULL, NULL, 39, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('b302e0c7-6ef4-4dc0-b745-34f82f619287', 'b896afe8-bf96-4f27-ad18-3a62706f5d13', 2, 'Làm vì mục đích gì đó...', 'V(て form) + おく', NULL, NULL, 39, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('e104916d-7d25-46e2-bc99-38011d142b86', 'fb02a05c-d541-4126-84fc-8797924df5b6', 1, 'Vẫn còn đang ~', 'まだ + V(て form) + います／いません', NULL, NULL, 39, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('cc31e17a-5b13-46eb-8328-f79c7676c85f', 'fb02a05c-d541-4126-84fc-8797924df5b6', 2, 'Vẫn chưa ~', 'まだ + V(て form) + います／いません', NULL, NULL, 39, 'pdf');

-- ---------- jp_grammar_examples ----------
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'a1e05f4b-132f-46ac-a831-b9c417f0b81b', 1, 'daily', '食べないと、食べちゃうよ。', 'Nếu bạn không ăn thì tôi ăn luôn nhé.', '食べないと、＿＿＿よ。', '食べちゃう', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'a1e05f4b-132f-46ac-a831-b9c417f0b81b', 2, 'daily', '早くしないと、遅れちゃうよ。', 'Không nhanh lên thì sẽ trễ luôn đó.', '早くしないと、＿＿＿よ。', '遅れちゃう', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'a1e05f4b-132f-46ac-a831-b9c417f0b81b', 3, 'daily', 'このケーキ、食べちゃうよ。いい？', 'Cái bánh này tôi ăn luôn nhé. Được không?', 'このケーキ、＿＿＿よ。いい？', '食べちゃう', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'fc0d4f5e-eaed-41b6-be53-db8f0da80bdc', 1, 'daily', '財布を忘れちゃった。', 'Tôi đã lỡ quên ví mất rồi.', '財布を＿＿＿。', '忘れちゃった', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'fc0d4f5e-eaed-41b6-be53-db8f0da80bdc', 2, 'daily', '大事なデータを消しちゃった。', 'Tôi đã lỡ xóa mất dữ liệu quan trọng.', '大事なデータを＿＿＿。', '消しちゃった', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'fc0d4f5e-eaed-41b6-be53-db8f0da80bdc', 3, 'daily', '電車に遅れちゃった。', 'Tôi đã lỡ trễ tàu mất rồi.', '電車に＿＿＿。', '遅れちゃった', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('3bf46128-b422-45e6-96e2-87cdd36e3646', NULL, 1, 'daily', '壁に絵が貼ってあります。', 'Trên tường đang treo một bức tranh.', '壁に絵が＿＿＿。', '貼ってあります', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('3bf46128-b422-45e6-96e2-87cdd36e3646', NULL, 2, 'daily', '机の上に本が置いてあります。', 'Trên bàn có để một cuốn sách.', '机の上に本が＿＿＿。', '置いてあります', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('3bf46128-b422-45e6-96e2-87cdd36e3646', NULL, 3, 'daily', '冷蔵庫に飲み物が入れてあります。', 'Trong tủ lạnh có để sẵn đồ uống.', '冷蔵庫に飲み物が＿＿＿。', '入れてあります', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('5f19e512-bcdf-4259-8869-a8f22216c62e', NULL, 1, 'daily', 'カレンダーは壁に貼ってあります。', 'Quyển lịch đang treo ở trên tường.', 'カレンダーは壁に＿＿＿。', '貼ってあります', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('5f19e512-bcdf-4259-8869-a8f22216c62e', NULL, 2, 'daily', 'チケットはかばんに入れてあります。', 'Vé được để sẵn trong túi.', 'チケットはかばんに＿＿＿。', '入れてあります', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('5f19e512-bcdf-4259-8869-a8f22216c62e', NULL, 3, 'daily', '花は玄関に飾ってあります。', 'Hoa được trang trí ở lối vào nhà.', '花は玄関に＿＿＿。', '飾ってあります', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('982c3474-5685-493e-a82b-e00709033c00', NULL, 1, 'daily', '食器を洗いましたか。もう洗ってあります。', 'Bạn đã rửa bát chưa? Tôi đã rửa rồi.', '食器を＿＿＿か。', '洗いました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('982c3474-5685-493e-a82b-e00709033c00', NULL, 2, 'daily', '部屋はもう掃除してあります。', 'Phòng đã được dọn dẹp sẵn rồi.', '部屋はもう＿＿＿。', '掃除してあります', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('982c3474-5685-493e-a82b-e00709033c00', NULL, 3, 'daily', '資料はもう準備してあります。', 'Tài liệu đã được chuẩn bị sẵn rồi.', '資料はもう＿＿＿。', '準備してあります', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', '17c9d0ab-3375-4e06-ae3d-759bd35da46e', 1, 'daily', '誕生日のパーティーをするまえに、プレゼントを買っておく。', 'Trước bữa tiệc sinh nhật của bạn, tôi sẽ mua sẵn quà.', '誕生日のパーティーをするまえに、プレゼントを＿＿＿。', '買っておく', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', '17c9d0ab-3375-4e06-ae3d-759bd35da46e', 2, 'daily', '旅行の前に、ホテルを予約しておく。', 'Trước chuyến du lịch, tôi sẽ đặt sẵn khách sạn.', '旅行の前に、ホテルを＿＿＿。', '予約しておく', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', '17c9d0ab-3375-4e06-ae3d-759bd35da46e', 3, 'daily', '会議の前に、資料をコピーしておく。', 'Trước cuộc họp, tôi sẽ photo sẵn tài liệu.', '会議の前に、資料を＿＿＿。', 'コピーしておく', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', 'b302e0c7-6ef4-4dc0-b745-34f82f619287', 1, 'daily', 'テストのためにたくさん勉強しておきます。', 'Tôi học rất nhiều cho bài kiểm tra.', 'テストのためにたくさん＿＿＿。', '勉強しておきます', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', 'b302e0c7-6ef4-4dc0-b745-34f82f619287', 2, 'daily', '将来のために、お金をためておきます。', 'Tôi tiết kiệm tiền vì tương lai.', '将来のために、お金を＿＿＿。', 'ためておきます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', 'b302e0c7-6ef4-4dc0-b745-34f82f619287', 3, 'daily', '健康のために、毎日運動しておきます。', 'Tôi tập thể dục mỗi ngày vì sức khỏe.', '健康のために、毎日＿＿＿。', '運動しておきます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2f84a542-2103-4e33-88f7-5092092bc66f', NULL, 1, 'daily', 'そこに置いておいてください。', 'Cứ để yên ở đó đi.', 'そこに＿＿＿。', '置いておいてください', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2f84a542-2103-4e33-88f7-5092092bc66f', NULL, 2, 'daily', 'ドアを開けておいてください。', 'Xin hãy cứ để cửa mở.', 'ドアを＿＿＿。', '開けておいてください', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2f84a542-2103-4e33-88f7-5092092bc66f', NULL, 3, 'daily', 'この本をそのままにしておいてください。', 'Xin hãy cứ để cuốn sách này nguyên như vậy.', 'この本をそのままに＿＿＿。', 'しておいてください', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('437b4ce0-dfd7-4923-ae89-2324e31870fb', NULL, 1, 'daily', 'そこに置いといて。', 'Cứ để yên ở đó đi.', 'そこに＿＿＿。', '置いといて', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('437b4ce0-dfd7-4923-ae89-2324e31870fb', NULL, 2, 'daily', 'これ、食べといてね。', 'Cái này cứ ăn đi nhé.', 'これ、＿＿＿ね。', '食べといて', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('437b4ce0-dfd7-4923-ae89-2324e31870fb', NULL, 3, 'daily', '電気、消しといて。', 'Cứ tắt đèn đi nhé.', '電気、＿＿＿。', '消しといて', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'e104916d-7d25-46e2-bc99-38011d142b86', 1, 'daily', 'まだ雨が降っています。', 'Trời vẫn còn đang mưa.', 'まだ＿＿＿。', '雨が降っています', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'e104916d-7d25-46e2-bc99-38011d142b86', 2, 'daily', 'まだ仕事をしています。', 'Tôi vẫn đang làm việc.', 'まだ＿＿＿。', '仕事をしています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'e104916d-7d25-46e2-bc99-38011d142b86', 3, 'daily', 'まだ子供は寝ています。', 'Con vẫn đang ngủ.', 'まだ子供は＿＿＿。', '寝ています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'cc31e17a-5b13-46eb-8328-f79c7676c85f', 1, 'daily', 'まだその本を返していません。', 'Tôi vẫn chưa trả lại quyển sách đó.', 'まだその本を＿＿＿。', '返していません', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'cc31e17a-5b13-46eb-8328-f79c7676c85f', 2, 'daily', 'まだレポートを書いていません。', 'Tôi vẫn chưa viết báo cáo.', 'まだレポートを＿＿＿。', '書いていません', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'cc31e17a-5b13-46eb-8328-f79c7676c85f', 3, 'daily', 'まだ晩ご飯を食べていません。', 'Tôi vẫn chưa ăn tối.', 'まだ晩ご飯を＿＿＿。', '食べていません', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('acf97be1-26e4-4c39-9b10-f706261d33d5', NULL, 1, 'daily', '三十歳で自分の家を建てようと思う。', 'Tôi định năm 30 tuổi sẽ xây dựng ngôi nhà của riêng mình.', '三十歳で自分の家を＿＿＿。', '建てようと思う', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('acf97be1-26e4-4c39-9b10-f706261d33d5', NULL, 2, 'daily', '来年、日本へ留学しようと思います。', 'Năm sau tôi định đi du học Nhật Bản.', '来年、日本へ＿＿＿。', '留学しようと思います', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('acf97be1-26e4-4c39-9b10-f706261d33d5', NULL, 3, 'daily', '今度、新しい仕事を探そうと思います。', 'Lần này tôi định tìm công việc mới.', '今度、新しい仕事を＿＿＿。', '探そうと思います', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('51218d5e-df2e-4c13-b6f8-ab9d8a53ca00', NULL, 1, 'daily', '日本へ行って天ぷらを食べようと思っています。', 'Tôi định sẽ đi Nhật và ăn tempura.', '日本へ行って天ぷらを＿＿＿。', '食べようと思っています', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('51218d5e-df2e-4c13-b6f8-ab9d8a53ca00', NULL, 2, 'daily', '将来、医者になろうと思っています。', 'Trong tương lai tôi định sẽ trở thành bác sĩ.', '将来、医者に＿＿＿。', 'なろうと思っています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('51218d5e-df2e-4c13-b6f8-ab9d8a53ca00', NULL, 3, 'daily', '来月、引っ越そうと思っています。', 'Tháng sau tôi định sẽ chuyển nhà.', '来月、＿＿＿。', '引っ越そうと思っています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('03cad5a7-cae1-4950-b57e-96ba1658d021', NULL, 1, 'daily', '中国語を習うつもりです。', 'Tôi dự định sẽ học tiếng Trung quốc.', '中国語を＿＿＿。', '習うつもりです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('03cad5a7-cae1-4950-b57e-96ba1658d021', NULL, 2, 'daily', '来週、国へ帰るつもりです。', 'Tuần sau tôi dự định về nước.', '来週、国へ＿＿＿。', '帰るつもりです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('03cad5a7-cae1-4950-b57e-96ba1658d021', NULL, 3, 'daily', '今年、車を買うつもりです。', 'Năm nay tôi dự định mua xe ô tô.', '今年、車を＿＿＿。', '買うつもりです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ab6c4855-1faa-4edb-b2a8-9cc27caa62e4', NULL, 1, 'daily', '日本語を話さないつもりです。', 'Tôi sẽ không nói tiếng Nhật.', '日本語を＿＿＿。', '話さないつもりです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ab6c4855-1faa-4edb-b2a8-9cc27caa62e4', NULL, 2, 'daily', 'もうお酒を飲まないつもりです。', 'Tôi dự định sẽ không uống rượu nữa.', 'もうお酒を＿＿＿。', '飲まないつもりです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ab6c4855-1faa-4edb-b2a8-9cc27caa62e4', NULL, 3, 'daily', '今度は行かないつもりです。', 'Lần này tôi dự định không đi.', '今度は＿＿＿。', '行かないつもりです', 'generated');

-- ---------- jp_grammar_questions (toàn bộ generated) ----------
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'a1e05f4b-132f-46ac-a831-b9c417f0b81b', 'fill_blank', 'Điền vào chỗ trống: 食べないと、＿＿＿よ。', NULL, NULL, NULL, NULL, '食べちゃう', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'a1e05f4b-132f-46ac-a831-b9c417f0b81b', 'choose_meaning', 'Mẫu ngữ pháp "Vちゃう／Vじゃう (khẩu ngữ của てしまう)" có nghĩa nào sau đây?', 'Vẫn còn đang ~ / Vẫn chưa ~', 'Ở ~ có cái gì đang ~', 'Luôn... nhé/ Luôn... không? (ý định làm ngay)', 'Cái gì đó đang ở đâu', 'Luôn... nhé/ Luôn... không? (ý định làm ngay)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'a1e05f4b-132f-46ac-a831-b9c417f0b81b', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Luôn... nhé/ Luôn... không? (ý định làm ngay)"?', '(そのまま)Vておいてください', 'Vないつもりです', 'Vようと思います', 'Vちゃう／Vじゃう (khẩu ngữ của てしまう)', 'Vちゃう／Vじゃう (khẩu ngữ của てしまう)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'fc0d4f5e-eaed-41b6-be53-db8f0da80bdc', 'fill_blank', 'Điền vào chỗ trống: 財布を＿＿＿。', NULL, NULL, NULL, NULL, '忘れちゃった', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'fc0d4f5e-eaed-41b6-be53-db8f0da80bdc', 'choose_meaning', 'Mẫu ngữ pháp "Vちゃう／Vじゃう (khẩu ngữ của てしまう)" có nghĩa nào sau đây?', 'Vẫn còn đang ~ / Vẫn chưa ~', 'Ở ~ có cái gì đang ~', 'Lỡ ~ mất (thể hiện tâm trạng tiếc nuối)', 'Cái gì đó đang ở đâu', 'Lỡ ~ mất (thể hiện tâm trạng tiếc nuối)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b9918354-bd5b-4c29-bbab-ac41a0198ba8', 'fc0d4f5e-eaed-41b6-be53-db8f0da80bdc', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Lỡ ~ mất (thể hiện tâm trạng tiếc nuối)"?', '(そのまま)Vておいてください', 'Vないつもりです', 'Vようと思います', 'Vちゃう／Vじゃう (khẩu ngữ của てしまう)', 'Vちゃう／Vじゃう (khẩu ngữ của てしまう)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('3bf46128-b422-45e6-96e2-87cdd36e3646', NULL, 'fill_blank', 'Điền vào chỗ trống: 壁に絵が＿＿＿。', NULL, NULL, NULL, NULL, '貼ってあります', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('3bf46128-b422-45e6-96e2-87cdd36e3646', NULL, 'choose_meaning', 'Mẫu ngữ pháp "[Địa điểm]にNがVたてあります" có nghĩa nào sau đây?', 'Ở ~ có cái gì đang ~', 'Cứ ~ như vậy (văn nói)', 'Đã làm gì trước, đã làm sẵn', 'Dự định không làm gì', 'Ở ~ có cái gì đang ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('3bf46128-b422-45e6-96e2-87cdd36e3646', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Ở ~ có cái gì đang ~"?', 'Vないつもりです', '[Địa điểm]にNがVたてあります', '(そのまま)Vておいてください', 'Vようと思っています', '[Địa điểm]にNがVたてあります', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('5f19e512-bcdf-4259-8869-a8f22216c62e', NULL, 'fill_blank', 'Điền vào chỗ trống: カレンダーは壁に＿＿＿。', NULL, NULL, NULL, NULL, '貼ってあります', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('5f19e512-bcdf-4259-8869-a8f22216c62e', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Nは[địa điểm]にVたてあります" có nghĩa nào sau đây?', 'Để nguyên trạng thái như vậy', 'Cái gì đó đang ở đâu', 'Chuẩn bị trước / Làm vì mục đích gì đó', 'Ở ~ có cái gì đang ~', 'Cái gì đó đang ở đâu', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('5f19e512-bcdf-4259-8869-a8f22216c62e', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Cái gì đó đang ở đâu"?', '(そのまま)Vておいてください', 'Nは[địa điểm]にVたてあります', '[Địa điểm]にNがVたてあります', 'Vとく＝Vておく (khẩu ngữ)', 'Nは[địa điểm]にVたてあります', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('982c3474-5685-493e-a82b-e00709033c00', NULL, 'fill_blank', 'Điền vào chỗ trống: 食器を＿＿＿か。', NULL, NULL, NULL, NULL, '洗いました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('982c3474-5685-493e-a82b-e00709033c00', NULL, 'choose_meaning', 'Mẫu ngữ pháp "もうVたてあります＝もうVました" có nghĩa nào sau đây?', 'Dạng rút gọn khẩu ngữ của てしまう', 'Ở ~ có cái gì đang ~', 'Đã làm gì trước, đã làm sẵn', 'Định làm gì đó ~', 'Đã làm gì trước, đã làm sẵn', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('982c3474-5685-493e-a82b-e00709033c00', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Đã làm gì trước, đã làm sẵn"?', 'Vておく', '(そのまま)Vておいてください', 'もうVたてあります＝もうVました', '[Địa điểm]にNがVたてあります', 'もうVたてあります＝もうVました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', '17c9d0ab-3375-4e06-ae3d-759bd35da46e', 'fill_blank', 'Điền vào chỗ trống: 誕生日のパーティーをするまえに、プレゼントを＿＿＿。', NULL, NULL, NULL, NULL, '買っておく', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', '17c9d0ab-3375-4e06-ae3d-759bd35da46e', 'choose_meaning', 'Mẫu ngữ pháp "Vておく" có nghĩa nào sau đây?', 'Để nguyên trạng thái như vậy', 'Ở ~ có cái gì đang ~', 'Đã làm gì trước, đã làm sẵn', 'Chuẩn bị trước, làm trước ~', 'Chuẩn bị trước, làm trước ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', '17c9d0ab-3375-4e06-ae3d-759bd35da46e', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Chuẩn bị trước, làm trước ~"?', 'Vちゃう／Vじゃう (khẩu ngữ của てしまう)', 'Vておく', 'まだVています／まだVていません', 'もうVたてあります＝もうVました', 'Vておく', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', 'b302e0c7-6ef4-4dc0-b745-34f82f619287', 'fill_blank', 'Điền vào chỗ trống: テストのためにたくさん＿＿＿。', NULL, NULL, NULL, NULL, '勉強しておきます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', 'b302e0c7-6ef4-4dc0-b745-34f82f619287', 'choose_meaning', 'Mẫu ngữ pháp "Vておく" có nghĩa nào sau đây?', 'Để nguyên trạng thái như vậy', 'Ở ~ có cái gì đang ~', 'Đã làm gì trước, đã làm sẵn', 'Làm vì mục đích gì đó...', 'Làm vì mục đích gì đó...', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('b896afe8-bf96-4f27-ad18-3a62706f5d13', 'b302e0c7-6ef4-4dc0-b745-34f82f619287', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Làm vì mục đích gì đó..."?', 'Vちゃう／Vじゃう (khẩu ngữ của てしまう)', 'Vておく', 'まだVています／まだVていません', 'もうVたてあります＝もうVました', 'Vておく', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2f84a542-2103-4e33-88f7-5092092bc66f', NULL, 'fill_blank', 'Điền vào chỗ trống: そこに＿＿＿。', NULL, NULL, NULL, NULL, '置いておいてください', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2f84a542-2103-4e33-88f7-5092092bc66f', NULL, 'choose_meaning', 'Mẫu ngữ pháp "(そのまま)Vておいてください" có nghĩa nào sau đây?', 'Để nguyên trạng thái như vậy', 'Ở ~ có cái gì đang ~', 'Cái gì đó đang ở đâu', 'Dự định sẽ làm gì', 'Để nguyên trạng thái như vậy', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2f84a542-2103-4e33-88f7-5092092bc66f', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Để nguyên trạng thái như vậy"?', 'Vるつもりです', 'Vとく＝Vておく (khẩu ngữ)', 'Vようと思います', '(そのまま)Vておいてください', '(そのまま)Vておいてください', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('437b4ce0-dfd7-4923-ae89-2324e31870fb', NULL, 'fill_blank', 'Điền vào chỗ trống: そこに＿＿＿。', NULL, NULL, NULL, NULL, '置いといて', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('437b4ce0-dfd7-4923-ae89-2324e31870fb', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vとく＝Vておく (khẩu ngữ)" có nghĩa nào sau đây?', 'Vẫn còn đang ~ / Vẫn chưa ~', 'Cái gì đó đang ở đâu', 'Cứ ~ như vậy (văn nói)', 'Định làm gì đó ~', 'Cứ ~ như vậy (văn nói)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('437b4ce0-dfd7-4923-ae89-2324e31870fb', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Cứ ~ như vậy (văn nói)"?', 'もうVたてあります＝もうVました', 'Vとく＝Vておく (khẩu ngữ)', 'Vておく', '[Địa điểm]にNがVたてあります', 'Vとく＝Vておく (khẩu ngữ)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'e104916d-7d25-46e2-bc99-38011d142b86', 'fill_blank', 'Điền vào chỗ trống: まだ＿＿＿。', NULL, NULL, NULL, NULL, '雨が降っています', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'e104916d-7d25-46e2-bc99-38011d142b86', 'choose_meaning', 'Mẫu ngữ pháp "まだVています／まだVていません" có nghĩa nào sau đây?', 'Để nguyên trạng thái như vậy', 'Vẫn còn đang ~', 'Đã làm gì trước, đã làm sẵn', 'Định sẽ làm ~ (diễn tả dự định, ý chí đã có từ trước)', 'Vẫn còn đang ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'e104916d-7d25-46e2-bc99-38011d142b86', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Vẫn còn đang ~"?', 'Vちゃう／Vじゃう (khẩu ngữ của てしまう)', 'まだVています／まだVていません', '(そのまま)Vておいてください', 'Vようと思います', 'まだVています／まだVていません', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'cc31e17a-5b13-46eb-8328-f79c7676c85f', 'fill_blank', 'Điền vào chỗ trống: まだその本を＿＿＿。', NULL, NULL, NULL, NULL, '返していません', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'cc31e17a-5b13-46eb-8328-f79c7676c85f', 'choose_meaning', 'Mẫu ngữ pháp "まだVています／まだVていません" có nghĩa nào sau đây?', 'Để nguyên trạng thái như vậy', 'Vẫn chưa ~', 'Đã làm gì trước, đã làm sẵn', 'Định sẽ làm ~ (diễn tả dự định, ý chí đã có từ trước)', 'Vẫn chưa ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fb02a05c-d541-4126-84fc-8797924df5b6', 'cc31e17a-5b13-46eb-8328-f79c7676c85f', 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Vẫn chưa ~"?', 'Vちゃう／Vじゃう (khẩu ngữ của てしまう)', 'まだVています／まだVていません', '(そのまま)Vておいてください', 'Vようと思います', 'まだVています／まだVていません', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('acf97be1-26e4-4c39-9b10-f706261d33d5', NULL, 'fill_blank', 'Điền vào chỗ trống: 三十歳で自分の家を＿＿＿。', NULL, NULL, NULL, NULL, '建てようと思う', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('acf97be1-26e4-4c39-9b10-f706261d33d5', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vようと思います" có nghĩa nào sau đây?', 'Dạng rút gọn khẩu ngữ của てしまう', 'Dự định không làm gì', 'Định làm gì đó ~', 'Định sẽ làm ~ (diễn tả dự định, ý chí đã có từ trước)', 'Định làm gì đó ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('acf97be1-26e4-4c39-9b10-f706261d33d5', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Định làm gì đó ~"?', 'Vようと思っています', 'Vないつもりです', 'Vようと思います', 'Vちゃう／Vじゃう (khẩu ngữ của てしまう)', 'Vようと思います', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('51218d5e-df2e-4c13-b6f8-ab9d8a53ca00', NULL, 'fill_blank', 'Điền vào chỗ trống: 日本へ行って天ぷらを＿＿＿。', NULL, NULL, NULL, NULL, '食べようと思っています', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('51218d5e-df2e-4c13-b6f8-ab9d8a53ca00', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vようと思っています" có nghĩa nào sau đây?', 'Cái gì đó đang ở đâu', 'Dự định không làm gì', 'Để nguyên trạng thái như vậy', 'Định sẽ làm ~ (diễn tả dự định, ý chí đã có từ trước)', 'Định sẽ làm ~ (diễn tả dự định, ý chí đã có từ trước)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('51218d5e-df2e-4c13-b6f8-ab9d8a53ca00', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Định sẽ làm ~ (diễn tả dự định, ý chí đã có từ trước)"?', 'Vようと思っています', 'Vとく＝Vておく (khẩu ngữ)', 'まだVています／まだVていません', 'Vちゃう／Vじゃう (khẩu ngữ của てしまう)', 'Vようと思っています', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('03cad5a7-cae1-4950-b57e-96ba1658d021', NULL, 'fill_blank', 'Điền vào chỗ trống: 中国語を＿＿＿。', NULL, NULL, NULL, NULL, '習うつもりです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('03cad5a7-cae1-4950-b57e-96ba1658d021', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vるつもりです" có nghĩa nào sau đây?', 'Cứ ~ như vậy (văn nói)', 'Vẫn còn đang ~ / Vẫn chưa ~', 'Dự định sẽ làm gì', 'Định sẽ làm ~ (diễn tả dự định, ý chí đã có từ trước)', 'Dự định sẽ làm gì', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('03cad5a7-cae1-4950-b57e-96ba1658d021', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Dự định sẽ làm gì"?', 'Vるつもりです', 'まだVています／まだVていません', '[Địa điểm]にNがVたてあります', 'Vようと思います', 'Vるつもりです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ab6c4855-1faa-4edb-b2a8-9cc27caa62e4', NULL, 'fill_blank', 'Điền vào chỗ trống: 日本語を＿＿＿。', NULL, NULL, NULL, NULL, '話さないつもりです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ab6c4855-1faa-4edb-b2a8-9cc27caa62e4', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vないつもりです" có nghĩa nào sau đây?', 'Dự định không làm gì', 'Cái gì đó đang ở đâu', 'Dự định sẽ làm gì', 'Định làm gì đó ~', 'Dự định không làm gì', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ab6c4855-1faa-4edb-b2a8-9cc27caa62e4', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Dự định không làm gì"?', 'Vようと思います', 'まだVています／まだVていません', 'Vようと思っています', 'Vないつもりです', 'Vないつもりです', 'generated');
