-- ============================================================
-- jp-go — Ngữ pháp N4, round 3 (11 mẫu, trang in 40).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 3 - 文法.
-- ============================================================

-- ---------- jp_grammar ----------
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('c8423c9a-44a2-40be-8f74-4316fae629e4', 'N4', 'Vる／Nの＋予定です', 'Có kế hoạch làm gì ~', '予定 = kế hoạch, thường do 1 tổ chức (trường/công ty) hoặc nhiều người quyết định', 'V(thể từ điển)／N + の + 予定です', 'Thông báo kế hoạch đã định trước (thường do tổ chức/nhiều người quyết định)', NULL, NULL, NULL, '{}', NULL, 40, 'Vる／Nの＋予定です', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('c4947afa-27a3-4969-9c15-b5d8b5c4ee7f', 'N4', 'Vた／Vない＋ほうがいいです', 'Nên/ Không nên làm gì', 'ほうがいい = nên; thể た cho khẳng định, thể ない cho phủ định', 'V(thể た)／V(thể ない) + ほうがいいです', 'Đưa ra lời khuyên nên hoặc không nên làm gì', NULL, NULL, NULL, '{}', NULL, 40, 'Vた／Vない＋ほうがいいです', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('4eb8d331-dca6-488c-b573-7574fc26ebec', 'N4', 'Vる/ない、Aな/Nじゃない、Aい/Aくない ＋ でしょう', 'Có lẽ/ hẳn là/ chắc là ~ (dự đoán)', 'でしょう dùng để dự đoán với độ tự tin khá cao', 'Vる/ない・Aな/Nじゃない・Aい/Aくない + でしょう', 'Dự đoán 1 sự việc sẽ xảy ra', NULL, NULL, NULL, '{}', NULL, 40, 'Vる/ない、Aな/Nじゃない、Aい/Aくない ＋ でしょう', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('4d58ed1b-49a1-470f-9aa0-2c3f3906e99e', 'N4', 'Vる/Vない、Aな/N、Aい/Aくない ＋ かもしれません', 'Không khéo mà lại ~/khả năng là ~/có lẽ là ~', 'かもしれません độ tự tin thấp hơn でしょう', 'Vる/Vない・Aな/N・Aい/Aくない + かもしれません', 'Dự đoán với độ chắc chắn thấp, khả năng có thể xảy ra', NULL, NULL, NULL, '{}', NULL, 40, 'Vる/Vない、Aな/N、Aい/Aくない ＋ かもしれません', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('ca85c642-3809-40a0-8f99-d5a31b061abc', 'N4', 'Vる＋な', 'Đừng làm gì ~ (thể cấm đoán)', 'Vる+な là thể cấm đoán mạnh, thường dùng trong khẩu ngữ nam giới/biển báo', 'V(thể từ điển) + な', 'Ra lệnh/cấm đoán ai đó không được làm gì (thể mạnh, thân mật)', NULL, NULL, NULL, '{}', NULL, 40, 'Vる＋な', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('1f83aafa-6b81-40ec-9053-91cec31ec163', 'N4', 'Vます＋なさい', 'Cách nói mệnh lệnh', 'V-ます (bỏ ます) + なさい, mệnh lệnh nhẹ nhàng hơn Vる+な', 'V(bỏ ます) + なさい', 'Ra lệnh nhẹ nhàng (thường người lớn nói với trẻ nhỏ)', NULL, NULL, NULL, '{}', NULL, 40, 'Vます＋なさい', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('ad936b93-4969-47dc-bc57-0425dadfec8d', 'N4', 'XはYという意味です', 'X có nghĩa là Y', 'という意味です dùng để giải thích nghĩa của 1 từ/câu', 'X + は + Y + という意味です', 'Giải thích ý nghĩa của 1 từ hoặc câu nói', NULL, NULL, NULL, '{}', NULL, 40, 'XはYという意味です', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('294898ce-a57f-4600-b6ec-6d1f27afb3ee', 'N4', '～と言いました／～と言っていました', 'Ai đó đã nói rằng ~', '言っていました nhấn mạnh việc thuật lại lời nói của người khác', '[câu trích dẫn] + と言いました／と言っていました', 'Thuật lại lời của người khác đã nói', NULL, NULL, NULL, '{}', NULL, 40, '～と言いました／～と言っていました', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('fbd18589-8f92-4ae2-a26c-7a23573e1e55', 'N4', '[Câu văn/thể thường] と伝えていただけませんか', 'Truyền đạt lại lời nhắn', '伝えていただけませんか = nhờ ai đó chuyển lời một cách lịch sự', '[câu trích dẫn thể thường] + と伝えていただけませんか', 'Nhờ ai đó truyền đạt lại 1 lời nhắn cho người thứ ba', NULL, NULL, NULL, '{}', NULL, 40, '[Câu văn/thể thường] と伝えていただけませんか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('e99239c7-348f-4743-9e94-9d832f837d9e', 'N4', 'Vる／Vた／Nの＋とおりに', 'Theo như ~', 'とおりに = làm đúng theo, không sai khác', 'V(thể từ điển／thể た)／N + の + とおりに', 'Làm 1 việc đúng theo cách/lời chỉ dẫn đã cho', NULL, NULL, NULL, '{}', NULL, 40, 'Vる／Vた／Nの＋とおりに', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('a6f82883-97b2-4dc5-b4ad-8cc0f73fa1ff', 'N4', 'V1た／Nの＋あとで', 'Sau khi ~', 'あとで đặt sau thể た của động từ hoặc の của danh từ', 'V(thể た)／N + の + あとで', 'Diễn tả 1 hành động xảy ra sau 1 hành động/sự kiện khác', NULL, NULL, NULL, '{}', NULL, 40, 'V1た／Nの＋あとで', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;

-- ---------- jp_grammar_examples ----------
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c8423c9a-44a2-40be-8f74-4316fae629e4', NULL, 1, 'daily', '東京へ出張の予定です。', 'Tôi có kế hoạch đi công tác ở Tokyo.', '東京へ出張の＿＿＿。', '予定です', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c8423c9a-44a2-40be-8f74-4316fae629e4', NULL, 2, 'daily', '来月、結婚する予定です。', 'Tháng sau tôi có kế hoạch kết hôn.', '来月、＿＿＿。', '結婚する予定です', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c8423c9a-44a2-40be-8f74-4316fae629e4', NULL, 3, 'daily', '会議は3時に始まる予定です。', 'Cuộc họp có kế hoạch bắt đầu lúc 3 giờ.', '会議は3時に＿＿＿。', '始まる予定です', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c4947afa-27a3-4969-9c15-b5d8b5c4ee7f', NULL, 1, 'daily', 'ひどくなったね。病院へ行ったほうがいいです。', 'Bệnh trở nặng hơn rồi. Bạn nên đi đến bệnh viện.', '病院へ＿＿＿。', '行ったほうがいいです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c4947afa-27a3-4969-9c15-b5d8b5c4ee7f', NULL, 2, 'daily', '風邪ですか。運動しないほうがいい。', 'Bạn bị cảm hả? Bạn không nên tập thể dục.', '風邪ですか。＿＿＿。', '運動しないほうがいい', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c4947afa-27a3-4969-9c15-b5d8b5c4ee7f', NULL, 3, 'daily', 'もっと野菜を食べたほうがいいですよ。', 'Bạn nên ăn nhiều rau hơn đấy.', 'もっと野菜を＿＿＿よ。', '食べたほうがいいです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4eb8d331-dca6-488c-b573-7574fc26ebec', NULL, 1, 'daily', '明日、雨が降るでしょう。', 'Có lẽ ngày mai sẽ mưa.', '明日、雨が＿＿＿。', '降るでしょう', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4eb8d331-dca6-488c-b573-7574fc26ebec', NULL, 2, 'daily', '彼はもうすぐ来るでしょう。', 'Chắc là anh ấy sắp đến rồi.', '彼はもうすぐ＿＿＿。', '来るでしょう', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4eb8d331-dca6-488c-b573-7574fc26ebec', NULL, 3, 'daily', '今日は忙しいでしょう。', 'Hôm nay chắc là bạn bận.', '今日は＿＿＿。', '忙しいでしょう', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4d58ed1b-49a1-470f-9aa0-2c3f3906e99e', NULL, 1, 'daily', '明日は雨かもしれません。', 'Khả năng là ngày mai sẽ mưa.', '明日は＿＿＿。', '雨かもしれません', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4d58ed1b-49a1-470f-9aa0-2c3f3906e99e', NULL, 2, 'daily', '彼は今日休むかもしれません。', 'Có lẽ hôm nay anh ấy sẽ nghỉ.', '彼は今日＿＿＿。', '休むかもしれません', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4d58ed1b-49a1-470f-9aa0-2c3f3906e99e', NULL, 3, 'daily', 'この話は本当かもしれません。', 'Câu chuyện này có lẽ là thật.', 'この話は＿＿＿。', '本当かもしれません', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ca85c642-3809-40a0-8f99-d5a31b061abc', NULL, 1, 'daily', '行くな。', 'Đừng đi.', '＿＿＿。', '行くな', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ca85c642-3809-40a0-8f99-d5a31b061abc', NULL, 2, 'daily', 'ここに入るな。', 'Đừng vào đây.', 'ここに＿＿＿。', '入るな', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ca85c642-3809-40a0-8f99-d5a31b061abc', NULL, 3, 'daily', '心配するな。', 'Đừng lo lắng.', '＿＿＿。', '心配するな', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('1f83aafa-6b81-40ec-9053-91cec31ec163', NULL, 1, 'daily', 'はやく食べなさい。', 'Ăn nhanh lên.', 'はやく＿＿＿。', '食べなさい', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('1f83aafa-6b81-40ec-9053-91cec31ec163', NULL, 2, 'daily', '宿題をしなさい。', 'Làm bài tập đi.', '宿題を＿＿＿。', 'しなさい', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('1f83aafa-6b81-40ec-9053-91cec31ec163', NULL, 3, 'daily', '静かにしなさい。', 'Im lặng đi.', '静かに＿＿＿。', 'しなさい', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ad936b93-4969-47dc-bc57-0425dadfec8d', NULL, 1, 'daily', '「ありがとう」は“Cảm ơn”という意味です。', '“Arigatou” có nghĩa là “Cảm ơn”.', '「ありがとう」は“Cảm ơn”＿＿＿。', 'という意味です', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ad936b93-4969-47dc-bc57-0425dadfec8d', NULL, 2, 'daily', '「さようなら」は“Tạm biệt”という意味です。', '“Sayounara” có nghĩa là “Tạm biệt”.', '「さようなら」は“Tạm biệt”＿＿＿。', 'という意味です', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ad936b93-4969-47dc-bc57-0425dadfec8d', NULL, 3, 'daily', '「頑張って」は“Cố lên”という意味です。', '“Ganbatte” có nghĩa là “Cố lên”.', '「頑張って」は“Cố lên”＿＿＿。', 'という意味です', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('294898ce-a57f-4600-b6ec-6d1f27afb3ee', NULL, 1, 'daily', '田中さんが10時に本社に来てくれると言っていました。', 'Ông Tanaka đã nói rằng sẽ đến trụ sở chính lúc 10 giờ.', '田中さんが10時に本社に＿＿＿。', '来てくれると言っていました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('294898ce-a57f-4600-b6ec-6d1f27afb3ee', NULL, 2, 'daily', '彼は明日休むと言いました。', 'Anh ấy đã nói rằng ngày mai sẽ nghỉ.', '彼は明日＿＿＿。', '休むと言いました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('294898ce-a57f-4600-b6ec-6d1f27afb3ee', NULL, 3, 'daily', '先生は宿題が多いと言っていました。', 'Thầy/cô đã nói rằng bài tập rất nhiều.', '先生は宿題が＿＿＿。', '多いと言っていました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fbd18589-8f92-4ae2-a26c-7a23573e1e55', NULL, 1, 'daily', 'ワンさんに「後で電話をください」と伝えていただけませんか。', 'Bạn có thể nói với Quang là “Gọi cho tôi sau” được không?', 'ワンさんに「後で電話をください」と＿＿＿。', '伝えていただけませんか', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fbd18589-8f92-4ae2-a26c-7a23573e1e55', NULL, 2, 'daily', '田中さんに「会議は3時からです」と伝えていただけませんか。', 'Bạn có thể nói với anh Tanaka là “Cuộc họp bắt đầu từ 3 giờ” được không?', '田中さんに「会議は3時からです」と＿＿＿。', '伝えていただけませんか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fbd18589-8f92-4ae2-a26c-7a23573e1e55', NULL, 3, 'daily', '部長に「明日休みます」と伝えていただけませんか。', 'Bạn có thể nói với trưởng phòng là “Ngày mai tôi nghỉ” được không?', '部長に「明日休みます」と＿＿＿。', '伝えていただけませんか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e99239c7-348f-4743-9e94-9d832f837d9e', NULL, 1, 'daily', '私が今から言うとおりに、書いてください。', 'Hãy viết theo những gì tôi sẽ nói bây giờ.', '私が今から言う＿＿＿、書いてください。', 'とおりに', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e99239c7-348f-4743-9e94-9d832f837d9e', NULL, 2, 'daily', '説明書のとおりに、組み立ててください。', 'Xin hãy lắp ráp theo như sách hướng dẫn.', '説明書の＿＿＿、組み立ててください。', 'とおりに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e99239c7-348f-4743-9e94-9d832f837d9e', NULL, 3, 'daily', '先生が教えたとおりに、練習しました。', 'Tôi đã luyện tập theo như thầy/cô đã dạy.', '先生が教えた＿＿＿、練習しました。', 'とおりに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a6f82883-97b2-4dc5-b4ad-8cc0f73fa1ff', NULL, 1, 'daily', '新しいのを買ったあとで、なくした本がみつかりました。', 'Sau khi mua cuốn sách mới, tôi tìm thấy cuốn sách mà tôi đã mất.', '新しいのを買った＿＿＿、なくした本がみつかりました。', 'あとで', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a6f82883-97b2-4dc5-b4ad-8cc0f73fa1ff', NULL, 2, 'daily', '食事のあとで、薬を飲んでください。', 'Xin hãy uống thuốc sau khi ăn.', '食事の＿＿＿、薬を飲んでください。', 'あとで', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a6f82883-97b2-4dc5-b4ad-8cc0f73fa1ff', NULL, 3, 'daily', 'シャワーを浴びたあとで、寝ます。', 'Tôi ngủ sau khi tắm.', 'シャワーを浴びた＿＿＿、寝ます。', 'あとで', 'generated');

-- ---------- jp_grammar_questions (toàn bộ generated) ----------
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c8423c9a-44a2-40be-8f74-4316fae629e4', NULL, 'fill_blank', 'Điền vào chỗ trống: 東京へ出張の＿＿＿。', NULL, NULL, NULL, NULL, '予定です', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c8423c9a-44a2-40be-8f74-4316fae629e4', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vる／Nの＋予定です" có nghĩa nào sau đây?', 'Không khéo mà lại ~/khả năng là ~/có lẽ là ~', 'Truyền đạt lại lời nhắn', 'Có kế hoạch làm gì ~', 'Ai đó đã nói rằng ~', 'Có kế hoạch làm gì ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c8423c9a-44a2-40be-8f74-4316fae629e4', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Có kế hoạch làm gì ~"?', 'Vる／Nの＋予定です', 'Vます＋なさい', 'Vる／Vた／Nの＋とおりに', 'V1た／Nの＋あとで', 'Vる／Nの＋予定です', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c4947afa-27a3-4969-9c15-b5d8b5c4ee7f', NULL, 'fill_blank', 'Điền vào chỗ trống: 病院へ＿＿＿。', NULL, NULL, NULL, NULL, '行ったほうがいいです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c4947afa-27a3-4969-9c15-b5d8b5c4ee7f', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vた／Vない＋ほうがいいです" có nghĩa nào sau đây?', 'Theo như ~', 'Có lẽ/ hẳn là/ chắc là ~ (dự đoán)', 'Nên/ Không nên làm gì', 'X có nghĩa là Y', 'Nên/ Không nên làm gì', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c4947afa-27a3-4969-9c15-b5d8b5c4ee7f', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Nên/ Không nên làm gì"?', 'XはYという意味です', 'Vる＋な', 'Vた／Vない＋ほうがいいです', 'V1た／Nの＋あとで', 'Vた／Vない＋ほうがいいです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4eb8d331-dca6-488c-b573-7574fc26ebec', NULL, 'fill_blank', 'Điền vào chỗ trống: 明日、雨が＿＿＿。', NULL, NULL, NULL, NULL, '降るでしょう', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4eb8d331-dca6-488c-b573-7574fc26ebec', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vる/ない、Aな/Nじゃない、Aい/Aくない ＋ でしょう" có nghĩa nào sau đây?', 'Đừng làm gì ~ (thể cấm đoán)', 'Có lẽ/ hẳn là/ chắc là ~ (dự đoán)', 'Cách nói mệnh lệnh', 'Không khéo mà lại ~/khả năng là ~/có lẽ là ~', 'Có lẽ/ hẳn là/ chắc là ~ (dự đoán)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4eb8d331-dca6-488c-b573-7574fc26ebec', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Có lẽ/ hẳn là/ chắc là ~ (dự đoán)"?', 'Vる/ない、Aな/Nじゃない、Aい/Aくない ＋ でしょう', 'Vる/Vない、Aな/N、Aい/Aくない ＋ かもしれません', 'Vる／Vた／Nの＋とおりに', 'V1た／Nの＋あとで', 'Vる/ない、Aな/Nじゃない、Aい/Aくない ＋ でしょう', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4d58ed1b-49a1-470f-9aa0-2c3f3906e99e', NULL, 'fill_blank', 'Điền vào chỗ trống: 明日は＿＿＿。', NULL, NULL, NULL, NULL, '雨かもしれません', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4d58ed1b-49a1-470f-9aa0-2c3f3906e99e', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vる/Vない、Aな/N、Aい/Aくない ＋ かもしれません" có nghĩa nào sau đây?', 'Không khéo mà lại ~/khả năng là ~/có lẽ là ~', 'Đừng làm gì ~ (thể cấm đoán)', 'Truyền đạt lại lời nhắn', 'Có kế hoạch làm gì ~', 'Không khéo mà lại ~/khả năng là ~/có lẽ là ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4d58ed1b-49a1-470f-9aa0-2c3f3906e99e', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Không khéo mà lại ~/khả năng là ~/có lẽ là ~"?', 'Vる／Nの＋予定です', 'Vる/Vない、Aな/N、Aい/Aくない ＋ かもしれません', 'Vる/ない、Aな/Nじゃない、Aい/Aくない ＋ でしょう', 'Vる／Vた／Nの＋とおりに', 'Vる/Vない、Aな/N、Aい/Aくない ＋ かもしれません', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ca85c642-3809-40a0-8f99-d5a31b061abc', NULL, 'fill_blank', 'Điền vào chỗ trống: ＿＿＿。', NULL, NULL, NULL, NULL, '行くな', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ca85c642-3809-40a0-8f99-d5a31b061abc', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vる＋な" có nghĩa nào sau đây?', 'Nên/ Không nên làm gì', 'Cách nói mệnh lệnh', 'Đừng làm gì ~ (thể cấm đoán)', 'Theo như ~', 'Đừng làm gì ~ (thể cấm đoán)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ca85c642-3809-40a0-8f99-d5a31b061abc', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Đừng làm gì ~ (thể cấm đoán)"?', 'Vます＋なさい', '[Câu văn/thể thường] と伝えていただけませんか', 'Vる＋な', 'Vる/Vない、Aな/N、Aい/Aくない ＋ かもしれません', 'Vる＋な', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('1f83aafa-6b81-40ec-9053-91cec31ec163', NULL, 'fill_blank', 'Điền vào chỗ trống: はやく＿＿＿。', NULL, NULL, NULL, NULL, '食べなさい', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('1f83aafa-6b81-40ec-9053-91cec31ec163', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vます＋なさい" có nghĩa nào sau đây?', 'Có lẽ/ hẳn là/ chắc là ~ (dự đoán)', 'X có nghĩa là Y', 'Theo như ~', 'Cách nói mệnh lệnh', 'Cách nói mệnh lệnh', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('1f83aafa-6b81-40ec-9053-91cec31ec163', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Cách nói mệnh lệnh"?', 'XはYという意味です', 'Vます＋なさい', 'Vる＋な', 'Vる/ない、Aな/Nじゃない、Aい/Aくない ＋ でしょう', 'Vます＋なさい', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ad936b93-4969-47dc-bc57-0425dadfec8d', NULL, 'fill_blank', 'Điền vào chỗ trống: 「ありがとう」は“Cảm ơn”＿＿＿。', NULL, NULL, NULL, NULL, 'という意味です', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ad936b93-4969-47dc-bc57-0425dadfec8d', NULL, 'choose_meaning', 'Mẫu ngữ pháp "XはYという意味です" có nghĩa nào sau đây?', 'Đừng làm gì ~ (thể cấm đoán)', 'Theo như ~', 'Cách nói mệnh lệnh', 'X có nghĩa là Y', 'X có nghĩa là Y', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ad936b93-4969-47dc-bc57-0425dadfec8d', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "X có nghĩa là Y"?', '～と言いました／～と言っていました', 'XはYという意味です', '[Câu văn/thể thường] と伝えていただけませんか', 'V1た／Nの＋あとで', 'XはYという意味です', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('294898ce-a57f-4600-b6ec-6d1f27afb3ee', NULL, 'fill_blank', 'Điền vào chỗ trống: 田中さんが10時に本社に＿＿＿。', NULL, NULL, NULL, NULL, '来てくれると言っていました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('294898ce-a57f-4600-b6ec-6d1f27afb3ee', NULL, 'choose_meaning', 'Mẫu ngữ pháp "～と言いました／～と言っていました" có nghĩa nào sau đây?', 'Không khéo mà lại ~/khả năng là ~/có lẽ là ~', 'Ai đó đã nói rằng ~', 'X có nghĩa là Y', 'Có lẽ/ hẳn là/ chắc là ~ (dự đoán)', 'Ai đó đã nói rằng ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('294898ce-a57f-4600-b6ec-6d1f27afb3ee', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Ai đó đã nói rằng ~"?', 'Vた／Vない＋ほうがいいです', '[Câu văn/thể thường] と伝えていただけませんか', 'Vる/ない、Aな/Nじゃない、Aい/Aくない ＋ でしょう', '～と言いました／～と言っていました', '～と言いました／～と言っていました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fbd18589-8f92-4ae2-a26c-7a23573e1e55', NULL, 'fill_blank', 'Điền vào chỗ trống: ワンさんに「後で電話をください」と＿＿＿。', NULL, NULL, NULL, NULL, '伝えていただけませんか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fbd18589-8f92-4ae2-a26c-7a23573e1e55', NULL, 'choose_meaning', 'Mẫu ngữ pháp "[Câu văn/thể thường] と伝えていただけませんか" có nghĩa nào sau đây?', 'Sau khi ~', 'Truyền đạt lại lời nhắn', 'Ai đó đã nói rằng ~', 'Không khéo mà lại ~/khả năng là ~/có lẽ là ~', 'Truyền đạt lại lời nhắn', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fbd18589-8f92-4ae2-a26c-7a23573e1e55', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Truyền đạt lại lời nhắn"?', 'XはYという意味です', 'Vた／Vない＋ほうがいいです', 'Vる／Nの＋予定です', '[Câu văn/thể thường] と伝えていただけませんか', '[Câu văn/thể thường] と伝えていただけませんか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e99239c7-348f-4743-9e94-9d832f837d9e', NULL, 'fill_blank', 'Điền vào chỗ trống: 私が今から言う＿＿＿、書いてください。', NULL, NULL, NULL, NULL, 'とおりに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e99239c7-348f-4743-9e94-9d832f837d9e', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vる／Vた／Nの＋とおりに" có nghĩa nào sau đây?', 'Theo như ~', 'Đừng làm gì ~ (thể cấm đoán)', 'X có nghĩa là Y', 'Nên/ Không nên làm gì', 'Theo như ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e99239c7-348f-4743-9e94-9d832f837d9e', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Theo như ~"?', 'V1た／Nの＋あとで', 'Vる/Vない、Aな/N、Aい/Aくない ＋ かもしれません', 'Vる／Vた／Nの＋とおりに', 'Vる＋な', 'Vる／Vた／Nの＋とおりに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a6f82883-97b2-4dc5-b4ad-8cc0f73fa1ff', NULL, 'fill_blank', 'Điền vào chỗ trống: 新しいのを買った＿＿＿、なくした本がみつかりました。', NULL, NULL, NULL, NULL, 'あとで', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a6f82883-97b2-4dc5-b4ad-8cc0f73fa1ff', NULL, 'choose_meaning', 'Mẫu ngữ pháp "V1た／Nの＋あとで" có nghĩa nào sau đây?', 'Sau khi ~', 'X có nghĩa là Y', 'Đừng làm gì ~ (thể cấm đoán)', 'Nên/ Không nên làm gì', 'Sau khi ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a6f82883-97b2-4dc5-b4ad-8cc0f73fa1ff', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Sau khi ~"?', '[Câu văn/thể thường] と伝えていただけませんか', 'V1た／Nの＋あとで', 'Vる/Vない、Aな/N、Aい/Aくない ＋ かもしれません', 'Vる＋な', 'V1た／Nの＋あとで', 'generated');
