-- ============================================================
-- jp-go — Ngữ pháp N4, round 4 (12 mẫu, trang in 41).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 3 - 文法.
-- ============================================================

-- ---------- jp_grammar ----------
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('77bf3a96-859b-45a4-afd2-329a8d459070', 'N4', 'V1てV2～', 'Làm V2 mà có V1', 'V1(て form) nối trực tiếp trước V2, diễn tả làm V1 trước rồi làm V2', 'V1(て form) + V2', 'Diễn tả hành động V2 được thực hiện kèm/sau khi có V1', NULL, NULL, NULL, '{}', NULL, 41, 'V1てV2～', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('afaa2be3-bc25-4622-b291-4fd66e76ab7b', 'N4', 'V1ないでV2～', 'Làm V2 mà không làm V1', 'V1(thể ない, bỏ い thêm で) nối trước V2', 'V1(thể ない, bỏ い) + で + V2', 'Diễn tả hành động V2 được thực hiện mà KHÔNG làm V1', NULL, NULL, NULL, '{}', NULL, 41, 'V1ないでV2～', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('bf4cdacc-c7d4-4106-b108-5caaa6ba8f1e', 'N4', '～Vば (thể điều kiện)', 'Nếu ~', 'Nhóm I: う→え+ば／Nhóm II: 見る→見れば／Nhóm III: 来る→来れば, する→すれば', 'V(thể ば)', 'Diễn tả điều kiện giả định, nếu xảy ra A thì B', NULL, NULL, NULL, '{}', NULL, 41, '～Vば (thể điều kiện)', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('a3947630-a859-42af-b36b-af29226945ee', 'N4', 'どうすればいいですか', 'Nên làm như thế nào thì tốt nhỉ?', 'どう + すれば + いいですか = hỏi cách xử lý 1 tình huống', 'どうすればいいですか (cố định)', 'Hỏi ý kiến nên xử lý 1 tình huống như thế nào', NULL, NULL, NULL, '{}', NULL, 41, 'どうすればいいですか', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('4b11a4ee-08d6-4615-a2d5-3d1b63a4c497', 'N4', 'Vる／Aい＋なら', 'Sử dụng khi đưa ra lời khuyên cho người khác', 'なら lấy chủ đề đối phương vừa nói để đưa ra lời khuyên tiếp theo', 'V(thể từ điển)／Aい + なら', 'Đưa ra lời khuyên/thông tin dựa trên chủ đề đối phương vừa đề cập', NULL, NULL, NULL, '{}', NULL, 41, 'Vる／Aい＋なら', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('2219d632-3152-4726-91cc-9384307804e3', 'N4', 'Vる／Aい／Aな (thể điều kiện) ＋ Vる／Aい／A ＋ ほど', 'Càng ~ càng ~', 'Lặp lại cùng 1 từ ở thể điều kiện rồi thể thường + ほど', 'V(thể ば)／Aい(thể ば)／Aな(thể ば) + [cùng từ đó thể thường] + ほど', 'Diễn tả mức độ tăng dần theo tỉ lệ thuận giữa 2 vế', NULL, NULL, NULL, '{}', NULL, 41, 'Vる／Aい／Aな (thể điều kiện) ＋ Vる／Aい／A ＋ ほど', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('61628965-9ed5-470f-babd-4e3fc290c5ef', 'N4', 'A[Vる／Vない]＋ように、B', 'Để A thì B', 'ように diễn tả mục đích cho hành động chủ động không kiểm soát được (khả năng, tự nhiên)', 'A(Vる／Vない, thường ở thể khả năng) + ように、B', 'Diễn tả mục đích của hành động B là để đạt được trạng thái/khả năng A', NULL, NULL, NULL, '{}', NULL, 41, 'A[Vる／Vない]＋ように、B', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('4d8074ac-af85-42aa-b35d-040346b64156', 'N4', 'Vるように／Vなく＋なります／なりました', 'Đã làm được / Đã không làm được', 'なる diễn tả sự thay đổi trạng thái theo thời gian', 'V(thể khả năng, thể từ điển)ように／V(thể khả năng, thể ない, bỏ い)なく + なります／なりました', 'Diễn tả sự thay đổi khả năng làm được/không làm được theo thời gian', NULL, NULL, NULL, '{}', NULL, 41, 'Vるように／Vなく＋なります／なりました', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('46c0ebd9-c99b-4f89-8a98-b24ef068ff17', 'N4', 'Vる／Vない＋ようにしています', 'Cố gắng làm gì', 'ようにしています diễn tả nỗ lực duy trì thói quen', 'V(thể từ điển)／V(thể ない) + ようにしています', 'Diễn tả sự cố gắng duy trì 1 thói quen tốt', NULL, NULL, NULL, '{}', NULL, 41, 'Vる／Vない＋ようにしています', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('36f58828-150f-44d0-899c-d79c07e20d8d', 'N4', 'Vる／Vない＋ようにしてください', 'Hãy làm gì ~', 'ようにしてください nhờ vả/yêu cầu ai đó cố gắng làm gì', 'V(thể từ điển)／V(thể ない) + ようにしてください', 'Yêu cầu ai đó cố gắng làm/không làm gì', NULL, NULL, NULL, '{}', NULL, 41, 'Vる／Vない＋ようにしてください', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('0d19752c-0ebb-460c-b493-6eaaa4ae133b', 'N4', '人に＋V (bị động)', 'Bị ai đó/ Được ai đó làm gì ~', 'Chủ thể gây tác động đứng trước に, động từ chia thể bị động', '[người] + に + V(thể bị động)', 'Diễn tả người nói chịu tác động (tốt hoặc xấu) từ hành động của người khác', NULL, NULL, NULL, '{}', NULL, 41, '人に＋V (bị động)', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('0d4783ce-2dd6-4d49-b2b0-e683556c83d4', 'N4', 'Aは／が＋V (bị động)', 'A được (bị) ~', 'Dùng khi chủ thể gây ra hành động không quan trọng/không nêu', 'A + は／が + V(thể bị động)', 'Diễn tả 1 sự vật/sự việc trở thành đối tượng của hành động (không cần nêu chủ thể)', NULL, NULL, NULL, '{}', NULL, 41, 'Aは／が＋V (bị động)', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;

-- ---------- jp_grammar_examples ----------
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('77bf3a96-859b-45a4-afd2-329a8d459070', NULL, 1, 'daily', '醤油をつけて食べます。', 'Chấm nước tương rồi ăn.', '醤油を＿＿＿食べます。', 'つけて', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('77bf3a96-859b-45a4-afd2-329a8d459070', NULL, 2, 'daily', '窓を開けて寝ます。', 'Mở cửa sổ rồi ngủ.', '窓を＿＿＿寝ます。', '開けて', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('77bf3a96-859b-45a4-afd2-329a8d459070', NULL, 3, 'daily', '手を洗ってご飯を食べます。', 'Rửa tay rồi ăn cơm.', '手を＿＿＿ご飯を食べます。', '洗って', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('afaa2be3-bc25-4622-b291-4fd66e76ab7b', NULL, 1, 'daily', '醤油をつけないで食べます。', 'Ăn không chấm nước tương.', '醤油を＿＿＿食べます。', 'つけないで', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('afaa2be3-bc25-4622-b291-4fd66e76ab7b', NULL, 2, 'daily', '朝ご飯を食べないで学校に行きます。', 'Đi học mà không ăn sáng.', '朝ご飯を＿＿＿学校に行きます。', '食べないで', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('afaa2be3-bc25-4622-b291-4fd66e76ab7b', NULL, 3, 'daily', '傘をささないで歩きます。', 'Đi bộ mà không che ô.', '傘を＿＿＿歩きます。', 'ささないで', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('bf4cdacc-c7d4-4106-b108-5caaa6ba8f1e', NULL, 1, 'daily', 'ほかの意見がなければ、これで終わりましょう。', 'Nếu không có ý kiến nào khác, hãy kết thúc tại đây.', 'ほかの意見が＿＿＿、これで終わりましょう。', 'なければ', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('bf4cdacc-c7d4-4106-b108-5caaa6ba8f1e', NULL, 2, 'daily', '安ければ、買います。', 'Nếu rẻ thì tôi sẽ mua.', '＿＿＿、買います。', '安ければ', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('bf4cdacc-c7d4-4106-b108-5caaa6ba8f1e', NULL, 3, 'daily', '時間があれば、遊びに来てください。', 'Nếu có thời gian thì hãy đến chơi.', '時間が＿＿＿、遊びに来てください。', 'あれば', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a3947630-a859-42af-b36b-af29226945ee', NULL, 1, 'daily', '電話番号がわからないんですが、どうすればいいですか。', 'Tôi không biết số điện thoại, phải làm sao bây giờ?', '電話番号がわからないんですが、＿＿＿。', 'どうすればいいですか', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a3947630-a859-42af-b36b-af29226945ee', NULL, 2, 'daily', 'パスワードを忘れたら、どうすればいいですか。', 'Nếu quên mật khẩu thì phải làm sao?', 'パスワードを忘れたら、＿＿＿。', 'どうすればいいですか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a3947630-a859-42af-b36b-af29226945ee', NULL, 3, 'daily', '道に迷ったら、どうすればいいですか。', 'Nếu bị lạc đường thì phải làm sao?', '道に迷ったら、＿＿＿。', 'どうすればいいですか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4b11a4ee-08d6-4615-a2d5-3d1b63a4c497', NULL, 1, 'daily', 'スーパーへ行きたいんですが、どうすればいいですか。スーパーならこの近くにあるよ。', 'Tôi muốn đi siêu thị thì như thế nào nhỉ? Nếu đi siêu thị thì có một cái ở gần đây đó.', 'スーパー＿＿＿この近くにあるよ。', 'なら', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4b11a4ee-08d6-4615-a2d5-3d1b63a4c497', NULL, 2, 'daily', '日本語を勉強するなら、この本がいいですよ。', 'Nếu học tiếng Nhật thì cuốn sách này tốt đấy.', '日本語を勉強する＿＿＿、この本がいいですよ。', 'なら', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4b11a4ee-08d6-4615-a2d5-3d1b63a4c497', NULL, 3, 'daily', '安いなら、この店がいいですよ。', 'Nếu muốn rẻ thì quán này tốt đấy.', '＿＿＿、この店がいいですよ。', '安いなら', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2219d632-3152-4726-91cc-9384307804e3', NULL, 1, 'daily', '日本語は勉強すればするほど面白くなります。', 'Tiếng Nhật mà càng học thì nó càng trở nên thú vị.', '日本語は勉強すれば＿＿＿面白くなります。', 'するほど', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2219d632-3152-4726-91cc-9384307804e3', NULL, 2, 'daily', 'このケーキは食べれば食べるほど好きになります。', 'Cái bánh này càng ăn càng thích.', 'このケーキは食べれば＿＿＿好きになります。', '食べるほど', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('2219d632-3152-4726-91cc-9384307804e3', NULL, 3, 'daily', '給料は高ければ高いほどいいです。', 'Lương càng cao càng tốt.', '給料は高ければ＿＿＿いいです。', '高いほど', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('61628965-9ed5-470f-babd-4e3fc290c5ef', NULL, 1, 'daily', '新聞が読めるように、漢字を勉強します。', 'Tôi sẽ học Kanji để có thể đọc báo.', '新聞が読める＿＿＿、漢字を勉強します。', 'ように', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('61628965-9ed5-470f-babd-4e3fc290c5ef', NULL, 2, 'daily', '忘れないように、メモします。', 'Ghi chú lại để không quên.', '忘れない＿＿＿、メモします。', 'ように', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('61628965-9ed5-470f-babd-4e3fc290c5ef', NULL, 3, 'daily', '遅れないように、早く出ます。', 'Ra ngoài sớm để không bị trễ.', '遅れない＿＿＿、早く出ます。', 'ように', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4d8074ac-af85-42aa-b35d-040346b64156', NULL, 1, 'daily', '日本語が話せるようになりました。', 'Tôi đã có thể nói tiếng Nhật.', '日本語が話せる＿＿＿。', 'ようになりました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4d8074ac-af85-42aa-b35d-040346b64156', NULL, 2, 'daily', '太りましたから、好きな服が着られなくなりました。', 'Bởi vì tôi đã tăng cân nên không thể mặc quần áo yêu thích của mình nữa.', '太りましたから、好きな服が＿＿＿。', '着られなくなりました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('4d8074ac-af85-42aa-b35d-040346b64156', NULL, 3, 'daily', '毎日練習して、ピアノが弾けるようになりました。', 'Luyện tập mỗi ngày nên tôi đã có thể chơi piano.', '毎日練習して、ピアノが＿＿＿。', '弾けるようになりました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('46c0ebd9-c99b-4f89-8a98-b24ef068ff17', NULL, 1, 'daily', '毎日運動して、何でも食べるようにしています。', 'Tôi cố gắng tập thể dục mỗi ngày và ăn mọi thứ.', '毎日運動して、何でも食べる＿＿＿。', 'ようにしています', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('46c0ebd9-c99b-4f89-8a98-b24ef068ff17', NULL, 2, 'daily', '甘い物を食べないようにしています。', 'Tôi cố gắng không ăn đồ ngọt.', '甘い物を食べない＿＿＿。', 'ようにしています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('46c0ebd9-c99b-4f89-8a98-b24ef068ff17', NULL, 3, 'daily', '毎朝早く起きるようにしています。', 'Tôi cố gắng dậy sớm mỗi sáng.', '毎朝早く起きる＿＿＿。', 'ようにしています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('36f58828-150f-44d0-899c-d79c07e20d8d', NULL, 1, 'daily', '必ず時間を守るようにしてください。', 'Hãy chắc chắn là bạn sẽ đúng giờ.', '必ず時間を守る＿＿＿。', 'ようにしてください', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('36f58828-150f-44d0-899c-d79c07e20d8d', NULL, 2, 'daily', '遅刻しないようにしてください。', 'Xin hãy cố gắng đừng đi trễ.', '遅刻しない＿＿＿。', 'ようにしてください', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('36f58828-150f-44d0-899c-d79c07e20d8d', NULL, 3, 'daily', '毎日薬を飲むようにしてください。', 'Xin hãy cố gắng uống thuốc mỗi ngày.', '毎日薬を飲む＿＿＿。', 'ようにしてください', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0d19752c-0ebb-460c-b493-6eaaa4ae133b', NULL, 1, 'daily', '私は課長に褒められました。', 'Tôi được trưởng phòng khen.', '私は課長に＿＿＿。', '褒められました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0d19752c-0ebb-460c-b493-6eaaa4ae133b', NULL, 2, 'daily', '私は先生に叱られました。', 'Tôi bị thầy/cô mắng.', '私は先生に＿＿＿。', '叱られました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0d19752c-0ebb-460c-b493-6eaaa4ae133b', NULL, 3, 'daily', '私は友達にパーティーに招待されました。', 'Tôi được bạn mời đến bữa tiệc.', '私は友達にパーティーに＿＿＿。', '招待されました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0d4783ce-2dd6-4d49-b2b0-e683556c83d4', NULL, 1, 'daily', '大阪で展覧会が開かれます。', 'Một cuộc triển lãm sẽ được tổ chức tại Osaka.', '大阪で展覧会が＿＿＿。', '開かれます', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0d4783ce-2dd6-4d49-b2b0-e683556c83d4', NULL, 2, 'daily', 'この本は多くの人に読まれています。', 'Cuốn sách này được nhiều người đọc.', 'この本は多くの人に＿＿＿。', '読まれています', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0d4783ce-2dd6-4d49-b2b0-e683556c83d4', NULL, 3, 'daily', 'このビルは去年建てられました。', 'Tòa nhà này được xây dựng năm ngoái.', 'このビルは去年＿＿＿。', '建てられました', 'generated');

-- ---------- jp_grammar_questions (toàn bộ generated) ----------
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('77bf3a96-859b-45a4-afd2-329a8d459070', NULL, 'fill_blank', 'Điền vào chỗ trống: 醤油を＿＿＿食べます。', NULL, NULL, NULL, NULL, 'つけて', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('77bf3a96-859b-45a4-afd2-329a8d459070', NULL, 'choose_meaning', 'Mẫu ngữ pháp "V1てV2～" có nghĩa nào sau đây?', 'Làm V2 mà có V1', 'Nên làm như thế nào thì tốt nhỉ?', 'Cố gắng làm gì', 'Đã làm được / Đã không làm được', 'Làm V2 mà có V1', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('77bf3a96-859b-45a4-afd2-329a8d459070', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Làm V2 mà có V1"?', 'V1ないでV2～', 'Vる／Aい／Aな (thể điều kiện) ＋ Vる／Aい／A ＋ ほど', 'Vるように／Vなく＋なります／なりました', 'V1てV2～', 'V1てV2～', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('afaa2be3-bc25-4622-b291-4fd66e76ab7b', NULL, 'fill_blank', 'Điền vào chỗ trống: 醤油を＿＿＿食べます。', NULL, NULL, NULL, NULL, 'つけないで', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('afaa2be3-bc25-4622-b291-4fd66e76ab7b', NULL, 'choose_meaning', 'Mẫu ngữ pháp "V1ないでV2～" có nghĩa nào sau đây?', 'A được (bị) ~', 'Bị ai đó/ Được ai đó làm gì ~', 'Nên làm như thế nào thì tốt nhỉ?', 'Làm V2 mà không làm V1', 'Làm V2 mà không làm V1', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('afaa2be3-bc25-4622-b291-4fd66e76ab7b', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Làm V2 mà không làm V1"?', 'V1ないでV2～', 'Vる／Aい＋なら', 'Vるように／Vなく＋なります／なりました', '～Vば (thể điều kiện)', 'V1ないでV2～', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('bf4cdacc-c7d4-4106-b108-5caaa6ba8f1e', NULL, 'fill_blank', 'Điền vào chỗ trống: ほかの意見が＿＿＿、これで終わりましょう。', NULL, NULL, NULL, NULL, 'なければ', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('bf4cdacc-c7d4-4106-b108-5caaa6ba8f1e', NULL, 'choose_meaning', 'Mẫu ngữ pháp "～Vば (thể điều kiện)" có nghĩa nào sau đây?', 'Làm V2 mà có V1', 'Nên làm như thế nào thì tốt nhỉ?', 'Nếu ~', 'Để A thì B', 'Nếu ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('bf4cdacc-c7d4-4106-b108-5caaa6ba8f1e', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Nếu ~"?', 'Vる／Aい＋なら', 'Aは／が＋V (bị động)', 'Vる／Vない＋ようにしてください', '～Vば (thể điều kiện)', '～Vば (thể điều kiện)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a3947630-a859-42af-b36b-af29226945ee', NULL, 'fill_blank', 'Điền vào chỗ trống: 電話番号がわからないんですが、＿＿＿。', NULL, NULL, NULL, NULL, 'どうすればいいですか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a3947630-a859-42af-b36b-af29226945ee', NULL, 'choose_meaning', 'Mẫu ngữ pháp "どうすればいいですか" có nghĩa nào sau đây?', 'Làm V2 mà không làm V1', 'Càng ~ càng ~', 'Nên làm như thế nào thì tốt nhỉ?', 'A được (bị) ~', 'Nên làm như thế nào thì tốt nhỉ?', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a3947630-a859-42af-b36b-af29226945ee', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Nên làm như thế nào thì tốt nhỉ?"?', 'どうすればいいですか', 'A[Vる／Vない]＋ように、B', 'Aは／が＋V (bị động)', 'Vる／Vない＋ようにしています', 'どうすればいいですか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4b11a4ee-08d6-4615-a2d5-3d1b63a4c497', NULL, 'fill_blank', 'Điền vào chỗ trống: スーパー＿＿＿この近くにあるよ。', NULL, NULL, NULL, NULL, 'なら', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4b11a4ee-08d6-4615-a2d5-3d1b63a4c497', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vる／Aい＋なら" có nghĩa nào sau đây?', 'Sử dụng khi đưa ra lời khuyên cho người khác', 'Cố gắng làm gì', 'Nên làm như thế nào thì tốt nhỉ?', 'Hãy làm gì ~', 'Sử dụng khi đưa ra lời khuyên cho người khác', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4b11a4ee-08d6-4615-a2d5-3d1b63a4c497', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Sử dụng khi đưa ra lời khuyên cho người khác"?', 'Vる／Aい＋なら', 'Vるように／Vなく＋なります／なりました', '人に＋V (bị động)', 'どうすればいいですか', 'Vる／Aい＋なら', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2219d632-3152-4726-91cc-9384307804e3', NULL, 'fill_blank', 'Điền vào chỗ trống: 日本語は勉強すれば＿＿＿面白くなります。', NULL, NULL, NULL, NULL, 'するほど', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2219d632-3152-4726-91cc-9384307804e3', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vる／Aい／Aな (thể điều kiện) ＋ Vる／Aい／A ＋ ほど" có nghĩa nào sau đây?', 'Càng ~ càng ~', 'Hãy làm gì ~', 'Làm V2 mà không làm V1', 'Cố gắng làm gì', 'Càng ~ càng ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('2219d632-3152-4726-91cc-9384307804e3', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Càng ~ càng ~"?', 'どうすればいいですか', 'Vる／Aい／Aな (thể điều kiện) ＋ Vる／Aい／A ＋ ほど', 'V1ないでV2～', 'A[Vる／Vない]＋ように、B', 'Vる／Aい／Aな (thể điều kiện) ＋ Vる／Aい／A ＋ ほど', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('61628965-9ed5-470f-babd-4e3fc290c5ef', NULL, 'fill_blank', 'Điền vào chỗ trống: 新聞が読める＿＿＿、漢字を勉強します。', NULL, NULL, NULL, NULL, 'ように', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('61628965-9ed5-470f-babd-4e3fc290c5ef', NULL, 'choose_meaning', 'Mẫu ngữ pháp "A[Vる／Vない]＋ように、B" có nghĩa nào sau đây?', 'Nên làm như thế nào thì tốt nhỉ?', 'Để A thì B', 'A được (bị) ~', 'Đã làm được / Đã không làm được', 'Để A thì B', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('61628965-9ed5-470f-babd-4e3fc290c5ef', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Để A thì B"?', 'Aは／が＋V (bị động)', 'A[Vる／Vない]＋ように、B', 'V1てV2～', 'Vるように／Vなく＋なります／なりました', 'A[Vる／Vない]＋ように、B', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4d8074ac-af85-42aa-b35d-040346b64156', NULL, 'fill_blank', 'Điền vào chỗ trống: 日本語が話せる＿＿＿。', NULL, NULL, NULL, NULL, 'ようになりました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4d8074ac-af85-42aa-b35d-040346b64156', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vるように／Vなく＋なります／なりました" có nghĩa nào sau đây?', 'Bị ai đó/ Được ai đó làm gì ~', 'Đã làm được / Đã không làm được', 'Càng ~ càng ~', 'Nếu ~', 'Đã làm được / Đã không làm được', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('4d8074ac-af85-42aa-b35d-040346b64156', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Đã làm được / Đã không làm được"?', 'V1てV2～', 'Vる／Aい／Aな (thể điều kiện) ＋ Vる／Aい／A ＋ ほど', 'Vるように／Vなく＋なります／なりました', 'V1ないでV2～', 'Vるように／Vなく＋なります／なりました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('46c0ebd9-c99b-4f89-8a98-b24ef068ff17', NULL, 'fill_blank', 'Điền vào chỗ trống: 毎日運動して、何でも食べる＿＿＿。', NULL, NULL, NULL, NULL, 'ようにしています', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('46c0ebd9-c99b-4f89-8a98-b24ef068ff17', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vる／Vない＋ようにしています" có nghĩa nào sau đây?', 'Bị ai đó/ Được ai đó làm gì ~', 'Hãy làm gì ~', 'Để A thì B', 'Cố gắng làm gì', 'Cố gắng làm gì', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('46c0ebd9-c99b-4f89-8a98-b24ef068ff17', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Cố gắng làm gì"?', 'A[Vる／Vない]＋ように、B', 'Vるように／Vなく＋なります／なりました', 'Vる／Vない＋ようにしています', 'Aは／が＋V (bị động)', 'Vる／Vない＋ようにしています', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('36f58828-150f-44d0-899c-d79c07e20d8d', NULL, 'fill_blank', 'Điền vào chỗ trống: 必ず時間を守る＿＿＿。', NULL, NULL, NULL, NULL, 'ようにしてください', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('36f58828-150f-44d0-899c-d79c07e20d8d', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Vる／Vない＋ようにしてください" có nghĩa nào sau đây?', 'Đã làm được / Đã không làm được', 'Hãy làm gì ~', 'Càng ~ càng ~', 'Làm V2 mà không làm V1', 'Hãy làm gì ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('36f58828-150f-44d0-899c-d79c07e20d8d', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Hãy làm gì ~"?', 'Vる／Vない＋ようにしてください', 'V1てV2～', '人に＋V (bị động)', '～Vば (thể điều kiện)', 'Vる／Vない＋ようにしてください', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0d19752c-0ebb-460c-b493-6eaaa4ae133b', NULL, 'fill_blank', 'Điền vào chỗ trống: 私は課長に＿＿＿。', NULL, NULL, NULL, NULL, '褒められました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0d19752c-0ebb-460c-b493-6eaaa4ae133b', NULL, 'choose_meaning', 'Mẫu ngữ pháp "人に＋V (bị động)" có nghĩa nào sau đây?', 'Càng ~ càng ~', 'Sử dụng khi đưa ra lời khuyên cho người khác', 'Để A thì B', 'Bị ai đó/ Được ai đó làm gì ~', 'Bị ai đó/ Được ai đó làm gì ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0d19752c-0ebb-460c-b493-6eaaa4ae133b', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "Bị ai đó/ Được ai đó làm gì ~"?', 'Vる／Aい／Aな (thể điều kiện) ＋ Vる／Aい／A ＋ ほど', 'Vる／Vない＋ようにしてください', '人に＋V (bị động)', 'Vるように／Vなく＋なります／なりました', '人に＋V (bị động)', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0d4783ce-2dd6-4d49-b2b0-e683556c83d4', NULL, 'fill_blank', 'Điền vào chỗ trống: 大阪で展覧会が＿＿＿。', NULL, NULL, NULL, NULL, '開かれます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0d4783ce-2dd6-4d49-b2b0-e683556c83d4', NULL, 'choose_meaning', 'Mẫu ngữ pháp "Aは／が＋V (bị động)" có nghĩa nào sau đây?', 'Làm V2 mà có V1', 'Càng ~ càng ~', 'A được (bị) ~', 'Cố gắng làm gì', 'A được (bị) ~', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0d4783ce-2dd6-4d49-b2b0-e683556c83d4', NULL, 'choose_pattern', 'Mẫu ngữ pháp nào có nghĩa "A được (bị) ~"?', 'Vる／Aい／Aな (thể điều kiện) ＋ Vる／Aい／A ＋ ほど', 'どうすればいいですか', 'Vるように／Vなく＋なります／なりました', 'Aは／が＋V (bị động)', 'Aは／が＋V (bị động)', 'generated');
