-- ============================================================
-- jp-go — Ngữ pháp N4, round 6 (10 mẫu, trang in 43).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 3 - 文法.
-- Nhóm 授受表現 (cho/nhận) + mục đích + đánh giá/tốn kém.
-- ============================================================

-- ---------- jp_grammar ----------
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('7c2795e6-c507-4ed8-82cd-e26bb67ed4a2', 'N4', '人に何かをあげます／さしあげます／やります', 'Cho (biếu, tặng) ai đó cái gì', 'さしあげます (khiêm nhường, cho người trên) / あげます (trung tính, ngang hàng) / やります (cho người dưới, động vật, thực vật)', 'N1は N2に N3を あげます／さしあげます／やります', 'Diễn tả hành động cho/tặng/biếu ai đó một thứ gì, chọn động từ theo quan hệ trên dưới', 'さしあげます: khiêm nhường (cho người trên); あげます: trung tính; やります: cho người dưới/động vật/thực vật', NULL, NULL, '{}', NULL, 43, '人に何かをあげます／さしあげます／やります', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('1c5bbbe5-f37d-4dd4-a9e9-c280135b5aa8', 'N4', '人から／に何かをいただきます／もらいます', 'Nhận từ ai đó cái gì', 'いただきます là khiêm nhường ngữ của もらいます, dùng khi nhận từ người trên', 'N1は N2から／に N3を いただきます／もらいます', 'Diễn tả hành động nhận một thứ gì từ ai đó, hoặc xin ai đó cái gì', 'いただきます: khiêm nhường (nhận từ người trên); もらいます: trung tính', NULL, NULL, '{}', NULL, 43, '人から／に何かをいただきます／もらいます', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('c0fbcf4f-cd0b-4760-a8c0-0dd394bb1978', 'N4', '人が何かをくださいます／くれます', 'Ai đó cho mình cái gì', 'くださいます là kính ngữ của くれます, chủ ngữ là người cho (đối lập với もらう chủ ngữ là người nhận)', 'N1が（は） N2に N3を くださいます／くれます', 'Diễn tả hành động ai đó cho/tặng mình (hoặc người trong nhóm mình) một thứ gì', 'くださいます: kính ngữ (người trên cho mình); くれます: trung tính', NULL, NULL, '{}', NULL, 43, '人が何かをくださいます／くれます', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('02004a84-aee7-41ab-8666-63043678f338', 'N4', '人に何かをVて＋さしあげます／あげます／やります', 'N1 làm V cho N2 (ban ơn, giúp đỡ)', 'Thêm て-form trước あげる/さしあげる/やる để diễn tả làm hành động đó vì lợi ích người khác', 'N1は N2に N3をV(て形) さしあげます／あげます／やります', 'Diễn tả hành động làm gì đó cho ai đó (có sắc thái ban ơn nếu dùng với người trên)', 'さしあげます: khiêm nhường (làm cho người trên); あげます: trung tính; やります: cho người dưới/động vật/thực vật', NULL, NULL, '{}', NULL, 43, '人に何かをVて＋さしあげます／あげます／やります', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('252e27db-87a4-48a2-b960-0366589b2dc2', 'N4', '人に何かをVていただきます／Vてもらいます', 'Nhờ/để ai đó làm gì cho mình', 'Chủ ngữ là người nhận lợi ích (mình), いただきます là khiêm nhường ngữ', 'N1は N2に N3をV(て形) いただきます／もらいます', 'Diễn tả việc mình nhờ/được ai đó làm gì đó cho mình', 'いただきます: khiêm nhường (nhờ người trên); もらいます: trung tính', NULL, NULL, '{}', NULL, 43, '人に何かをVていただきます／Vてもらいます', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('a0b65def-4be5-41b1-9915-fc8c5d8c199e', 'N4', '人が(は)何かをVてくださいます／くれます', 'Ai đó làm gì cho tôi', 'Chủ ngữ là người làm hành động, くださいます là kính ngữ', 'N1が（は） N2に N3をV(て形) くださいます／くれます', 'Diễn tả việc ai đó chủ động làm gì đó cho mình (có sắc thái biết ơn)', 'くださいます: kính ngữ (người trên làm cho mình); くれます: trung tính', NULL, NULL, '{}', NULL, 43, '人が(は)何かをVてくださいます／くれます', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('5dce2c42-e3fd-4001-8c71-9c1e666a430c', 'N4', 'N1にN2をV', 'Mua/làm N2 để làm quà, kỉ niệm cho N1', 'N1 (dịp/mục đích) + に thường đi cùng động từ mua/chọn', 'N1（お土産／記念など）に N2を 買います／選びます', 'Diễn tả việc mua hoặc chọn một thứ gì đó để làm quà/kỷ niệm cho một dịp', NULL, NULL, NULL, '{}', NULL, 43, 'N1にN2をV', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('d81c5d74-1e44-431a-ac69-76349a62a9b8', 'N4', 'Vる／Nのために、〜', 'Vì ~, để ~, cho ~ (mục đích)', 'ために nêu mục đích cần đạt được cho hành động ở vế sau', 'V(thể từ điển)／N + の + ために、〜', 'Nêu mục đích của hành động ở vế sau', NULL, NULL, NULL, '{}', NULL, 43, 'Vる／Nのために、〜', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'N4', 'Vるの／Nに、〜', 'Dùng để làm gì / đánh giá hữu ích, cần thiết / tốn thời gian, tiền bạc', 'のに biến mệnh đề động từ thành cụm danh từ đóng vai trò bổ ngữ mục đích', 'V(thể từ điển)／N + のに、〜', NULL, NULL, NULL, NULL, '{}', NULL, 43, 'Vるの／Nに、〜', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('ada779fa-fad6-4bd1-aa67-1435b1b4b079', 'N4', '数量詞＋は〜', 'Tối thiểu, ít nhất là ~', 'は sau số lượng nhấn mạnh mức tối thiểu cần đạt', '[Số lượng] + は + [đủ/cần thiết]', 'Nêu số lượng tối thiểu cần có để thực hiện việc gì', NULL, NULL, NULL, '{}', NULL, 43, '数量詞＋は〜', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;

-- ---------- jp_grammar_usages (chỉ tạo khi multi_usage) ----------
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('3cfdded9-8c9b-48ca-9eb7-72b7be0e319e', 'dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 1, 'Dùng để làm gì (Vるの／Nに + 使う)', 'V(thể từ điển)／N + のに + 使います', NULL, NULL, 43, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('df58e22a-42e1-4e69-a8be-49a65ef91ed9', 'dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 2, 'Đánh giá hữu ích/cần thiết (Vるの／Nに + 役に立つ／要る／いい／便利／必要だ)', 'V(thể từ điển)／N + のに + 便利です／必要です／いいです', NULL, NULL, 43, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('b6523eb6-be02-41cc-ae13-1bd081fe467d', 'dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 3, 'Tốn (mất) thời gian/tiền (Vるの／Nに + 時間がかかる／お金がかかる)', 'V(thể từ điển)／N + のに + 時間／お金が かかります', NULL, NULL, 43, 'pdf');

-- ---------- jp_grammar_examples ----------
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('7c2795e6-c507-4ed8-82cd-e26bb67ed4a2', NULL, 1, 'daily', '社長にプレゼントをさしあげます。', 'Chúng tôi sẽ tặng quà cho Giám đốc.', '社長にプレゼントを＿＿＿。', 'さしあげます', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('7c2795e6-c507-4ed8-82cd-e26bb67ed4a2', NULL, 2, 'daily', '友だちに誕生日のプレゼントをあげました。', 'Tôi tặng quà sinh nhật cho một người bạn.', '友だちに誕生日のプレゼントを＿＿＿。', 'あげました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('7c2795e6-c507-4ed8-82cd-e26bb67ed4a2', NULL, 3, 'daily', '子どもにおかしをやります。', 'Tôi cho kẹo những đứa trẻ con.', '子どもにおかしを＿＿＿。', 'やります', 'pdf');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('7c2795e6-c507-4ed8-82cd-e26bb67ed4a2', NULL, 'fill_blank', 'Điền vào chỗ trống: 社長にプレゼントを＿＿＿。', NULL, NULL, NULL, NULL, 'さしあげます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('7c2795e6-c507-4ed8-82cd-e26bb67ed4a2', NULL, 'choose_meaning', '「友だちに誕生日のプレゼントをあげました。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Tôi tặng quà sinh nhật cho một người bạn.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('7c2795e6-c507-4ed8-82cd-e26bb67ed4a2', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 子どもにおかしを＿＿＿。', NULL, NULL, NULL, NULL, 'やります', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('1c5bbbe5-f37d-4dd4-a9e9-c280135b5aa8', NULL, 1, 'daily', 'おばあさんにかわいいセーターをもらいました。', 'Tôi nhận được một chiếc áo len dễ thương từ bà tôi.', 'おばあさんにかわいいセーターを＿＿＿。', 'もらいました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('1c5bbbe5-f37d-4dd4-a9e9-c280135b5aa8', NULL, 2, 'daily', '先生に本をいただきました。', 'Tôi nhận được một cuốn sách từ thầy giáo.', '先生に本を＿＿＿。', 'いただきました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('1c5bbbe5-f37d-4dd4-a9e9-c280135b5aa8', NULL, 3, 'daily', '友だちからチョコレートをもらいました。', 'Tôi nhận được sô-cô-la từ bạn.', '友だちからチョコレートを＿＿＿。', 'もらいました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('1c5bbbe5-f37d-4dd4-a9e9-c280135b5aa8', NULL, 'fill_blank', 'Điền vào chỗ trống: おばあさんにかわいいセーターを＿＿＿。', NULL, NULL, NULL, NULL, 'もらいました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('1c5bbbe5-f37d-4dd4-a9e9-c280135b5aa8', NULL, 'choose_meaning', '「先生に本をいただきました。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Tôi nhận được một cuốn sách từ thầy giáo.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('1c5bbbe5-f37d-4dd4-a9e9-c280135b5aa8', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 友だちからチョコレートを＿＿＿。', NULL, NULL, NULL, NULL, 'もらいました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c0fbcf4f-cd0b-4760-a8c0-0dd394bb1978', NULL, 1, 'daily', '彼氏がバラの花をくれました。', 'Bạn trai tặng tôi một bông hoa hồng.', '彼氏がバラの花を＿＿＿。', 'くれました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c0fbcf4f-cd0b-4760-a8c0-0dd394bb1978', NULL, 2, 'daily', '先生が辞書をくださいました。', 'Thầy giáo đã cho tôi một cuốn từ điển.', '先生が辞書を＿＿＿。', 'くださいました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('c0fbcf4f-cd0b-4760-a8c0-0dd394bb1978', NULL, 3, 'daily', '友だちが誕生日にケーキをくれました。', 'Bạn tôi đã tặng tôi bánh kem vào ngày sinh nhật.', '友だちが誕生日にケーキを＿＿＿。', 'くれました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c0fbcf4f-cd0b-4760-a8c0-0dd394bb1978', NULL, 'fill_blank', 'Điền vào chỗ trống: 彼氏がバラの花を＿＿＿。', NULL, NULL, NULL, NULL, 'くれました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c0fbcf4f-cd0b-4760-a8c0-0dd394bb1978', NULL, 'choose_meaning', '「先生が辞書をくださいました。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Thầy giáo đã cho tôi một cuốn từ điển.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('c0fbcf4f-cd0b-4760-a8c0-0dd394bb1978', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 友だちが誕生日にケーキを＿＿＿。', NULL, NULL, NULL, NULL, 'くれました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('02004a84-aee7-41ab-8666-63043678f338', NULL, 1, 'daily', '部長にお金を貸してさしあげました。', 'Tôi đã cho trưởng phòng mượn tiền.', '部長にお金を貸して＿＿＿。', 'さしあげました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('02004a84-aee7-41ab-8666-63043678f338', NULL, 2, 'daily', '妹に宿題を教えてあげました。', 'Tôi đã dạy em gái làm bài tập.', '妹に宿題を教えて＿＿＿。', 'あげました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('02004a84-aee7-41ab-8666-63043678f338', NULL, 3, 'daily', '犬にご飯を作ってやりました。', 'Tôi đã nấu cơm cho con chó.', '犬にご飯を作って＿＿＿。', 'やりました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('02004a84-aee7-41ab-8666-63043678f338', NULL, 'fill_blank', 'Điền vào chỗ trống: 部長にお金を貸して＿＿＿。', NULL, NULL, NULL, NULL, 'さしあげました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('02004a84-aee7-41ab-8666-63043678f338', NULL, 'choose_meaning', '「妹に宿題を教えてあげました。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Tôi đã dạy em gái làm bài tập.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('02004a84-aee7-41ab-8666-63043678f338', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 犬にご飯を作って＿＿＿。', NULL, NULL, NULL, NULL, 'やりました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('252e27db-87a4-48a2-b960-0366589b2dc2', NULL, 1, 'daily', '部長にレポートを見ていただきます。', 'Trưởng phòng xem báo cáo cho tôi.', '部長にレポートを見て＿＿＿。', 'いただきます', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('252e27db-87a4-48a2-b960-0366589b2dc2', NULL, 2, 'daily', '友だちに荷物を運んでもらいました。', 'Tôi đã nhờ bạn chuyển đồ giúp.', '友だちに荷物を運んで＿＿＿。', 'もらいました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('252e27db-87a4-48a2-b960-0366589b2dc2', NULL, 3, 'daily', '先生に作文を直していただきました。', 'Tôi đã được thầy giáo sửa bài văn cho.', '先生に作文を直して＿＿＿。', 'いただきました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('252e27db-87a4-48a2-b960-0366589b2dc2', NULL, 'fill_blank', 'Điền vào chỗ trống: 部長にレポートを見て＿＿＿。', NULL, NULL, NULL, NULL, 'いただきます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('252e27db-87a4-48a2-b960-0366589b2dc2', NULL, 'choose_meaning', '「友だちに荷物を運んでもらいました。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Tôi đã nhờ bạn chuyển đồ giúp.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('252e27db-87a4-48a2-b960-0366589b2dc2', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 先生に作文を直して＿＿＿。', NULL, NULL, NULL, NULL, 'いただきました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a0b65def-4be5-41b1-9915-fc8c5d8c199e', NULL, 1, 'daily', '社長は私の娘に書道を教えてくださいました。', 'Giám đốc dạy con gái tôi thư pháp.', '社長は私の娘に書道を教えて＿＿＿。', 'くださいました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a0b65def-4be5-41b1-9915-fc8c5d8c199e', NULL, 2, 'daily', '友だちが引っ越しを手伝ってくれました。', 'Bạn tôi đã giúp tôi chuyển nhà.', '友だちが引っ越しを手伝って＿＿＿。', 'くれました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a0b65def-4be5-41b1-9915-fc8c5d8c199e', NULL, 3, 'daily', '母が毎朝お弁当を作ってくれます。', 'Mẹ tôi làm cơm hộp cho tôi mỗi sáng.', '母が毎朝お弁当を作って＿＿＿。', 'くれます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a0b65def-4be5-41b1-9915-fc8c5d8c199e', NULL, 'fill_blank', 'Điền vào chỗ trống: 社長は私の娘に書道を教えて＿＿＿。', NULL, NULL, NULL, NULL, 'くださいました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a0b65def-4be5-41b1-9915-fc8c5d8c199e', NULL, 'choose_meaning', '「友だちが引っ越しを手伝ってくれました。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Bạn tôi đã giúp tôi chuyển nhà.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a0b65def-4be5-41b1-9915-fc8c5d8c199e', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 母が毎朝お弁当を作って＿＿＿。', NULL, NULL, NULL, NULL, 'くれます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('5dce2c42-e3fd-4001-8c71-9c1e666a430c', NULL, 1, 'daily', '私は旅行のお土産に人形を買いました。', 'Tôi đã mua một búp bê làm kỷ niệm chuyến đi của mình.', '私は旅行のお土産に人形を＿＿＿。', '買いました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('5dce2c42-e3fd-4001-8c71-9c1e666a430c', NULL, 2, 'daily', '結婚のお祝いに食器を選びました。', 'Tôi đã chọn bộ chén đĩa để làm quà mừng đám cưới.', '結婚のお祝いに食器を＿＿＿。', '選びました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('5dce2c42-e3fd-4001-8c71-9c1e666a430c', NULL, 3, 'daily', '卒業の記念にアルバムを作りました。', 'Tôi đã làm một cuốn album để làm kỷ niệm tốt nghiệp.', '卒業の記念にアルバムを＿＿＿。', '作りました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('5dce2c42-e3fd-4001-8c71-9c1e666a430c', NULL, 'fill_blank', 'Điền vào chỗ trống: 私は旅行のお土産に人形を＿＿＿。', NULL, NULL, NULL, NULL, '買いました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('5dce2c42-e3fd-4001-8c71-9c1e666a430c', NULL, 'choose_meaning', '「結婚のお祝いに食器を選びました。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Tôi đã chọn bộ chén đĩa để làm quà mừng đám cưới.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('5dce2c42-e3fd-4001-8c71-9c1e666a430c', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 卒業の記念にアルバムを＿＿＿。', NULL, NULL, NULL, NULL, '作りました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('d81c5d74-1e44-431a-ac69-76349a62a9b8', NULL, 1, 'daily', '大学に入るために、一生懸命勉強します。', 'Để vào đại học, tôi sẽ chăm chỉ học tập.', '大学に入る＿＿＿、一生懸命勉強します。', 'ために', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('d81c5d74-1e44-431a-ac69-76349a62a9b8', NULL, 2, 'daily', '家族のために、毎日一生懸命働いています。', 'Vì gia đình, tôi làm việc chăm chỉ mỗi ngày.', '家族の＿＿＿、毎日一生懸命働いています。', 'ために', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('d81c5d74-1e44-431a-ac69-76349a62a9b8', NULL, 3, 'daily', '健康のために、毎朝ジョギングをしています。', 'Vì sức khỏe, tôi chạy bộ mỗi sáng.', '健康の＿＿＿、毎朝ジョギングをしています。', 'ために', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('d81c5d74-1e44-431a-ac69-76349a62a9b8', NULL, 'fill_blank', 'Điền vào chỗ trống: 大学に入る＿＿＿、一生懸命勉強します。', NULL, NULL, NULL, NULL, 'ために', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('d81c5d74-1e44-431a-ac69-76349a62a9b8', NULL, 'choose_meaning', '「家族のために、毎日一生懸命働いています。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Vì gia đình, tôi làm việc chăm chỉ mỗi ngày.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('d81c5d74-1e44-431a-ac69-76349a62a9b8', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 健康の＿＿＿、毎朝ジョギングをしています。', NULL, NULL, NULL, NULL, 'ために', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', '3cfdded9-8c9b-48ca-9eb7-72b7be0e319e', 1, 'daily', 'やかんはお湯を沸かすのに使います。', 'Ấm đun nước được sử dụng để đun sôi nước.', 'やかんはお湯を沸かす＿＿＿使います。', 'のに', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', '3cfdded9-8c9b-48ca-9eb7-72b7be0e319e', 2, 'daily', 'はさみは紙を切るのに使います。', 'Kéo được dùng để cắt giấy.', 'はさみは紙を切る＿＿＿使います。', 'のに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', '3cfdded9-8c9b-48ca-9eb7-72b7be0e319e', 3, 'daily', 'この機械は米を炊くのに使います。', 'Cái máy này được dùng để nấu cơm.', 'この機械は米を炊く＿＿＿使います。', 'のに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', '3cfdded9-8c9b-48ca-9eb7-72b7be0e319e', 'fill_blank', 'Điền vào chỗ trống: やかんはお湯を沸かす＿＿＿使います。', NULL, NULL, NULL, NULL, 'のに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', '3cfdded9-8c9b-48ca-9eb7-72b7be0e319e', 'choose_meaning', '「はさみは紙を切るのに使います。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Kéo được dùng để cắt giấy.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', '3cfdded9-8c9b-48ca-9eb7-72b7be0e319e', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: この機械は米を炊く＿＿＿使います。', NULL, NULL, NULL, NULL, 'のに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'df58e22a-42e1-4e69-a8be-49a65ef91ed9', 1, 'daily', '風呂敷は物を包むのに便利です。', 'Khăn gói đồ thuận tiện cho việc gói đồ.', '風呂敷は物を包む＿＿＿便利です。', 'のに', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'df58e22a-42e1-4e69-a8be-49a65ef91ed9', 2, 'daily', '辞書は言葉の意味を調べるのに役に立ちます。', 'Từ điển hữu ích cho việc tra nghĩa của từ.', '辞書は言葉の意味を調べる＿＿＿役に立ちます。', 'のに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'df58e22a-42e1-4e69-a8be-49a65ef91ed9', 3, 'daily', 'このアプリは日本語を勉強するのにいいです。', 'Ứng dụng này tốt cho việc học tiếng Nhật.', 'このアプリは日本語を勉強する＿＿＿いいです。', 'のに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'df58e22a-42e1-4e69-a8be-49a65ef91ed9', 'fill_blank', 'Điền vào chỗ trống: 風呂敷は物を包む＿＿＿便利です。', NULL, NULL, NULL, NULL, 'のに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'df58e22a-42e1-4e69-a8be-49a65ef91ed9', 'choose_meaning', '「辞書は言葉の意味を調べるのに役に立ちます。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Từ điển hữu ích cho việc tra nghĩa của từ.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'df58e22a-42e1-4e69-a8be-49a65ef91ed9', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: このアプリは日本語を勉強する＿＿＿いいです。', NULL, NULL, NULL, NULL, 'のに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'b6523eb6-be02-41cc-ae13-1bd081fe467d', 1, 'daily', 'この車を修理するのに2時間かかります。', 'Sẽ mất 2 giờ để sửa chiếc xe này.', 'この車を修理する＿＿＿2時間かかります。', 'のに', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'b6523eb6-be02-41cc-ae13-1bd081fe467d', 2, 'daily', '家を建てるのに1年かかりました。', 'Đã mất 1 năm để xây nhà.', '家を建てる＿＿＿1年かかりました。', 'のに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'b6523eb6-be02-41cc-ae13-1bd081fe467d', 3, 'daily', '留学するのにたくさんお金がかかります。', 'Đi du học tốn rất nhiều tiền.', '留学する＿＿＿たくさんお金がかかります。', 'のに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'b6523eb6-be02-41cc-ae13-1bd081fe467d', 'fill_blank', 'Điền vào chỗ trống: この車を修理する＿＿＿2時間かかります。', NULL, NULL, NULL, NULL, 'のに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'b6523eb6-be02-41cc-ae13-1bd081fe467d', 'choose_meaning', '「家を建てるのに1年かかりました。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Đã mất 1 năm để xây nhà.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dccdf471-d6f2-430b-9ac3-b383cb0a4e47', 'b6523eb6-be02-41cc-ae13-1bd081fe467d', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 留学する＿＿＿たくさんお金がかかります。', NULL, NULL, NULL, NULL, 'のに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ada779fa-fad6-4bd1-aa67-1435b1b4b079', NULL, 1, 'daily', 'パーティーをするのに10人は必要です。', 'Để có một bữa tiệc cần có ít nhất 10 người.', 'パーティーをするのに10人＿＿＿必要です。', 'は', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ada779fa-fad6-4bd1-aa67-1435b1b4b079', NULL, 2, 'daily', 'この仕事を終わらせるのに1週間はかかります。', 'Để hoàn thành công việc này cần ít nhất 1 tuần.', 'この仕事を終わらせるのに1週間＿＿＿かかります。', 'は', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('ada779fa-fad6-4bd1-aa67-1435b1b4b079', NULL, 3, 'daily', '家族旅行には10万円は必要です。', 'Cho chuyến du lịch gia đình cần ít nhất 100 nghìn yên.', '家族旅行には10万円＿＿＿必要です。', 'は', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ada779fa-fad6-4bd1-aa67-1435b1b4b079', NULL, 'fill_blank', 'Điền vào chỗ trống: パーティーをするのに10人＿＿＿必要です。', NULL, NULL, NULL, NULL, 'は', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ada779fa-fad6-4bd1-aa67-1435b1b4b079', NULL, 'choose_meaning', '「この仕事を終わらせるのに1週間はかかります。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Để hoàn thành công việc này cần ít nhất 1 tuần.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('ada779fa-fad6-4bd1-aa67-1435b1b4b079', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 家族旅行には10万円＿＿＿必要です。', NULL, NULL, NULL, NULL, 'は', 'generated');

-- Tổng: 10 grammar, 3 usages, 36 examples, 36 questions
