-- ============================================================
-- jp-go — Ngữ pháp N4, round 7 (11 mẫu, trang in 44).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 3 - 文法.
-- ============================================================

-- ---------- jp_grammar ----------
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('28504cda-ba31-4165-b584-8ccd8d6d1eef', 'N4', '数量詞＋も〜', 'Những/ Tận ~ (nhấn mạnh số lượng nhiều/lâu hơn dự kiến)', 'も sau số lượng nhấn mạnh mức độ nhiều/lâu hơn mong đợi', '[Số lượng] + も + ~', 'Nhấn mạnh số lượng/thời gian nhiều, lâu hơn mong đợi', NULL, NULL, NULL, '{}', NULL, 44, '数量詞＋も〜', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('cf26310a-21ab-405e-bdf4-fd46616117e6', 'N4', 'Vます／Aい／Aな＋すぎます', 'Quá nhiều...', 'すぎる gắn sau thân động từ/tính từ để diễn tả mức độ vượt quá bình thường', 'V(ます形bỏます)／Aい(bỏい)／Aな(bỏな) + すぎます', 'Diễn tả một hành động/tính chất ở mức độ quá nhiều, quá mức', NULL, NULL, NULL, '{}', NULL, 44, 'Vます／Aい／Aな＋すぎます', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('d4f5253e-be53-4e86-b213-6102484b632a', 'N4', 'Aい（く）／Aな（に）＋V', 'Tính từ bổ nghĩa cho động từ (thể phó từ hóa)', 'い形容詞 đổi い→く, な形容詞 thêm に, trước khi bổ nghĩa cho động từ', 'Aい → Aく + V ／ Aな → Aに + V', 'Chuyển tính từ thành phó từ để bổ nghĩa cho động từ đứng sau', NULL, NULL, NULL, '{}', NULL, 44, 'Aい（く）／Aな（に）＋V', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('455b24fe-80fd-4b94-b3c4-9b0c038a4bb1', 'N4', 'Nにします', 'Biểu thị sự lựa chọn hoặc quyết định', 'にする dùng để chọn/quyết định một thứ trong nhiều lựa chọn', 'N + にします', 'Diễn tả việc chọn hoặc quyết định một thứ gì đó', NULL, NULL, NULL, '{}', NULL, 44, 'Nにします', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('f9fb3b07-760b-44b4-8fe7-5eb7a7b9132e', 'N4', 'Vる／Vた／Vない／Aい／Aな／Nの＋場合', 'Trong trường hợp ~, khi ~', '場合 nêu một tình huống/điều kiện giả định, trang trọng hơn たら/なら', 'V(thể thường)／Aい／Aな(な)／N(の) + 場合、〜', 'Nêu một trường hợp/tình huống giả định và kết quả/cách xử lý tương ứng', NULL, NULL, NULL, '{}', NULL, 44, 'Vる／Vた／Vない／Aい／Aな／Nの＋場合', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('d9ef7436-7bbb-4676-846f-7df299a1c4c1', 'N4', 'V（普通形）／Aい／Aな／Nな＋のに', 'Thế mà, vậy mà (nghịch với điều mong đợi)', 'のに ở đây khác với のに mục đích (Vるのに使う) — đây là のに nghịch, biểu thị bất ngờ/bất mãn', 'V(thể thường)／Aい／Aな(な)／N(な) + のに、〜', 'Diễn tả sự trái ngược, bất ngờ hoặc bất mãn giữa 2 vế câu', NULL, NULL, NULL, '{}', NULL, 44, 'V（普通形）／Aい／Aな／Nな＋のに', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('06566380-163a-42ef-b882-da4a59fd478c', 'N4', 'Vた＋ばかりです', 'Vừa mới làm gì ~', 'ばかり nhấn mạnh việc vừa mới xảy ra, khoảng cách thời gian rất ngắn', 'V(た形) + ばかりです', 'Diễn tả một hành động vừa mới hoàn thành xong', NULL, NULL, NULL, '{}', NULL, 44, 'Vた＋ばかりです', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', 'N4', 'Vます／Aい／Aな＋そうです', 'Suy đoán bằng mắt: sắp xảy ra / trông có vẻ ~', 'そうです dùng mắt để suy đoán, khác với そうです nghe nói (V/A普通形+そうです)', 'V(ます形bỏます)／Aい(bỏい)／Aな(bỏな) + そうです', NULL, NULL, NULL, NULL, '{}', NULL, 44, 'Vます／Aい／Aな＋そうです', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', 'N4', 'Vて来ます', 'Đi làm gì đó rồi quay về / Đã dần trở nên ~', 'て来る sau động từ di chuyển/hành động = đi làm rồi về; sau động từ biến đổi = dần trở nên', 'V(て形) + 来ます', NULL, NULL, NULL, NULL, '{}', NULL, 44, 'Vて来ます', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', 'N4', 'Vます＋やすいです／にくいです', 'Dễ làm việc gì / Khó làm việc gì', 'やすい (dễ) và にくい (khó) là 2 nét nghĩa đối lập của cùng 1 mẫu', 'V(ます形 bỏ ます) + やすいです／にくいです', NULL, NULL, NULL, NULL, '{}', NULL, 44, 'Vます＋やすいです／にくいです', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('72c693cc-992d-4132-9f88-4f11dcd44576', 'N4', 'Vる／Vている／Vた＋ところです', 'Chuẩn bị làm ~ / Đang làm ~ / Vừa làm ~', 'ところ chỉ 1 thời điểm cụ thể trong tiến trình hành động: trước khi làm／đang làm／ngay sau khi làm xong', 'Vる／Vている／Vた + ところです', NULL, NULL, NULL, NULL, '{}', NULL, 44, 'Vる／Vている／Vた＋ところです', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;

-- ---------- jp_grammar_usages ----------
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('8ba8f78c-164a-4e0a-bdf4-fa2a4d20dfe6', 'e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', 1, '(Có vẻ) Sắp ~ đến nơi rồi (dựa trên Vます)', 'V(ます形 bỏ ます) + そうです', NULL, NULL, 44, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('a43e9d48-863c-46b4-991a-67725c91ec54', 'e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', 2, 'Trông có vẻ ~ (suy đoán qua bề ngoài của sự vật, dựa trên Aい/Aな)', 'Aい(bỏい)／Aな(bỏな) + そうです', NULL, NULL, 44, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('913e8350-f752-4d58-9458-74b5c81c99b5', '6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', 1, 'Đi làm việc gì đó rồi quay về', 'V(て形) + 来ます', NULL, NULL, 44, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('df282590-57e0-4d98-a589-cf403a735fe6', '6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', 2, 'Đã (trở nên) ~ rồi (biến đổi dần dần)', 'V(て形) + きます／きた', NULL, NULL, 44, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('db064262-f7e8-4de1-aae0-15726050f5ce', 'dbe369ec-79fb-495f-8da2-2a19d65cd2bc', 1, 'Dễ làm việc gì (Vます＋やすいです)', 'V(ます形 bỏ ます) + やすいです', NULL, NULL, 44, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('47f3293d-98cc-4e98-b965-ec4a6dc03480', 'dbe369ec-79fb-495f-8da2-2a19d65cd2bc', 2, 'Khó làm việc gì (Vます＋にくいです)', 'V(ます形 bỏ ます) + にくいです', NULL, NULL, 44, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('63a3a76c-1a3d-40cf-a4f4-7c74af9ec043', '72c693cc-992d-4132-9f88-4f11dcd44576', 1, 'Vる＋ところです: Chuẩn bị làm ~', 'V(thể từ điển) + ところです', NULL, NULL, 44, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('cedf78e5-ff41-42e7-aa1b-57771e92ca11', '72c693cc-992d-4132-9f88-4f11dcd44576', 2, 'Vている＋ところです: Đang làm ~', 'V(て形)いる + ところです', NULL, NULL, 44, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('82f4f787-7dd7-4e46-b5ea-e188e9c1cdd1', '72c693cc-992d-4132-9f88-4f11dcd44576', 3, 'Vた＋ところです: Vừa làm ~', 'V(た形) + ところです', NULL, NULL, 44, 'pdf');

-- ---------- jp_grammar_examples + jp_grammar_questions ----------
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('28504cda-ba31-4165-b584-8ccd8d6d1eef', NULL, 1, 'daily', '学校まで行くのに2時間もかかります。', 'Mất tận 2 giờ để đến trường.', '学校まで行くのに2時間＿＿＿かかります。', 'も', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('28504cda-ba31-4165-b584-8ccd8d6d1eef', NULL, 2, 'daily', 'この本は1000ページもあります。', 'Cuốn sách này có tận 1000 trang.', 'この本は1000ページ＿＿＿あります。', 'も', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('28504cda-ba31-4165-b584-8ccd8d6d1eef', NULL, 3, 'daily', '彼はビールを10本も飲みました。', 'Anh ấy đã uống tận 10 chai bia.', '彼はビールを10本＿＿＿飲みました。', 'も', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('28504cda-ba31-4165-b584-8ccd8d6d1eef', NULL, 'fill_blank', 'Điền vào chỗ trống: 学校まで行くのに2時間＿＿＿かかります。', NULL, NULL, NULL, NULL, 'も', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('28504cda-ba31-4165-b584-8ccd8d6d1eef', NULL, 'choose_meaning', '「この本は1000ページもあります。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Cuốn sách này có tận 1000 trang.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('28504cda-ba31-4165-b584-8ccd8d6d1eef', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 彼はビールを10本＿＿＿飲みました。', NULL, NULL, NULL, NULL, 'も', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('cf26310a-21ab-405e-bdf4-fd46616117e6', NULL, 1, 'daily', '昨日お酒を飲みすぎました。', 'Hôm qua tôi đã uống quá nhiều rượu.', '昨日お酒を＿＿＿。', '飲みすぎました', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('cf26310a-21ab-405e-bdf4-fd46616117e6', NULL, 2, 'daily', 'このラーメンは辛すぎます。', 'Món mì này quá cay.', 'このラーメンは＿＿＿。', '辛すぎます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('cf26310a-21ab-405e-bdf4-fd46616117e6', NULL, 3, 'daily', '毎日残業しすぎて、疲れました。', 'Vì tăng ca quá nhiều mỗi ngày nên tôi đã mệt.', '毎日＿＿＿、疲れました。', '残業しすぎて', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('cf26310a-21ab-405e-bdf4-fd46616117e6', NULL, 'fill_blank', 'Điền vào chỗ trống: 昨日お酒を＿＿＿。', NULL, NULL, NULL, NULL, '飲みすぎました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('cf26310a-21ab-405e-bdf4-fd46616117e6', NULL, 'choose_meaning', '「このラーメンは辛すぎます。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Món mì này quá cay.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('cf26310a-21ab-405e-bdf4-fd46616117e6', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 毎日＿＿＿、疲れました。', NULL, NULL, NULL, NULL, '残業しすぎて', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('d4f5253e-be53-4e86-b213-6102484b632a', NULL, 1, 'daily', '音が小さいですから、大きくしてください。', 'Bởi vì âm thanh quá nhỏ nên hãy cho to lên.', '音が小さいですから、＿＿＿してください。', '大きく', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('d4f5253e-be53-4e86-b213-6102484b632a', NULL, 2, 'daily', '部屋をきれいにしてください。', 'Hãy dọn phòng cho sạch sẽ.', '部屋を＿＿＿してください。', 'きれいに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('d4f5253e-be53-4e86-b213-6102484b632a', NULL, 3, 'daily', '早く起きて、朝ご飯を食べました。', 'Tôi dậy sớm và ăn sáng.', '＿＿＿起きて、朝ご飯を食べました。', '早く', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('d4f5253e-be53-4e86-b213-6102484b632a', NULL, 'fill_blank', 'Điền vào chỗ trống: 音が小さいですから、＿＿＿してください。', NULL, NULL, NULL, NULL, '大きく', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('d4f5253e-be53-4e86-b213-6102484b632a', NULL, 'choose_meaning', '「部屋をきれいにしてください。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Hãy dọn phòng cho sạch sẽ.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('d4f5253e-be53-4e86-b213-6102484b632a', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: ＿＿＿起きて、朝ご飯を食べました。', NULL, NULL, NULL, NULL, '早く', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('455b24fe-80fd-4b94-b3c4-9b0c038a4bb1', NULL, 1, 'daily', '晩ご飯は和食にしましょう。', 'Bữa tối hãy ăn đồ Nhật.', '晩ご飯は和食＿＿＿しましょう。', 'に', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('455b24fe-80fd-4b94-b3c4-9b0c038a4bb1', NULL, 2, 'daily', '飲み物は紅茶にします。', 'Tôi sẽ chọn trà đen làm đồ uống.', '飲み物は紅茶＿＿＿します。', 'に', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('455b24fe-80fd-4b94-b3c4-9b0c038a4bb1', NULL, 3, 'daily', '旅行の行き先はハワイにしました。', 'Tôi đã quyết định điểm đến du lịch là Hawaii.', '旅行の行き先はハワイ＿＿＿しました。', 'に', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('455b24fe-80fd-4b94-b3c4-9b0c038a4bb1', NULL, 'fill_blank', 'Điền vào chỗ trống: 晩ご飯は和食＿＿＿しましょう。', NULL, NULL, NULL, NULL, 'に', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('455b24fe-80fd-4b94-b3c4-9b0c038a4bb1', NULL, 'choose_meaning', '「飲み物は紅茶にします。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Tôi sẽ chọn trà đen làm đồ uống.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('455b24fe-80fd-4b94-b3c4-9b0c038a4bb1', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 旅行の行き先はハワイ＿＿＿しました。', NULL, NULL, NULL, NULL, 'に', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('f9fb3b07-760b-44b4-8fe7-5eb7a7b9132e', NULL, 1, 'daily', '授業に間に合わない場合は、クラス長に連絡してください。', 'Trong trường hợp không kịp giờ học, hãy liên lạc với lớp trưởng.', '授業に間に合わない＿＿＿は、クラス長に連絡してください。', '場合', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('f9fb3b07-760b-44b4-8fe7-5eb7a7b9132e', NULL, 2, 'daily', '雨の場合は、試合は中止します。', 'Trong trường hợp trời mưa, trận đấu sẽ bị hủy.', '雨の＿＿＿は、試合は中止します。', '場合', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('f9fb3b07-760b-44b4-8fe7-5eb7a7b9132e', NULL, 3, 'daily', '道が分からない場合は、駅員に聞いてください。', 'Trong trường hợp không biết đường, hãy hỏi nhân viên nhà ga.', '道が分からない＿＿＿は、駅員に聞いてください。', '場合', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('f9fb3b07-760b-44b4-8fe7-5eb7a7b9132e', NULL, 'fill_blank', 'Điền vào chỗ trống: 授業に間に合わない＿＿＿は、クラス長に連絡してください。', NULL, NULL, NULL, NULL, '場合', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('f9fb3b07-760b-44b4-8fe7-5eb7a7b9132e', NULL, 'choose_meaning', '「雨の場合は、試合は中止します。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Trong trường hợp trời mưa, trận đấu sẽ bị hủy.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('f9fb3b07-760b-44b4-8fe7-5eb7a7b9132e', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 道が分からない＿＿＿は、駅員に聞いてください。', NULL, NULL, NULL, NULL, '場合', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('d9ef7436-7bbb-4676-846f-7df299a1c4c1', NULL, 1, 'daily', '冬の山は危険なのに、どうして登るんですか。', 'Núi vào mùa đông rất nguy hiểm, vậy mà tại sao bạn lại leo núi?', '冬の山は危険な＿＿＿、どうして登るんですか。', 'のに', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('d9ef7436-7bbb-4676-846f-7df299a1c4c1', NULL, 2, 'daily', '一生懸命勉強したのに、試験に落ちました。', 'Tôi đã học rất chăm chỉ, vậy mà lại rớt kỳ thi.', '一生懸命勉強した＿＿＿、試験に落ちました。', 'のに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('d9ef7436-7bbb-4676-846f-7df299a1c4c1', NULL, 3, 'daily', 'もう5月なのに、まだ寒いです。', 'Đã là tháng 5 rồi, vậy mà vẫn còn lạnh.', 'もう5月な＿＿＿、まだ寒いです。', 'のに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('d9ef7436-7bbb-4676-846f-7df299a1c4c1', NULL, 'fill_blank', 'Điền vào chỗ trống: 冬の山は危険な＿＿＿、どうして登るんですか。', NULL, NULL, NULL, NULL, 'のに', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('d9ef7436-7bbb-4676-846f-7df299a1c4c1', NULL, 'choose_meaning', '「一生懸命勉強したのに、試験に落ちました。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Tôi đã học rất chăm chỉ, vậy mà lại rớt kỳ thi.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('d9ef7436-7bbb-4676-846f-7df299a1c4c1', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: もう5月な＿＿＿、まだ寒いです。', NULL, NULL, NULL, NULL, 'のに', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('06566380-163a-42ef-b882-da4a59fd478c', NULL, 1, 'daily', 'さっき昼ご飯を食べたばかりです。', 'Tôi vừa mới ăn cơm trưa.', 'さっき昼ご飯を＿＿＿。', '食べたばかりです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('06566380-163a-42ef-b882-da4a59fd478c', NULL, 2, 'daily', 'この会社に入ったばかりです。', 'Tôi vừa mới vào công ty này.', 'この会社に＿＿＿。', '入ったばかりです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('06566380-163a-42ef-b882-da4a59fd478c', NULL, 3, 'daily', '彼は日本に来たばかりです。', 'Anh ấy vừa mới đến Nhật.', '彼は日本に＿＿＿。', '来たばかりです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('06566380-163a-42ef-b882-da4a59fd478c', NULL, 'fill_blank', 'Điền vào chỗ trống: さっき昼ご飯を＿＿＿。', NULL, NULL, NULL, NULL, '食べたばかりです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('06566380-163a-42ef-b882-da4a59fd478c', NULL, 'choose_meaning', '「この会社に入ったばかりです。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Tôi vừa mới vào công ty này.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('06566380-163a-42ef-b882-da4a59fd478c', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 彼は日本に＿＿＿。', NULL, NULL, NULL, NULL, '来たばかりです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', '8ba8f78c-164a-4e0a-bdf4-fa2a4d20dfe6', 1, 'daily', '荷物が落ちそうです。', 'Hành lý của tôi sắp rơi.', '荷物が＿＿＿。', '落ちそうです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', '8ba8f78c-164a-4e0a-bdf4-fa2a4d20dfe6', 2, 'daily', '雨が降りそうです。', 'Trời có vẻ sắp mưa.', '雨が＿＿＿。', '降りそうです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', '8ba8f78c-164a-4e0a-bdf4-fa2a4d20dfe6', 3, 'daily', '赤ちゃんが泣きそうです。', 'Em bé có vẻ sắp khóc.', '赤ちゃんが＿＿＿。', '泣きそうです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', '8ba8f78c-164a-4e0a-bdf4-fa2a4d20dfe6', 'fill_blank', 'Điền vào chỗ trống: 荷物が＿＿＿。', NULL, NULL, NULL, NULL, '落ちそうです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', '8ba8f78c-164a-4e0a-bdf4-fa2a4d20dfe6', 'choose_meaning', '「雨が降りそうです。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Trời có vẻ sắp mưa.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', '8ba8f78c-164a-4e0a-bdf4-fa2a4d20dfe6', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 赤ちゃんが＿＿＿。', NULL, NULL, NULL, NULL, '泣きそうです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', 'a43e9d48-863c-46b4-991a-67725c91ec54', 1, 'daily', 'このケーキはおいしそうです。', 'Bánh này trông có vẻ rất ngon.', 'このケーキは＿＿＿。', 'おいしそうです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', 'a43e9d48-863c-46b4-991a-67725c91ec54', 2, 'daily', 'この問題は難しそうです。', 'Câu hỏi này trông có vẻ khó.', 'この問題は＿＿＿。', '難しそうです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', 'a43e9d48-863c-46b4-991a-67725c91ec54', 3, 'daily', '彼は元気そうです。', 'Anh ấy trông có vẻ khỏe mạnh.', '彼は＿＿＿。', '元気そうです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', 'a43e9d48-863c-46b4-991a-67725c91ec54', 'fill_blank', 'Điền vào chỗ trống: このケーキは＿＿＿。', NULL, NULL, NULL, NULL, 'おいしそうです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', 'a43e9d48-863c-46b4-991a-67725c91ec54', 'choose_meaning', '「この問題は難しそうです。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Câu hỏi này trông có vẻ khó.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e74ac172-f2e4-46cf-a2f9-fd24a18cf6a3', 'a43e9d48-863c-46b4-991a-67725c91ec54', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 彼は＿＿＿。', NULL, NULL, NULL, NULL, '元気そうです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', '913e8350-f752-4d58-9458-74b5c81c99b5', 1, 'daily', '電話をかけて来ます。', 'Đi gọi điện thoại rồi quay lại.', '電話をかけて＿＿＿。', '来ます', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', '913e8350-f752-4d58-9458-74b5c81c99b5', 2, 'daily', 'ちょっとコンビニへ行って来ます。', 'Tôi đi cửa hàng tiện lợi một chút rồi về.', 'ちょっとコンビニへ行って＿＿＿。', '来ます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', '913e8350-f752-4d58-9458-74b5c81c99b5', 3, 'daily', '郵便局へ手紙を出して来ます。', 'Tôi đi gửi thư ở bưu điện rồi về.', '郵便局へ手紙を出して＿＿＿。', '来ます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', '913e8350-f752-4d58-9458-74b5c81c99b5', 'fill_blank', 'Điền vào chỗ trống: 電話をかけて＿＿＿。', NULL, NULL, NULL, NULL, '来ます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', '913e8350-f752-4d58-9458-74b5c81c99b5', 'choose_meaning', '「ちょっとコンビニへ行って来ます。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Tôi đi cửa hàng tiện lợi một chút rồi về.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', '913e8350-f752-4d58-9458-74b5c81c99b5', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 郵便局へ手紙を出して＿＿＿。', NULL, NULL, NULL, NULL, '来ます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', 'df282590-57e0-4d98-a589-cf403a735fe6', 1, 'daily', 'ああ、お腹が空いてきた。', 'Aa, đói rồi.', 'ああ、お腹が＿＿＿。', '空いてきた', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', 'df282590-57e0-4d98-a589-cf403a735fe6', 2, 'daily', 'だんだん暖かくなってきました。', 'Trời đã dần dần ấm lên rồi.', 'だんだん暖かく＿＿＿。', 'なってきました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', 'df282590-57e0-4d98-a589-cf403a735fe6', 3, 'daily', '空が暗くなってきました。', 'Bầu trời đã dần tối lại rồi.', '空が暗く＿＿＿。', 'なってきました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', 'df282590-57e0-4d98-a589-cf403a735fe6', 'fill_blank', 'Điền vào chỗ trống: ああ、お腹が＿＿＿。', NULL, NULL, NULL, NULL, '空いてきた', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', 'df282590-57e0-4d98-a589-cf403a735fe6', 'choose_meaning', '「だんだん暖かくなってきました。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Trời đã dần dần ấm lên rồi.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('6dc03016-0c3b-4d72-9fde-8d26eb8de0f5', 'df282590-57e0-4d98-a589-cf403a735fe6', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 空が暗く＿＿＿。', NULL, NULL, NULL, NULL, 'なってきました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', 'db064262-f7e8-4de1-aae0-15726050f5ce', 1, 'daily', 'このコンピューターは使いやすいです。', 'Cái máy tính này dễ sử dụng.', 'このコンピューターは＿＿＿。', '使いやすいです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', 'db064262-f7e8-4de1-aae0-15726050f5ce', 2, 'daily', 'この漢字は覚えやすいです。', 'Chữ Kanji này dễ nhớ.', 'この漢字は＿＿＿。', '覚えやすいです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', 'db064262-f7e8-4de1-aae0-15726050f5ce', 3, 'daily', 'この靴は歩きやすいです。', 'Đôi giày này đi dễ chịu.', 'この靴は＿＿＿。', '歩きやすいです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', 'db064262-f7e8-4de1-aae0-15726050f5ce', 'fill_blank', 'Điền vào chỗ trống: このコンピューターは＿＿＿。', NULL, NULL, NULL, NULL, '使いやすいです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', 'db064262-f7e8-4de1-aae0-15726050f5ce', 'choose_meaning', '「この漢字は覚えやすいです。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Chữ Kanji này dễ nhớ.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', 'db064262-f7e8-4de1-aae0-15726050f5ce', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: この靴は＿＿＿。', NULL, NULL, NULL, NULL, '歩きやすいです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', '47f3293d-98cc-4e98-b965-ec4a6dc03480', 1, 'daily', '足が痛いので、歩きにくいです。', 'Bởi vì chân tôi bị đau nên rất khó đi bộ.', '足が痛いので、＿＿＿。', '歩きにくいです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', '47f3293d-98cc-4e98-b965-ec4a6dc03480', 2, 'daily', 'この本は字が小さくて、読みにくいです。', 'Cuốn sách này chữ nhỏ nên khó đọc.', 'この本は字が小さくて、＿＿＿。', '読みにくいです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', '47f3293d-98cc-4e98-b965-ec4a6dc03480', 3, 'daily', 'この漢字は難しくて、覚えにくいです。', 'Chữ Kanji này khó nên khó nhớ.', 'この漢字は難しくて、＿＿＿。', '覚えにくいです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', '47f3293d-98cc-4e98-b965-ec4a6dc03480', 'fill_blank', 'Điền vào chỗ trống: 足が痛いので、＿＿＿。', NULL, NULL, NULL, NULL, '歩きにくいです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', '47f3293d-98cc-4e98-b965-ec4a6dc03480', 'choose_meaning', '「この本は字が小さくて、読みにくいです。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Cuốn sách này chữ nhỏ nên khó đọc.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('dbe369ec-79fb-495f-8da2-2a19d65cd2bc', '47f3293d-98cc-4e98-b965-ec4a6dc03480', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: この漢字は難しくて、＿＿＿。', NULL, NULL, NULL, NULL, '覚えにくいです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', '63a3a76c-1a3d-40cf-a4f4-7c74af9ec043', 1, 'daily', 'Q: もうレポートのコピーをしましたか。A: いいえ、これからするところです。', 'Q: Bạn đã copy báo cáo chưa? A: Chưa, bây giờ tôi chuẩn bị làm.', 'A: いいえ、これから＿＿＿。', 'するところです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', '63a3a76c-1a3d-40cf-a4f4-7c74af9ec043', 2, 'daily', 'これから晩ご飯を食べるところです。', 'Bây giờ tôi chuẩn bị ăn cơm tối.', 'これから晩ご飯を＿＿＿。', '食べるところです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', '63a3a76c-1a3d-40cf-a4f4-7c74af9ec043', 3, 'daily', '今からシャワーを浴びるところです。', 'Bây giờ tôi chuẩn bị đi tắm.', '今からシャワーを＿＿＿。', '浴びるところです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', '63a3a76c-1a3d-40cf-a4f4-7c74af9ec043', 'fill_blank', 'Điền vào chỗ trống: A: いいえ、これから＿＿＿。', NULL, NULL, NULL, NULL, 'するところです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', '63a3a76c-1a3d-40cf-a4f4-7c74af9ec043', 'choose_meaning', '「これから晩ご飯を食べるところです。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Bây giờ tôi chuẩn bị ăn cơm tối.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', '63a3a76c-1a3d-40cf-a4f4-7c74af9ec043', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 今からシャワーを＿＿＿。', NULL, NULL, NULL, NULL, '浴びるところです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', 'cedf78e5-ff41-42e7-aa1b-57771e92ca11', 1, 'daily', '音楽会は6時に始まります。今、会場を用意しているところです。', 'Buổi hòa nhạc bắt đầu lúc 6 giờ. Bây giờ tôi đang chuẩn bị hội trường.', '今、会場を＿＿＿。', '用意しているところです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', 'cedf78e5-ff41-42e7-aa1b-57771e92ca11', 2, 'daily', '今、資料をまとめているところです。', 'Bây giờ tôi đang tổng hợp tài liệu.', '今、資料を＿＿＿。', 'まとめているところです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', 'cedf78e5-ff41-42e7-aa1b-57771e92ca11', 3, 'daily', '今、会議で説明しているところです。', 'Bây giờ tôi đang giải thích trong cuộc họp.', '今、会議で＿＿＿。', '説明しているところです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', 'cedf78e5-ff41-42e7-aa1b-57771e92ca11', 'fill_blank', 'Điền vào chỗ trống: 今、会場を＿＿＿。', NULL, NULL, NULL, NULL, '用意しているところです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', 'cedf78e5-ff41-42e7-aa1b-57771e92ca11', 'choose_meaning', '「今、資料をまとめているところです。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Bây giờ tôi đang tổng hợp tài liệu.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', 'cedf78e5-ff41-42e7-aa1b-57771e92ca11', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 今、会議で＿＿＿。', NULL, NULL, NULL, NULL, '説明しているところです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', '82f4f787-7dd7-4e46-b5ea-e188e9c1cdd1', 1, 'daily', 'たった今、バスが出たところです。', 'Xe buýt vừa rời đi.', 'たった今、バスが＿＿＿。', '出たところです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', '82f4f787-7dd7-4e46-b5ea-e188e9c1cdd1', 2, 'daily', 'たった今、会議が終わったところです。', 'Cuộc họp vừa mới kết thúc.', 'たった今、会議が＿＿＿。', '終わったところです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', '82f4f787-7dd7-4e46-b5ea-e188e9c1cdd1', 3, 'daily', 'さっき駅に着いたところです。', 'Tôi vừa mới đến ga.', 'さっき駅に＿＿＿。', '着いたところです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', '82f4f787-7dd7-4e46-b5ea-e188e9c1cdd1', 'fill_blank', 'Điền vào chỗ trống: たった今、バスが＿＿＿。', NULL, NULL, NULL, NULL, '出たところです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', '82f4f787-7dd7-4e46-b5ea-e188e9c1cdd1', 'choose_meaning', '「たった今、会議が終わったところです。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Cuộc họp vừa mới kết thúc.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('72c693cc-992d-4132-9f88-4f11dcd44576', '82f4f787-7dd7-4e46-b5ea-e188e9c1cdd1', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: さっき駅に＿＿＿。', NULL, NULL, NULL, NULL, '着いたところです', 'generated');

-- Tổng: 11 grammar, 9 usages, 48 examples, 48 questions
