-- ============================================================
-- jp-go — Ngữ pháp N4, round 8 (9 mẫu, trang in 45).
-- Nguồn: PDF "Tổng hợp kiến thức N4" (Dũng Mori), PART 3 - 文法.
-- ============================================================

-- ---------- jp_grammar ----------
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('6ffab807-1edd-4bd6-bc62-b08e5e862373', 'N4', 'V（普通形）／Aい／Aな／Nの＋はずです', 'Chắc chắn là ~ (suy luận có căn cứ)', 'はず dùng khi người nói có căn cứ hợp lý để tin rằng điều gì chắc chắn đúng', 'V(thể thường)／Aい／Aな(な)／N(の) + はずです', 'Diễn tả sự suy luận chắc chắn dựa trên căn cứ, lý lẽ hợp lý', NULL, NULL, NULL, '{}', NULL, 45, 'V（普通形）／Aい／Aな／Nの＋はずです', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('754f3c2e-1837-4931-a447-9f553b84ea88', 'N4', 'V（普通形）／Aい／Aな（だ）／N（だ）＋そうです（伝聞）', 'Nghe nói ~ (truyền đạt lại thông tin nghe/đọc được)', 'そうです truyền văn gắn sau thể thường nguyên vẹn (khác そうです suy đoán bằng mắt ở round 7, gắn sau gốc Vます/Aい/Aな)', 'V(thể thường)／Aい／Aな(だ)／N(だ) + そうです', 'Truyền đạt lại thông tin đã nghe/đọc được từ người khác hoặc nguồn tin', NULL, NULL, NULL, '{}', NULL, 45, 'V（普通形）／Aい／Aな（だ）／N（だ）＋そうです（伝聞）', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('e3673d1b-72e3-4112-a5de-f601fbb23ecc', 'N4', 'V（普通形）／Aな（だ）／N（だ）＋ようです', 'Hình như, dường như ~ (phán đoán dựa trên căn cứ/giác quan quan sát được)', 'ようです là văn viết/lịch sự hơn みたいです, dùng khi có căn cứ quan sát thực tế', 'V(thể thường)／Aい／Aな(な)／N(の) + ようです', 'Phán đoán một sự việc dựa trên căn cứ/giác quan quan sát được', NULL, NULL, NULL, '{}', NULL, 45, 'V（普通形）／Aな（だ）／N（だ）＋ようです', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('776ef381-7b4c-47c0-9dad-d23d68287d7c', 'N4', 'V（普通形）／Aい／Aな（だ）／N＋みたいです', 'Hình như, dường như ~ (khẩu ngữ của ようです)', 'みたいです là dạng khẩu ngữ, thân mật hơn của ようです, cùng ý nghĩa phán đoán', 'V(thể thường)／Aい／Aな／N + みたいです', 'Phán đoán một sự việc dựa trên căn cứ quan sát được, dùng trong văn nói thân mật', NULL, NULL, NULL, '{}', NULL, 45, 'V（普通形）／Aい／Aな（だ）／N＋みたいです', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('0b40238a-6f64-4137-a556-794ef1585f47', 'N4', '音／におい／味＋がします', 'Có tiếng động, mùi, vị...', 'がする gắn sau danh từ chỉ cảm giác giác quan (âm thanh, mùi, vị) mà không cần chủ động tạo ra', '音／におい／味 + が + します', 'Diễn tả việc cảm nhận được âm thanh, mùi, vị một cách tự nhiên (không chủ ý)', NULL, NULL, NULL, '{}', NULL, 45, '音／におい／味＋がします', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('34789259-540e-4bd9-92a3-41b6540acd51', 'N4', 'Vさせていただけませんか。', 'Xin cho tôi được ~ (xin phép rất lịch sự)', 'させていただけませんか là dạng xin phép khiêm nhường, lịch sự nhất trong các cách xin phép', 'V(thể sai khiến て形) + いただけませんか', 'Xin phép ai đó cho mình làm gì một cách rất lịch sự, khiêm nhường', NULL, NULL, NULL, '{}', NULL, 45, 'Vさせていただけませんか。', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('da963a11-d0dd-412b-8a6c-277eeb3802cf', 'N4', 'Vさせていただきます。', 'Tôi xin phép ~ (thông báo lịch sự việc mình sẽ làm)', 'させていただきます dùng để thông báo lịch sự một hành động mình sắp làm, có xin phép trước', 'V(thể sai khiến て形) + いただきます', 'Thông báo một cách lịch sự, khiêm nhường về việc mình sẽ làm (đã được cho phép)', NULL, NULL, NULL, '{}', NULL, 45, 'Vさせていただきます。', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', 'N4', 'Vさせる（使役形）', 'Thể sai khiến: bắt/cho phép ai đó làm gì', 'Trợ từ đánh dấu người bị sai khiến khác nhau tùy động từ tha động (に) hay tự động (を)', 'V(thể sai khiến): 五段→ 語幹+せる／一段→ 語幹+させる／する→させる／来る→来させる', NULL, NULL, NULL, NULL, '{}', NULL, 45, 'Vさせる（使役形）', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;
insert into jp_grammar (id, level, grammar_pattern, meaning_vi, memory_hint_vi, connection, usage, register, notes, common_mistake, similar_patterns, difference_note, source_page, source_text, source_type, review_status) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', 'N4', '尊敬語（Dạng đặc biệt của động từ）', 'Kính ngữ đặc biệt: します／います／行きます・来ます đổi thành dạng tôn kính riêng', '3 cặp động từ này KHÔNG chia theo quy tắc お＋Vます形＋になります thông thường mà có dạng đặc biệt riêng', 'します → なさいます／います → いらっしゃいます／行きます・来ます → いらっしゃいます', NULL, NULL, NULL, NULL, '{}', NULL, 45, '尊敬語（Dạng đặc biệt của động từ）', 'pdf', 'ok')
on conflict (level, grammar_pattern) do nothing;

-- ---------- jp_grammar_usages ----------
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('5abcfd0d-4581-4608-bec6-66a63aa8e3e0', 'fbe1065e-000b-404e-bbc3-307fe2760bfa', 1, 'Người bị sai khiến + に + (tân ngữ)を + V(thể sai khiến) — dùng với động từ tha động (có tân ngữ)', 'N1は N2に N3を V(thể sai khiến)', NULL, NULL, 45, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('e0dc6c9a-7a26-4d99-b679-2b454285ae25', 'fbe1065e-000b-404e-bbc3-307fe2760bfa', 2, 'Người bị sai khiến + を + V(thể sai khiến) — dùng với động từ tự động (không tân ngữ)', 'N1は N2を V(thể sai khiến)', NULL, NULL, 45, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('18dc3aa3-10dc-40a2-baa2-6fbe7a733def', 'a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', 1, 'します → なさいます', 'します → なさいます', NULL, NULL, 45, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('58dff9b2-f2e7-4cc5-a266-61fdc3e419ae', 'a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', 2, 'います → いらっしゃいます', 'います → いらっしゃいます', NULL, NULL, 45, 'pdf');
insert into jp_grammar_usages (id, grammar_id, usage_no, meaning, connection, usage, notes, source_page, source_type) values ('1edd12d4-2e66-41c3-a477-d522218e7a6c', 'a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', 3, '行きます／来ます → いらっしゃいます', '行きます／来ます → いらっしゃいます', NULL, NULL, 45, 'pdf');

-- ---------- jp_grammar_examples + jp_grammar_questions ----------
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('6ffab807-1edd-4bd6-bc62-b08e5e862373', NULL, 1, 'daily', '雪が降ってきましたから、寒いはずです。', 'Bởi vì tuyết vừa rơi nên trời chắc chắn sẽ lạnh.', '雪が降ってきましたから、寒い＿＿＿。', 'はずです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('6ffab807-1edd-4bd6-bc62-b08e5e862373', NULL, 2, 'daily', '彼は日本に10年住んでいたから、日本語が上手なはずです。', 'Vì anh ấy đã sống ở Nhật 10 năm nên chắc chắn giỏi tiếng Nhật.', '彼は日本に10年住んでいたから、日本語が上手な＿＿＿。', 'はずです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('6ffab807-1edd-4bd6-bc62-b08e5e862373', NULL, 3, 'daily', 'もう7時ですから、店は閉まっているはずです。', 'Vì đã 7 giờ rồi nên cửa hàng chắc chắn đã đóng cửa.', 'もう7時ですから、店は閉まっている＿＿＿。', 'はずです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('6ffab807-1edd-4bd6-bc62-b08e5e862373', NULL, 'fill_blank', 'Điền vào chỗ trống: 雪が降ってきましたから、寒い＿＿＿。', NULL, NULL, NULL, NULL, 'はずです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('6ffab807-1edd-4bd6-bc62-b08e5e862373', NULL, 'choose_meaning', '「彼は日本に10年住んでいたから、日本語が上手なはずです。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Vì anh ấy đã sống ở Nhật 10 năm nên chắc chắn giỏi tiếng Nhật.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('6ffab807-1edd-4bd6-bc62-b08e5e862373', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: もう7時ですから、店は閉まっている＿＿＿。', NULL, NULL, NULL, NULL, 'はずです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('754f3c2e-1837-4931-a447-9f553b84ea88', NULL, 1, 'daily', '天気予報によると、明日雨が降るそうです。', 'Theo như dự báo thời tiết, nghe nói ngày mai sẽ mưa.', '天気予報によると、明日雨が＿＿＿。', '降るそうです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('754f3c2e-1837-4931-a447-9f553b84ea88', NULL, 2, 'daily', 'ニュースによると、あの俳優は来月結婚するそうです。', 'Theo tin tức, nghe nói diễn viên đó sẽ kết hôn vào tháng sau.', 'ニュースによると、あの俳優は来月＿＿＿。', '結婚するそうです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('754f3c2e-1837-4931-a447-9f553b84ea88', NULL, 3, 'daily', '田中さんの話では、この店の料理はとてもおいしいそうです。', 'Theo lời anh Tanaka, nghe nói món ăn ở quán này rất ngon.', '田中さんの話では、この店の料理はとても＿＿＿。', 'おいしいそうです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('754f3c2e-1837-4931-a447-9f553b84ea88', NULL, 'fill_blank', 'Điền vào chỗ trống: 天気予報によると、明日雨が＿＿＿。', NULL, NULL, NULL, NULL, '降るそうです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('754f3c2e-1837-4931-a447-9f553b84ea88', NULL, 'choose_meaning', '「ニュースによると、あの俳優は来月結婚するそうです。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Theo tin tức, nghe nói diễn viên đó sẽ kết hôn vào tháng sau.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('754f3c2e-1837-4931-a447-9f553b84ea88', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 田中さんの話では、この店の料理はとても＿＿＿。', NULL, NULL, NULL, NULL, 'おいしいそうです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e3673d1b-72e3-4112-a5de-f601fbb23ecc', NULL, 1, 'daily', '彼はN1を合格したようです。', 'Hình như anh ấy đã thi đỗ N1.', '彼はN1を合格した＿＿＿。', 'ようです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e3673d1b-72e3-4112-a5de-f601fbb23ecc', NULL, 2, 'daily', '隣の部屋に誰かいるようです。', 'Hình như có ai đó ở phòng bên cạnh.', '隣の部屋に誰かいる＿＿＿。', 'ようです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('e3673d1b-72e3-4112-a5de-f601fbb23ecc', NULL, 3, 'daily', 'この道は工事中のようです。', 'Con đường này hình như đang thi công.', 'この道は工事中の＿＿＿。', 'ようです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e3673d1b-72e3-4112-a5de-f601fbb23ecc', NULL, 'fill_blank', 'Điền vào chỗ trống: 彼はN1を合格した＿＿＿。', NULL, NULL, NULL, NULL, 'ようです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e3673d1b-72e3-4112-a5de-f601fbb23ecc', NULL, 'choose_meaning', '「隣の部屋に誰かいるようです。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Hình như có ai đó ở phòng bên cạnh.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('e3673d1b-72e3-4112-a5de-f601fbb23ecc', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: この道は工事中の＿＿＿。', NULL, NULL, NULL, NULL, 'ようです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('776ef381-7b4c-47c0-9dad-d23d68287d7c', NULL, 1, 'daily', '先生は来ないみたいですね。', 'Dường như giáo viên sẽ không đến.', '先生は来ない＿＿＿ね。', 'みたいです', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('776ef381-7b4c-47c0-9dad-d23d68287d7c', NULL, 2, 'daily', 'あの二人は付き合っているみたいです。', 'Hình như hai người đó đang hẹn hò.', 'あの二人は付き合っている＿＿＿。', 'みたいです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('776ef381-7b4c-47c0-9dad-d23d68287d7c', NULL, 3, 'daily', 'この漫画、面白いみたいです。', 'Bộ truyện tranh này hình như hay.', 'この漫画、面白い＿＿＿。', 'みたいです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('776ef381-7b4c-47c0-9dad-d23d68287d7c', NULL, 'fill_blank', 'Điền vào chỗ trống: 先生は来ない＿＿＿ね。', NULL, NULL, NULL, NULL, 'みたいです', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('776ef381-7b4c-47c0-9dad-d23d68287d7c', NULL, 'choose_meaning', '「あの二人は付き合っているみたいです。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Hình như hai người đó đang hẹn hò.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('776ef381-7b4c-47c0-9dad-d23d68287d7c', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: この漫画、面白い＿＿＿。', NULL, NULL, NULL, NULL, 'みたいです', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0b40238a-6f64-4137-a556-794ef1585f47', NULL, 1, 'daily', '子供の声がします。', 'Có tiếng động của đứa trẻ.', '子供の声＿＿＿。', 'がします', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0b40238a-6f64-4137-a556-794ef1585f47', NULL, 2, 'daily', '台所からいいにおいがします。', 'Có mùi thơm từ nhà bếp.', '台所からいいにおい＿＿＿。', 'がします', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('0b40238a-6f64-4137-a556-794ef1585f47', NULL, 3, 'daily', 'このスープは変な味がします。', 'Món súp này có vị lạ.', 'このスープは変な味＿＿＿。', 'がします', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0b40238a-6f64-4137-a556-794ef1585f47', NULL, 'fill_blank', 'Điền vào chỗ trống: 子供の声＿＿＿。', NULL, NULL, NULL, NULL, 'がします', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0b40238a-6f64-4137-a556-794ef1585f47', NULL, 'choose_meaning', '「台所からいいにおいがします。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Có mùi thơm từ nhà bếp.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('0b40238a-6f64-4137-a556-794ef1585f47', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: このスープは変な味＿＿＿。', NULL, NULL, NULL, NULL, 'がします', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('34789259-540e-4bd9-92a3-41b6540acd51', NULL, 1, 'daily', 'あした用事がありますから、一日休ませていただけませんか。', 'Ngày mai tôi có chút việc, xin phép anh cho tôi được nghỉ một ngày.', 'あした用事がありますから、一日＿＿＿。', '休ませていただけませんか', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('34789259-540e-4bd9-92a3-41b6540acd51', NULL, 2, 'daily', 'すみませんが、今日早く帰らせていただけませんか。', 'Xin lỗi, hôm nay xin phép cho tôi về sớm được không ạ?', 'すみませんが、今日早く＿＿＿。', '帰らせていただけませんか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('34789259-540e-4bd9-92a3-41b6540acd51', NULL, 3, 'daily', '会議の前に、少し説明させていただけませんか。', 'Trước cuộc họp, xin phép cho tôi giải thích một chút được không ạ?', '会議の前に、少し＿＿＿。', '説明させていただけませんか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('34789259-540e-4bd9-92a3-41b6540acd51', NULL, 'fill_blank', 'Điền vào chỗ trống: あした用事がありますから、一日＿＿＿。', NULL, NULL, NULL, NULL, '休ませていただけませんか', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('34789259-540e-4bd9-92a3-41b6540acd51', NULL, 'choose_meaning', '「すみませんが、今日早く帰らせていただけませんか。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Xin lỗi, hôm nay xin phép cho tôi về sớm được không ạ?', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('34789259-540e-4bd9-92a3-41b6540acd51', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 会議の前に、少し＿＿＿。', NULL, NULL, NULL, NULL, '説明させていただけませんか', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('da963a11-d0dd-412b-8a6c-277eeb3802cf', NULL, 1, 'daily', '先に帰らせていただきます。', 'Tôi xin phép về trước ạ.', '先に＿＿＿。', '帰らせていただきます', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('da963a11-d0dd-412b-8a6c-277eeb3802cf', NULL, 2, 'daily', 'これで発表を終わらせていただきます。', 'Tôi xin phép kết thúc phần thuyết trình ở đây ạ.', 'これで発表を＿＿＿。', '終わらせていただきます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('da963a11-d0dd-412b-8a6c-277eeb3802cf', NULL, 3, 'daily', '本日は休ませていただきます。', 'Hôm nay tôi xin phép nghỉ ạ.', '本日は＿＿＿。', '休ませていただきます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('da963a11-d0dd-412b-8a6c-277eeb3802cf', NULL, 'fill_blank', 'Điền vào chỗ trống: 先に＿＿＿。', NULL, NULL, NULL, NULL, '帰らせていただきます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('da963a11-d0dd-412b-8a6c-277eeb3802cf', NULL, 'choose_meaning', '「これで発表を終わらせていただきます。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Tôi xin phép kết thúc phần thuyết trình ở đây ạ.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('da963a11-d0dd-412b-8a6c-277eeb3802cf', NULL, 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 本日は＿＿＿。', NULL, NULL, NULL, NULL, '休ませていただきます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', '5abcfd0d-4581-4608-bec6-66a63aa8e3e0', 1, 'daily', '私は学生にベトナム語を使わせない。', 'Tôi không cho học sinh của mình sử dụng tiếng Việt.', '私は学生にベトナム語を＿＿＿。', '使わせない', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', '5abcfd0d-4581-4608-bec6-66a63aa8e3e0', 2, 'daily', '先生は学生に宿題をさせました。', 'Giáo viên đã bắt học sinh làm bài tập.', '先生は学生に宿題を＿＿＿。', 'させました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', '5abcfd0d-4581-4608-bec6-66a63aa8e3e0', 3, 'daily', '母は子供に野菜を食べさせました。', 'Mẹ đã cho con ăn rau.', '母は子供に野菜を＿＿＿。', '食べさせました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', '5abcfd0d-4581-4608-bec6-66a63aa8e3e0', 'fill_blank', 'Điền vào chỗ trống: 私は学生にベトナム語を＿＿＿。', NULL, NULL, NULL, NULL, '使わせない', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', '5abcfd0d-4581-4608-bec6-66a63aa8e3e0', 'choose_meaning', '「先生は学生に宿題をさせました。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Giáo viên đã bắt học sinh làm bài tập.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', '5abcfd0d-4581-4608-bec6-66a63aa8e3e0', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 母は子供に野菜を＿＿＿。', NULL, NULL, NULL, NULL, '食べさせました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', 'e0dc6c9a-7a26-4d99-b679-2b454285ae25', 1, 'daily', '4時半に学生さんを帰らせる。', 'Tôi cho học sinh ra về lúc bốn giờ rưỡi.', '4時半に学生さんを＿＿＿。', '帰らせる', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', 'e0dc6c9a-7a26-4d99-b679-2b454285ae25', 2, 'daily', '先生は学生を教室に立たせました。', 'Giáo viên bắt học sinh đứng ở lớp học.', '先生は学生を教室に＿＿＿。', '立たせました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', 'e0dc6c9a-7a26-4d99-b679-2b454285ae25', 3, 'daily', '部長は新人を先に休ませました。', 'Trưởng phòng đã cho nhân viên mới nghỉ trước.', '部長は新人を先に＿＿＿。', '休ませました', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', 'e0dc6c9a-7a26-4d99-b679-2b454285ae25', 'fill_blank', 'Điền vào chỗ trống: 4時半に学生さんを＿＿＿。', NULL, NULL, NULL, NULL, '帰らせる', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', 'e0dc6c9a-7a26-4d99-b679-2b454285ae25', 'choose_meaning', '「先生は学生を教室に立たせました。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Giáo viên bắt học sinh đứng ở lớp học.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('fbe1065e-000b-404e-bbc3-307fe2760bfa', 'e0dc6c9a-7a26-4d99-b679-2b454285ae25', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 部長は新人を先に＿＿＿。', NULL, NULL, NULL, NULL, '休ませました', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '18dc3aa3-10dc-40a2-baa2-6fbe7a733def', 1, 'daily', 'A: 今、何のお仕事をなさっていますか。 B: 今、日本語を教えています。', 'A: Bây giờ anh đang làm gì vậy? B: Bây giờ tôi đang dạy tiếng Nhật.', 'A: 今、何のお仕事を＿＿＿か。', 'なさっています', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '18dc3aa3-10dc-40a2-baa2-6fbe7a733def', 2, 'daily', 'A: 週末は何をなさいますか。 B: 家族とゆっくり過ごします。', 'A: Cuối tuần anh làm gì vậy? B: Tôi ở nhà thư giãn cùng gia đình.', 'A: 週末は何を＿＿＿か。', 'なさいます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '18dc3aa3-10dc-40a2-baa2-6fbe7a733def', 3, 'daily', '社長はどんなスポーツをなさいますか。', 'Giám đốc chơi môn thể thao nào ạ?', '社長はどんなスポーツを＿＿＿か。', 'なさいます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '18dc3aa3-10dc-40a2-baa2-6fbe7a733def', 'fill_blank', 'Điền vào chỗ trống: A: 今、何のお仕事を＿＿＿か。', NULL, NULL, NULL, NULL, 'なさっています', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '18dc3aa3-10dc-40a2-baa2-6fbe7a733def', 'choose_meaning', '「A: 週末は何をなさいますか。 B: 家族とゆっくり過ごします。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'A: Cuối tuần anh làm gì vậy? B: Tôi ở nhà thư giãn cùng gia đình.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '18dc3aa3-10dc-40a2-baa2-6fbe7a733def', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 社長はどんなスポーツを＿＿＿か。', NULL, NULL, NULL, NULL, 'なさいます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '58dff9b2-f2e7-4cc5-a266-61fdc3e419ae', 1, 'daily', 'A: 今、どこにいらっしゃいますか。 B: はい、今、事務所にいます。', 'A: Bây giờ anh đang ở đâu vậy? B: Bây giờ tôi đang ở văn phòng.', 'A: 今、どこに＿＿＿か。', 'いらっしゃいます', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '58dff9b2-f2e7-4cc5-a266-61fdc3e419ae', 2, 'daily', '部長は今、会議室にいらっしゃいます。', 'Trưởng phòng bây giờ đang ở phòng họp.', '部長は今、会議室に＿＿＿。', 'いらっしゃいます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '58dff9b2-f2e7-4cc5-a266-61fdc3e419ae', 3, 'daily', '先生はまだ教室にいらっしゃいますか。', 'Thầy giáo vẫn còn ở lớp học ạ?', '先生はまだ教室に＿＿＿か。', 'いらっしゃいます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '58dff9b2-f2e7-4cc5-a266-61fdc3e419ae', 'fill_blank', 'Điền vào chỗ trống: A: 今、どこに＿＿＿か。', NULL, NULL, NULL, NULL, 'いらっしゃいます', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '58dff9b2-f2e7-4cc5-a266-61fdc3e419ae', 'choose_meaning', '「部長は今、会議室にいらっしゃいます。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Trưởng phòng bây giờ đang ở phòng họp.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '58dff9b2-f2e7-4cc5-a266-61fdc3e419ae', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: 先生はまだ教室に＿＿＿か。', NULL, NULL, NULL, NULL, 'いらっしゃいます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '1edd12d4-2e66-41c3-a477-d522218e7a6c', 1, 'daily', 'A: 島川先生は神戸にいらっしゃったことがありますか。 B: まだないんです。', 'A: Thầy Shimakawa đã bao giờ đến Kobe chưa ạ? B: Tôi chưa đến đó bao giờ.', 'A: 島川先生は神戸に＿＿＿ことがありますか。', 'いらっしゃった', 'pdf');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '1edd12d4-2e66-41c3-a477-d522218e7a6c', 2, 'daily', '社長は明日アメリカからいらっしゃいます。', 'Ngày mai giám đốc sẽ đến từ Mỹ.', '社長は明日アメリカから＿＿＿。', 'いらっしゃいます', 'generated');
insert into jp_grammar_examples (grammar_id, usage_id, example_no, example_type, example_jp, example_vi, cloze_jp, answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '1edd12d4-2e66-41c3-a477-d522218e7a6c', 3, 'daily', 'お客様は3時にいらっしゃる予定です。', 'Dự kiến khách sẽ đến lúc 3 giờ.', 'お客様は3時に＿＿＿予定です。', 'いらっしゃる', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '1edd12d4-2e66-41c3-a477-d522218e7a6c', 'fill_blank', 'Điền vào chỗ trống: A: 島川先生は神戸に＿＿＿ことがありますか。', NULL, NULL, NULL, NULL, 'いらっしゃった', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '1edd12d4-2e66-41c3-a477-d522218e7a6c', 'choose_meaning', '「社長は明日アメリカからいらっしゃいます。」nghĩa là gì?', NULL, NULL, NULL, NULL, 'Ngày mai giám đốc sẽ đến từ Mỹ.', 'generated');
insert into jp_grammar_questions (grammar_id, usage_id, question_type, question_text, choice_1, choice_2, choice_3, choice_4, correct_answer, source_type) values ('a7d55ba1-df2a-41b4-801c-0c8b93dff3e9', '1edd12d4-2e66-41c3-a477-d522218e7a6c', 'choose_pattern', 'Chọn mẫu ngữ pháp đúng cho câu: お客様は3時に＿＿＿予定です。', NULL, NULL, NULL, NULL, 'いらっしゃる', 'generated');

-- Tổng: 9 grammar, 5 usages, 36 examples, 36 questions
