-- Hoàn thiện bộ 3 ngữ cảnh cho N5 bài 7 (52 mục).

with classifications(word_jp,word_class,dictionary_form) as (values
 ('お茶','名詞','お茶'),('お酒','名詞','お酒'),('コーヒー','名詞','コーヒー'),('ご飯','名詞','ご飯'),
 ('ジュース','名詞','ジュース'),('たばこ','名詞','たばこ'),('チョコレート','名詞','チョコレート'),('パン','名詞','パン'),
 ('ビール','名詞','ビール'),('メール','名詞','メール'),('レポート','名詞','レポート'),('ワイン','名詞','ワイン'),
 ('卵','名詞','卵'),('手紙','名詞','手紙'),('果物','名詞','果物'),('水','名詞','水'),('牛肉','名詞','牛肉'),
 ('肉','名詞','肉'),('薬','名詞','薬'),('野菜','名詞','野菜'),('魚','名詞','魚'),('「写真を」撮る','動詞','撮る'),
 ('いつも','副詞','いつも'),('お正月','名詞','お正月'),('お花見','動名詞','お花見'),('カフェ','名詞','カフェ'),
 ('コメント','名詞','コメント'),('サッカー','名詞','サッカー'),('する','動詞','する'),('ちょっと','副詞','ちょっと'),
 ('テニス','名詞','テニス'),('みんなで','副詞','みんなで'),('レストラン','名詞','レストラン'),('一緒に','副詞','一緒に'),
 ('会う','動詞','会う'),('何','名詞','何'),('写真','名詞','写真'),('吸う','動詞','吸う'),('宿題','名詞','宿題'),
 ('店','名詞','店'),('庭','名詞','庭'),('映画','名詞','映画'),('時々','副詞','時々'),('書く','動詞','書く'),
 ('聞く','動詞','聞く'),('見る','動詞','見る'),('読む','動詞','読む'),('買う','動詞','買う'),('音楽','名詞','音楽'),
 ('食べる','動詞','食べる'),('食事する','動詞','食事する'),('飲む','動詞','飲む')
)
update public.jp_vocab v set word_class=c.word_class,dictionary_form=c.dictionary_form
from classifications c where v.level='N5' and v.lesson_no=7 and v.word_jp=c.word_jp;

-- Tách các câu đời thường bị dùng chung cho danh từ và động từ liên quan.
with fixes(word_jp,example_jp,example_vi,cloze_jp,answer,focus_note) as (values
 ('「写真を」撮る','旅行で家族の写真を撮りました。','Trong chuyến đi tôi đã chụp ảnh gia đình.','旅行で家族の写真を_____。','撮りました','写真を撮る là chụp ảnh.'),
 ('吸う','父は外でたばこを吸います。','Bố tôi hút thuốc ở bên ngoài.','父は外でたばこを_____。','吸います','たばこを吸う; nơi thực hiện đi với で.'),
 ('宿題','今日の宿題は少し難しいです。','Bài tập hôm nay hơi khó.','今日の_____は少し難しいです。','宿題','今日の + danh từ.'),
 ('書く','毎晩、短い日記を書いています。','Mỗi tối tôi viết một đoạn nhật ký ngắn.','毎晩、短い日記を_____います。','書いて','書く → 書いています.'),
 ('見る','週末に家族と映画を見ました。','Cuối tuần tôi đã xem phim cùng gia đình.','週末に家族と映画を_____。','見ました','見る → 見ました.'),
 ('買う','帰りにスーパーで牛乳を買います。','Trên đường về tôi mua sữa ở siêu thị.','帰りにスーパーで牛乳を_____。','買います','Nを買う; nơi mua đi với で.'),
 ('音楽','静かな音楽が好きです。','Tôi thích nhạc nhẹ.','静かな_____が好きです。','音楽','Đối tượng yêu thích đi với が.'),
 ('食べる','朝は果物を食べています。','Buổi sáng tôi ăn trái cây.','朝は果物を_____います。','食べて','食べる → 食べています.'),
 ('食事する','今夜、家族と食事します。','Tối nay tôi dùng bữa cùng gia đình.','今夜、家族と_____。','食事します','Người cùng ăn đi với と.'),
 ('飲む','暑い日は水をたくさん飲みます。','Ngày nóng tôi uống nhiều nước.','暑い日は水をたくさん_____。','飲みます','Nを飲む.')
)
update public.jp_vocab_examples e set example_jp=f.example_jp,example_vi=f.example_vi,
 cloze_jp=f.cloze_jp,answer=f.answer,difficulty=1,focus_note=f.focus_note
from fixes f join public.jp_vocab v on v.level='N5' and v.lesson_no=7 and v.word_jp=f.word_jp
where e.vocab_id=v.id and e.example_no=2;

with curated(word_jp,example_no,example_type,example_jp,example_vi,cloze_jp,answer,difficulty,focus_note) as (values
 ('お茶',1,'exam','食事の後で温かいお茶を飲みました。','Sau bữa ăn tôi đã uống trà nóng.','食事の後で温かい_____を飲みました。','お茶',1,'Đồ uống đi với を飲む.'),
 ('お茶',3,'business','お客様にお茶をお出ししてください。','Vui lòng mời trà khách.','お客様に_____をお出ししてください。','お茶',2,'お茶をお出しする là mời trà lịch sự.'),
 ('お酒',1,'exam','父はお酒をあまり飲みません。','Bố tôi không uống nhiều rượu.','父は_____をあまり飲みません。','お酒',1,'あまり đi với phủ định.'),
 ('お酒',3,'business','勤務中はお酒を飲んではいけません。','Không được uống rượu trong giờ làm việc.','勤務中は_____を飲んではいけません。','お酒',2,'Vてはいけません chỉ cấm đoán.'),
 ('コーヒー',1,'exam','眠かったので、濃いコーヒーを飲みました。','Vì buồn ngủ nên tôi uống cà phê đậm.','眠かったので、濃い_____を飲みました。','コーヒー',1,'濃いコーヒー là cà phê đậm.'),
 ('コーヒー',3,'business','会議室にコーヒーを十杯用意しました。','Tôi đã chuẩn bị mười cốc cà phê trong phòng họp.','会議室に_____を十杯用意しました。','コーヒー',2,'Đếm cốc dùng 杯.'),
 ('ご飯',1,'exam','母が作ったご飯はとてもおいしかったです。','Cơm mẹ nấu rất ngon.','母が作った_____はとてもおいしかったです。','ご飯',1,'Mệnh đề bổ nghĩa cho ご飯.'),
 ('ご飯',3,'business','昼の会議前に早めにご飯を食べました。','Tôi đã ăn sớm trước cuộc họp trưa.','昼の会議前に早めに_____を食べました。','ご飯',2,'ご飯を食べる.'),
 ('ジュース',1,'exam','冷蔵庫にりんごジュースが一本あります。','Trong tủ lạnh có một chai nước táo.','冷蔵庫にりんご_____が一本あります。','ジュース',1,'Loại quả + ジュース.'),
 ('ジュース',3,'business','休憩室のジュースは自由に飲めます。','Nước trái cây trong phòng nghỉ có thể uống tự do.','休憩室の_____は自由に飲めます。','ジュース',2,'Nは自由にV được dùng trong hướng dẫn.'),
 ('たばこ',1,'exam','この建物の中ではたばこを吸えません。','Trong tòa nhà này không thể hút thuốc.','この建物の中では_____を吸えません。','たばこ',1,'たばこを吸う.'),
 ('たばこ',3,'business','たばこは指定された場所でお願いします。','Vui lòng chỉ hút thuốc ở nơi quy định.','_____は指定された場所でお願いします。','たばこ',2,'Cách nhắc lịch sự về khu vực hút thuốc.'),
 ('チョコレート',1,'exam','妹にチョコレートを一箱あげました。','Tôi đã cho em gái một hộp sô-cô-la.','妹に_____を一箱あげました。','チョコレート',1,'Đếm hộp dùng 箱.'),
 ('チョコレート',3,'business','受付にお土産のチョコレートを置きました。','Tôi đã để sô-cô-la quà tặng ở quầy lễ tân.','受付にお土産の_____を置きました。','チョコレート',2,'お土産の + món quà.'),
 ('パン',1,'exam','駅の近くの店で焼きたてのパンを買いました。','Tôi mua bánh mì mới nướng ở tiệm gần ga.','駅の近くの店で焼きたての_____を買いました。','パン',1,'焼きたてのパン là bánh mì mới nướng.'),
 ('パン',3,'business','朝の研修用にパンを人数分注文しました。','Tôi đã đặt đủ bánh mì theo số người cho buổi đào tạo sáng.','朝の研修用に_____を人数分注文しました。','パン',2,'人数分 là phần đủ theo số người.'),
 ('ビール',1,'exam','暑い日に冷たいビールを飲みました。','Tôi đã uống bia lạnh vào ngày nóng.','暑い日に冷たい_____を飲みました。','ビール',1,'冷たい bổ nghĩa cho đồ uống.'),
 ('ビール',3,'business','懇親会のためにビールを用意しました。','Tôi đã chuẩn bị bia cho buổi giao lưu.','懇親会のために_____を用意しました。','ビール',2,'Nのために用意する.'),
 ('メール',1,'exam','先生から届いたメールを読みました。','Tôi đã đọc email nhận được từ giáo viên.','先生から届いた_____を読みました。','メール',1,'Người gửi đi với から.'),
 ('メール',3,'business','添付資料を確認してからメールを返信します。','Tôi sẽ kiểm tra tài liệu đính kèm rồi trả lời email.','添付資料を確認してから_____を返信します。','メール',2,'メールを返信する.'),
 ('レポート',1,'exam','来週までに環境についてのレポートを出します。','Tôi sẽ nộp báo cáo về môi trường trước tuần sau.','来週までに環境についての_____を出します。','レポート',2,'Nについてのレポート.'),
 ('レポート',3,'business','不具合の原因をレポートにまとめました。','Tôi đã tổng hợp nguyên nhân lỗi vào báo cáo.','不具合の原因を_____にまとめました。','レポート',2,'Nをレポートにまとめる.'),
 ('ワイン',1,'exam','この料理には赤いワインが合います。','Rượu vang đỏ hợp với món này.','この料理には赤い_____が合います。','ワイン',2,'Nに合う là hợp với N.'),
 ('ワイン',3,'business','会食で地元のワインが出ました。','Trong bữa tiếp khách có phục vụ vang địa phương.','会食で地元の_____が出ました。','ワイン',2,'会食でNが出る.'),
 ('卵',1,'exam','朝ご飯に卵を二つ食べました。','Tôi đã ăn hai quả trứng vào bữa sáng.','朝ご飯に_____を二つ食べました。','卵',1,'Đếm vật nhỏ dùng つ.'),
 ('卵',3,'business','この商品に卵が入っているか確認してください。','Vui lòng kiểm tra sản phẩm này có trứng không.','この商品に_____が入っているか確認してください。','卵',2,'Nが入っているか hỏi thành phần.'),
 ('手紙',1,'exam','国の家族から長い手紙が届きました。','Một bức thư dài từ gia đình ở quê đã tới.','国の家族から長い_____が届きました。','手紙',1,'Người gửi đi với から.'),
 ('手紙',3,'business','お礼の手紙を取引先へ送りました。','Tôi đã gửi thư cảm ơn tới đối tác.','お礼の_____を取引先へ送りました。','手紙',2,'お礼の手紙 là thư cảm ơn.'),
 ('果物',1,'exam','毎朝、新鮮な果物を食べています。','Mỗi sáng tôi ăn trái cây tươi.','毎朝、新鮮な_____を食べています。','果物',1,'新鮮な + thực phẩm.'),
 ('果物',3,'business','休憩室に差し入れの果物があります。','Trong phòng nghỉ có trái cây được biếu.','休憩室に差し入れの_____があります。','果物',2,'差し入れ là đồ mang tặng nơi làm việc.'),
 ('水',1,'exam','運動した後で水をたくさん飲みました。','Sau khi vận động tôi uống nhiều nước.','運動した後で_____をたくさん飲みました。','水',1,'水を飲む.'),
 ('水',3,'business','機械に水がかからないようにしてください。','Hãy tránh để nước bắn vào máy.','機械に_____がかからないようにしてください。','水',2,'Nに水がかかる.'),
 ('牛肉',1,'exam','このカレーには牛肉が入っています。','Món cà ri này có thịt bò.','このカレーには_____が入っています。','牛肉',1,'Thành phần đi với が入っている.'),
 ('牛肉',3,'business','海外向け商品の牛肉の産地を確認しました。','Tôi đã xác nhận xuất xứ thịt bò của sản phẩm xuất khẩu.','海外向け商品の_____の産地を確認しました。','牛肉',3,'Nの産地 là xuất xứ của N.'),
 ('肉',1,'exam','肉と野菜を一緒に炒めます。','Tôi xào thịt và rau cùng nhau.','_____と野菜を一緒に炒めます。','肉',1,'と nối hai nguyên liệu.'),
 ('肉',3,'business','肉は冷蔵庫で保存してください。','Vui lòng bảo quản thịt trong tủ lạnh.','_____は冷蔵庫で保存してください。','肉',2,'Nを/は冷蔵庫で保存する.'),
 ('薬',1,'exam','この薬は食事の後に飲んでください。','Vui lòng uống thuốc này sau bữa ăn.','この_____は食事の後に飲んでください。','薬',1,'薬を飲む, không dùng 食べる.'),
 ('薬',3,'business','会社の救急箱に必要な薬を補充しました。','Tôi đã bổ sung thuốc cần thiết vào hộp sơ cứu công ty.','会社の救急箱に必要な_____を補充しました。','薬',2,'薬を補充する.'),
 ('野菜',1,'exam','健康のために野菜を毎日食べています。','Vì sức khỏe tôi ăn rau mỗi ngày.','健康のために_____を毎日食べています。','野菜',1,'Nのために chỉ mục đích/lý do.'),
 ('野菜',3,'business','社員食堂では地元の野菜を使っています。','Nhà ăn nhân viên sử dụng rau địa phương.','社員食堂では地元の_____を使っています。','野菜',2,'Nを使う.'),
 ('魚',1,'exam','市場で新鮮な魚を三匹買いました。','Tôi mua ba con cá tươi ở chợ.','市場で新鮮な_____を三匹買いました。','魚',1,'Đếm động vật nhỏ dùng 匹.'),
 ('魚',3,'business','今日の定食は焼いた魚です。','Suất ăn hôm nay là cá nướng.','今日の定食は焼いた_____です。','魚',2,'Mệnh đề 焼いた bổ nghĩa cho 魚.'),
 ('「写真を」撮る',1,'exam','この美術館では写真を撮ってはいけません。','Không được chụp ảnh trong bảo tàng này.','この美術館では写真を_____はいけません。','撮って',2,'撮る → 撮って; Vてはいけない.'),
 ('「写真を」撮る',3,'business','完成した製品の写真を撮って記録します。','Tôi chụp ảnh sản phẩm hoàn thiện để lưu hồ sơ.','完成した製品の写真を_____記録します。','撮って',2,'Vて nối hai hành động.'),
 ('いつも',1,'exam','姉はいつも七時に家を出ます。','Chị tôi luôn ra khỏi nhà lúc 7 giờ.','姉は_____七時に家を出ます。','いつも',1,'いつも đứng trước thói quen.'),
 ('いつも',3,'business','この機械はいつも同じ温度に設定します。','Máy này luôn được cài cùng một nhiệt độ.','この機械は_____同じ温度に設定します。','いつも',2,'いつも chỉ quy trình lặp lại.'),
 ('お正月',1,'exam','お正月には神社へ行く人が多いです。','Dịp năm mới có nhiều người đi đền.','_____には神社へ行く人が多いです。','お正月',1,'Dịp thời gian có thể đi với には.'),
 ('お正月',3,'business','お正月休みの日程を全員に連絡しました。','Tôi đã thông báo lịch nghỉ Tết cho mọi người.','_____休みの日程を全員に連絡しました。','お正月',2,'お正月休み là kỳ nghỉ năm mới.'),
 ('お花見',1,'exam','春になると家族でお花見をします。','Đến mùa xuân, gia đình tôi đi ngắm hoa.','春になると家族で_____をします。','お花見',1,'お花見をする.'),
 ('お花見',3,'business','部署のお花見は来週の土曜日です。','Buổi ngắm hoa của phòng ban vào thứ Bảy tuần sau.','部署の_____は来週の土曜日です。','お花見',2,'部署のお花見 là hoạt động tập thể.'),
 ('カフェ',1,'exam','駅前のカフェで友達を待ちました。','Tôi đã đợi bạn ở quán cà phê trước ga.','駅前の_____で友達を待ちました。','カフェ',1,'Nơi chờ đi với で.'),
 ('カフェ',3,'business','お客様と会社近くのカフェで打ち合わせました。','Tôi đã trao đổi với khách ở quán gần công ty.','お客様と会社近くの_____で打ち合わせました。','カフェ',2,'Nơi họp đi với で.'),
 ('コメント',1,'exam','先生が作文にコメントを書いてくれました。','Giáo viên đã viết nhận xét vào bài văn cho tôi.','先生が作文に_____を書いてくれました。','コメント',1,'Nにコメントを書く.'),
 ('コメント',3,'business','資料へのコメントを明日までにお願いします。','Vui lòng gửi ý kiến về tài liệu trước ngày mai.','資料への_____を明日までにお願いします。','コメント',2,'Nへのコメント.'),
 ('サッカー',1,'exam','弟は学校のチームでサッカーをしています。','Em trai tôi chơi bóng đá trong đội trường.','弟は学校のチームで_____をしています。','サッカー',1,'サッカーをする.'),
 ('サッカー',3,'business','会社のサッカー部に新入社員が入りました。','Nhân viên mới đã vào câu lạc bộ bóng đá công ty.','会社の_____部に新入社員が入りました。','サッカー',2,'サッカー部 là câu lạc bộ bóng đá.'),
 ('する',1,'exam','寝る前に歯を磨いて、宿題をします。','Trước khi ngủ tôi đánh răng và làm bài tập.','寝る前に歯を磨いて、宿題を_____。','します',1,'する → します.'),
 ('する',3,'business','午後から設備の点検をします。','Từ chiều tôi sẽ kiểm tra thiết bị.','午後から設備の点検を_____。','します',2,'Danh từ hành động + をする.'),
 ('ちょっと',1,'exam','この荷物はちょっと重いです。','Hành lý này hơi nặng.','この荷物は_____重いです。','ちょっと',1,'ちょっと làm nhẹ mức độ.'),
 ('ちょっと',3,'business','今はちょっと手が離せません。','Bây giờ tôi hơi bận tay.','今は_____手が離せません。','ちょっと',2,'Cách từ chối mềm trong công việc.'),
 ('テニス',1,'exam','日曜日に公園でテニスをしました。','Chủ Nhật tôi chơi quần vợt ở công viên.','日曜日に公園で_____をしました。','テニス',1,'テニスをする.'),
 ('テニス',3,'business','取引先とのテニス会に参加しました。','Tôi đã tham gia buổi chơi tennis với đối tác.','取引先との_____会に参加しました。','テニス',2,'N会に参加する.'),
 ('みんなで',1,'exam','旅行の写真をみんなで見ました。','Mọi người đã cùng xem ảnh chuyến đi.','旅行の写真を_____見ました。','みんなで',1,'みんなで chỉ cả nhóm cùng làm.'),
 ('みんなで',3,'business','問題の原因をみんなで考えましょう。','Chúng ta hãy cùng nhau suy nghĩ nguyên nhân vấn đề.','問題の原因を_____考えましょう。','みんなで',2,'Vましょう là cùng đề nghị.'),
 ('レストラン',1,'exam','予約したレストランは駅の近くです。','Nhà hàng đã đặt ở gần ga.','予約した_____は駅の近くです。','レストラン',1,'Mệnh đề bổ nghĩa cho レストラン.'),
 ('レストラン',3,'business','会食のレストランを三軒比較しました。','Tôi đã so sánh ba nhà hàng cho bữa tiếp khách.','会食の_____を三軒比較しました。','レストラン',2,'Đếm cửa hàng/nhà hàng dùng 軒.'),
 ('一緒に',1,'exam','放課後、友達と一緒に図書館へ行きました。','Sau giờ học tôi cùng bạn đi thư viện.','放課後、友達と_____図書館へ行きました。','一緒に',1,'人と一緒に.'),
 ('一緒に',3,'business','この資料を一緒に確認していただけますか。','Anh/chị có thể cùng tôi kiểm tra tài liệu này không?','この資料を_____確認していただけますか。','一緒に',2,'Vていただけますか là yêu cầu lịch sự.'),
 ('会う',1,'exam','駅で十年ぶりに友達に会いました。','Tôi gặp lại bạn ở ga sau mười năm.','駅で十年ぶりに友達に_____。','会いました',1,'Người gặp đi với に.'),
 ('会う',3,'business','明日、取引先の担当者に会う予定です。','Ngày mai tôi dự định gặp người phụ trách bên đối tác.','明日、取引先の担当者に_____予定です。','会う',2,'人に会う予定.'),
 ('何',1,'exam','箱の中に何が入っていますか。','Trong hộp có gì?','箱の中に_____が入っていますか。','何',1,'何が hỏi chủ thể/vật bên trong.'),
 ('何',3,'business','不具合の原因は何か調べています。','Chúng tôi đang tìm hiểu nguyên nhân lỗi là gì.','不具合の原因は_____か調べています。','何',2,'何か trong câu hỏi gián tiếp.'),
 ('写真',1,'exam','机の上に家族の写真が飾ってあります。','Trên bàn có trưng ảnh gia đình.','机の上に家族の_____が飾ってあります。','写真',1,'写真が飾ってある.'),
 ('写真',3,'business','作業前と作業後の写真を報告書に入れました。','Tôi đã đưa ảnh trước và sau công việc vào báo cáo.','作業前と作業後の_____を報告書に入れました。','写真',2,'Nの写真を報告書に入れる.'),
 ('吸う',1,'exam','ここは禁煙ですから、たばこを吸わないでください。','Ở đây cấm hút thuốc nên vui lòng không hút.','ここは禁煙ですから、たばこを_____ください。','吸わないで',2,'吸う → 吸わないで.'),
 ('吸う',3,'business','工場の中ではたばこを吸うことができません。','Không thể hút thuốc trong nhà máy.','工場の中ではたばこを_____ことができません。','吸う',2,'Vることができる.'),
 ('宿題',1,'exam','宿題を忘れたので、先生に謝りました。','Vì quên bài tập nên tôi đã xin lỗi giáo viên.','_____を忘れたので、先生に謝りました。','宿題',1,'Nを忘れる.'),
 ('宿題',3,'business','研修の宿題として改善案を考えます。','Tôi sẽ nghĩ phương án cải tiến như bài tập của khóa đào tạo.','研修の_____として改善案を考えます。','宿題',2,'Nとして là với tư cách N.'),
 ('店',1,'exam','この店では新鮮な魚を売っています。','Cửa hàng này bán cá tươi.','この_____では新鮮な魚を売っています。','店',1,'店では nêu nơi hoạt động.'),
 ('店',3,'business','会食に使う店を予約しました。','Tôi đã đặt nhà hàng dùng cho bữa tiếp khách.','会食に使う_____を予約しました。','店',2,'Mệnh đề bổ nghĩa cho 店.'),
 ('庭',1,'exam','祖父は庭で野菜を育てています。','Ông tôi trồng rau trong vườn.','祖父は_____で野菜を育てています。','庭',1,'Nơi hoạt động đi với で.'),
 ('庭',3,'business','会社の庭を毎週清掃しています。','Khu vườn công ty được dọn mỗi tuần.','会社の_____を毎週清掃しています。','庭',2,'会社の庭.'),
 ('映画',1,'exam','昨日見た映画の題名を忘れました。','Tôi quên tên bộ phim đã xem hôm qua.','昨日見た_____の題名を忘れました。','映画',1,'Mệnh đề bổ nghĩa cho 映画.'),
 ('映画',3,'business','研修で安全についての映画を見ました。','Trong đào tạo chúng tôi xem phim về an toàn.','研修で安全についての_____を見ました。','映画',2,'Nについての映画.'),
 ('時々',1,'exam','父は時々自転車で会社へ行きます。','Bố tôi thỉnh thoảng đi làm bằng xe đạp.','父は_____自転車で会社へ行きます。','時々',1,'時々 chỉ tần suất không đều.'),
 ('時々',3,'business','この装置は時々大きな音がします。','Thiết bị này thỉnh thoảng phát ra tiếng lớn.','この装置は_____大きな音がします。','時々',2,'時々 + hiện tượng.'),
 ('書く',1,'exam','答えを鉛筆で書いてください。','Vui lòng viết đáp án bằng bút chì.','答えを鉛筆で_____ください。','書いて',1,'Dụng cụ đi với で.'),
 ('書く',3,'business','点検結果を報告書に書きました。','Tôi đã viết kết quả kiểm tra vào báo cáo.','点検結果を報告書に_____。','書きました',2,'Nを tài liệuに書く.'),
 ('聞く',1,'exam','分からない言葉を先生に聞きました。','Tôi hỏi giáo viên từ không hiểu.','分からない言葉を先生に_____。','聞きました',1,'聞く có nghĩa hỏi khi đi với 人に.'),
 ('聞く',3,'business','現場の状況を担当者に聞いてください。','Vui lòng hỏi người phụ trách về tình hình hiện trường.','現場の状況を担当者に_____ください。','聞いて',2,'Nを人に聞く.'),
 ('見る',1,'exam','窓から海を見ることができます。','Có thể nhìn thấy biển từ cửa sổ.','窓から海を_____ことができます。','見る',1,'Vることができる.'),
 ('見る',3,'business','送信前に資料をもう一度見てください。','Vui lòng xem lại tài liệu trước khi gửi.','送信前に資料をもう一度_____ください。','見て',2,'見る → 見てください.'),
 ('読む',1,'exam','寝る前に本を三十ページ読みました。','Trước khi ngủ tôi đọc 30 trang sách.','寝る前に本を三十ページ_____。','読みました',1,'読む → 読みました.'),
 ('読む',3,'business','契約書をよく読んでから署名してください。','Hãy đọc kỹ hợp đồng rồi ký.','契約書をよく_____から署名してください。','読んで',2,'読む → 読んでから.'),
 ('買う',1,'exam','誕生日に母へ花を買いました。','Tôi đã mua hoa tặng mẹ vào sinh nhật.','誕生日に母へ花を_____。','買いました',1,'買う → 買いました.'),
 ('買う',3,'business','必要な部品をオンラインで買いました。','Tôi đã mua linh kiện cần thiết trực tuyến.','必要な部品をオンラインで_____。','買いました',2,'Nを買う; phương thức đi với で.'),
 ('音楽',1,'exam','勉強するときは静かな音楽を聞きます。','Khi học tôi nghe nhạc nhẹ.','勉強するときは静かな_____を聞きます。','音楽',1,'音楽を聞く.'),
 ('音楽',3,'business','店内で流す音楽の音量を下げました。','Tôi đã giảm âm lượng nhạc phát trong cửa hàng.','店内で流す_____の音量を下げました。','音楽',2,'音楽の音量.'),
 ('食べる',1,'exam','この魚は骨が多くて食べにくいです。','Cá này nhiều xương nên khó ăn.','この魚は骨が多くて_____にくいです。','食べ',2,'Bỏ ます + にくい: 食べにくい.'),
 ('食べる',3,'business','会議が始まる前に昼食を食べてください。','Vui lòng ăn trưa trước khi cuộc họp bắt đầu.','会議が始まる前に昼食を_____ください。','食べて',2,'食べる → 食べてください.'),
 ('食事する',1,'exam','家族と食事しながら旅行の話をしました。','Tôi vừa ăn cùng gia đình vừa nói chuyện chuyến đi.','家族と_____ながら旅行の話をしました。','食事し',2,'Bỏ ます + ながら: 食事しながら.'),
 ('食事する',3,'business','お客様と食事する店を予約しました。','Tôi đã đặt nhà hàng dùng bữa với khách.','お客様と_____店を予約しました。','食事する',2,'Mệnh đề bổ nghĩa cho 店.'),
 ('飲む',1,'exam','頭が痛かったので、薬を飲みました。','Vì đau đầu nên tôi đã uống thuốc.','頭が痛かったので、薬を_____。','飲みました',1,'薬を飲む.'),
 ('飲む',3,'business','暑い現場では定期的に水を飲んでください。','Ở công trường nóng hãy uống nước định kỳ.','暑い現場では定期的に水を_____ください。','飲んで',2,'飲む → 飲んでください.' )
)
insert into public.jp_vocab_examples
 (vocab_id,example_no,example_type,example_jp,example_vi,cloze_jp,answer,difficulty,focus_note,source_type)
select v.id,c.example_no,c.example_type,c.example_jp,c.example_vi,c.cloze_jp,c.answer,c.difficulty,c.focus_note,'generated'
from curated c join public.jp_vocab v on v.level='N5' and v.lesson_no=7 and v.word_jp=c.word_jp
on conflict (vocab_id,example_no) do update set
 example_type=excluded.example_type,example_jp=excluded.example_jp,example_vi=excluded.example_vi,
 cloze_jp=excluded.cloze_jp,answer=excluded.answer,difficulty=excluded.difficulty,
 focus_note=excluded.focus_note,source_type=excluded.source_type;
